### ISSUE TITLE
consider adding SelenideElement execute(Command<Void> command);

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#1000]
In 5.3.0 we added custom commands execution. 
the `execute` method accept only `Command<SelenideElement>`...
Yet, even native Selenide Click command is of type: `Command<Void>`... Hence, it would be natural and consistent to allow users to define their "void" commands and pass to the `execute` method...

**Comment by asolntsev** [comment]
I was also thinking about it.
But it seemed to be useless, because `$.execute()` is mostly useful when chained with other commands. If you have just one `void` method, you can just call that method directly.

**Comment by yashaka** [comment]
We also have native commands in Selenide that are of `Command<WebElement>` type...
So probably... we would need to be able to pass such commands to the execute method...

Maybe even it would be better originally allowing any Command<T> to be accepted by the execute command... And making it return "this" selenideelement in any case...

**Comment by yashaka** [comment]
@asolntsev 
you can accept any Command<T> type, but return "this" selenideelement always... yet keeping it "chainable"

**Comment by yashaka** [comment]
By the way... probably execute is uesfull not just for chaining...
this ability in Selenide is useful because you have an ability to define your custom command and not just call it separately but call it under the hood of same "waiting" logic that is available in native SelenideElement implementation

**Comment by yashaka** [comment]
> BTW, probably it would be a good idea to convert method $.click() to non-void.

often this will be a workaround... 
For example... my custom command is supposed to return same "this" SelenideElement...
But I can't implement such command (correct me If I am wrong...), because inside Command<SelenideElement> implementation I have no access to "this" SelenideElement... 
So I will have to return "null" just to match the signature... 
I can also create new SelenideElement based on the webelement that I have... But then this will be a cached version of SelenideElement, that I also will not want in all scenarios...

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/1001
