### ISSUE TITLE
Add an option for mobile emulation

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1008]
## The problem
We often want to open browser in "mobile emulation" mode. 
We would like to have an option in Selenide to do it easily. 

## Details
Currently we have to implement own `WebdriverProvider` to add this option:

```java
  Map<String, String> mobileEmulation = new HashMap<>();
  mobileEmulation.put("deviceName", "Nexus 5");
  ChromeOptions chromeOptions = new ChromeOptions();
  chromeOptions.setExperimentalOption("mobileEmulation", mobileEmulation);
```

See https://chromedriver.chromium.org/mobile-emulation

**Comment by osyanin** [comment]
I think it could help to automate mobile browsing without android or ios emulation.

**Comment by rosolko** [comment]
@asolntsev Not sure about this. Related to documentation we have a lot of configuration parameters and we can't implement them all. And based on different needs of each user it will be better to initialize driver for this case using custom driver provider.

**Comment by SergeyPirogov** [comment]
@asolntsev +1 for @rosolko

**Comment by vinogradoff** [comment]
It is a very typical case, why not to make the life of Selenide user easier.

**Comment by asolntsev** [comment]
@rosolko we are not talking about Android or iOS emulators etc. We are only talking about browser mode which runs "like in mobile". Like if you want to open site https://selenide.org in mobile. 

It's often needed, and it only requires one property `"deviceName", "Nexus 5"`.

**Comment by vinogradoff** [comment]
It looks to me to be a good idea to make only one property. Perhaps with naming emulationDeviceName (or similar) to make the idea of property clear through naming.

It is even possible to make it without any new property, putting the name to existing browser property (and adding some logic to handle the cases: 1) browser 2) classname of webdriver 3) emulated mobile devices). But I am not sure if it is a good idea.

**Comment by rosolko** [comment]
@asolntsev But stick with `"deviceName", "Nexus 5"` is also not a good idea. A lot of mobile devices available for select with different screen resolution and aspect ratio and also tables there

**Comment by osyanin** [comment]
> @rosolko we are not talking about Android or iOS emulators etc. We are only talking about browser mode which runs "like in mobile". Like if you want to open site https://selenide.org in mobile.
> 
> It's often needed, and it only requires one property `"deviceName", "Nexus 5"`.

There is a really much variants to choose in default.
You are can look at them in developer mode, enabling mobile view. 
Then you can choose a device, or set custom device with name, resolution, pixel ratio, user agent string, mobile with/without touch or desktop with-without touch

**Comment by vinogradoff** [comment]
@rosolko "Nexus 5" and "deviceNamd" is just an example, I guess. No defaults, name as a String without verifications

**Comment by rosolko** [comment]
@vinogradoff So, instead of one config parameter such as `headless` you should pass a lot of for device name and additional - resolution, ration and touch simulation for example. So isn't it simpler to use custom driver provider for this case?

**Comment by vinogradoff** [comment]
@rosolko - no, just one parameter - name of the device. Each device hat its resolution and ratio already. I am writing emulation tests, only single parameter (name of the device) is enough for all my cases.

**Comment by rosolko** [comment]
@vinogradoff If you leave only one `deviceName` parameter you have to create and maintain in a future list of allowed paramenters. And solution is going to be non-generic but hardcoded. We already has such problem - webdrivermanager with browser-driver map that required non-stop maintain.

**Comment by vinogradoff** [comment]
@rosolko of course not, Chrome can  add/remove/rename the device names at any time. Chrome already did it multiple times. So it should be just a String. If the given deviceName is not supported by chrome driver it delivers (already does) the readable error message - so no problem for the user to understand where is the problem.

**Comment by vinogradoff** [comment]
example code would be

```
Configuration.emulationDeviceName="Nexus 5"; // works
Configuration.emulationDeviceName="Nexus V"; // readable error message at open();
```
Or even (reusing browser parameter):

`Configuration.browser="Nexus 5"; // works`

**Comment by rosolko** [comment]
How are you going to identify in this case `Configuration.browser="Nexus 5";` that it's chrome and mobile emulation?
This case `Configuration.emulationDeviceName="Nexus 5";` we can handle it as `remote` parameter, agree

**Comment by vinogradoff** [comment]
@rosolko as stated above - I'm not sure if it is a good idea to reuse browser.

But technically it is possible now, because only chrome supports mobile emulation. But it is probably the reason not to reuse "browser", because if Firefox start supporting it on there own, then it will become difficult to handle.

**Comment by rosolko** [comment]
It's a strong reason to no implement this at all.
Unfortunately I don't change my mind - still down-vote for this changes.

**Comment by vinogradoff** [comment]
Could you elaborate, what is the strong reason not to implement it?

**Comment by osyanin** [comment]
Honestly, Firefox supports emulation, but has it's own device list.

**Comment by osyanin** [comment]
`Configuration.browser="Firefox";` // works 
`Configuration.emulationDeviceName="Galaxy S9/S9+";` // works
emulationDeviceName default = null. No emulation.
If set, it checks browser for device list, and compares it's value with that list. 
If not founds, prints readable error.

Maybe additional: 
`Configuration.addEmulatedMobileProfile.name="Galaxy S9/S9+ (Custom)"`
`Configuration.addEmulatedMobileProfile.name="Mozilla/5.0 (Linux; Android 7.0; SM-G892A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36"`
`Configuration.addEmulatedMobileProfile.size="360x740"`
`Configuration.addEmulatedMobileProfile.devicePixelRatio=4`
`Configuration.addEmulatedMobileProfile.touchScreen=true/false`

**Comment by rosolko** [comment]
@osyanin What for do we need to support a ton of configuration parameters instead of custom driver?

**Comment by osyanin** [comment]
No no, not support parameters by itself. 
Only search them if webdriver allows it. Not save some hardcode in library itself.

**Comment by rosolko** [comment]
Based on your description we have to at least list all of this params on config to process them later
```
Configuration.addEmulatedMobileProfile.name="Galaxy S9/S9+ (Custom)"
Configuration.addEmulatedMobileProfile.name="UserAgentString"
Configuration.addEmulatedMobileProfile.size="360x740"
Configuration.addEmulatedMobileProfile.devicePixelRatio=4
Configuration.addEmulatedMobileProfile.touchScreen=true/false

**Comment by vinogradoff** [comment]
Actually I described the opposite. On our project the use of just one setting for typical phone like iPhone, Galaxy, Nexus was enough. My guess is that it is the case for the vast majority of the mobile emulation users of Selenium/Selenide. I don't share the implication that we *must* support every other option too. 

If you can explain your choice of the word *must*?

**Comment by BorisOsipov** [comment]
My two cents. I agree with @rosolko @SergeyPirogov - we should sum up its pros and cons before implementing this and do it carefully.

>My guess is that it is the case for the vast majority of the mobile emulation

assumption without proofs. I had different case - we need some specific device settings just because customer wants(some specific tablet devices)

>I don't share the implication that we must support every other option too.

But user indeed will want. Some time later we will have issues like "we want configure optionName by selenide config, not only general device name" just because users don't care about thousands options in selenide config.

I still don't understand what is the most difficult piece in writting custom webdriver provider to implement mobile emulation with any options you want. If there are, maybe it will be better to share some examples in wiki\docs to help users then?

p.s. also `deviceName` will confuse with appium options if i am not mistaken.

**Comment by asolntsev** [comment]
I have another idea. 
1. Currently we support such a system property: `-Dchromeoptions.args=--diagnostics,--disable-blink-features`.
2. We could also support similar system property: `"-Dchromeoptions.mobileEmulation=deviceName=Nexus 5"`

In this case user will be able to set up any settings for mobile browser without need to change Selenide source.

**Comment by vinogradoff** [comment]
@asolntsev this would be quite acceptable for my case

**Comment by asolntsev** [comment]
done in PR #1011
