### ISSUE TITLE
improve error message when after condition failed, yet we fail to describe the element properly...

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#1013]
given `element.shouldNot(exist)`
and config timeout is 4s
when element still exist after 4s
and should start to fail...
and we start to build error message, and start to "print element"
and here, actually element disappears from DOM, and we fail to print it... 
then we have an error message like:

```
Element should not exist {By.id: com.ivia:id/submit}
Element: 'StaleElementReferenceException: The element 'By.id: com.ivia:id/submit' does not exist in DOM anymore'
```

but probably we should have something like:

```
Element should not exist {By.id: com.ivia:id/submit}
Element: ups, we failed to print an element becuase of: 'StaleElementReferenceException: The element 'By.id: com.ivia:id/submit' does not exist in DOM anymore'
```

"ups, we failed to print an element becuase of:" can be changed to something more adequate... ;)

**Comment by asolntsev** [comment]
Fixed by https://github.com/selenide/selenide/pull/1239
