### ISSUE TITLE
$.getWrappedElement() should not wait for timeout if element does not exist

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#1015]
the subj method is implemented based on the command: 

```
public class ToWebElement implements Command<WebElement> {
  @Override
  public WebElement execute(SelenideElement proxy, WebElementSource locator, Object[] args) {
    return locator.getWebElement();
  }
}
```

this command will fail if element does not exist... 
and will be retried inside "the only one logic of SelenideElementProxy invocation of all commands":

```
class SelenideElementProxy implements InvocationHandler {
//...

  @Override
  public Object invoke(Object proxy, Method method, Object... args) throws Throwable {
    if (methodsToSkipLogging.contains(method.getName()))
      return Commands.getInstance().execute(proxy, webElementSource, method.getName(), args);

    validateAssertionMode(config());

    long timeoutMs = getTimeoutMs(method, args);
    long pollingIntervalMs = getPollingIntervalMs(method, args);
    SelenideLog log = SelenideLogger.beginStep(webElementSource.getSearchCriteria(), method.getName(), args);
    try {
      Object result = dispatchAndRetry(timeoutMs, pollingIntervalMs, proxy, method, args);
      SelenideLogger.commitStep(log, PASS);
      return result;
    }
    catch (Error error) {
      Error wrappedError = UIAssertionError.wrap(driver(), error, timeoutMs);
      SelenideLogger.commitStep(log, wrappedError);
      if (config().assertionMode() == SOFT && methodsForSoftAssertion.contains(method.getName()))
        return proxy;
      else
        throw wrappedError;
    }
    catch (RuntimeException error) {
      SelenideLogger.commitStep(log, error);
      throw error;
    }
  }
// ...
}
```

but it should not... We should have a raw interface to original Selenium WebDriver WebElement without any waiting logic...

**Comment by BorisOsipov** [comment]
Will better to create new method if it needs, because changing current will be breaking change that will not be easy to find and fix.

Also I am not sure about this idea... you need element but you are ready to recieve NoSuchElementEx instead.. for what?

**Comment by yashaka** [comment]
I am not sure this "breaking change" will affect a lot of users...
If somebody uses "webelement" he is using it in rare cases, I probably they would expect element not to wait. Otherwise they would use SelenideElement as it is...

Also, this method was almost all the time in Selenide, and in the past it was without waiting logic... So I would say - this is really a bug, not something that people got used to, and now we are going to break it... 

The idea is to have an ability to get a raw interface to webelement from Selenide. This might be needed for implementing some extensions on top of Selenide in the cases where Selenide lacks something... For example right now I am extending Selenide in context of Mobile Automation, and in some cases I need this "raw" interface to WebElement...

**Comment by yashaka** [comment]
For example, I need this toWebElement to fail at the moment of call to identify this failure as a false feedback in context of implementing custom conditions in context of mobile automation

**Comment by BorisOsipov** [comment]
>If somebody uses "webelement" he is using it in rare cases, and probably they would expect webelement not to wait.

Unfortunately, it is not true. I've seen a lot of cases when people use toWebelement to pass use weblement directly. Mostly they try to cheat selenide to avoid "Element is not visible" exception or smth else. And removing waiting will affect them.

>Also, this method was almost all the time in Selenide, and in the past it was without waiting logic

It is interesting. I agree it is a bug. Will see how long is it.

**Comment by BorisOsipov** [comment]
>Also, this method was almost all the time in Selenide, and in the past it was without waiting logic

I checked. toWebElement is implemented by command since at least 2015... I didn't go deeper. So I assume it was with waiting originally

**Comment by yashaka** [comment]
I am afraid, you missed something... Just did not check deep enough... 
Look at this state on 1/11/2015, this is a class that implements waiting logic, it defines two methods: getDelegate that waits and getActualDelegate that does not wait:
![image](https://user-images.githubusercontent.com/1961118/68851808-4139c480-06df-11ea-8b3d-d6e845b3cc7a.png)

Then all selenide methods are based on calling either getDelegate (if they need to wait) or getActualDelegate (if they do not want to wait). Now look at how toWebElement is defined:
![image](https://user-images.githubusercontent.com/1961118/68852063-d046dc80-06df-11ea-9820-bd7036248139.png)
Same as getWrappedWebElement by the way:
![image](https://user-images.githubusercontent.com/1961118/68852113-ea80ba80-06df-11ea-829a-b29d6beb44b5.png)

And here is an example of method that needs to wait:
```
    else if ("pressEnter".equals(method.getName())) {
      getDelegate().sendKeys(Keys.ENTER);
      return proxy;
    }
```

As you can see, in the past toWebElement was implemented without waiting explicitly. This was an original intent to provide an access to the raw webelement, so called "actual delegate" without any "selenide magic". 

Then, after refactoring, the bug was introduced :( Seems like it happened even earlier than moving to Command pattern.

**Comment by yashaka** [comment]
> Unfortunately, it is not true. I've seen a lot of cases when people use toWebelement to pass use weblement directly. Mostly they try to cheat selenide to avoid "Element is not visible" exception or smth else. And removing waiting will affect them.

I am sure somebody will find a way to use a selenide in a crazy way:) But I would not keep API adapted for those "crazy things":) Especially if it is a bug, and if logically it's not natural to have such implementation...

Yet we can discuss the "natural" behaviour... And if we find that old behaviour is unnatural, I would vote for a breaking change... Maybe though in a next increment of main number in versioning... 

So... we have two methods toWebElement and getWrappedElement ...
Both originally did not have waiting logic... 

And at least getWrappedElement - should always return wrapped entity as it is... as in raw selenium... Because Selenide is a wrapper, and when we have some method in it that by its name tells "give me a thing that you wrapped in" - we should give it as it is... waithout waiting...

About toWebElement - I am not totally sure... The name sounds like "type convertion"... So maybe it is natural to keep an actual object with all "waiting magic" but provide it via raw WebElement interface so somebody in their code can use it for some legacy stuff... Seems like it's more natural to keep this method with waiting logic... The only thing that confuses me, is that actually for such convertion behaviour we don't need a separate method... We can just path SelenideElement to whatever accepts WebElement, because `SelenideElement extends WebElement`...

**Comment by BorisOsipov** [comment]
>I am afraid, you missed something... Just did not check deep enough...

great investigation. thank you!

>Especially if it is a bug, and if logically it's not natural to have such implementation...

Yeah I don't argue that is a bug. But old bugs become feature for users after long time :)))

Finally, we want to have two method to get WebElement - one with waiting, one without to please all, right?

>I would vote for a breaking change... Maybe though in a next increment of main number in versioning...

I'd be better to deprecate one method now, and then replace it in with next increment of main number. It will make transition more smoothly

> The only thing that confuses me, is that actually for such convertion behaviour we don't need a
> separate method... We can just path SelenideElement to whatever accepts WebElement, because > SelenideElement extends WebElement...

Yes it is. But selenide overrides original selenium methods behaviour - it is acceptable not for all.

**Comment by yashaka** [comment]
:)

Yeah, not for all - that's why they can have an api to raw webelement, completely the same way  as in raw webdriver:) for example via getWrappedElement

So... 

1
I am ok to have two methods in Selenide, one with waiting and one without... Though I would have only one, without:), and for "waiting case", I would just use `(WebElement) mySelenideElement`. But no problem, we can have two methods:)

2
I vote for having SelenideElement#getWrappedElement as the version without waiting, asap as bug fix, not waiting for next increment of main number. Or - deprecate in next minor version, and change it's behaviour in the following minor version (after next one). 

3
Regarding SelenideElement#toWebElement - I am ok to keep it as "waiting version", though I would change it's implementation to just return something like `(WebElement) proxy` just because for my taste it's more natural :)... But ok to keep it as it is... 

@asolntsev, what do you also think on all of that?

**Comment by asolntsev** [comment]
Yes, this is true:
> the original intent to provide an access to the raw webelement, so called "actual delegate" without any "selenide magic".

So I suggest to change `toWebElement()` behaviour to just return the `WebElement` without waiting. 
I am pretty sure that it was an accidental change when `toWebElement()` started waiting for the element.

If somebody needs to wait, he can write `$.shouldBe(visible).toWebElement()`. 
That's why I don't want to introduce 2 separate methods. 

P.S. Just proxying to `WebElement` may not work. For example, if I remove `.toWebElement()` from [this example](https://github.com/selenide-examples/selenide-appium/blob/master/src/test/java/org/selenide/examples/appium/AndroidDragAndDropTest.java), I get the following error:

```java
java.lang.ClassCastException: Cannot cast com.sun.proxy.$Proxy5 to org.openqa.selenium.remote.RemoteWebElement

	at java.lang.Class.cast(Class.java:3369)
	at io.appium.java_client.touch.offset.ElementOption.withElement(ElementOption.java:89)
	at io.appium.java_client.touch.offset.ElementOption.element(ElementOption.java:49)
	at org.selenide.examples.appium.AndroidDragAndDropTest.dragAndDrop(AndroidDragAndDropTest.java:34)

```

**Comment by yashaka** [comment]
I am pretty ok with the last Andrey's proposal.

**Comment by asolntsev** [comment]
@yashaka I could not reproduce the issue? Did you actually try it, or just analyzed the code? :) 

Method `toWebElement()` never waited because of `methodsToSkipLogging`:

```java
class SelenideElementProxy implements InvocationHandler {
  private static final Set<String> methodsToSkipLogging = new HashSet<>(asList(
      "toWebElement",
      "toString",
      "getSearchCriteria"
  ));

```

**Comment by yashaka** [comment]
@asolntsev, pretty fast close:-)

I tried it, and it blocked me in some way... I had to find workarounds to get an API to raw webelement... 

I will check details and come back later...

**Comment by yashaka** [comment]
@asolntsev , 
Weird... Probably originally I tried only with getWrappedElement, and that's why I saw waiting on my side... And seems like I did not pay enough attention to the difference between getWrappedElement and toWebElement... Sorry...

So, summarizing:
* toWebElement fails fast, with no waiting
* getWrappedElement waits... 

Maybe I would vote for keeping toWebElement as version with waiting and getWrappedElement as non-waiting version... Because "get..." - usually means "get it now, fast". And "to..." usually means "represent what we have now", and it's seems to natural to represent SelenideElement that is dynamic and with waiting logic in general – as WebElement with waiting...

But ok as it is...

**Comment by asolntsev** [comment]
I suggest that both methods should NOT wait. They are rather synonyms. Otherwise it's too hard to keep the difference in mind.

I don't see any reasons why someone would need the "waiting" here.

**Comment by yashaka** [comment]
Yeah, me too... Originally I was also for the idea to keep both as non-waiting... 
Let's add getWrappedElement to the list in methodsToSkipLogging

**Comment by asolntsev** [comment]
Done in https://github.com/selenide/selenide/pull/1124
