### ISSUE TITLE
Add opportunity to get screenshot from current thread via ScreenShot Laboratory

### ISSUE THREAD

**Issue by Osmyslitelny** [selenide/selenide#1029]
For https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/impl/ScreenShotLaboratory.java add opportunity to get latest or all screenshots from current thread
Something like that:
```
  public File getLastThreadScreenshot() {
      return currentContextScreenshots.isEmpty() ? null : currentContextScreenshots.get(currentContextScreenshots.size() - 1);
  }
```
or
```
  public List<File> getLastThreadScreenshot() {
      return currentContextScreenshots.isEmpty() ? null : currentContextScreenshots.get();
  }
```
or add methods for working with **currentContext** variable without remove it.
Also don't forget add some logic into https://github.com/selenide/selenide/blob/master/statics/src/main/java/com/codeborne/selenide/Screenshots.java

**Comment by dstekanov** [comment]
Hi @Osmyslitelny, thanks for your proposal. 
I just wanted to know the cases when you need it and if you still need this opportunity?

**Comment by Osmyslitelny** [comment]
I use ScreenShotLaboratory for not creating custom logic/lib/api for making screenshot. 
 have few threads that point why I work with context.
I have bdd and 1 context its 1 feature/scenario (name not very important), important moment that my context more then few lines (1 test). 1 context could include 10 test-steps. Step number 1,5 and 6 for example could work with screenshot. Every time when step 5 and six failed, my Listener invoked and I have to be sure that into report I will have last making screenshot.
Common view of listener:
`class FiledListener {
....
public void failed(String step, Throwable cause) {
     Log.error("There is step: " step.getStepNumber() + "And there is screenshot" ScreenshotHelper.getCurrentThreadLastScreenshot())
}
`
As result I'm getting page screenshot of Selenide (default logic). And I get my custom screenshot for every failed test. In common view I could work with my Context values from ScreenShotLaboratory as Context values and I dont need any extra logic for 'screenshotKeeper' for getting and setting them.
