### ISSUE TITLE
[RTC] Implement executeAsyncScript

### ISSUE THREAD

**Issue by tyge68** [selenide/selenide#1030]
## The problem
As a test implementer , I would like to test an sync method call on the browser using the webdriver .executeAsyncScript(...) method 

## Details
I couldn't find the equivalent of the .executeAsyncScript method (1) on the Selenide class. Only the non async one is available.

## Tell us about your environment
Not relevant

## Code To Reproduce Issue [ Good To Have ]
Current workaround:
JavascriptExecutor js = (JavascriptExecutor) WebDriverRunner.getWebDriver();
js.executeAsyncScript("someJavaScriptAsync(arguments[0])");

Currently I would like to have following:
Selenide.executeAsyncScript("someJavaScriptAsync(arguments[0])")

(1) https://selenium.dev/selenium/docs/api/java/org/openqa/selenium/JavascriptExecutor.html#executeAsyncScript-java.lang.String-java.lang.Object...-

**Comment by asolntsev** [comment]
Done in PR #1031
