### ISSUE TITLE
Add quotes around selectors in Selenide logger

### ISSUE THREAD

**Issue by nbdnnm** [selenide/selenide#1032]
Currently, selenide logs events the next way:
![image](https://user-images.githubusercontent.com/22072588/71561652-7b85d800-2a79-11ea-9fe5-1386eb2354a4.png)

So selectors are not wrapped by quotes as it is in code itself.

Not a big deal, but would be useful to have it in order to simply copy-paste in the next browser window and find an element.

The next code responsible for that logic:
https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/logevents/SelenideLog.java#L56
https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/logevents/SelenideLogger.java#L37-L68

@asolntsev @vinogradoff @rosolko @BorisOsipov welcome to comment

**Comment by asolntsev** [comment]
@nbdnnm We can add quotes. I don't see any problems. I also think that `$("#username")` looks better than `$(#username)`. 

P.S. But the idea of copying those lines from report and pasting into browser seems to me very strange. I hope you do not it often. ;)

**Comment by asolntsev** [comment]
done in https://github.com/selenide/selenide/pull/1092
