### ISSUE TITLE
Cannot run tests on all Windows Laptops

### ISSUE THREAD

**Issue by melinda24** [selenide/selenide#1038]
Cannot run Selenide tests on all laptops, ran on 1 but not on the other 4.  All laptops are the same.  Run in Chrome browser.  I can't provide our test codes but it can be a very simple like just open URL. It just won't navigate to the URL.  It works if you uninstall the Chrome browser.
This exception is thrown. I removed the the host and ip address that are shown you will just see empty stings or ticks: 

org.openqa.selenium.WebDriverException: unknown error: DevToolsActivePort file doesn't exist Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: '', ip: '', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_231' Driver info: driver.version: SelenideDriver
--

Thank you very much in advance for any suggestions.

**Comment by vinogradoff** [comment]
Is this all logs you get?

What is Chrome Version?
Do you start tests with maven/gradle or only from IDE?
If you are using one of the latest Selenide versions please add this dependency to gradle/maven to get more logs:

Gradle: 
```
testRuntimeOnly 'org.slf4j:slf4j-simple:1.7.28'
```
Мaven:

```xml
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-simple</artifactId>
    <version>1.7.28</version>
    <scope>test</scope>
</dependency>
```

**Comment by vinogradoff** [comment]
You definitely have problems of starting browser with Selenium WebDriver, but still there are too many possible reasons for that.

**Comment by melinda24** [comment]
We got a couple of brand new lap tops and do not have any issue I
mentioned.  We think it may be with these lap tops that has something or
not have something and decide it wasn't worth the time to look into these
old laptops and retired them.
I don't have those laptops anymore to run and get you more logs.  There
wasn't much of anything in the log except the first line.
Thank you very much for your reply.

Selenide 5.6.0
Chrome 79
Gradle

**Comment by vinogradoff** [comment]
Yes, looks okay, please add the line above in dependencies to build.gradle and restart. Then you will get a couple more lines about WebDriver version or possibly error messages explaining what is wrong with it. 
Then post them here.

There are some posts on StackOverflow about the similar problem, in most cases - it seems to be occuring when there are too little resources for opening the browser. But for hardware notebook - it must be a **very** old one or bad one for this to happen. Not one capable of running Windows 10 anyway:)

But look at these and similar posts:
https://stackoverflow.com/questions/56637973/how-to-fix-selenium-devtoolsactiveport-file-doesnt-exist-exception-in-python
https://stackoverflow.com/questions/54760863/error-unknown-error-devtoolsactiveport-file-doesnt-exist-when-executing-ruby
https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t

Anyway the problem is not in Selenide itself, but in Selenium WebDriver not able to open the browser. Post your logs and perhaps gradle.build - we can try to help if the information in posts is not enough.

**Comment by melinda24** [comment]
Thank you.

**Comment by melinda24** [comment]
Here is log, where you see X's, I intentionally replaced with the X's

org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited normally (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.) Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'xxxxxx', ip: 'xxxx', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241' Driver info: driver.version: SelenideDriver selenide.url: https://xxxxxx.com selenide.baseUrl: http://localhost:8080 remote stacktrace: Backtrace: Ordinal0 [0x0112A113+1548563] Ordinal0 [0x010ADDA1+1039777] Ordinal0 [0x0102E485+517253] Ordinal0 [0x00FBCB98+52120] Ordinal0 [0x00FDB797+178071] Ordinal0 [0x00FDB59D+177565] Ordinal0 [0x00FD95FB+169467] Ordinal0 [0x00FC160A+71178] Ordinal0 [0x00FC2690+75408] Ordinal0 [0x00FC2629+75305] Ordinal0 [0x010C71B7+1143223] GetHandleVerifier [0x011C2B46+507814] GetHandleVerifier [0x011C2864+507076] GetHandleVerifier [0x011C9F47+537511] GetHandleVerifier [0x011C3402+510050] Ordinal0 [0x010BF29C+1110684] Ordinal0 [0x010C938B+1151883] Ordinal0 [0x010C94F3+1152243] Ordinal0 [0x010C83F5+1147893] BaseThreadInitThunk [0x76318744+36] RtlGetAppContainerNamedObjectPath [0x771558ED+253] RtlGetAppContainerNamedObjectPath [0x771558BD+205] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) at java.lang.reflect.Constructor.newInstance(Unknown Source) at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62) at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30) at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126) at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) at java.util.stream.AbstractPipeline.copyInto(Unknown Source) at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) at java.util.stream.AbstractPipeline.evaluate(Unknown Source) at java.util.stream.ReferencePipeline.findFirst(Unknown Source) at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128) at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74) at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136) at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552) at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213) at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181) at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168) at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157) at com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:26) at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$1(WebDriverFactory.java:51) at java.util.Optional.map(Unknown Source) at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:51) at com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:39) at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:126) at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:120) at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:89) at com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:47) at com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:150) at com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:65) at com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:28) at com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:66) at com.codeborne.selenide.Selenide.open(Selenide.java:41) at com.shelter.test.testsystem.tests.CATestBase.startupCA(CATestBase.java:60) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134) at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63) at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348) at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302) at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:619) at org.testng.TestRunner.beforeRun(TestRunner.java:609) at org.testng.TestRunner.run(TestRunner.java:580) at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) at org.testng.SuiteRunner.run(SuiteRunner.java:286) at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187) at org.testng.TestNG.runSuitesLocally(TestNG.java:1109) at org.testng.TestNG.runSuites(TestNG.java:1039) at org.testng.TestNG.run(TestNG.java:1007) at com.shelter.test.testsystem.testhelpers.TestRunner.runTest(TestRunner.java:63) at com.shelter.test.testsystem.testhelpers.STController.handleRunTest(STController.java:350) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at sun.reflect.misc.Trampoline.invoke(Unknown Source) at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at sun.reflect.misc.MethodUtil.invoke(Unknown Source) at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1771) at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657) at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) at javafx.event.Event.fireEvent(Event.java:198) at javafx.scene.Node.fireEvent(Node.java:8411) at javafx.scene.control.Button.fire(Button.java:185) at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182) at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96) at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89) at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) at javafx.event.Event.fireEvent(Event.java:198) at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394) at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295) at java.security.AccessController.doPrivileged(Native Method) at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432) at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410) at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431) at com.sun.glass.ui.View.handleMouseEvent(View.java:555) at com.sun.glass.ui.View.notifyMouse(View.java:937) at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186) at java.lang.Thread.run(Unknown Source)

**Comment by melinda24** [comment]
I added more logs as requested in the issue.  Thank you.

**Comment by asolntsev** [comment]
@melinda24 As much as I see, this problem is not Selenide-specific. It's more like a Chromedriver issue. 
Could you please try to use plain Selenium - does the problem still reproduce?
I mean, like 
```
WebDriver driver = new ChromeDriver();
driver.navigate().to("https://google.com");
```
