### ISSUE TITLE
Clicks not reliably happening with dynamic content

### ISSUE THREAD

**Issue by ken-p** [selenide/selenide#1040]
## The problem
Conditions (like shouldBe) sometimes allow clicks to happen too soon, and often clicks get swallowed, when dealing with dynamic content

## Details
The app I'm working on has a lot of dynamic content...for example, different types of drawers that slide in and out. Intermittently, we've noticed that sometimes Selenide will try to interact with an element too soon (like while the drawer is still opening), and the result can be a swallowed click (it thinks the element was clicked on, but the page does not change), or a click on the wrong element even.

I've tried to find a public page on the internet to reproduce this, and I found something similar. It's a jquery page but I'm seeing this problem in angular pages too. See the code below.

## Tell us about your environment
* **Selenide Version**: 5.6.1
* **Chrome\Firefox\IE Version**: Chrome 79
* **Browser Driver Version**: Chrome 79
* **Selenium Version**: 3.14.159...
* **OS Version**: Mac 10.14

## Code To Reproduce Issue [ Good To Have ]
Create a simple testng project with this as the test class:

```java
    @BeforeClass
    public void setup() {
        System.setProperty("webdriver.chrome.driver", "/selenium/chromedriver");
        System.setProperty("selenide.browser", "Chrome");
        Configuration.timeout = 20000;
    }

    @Test(invocationCount = 50, threadPoolSize = 5)
    public void drawerTest() {
        open("http://jqueryfordesigners.com/demo/plugin-slide-demo.html");
        $$("ul li h2").filterBy(text("Top Downloads")).first().hover();
        $("a[title='iTunes 7.5']").shouldBe(visible).click();
        $(".section-mac").shouldBe(visible);
    }
```
The test will open the demo page, and hover over "Top Downloads" which will expand that section, then try to click on the iTunes link. The last line is a verification that the click happened and we're on the appropriate apple page. In the 50 iterations, I can reliably see a few times the click going to the wrong place, or not happen at all.

Is there something code-wise I can do differently to get around this problem, or is it something that Selenide can handle and I'm missing it? Thanks!

**Comment by asolntsev** [comment]
@ken-p Hi. Yes, it's a well-known problem that I addressed in many conferences presentations.
I can suggest several options:
1. Wait until all the animation is completed. Often you can do it by verifying that element has got/lost some CSS class or attribute:   
    * `$(".loader").should(disappear);` or 
    * `$(".datePicker").shouldHave(cssClass("dt-initialized"));`
2. Use option `Configuration.clickViaJs = true;`
   In this case, Selenide will perform click by executing JavaScript code, thus independently of the element content/location.
