### ISSUE TITLE
How to override Command for custom SelenideElement

### ISSUE THREAD

**Issue by shalak** [selenide/selenide#1047]
How can I override some already existing command, but only for those elements that were obtained via custom `$_()` method?

I have a custom dropdown list in my project that's not a native select and I would like to change the behavior of choosing the options.

When I prepared custom `SelenideComponent` with `selectOptionByValue(String... value`) and I added the command like in the example, the new, overriden `selectOptionByValue` is called even on the regular `SelenideElement` objects, the ones that were obtained via `$()`.

Please take a look the [example implementation and tests that I prepared](https://github.com/shalak/selenide/tree/override-command/statics/src/test/java/integration/overridencommands) to see what I mean.

**Comment by mszajowskiwr** [comment]
This may be unrelated, but when I'm creating a custom `SelenideElement` implementation, I'm loosing the chaining possibility, because the `should()` still returns plain `SelenideElement`, not the custom one. Is there a way to make the chaining work?

**Comment by shalak** [comment]
On a different, unrelated note - when I'm creating a custom SelenideElement implementation, I'm loosing the chaining possibility, because the should() still returns plain SelenideElement, not the custom one. Is there a way to make the chaining work?

**Comment by asolntsev** [comment]
@shalak 
1. No, there is no way to override a command only for custom `SelenideComponent`. But you can just define a new method (say, `select2`). And use it like `$_("select#gender").select2("male");`

2. Yes, you are loosing chaining. As far as I know, it's impossible to solve it in Java.
But probably you would like to use a newer method for running custom commands in Selenide: `execute`. 

Like 

```java
var turnCalendar = new Command<SelenideElement>() {...};
    var pickDate = new Command<SelenideElement>() {...};

    $("hiddenFileInput").execute(turnCalendar).execute(pickDate("03.09");
```
See https://selenide.org/2019/09/02/selenide-5.3.0/
