### ISSUE TITLE
Implement plugin system for Selenide

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1051]
## The problem
Currently Selenide allows to override some parts of it and customize its behaviour. But probably this mechanism is not ideal. 

## Details
I don't have exact plans yet. This issue is for public discussion.

START BRAINSTORMING!

**Comment by SeleniumTestAB** [comment]
That would be good if selenide was like allure if we speak about runtime, unless you mean plugins like pull requests from us and that selenide will know to use it. Plugins would be nice to organize. Or even better approach, make some base dependency like selenide-core and then add another ones?

**Comment by rosolko** [comment]
I think good start pint will be:

- core
- commands
- drivers
- conditions

**Comment by SeleniumTestAB** [comment]
> 
> 
> I think good start pint will be:
> 
>     * core
> 
>     * commands
> 
>     * drivers
> 
>     * conditions

I would add something like frameworks there so that ppl can make some kind of adaptors. It might give some ease of configuration if done right. Also what about static part of selenide? which is one of its trademark points?
