### ISSUE TITLE
IEDriverServer 3.150 is not work. `No matching capability sets found` error occurred

### ISSUE THREAD

**Issue by tmshft** [selenide/selenide#1061]
## The problem
I tried Selenide v5.6.1 on Internet Explorer , but I can not open browser.
`No matching capability sets found` error has occurred.

## Details
When I use IEDriverServer version 3.4.0.0, it works fine.

## Tell us about your environment
* **Selenide Version**: v5.6.1
* **Chrome\Firefox\IE Version**:  IE11
* **Browser Driver Version**: 3.150.1.0(32bit)
* **Selenium Version**: 3.141.59
* Java: AdoptOpenJDK 8.0.222
* **OS Version**: Windows10 / Windows Server 2016

## Code To Reproduce Issue [ Good To Have ]

  ```java
  Configuration.browser = "ie";
  System.setProperty("webdriver.ie.driver", "my driver path");
  open("some url");
  ```

## Error log(partically)

``` log
Started InternetExplorerDriver server (32-bit)
3.150.1.0
Listening on port 14917
Only local connections are allowed
No matching capability sets found.
Unable to match capability set 0: acceptInsecureCerts was 'true', but the IE driver does not allow bypassing insecure (self-signed) SSL certificates
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '{my host}', ip: '{my ip}', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_222'
Driver info: driver.version: SelenideDriver
selenide.url: https://github.com/selenide/selenide
selenide.baseUrl: http://localhost:8080
remote stacktrace: 
org.openqa.selenium.SessionNotCreatedException: No matching capability sets found.
Unable to match capability set 0: acceptInsecureCerts was 'true', but the IE driver does not allow bypassing insecure (self-signed) SSL certificates
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '{my host}', ip: '{my ip}', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_222'
Driver info: driver.version: SelenideDriver
selenide.url: https://github.com/selenide/selenide
selenide.baseUrl: http://localhost:8080
```log

**Comment by BorisOsipov** [comment]
Hmm seems it has to be fixed - we should not set `acceptInsecureCerts` for IE driver.
Details here https://github.com/selenide/selenide/issues/1039#issuecomment-579259187

@shift-morikawa work around for you here https://github.com/selenide/selenide/issues/1039#issuecomment-579276494

**Comment by shift-morikawa** [comment]
Thank you @BorisOsipov 

I've added following code 
`Configuration.browserCapabilities.setAcceptInsecureCerts(false);`
or 
`capbilities.setAcceptInsecureCerts(false);`
Then it works fine!!

**Comment by BorisOsipov** [comment]
Don't close it, please. It is a bug and we need fix.

**Comment by shift-morikawa** [comment]
sorry, I got it!!

**Comment by BorisOsipov** [comment]
The same thing for Safari.`Capability 'acceptInsecureCerts' could not be honored.
`

**Comment by asolntsev** [comment]
@BorisOsipov I registered a separate issue for Safari: https://github.com/selenide/selenide/issues/1236
