### ISSUE TITLE
Provide IsImage Comand functionality as a Condition

### ISSUE THREAD

**Issue by gregorko** [selenide/selenide#1069]
I would like to use the IsImage check (mainly for checking if the image is loaded successfully) as a condition. 
``
$("img").should(isImage)
``

Currently this is not possible and you have to do:
``
assertThat($("img").isImage()).isTrue()
``

Which feels awkward when you are doing all your checks in the Selenide style. Also the screenshot functionality seems to not work when using assertThat checks.

**Comment by rosolko** [comment]
You can easily implement and use custom condition for it
https://github.com/selenide/selenide/wiki/Custom-conditions

**Comment by asolntsev** [comment]
Impemented in PR #1086
