### ISSUE TITLE
Implement soft assert feature inside static @BeforeAll annotation for JUnit5

### ISSUE THREAD

**Issue by IsmagilovQA** [selenide/selenide#1070]
It's not possible to use `@ExtendWith({SoftAssertsExtension.class}) `, `Configuration.assertionMode = SOFT;` inside static `@BeforeAll `annotation  in JUnit 5
when login is situated inside `@BeforeAll `.

```
@ExtendWith({SoftAssertsExtension.class})
public class TestBase {


    @Step
    @BeforeAll
    static void setUp() {
        Configuration.browser = IOSDriverProvider.class.getName();
        Configuration.startMaximized = false; 
        Configuration.browserSize = null;
        Configuration.assertionMode = SOFT;
        SelenideLogger.addListener("allure", new AllureSelenide()); // allure

        open();
        new Login().login();
    }
```
After running this block I have the error like:
> Using soft asserts, but without @SoftAsserts annotation
> java.lang.IllegalStateException: Using soft asserts, but without @SoftAsserts annotation

For now, it's possible to use it only with `@BeforeEach` annotation.

**Comment by djangofan** [comment]
TestNG handles this by allowing you to throw a SkipException in the setup block.

**Comment by osyanin** [comment]
Вот это подарок к новому году!
