### ISSUE TITLE
feature request for relative locator in selenium 4

### ISSUE THREAD

**Issue by hatzhang** [selenide/selenide#1073]
## feature request for relative locator
Is there any plan to go for selenium 4. Really want its relative locator feature, like toLeftOf(),above()..  i tried to simulate toRightOf by using pressTab, but got ElementNotInteractableException.

**Comment by asolntsev** [comment]
@hatzhang We have an open pull request for upgrading to Selenium 4: https://github.com/selenide/selenide/pull/931

One Selenium 4 is released, we will immediately ugprade.
