### ISSUE TITLE
Problem with fastSetValue on Material UI Components 

### ISSUE THREAD

**Issue by rusakovStas** [selenide/selenide#1074]
## The problem
Material UI is one of the most popular React Components library. 
And when i'm trying to use Selenide with fastSetValues (setting values via js) it's not working correctly. 

## Details
When Selenide sets value via JS Material UI component ( Autocomplete ) do not call hooks like onInputChange and others. 

## Tell us about your environment
* **Selenide Version**: 5.8.0
* **Yandex browser**: 20.2.0.1145
* **Browser Driver Version**: 79
* **Selenium Version**: embedded in Selenide
* **OS Version**: mac OS

## Code To Reproduce Issue [ Good To Have ]
To reproduce the bug you may run the test: 
```
@Test
    void check() {
        Configuration.fastSetValue = true;
        open("https://rusakovstas.github.io/material-autocomplete/");
        $(byText("Вбейте что нибудь или скопируйте")).closest("div").$("input").setValue("123");
        $(byText("Поймали логику!")).shouldBe(visible);
    }
```
For now it's failed. If you remove Configuration.fastSetValue = true; it works fine.

**Comment by rusakovStas** [comment]
Hi! 
I've finally found the solution of this question! It's really simple) 
To set value via js properly for Material UI you have to do this by `setAttribute('value', 'some text'); `
Not just `element.value = `
I think the reason in some JS Proxy or something like that.

I even have changed the method setValue in Selenide and it's working (after local install)! 
But now: 
1. i can't push branch (getting 403). Maybe there are some rules for that? 
2. i'm not sure how can i write the test for this? 

Just in case code for fix is pretty simple: 

```
private String setValueByJs(Driver driver, WebElement element, String text) {
    return driver.executeJavaScript(
        "return (function(webelement, text) {" +
            "if (webelement.getAttribute('readonly') != undefined) return 'Cannot change value of readonly element';" +
            "if (webelement.getAttribute('disabled') != undefined) return 'Cannot change value of disabled element';" +
            "webelement.focus();" +
            "var maxlength = webelement.getAttribute('maxlength') == null ? -1 : parseInt(webelement.getAttribute('maxlength'));" +
            "webelement.setAttribute('value', " +
            "maxlength == -1 ? text " +
            ": text.length <= maxlength ? text " +
            ": text.substring(0, maxlength));" +
            "return null;" +
            "})(arguments[0], arguments[1]);",
        element, text);
  }
```

**Comment by rusakovStas** [comment]
P.S. As far as i can see - all tests works properly.

**Comment by asolntsev** [comment]
@rusakovStas Good catch! 
I created a fix in Selenide [5.8.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/codeborne/selenide/5.8.1-SNAPSHOT/selenide-5.8.1-20200301.223659-1.jar) - can you try it?

**Comment by rusakovStas** [comment]
Thank you! 
I tried - it works. But unfortunately not for all cases( 
i'd like to add a few more tests.

**Comment by rusakovStas** [comment]
It looks like another cases doesn't work cause another reasons. After all, the case with custom business logic works. So, i think that's enough for now.

**Comment by rusakovStas** [comment]
By the way, for the feature, is this normal to use githubactions pages for Integration tests in Selenide? I think it's really convenient)

**Comment by asolntsev** [comment]
@rusakovStas We currently use TravisCI for Selenide builds. Yes, we could migrate to Github actions, but I don't know if it really changes our lives drastically.

**Comment by asolntsev** [comment]
@rusakovStas Something is wrong with PR https://github.com/selenide/selenide/pull/1076. It breaks a lot of tests in some my my work projects. Could not figure out why.

**Comment by rusakovStas** [comment]
Hm. 
It's weird. I read this [article](https://learn.javascript.ru/attributes-and-custom-properties#ishodnoe-znachenie-value) and thought that it would be more right to change value attribute. But it's good to have tests) So then i better set attribute via execute command like in your `selectBootstrap`

**Comment by rusakovStas** [comment]
P.S. 
I tried that way: 
```java
  private String setValueByJs(Driver driver, WebElement element, String text) {
    return driver.executeJavaScript(
        "return (function(webelement, text) {" +
            "if (webelement.getAttribute('readonly') != undefined) return 'Cannot change value of readonly element';" +
            "if (webelement.getAttribute('disabled') != undefined) return 'Cannot change value of disabled element';" +
            "webelement.focus();" +
            "var maxlength = webelement.getAttribute('maxlength') == null ? -1 : parseInt(webelement.getAttribute('maxlength'));" +
            "var clearText = "+
            "maxlength == -1 ? text " +
            ": text.length <= maxlength ? text " +
            ": text.substring(0, maxlength);"+
            "webelement.setAttribute('value', clearText);" +
            "webelement.value = clearText;"+
            "return null;" +
            "})(arguments[0], arguments[1]);",
        element, text);
  }
```
It doesn't work for my case.

**Comment by occupant23** [comment]
Hi, we also found this issue and evaluated it a little bit further and created an issue at MaterialUI https://github.com/mui-org/material-ui/issues/19346. The issue seemed to be exclusive to the ChromeDriver.

**Comment by rusakovStas** [comment]
Hi @occupant23) 
It's cool) Will monitor developments)

**Comment by rusakovStas** [comment]
But for now you could use custom command via execute method) 
For my case i wrote command like this: 
```
public static Command<SelenideElement> setValueAttribute(String value) {
       return (proxy, locator, args) -> {
           Selenide.executeJavaScript("arguments[0].focus(); arguments[0].setAttribute('value', arguments[1]);", proxy, value);
           events.fireEvent(locator.driver(), proxy, "keydown", "keypress", "input", "keyup", "change");
           return proxy;
       };
    }
```
And in tests it's look like: 
`$("input").execute(setValueAttribute("some value"));`

**Comment by asolntsev** [comment]
@rusakovStas Thank you for sharing the knowledge.
Do I correctly understand that there is nothing to fix in Selenide?
Can we close this issue then?

**Comment by rusakovStas** [comment]
So, since the fix https://github.com/selenide/selenide/issues/1074#issuecomment-593118940 
broke tests, i think there is nothing to do. 
Issue may be closed.

**Comment by occupant23** [comment]
You could upvote the issue, so that it's not postponed.

**Comment by asolntsev** [comment]
done
