### ISSUE TITLE
StaleElementReferenceException for SelenideElements

### ISSUE THREAD

**Issue by Zahorodnii** [selenide/selenide#1079]
## The problem
StaleElementReferenceException for inner SelenideElements.

## Details
Trying to describe problem on my project.
I have next UI elements: List with two benefit types, punch cards and gifts
|UI|HTML|
|:--------:|:----------:|
|![зображення](https://user-images.githubusercontent.com/58936047/75878116-c62d2300-5e21-11ea-984f-4c71eadc50ab.png)|![зображення](https://user-images.githubusercontent.com/58936047/75878374-2a4fe700-5e22-11ea-9398-497e21aa0b16.png)|

For these components, I have the following hierarchy:
`AbstractBenefit -> GiftComponent`
`AbstractBenefit -> PunchCardComponent`
where AbstractBenefit contains base benefit element, benefitItem <- initialize from constructor, when GiftComponent or PunchCardComponent will create. 
Example with gifts list:
``` java
public GiftComponent getGift(String giftTitle) {
        return $$(byAttribute("data-type", "gift")).stream()
                .filter(giftItem -> giftItem.$(".benefit-item-title").text().equals(giftTitle))
                .map(giftItem -> new GiftComponent(giftItem, this))
                .findFirst()
                .orElse(null);
    }
```
When we manipulate gift, need to reload page, and after page reload any SelenideElement method for benefitItem, like:
``` java
protected void openBenefitActions() {
        benefitItem.$(".benefit-actions").click();
        log.debug("Clicked on 'Benefit Actions' button");
    }
```
will throw StaleElementReferenceException. Now for procces this exception I create Aspect and invoking next method for element reload:
``` java
@Override
    public void reload() {
        benefitItem = $(byAttribute("data-id", UUID));
        log.warn("Benefit item was reloaded");
    }
```
but how I know, Selenide reload elements when StaleElementReferenceException throwing

## Tell us about your environment
* **Selenide Version**: 5.8.0
* **Browser Driver Version**: Selenide bonigarcia

**Comment by asolntsev** [comment]
@Zahorodnii Yes, in most cases Selenide does reload elements. But there is one exception: when you iterate a collection, Selenide doesn't reload its elements (trying to speed up the test). We had a long discussion [in this issue](https://github.com/selenide/selenide/issues/797) that it's probably a bad idea. :) So we will probably will change this behaviour. 

Anyway, in your case there is a simple solution. Don't iterate collection in method `getGift`, but use filtering instead. Something like that:

```java
public GiftComponent getGift(String giftTitle) {
  return $$(".benefit-item-title").find(byText(giftTitle)).closest("div.gift");
}
```

Another option is to write an XPath for finding your element by attribute and text. It's the most fast and stable option. Here is a similar example from my working project:

```java
  private SelenideElement passportRow(String passportNumber) {
    return $x("//*[@id='passport-table']//tr//td[string(.) = '" + passportNumber + "']/ancestor::tr[1]");
  }
```

**Comment by Zahorodnii** [comment]
About second option, I can't do it, becouse benefitItem initialize in one place, inner elements in second place, create static constants for this I don't want, and I proposed in Selenide chat create method like, benefitItem.getLocator()

About first option, this is a good idea, but not everywhere you can apply it, for example:
``` java
@DisableImplicitWait
    @SuppressWarnings("unchecked")
    protected MemberProfilePage removeBenefitsPack(Supplier<List<COMPONENT>> expandBenefitsSupplier) {
        List<COMPONENT> benefits = new ArrayList<>();

        if (similarButton.exists()) {
            for (COMPONENT benefit : expandBenefitsSupplier.get()) {
                benefit.remove().apply();
                benefits.add(benefit);
            }
        }

        benefits.add((COMPONENT) this);
        String rootBenefitTitle = getTitle();
        ProfileDetailsComponent details = removeBenefit().details();

        Selenide.Wait()
                .pollingEvery(ofSeconds(1))
                .withTimeout(ofSeconds(APPROXIMATE_REMOVE_SECONDS * benefits.size()))
                .until(webDriver -> {
                    details.refreshAfterChanging();

                    for (COMPONENT benefit : benefits) {
                        benefit.reload();
                        if (benefitItem.isDisplayed()) {
                            return false;
                        }
                    }

                    return true;
                });

        log.info("All '{}' benefits in pack was removed", rootBenefitTitle);
        return (MemberProfilePage) getIntegrablePage();
    }
```
in place:
``` java
if (benefitItem.isDisplayed()) {
   return false;
}
```
if I not reload, isDisplayed working not correctly, and I can't use method `find` in this case.

**Comment by BorisOsipov** [comment]
`I proposed in Selenide chat create method like, benefitItem.getLocator()`

ok. what `getLocator()` should return for 
```
$(".somecss [name=foo]).$(By.Xpath("//span[@class="product_info_details"]/b[contains(.,'ISBN')]/following-sibling::text()[1]")).$(By.linkText("baz")).getLocator()
```

?

**Comment by Zahorodnii** [comment]
@BorisOsipov need to discuss it, becouse I understand that it not 5 minute implementation.
