### ISSUE TITLE
Sometimes Selenide.open() not execute in sequence operation.

### ISSUE THREAD

**Issue by conhaifeng** [selenide/selenide#1082]
## The problem
Sometimes Selenide.open() not execute in sequence operation.

## Details
Using selenide to test web page.
The scenario is login and switch to other page, code is:
```
public class LoginPage{

    private By loginIframe = By.id("login-iframe");

    private By loginId = By.id("fm-login-id");

    private By loginPassword = By.id("fm-login-password");

    private By submitButton = By.id("fm-login-submit");

    public LoginPage()
    {
        $(loginIframe).should(Condition.appear);
    }

    public void login(String loginName, String password)
    {
        $(loginId).val(loginName);
        $(loginPassword).val(password);
        $(submitButton).click();
        # here, sometimes not work
        Selenide.open("https://sample.com/info");
    }
}
```

Sample code is above
after `$(submitButton).click()` sometimes `Selenide.open()` not work, as if it was never executed.
if i set ` Selenide.sleep(time)` after `click()`, and it's ok.
i think during new page is loading when `click()` executed,  another call to webdriver will not work.
so, what's the problem, is it a bug ?

ps.
I know it's a bad practice to set selenide.open() there,
it is in test method actually.

## Tell us about your environment
* **Selenide Version**: 5.8.0
* **Chrome\Firefox\IE Version**: Chrome, 80.0.3987.122
* **Browser Driver Version**: 80.0.3987.106
* **Selenium Version**: 3.141.59
* **OS Version**: windows

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
Hi.
I guess method `$(submitButton).click()`, and you just don't wait until it's fully loaded. (Actually, `$.click()` usually waits for page loading, but probably something is loaded asynchronously etc.)
