### ISSUE TITLE
Allow to pass driver specific options from configuration

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1097]
## The problem

As Selenide user I want to pass `ChromeOptions` \ `FirefoxOptions` \ `EtcOptions` from `Configuration` without `WebDriverProvider`

Now it is not possible due bug https://github.com/selenide/selenide/issues/676 (actually selenium capabilities merge bug) - some options are lost on capabilities merging.

**Comment by SeleniumTestAB** [comment]
So actually my PR wasn't a bad idea afterall :)

**Comment by asolntsev** [comment]
@SeleniumTestAB Sure, it was not bad at all. The following is just implementation details.
