### ISSUE TITLE
IE Browser: Certificate Issue with Proxy enabled

### ISSUE THREAD

**Issue by kkleimenova** [selenide/selenide#1105]
I got SSL certificate issue (Site is not secure error) while running my script in IE 11 with proxy enabled.

## Details of configuration:
        Configuration.browser = "ie";
        Configuration.startMaximized = true;
        Configuration.baseUrl = ADMIN_PORTAL_BASE_URL;
        Configuration.reportsFolder = TARGET_SCREENSHOTS;
        Configuration.fileDownload = FileDownloadMode.PROXY;
        Configuration.proxyEnabled=true;
        Configuration.driverManagerEnabled = true;

## Tell us about your environment
* **Selenide Version**:  5.10.0
* **Chrome\Firefox\IE Version**:  IE 11
* **Browser Driver Version**: Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
* **OS Version**: Windows 10

## Logs
[main] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
[main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Starting proxy at address: 0.0.0.0/0.0.0.0:0
[main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy listening with TCP transport
[main] INFO org.littleshoot.proxy.impl.DefaultHttpProxyServer - Proxy started at address: /0:0:0:0:0:0:0:0:58700
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Reading https://selenium-release.storage.googleapis.com/ to seek IEDriverServer
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Latest version of IEDriverServer is 3.150
[main] INFO io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.ie.driver as C:\Users\KKleimenova\.m2\repository\webdriver\IEDriverServer\x64\3.150\IEDriverServer.exe
Started InternetExplorerDriver server (64-bit)
3.150.0.0
Listening on port 4763
Only local connections are allowed
Apr 06, 2020 11:16:10 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - BrowserName=internet explorer Version=11 Platform=WINDOWS
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenide v. 5.10.0
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
[main] INFO com.codeborne.selenide.drivercommands.CreateDriverCommand - Create webdriver in current thread 1: InternetExplorerDriver -> InternetExplorerDriver: internet explorer on WINDOWS (15ef9658-a1f9-4169-a7ca-52438e031407)
[LittleProxy-0-ClientToProxyWorker-2] WARN com.browserup.bup.mitm.util.SslUtil - Disabling upstream server certificate verification. This will allow attackers to intercept communications with upstream servers.
[LittleProxy-0-ProxyToServerWorker-1] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x7f4dd3ac, L:0.0.0.0/0.0.0.0:58739 ! R:qa-rpxadmin.realpage.com/10.34.120.246:443]: Connection to upstream server failed
[LittleProxy-0-ProxyToServerWorker-0] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x927d2211, L:0.0.0.0/0.0.0.0:58738 ! R:fonts.googleapis.com/172.217.12.74:443]: Connection to upstream server failed
[LittleProxy-0-ProxyToServerWorker-2] INFO org.littleshoot.proxy.impl.ProxyToServerConnection - (HANDSHAKING) [id: 0x2b1876f1, L:0.0.0.0/0.0.0.0:58737 ! R:fonts.googleapis.com/172.217.12.74:443]: Connection to upstream server failed
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1067)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1416)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:816)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

**Comment by asolntsev** [comment]
To be honest, I don't know exactly how to solve this problem.
I guess we would need to add the proxy's cert to browser's trusted certs. But I haven't tried it personally. Any help is welcome.

**Comment by rosolko** [comment]
As I remember IE require manual proxy configuration

**Comment by asolntsev** [comment]
@kkleimenova Is this issue still on?
1. Proxy doesn't work well in IE. Because IE cannot have its own proxy, it can only use global Windows proxy. 
2. I guess nobody should test on IE nowadays :) IE was replaced by Edge browser. 

It seems that we can close the issue because we don't have any ideas anyway.
