### ISSUE TITLE
impossible to use System.setProperty("chromeoptions.mobileEmulation,...); with remote driver

### ISSUE THREAD

**Issue by BabinAB** [selenide/selenide#1109]
Hello guys. We've just spotted that System.setProperty("chromeoptions.mobileEmulation", "deviceName=Nexus 5"); is not working properly on remote machines. It works perfectly locally.
for Reproducing this issue you can clone this sandbox project - https://github.com/BabinAB/SelenideRemote and run Selenoid locally.  And for comparison you can remove "remote="http://localhost:4444/wd/hub";" from BaseClass.

**Comment by BorisOsipov** [comment]
Also need to check `-Dselenide.headless=true` for remote. Seems it doesn't work
