### ISSUE TITLE
Add method `$.hover()`

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#111]
The goal is to move cursor over element with pop-up menu. 

Possible implementation is using actions().moveToElement().

[requested by Pavel Aksenov]

**Comment by saikumar425** [comment]
how to do hover operation by using selenide

**Comment by saikumar425** [comment]
how to do drag$drop operation by using selenide

**Comment by asolntsev** [comment]
@saikumar425 See example here: http://selenide.org/2014/04/27/selenide-2.10/

`$("#from").dragAndDropTo("#to");`

`$("h1").hover();`

**Comment by Tonicku** [comment]
hi the hover functionality not working 

Browser                : Opera
Operating System: Windows 10

Dependency in use
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>5.15.1</version>
        </dependency>

`        SelenideElement selectedMainNavItem = NAVIGATION_BAR.$x(".//ul[contains(@class, 'navbar-nav')]/li[a[@id='dropdown-" + subMenu.getMenuTitle().replace(" ", "-") + "']]").hover();
        selectedMainNavItem.hover();
        SelenideElement selectedSubMainNavItem = selectedMainNavItem.$x("./ul/li/a[@href='/resumes/']"); //.should(Condition.text(subMenu.getTitle()));
        selectedSubMainNavItem.click();`

**Comment by AndreiByin** [comment]
tell me please what is the method for checking this particular pop-up window?

> @ saikumar425 См. пример здесь: http://selenide.org/2014/04/27/selenide-2.10/
> 
> `$("#from").dragAndDropTo("#to");`
> 
> `$("h1").hover();`

tell me please what is the method for checking this particular pop-up window after using the method $("h1").hover(); ?

**Comment by Tonicku** [comment]
> tell me please what is the method for checking this particular pop-up window?
> 
> > @ saikumar425 См. пример здесь: http://selenide.org/2014/04/27/selenide-2.10/
> > `$("#from").dragAndDropTo("#to");`
> > `$("h1").hover();`
> 
> tell me please what is the method for checking this particular pop-up window after using the method $("h1").hover(); ?

Hi Andrei, thanks for asking. i think it's my mistake.... the functionality works but the javascript / css in our application seemsm handling the popup is not stable.
