### ISSUE TITLE
Implement Drag'nDrop using JS code

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1110]
This js library can be used:
https://github.com/Photonios/JS-DragAndDrop-Simulator

## The problem
Drag'nDrop doesn't work properly in most (all?) webdrivers. People need a workarohnd in Selenide.

**Comment by dstekanov** [comment]
Hi @asolntsev, it works with Chrome.
But I cannot figure out why it does not want to work with Firefox...

**Comment by kikxter** [comment]
I haven't been able to make it work on either Chrome, Firefox or Edge. 

Using Selenide v. 5.5.0
BrowserName=chrome Version=86.0.4240.111 Platform=MAC
Selenium WebDriver v. 3.141.59

My issue is that the DROP is done wherever my mouse pointer is located at the moment not where the TO (WebElement / SelenideElement ) is located at.

**Comment by dbudim** [comment]
working on it in [PR](https://github.com/selenide/selenide/pull/1412)

**Comment by dbudim** [comment]
done, please review [PR](https://github.com/selenide/selenide/pull/1412)

**Comment by camohub** [comment]
So which version of Selenide is fixed? I have 5.19.0

**Comment by asolntsev** [comment]
The feature was released in Selenide 5.19.0:

![image](https://user-images.githubusercontent.com/279773/111294722-49976c00-8653-11eb-8439-4526228c2975.png)
