### ISSUE TITLE
[Bug] Enabled "driverManagerEnabled" that download webdriver binary automatically out of work

### ISSUE THREAD

**Issue by ansonliao** [selenide/selenide#1111]
Dear all, 
My Selenide version is the latest (`5.10.0`), and I set the `selenide.driverManagerEnabled` to true explicitly to download the webdriver binary automatically, but `Selenide` will not download the webdriver binary automatically.

My OS is Mac OS.

Please help to check.

![image](https://user-images.githubusercontent.com/6060224/78896438-0d52a780-7aa3-11ea-8049-683eb022b7e2.png)

**Comment by vinogradoff** [comment]
Actually it is default on true. You can just delete the line. 
I guess the problem with this code could be that systemProperties are Strings, so the quotes around true could help -> "true"  

Please tell me if I could solve the problem.

**Comment by ansonliao** [comment]
@vinogradoff 
Oh, yes, removed the line `systemProperties['selenide.driverManagerEnabled'] = true` solved the problem
Thanks @vinogradoff

**Comment by ansonliao** [comment]
@vinogradoff 
Sorry, after removed the line `systemProperties['selenide.driverManagerEnabled'] = true` can't solve the problem, still can't download the webdriver binary

![image](https://user-images.githubusercontent.com/6060224/78898469-712a9f80-7aa6-11ea-8a24-02cc690be4a8.png)

**Comment by vinogradoff** [comment]
can you please show your test?

settings are actually okay, 'selenide.browser' instead of 'browser' - but chrome is default so you can skip this line too.

**Comment by ansonliao** [comment]
@vinogradoff 
I found the root cause, as I implemented my custom `WebDriverProvider` and set the default WebDriverProvider as `Configuration.browser = CustomWebDriverProvider.class.getName();`, 
it need to handle how to download the webdriver and export the webdriver binary system property value by myself, even keep `selenide.driverManagerEnabled` as `true`.

I thought if implemented `WebDriverProvider` and set `selenide.driverManagerEnabled` to `true`, `Selenide` will handle the webdriver binary download for user, but it is wrong.

**Comment by vinogradoff** [comment]
Yes, when you creates your own driver - you must do everything yourself.

Example:
https://github.com/selenide/selenide/wiki/How-to-run-the-browser-in-MobileEmulation-mode

see the line:
`WebDriverManager.chromedriver().setup();`

It sets up WebDriverManager for chrome.

Can we close? :)

**Comment by ansonliao** [comment]
@vinogradoff 
Sure, we can close this issue now, thanks for your help.
