### ISSUE TITLE
How to make ElementsContainer works?

### ISSUE THREAD

**Issue by ansonliao** [selenide/selenide#1112]
My `selenide` version is the latest, and I need to introduce `ElementsContainer` for my testing, from my study of `ElementsContainer` in simple, but it fail, looks like `ElementsContainer` is not straightforward to use, my codes as below:

```java
public class SearchPage {

    @FindBy(css = "div[class='RNNXgb']")
    public SearchBlock searchBlock;

    public void open() {
        Selenide.open("https://www.google.com");
    }

    public void search(String text) {
        searchBlock.searchInput.val(text).pressEnter();
    }

    static class SearchBlock extends ElementsContainer {
        SelenideElement searchIcon
                = $("div[class='hsuHs']");
        SelenideElement searchInput
                = $(By.name("q"));
        SelenideElement voiceIconBtn
                = $("div[class='hpuQDe']");
    }

}
```

My testing code:
```java
public void f2() {
        SearchPage page = new SearchPage();
        page.open();
        page.search("selenide");
}
```

finally, I got the error as below.
![image](https://user-images.githubusercontent.com/6060224/79039623-1bc0d080-7c15-11ea-920f-eb6aea913a6a.png)

As less error message from the exception, so I don't know how to fix, could someone advise how to fix it?

Thanks

**Comment by vinogradoff** [comment]
That's because you need to use PageFactory to initialise Selenium @FindBy annotation.

Luckily you don't need @FindBy annotations at all when using Selenide.
Just assign the variable:
` public SearchBlock searchBlock=$("div[class='RNNXgb']);`

or (better locator)
`public SearchBlock searchBlock=$("div.RNNXgb"]);`

**Comment by ansonliao** [comment]
@vinogradoff 
I tried using `$` to initialize the `ElementsContainer`, but error me the type is wrong.

![image](https://user-images.githubusercontent.com/6060224/79042814-7403cc80-7c2d-11ea-9c6f-d342d377dc46.png)

**Comment by ansonliao** [comment]
I tried to initialize the page object by `Selenide#page` method, but also failed

![image](https://user-images.githubusercontent.com/6060224/79043007-df9a6980-7c2e-11ea-979d-6a50492161d9.png)

**Comment by vinogradoff** [comment]
Oh, I see.

ElementsContainer looks like an ancient artefact from early Selenide days. I didn't even know it exists. I will ask the team if we can deprecate & delete it to avoid further confusion.

 To implement one widget as a part of another you can just use the basic simple objects, like this:

```java
public class SearchPage {

    public void open() {
        Selenide.open("https://www.google.com");
    }

    public void search(String text) {
        new SearchBlock().searchInput.val(text).pressEnter();
    }

    static class SearchBlock {
        SelenideElement root=$("div[class='RNNXgb']");
        SelenideElement searchIcon
                = root.$("div[class='hsuHs']");
        SelenideElement searchInput
                = root.$(By.name("q"));
        SelenideElement voiceIconBtn
                = root.$("div[class='hpuQDe']");
    }

}
```

**Comment by asolntsev** [comment]
@ansonliao You could rewrite the initial code a little bit to make `ElementsContainer` work:

```
    SearchPage page = open("https://www.google.com", SearchPage.class);
    page.search("selenide");
```

Method `page` currently requires an opened browser. That's why you need to call `Selenide.open` first, and only then create a page object instance. 

But as @vinogradoff mentioned, you don't need `ElementsContainer` at all.

Please let us know if you can write your test without `ElementsContainer`.

**Comment by ansonliao** [comment]
@asolntsev 
I am not sure whether don't need `ElementsContainer` at all in `Selenide`, in `HtmlElement` library we are using  webelement `block` to handling the table view of the page element, for example, the table view as below, some sub-elements in the cell of the table view, using the webelement `block` is very easy to handle specific target of the element of the cell correctly, I need to study `Selenide` whether can fulfill our requirement to decide to migrate to `selenide`, I will study deep about `selenide`

![image](https://user-images.githubusercontent.com/6060224/79110641-77be5d00-7dad-11ea-973e-0c16c5a2bc61.png)

**Comment by ansonliao** [comment]
@vinogradoff 
thanks for your reply, I think your solution can handle the simple sample, but can't handle the table view case (each cell includes the same locator, and each element in the table cell also includes same locator), similar as below.

![image](https://user-images.githubusercontent.com/6060224/79110913-1054dd00-7dae-11ea-99b1-053957bfa4eb.png)

**Comment by ansonliao** [comment]
Here also is the advance feature for Appium, Java client

https://github.com/appium/java-client/blob/master/docs/Page-objects.md#the-additional-feature

**Comment by ansonliao** [comment]
@asolntsev 

test code was changed to:

```java
@Test
public void f2() {
        SearchPage page = open("https://www.google.com", SearchPage.class);
        page.footer.advertising.click();
        page.search("selenide");
}
```

I am working on how to encapsulate the `SearchPage page = open("https://www.google.com", SearchPage.class)` to `SearchPage#open()` method, if it can, I think can solve my migration almost.

**Comment by asolntsev** [comment]
@ansonliao Sorry, but you are so used to your old constructions. :) 
Everything is much easier with Selenide. 

But well, here is an easy way to use `SearchPage#open()` method without any refactorings:
```
@Test public void f2() {
  Selenide.open();
  SearchPage page = new SearchPage();
  page.open();
  page.search("selenide");
}

public class SearchPage {
    ...
    public void open() {
        Selenide.open("https://www.google.com");
    }
    ...
```

**Comment by ansonliao** [comment]
@asolntsev 
Just tried the code from your suggestion, but failed.

testing code: 
![image](https://user-images.githubusercontent.com/6060224/79304035-ef61c880-7f22-11ea-8fee-edd8ab8ef858.png)

and the error:

![image](https://user-images.githubusercontent.com/6060224/79304094-16b89580-7f23-11ea-912d-e14bbf10999d.png)

thanks @vinogradoff @asolntsev replies, and I think Selenide support the element block is not good and not elegant, so we are suspending the migration, thanks for your suggestion.



it

**Comment by asolntsev** [comment]
@ansonliao Don't rush to conclusions :)

Sorry, I did a mistake in my previous answer. Just replace `new SearchPage()` by `page(SearchPage.class)`, and everything will work. 

P.S. All this is also valid for Selenide:
> normally the first page call the Selenide#open(String url) only, and then others page will be opened by some behavior of the previous page.

I don't understand why you decided that it's somehow different in Selenide.

**Comment by ansonliao** [comment]
@asolntsev 
Maybe so I am not know well to `Selenide` so fart, that why I need to study more deeply about `Selenide`.

I have another question about the table view or scroll down to load more of the page.

for example, below it is my page of the table view, we can click the `SHOW MORE` button, and the table view will load more information and create more table cells.
 
![image](https://user-images.githubusercontent.com/6060224/79341468-6bc5cd00-7f5e-11ea-8b16-4d19bf437f33.png)

after clicking the `SHOW MORE` button, to get the new records of table view, need to call `historyPage = page(HistoryPage.class);` again, to fetch the new table cells.

if without `historyPage = page(HistoryPage.class);`, the `recordSize = historyPage.recordList.bookingRecords.size();` will be same.

![image](https://user-images.githubusercontent.com/6060224/79341987-281f9300-7f5f-11ea-809f-415b61fa2544.png)

Any good solution can refactor the code so that don't need to call `historyPage = page(HistoryPage.class);` after click `SHOW MORE` button?

Thanks so much.

**Comment by asolntsev** [comment]
@ansonliao In Selenide, it works out-of-the box: `$$` reloads collection every time. You don't need to call `page(HistoryPage.class)` every time when data changes. 

I guess the trick is in `recordList` and `bookingRecords` - what they are?

**Comment by ansonliao** [comment]
@asolntsev 
The `BookingRecord` is extended from `ElementsContainer`

```java
static class BookingRecord extends ElementsContainer {
        SelenideElement pickupTime = $("div[id^='bookingPickupTime-']");
        SelenideElement status = $("span[id^='bookingStatusTag-'] > span");
        SelenideElement openRecordBtn = $("img[id^='bookingId-']");
}
```


and the table cell list of table view are:
```java
@FindBy(css = "div[id^='bookingRef-']")
 List<BookingRecord> bookingRecords;
```

![image](https://user-images.githubusercontent.com/6060224/79350517-23141100-7f6a-11ea-8c30-2a025adc230f.png)

whether can convert the `List<BookingRecord>` to `ElementsCollection`?
I found `ElementsCollection` is not a generic type, can't cast as `ElementsCollection<BookingRecord>`.

please advise

**Comment by asolntsev** [comment]
@ansonliao 
1. Yes, `List` fields of page objects marked as `@FindBy` are not re-loaded. We even have an issue registered: https://github.com/selenide/selenide/issues/482
We assigned it a lowest priority because it's not really needed: Selenide allows creating page objects/containers much easier. See https://selenide.org/documentation/page-objects.html

2. Yes, `ElementsCollection` can only contain `SelenideElement` instances and cannot be casted to `ElementsCollection<BookingRecord>`. Again, we think it's not really needed. 


Here is how you code could look like without any `ElementContainer's at all: https://gist.github.com/asolntsev/bf4b0ac648c50ed6dfdaf334a6f36912

**Comment by vinogradoff** [comment]
@ansonliao thank you it is a nice challenge.

One remark is that I personally don't like using this kind of collections at all because  iterating them (in UI-sense) is often pretty slow. There is alway an XPath that can just find the right element in the table with single search.

But let's exercise some page objects without constructing too much of a framework.
I've startet with you rottentomatos page example, and created a simple
MovieList->MovieBlock->MovieTitle hierarchy in here. It uses only constructors and SelenideElement, nothing more.

https://github.com/vinogradoff/selenide101/tree/master/src/test/java/de/vinogradoff/runnable_examples/element_containers

The test looks still a bit bulky, I will also look for alternative solutions :).

**Comment by ansonliao** [comment]
@asolntsev 
Thanks for your reply.
I understand the design of `Selenide`, I would like to share some opinions.

1. In my current code using Selenium `@FindBy/@FindBys` etc, the standard Selenium is supported auto re-load the DOM even the lazy load page, so I think `Selenide` can inherit this implicit feature of standard Selenium, now more and more website are running lazy load feature, for example, the news website, https://www.nytimes.com/, the home page of this website is lazy load, if `Selenide` don't support `@FindBy` lazy support, I am not sure that `Selenide`'s locate strategies `$`/`$$` can handle all locate strategies of the page element, but I am sure many testers also need to locate the page element by Selenium standard locate strategies such as `@FindBy/@FindBys` even `$/$$` of Selenide is easier to use.

2. `ElementsCollection` only support `SelenideElement` but `ElementsContainer` also are the standard type of `Selenide` and out of support of `ElementsCollection`, 

3. Thanks for your code that display the `ElementsContainer` to solve my problem. But I think `Selenide` to handle the container of elements is very curved, for example: 
https://gist.github.com/asolntsev/bf4b0ac648c50ed6dfdaf334a6f36912#file-pageobjectwithoutcontainerstest-java-L32

compare to others, support webelement block is very easy, very clear, and very simple, and the library doesn't miss the implicit feature of standard Selenium:
https://github.com/yandex-qatools/htmlelements#create-blocks-of-elements

here also can solve the problem that `Selenide` can't locate all `ElementsContainer` and save them as a collection.

and here:
https://gist.github.com/asolntsev/bf4b0ac648c50ed6dfdaf334a6f36912#file-pageobjectwithoutcontainerstest-java-L29

in `Selenide`, `ElementsCollection` is same level as `SelenideElement`, it is the disadvantage of `ElementsCollection`

Actually, `Webelement Block` or `Webelement Widget` or `ElementsContainer` is the page object pattern of the standard of `Selenium`: `WebElement#findBy()` or `WebElement#findBys()`, and webelement is very useful to grouping some block of the page element, for example, in the news website (https://www.nytimes.com/), each news are grouped by some sub information, we can create some blocks of the elements to handle different news.
![image](https://user-images.githubusercontent.com/6060224/79411933-bf73fd00-7fd6-11ea-8e02-404ce66fd4bf.png)

for example the case of my other:
![image](https://user-images.githubusercontent.com/6060224/79411424-63f53f80-7fd5-11ea-9617-f343cce05d06.png)

actually we are separated object class and page class, as some object of the page is more than 30, if group the object and page together, the java class file will be large.
also element container can make object class more readability and good organization.


If using `$$`, have to handle all news titles separated, handle news sub-titles separated, handle news cover images separated, otherwise need to handle it by `$$#get(index).findBy()`, but it is not page object or it is only half of page object.  (in this case, `WebDriverIO + Mocha + Chai`, it is more straightforward than the libraries of Java of Selenium).

Thanks @asolntsev @vinogradoff pay the time to provide some suggestion and coding for my question, I think my last question the root cause from @asolntsev is `Selenide` now don't support `@FindBy` automatically reload when the DOM refresh (but Selenium standard support), or `ElementsContainer` only support contains `SelenideElement` (not generic type).

**Comment by ansonliao** [comment]
@asolntsev @vinogradoff 
I think I would like to confirm that:
1. Whether `Selenide` supports all `@FindBy/@FindBys` and `$/$$` to reload the DOM when it updated (for example, lazy load, or some manual trigger DOM updated for example my case click `SHOW MORE` button to load more data into table view)? or `Selenide` only support owned `$/$$` automatically reload the updated DOM?

And I suggest that `ElementsCollection` also support generic type that support both `SelenideElement` and `ElementsContainer`, both these two types are `Selenide` owned customized types, `ElementsCollection` don't support `ElementsContainer` are so strange
And suggest make `ElementsCollection` more flexible, not limited to extended assertion methods, it's too limited as it is very specified and very weak functionality `Collection` type (seems fake collection) and actually the assertion can introduce more powerful tools such as `AssertJ` of Java.

Of cause, it is only my opinions.

**Comment by asolntsev** [comment]
@ansonliao Yes, I know about HtmlElements. 

- A long time ago, we wanted to do the same - that's why we created `ElementsContainer`. 

- Later we realized that Selenide provides much simpler way - that's why nobody wanted to waste time on improving `ElementsContainer`. 

### I like your suggestions
> let Selenide support @FindBy/@FindBys etc. to support the reload automatically?
> for example, under the license, fork the project and change some function's classes.

No need to fork the project. Let's do it in Selenide. 
I wish Selenide could reload @FindBy/@FindBys automatically - it's just not implemented yet. 

> bigger disadvantage is ElementsCollection is the same type of SelenideElement

It's not disadvantage, it's just a feature request.  :)
Yes, I wish `ElementsCollection` could contain others `ElementsContainer`s, not only `SelenideElement`. It was not of a high priority until now, but probably we will implement it now. 

### I am disagree with some of your sayings:

> no reload issue when the DOM updated

As I know, Selenium's `@FindBy`/`@FindBys`/`@FindAll` do **not** reload collection on every data change. They do lazy-loading, but not re-loading. 

> I am sure Selenide combination $/$$ and ElementsContainer can't handle all locate strategy of the page and don't need @FindBy anymore

Yes, Selenide `$`/`$$` does support all `By` strategies. 
Yes, You don't need `$FindBy` anymore. 100% sure. 
Moreover, Selenide `$`/`$$` methods do reload data (which Selenium's `@FindBy` does not).

**Comment by ansonliao** [comment]
@asolntsev 

I created a very simple project to show that `@FindBy/@FindBys` can be reload the DOM automatically, please check the project from the link: https://github.com/ansonliao/Selenium-RottenTomatoes

and you can run it by command line:
```bash
./gradlew clean test
```
 
The sample site is: https://www.rottentomatoes.com/browse/top-dvd-streaming/
![image](https://user-images.githubusercontent.com/6060224/79448025-578fd780-8013-11ea-9e24-5d2c36d9d38a.png)
![image](https://user-images.githubusercontent.com/6060224/79448093-670f2080-8013-11ea-9b82-a7ef1ab550fa.png)


scenario is: 
1. Open the url
2. Check the movie list and count the card number
3. Click `Show More` button to load more movie card
4. Check the movie list and count the card number again
5. Repeat step 3 and step 4 until `Show More` button disappeared
In the code, I only click the `show more` button by `Selenium` default method `WebElement#click()`, no extra reload action.

here is my test result screenshots:

![image](https://user-images.githubusercontent.com/6060224/79448185-8c9c2a00-8013-11ea-9b6d-2aaab49fa9b9.png)

`DVDPage#clickShowMore()`
![image](https://user-images.githubusercontent.com/6060224/79448230-a5a4db00-8013-11ea-92ae-c612e0f020e0.png)

**Comment by ansonliao** [comment]
@asolntsev 
Thanks for your replies, and I will study deeply of Selenide

**Comment by asolntsev** [comment]
@ansonliao thank you for the example project! I will try it any give a feedback.

**Comment by ansonliao** [comment]
@asolntsev , @vinogradoff 
I would like to consult that if we are separated page object class into two classes, for example, elements is one class, page behaviors is another class, how I can initialize the page object?

For example:
`HomeElements.java`
```java
public class HomeElements {
    SelenideElement userName = $("#username");
    SelenideElement password = $("#password");
    SelenideElement submit = $("#submit_button");
    SelenideElement errorMsg = $("#error");
    ...    // more than 20 elements
}

`HomePage.java`
```java
public class HomePage {
    HomeElements elements = new HomeElements();

    public HomePage() {
        // how to initialize the element class 
    }

    public HomePage enterUserName(String userName) {
        elements.userName.setValue(username);
    }

    ...
}
```

Thanks.

**Comment by asolntsev** [comment]
@ansonliao I don't think it's a good practice. The idea of page object (as any other Object in OOP) is to hide elements and expose behaviour.

**Comment by ansonliao** [comment]
@asolntsev 
I understand, and the reality that many pages include huge elements, and if the page also includes some ElementsContainer class or inner class of element block, the page.java will be huge with thousands of code lines.

**Comment by asolntsev** [comment]
In this case big page objects should be split to smaller page objects (you can call them widgets or ElementContainers). But each of them should have the same principle: hide elements, expose behaviour.

**Comment by vinogradoff** [comment]
<img width="1908" alt="Rotten Tomatoes: Movies | TV Shows | Movie Trailers | Reviews - Rotten Tomatoes 2020-04-22 13-30-04" src="https://user-images.githubusercontent.com/6568032/79976853-97384280-849d-11ea-82ea-aebf362a9791.png">

That's how I would typically break it in different files (widgetobjects). Then, if I have too many files (happens soon) - I toss them into packages (packages are up to test designer - grouped for functions, pages, whatever reads best).

**Comment by ansonliao** [comment]
@vinogradoff 
Could you kindly share some code about your solution? thanks.

**Comment by vinogradoff** [comment]
@ansonliao here is some code examples of how I typically define pageobject

https://github.com/vinogradoff/hackathon-2017/tree/master/src/test/java/lt/hackathon/pageobjects (amazon.com)

https://github.com/vinogradoff/advanced-selenide-example/tree/master/src/test/java/by/comaqa/advanced/tests/pagewidgets 
(https://demo.1crmcloud.com/login.php)

These PageObjects (actually more WidgetObjects) are never connected with each other outside the test.

I understand, that some people may want to connect them like this: `new HomePage().getHeader().getLogin().login(user,pwd)` I don't do this, it is my style. I just go with `new Login().login(user,pwd)` (which may reside in homepage.header package, though). Occama Razor style, if it works the same, why add more abstraction. :-)

I don't object if someone is using the other style, for me the criteria for a good test are two:
- it works
- it is well readable

**Comment by asolntsev** [comment]
@ansonliao I played with your project https://github.com/ansonliao/Selenium-RottenTomatoes - thank you once more for sharing it!

This is what I found:
1. Selenium DOES NOT reload elements/collections marked with `@FindBy`/`@FindBys`.
2. But HtmlUnit does reload. In your example you are using HtmlUnit page factory, not pure Selenium page factory.

**Comment by ansonliao** [comment]
@asolntsev 
Sorry, for a long time no reply on this thread.
I am running `Selenide` with the latest version `5.13.0`.

1. 
About the reload, I created a simple code by `Selenide`, looks like `$$` no automate reload function, please check the code below:

```java
public class testRottenTomatos {

    @BeforeMethod
    public void beforeMethod() {
        Configuration.browser = "chrome";
        Configuration.timeout = 20000;
    }

    @Test
    public void testDVDPage() {
        open("https://www.rottentomatoes.com/browse/top-dvd-streaming/");
        SelenideElement showMore = $("#show-more-btn > button").shouldBe(Condition.enabled);
        ElementsCollection movies;
        while (showMore.isEnabled()) {
            movies = $$(".mb-movies .mb-movie");
            System.out.println("====> movies: " + movies.size());
            showMore.click();
        }
    }
}
```

and the resulting screenshot as below:
![image](https://user-images.githubusercontent.com/6060224/87182592-0c861780-c317-11ea-9dd7-b2d1e42d7e34.png)



2. 
BTW, for this code above, I notice a case that in the code snippet:
```java
while (showMore.isEnabled()) {
    movies = $$(".mb-movies .mb-movie");
    System.out.println("====> movies: " + movies.size());
    showMore.click();
}
```
When I changed `while (showMore.isEnabled())` to `while (showMore.isDisplayed())`, the `while` block will be skipped to execute, may I know the difference between `SelenideElement#isEnabled()` and `SelenideElement#isDisplayed()`?

Thanks.

**Comment by ansonliao** [comment]
@asolntsev 
I solved the problem that `$$` reload issue, it is my code issue, I updated the code as below:
```java
    @BeforeMethod
    public void beforeMethod() {
        Configuration.browser = "chrome";
        Configuration.timeout = 20000;
    }

    @Test
    public void testDVDPage() {
        open("https://www.rottentomatoes.com/browse/top-dvd-streaming/");
        SelenideElement showMore = $("div[id='show-more-btn'] > button").shouldBe(Condition.enabled);
        ElementsCollection movies = $$("div[class='mb-movies'] div[class='mb-movie']").shouldBe(CollectionCondition.sizeGreaterThan(0));
        while (true) {
            System.out.println("====> movies: " + movies.size());
            if (isDisplayed(showMore)) {
                showMore.click();
                sleep(2000);
            } else {
                break;
            }
        }
    }

    private boolean isDisplayed(SelenideElement element) {
        try {
            return element.isDisplayed();
        } catch (Exception e) {
            return false;
        }
    }
```

another question about check the element is displayed or not, in the code: `if (isDisplayed(showMore))...`, 
if I use the `SelenideElement` condition method `.isDisplayed()`, like this:
`if (showMore.isDisplayed())...`, once the element is disappeared from the page, this statement will throw exception,
so I created a private method to handle it: `private boolean isDisplayed(SelenideElement element)`
could you kindly brief something like this checking functions (for example, check the element displayed and further whether enabled to click or not)that whether Selenide also included that maybe I don't know?

Thanks

**Comment by asolntsev** [comment]
@ansonliao Hi. 
1. Sorry, It's hard to understand what exactly have you changed. Just added `movies.shouldHave(sizeGreaterThan(0))`? Well, it's reasonable. 

2. I think you don't really need your method `isDisplayed` with try/catch inside. Because Selenide method `$.isDisplayed()` already does similar try/catch. See [implementation](https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/commands/IsDisplayed.java).

**Comment by ansonliao** [comment]
@asolntsev 
1.
The page `https://www.rottentomatoes.com/browse/top-dvd-streaming/` after loaded (Selenide#open(...) executed completed), I found that the movie card list still in the loading process and can't be visible, so just add this checking to wait for it to display `movies.shouldHave(sizeGreaterThan(0)`, it is only the sample page, don't need to pay more attention about it.
2. 
Finally, I used the `$.isDisplayed()` and it works now

**Comment by ansonliao** [comment]
I think we can close this issue.

**Comment by asolntsev** [comment]
Thought, there is a room for improvement. Thank you for the discussion.

**Comment by asolntsev** [comment]
Hi @ansonliao!
How is your migration going on? :)

I wanted to let you know that we fixed issue https://github.com/selenide/selenide/issues/482: now Selenide can reload ElementContainers etc. And page object fields can be of any custom type. It was done in [Selenide 5.17.0](https://selenide.org/2020/12/26/selenide-5.17.0/). 

Hopefully it also solves your issues with page objects.

**Comment by ansonliao** [comment]
Hi @asolntsev , we were already migrated the existed Selenium to `Selenide` framework, and integrated with `Allure` report, (but finally we will drop `allure` and migrate to `reporportal`

**Comment by asolntsev** [comment]
Glad to know it! :)
