### ISSUE TITLE
5.11 is missing com.codeborne.selenide/Selenide.java

### ISSUE THREAD

**Issue by jpratt2** [selenide/selenide#1113]
Is this known?
The file com/codeborne/selenide/Selenide.java is missing in the current version on github, 5.11.
https://github.com/selenide/selenide/tree/master/src/main/java/com/codeborne/selenide

It is present in 5.10, so I think this is an error.

**Comment by rosolko** [comment]
No, even in 5.10 this file isn't presented by this path:
https://github.com/selenide/selenide/tree/v5.10.0/src/main/java/com/codeborne/selenide

Any way it exists and located by this path:
https://github.com/selenide/selenide/blob/master/statics/src/main/java/com/codeborne/selenide/Selenide.java
