### ISSUE TITLE
handle different rendering of 'href' attribute that comes from Selenium Webdriver

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#1123]
GIVEN

```java
open("https://todomvc4tasj.herokuapp.com/");
SelenideElement element = browser.all("#filters li a").get(1);
WebElement webelement = element();
```

THEN
```java
webelement.getAttribute("outerHTML"); // => '<a href="#/active">Active</a>'
```
AND
```java
webelement.getAttribute("href"); // => 'https://todomvc4tasj.herokuapp.com/#/active'
```

have different results for 'href' attribute

Actually in browser inspector, we see href in DOM as `#/active`, and in browser console the js code will return `#/active`, 
![image](https://user-images.githubusercontent.com/1961118/79636093-ec164900-817d-11ea-9239-2aca0a0de0ca.png)

but if in browser inspector we hover mouse on the `href` attribute of element it will display hint with the "absolute rendering of the link". 
![image](https://user-images.githubusercontent.com/1961118/79636043-a6f21700-817d-11ea-9ef2-de6053561a65.png)

Seems like Selenium Webdriver simulates such "browser style rendering" for href... 
![image](https://user-images.githubusercontent.com/1961118/79636072-c1c48b80-817d-11ea-8bb4-9c185b18b5e8.png)

But then it becomes inconsistent with how Selenium Webdriver renders 'outerHTML' attribute... 
![image](https://user-images.githubusercontent.com/1961118/79636074-cbe68a00-817d-11ea-97f7-7a1590447be9.png)

Open Points:
- how to handle this in Selenide?
  - add option to Configuration.getAttributeByJs to be able to switch from webdriver to js rendering of all attributes?
- should it be improved on Selenium Webdriver side?
  - options:
    - make 'href' return relative url as in HTML?
    - improve 'outerHtml' return absoluter URL too? 

Why care?

Because the following code will fail:

```java
element.shouldHave(attribute("href", "#/active"));
```

![image](https://user-images.githubusercontent.com/1961118/79636033-8a55df00-817d-11ea-9b59-0407ff9fd25d.png)

And the user will be confused with such behaviour... 

Especially that error message will how that element has href attribute as expected...

**Comment by yashaka** [comment]
UPDATE

Actually the selenide message is more or less OK...

```
Element should have attribute href="#/active" {#filters>li>a[1]}
Element: '<a href="#/active" type>Active</a>'
Actual value: href="https://todomvc4tasj.herokuapp.com//#/active"
```

Not fully obvious... telling that element is `Element: '<a href="#/active" type>Active</a>'`
but the value of href (that we just saw as '#/active') is `"https://todomvc4tasj.herokuapp.com//#/active"`... Confuses a bit, but possible to understand...

but yet, if we care in selenide about "human readable API" I would think on how to improve and make the code: `$$("#filters>li>a").get(1).shouldHave(attribute("href", "#/active"))` to work as a user would naturally think about it... That's why we have Selenide over Selenium Webdriver - to provide a concise and readable API :)


P.S.
In selenium everything should be ok, since this is a feature. 
An excerpt from the official doc:

> "More exactly, this method will return the value of the property with the given name, if it exists. If it does not, then the value of the attribute with the given name is returned. If neither exists, null is returned."

**Comment by asolntsev** [comment]
Right now, I don't see any good+solution for this issue. 
Feel free to suggest any ideas.
