### ISSUE TITLE
Download files using CDP

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1127]
This is a feature request for those who cannot use proxy / href attribute.

**Comment by asolntsev** [comment]
Status update: it seems that CDP doesn't allow downloading of files. 
We can ask all network requests from CDP, but this info only includes URLs and headers, not the content of downloaded files.

**Comment by asolntsev** [comment]
Closing the issue because it seems technically impossible by now.

**Comment by BorisOsipov** [comment]
@asolntsev some news about this.

@artemryazantsev kindly shared with me the sample how to catch response body by CDP. See gist https://gist.github.com/BorisOsipov/d8243c58d258cf03f7e241d4ebab3845. Can you have a look? Maybe be we can use such approach.

Many thanks to @artemryazantsev

**Comment by asolntsev** [comment]
Wow. I will check it, thank you!

**Comment by asolntsev** [comment]
@BorisOsipov @artemryazantsev Unfortunately, this code still cannot get response body of downloaded files :( 
It gets response body of "usual" responses loaded by browser, but not bodies of downloaded files. 

See https://gist.github.com/asolntsev/b9cc80d923e41abf215a28e549dd5a10
