### ISSUE TITLE
Highlight matched elements

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#113]
[requested by Alexander Momot]

Подсветка (например мигание элементов), с которыми мы провзаимодействовали. Если бы можно было "помигать" элементами, которые нашли, и "озеленить" те, которые найдены (чтобы понять, насколько страница покрыта тестами) - было бы идеально!

**Comment by kkochetov** [comment]
https://github.com/codeborne/selenide/pull/392 it helps?
also i can (i think) add "green coverage" with this.

**Comment by symonk** [comment]
did you think more on this @asolntsev ? I don't think it has a place in selenide.  maybe in some sort of special mode, but if you want to do this you can just do it with a Selenium Listener implementation instead?

**Comment by BorisOsipov** [comment]
I don't think it is realy need.

**Comment by asolntsev** [comment]
@symonk Arguments against it:
- It's not really useful (needed)
- it doesn't solve any real problems
- it's impossible to implement highlighting that would look nice with every possible application design.

@BorisOsipov Arguments for it:
- Many people are asking for it. Though I personally think it's useless, it's a frequently requested feature. It wold be popular.

**Comment by rosolko** [comment]
@asolntsev @BorisOsipov From my point of view it shouldn't be a part of this library.
But if some one provide work code sample - we can easily place it on wiki as we do it for community conditions.

**Comment by asolntsev** [comment]
@rosolko there is a working code for highlighting elements: https://github.com/selenide-examples/gmail/blob/master/test/org/selenide/examples/gmail/Highlighter.java

**Comment by rosolko** [comment]
Awesome!
I think it's enough for self implementation/using and we can easily close this bug as completed. What do you think?

**Comment by jkromski** [comment]
I would love that feature. We wasted some time already because we were thinking that we selected right element. Having .flash() or enabling some kind develop mode which would highlight every single element which is used, would be awesome.

I get the point that this could be implemented by users, as many other things. My biggest point is, Selenide simplifies and helps creating tests. This is what helps preventing errors in finding right element. Love it

**Comment by jkromski** [comment]
and I will, but it would be great to have it in place/built-in. 

Before seeing that ticket I didn't know that it could be resolved this way. So I guess there are many users/developers/testers who still trying to find out if they found right element. If we could have it as built-in functionality then these users will appreciate a lot. This would be another argument to use Selenide instead of Selenium directly. 

some other testing frameworks solve these problems already this way or another
https://docs.cypress.io/guides/core-concepts/test-runner.html#Selector-Playground

**Comment by BorisOsipov** [comment]
My point is - Selenide is great tool for specific tasks. But we must not include all things that users want - it makes tool overcomplicated in use and support. It will be nice to follow some kind of unix way as may as we can.

**Comment by jkromski** [comment]
I get that, but this shouldn't be resolved only by opinions, and no general rules. Why reject that functionality over other? 

Why we have screenshots? They can be implemented by users, don't they?

It has been reported few times, which means people feel that this functionality should be in. It solves a problem which they have.

Out of Topic: would be good to define some rules on what should be added as a feature and what not, to avoid discussions like that.

**Comment by asolntsev** [comment]
@jkromski Sorry for the delay. It's important topic, I just lost it in my inbox. :(

And I don't see any problems with discussions. It's the essence of open source. It's the essence of community. It's the essence of democracy. We MUST discuss things. :)

I am afraid it's too hard (if impossible) to define such rules. I would suggest something like:

> Feature request can be implemented if
> 1. It conforms to the general Selenide mission
> 2. Many of Selenide users find it useful. Say, at least 30%? or 20%? Or 10%?
> 3. It's (more or less) equally understood by all Selenide users (like screenshots)
> 4. it doesn't cause harm for most of Selenide users

As you see, all these criteria are highly subjective. 
Highlighting of elements probably applies to (1) and maybe even (2), but not (3). The exact mechanism of highlighting (color, speed, animation etc) heavily depends on the application under test. I guess every Selenide user will want it _differently_. And (4) is problematic, because highlighting makes tests slower, needs more configuration parameters etc.

And last but not least: this feature request was registered year 2014, but nobody implemented it (except one PR which also had a long discussion, I don't remember details anymore). :( It's the main reason why we closed the issue. 

@jkromski If you wish, you can implement this feature. It's never late to reopen it. It's open source. :)

**Comment by symonk** [comment]
I don't think we should build it into the core library here,  A selenium custom listener can handle this if any user so wants too but in my opinion the use-case is very small.  Typically we do not 'watch' the automated tests running all the time, so I don't see what type of benefit this can offer.

**Comment by dstekanov** [comment]
Added example from [#113 (comment)](https://github.com/selenide/selenide/issues/113#issuecomment-434204797) to [How to visualize click](https://selenide.org/2019/12/06/advent-calendar-visualize-click/)

Seems this idea really should not be a part of the core Selenide project. 
Closing this ticket...
