### ISSUE TITLE
CollectionContition could accept `List<SelenideElement>` instead of `List<WebElement>`

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1135]
## The problem
It would be more convenient to use `Predicate<SelenideElement>` instead of `Predicate<WebElement>` in methods `allMatch`, `anyMatch`, `noneMatch`.

## Details

Now folks need to implement `allMatch` like this:

```java
trs.shouldBe(allMatch("all value same in column",
                    e -> e.findElements(By.tagName("td")).get(i).getText().equals(cellValue)));
```

it would be simpler if `allMatch` accepted `Predicate<SelenideElement>`:

```java
trs.shouldBe(allMatch("all value same in column",
                    e -> e.findAll("td").get(i).has(text(cellValue));
```

## Pros
The following things would be possible (which are not possible now):
* Navigation: search for inner elements using `e.find("[class*='<class-part>']")`
* Use `execute` methods from `SelenideElement`.
* Use pseudo-elements
* Use `Condition`s and other `SelenideElement` methods.

Note that current approach forces users to mix Selenium and Selenide syntax which is probably bad. 

## Cons:

I see a potential risk if folks use "waiting" methods of `SelenideElement` like `shouldHave`.  
The point of `$$.allMatch` and other collection checks is that they can wait (if condition is not satisifed yet). If we give access to `SelenideElement` inside `allMatch` (and other `CollectionCondition`), folks can call methods like `.shouldHave(…)`, and then we get "waiting inside waiting". It may become an untrackable nightmare.

**Comment by sergiomartins8** [comment]
sup @asolntsev 👋 

Well, I wanted to check if all the elements in a `ElementsCollection` were visible, which made me come across of the issue #33 and this issue itself.

Also, this makes so much sense, since I could do something like
```java
pageObject.someElementsCollectionExample()
                .shouldBe(allMatch("Description", SelenideElement::is(visible)));
```

However, currently I've this workaround (not even in production - _feel free to feedback_):

```java
pageObject.someElementsCollectionExample()
                .filterBy(visible)
                .shouldHaveSize(3);
```

Which doesn't seem right at all 🤷‍♂️ 

But, still something like https://github.com/selenide/selenide/issues/33#issuecomment-148029124 would suit best.

**Comment by asolntsev** [comment]
@sergiomartins8 I don't understand why you think `$$.filterBy(visible).shouldHaveSize(3);` is not right. I think it's total ok solution. 

Then only problem I see with all solutions described above is **performance**. Whatever way you iterate/filter the WebElements, it can be slow (if you have many elements). There is a way to filter them effectively, see https://selenide.org/2019/12/04/advent-calendar-effective-size-check/. But if you apply this, you don't need feature #1135 either #33.

**Comment by sergiomartins8** [comment]
Seems like a nice approach @asolntsev 
```java
@Test {
  assertEquals(1, sizeOf("#books .book:visible"));
}
``` 

The thing is that I don't want to use `asserts` on the test side. To keep it concise I've been using `should` variations only. 
Don't really wanna mix these two concepts since selenide provides these beauty expectations.

**Comment by asolntsev** [comment]
@sergiomartins8 Ok, I understand. 
I started thinking that probably we could add to Selenide this feature:
When you execute command `$$("#books .book:visible").shouldHave(size(1))`, Selenide loads only the number of elements using JavaScript without fetching the whole `WebElement` instances from WebDriver. It would be a great optimisation. 

I even think that all those checks like `$$("#books .book:visible").shouldHave(texts("foo", "bar", "zoo"))` could be done via JavaScript which would make them much more efficient.

I will register a separate issue for this idea.

**Comment by asolntsev** [comment]
Closing this feature request in favor of #1244.

I realized that it's ok for `Condition` and `CollectionCondition` implementations to use Selenium API, not Selenide API. They are low-level "bricks" for Selenide, and typical users don't need to implement them in most cases.
