### ISSUE TITLE
Selenide waitWhile() and waitUntil() functions ignore custom timeout if value exceeds certain number

### ISSUE THREAD

**Issue by SeleniumTestAB** [selenide/selenide#1137]
## The problem
Methods waitWhile() and waitUntil() do not wait full custom timeout but rather wait the global one if for example timeout value exceeds 10k of miliseconds

## Details
Tested on values such as 8000, 9000, 12000 and 50000. First two worked, the other ones did not work (selenide was waiting 9 sec at max). Condition used was "Visible".

## Tell us about your environment
* **Selenide Version**: 5.11.1 
* **Chrome\Firefox\IE Version**:  Chrome version 80.0.39
* **Browser Driver Version**: 
* **Selenium Version**: selenium 3 latest
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]
element.waitUntil(Condition.visible, 50000);
element.waitWhile(Condition.visible, 50000);

I also tested with Long.valueOf() function.

**Comment by SeleniumTestAB** [comment]
okay it seems 2 things i did bad:

1) using raw integer as value instead of using Long.valueOf() but maybe it should be converted inside selenide
2) using wrong condition to task. I wanted to wait until element dissapears so i did wrong wait method (should be waitWhile() instead of waitUntil(), my bad)

@asolntsev what do you think about first point?

**Comment by asolntsev** [comment]
@SeleniumTestAB Can you show the code? I cannot reproduce the problem.
