### ISSUE TITLE
Cannot set Firefox preference via system properties

### ISSUE THREAD

**Issue by takeya0x86** [selenide/selenide#1139]
## The problem
I tried to run test on Firefox. And some settings are required changing.
I wrote a below code to change Firefox settings.

```
// build.gradle
systemProperty 'firefoxprofile.prompts.tab_modal.enabled', 'true'
```

But I got an error message.

```
Preference prompts.tab_modal.enabled may not be overridden: frozen value=false, requested value=true
```

## Details
I have checked plain Selenium. I figured out that it works fine when using `FirefoxOptions#addPreference` instead of `FirefoxProfile`.

```java
// Success
FirefoxOptions options = new FirefoxOptions();
options.addPreference("prompts.tab_modal.enabled", true);
driver = new FirefoxDriver(options);

// Error
FirefoxProfile profile = new FirefoxProfile();
profile.setPreference("prompts.tab_modal.enabled", true);
FirefoxOptions options = new FirefoxOptions();
options.setProfile(profile);
driver = new FirefoxDriver(options);
```

Is it possible to change implementation to `FirefoxOptions#addPreference`?

## Tell us about your environment
* **Selenide Version**: 5.11.1
* **Chrome\Firefox\IE Version**: Firefox 75
* **Browser Driver Version**: 0.26.0
* **Selenium Version**: 3.141.59
* **OS Version**: macOS 10.15.4

## Code To Reproduce Issue [ Good To Have ]

In `build.gradle`

```
test {
    systemProperty 'firefoxprofile.prompts.tab_modal.enabled', 'true'
}
```
and run `./gradlew test`

**Comment by takeya0x86** [comment]
It's additional information. Please refer.
SeleniumHQ/selenium#7776
Selenium member said that
> Using FirefoxProfile is not required (and is not recommended) to instantiale a geckodriver-based FirefoxDriver.

**Comment by asolntsev** [comment]
Hi 
Currently Selenide only reads system properties with prefix `firefoxprofile.`. 
You can read implementation [here](https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/webdriver/FirefoxDriverFactory.java)

It seems that we should create another system properties for setting firefox options without `FirefoxProfile`.

NB! But do you really need to use system properties? Isn't it easier to just implement `WebDriverProvider`? See [doc](https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver)

P.S. Strange: I read [from the doc](https://developer.mozilla.org/en-US/docs/Mozilla/Using_tab-modal_prompts) that `tab_modal.enabled` is `true` by default. You should not need to set it explicitly.

**Comment by takeya0x86** [comment]
Thank you for comment! OK, I'll try to use custom `WebDriverProvider`.


> P.S. Strange: I read from the doc that tab_modal.enabled is true by default. You should not need to set it explicitly.

I know this. But using Selenide, `tab_modal.enabled` is overridden to `false`. 
I have investigated it. The `FirefoxProfile` class always loads many other settings and makes it immutable.
https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/java/client/src/org/openqa/selenium/firefox/FirefoxProfile.java#L48
https://github.com/SeleniumHQ/selenium/blob/selenium-3.141.59/javascript/firefox-driver/webdriver.json#L38

**Comment by asolntsev** [comment]
@takeya0x86 Thank you for the information! It helped a lot. 

Here is my results:
1. Selenide used `FirefoxProfile` to set downloads folder (preference `"browser.download.dir"`).
2. Thanks to your information, I found that `FirefoxProfile` is not really needed to set downloads folder. Much simpler option is `firefoxOptions.addPreference("browser.download.dir", "/folder");`
3. I will drop away using `FirefoxProfile` in Selenide 5.12.0, which should solve your problem.

**Comment by asolntsev** [comment]
Done in https://github.com/selenide/selenide/pull/1165
