### ISSUE TITLE
Selenide hangs forever trying to close unused webdrivers

### ISSUE THREAD

**Issue by HenningThiemann** [selenide/selenide#1147]
## The problem
Selenide hangs forever trying to close unused webdrivers.

## Details
Selenide tries to close unsed webdrivers at the end of a session. Whilst this is a good idea generally, it causes an infinite loop, if you already stopped the webdriver before (manually).
The InterruptedException is never thrown and as a result, the while(true) loop is never terminated. https://github.com/selenide/selenide/blob/76ba86d999cc9fca6479697f31edef5c312eb7c9/statics/src/main/java/com/codeborne/selenide/impl/UnusedWebdriversCleanupThread.java#L32

Log Message:
[Webdrivers killer thread] INFO  com.codeborne.selenide.impl.UnusedWebdriversCleanupThread.closeUnusedWebdrivers - Thread 1 is dead. Let's close webdriver RemoteWebDriver

..remains in this state for some minutes.

Would be a good idea to implement a maximum count (e.g. 10) to terminate the loop afterwards.

## Tell us about your environment
* **Selenide Version**: 5.11.1 
* **Chrome\Firefox\IE Version**: Browserstack, Chrome 79 on Windows 10
* **Selenium Version**: 3.141.59

**Comment by asolntsev** [comment]
@HenningThiemann Could you provide some code to reproduce the problem?

I tried just now, and cannot reproduce it. `UnusedWebdriversCleanupThread` is a separate daemon thread which checks for unused browsers every 100 ms. If all tests are completed, it just silently dies. I don't observe any problems with it.

**Comment by asolntsev** [comment]
Feel free to reopen when provided code to reproduce the problem.
