### ISSUE TITLE
retry merchant

### ISSUE THREAD

**Issue by roughsoft** [selenide/selenide#1151]
how can I retry some action，for example I want to retry three times when I visit the page and I failure。

**Comment by asolntsev** [comment]
@roughsoft Selenide already does re-try for all `$.should*` and `$$.should*` methods automatically. You don't need to configure anything. 

E.g. method `$("button").click()`
1. tries to click the button
2. if ok - test goes on.
3. if failed - Selenide does re-try (up to 4 seconds by default)
4. if all re-tries failed, test will fail after 4 seconds.
