### ISSUE TITLE
about roadmap

### ISSUE THREAD

**Issue by roughsoft** [selenide/selenide#1158]
where I can get these information？Thank you

**Comment by asolntsev** [comment]
Hi @roughsoft .
I marked all "important" issues with label "roadmap". 

Here is the Selenide roadmap:  https://github.com/selenide/selenide/issues?q=is%3Aissue+is%3Aopen+label%3Aroadmap

**Comment by asolntsev** [comment]
@roughsoft Thank you for your question. I published a separate page for [Selenide roadmap](https://github.com/selenide/selenide/wiki/Roadmap)
