### ISSUE TITLE
any plan about testing winapp

### ISSUE THREAD

**Issue by roughsoft** [selenide/selenide#1159]
integrate windowsapp driver？

**Comment by rosolko** [comment]
no

**Comment by asolntsev** [comment]
@roughsoft what is windowsapp driver? Can you give a link?

If it's written in Java and implements WebDriver standard, it can be easily integrated with Selenide.

**Comment by roughsoft** [comment]
https://github.com/microsoft/WinAppDriver
@asolntsev

**Comment by asolntsev** [comment]
@roughsoft Thank you for the link. 
At a first glance, it seems that WinAppDriver implements `WebDriver` protocol, which means that it can be used with Selenide out-of-the-box. No special support needed.

Feel free to share your experience or any ideas how can we improve this integration.

**Comment by roughsoft** [comment]
need some more work！
https://medium.com/@licanhua/automated-windows-ui-testing-by-jest-selenium-appium-selenium-webdriver-winappdriver-6cb708121d71
can you make some example？
