### ISSUE TITLE
describe.each(table)(name, fn, timeout)

### ISSUE THREAD

**Issue by roughsoft** [selenide/selenide#1160]
describe.each(table)(name, fn, timeout)

Use describe.each if you keep duplicating the same test suites with different data. describe.each allows you to write the test suite once and pass data in.

https://jestjs.io/docs/en/api#describeeachtablename-fn-timeout

how can I do it in selenide？

**Comment by roughsoft** [comment]
@asolntsev

**Comment by asolntsev** [comment]
It's called "Parameterized Tests".
It's a responsibility of testing framework (JUnit or TestNG), not Selenide.

For example: https://www.baeldung.com/parameterized-tests-junit-5
