### ISSUE TITLE
Redesign of selenide.org to support mobile devices

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1161]
## The problem
Current design of selenide.org doesn't look well on smartphones.  
We need to redesign it. 

## Current status
We have a new design project: https://selenide.org/selenide-site-ng/
* Source code: https://github.com/selenide/selenide-site-ng.git

But the site content is not migrated yet :(

**Comment by s4ik4t** [comment]
Is there anything I can help you with?

**Comment by asolntsev** [comment]
FINALLY!!!

I have tuned the CSS of existing design, so no selenide.org looks friendly on mobile devices.
