### ISSUE TITLE
Upgrade to Selenium 4

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1162]
### Are we going to support Selenium 4?

Yes. 

We already have a green pull request: https://github.com/selenide/selenide/pull/1099

We will merge it once Selenium 4 is released.

### Can I try it right now?
You already can use this version. 

1. Add this repo to your project:

```
repositories {
    maven { url 'https://jitpack.io' }
}
```

2. Add this dependency:

```
dependencies {
  implementation("com.github.selenide:selenide:upgrade-to-selenium4-alpha5-SNAPSHOT")
}
```

**Comment by asolntsev** [comment]
Mark this issue as done (see PR https://github.com/selenide/selenide/pull/1099)

**Comment by Livira** [comment]
Hi guys,  I've added the dependency but facing some difficulties with accessing the underlying selenium4 features from Selenide.
When I create Chromedriver via new I can access the respective methods, like
```
ChromeDriver driver = new ChromeDriver();
DevTools devTools = driver.getDevTools();
...
```
However, when I call WebDriverRunner.getWebDriver() - I cannot see the selenium4 related methods.

**Comment by asolntsev** [comment]
Hi @Livira !
Which dependency have you added? Selenium or Selenide? 

Current Selenide version cannot work with Selenium 4 because SE4 is not backward-compatible.
Once SE4 is released, we will immediately release a compatible Selenide version.

**Comment by Livira** [comment]
Thank you for the answer, 
I've added Selenide dependency, the one from the comment above 'com.github.selenide.selenide:grid:upgrade-to-selenium4-beta-1-SNAPSHOT'.
I was mistakenly thought that this dependency will allow me to play around with new Selenuim4 features under Selenide.
I was able to use Selenuim4 new methods, but not via the driver wrapped by Selenide

**Comment by asolntsev** [comment]
@Livira That's right, dependency `com.github.selenide.selenide:grid:upgrade-to-selenium4-beta-1-SNAPSHOT` should allow you to play around with new Selenuim4 features under Selenide. 

Then we probably need to investigate why you cannot do it. I think that method `WebDriverRunner.getWebDriver()` should return a new `ChromeDriver` from SE4 with all its new methods...

**Comment by Livira** [comment]
Thank you!
It would be nice if WebDriverRunner.getWebDriver() returns SE4 chromedriver

**Comment by berrezzka** [comment]
Hi! 
I'm trying to add a dependency to my maven project and getting the error 
**'Could not find artifact com.codeborne:selenide:pom:6.0.0-beta-1-SNAPSHOT in jitpack.io (https://jitpack.io)'**

What I'm doing wrong?

Added to my pom.xml:

repository:
```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
```
dependency:

```
        <dependency>
            <groupId>com.github.selenide.selenide</groupId>
            <artifactId>grid</artifactId>
            <version>upgrade-to-selenium4-beta-1-SNAPSHOT</version>
        </dependency>
```

**Comment by BorisOsipov** [comment]
@berrezzka known issue. jitpack builds are broken now.

**Comment by korabel00** [comment]
Could not find com.github.selenide.selenide:grid:upgrade-to-selenium4-beta-1-SNAPSHOT.
Why is this happening?
build.gradle.kts:
repositories {
    mavenCentral()
    jcenter()
    maven { url = uri("https://jitpack.io") }
}

**Comment by asolntsev** [comment]
@korabel00 Yes, Jitpack builds have been broken for a while :(

I hope we will fix them soon, but meanwhile you can just use Selenide version `6.0.0-beta-1-SNAPSHOT`:

```
dependencies {
  testImplementation 'com.codeborne:selenide:6.0.0-beta-1-SNAPSHOT'
}

repositories{
  mavenCentral()
  maven {
    url uri('https://oss.sonatype.org/content/repositories/snapshots/')
    mavenContent {
      snapshotsOnly()
    }
  }
}

```

**Comment by korabel00** [comment]
Thank you, Anton!

**Comment by korabel00** [comment]
But with this one (6.0.0-beta-1-SNAPSHOT) seems like I cannot play around with getDevTools() stuff

**Comment by BorisOsipov** [comment]
@korabel00 you can. see an example https://github.com/BorisOsipov/selenide-devtools-example/blob/master/src/test/java/com/example/demoselenideselenium4/MainPageTest.java

**Comment by korabel00** [comment]
Thanks a lot, Boris!

**Comment by ysamarin** [comment]
> @korabel00 you can. see an example https://github.com/BorisOsipov/selenide-devtools-example/blob/master/src/test/java/com/example/demoselenideselenium4/MainPageTest.java

selenide with devtools only working for local run ? selenoid (remote web driver) isn't supported ?

**Comment by BorisOsipov** [comment]
@ysamarin
>selenide with devtools only working for local run 

It is not selenide feature. It is selenium 4 feature.

> selenoid (remote web driver) isn't supported ?

Selenium grid v4 supported out of the box by selenium team.
Selenoid is not supported due incompatible api see https://github.com/aerokube/selenoid/issues/1063

But you can implement it manually, see example

https://github.com/BorisOsipov/selenide-devtools-example/blob/master/src/test/java/com/example/demoselenideselenium4/MainPageTest.java#L52

**Comment by ysamarin** [comment]
@BorisOsipov Thanks !

**Comment by s4ik4t** [comment]
@asolntsev @BorisOsipov is there any plan to update the Selenide beta with the latest Selenium 4 RC version?

**Comment by rosolko** [comment]
@s4ik4t You can track progress in a https://github.com/selenide/selenide/pull/1407

**Comment by asolntsev** [comment]
@s4ik4t You can use version `com.codeborne:selenide:5.24.3-selenium-4.0.0-rc-1` to get latest Selenide+Selenium4.

**Comment by s4ik4t** [comment]
Awesome, thanks 👍

**Comment by Fra1do** [comment]
Hello. I have problem with mass run tests. There are a lot of tests fallen with error
`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '4.0.0-rc-1', revision: 'bc5511cbda'
System info: host: '21846d2371f1', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-73-generic', java.version: '16-ea'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--verbose], extensions: []}}], desiredCapabilities=Capabilities {browserName: chrome, enableLog: true, enableVNC: true, enableVideo: true, goog:chromeOptions: {args: [--verbose], extensions: []}}}]
Capabilities {}`

**Comment by BorisOsipov** [comment]
@Fra1do 

1) Mixing rc1 and beta-4 dependencies is not good idea
2) Probably it is your test infrastructure(selenoid\moon) issue not selenide
