### ISSUE TITLE
Unexpected browser close

### ISSUE THREAD

**Issue by StanislavSelen** [selenide/selenide#1172]
## The problem
I want the browser to remain open after work. Instead, it closes. Moreover, the parameter Configuration.holdBrowserOpen = true.

## Details
Configuration.timeout = 30000;
Configuration.startMaximized = true;
Configuration.holdBrowserOpen = true;
Configuration.browser = ChatCbDriver.class.getName();

## Tell us about your environment
* **Selenide Version**: 5.11.1
* **Chrome\Firefox\IE Version**: Chrome81.0.4044.138, (64)
* **Browser Driver Version**: 81.0.4044.138
* **Selenium Version**: 3.141.59
* **OS Version**: macOS Catalina 10.15.4

## Code To Reproduce Issue [ Good To Have ]
After closing the browser, there are messages in the console:
UnusedWebdriversCleanupThread:44 - Thread 20 is dead. Let's close webdriver ChromeDriver: chrome on MAC (5671c8cc757521bc92f0c2ec30147e89)
INFO  CloseDriverCommand:18 - Hold browser and proxy open: 63 -> ChromeDriver: chrome on MAC (null), null
Disconnected from the target VM, address: '127.0.0.1:52651', transport: 'socket'

**Comment by asolntsev** [comment]
I cannot reproduce the issue. Can you share a code that would help me?

**Comment by StanislavSelen** [comment]
Maven project - https://github.com/StanislavSelen/selenideCucumberParallel
Run - mvn test

The problem appears when I try to run tests on multiple threads using cucumber - [link](**url**)


```
@Override
@DataProvider(parallel = true)
public Object[][] scenarios() {
    return super.scenarios();
}
```

If remove the parallel launch, the problem will disappear.

**Comment by asolntsev** [comment]
Thank you for the example!
Now I can reproduce the problem.

1. Do you see these warnings when you run your tests?
```
[INFO] Running runner.RunTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

It clearly says that you need to add SLF4J implementation to the project, otherwise you cannot see Selenide logs.

2. When you do it, you will see that Selenide closes the webdriver when a thread dies.

3. It's a bug in Selenide: in some cases it closes the webdriver despite of `holdBrowserOpen` setting. I will fix it in next release.
