### ISSUE TITLE
Add ability to click SelenideElement via JS/Selenium without changing Configuration.clickViaJs global parameter

### ISSUE THREAD

**Issue by artemryazantsev** [selenide/selenide#1173]
## Add ability to click SelenideElement via JS/Native(Selenium) click 
I'd like to have ability to click SelenideElement via JS/Selenium click without changing Configuration.clickViaJs global parameter.

As @asolntsev mentioned in Telegram chat it potentially can be:

> 
Да, возможно, стоит сделать. Но тогда, наверное, не методы $.click() и $.clickViaJS(), а что-нибудь более общее, типа $.click(ClickOptions options).

## Details
It is a common case when only JS clicks work for some elements and at the same moment these JS clicks don't work for other elements (e.g. react-js app in my case). And it would be great to have an ability to combine click types directly via Selenide without self-created JS/Selenium helper classes.

Current implementation doesn't provide an ability to click SelenideElement via JS/Selenium , user should select click type by setting `Configuration.clickViaJs = true/false `parameter

**Comment by asolntsev** [comment]
implemented by https://github.com/selenide/selenide/pull/1226
