### ISSUE TITLE
waitUntil(visible, 500000) times out after 4 seconds

### ISSUE THREAD

**Issue by pgianino** [selenide/selenide#1180]
## The problem
Sorry if I am missing the answer in prior posts, but I am new Selenide, GitHub, etc.  I want my test to wait up until 50 seconds for a page element to be visible.  When I run as JUnit, the Java console shows that it timed out at 4 seconds.  I tried using sleep(50000) and that worked, but I don't want to hardcode that long of a wait if the element becomes visible sooner.  Also - this might be the same issue I am having Selenide finding elements sometimes and not finding the same elements other times, and I generally have a "standard" condition of "waitUntil(visible, 10000)".

## Details
Here is the console output:
Element should be visible or transparent: visible or have css value opacity=0 {By.xpath: //*[@id="searchdetail"]/div/div[1]/a[1]}
Element: '<a data-bind="click: searchCustomer, css: { selected: SearchMode() == 'Customer' }" displayed:false></a>'
Actual value: visible:false, 1
Timeout: 4 s.

## Tell us about your environment
* **Selenide Version**: 5.6.1
* **Firefox Version**: 76.0.1 (64-bit)
* **Browser Driver Version**: Sorry - not sure how to identify that, but it would have been downloaded when I started the project in January
* **Selenium Version**: Sorry - not sure how to find that, but it would have been downloaded when I started the project in January
* **OS Version**: Windows 10 Enterprise, 10.0.17763 Build 17763

## Code To Reproduce Issue
$(By.id("searchinput")).waitUntil(visible, 500000).click();

**Comment by asolntsev** [comment]
@pgianino Sorry, I cannot reproduce the issue. 
I am running command `$(By.id("searchinput")).waitUntil(visible, 500000).click();`, and it doesn't fail after 4 seconds. It lasts for a long time. 

Could you share the whole code?

**Comment by pgianino** [comment]
Thanks for reaching out to me.  The line of code is a method in the activateSearchFor method in a PageObject class,.  The main Test class calls searchCustomer in the PageObject class, which in turn calls activateSearchFor in the same PageObject class.

Aside from the possibility of any issue with the code, is there something else needed to override any default timeout settings in Selenide, Selenium, etc?

package com.domain.pageobjects;

import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Condition.enabled;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$$;
import com.codeborne.selenide.ElementsCollection;
import static com.codeborne.selenide.Selenide.sleep;

import org.openqa.selenium.By;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.yandex.qatools.allure.annotations.Step;

public class LLHome extends DefaultObjects {
    
    protected static Logger logger = LoggerFactory.getLogger(LLHome.class);

	// SearchCustomer
    @Step("Search Customer")
	public LLHome searchCustomer(String customer) {
		activateSearchFor();
		activateCustomerSearch();
		setByIdAndGo("searchinput", customer);
		selectCustomerFromSearchResults();
		return this;
	}
	
	// Activate SearchFor
    @Step("Activate Search For")
	public LLHome activateSearchFor() {
		$(By.id("searchinput")).waitUntil(visible, 50000).click();
		logger.info("Activated Search For");
		return this;
	}

}

**Comment by asolntsev** [comment]
@pgianino Sorry, but your answer doesn't help me to reproduce the issue. :( 

Sure, you can override the default timeout in Selenide:

```java
Configuration.timeout = 8000;
```

Probably this video can help: https://selenide.org/2015/09/23/selenide-on-seleniumconf/

**Comment by pgianino** [comment]
Thanks looking into it and for the link.  I know how hard it is to reproduce someone else's entire environment and code.  For whatever it is worth, I've been playing around today and so far I see that a waitUntil of up to 23000 seems to work - ie; it times out at the milliseconds I specify (23 seconds, 20 seconds, 10 seconds).  But once I cross over to 24000, 25000, 30000, 50000 - it consistently times out at 4 seconds (according to my console output).

**Comment by BorisOsipov** [comment]
@pgianino 
>I know how hard it is to reproduce someone else's entire environment and code.

Sure, we understand it.
Could you please share with us full error stack trace? Or even better the gist with full test log if it is possible. 

Maybe this will give us some insight why the issue appears.

**Comment by pgianino** [comment]
Hopefully my masking of company-specific info doesn't get in the way of analyzing the Tracelog and the Console output.

[selenide_1180_Tracelog.TXT](https://github.com/selenide/selenide/files/4713502/selenide_1180_Tracelog.TXT)

[selenide_1180_Console.TXT](https://github.com/selenide/selenide/files/4713503/selenide_1180_Console.TXT)

**Comment by asolntsev** [comment]
@pgianino Thank you for the logs. Now it's clear.

Let's consider this line:

```java
$(By.id("searchinput")).waitUntil(visible, 50000).click();
```

it consists of two calls:
1. `$(By.id("searchinput")).waitUntil(visible, 50000);`
2. `$(By.id("searchinput")).click();`

The first call works successfully (element is visible), but the second one fails. And it has default timeout (4 seconds).

**Comment by pgianino** [comment]
Not sure I understood if you were making a suggestion, but today I separated the two calls to match what you showed, and the output stills shows a 4s timeout  occurred on the waitUntil(visible, 50000).

Do you have another suggestion that I could try?

Thanks again.

**Comment by asolntsev** [comment]
@pgianino please show the new stacktrace after splitting the two calls.

**Comment by pgianino** [comment]
[selenide_1180_Tracelog 2.TXT](https://github.com/selenide/selenide/files/4724560/selenide_1180_Tracelog.2.TXT)

[selenide_1180_Console 2.TXT](https://github.com/selenide/selenide/files/4724561/selenide_1180_Console.2.TXT)

Thanks.

**Comment by asolntsev** [comment]
@pgianino Thank you. I see from the last stacktrace that the `click` method fails with timeout 4 seconds:

```java
Element should be visible or transparent: visible or have css value opacity=0 {By.xpath: //*[@id="searchdetail"]/div/div[1]/a[1]}
...
Timeout: 4 s.
...
	at com.codeborne.selenide.commands.Click.execute(Click.java:13)
...
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy93.click(Unknown Source)
	at com.MyDomain.pageobjects.MyAppHome.activateCustomerSearch(MyAppHome.java:101)
	at com.MyDomain.pageobjects.MyAppHome.searchCustomer(MyAppHome.java:72)
	at com.MyDomain.demo.MyAppDemoTest.shouldCreateNewQuoteAndReturnPremium(MyAppDemoTest.java:30)
```

**Comment by pgianino** [comment]
@asolntsev Great catch!!  I apologize if I misread it before.  Last question (I hope) - what would cause a Click action to timeout if the object/element was already visible or enabled?  Maybe I can improve my test code?  Or there might be something in the application code that this is showing us, or maybe even something in the network communication that is slow to respond to the click?

Many thanks for your time on this !!

**Comment by asolntsev** [comment]
@pgianino It depends on your application. The error message clearly says that at moment of clicking, the element was not visible. Only you can know why.

P.S. In your code above you showed that you are clicking element `$(By.id("searchinput"))`, but in the error message I can read that you are actually trying to click another element: `By.xpath("//*[@id="searchdetail"]/div/div[1]/a[1]")`.

**Comment by pgianino** [comment]
Thanks for your help.  With that in mind, I have some ideas and possible solutions.  I also googled "selenium click timeout" and found that folks have hit similar issues with the Click action when using Selenium so I might borrow from those solutions to integrate with my Selenide test.

I agree that this item is Closed.
