### ISSUE TITLE
Add method $.as("name") to give elements human-readable names

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1200]
## The problem
People often have to use long unreadable locators. They want to give them a short readable names which could be seen in logs or reports.

## Tell us about your environment
* **Selenide Version**: 5.12.2

## Code To Reproduce Issue [ Good To Have ]

```
$(By.xpath("/long/ugly/xpath[1][2][3]")).as("Login button").click();
```

**Comment by asolntsev** [comment]
@sergiomartins8 Good point. If you declare By or Xpath as a constant, you can give this constant a readable name. 
The suggested `as` method can help in case when you don't declare a constant, but use short note `$("/x/y/z").as("login button").click();`.

**Comment by romansvesh** [comment]
There are another case too: with "as" we can use names in another language.
