### ISSUE TITLE
"IllegalStateException: No webdriver is bound to current thread: 19. You need to call open(url) first." whith  .stream().parallel() 

### ISSUE THREAD

**Issue by borysras** [selenide/selenide#1204]
## The problem
When I use .stream().parallel()  in my tests the test is failing with the next error message "IllegalStateException: No webdriver is bound to current thread: 19. You need to call open(url) first."

## Details
Faills only if used .parallel() in stream

## Tell us about your environment
* **Selenide Version**: 5.3.1 but tried on lower

## Code To Reproduce Issue [ Good To Have ]
numbers.stream()
                            **.parallel()**
                            .map( number -> getValue( Name, number ) )
                            .collect(
                                    Collectors.toList() );
}

**Comment by asolntsev** [comment]
@borysras Just don't `.parallel()` :)

WebDriver is not thread-safe. It's not intended to use in parallel threads.

**Comment by borysras** [comment]
but this construction works well with selenium...

**Comment by asolntsev** [comment]
Yes, it may occasionally work, but WebDriver doesn't guarantee to work in parallel threads. 
Selenide just makes sure you don't do it occasionally. 

Still, why do you want to use `.parallel()` in this case? 
If you want to speed up your tests, I can suggest a better solution.

**Comment by borysras** [comment]
Yes, I do this to speed up my tests. What solution do you have?

**Comment by asolntsev** [comment]
Use JS. With one JavaScript call, you can quickly get all numbers.
See slides 18-23 in [this presentation](https://docs.google.com/presentation/d/1tV_jk3XAZW_PqJ0IBPROe_-0O8GE_6O0QfydgqJd7B8/edit?usp=sharing).

**Comment by borysras** [comment]
Thanks! I`ll try)
