### ISSUE TITLE
Angular MatDialog

### ISSUE THREAD

**Issue by NickMeert-dev** [selenide/selenide#1218]
I can't acces the elements inside my Angular MatDialog.

`<mat-dialog-container aria-modal="true" class="mat-dialog-container ng-tns-c40-41 ng-trigger ng-trigger-dialogContainer ng-star-inserted" tabindex="-1" id="mat-dialog-3" aria-labelledby="mat-dialog-title-3" style="transform: none;"><!----><minfin-information-creation-view _nghost-tux-c41="" class="ng-star-inserted"><h1 _ngcontent-tux-c41="" class="mat-dialog-title" mat-dialog-title="" id="mat-dialog-title-3">Information</h1><mat-dialog-content _ngcontent-tux-c41="" class="mat-dialog-content ng-untouched ng-pristine ng-invalid"><mat-form-field _ngcontent-tux-c41="" appearance="outline" class="mat-form-field ng-tns-c8-42 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float ng-untouched ng-pristine ng-invalid"><div class="mat-form-field-wrapper"><div class="mat-form-field-flex"><!----><!----><div class="mat-form-field-outline ng-tns-c8-42 ng-star-inserted" style=""><div class="mat-form-field-outline-start"></div><div class="mat-form-field-outline-gap">`

What do i do to acces the dialog?

**Comment by rosolko** [comment]
Can you please add details? What element you're trying to get? How? What error displayed? Because as for now this issue looks invalid

**Comment by NickMeert-dev** [comment]
it seems to work but when i close a dialog and re-open and select the same input field (in 1 test), the ID given by angular adds 1
so when adding custom IDs it works, still thanks for replying so fast

![image](https://user-images.githubusercontent.com/52421597/86021706-ad2c2b80-ba29-11ea-8a3a-f3d4dc218598.png)

**Comment by rosolko** [comment]
Still not clear behavior. From your description it looks like something wrong with application under test.

**Comment by NickMeert-dev** [comment]
i'll try to explain clearly: after i open my dialog the id of my input field is "mat-input-6" , when i close it and open it again it is "mat-input-7" and so on.

But apparently this is normal angualr behaviour, so testing with angular $(By.id(standard angular id)) is pretty unstable when doing multiple things in 1 session because of the changing

**Comment by rosolko** [comment]
So, as I sad before - this problem in application, not in selenide. 
This case you need to watch and take care of id and it's representation in a selector by yourself. 
Web applications based on a tons of different framework and we physically can't support them all.
I advise you to simply increase counter on each access to to dialog and pass into selector string.

**Comment by asolntsev** [comment]
@NickMeert-dev Then you can use
1. in the beginning - `$("mat-input-6")`
2. and after re-opening - `$("mat-input-7")`
Why you call it unstable?

**Comment by NickMeert-dev** [comment]
unstable is a wrong word of choice, it was just unexpected behaviour when doing tests in random order
