### ISSUE TITLE
Duplicate Browser sessions created in Parallel Testing

### ISSUE THREAD

**Issue by sahilsehgals4392** [selenide/selenide#1219]
## The problem
Hi All,
I am trying to execute parallel testing unsing TestNG (parallel=tests) configuration.
I am passing browser and platform at runtime via TestNG parameters and using @BeforeClass annotation in test class

## Details
Although 2 different browsers are passed in testNg parameters , the both the tests get executed on same browser (chosen randomly bw chrome/ff)

## Tell us about your environment
* **Selenide Version**: 5.11.1
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 3.141.59
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]
TestNG.xml
--------------------------------------------------------------------
       <suite name="Parallel Suite " parallel="tests" thread-count="2">
       <test name="Local FF Browser Test">
        <parameter name="browser" value="ff"/>
        <parameter name="platform" value="windows"/>
                <classes>
            <class name="tests.ClassA"/>
        </classes>
    </test>
    <test name="Local Chrome Browser Test">
        <parameter name="browser" value="Chrome"/>
        <parameter name="platform" value="windows"/>
        <classes>
            <class name="tests.ClassA"/>
        </classes>
    </test>
</suite>

ClassA:
@BeforeClass
    @Parameters({"platform", "browser"})
    public void setup(@Optional("windows") String platform, @Optional("chrome") String browser) {
                app.launch(platform, browser);
    }

App.Launch is internally calling browser launcher which has a if-else statement of kind:
if (browser.equalsIgnoreCase("chrome")) {
			Configuration.browser = WebDriverRunner.CHROME;
		}
else if{.......
}...
open();

**Comment by asolntsev** [comment]
@sahilsehgals4392 Yes, you cannot run two different browsers in the same JVM. It's because `Configuration.browser` is a static field, it cannot have 2 values at the same time.

I recommend to run parallel tests **in processes, not in threads**. It's easy to do just by settings `<forkCount>3</forkCount>`. See https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html

**Comment by asolntsev** [comment]
@sahilsehgals4392 Even better solution is to use different Maven profiles for different browsers. And use parallel test execution to parallelize tests with one browser. 

See for example: https://github.com/selenide-examples/google/blob/master/pom.xml

**Comment by sahilsehgals4392** [comment]
@asolntsev , Thanks for the confirmation.
I was sensing the same that i could be due to Static nature of Configuration.Browser.

Thanks & Regards,
Sahil Sehgal

**Comment by vrnvorona** [comment]
@asolntsev What about parallelising browsers though?

**Comment by asolntsev** [comment]
@vrnvorona What exactly are you suggesting?

**Comment by vrnvorona** [comment]
@asolntsev Not suggesting, merely asking how I can achieve parallel test execution on multiple browsers without Configuration.Browser. I see that most Selenide methods use static driver thought getSelenideDriver(), thus I don't know how to get parallel browsers instead of one browser with parallel tests.

Though maybe consecutive browsers with parallel tests is better?

**Comment by asolntsev** [comment]
@vrnvorona I answered this question earlier: https://github.com/selenide/selenide/issues/1219#issuecomment-653434421

**Comment by vrnvorona** [comment]
@asolntsev so basically run as in this example from different terminal instances? ./gradlew chrome from one, ./gradlew firefox from another etc?

**Comment by asolntsev** [comment]
@vrnvorona yes, you can run `./gradlew chrome` in one terminal, and `./gradlew firefox` in another terminal. 

Another options are:
1. Run with single command: `./gradlew chrome & ./gradlew firefox && fg`
2. Create two separate jobs in Jenkins, one for `./gradlew chrome` and another for `./gradlew firefox`.
