### ISSUE TITLE
Concise UI automate with Java!

### ISSUE THREAD

**Issue by roughsoft** [selenide/selenide#1223]
Concise UI automate with Java!
change vision to these：test，rpa，web automate，desktop UI automate

**Comment by asolntsev** [comment]
@roughsoft What do you mean? do you want to request some feature or suggest some changes in code or site?

**Comment by roughsoft** [comment]
I think selenide is great work!
It can do more things, no only test field.
It can do web automate,desktop ui automate,rpa.

**Comment by asolntsev** [comment]
Thank you for the feedback!
