### ISSUE TITLE
Shortcut for BASE64 encoded screenshot 

### ISSUE THREAD

**Issue by SergeyPirogov** [selenide/selenide#1224]
## The problem
Selenide can be used to conduct screenshot based testing to check layout. But many tools that we have to integrate with requires Base64 encoded screenshots. Now we can do it as:

```
((TakesScreenshot) WebDriverRunner.getWebDriver()).getScreenshotAs(OutputType.BASE64)
```

It would be better to have 
```
Selenide.screenshot(OutputType.BASE64)
```

**Comment by asolntsev** [comment]
implemented in https://github.com/selenide/selenide/pull/1231

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/1231
