### ISSUE TITLE
Add CollectionCondition for checking cssclass, attribute value

### ISSUE THREAD

**Issue by arturmkr** [selenide/selenide#1228]
It would be great to have CollectionCondition for checking elements of Collection for having css class or attribute.

So instead of following:
```
    ElementsCollection listElements = $$("div.list");
    for (SelenideElement el : listElements) {
      el.shouldHave(not(cssClass("selected")));
      el.shouldHave(attribute("dataId","TestValue"));
    }
```

Would be something like this:
```
listElements.shouldHave(not(cssClass("selected")));
listElements.shouldHave(attribute("dataId","TestValue"));
```

**Comment by asolntsev** [comment]
Almost the same effect can be achieved using `forEach` method:

```java
    listElements.forEach(el -> el.shouldHave(not(cssClass("selected"))));
    listElements.forEach(el -> el.shouldHave(attribute("dataId","TestValue")));
```

NB! Don't forget that such test is dangerous. It might happen that it doesn't test anything. For example, if `$$("div.list")` doesn't contain any elements.

**Comment by arturmkr** [comment]
That's why before these tests I do something like this:
`$$("div.list").shouldBe(CollectionCondition.sizeGreaterThanOrEqual(1));`

**Comment by sakamoto66** [comment]
In this case, I write:
`$$("div.list").filter(attribute("dataId","TestValue")).shouldBe(CollectionCondition.sizeGreaterThanOrEqual(1));`
