### ISSUE TITLE
Smart locators feature request

### ISSUE THREAD

**Issue by jbadeau** [selenide/selenide#1230]
Hello,

I would like to make a feature request for smart (proximity, relative, etc) locators:

These types of locators treats the browser as a black box. With these locators we can write scripts by looking at a web page and without inspecting it’s source code For example on google.com the command

> click("Google Search")
clicks on any element with the text Google Search (a button on the page at https://google.com). Smart locators mimics user interactions with the browser. For example if you want to write into an element that’s currently in focus use

> write("something")
Or if you want to write into a specific text field

> write("something", into(textBox({placeholder: "Username"})))

This is like the approach of taiko [smart locators](https://github.com/getgauge/taiko)  and Selenium 4 [ Relative Locator](https://dzone.com/articles/how-selenium-4-relative-locator-can-change-the-way)

I would be interested to help design the API and implement

>Jose

**Comment by asolntsev** [comment]
Hi @jbadeau!
Thank you for the suggestion.

While the goal of Selenide is to help developers by seamlessly solving low-level bothering issues (like timeouts), I am rather skeptical about smart locators. 
1. I may be wrong, but it seems to me that it's a **developer's task** to find the right locator. And it's not a rocket science at all. 
2. There is a risk that "smart" locator will find a wrong element **scares me**. There might be multiple elements with text/value/label "Google Search". Not good. 

Still, any ideas are welcome. We can discuss the topic. 

P.S. If Selenium 4 already has Relative Locator, what else should Selenide add to this?

**Comment by asolntsev** [comment]
feel free to reopen the issue when received new information.
