### ISSUE TITLE
Unable to create new service: ChromeDriverService

### ISSUE THREAD

**Issue by DEEKEEN** [selenide/selenide#1232]
I would like to run automation tests using Selenide latest version on selenium server(local machine).
CMD command:
java -jar selenium-server-standalone-3.141.59.jar -port 4444
Test Configuration:
    @BeforeMethod(alwaysRun = true)
    public void tearUp(Method method) {
        Configuration.browser = WebDriverRunner.CHROME;
        Configuration.remote = "http://localhost:4444/wd/hub";
        open("https://google.com");
    }

I got an error:
org.openqa.selenium.SessionNotCreatedException: Unable to create new service: ChromeDriverService

I guess i need to add chrome driver?
System.setProperty("webdriver.chrome.driver","path to chromedriver.exe");

**Comment by asolntsev** [comment]
@DEEKEEN No. Selenide downloads chromedriver automatically (in most cases). 
Please attach a full tracktrace of your error, there should be more details.
