### ISSUE TITLE
I want to improve shadowCss

### ISSUE THREAD

**Issue by sakamoto66** [selenide/selenide#1246]
shadowCss has no good access for certain HTML structures.

- Specific HTML structure
```
html
  + body
    + host1
      + #shadow-root
	 + innter
	    + #shadow-root
              + p
	 + innter
	    + #shadow-root
              + p
	 + innter
	    + #shadow-root
              + p
	 + innter
	    + #shadow-root
              + p
```
If you access the first innter/p, there is no problem.
```
$(shadowCss("p", "host1", "innter")).should(exist);
```
However, the second and subsequent innter/p cannot be flexibly accessed.
```
$$(shadowCss("innter", "host1")).forEach(innter ->{
  innter.find(shadowCss("p", null)).should(exist);
})
```
This code gives an error.
> Cannot find elements when the selector is null

This is because the second parameter of shadowCss is required parameter.
Is it possible to change the second parameter to an optional parameter?

- Ideal code
```
$$(shadowCss("innter", "host1")).forEach(innter ->{
  innter.find(shadowCss("p")).should(exist);
})
```

**Comment by dstekanov** [comment]
Hi @sakamoto66, sorry for the late response.

I've just looked and I see that with the current implementation you can interact with your elements one by one by using pseudo-class from CSS selectors `:nth-child()`, (I know it has drawbacks, like not ordered elements, etc.) e.g.:
```
$(shadowCss("p", "host1", "innter:nth-child(1)")).shouldHave(text("text1"));
$(shadowCss("p", "host1", "innter:nth-child(2)")).shouldHave(text("text2"));
```
I hope it will unblock you from writing such tests for now and I am going to look further what we can implement to get all elements from inner similar hosts...

**Comment by sakamoto66** [comment]
Hi @dstekanov, thank you response.

I thought of a fix plan.
The problem is that you need to select at least one shadowroot.
The fix plan has removed shadowroot as a required parameter.

However, with this fix plan, the output result of toString changes.

- before
> By.cssSelector: #shadow [#inner-shadow] #target
- after
> By.cssSelector: [#shadow, #inner-shadow] #target

The test code for this fix plan is ShadowElementTest.getElementsInsideInnerShadowHosts.

**Comment by dpeger** [comment]
Would you mind to check if this issue is solved for you by #1346 (should be part of 5.17+).

```$$(shadowCss("p", "host1", "innter"))``` should return a list of all ```p``` elements. That is your code becomes:

```
$$(shadowCss("p", "host1", "innter")).forEach(p ->{
  p.should(exist);
});
```

**Comment by asolntsev** [comment]
@sakamoto66 ^^^ Could you answer this? ^^^

**Comment by asolntsev** [comment]
@sakamoto66 Probably this issue was fixed by https://github.com/selenide/selenide/pull/1373 ?

**Comment by sakamoto66** [comment]
@asolntsev
hi!
I confirmed success.
thank you!

**Comment by asolntsev** [comment]
@sakamoto66 Thank you. Glad to know that your problem was fixed.
