### ISSUE TITLE
Selenide/Saucelabs Compatiblity

### ISSUE THREAD

**Issue by pgianino** [selenide/selenide#1250]
Has anyone successfully integrated Selenide/Java tests with Saucelabs for remote execution?  We are just starting to look into this for CI/CD pipeline integration (ie; running automated/unattended tests from Bamboo and/or Azure), and don't want to spend time on it if there are known issues or challenges.

**Comment by asolntsev** [comment]
@pgianino I know that people do you Selenide with Saucelabs. 

* See this post for example: https://groups.google.com/forum/#!topic/selenide/FR8Gp-W8aIc
* see this sample project: https://github.com/markwinspear/selenide-test-2015
