### ISSUE TITLE
There is lack a feature in newest release version 5.13.1

### ISSUE THREAD

**Issue by SeleniumTestAB** [selenide/selenide#1253]
## The problem
In the newest version 5.13.1 there should be added collectionCondition ItemWithText() (provided by https://github.com/selenide/selenide/pull/1194) but there is no code in the jar for it. Maven was used to provide dependency

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version*5.13.1*: 
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by BorisOsipov** [comment]
@SeleniumTestAB it is in 5.14
see change log https://github.com/selenide/selenide/blob/master/CHANGELOG.md

**Comment by asolntsev** [comment]
@SeleniumTestAB it will be released in Selenide 5.14.0

**Comment by SeleniumTestAB** [comment]
@asolntsev then please update the release notes for 5.13.1. They are misleading

**Comment by asolntsev** [comment]
I don't see it. Where exactly do you see the misleading text?
