### ISSUE TITLE
[DEFECT] - After `getWebDriver().quit()` should return false on `hasWebDriverStarted()`

### ISSUE THREAD

**Issue by sergiomartins8** [selenide/selenide#1255]
## The problem
@asolntsev, calling `getWebDriver().quit();` does not update `WebDriverRunner.hasWebDriverStarted()`.

## Details
Logs:
```shell
2020-08-20 12:11:24.653 [main] WARN  SomeTest - CLOSING DRIVER!
2020-08-20 12:11:26.758 [main] WARN  SomeTest - IS DRIVER OPEN: true
```

## Tell us about your environment
* **Selenide Version**: 5.14
* **Chrome\Firefox\IE Version**: All of them.
* **Browser Driver Version**: latest.
* **Selenium Version**: Same as selenide uses.
* **OS Version**: OSX

## Code To Reproduce Issue [ Good To Have ]
```java
open("https://google.com");
getWebDriver().quit();
System.out.println(WebDriverRunner.hasWebDriverStarted()); // true 🤷‍♀️ - should be false instead.
```

**Comment by BorisOsipov** [comment]
It is not a defect. You have not to call `getWebDriver().quit();` directly instead use `WebDriverRunner.closeWebDriver();`
