### ISSUE TITLE
Не работает fastSetValue в iframe

### ISSUE THREAD

**Issue by jmen4fun** [selenide/selenide#1271]
Пример: 
SelenideElement
            waitTextArea = $x("//a[@id='cke_24']");

    public void setUp(){
        Configuration.fastSetValue = true;
    }
    @Step
    public DealPage setText(){
        Selenide.switchTo().frame($x("//iframe[@class='cke_wysiwyg_frame cke_reset']"));
        $x("//p").click();
        StringSelection stringSelection = new StringSelection(DataConfig.TaskData.TEXT_ARTICLE);
        $x("//p").setValue(DataConfig.TaskData.TEXT_ARTICLE);
        Selenide.switchTo().defaultContent();
        return this;
    }

**Comment by asolntsev** [comment]
@jmen4fun Sorry, I cannot reproduce the problem. 
`fastSetValue` works for me in frame. See commit https://github.com/selenide/selenide/commit/1bb5f006a5093c41eab9547ad5edf2d6891fb007

**Comment by asolntsev** [comment]
@jmen4fun Feel free to reopen the issue if we get more information.
