### ISSUE TITLE
[Safari 14.0] DownloadMode=FOLDER with JS generated file doesn't work

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#1275]
## The problem
Download doesn't proceed, if it is JS generated.

## Details
Popup - "Allow downloads at this site" which prevents the execution to end.

![image](https://user-images.githubusercontent.com/6568032/93792329-ad595300-fc35-11ea-9371-39e18903e038.png)

## Tell us about your environment
* **Selenide Version**:  5.14.0
* **Safari Version**: 14.0 

## Code To Reproduce Issue [ Good To Have ]
    Configuration.browser="safari";
    Configuration.fileDownload= FileDownloadMode.FOLDER;
    open("https://jsfiddle.net/qL2csxn3/15");
    switchTo().frame("result");
    File text = $("#js-download").download();

**Comment by BorisOsipov** [comment]
@vinogradoff from blog release notes

```
What has been changed in 5.14.0:

....Stabilized new file downloading mode FOLDER
See issue #1220 and PR #1221.

Unfortunately, it doesn’t work in IE and Safari (which don’t allow to customize downloads folder).
```
