### ISSUE TITLE
IllegalArgumentException in a case of search of the child element using XPath

### ISSUE THREAD

**Issue by ovilio** [selenide/selenide#1281]
## The problem
I got an IllegalArgumentException: "XPath starting from / searches from root" error because of the using double-slash-started XPath string for the search of the child element. 

## Details
In issue #963 was discussed the problem with incorrect element search from parent element using XPath and as a result, the `checkThatXPathNotStartingFromSlash()` was implemented in the corresponding PR. In this method, the restriction was imposed on using slash-started XPath. 
I have a concern that it was done in a quite wrong approach and that's why:

1. Looks like raw Selenium doesn't have such restrictions for searching child element.

_for better understanding, below will be shown working code (and related logs) of the similar method for taking Type value for the modal window. Here I changed "//" to ".//" in XPath string according to advices in the #963  issue:_
```java
public String getTypeValue() {
 String dialogForm = "div[role='dialog']";
 String typeString = ".//p[contains(text(),'Type')]/following-sibling::p")
 return $(dialogForm).$x(typeString).getText();
}
```

I have the following method for taking Name value from the modal window:
```java
public String getNameValue() {
 String dialogForm = "div[role='dialog']";
 String nameString = "//p[contains(text(),'Name')]/following-sibling::p";
 return $(dialogForm).$x(nameString).getText();
        }
```
wich produced following logs with exception:
```
[2020/10/05 18:46:02.973] Search for element By.cssSelector: div[role='dialog']
[2020/10/05 18:46:02.984] Search for element By.xpath: .//p[contains(text(),'Type')]/following-sibling::p
[2020/10/05 18:46:03.011] Text found: "customer type"
[2020/10/05 18:46:03.014] Search for element By.cssSelector: div[role='dialog']
[2020/10/05 18:46:03.028] Found element: div

java.lang.IllegalArgumentException: XPath starting from / searches from root
```
In javadoc for $x() method is mentioned that it is an alias for `webElement.findElement(By.xpath(xpathLocator))` so i replaced it with raw Selenium methods to make code do same things as Selenide methods:
```java
public String getNameValue() {
 String dialogForm = "div[role='dialog']";
 String nameString = "//p[contains(text(),'Name')]/following-sibling::p";
 WebDriver webDriver = WebDriverRunner.getWebDriver();
 return webDriver.findElement(By.cssSelector(dialogForm)).findElement(By.xpath(nameString)).getText();
        }
```
wich coorectle finds all elements, return the text and produced following logs:
```
[2020/10/05 19:00:20.680] Search for element By.cssSelector: div[role='dialog']
[2020/10/05 19:00:20.692] Found element: div
[2020/10/05 19:00:20.692] Search for element By.xpath: .//p[contains(text(),'Type')]/following-sibling::p
[2020/10/05 19:00:20.721] Text found: "customer type"
[2020/10/05 19:00:20.725] Search for element By.cssSelector: div[role='dialog']
[2020/10/05 19:00:20.740] Found element: div
[2020/10/05 19:00:20.740] Search for element By.xpath: //p[contains(text(),'Name')]/following-sibling::p
[2020/10/05 19:00:20.769] Text found: "customer name"
```

As you can see, similar Selenium code doesn't lead to any exceptions related to searching child elements by "//" XPath and works properly as well as ".//" search with Selenide (displayed by Type field search method).

2. According to the [XPath v1.0 W3C specification](https://www.w3.org/TR/1999/REC-xpath-19991116/#path-abbrev) the "A//B" syntaxis is allowed and described as:

> chapter//para selects the para element descendants of the chapter element children of the context node 

and very much alike description of ".//A" syntaxis:

> .//para selects the para element descendants of the context node

So, seems like the dot is not necessarily for searching child node from the parent context node.

**Comment by BorisOsipov** [comment]
>seems like the dot is not necessarily for searching child node from the parent context node.

No, it is. Please play with example below.

```
<html>
<div class='foo'>Hello</div>

<div class='bar'>
	<div class='foo'>Bye</div>
</div>

</html>
```

```
        Configuration.browser = "chrome";
		// open html sample
        open("data:text/html, data:text/html, <html> <div class='foo'>Hello</div> <div class='bar'> <div class='foo'>Bye</div> </div> </html>");
		// searching WITH dot
        String xpath1Text = $x("//div[@class='bar']").$x(".//*[@class='foo']").getText();
        assertEquals("Bye", xpath1Text);
        WebDriver webDriver = WebDriverRunner.getWebDriver();
		// searching WITHOUT dot with plain webdriver
        String xpath2Text = webDriver.findElement(By.xpath("//div[@class='bar']")).findElement(By.xpath("//*[@class='foo']")).getText();
        assertEquals("Bye", xpath2Text);// FAILS WITH expected: <Bye> but was: <Hello>
````
