### ISSUE TITLE
How to get window size in selenide ? we do in selenium like this   Dimension d = driver.manage().window().getSize();

### ISSUE THREAD

**Issue by PranavHanwante** [selenide/selenide#1283]
## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to Selenide).
Tell us what you were trying to do and what happened instead. 

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by BorisOsipov** [comment]
`Dimension size = WebDriverRunner.getWebDriver().manage().window().getSize();`
