### ISSUE TITLE
Unused SelendeElement fields are shown in the report

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1290]
## The problem
In Page Objects, `SelenideElement` fields are shown in the report even if they are not used in the test.

## Details
See details in https://github.com/allure-framework/allure-java/issues/445

**Comment by oksanamorhunova** [comment]
I have the same issue with latest selenide 5.17.0. Can I reopen this issue?
<img width="738" alt="Знімок екрана  о 2 37 40 пп" src="https://user-images.githubusercontent.com/74051073/128702364-134e8a2a-9d82-4084-8ed0-201812e69d7b.png">
![Знімок екрана  о 2 38 58 пп](https://user-images.githubusercontent.com/74051073/128702392-21b00568-f5a1-47c5-a99b-6122190dda30.png)

selenide-5.17.0
testng-6.14.3
allure-testng-2.13.3
allure-selenide-2.13.2
allure-maven-2.10

**Comment by asolntsev** [comment]
@oksanamorhunova what is `Filter.of`? I guess this method calls some method of SelenideElement, that's why it's added to the report.

Could you share the code of `Filter`?

P.S. lastest Selenide versioon ise 5.23.2, not 5.17.0 :)

**Comment by oksanamorhunova** [comment]
yes here is Filter
![Знімок екрана  о 5 36 14 пп](https://user-images.githubusercontent.com/74051073/128724277-c2dd6210-34b7-44e4-8277-7e39f1276524.png)
so I am creating a custom element Filter using method in another field Table
![Знімок екрана  о 5 36 55 пп](https://user-images.githubusercontent.com/74051073/128724367-488e7372-9ffe-4572-aeb7-8a9a35438d7a.png)
but this test starts from 'Navigate to the page' step and all those extra steps before 'Navigate..' should not be in the report 
Also I want to admit that those steps are present for each test even when I am not using filter element

**Comment by asolntsev** [comment]
@oksanamorhunova I found the problem.
This issue existed in Selenide 5.17.0, but was later fixed in 5.20.0: https://ru.selenide.org/2021/03/23/selenide-5.20.1/

**Comment by oksanamorhunova** [comment]
@asolntsev Thank you) I will upgrade selenide
