### ISSUE TITLE
Selenide.closeWebDriver and WebDriverRunner.closeWebDriver

### ISSUE THREAD

**Issue by mymtak** [selenide/selenide#1292]
## The problem
What is the difference between Selenide.closeWebDriver and WebDriverRunner.closeWebDriver?
Which one should I use?

## Tell us about your environment
* **Selenide Version**:5.15.0 
* **Chrome Version**:86.0.4240.111 
* **Browser Driver Version**: ChromeDriver 86.0.4240.22
* **OS Version**: Windows10

**Comment by BorisOsipov** [comment]
@mymtak there are no differences. Use anyone.
