### ISSUE TITLE
Feature: set active SelenideDriver

### ISSUE THREAD

**Issue by sanchek** [selenide/selenide#1296]
Create method for setting currenly active SelenideDriver with it's own SelenideConfig

## The problem
If user wants to open two browsers in test, he need to point browser explicitly.
For example (https://selenide.org/2018/10/10/selenide-5.0.0/): 
```
SelenideDriver browser1 = new SelenideDriver();
SelenideDriver browser2 = new SelenideDriver();

browser1.open("https://google.com");
browser2.open("http://yandex.ru");

browser1.$(h1).shouldHave(text("Google"));
browser2.$(h1).shouldHave(text("Yandeks"));
```

## Solution can might look like this:
```
    SelenideConfig browserConfig1 = new SelenideConfig()
      .baseUrl("http://google.ru");
    SelenideDriver selenideDriver1 = new SelenideDriver(browserConfig1);
    WebDriverRunner.setActiveSelenideDriver(selenideDriver1);
    Selenide.open("/signin");
    assertThat(selenideDriver1.url()).isEqualTo("http://google.ru/signin");
    
    SelenideConfig browserConfig2 = new SelenideConfig()
      .baseUrl("http://ya.ru");
    SelenideDriver selenideDriver2 = new SelenideDriver(browserConfig2);
    WebDriverRunner.setActiveSelenideDriver(selenideDriver2);
    Selenide.open("/signin");
    assertThat(selenideDriver2.url()).isEqualTo("http://ya.ru/signin");
```

**Comment by asolntsev** [comment]
@sanchek While I may be mistaken, it seems to me an over-complication. 

If you really need to use different `SelenideDriver` instances in tests, why not just instantiate them and store into test field? It's much more simple and predictable than playing with static methods. 

```java
public class MyJUnitTest {
  private SelenideDriver web = new SelenideDriver();

  @Test 
  public void someTest() {
    web.open("https://google.com");
    web.$(h1).shouldHave(text("Google"));
  }
```

**Comment by sanchek** [comment]
To me changeing currect active driver looks like more simple and reusable solution.

First of all, you can use and adopt any previously written testcases without any meaningful modifiactions.

Second, whithout changing webdriver you wont be able to use PageObject pattern without calling webdriver instance, and also PageObject classes should me modified.
Example:
![image](https://user-images.githubusercontent.com/6098833/97962742-9cc0fe80-1dd7-11eb-8deb-b3ff8f6fc079.png)
![image](https://user-images.githubusercontent.com/6098833/97962774-acd8de00-1dd7-11eb-8f57-02180ca13a75.png)

**Comment by asolntsev** [comment]
Yes, but it's a bad idea to open a web page in a constructor. What if you rewrite your page object a little, so that you don't need to pass SelenideDriver to it?

Something like

```java
class LoginPage() {
  private val profileHeader = $(...);
  private val signInPhoneField = $(...);
}

class MyTest {
  private SelenideDriver web = new SelenideDriver(new SelenideConfig().browserSize("1024x768").baseUrl("http://ya.ru"));

  @Test 
  public void someTest() {
    val page = web.open("https://google.com", LoginPage::class.java);
    page.profileHeader.shouldHave(text("Google"));
  }
}
```

**Comment by sanchek** [comment]
In this case I've got error: _No webdriver is bound to current thread: 17. You need to call open(url) first._
I suppose it's because of SelenideElement (profileHeader) inside PageObject should be found via $ be the same webdriver that opened this page.

**Comment by asolntsev** [comment]
@sanchek Yes, and we have issue for that: https://github.com/selenide/selenide/issues/1048 :) 
Unfortunately, it's a bit hard to fix that issue by the moment... 

Another option would be to declare page object fields with `FindBy` annotation:

```java
class LoginPage() {
  @FindBy(id="...")
  private val profileHeader;

  @FindBy(xpath="...")
  private val signInPhoneField = $(...);
}
```

**Comment by asolntsev** [comment]
@sanchek One option that I am thinking about is adding method `WebDriverRunner.setSelenideConfig()`. 
It solves your problem, but doesn't introduce complexity with `SelenideDriver`s.

**Comment by sanchek** [comment]
I don't understand how this method should be implemented and used.
Does the user need to recreate the driver after setting the config?

**Comment by asolntsev** [comment]
Using this method, we could rewrite your initial code sample this way:

```java
  SelenideConfig browserConfig1 = new SelenideConfig().baseUrl("http://google.ru");
    WebDriverRunner.setSelenideConfig(browserConfig1);
    Selenide.open("/signin");
    assertThat(selenideDriver1.url()).isEqualTo("http://google.ru/signin");
    
    SelenideConfig browserConfig2 = new SelenideConfig().baseUrl("http://ya.ru");
    WebDriverRunner.setSelenideConfig(browserConfig2);
    Selenide.open("/signin");
    assertThat(selenideDriver2.url()).isEqualTo("http://ya.ru/signin");
```

As you see, we just eliminated `selenideDriver1` and `selenideDriver2`. Everything else is the same.

**Comment by sanchek** [comment]
It looks quite clear, but I'm afraid that just changing the config will change the behaviour of first opened page (timeout and etc.)

**Comment by asolntsev** [comment]
@sanchek Now you see how complex it is. :) 
There is hundred of such nuances: "what if..", "in which order...", "what could be affected...". 

The idea is that `SelenideConfig` will be hold in ThreadLocal. After calling `WebDriverRunner.setSelenideConfig`, it will applied only to current thread.

**Comment by asolntsev** [comment]
After discussion we realized that users need only to set `Config`, not the whole `SelenideDriver`. Superseded by https://github.com/selenide/selenide/issues/1372.
