### ISSUE TITLE
setScriptTimeout method

### ISSUE THREAD

**Issue by mymtak** [selenide/selenide#1304]
## The problem
Is it possible to use the setScriptTimeout method in Selenide?
I want to extend from the default 30 seconds.

## Tell us about your environment
* **Selenide Version**: 5.15.0
* **Chrome\Firefox\IE Version**: 86.0.4240.111
* **Browser Driver Version**: ChromeDriver 86.0.4240.22
* **OS Version**: Windows10

## Code To Reproduce Issue [ Good To Have ]
org.openqa.selenium.ScriptTimeoutException: script timeout
  (Session info: chrome=86.0.4240.111)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 86.0.4240.111, chrome: {chromedriverVersion: 86.0.4240.22 (398b0743353ff..., userDataDir: C:\Users\manager\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:59473}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, ...

**Comment by asolntsev** [comment]
@mymtak You can use method `WebDriverRunner.getWebDriver().manage().timeouts().setScriptTimeout(42, SECONDS)`. 

We probably could create a shorter alias in Selenide style, but this seems to be a rate case.
