### ISSUE TITLE
Can not run chrome with browser extension

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1314]
## The problem
An error occurs when try to launch chrome with extension:
`org.openqa.selenium.WebDriverException: unknown error: cannot exclude load-extension switch when extensions are specified`

Reason:
https://github.com/selenide/selenide/blob/6108bdaad05cb14bbd5947d25ccbc4ded2c5dded/src/main/java/com/codeborne/selenide/webdriver/ChromeDriverFactory.java#L96-L98

## Code To Reproduce Issue [ Good To Have ]
Use sample test https://github.com/BorisOsipov/selenide-ui-ext-tests/blob/master/src/test/java/com/example/WithExtensionTest.java#L24

## Tell us about your environment
* **Selenide Version**: 5.15.1
* **Chrome\Firefox\IE Version**: 86
* **Browser Driver Version**: 86

**Comment by BorisOsipov** [comment]
cc @stykalin

**Comment by asolntsev** [comment]
@BorisOsipov Yes, the problem is that `ChromeDriverFactory` adds `load-extension` switch by default. I assumed that everyone who wants to add an extension needs to subclass `ChromeDriverFactory` anyway, so he will just override method `excludeSwitches()` also.

**Comment by BorisOsipov** [comment]
@asolntsev yes I did it but ran into https://github.com/selenide/selenide/issues/1315
