### ISSUE TITLE
Cannot use AbstractDriverFactory with remote option

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1315]
## The problem
```
 Configuration.browser = CustomChromeDriverFactory.class.getName();
 Configuration.remote = "http://localhost:4444/wd/hub";
 open("https://www.cryptopro.ru/sites/default/files/products/cades/demopage/main.html");
```
Cause an error:
```
org.openqa.selenium.WebDriverException: Requested environment is not available (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 58 milliseconds
```
It occurs because we pass string `com.example.CustomChromeDriverFactory` as `browserName` capability and grid cannot start such browser.

## Code To Reproduce Issue [ Good To Have ]
Use sample test and any grid https://github.com/BorisOsipov/selenide-ui-ext-tests/blob/master/src/test/java/com/example/WithExtensionTest.java#L33

**Comment by BorisOsipov** [comment]
сс @stykalin

**Comment by asolntsev** [comment]
fixed by PR https://github.com/selenide/selenide/pull/1324
