### ISSUE TITLE
Cycle "for (SelenideElement el : $$x("path")" generates StaleElementReferenceException

### ISSUE THREAD

**Issue by MTokarenko** [selenide/selenide#1330]
## The problem
I have a list with Selenide elements ($$x()) and I need to click at each of them, do some actions and click at the next element from the list.
I guess the dom tree is refreshing during click at the element (I'm working with web app).
At Selenide version 4.19. my code worked fine.

## Details
At version 5.0.0 and above I get 
Element should be visible or transparent: visible or have css value opacity=0 {$$(31 elements)[2]}
Element: 'Ups, failed to described the element [caused by: StaleElementReferenceException: stale element reference: element is not attached to the page document]'
StaleElementReferenceException: stale element reference: element is not attached to the page document at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:94)

I understand why such exception happens but can't realize how to solve it and why at 4.x.x selenide version it worked, may it's a bug.

## Tell us about your environment
* **Selenide Version**: 5.0.0  and above
* **Chrome\Firefox\IE Version**: Chrome 86.0.4240.198
* **OS Version**: Win 10

## Code To Reproduce Issue
```
    String folderXpath = ".//div[contains(@class, '-clickable-') and contains(@class, '-tree-node-caption')]";
    for (SelenideElement folder : $$x(folderXpath)) {
        folder.click();

        //some code

        closeCurrentTab();
    }
```

**Comment by asolntsev** [comment]
Hi @MTokarenko .
This is same issue as https://github.com/selenide/selenide/issues/797. 
At some moment we introduce caching when iterating collections. We are still not sure if it was a good idea. :)

### What's the problem
I think that it's rather a bad practice to use cycles in tests. 
NB! What if `folderXpath` doesn't find any elements? Then your test will do nothing, but stay green.  

### Solution
Probably a better way to write such a test would be to check each link explicitly:
```java
checkLink($(folderXpath, 0).shouldHave(text("foo 1")));
checkLink($(folderXpath, 1).shouldHave(text("foo 2")));
checkLink($(folderXpath, 2).shouldHave(text("foo 3")));
```

**Comment by MTokarenko** [comment]
Hi @asolntsev !
Hope you will return this 'opportunity' for us :)
I use such cycles in the 'universal' tests. For example in this case I don't know the folders names, I just need to click at each of them and make sure that screen is opened without any exception. Kind a smoke test for many projects, based on the same structure.

## What if folderXpath doesn't find any elements? Then your test will do nothing, but stay green.
I believe if the author writes such code, he should be aware that $$x() may return nothing.

**Comment by asolntsev** [comment]
> I believe if the author writes such code, he should be aware that $$x() may return nothing.

That's the problem. 
It's too easy to make such an error. You should check for sure that there are some folders, and at lest some folders have proper name and content. 

> I use such cycles in the 'universal' tests.
I would suggest to replace such tests with a proper tool:
1. Monitoring
2. Google analytics
3. Logs analysis
4. etc.

For example, I just perform  HTTP GET requests in a loop in such case.

**Comment by MTokarenko** [comment]
> It's too easy to make such an error.
Understand this. At new version of our app, dom-tree was changed and xpath and my xpath became invalid, but test still was green). But anyway, I believe user should have possibility to iterate over the collection. In the release notes of selenide 4.12.3 I have found $$().snapshot() method. But code with snapshot() still calls StaleElementReferenceException.
```
  String folderXpath = ".//div[contains(@class, '-clickable-') and contains(@class, '-tree-node-caption')]";
            ElementsCollection folders = $$(xpath(folderXpath)).snapshot();
            for (SelenideElement folder : folders) {
                folder.click();
            }
```
Am I doing something wrong?

**Comment by asolntsev** [comment]
@MTokarenko :) :) :) 

Yes, method `.snapshot()` caches the collection. It returns _old_ elements, that's why it causes `StaleElementReferenceException`. 

This code should work in your case:

```java
  int folders = $$x(folderXpath).size();
  for (int i = 0; i < folders; i++) {
      $x(folderXpath, i).click();
   }
```

**Comment by MTokarenko** [comment]
Thank you!)
