### ISSUE TITLE
Because option "Sizzle" is enabled, the string representation for css elements does not work

### ISSUE THREAD

**Issue by Catchermax** [selenide/selenide#1331]
## The problem
When you try to return a string object for an element it works, but if you use option `Configuration.selectorMode = SelectorMode.Sizzle;` then string object always `unknown`

## Details
**Just use this code to check it**

it is working fine, return string "css selector: input#text"
```
import com.codeborne.selenide.Selenide;
import org.junit.jupiter.api.Test;
import static com.codeborne.selenide.Selenide.element;

public class PapapapaTest {

    @Test
    void checkSizzleTest() {
        Selenide.open("https://yandex.ru/");
        System.out.println(element("input#text").toWebElement().toString());
    }
}
```

but it doesn't work, return string "unknown locator"
```
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.SelectorMode;
import com.codeborne.selenide.Selenide;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.element;

public class PapapapaTest {
    @Test
    void checkSizzleTest() {
        Configuration.selectorMode = SelectorMode.Sizzle;
        Selenide.open("https://yandex.ru/");
        System.out.println(element("input#text").toWebElement().toString());
    }
}
```
Also for XPath it works always

## Tell us about your environment
* **Selenide Version**:  5.16.1
* **Chrome\Firefox\IE Version**: Version 86.0.4240.198 (Official Build) (x86_64)
* **OS Version**: Mac os

**Comment by asolntsev** [comment]
@Catchermax Can you explain why it's needed to call `$.toWebElement().toString()`? I don't see how it can be useful. Why not just `$.toString()`?

And yes, it returns `"unknown locator"` because this element is loaded with Sizzle library, not css locator. JOKK.

**Comment by Catchermax** [comment]
It useful to create an interactive map of locators to estimate the amount of coverage of the ui part of the project

**Comment by asolntsev** [comment]
@Catchermax But the behaviour of `WebElement.toString()` is not defined. It potentially can return anything. You should find a better way to compose your interactive map. 

Currently it returns `[[ChromeDriver: chrome on MAC (d05fd53b66055b12601dba8f4d14058c)] -> css selector: :header]`. Do you really find it useful?

**Comment by asolntsev** [comment]
@Catchermax Good news: I found a better way for you. :)
Just use method `SelenideElement.getSearchCriteria()`:

```java
Configuration.selectorMode = SelectorMode.Sizzle;
SelenideElement input = $(":header");
assertThat(input.toString()).isEqualTo("<h1>Page with JQuery</h1>");
assertThat(input.getSearchCriteria()).isEqualTo(":header");
assertThat(input.getWrappedElement().toString()).isEqualTo("[org.openqa.selenium.remote.RemoteWebElement@9953de0d -> unknown locator]");

```
