### ISSUE TITLE
Incorrect click with coordinates after 5.15.0

### ISSUE THREAD

**Issue by petroOv-PDFfiller** [selenide/selenide#1332]
## The problem
Since Selenide 5.15.0  click (x, y) (https://github.com/selenide/selenide/blob/05e3bad56b21514829336788a4112ae53810660c/src/main/java/com/codeborne/selenide/commands/Click.java#L49) has been declared deprecated and you need to use ClickOptions in its place, and so, added a check there if x == 0 and y == 0 then call click () without offset (https://github.com/selenide/selenide/blob/05e3bad56b21514829336788a4112ae53810660c/src/main/java/com/codeborne/selenide/commands/Click.java#L78). And my implementation does not want to click on the canvas in the editor at coordinates 0,0. if I want to click without coordinates, then I will call the appropriate method, but why we use default method when coordinates explicitly indicated.

## ENV
* **Selenide Version**: 5.15.0
* **Chrome\Firefox\IE Version**: Chrome latest version
* **Browser Driver Version**: Latest chromedriver
* **Selenium Version**: 3.141.59
* **OS Version**: mac os 10.15

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/1333

**Comment by dstekanov** [comment]
@petroOv-PDFfiller thanks for the issue. Is it possible to provide a page example with your case?
