### ISSUE TITLE
Inconsistency: Configuration.browserSize to accept org.openqa.selenium.Dimension too

### ISSUE THREAD

**Issue by fkrivsky** [selenide/selenide#1336]
## The problem
The **Configuration.browserSize** setting accepts only **String** in format 1024x768.
OTOH, **WebDriverRunner.getWebDriver().manage().window().setSize(targetSize)** accepts only **org.openqa.selenium.Dimension** as input parameter.

For the sake of consistency, **Configuration.browserSize** should accept **org.openqa.selenium.Dimension** too.

## Tell us about your environment
* **Selenide Version**: 5.16.0
* **Chrome\Firefox\IE Version**: any
* **Browser Driver Version**: any
* **Selenium Version**:  any
* **OS Version**: any

**Comment by asolntsev** [comment]
Consistency is a varied concept :)

Users can set browser size via `System.setProperty("selenide.browserSize", "1024x768")`. For the sake of consistency with this method we made `Configuration.browserSize` also a String with format `"1024x768"`.

**Comment by fkrivsky** [comment]
I see :) That also makes sense, as both are properties...
Well, we already handle it ourselves so as you wish :) Not a high priority for me anyway...
