### ISSUE TITLE
5.16.2 version fails with java.lang.File exception

### ISSUE THREAD

**Issue by iRaunchy** [selenide/selenide#1337]
Works fine with 5.15.1 though.  The same code fails only on 5.16.2. Content is not null.
Code example:
 try (InputStream is = Files.newInputStream(content)) {
            Allure.addAttachment(screenshotName, is);
        } catch (Throwable e) {
            throw new Error("Wrong file address");
        }
    }

**Comment by asolntsev** [comment]
@iRaunchy Hi. I don't see any Selenide code here. How can it fail because of Selenide changes? 
Can you provide a full error message with stack trace?

**Comment by iRaunchy** [comment]
preProcess:79, Aj (org.aspectj.weaver.loadtime)
transform:51, ClassPreProcessorAgentAdapter (org.aspectj.weaver.loadtime)
transform:246, ClassFileTransformer (java.lang.instrument)
transform:188, TransformerManager (sun.instrument)
transform:563, InstrumentationImpl (sun.instrument)
translateToIOException:92, UnixException (sun.nio.fs)
rethrowAsIOException:111, UnixException (sun.nio.fs)
rethrowAsIOException:116, UnixException (sun.nio.fs)
newByteChannel:219, UnixFileSystemProvider (sun.nio.fs)
newByteChannel:375, Files (java.nio.file)
newByteChannel:426, Files (java.nio.file)
newInputStream:420, FileSystemProvider (java.nio.file.spi)
newInputStream:160, Files (java.nio.file)
attachScreenshot:104, CommonUtils (com.tripactions.utils)
makeScreenshotAttachment:39, CommonUtils (com.tripactions.utils)
userHomePageAction:38, SearchPage (com.tripactions.pages)
login:205, BaseTest (com.tripactions)
setup:122, BaseTest (com.tripactions)
setup:38, AdminPolicySmokeTest (com.tripactions.tests.Smoke.admin)
invoke0:-1, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:62, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:564, Method (java.lang.reflect)
invokeMethod:133, MethodInvocationHelper (org.testng.internal)
invokeMethodConsideringTimeout:62, MethodInvocationHelper (org.testng.internal)
invokeConfigurationMethod:340, ConfigInvoker (org.testng.internal)
invokeConfigurations:294, ConfigInvoker (org.testng.internal)
runConfigMethods:683, TestInvoker (org.testng.internal)
invokeMethod:510, TestInvoker (org.testng.internal)
invokeTestMethod:172, TestInvoker (org.testng.internal)
runInSequence:46, MethodRunner (org.testng.internal)
invoke:804, TestInvoker$MethodInvocationAgent (org.testng.internal)
invokeTestMethods:145, TestInvoker (org.testng.internal)
invokeTestMethods:146, TestMethodWorker (org.testng.internal)
run:128, TestMethodWorker (org.testng.internal)
accept:-1, 2078510778 (org.testng.TestRunner$$Lambda$263)
forEach:1511, ArrayList (java.util)
privateRun:770, TestRunner (org.testng)
run:591, TestRunner (org.testng)
runTest:402, SuiteRunner (org.testng)
runSequentially:396, SuiteRunner (org.testng)
privateRun:355, SuiteRunner (org.testng)
run:304, SuiteRunner (org.testng)
runSuite:53, SuiteRunnerWorker (org.testng)
run:96, SuiteRunnerWorker (org.testng)
runSuitesSequentially:1180, TestNG (org.testng)
runSuitesLocally:1102, TestNG (org.testng)
runSuites:1032, TestNG (org.testng)
run:1000, TestNG (org.testng)
run:66, IDEARemoteTestNG (com.intellij.rt.testng)
main:109, RemoteTestNGStarter (com.intellij.rt.testng)

**Comment by iRaunchy** [comment]
java.nio.file.NoSuchFileException: file:/Users/app/src/******/*******-tests/target/allure-results/*********_1606818888611.png

The file physically exists, running the same code on old version on Selenide works fine. Had to rollback the version only - no issues.

**Comment by iRaunchy** [comment]
More detailed code snippet 

attachScreenshot(screenName, Selenide.screenshot(screenName))

private static void attachScreenshot(String screenshotName, String folder) {
        Path content = Paths.get(folder);
        try (InputStream is = Files.newInputStream(content)) {
            Allure.addAttachment(screenshotName, is);
        } catch (Throwable e) {
            Exception ex = new Exception();

            ex.getStackTrace();
            ex.printStackTrace();
            throw new Error("Wrong file address");
        }
    }

**Comment by asolntsev** [comment]
@iRaunchy I tried this code - it worked with both versions Selenide 5.16.2 and 5.15.1.

Can you provide a full code sample that actually reproduces the problem?

**Comment by iRaunchy** [comment]
@asolntsev 
Found an issue I think.

String path = Selenide.screenshot(namePrefix + "_" + LocalDateTime.now().format(dtf));
returns different path in 5.15.1 and 5.16.0 and further.
Newer Selenide version returns like this "file:/var/lib/"
Older version returns like this "/var/lib/" 
Then it fails to find the file here
InputStream is = Files.newInputStream(Paths.get(path))

**Comment by asolntsev** [comment]
@iRaunchy Thank you for explanation. 
This returned path was never be meant for parsing. It should be used only for logging or adding information to error message. No need to parse it.
