### ISSUE TITLE
SelenideElement.waitUntil() prepends "be" to error messages.

### ISSUE THREAD

**Issue by raidora** [selenide/selenide#1338]
## The problem
I'm using the SelenideElement.waitUntil() method for it's ability to specify a custom timeout.
However, getting a grammatically correct error message out of it seems impossible since waitUntil() seems to prepend the word "be" to any condition thrown at it.

## Details
Code like this:
`$x("//xpathexample").waitUntil(Condition.have(Condition.cssClass(".example")), 2000);`

Produces an error that starts like this:
`Element should be have css class '.example' {By.xpath: //xpathexample}`

_Mind the "should be have" part of the error message._

The following would produce a "Element should be be visible" in the error message:
`$("example").waitUntil(Condition.be(Condition.visible), 2000);`

## Tell us about your environment
* **Selenide Version**: 5.12.2
* **Chrome Version**: Remote, v:86.0.4240.75
* **OS Version**: Win 10 version 2004, build 19041.572

**Comment by asolntsev** [comment]
Agree. 
Probably a good solution would be to deprecate methods `waitUntil`/`waitWhile` and create an overloaded methods `shouldBe`/`shouldHave` with timeout parameter. That's what issue https://github.com/selenide/selenide/issues/1136 was created for. Help appreciated.

**Comment by asolntsev** [comment]
fixed in https://github.com/selenide/selenide/pull/1340
