### ISSUE TITLE
Feature Request: Implement textType(text, charsPerMinute) method

### ISSUE THREAD

**Issue by DuskoV** [selenide/selenide#1358]
## The problem
Consider having AJAX driven text box on the screen (think about selecting airport on the travel website). In this case, user is typing text into input box, and AJAX calls are firing how user is typing the text.

## Details
If we use simple text("Los Angeles") , then AJAX calls test would break, since the value "Los Angeles" is quickly injected into input box. 

## How to solve this?
Have a new textType("Los Angeles", 400) method, which would enter "Los Angeles" by typing each character with delay between them of 60/400 [seconds] .

"400" can be default value in config, and can be dev changed as needed. In that case secondary method textType("Los Angeles") can be implemented

**Comment by asolntsev** [comment]
@DuskoV Have you tried `$.sendKeys("Los Angeles")` instead of `$.text("Los Angeles")`? 
It does emulate exactly what real users do: type keys one-by-one. But without any delays.

**Comment by DuskoV** [comment]
Yes, would be great to add delay to this method. Thanks!

**Comment by EugeneMurS** [comment]
I implemented similar functionality through Actions (C#).

1. Implement custom Interaction:
		
		public class PauseInteraction : Interaction {
			private readonly TimeSpan _duration;

			public PauseInteraction(TimeSpan duration) : base(new KeyInputDevice("default keyboard")) {
				_duration = duration;
			}

			public override Dictionary<string, object> ToDictionary()
				=> new () {
					["type"] = "pause",
					["duration"] = Convert.ToInt64(_duration.TotalMilliseconds)
				};

			public override bool IsValidFor(InputDeviceKind sourceDeviceKind) {
				return true;
			}

			public override string ToString() {
				return string.Format(CultureInfo.InvariantCulture, "Pause [duration: {0} ms]", _duration.TotalMilliseconds);
			}
		}

2. Implement new action as extension:

		public static class ActionsExtensions {
			private static ActionBuilder GetActionsBuilder(Actions actions) => typeof(Actions).GetField("actionBuilder", BindingFlags.Instance | BindingFlags.NonPublic)
			                                                                                  ?.GetValue(actions) as ActionBuilder
			                                                                   ?? throw new InvalidOperationException("private field ActionBuilder actionBuilder not found in class Actions");

			public static Actions Wait(this Actions actions, TimeSpan duration) {
				var pauseInteraction = new PauseInteraction(duration);
				ActionBuilder actionBuilder = GetActionsBuilder(actions);
				ActionSequence lastActionSequence = actionBuilder.ToActionSequenceList().LastOrDefault();

				if (lastActionSequence == null) {
					throw new WebDriverException($"You cannot use the action '{nameof(Wait)}' first");
				}

				lastActionSequence.AddAction(pauseInteraction);

				return actions;
			}
		}

3. Call 'Wait' action in code (for example):

			foreach (char c in text) {
				fillActions.SendKeys(c.ToString(new CultureInfo("En-Us", false)))
				           .Wait(TimeSpan.FromMilliseconds(100));
			}

**Comment by asolntsev** [comment]
@DuskoV So you need this "type with delays" feature just to test _debounce_? Probably it's not a good idea because such a test may be flaky. You never know in which order and with what speed the keys and requests will be sent and processed.

Anyway, you can always emulate such behaviour with just calling `sendKeys("part of string")` and `sleep(ms)` several times.
It doesn't seem to be a widely used feature at the moment.
