### ISSUE TITLE
Allow user disable\enable wd logs 

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1365]
Starting from version 5.13.0, Selenide write webdriver logs to files like `build/reports/tests/webdriver.uuid.log`. 

Many user complain that these logs take a lot of disk space, and not really needed.

**Comment by asolntsev** [comment]
I think the log should be disabled by default: it seems nobody really needs it.

**Comment by kczornyj** [comment]
Hello, it would be great if there could be a True/False variable in the Configuration file to save the webdriver log or not.

**Comment by kczornyj** [comment]
Thank you!
