### ISSUE TITLE
Using Condition.and with a non-existing element causes NoSuchElementException

### ISSUE THREAD

**Issue by pavelpp** [selenide/selenide#1369]
## The problem
When wrapping condition in and(), then NoSuchElementException may happen if the element does not exist.  

## Tell us about your environment
* **Selenide Version**: 5.17.0

## Code To Reproduce Issue [ Good To Have ]
```
open("https://docs.cypress.io/");
$(".lolkek").shouldNotBe(visible, ofSeconds(5)); //works
$(".lolkek").shouldNotBe(and("and visible", visible), ofSeconds(5));//NoSuchElementException

**Comment by asolntsev** [comment]
@pavelpp  fixed by https://github.com/selenide/selenide/pull/1370
