### ISSUE TITLE
"should" action with duration has invalid logging for duration timeout value

### ISSUE THREAD

**Issue by evgeny-tumashchick** [selenide/selenide#1376]
## The problem
"should" action with duration parameter has wrong logging in allure report. Duration time replaced with alphanumeric code e.g. PT1M, PT2M etc.

## Details
Presumably reproduced starting from 5.17.0

logging with "wait until" action in Allure report:
`$("<locator>") wait until([visible, 60000])`

logging with "should" in Allure report:
`$("<locator>") should be([visible, PT1M])`

**Comment by asolntsev** [comment]
@evgeny-tumashchick By the way, this "PT1M" is not a bug, but an ISO-8601 representation of duration. 
For example, "PT1M" means "period time 1 minute". :) 

But well, let's replace it by "1m", "1s" or "400 ms".

**Comment by evgeny-tumashchick** [comment]
My mind didn't recognize that PTM1 cold be an abbreviation and after explanation it even seems logical :)
Anyway thank you for made update. It seems that "1m", "1s" or "400 ms" would have no other points than time period

**Comment by asolntsev** [comment]
Agree. 
I was also surprised that "PT1M" is  an ISO standard. Quite unreadable.
