### ISSUE TITLE
Command `Selenide.refresh()` is not displayed in Selenide/Allure report

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1383]
## Tell us about your environment
* **Selenide Version**: 5.18.0

**Comment by BorisOsipov** [comment]
As well as Selenide.confirm(), back(), etc.

it really matters?

**Comment by asolntsev** [comment]
Well, yes - otherwise you just don't see some of your test steps in the report (for example, we don't see how long time did it take).

Why we need those reports at all?
