### ISSUE TITLE
Selenide doesn't assign a value to `div` in `Configuration.fastSetValue =true` mode

### ISSUE THREAD

**Issue by nili0513** [selenide/selenide#1388]
Selenide test found a problem, I do not know if it is a bug

Before, I always used setValue () method to be effective for textarea, input and div, but recently I upgraded selenide to 5.17.3 and configured it Configuration.fastSetValue =True; after the attribute, it does not assign a value to Div. input and textarea have no effect.

(1) I want to know how fastsetvalue works?

(2) Why can't fastsetvalue be assigned to div

(3) What are the detailed differences between setValue and fastsetvalue?

Thank you

## Tell us about your environment
* **Selenide Version**:  5.17.3
* **Chrome\Firefox\IE Version**:  Chrome
* **Browser Driver Version**:  latest version
* **OS Version**: Win10 64bit

**Comment by asolntsev** [comment]
@nili0513 This is an open-source, dude :) You can always look into [source code](https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/commands/SetValue.java).

Shortly:
1. in `fastSetValue = false` mode:
  * `element.clear();`
  * `element.sendKeys("blah");`
2. in `fastSetValue = true` mode:
  * `WebDriver.executeJavaScript("element.value = "blah");`

**Comment by nili0513** [comment]
@asolntsev 
hello, Thanks for your quick response.

I want to know why when fastsetvalue = true mode, the setValue () method does give a value to div element, but it does not display on the UI page, causing the test to fail

Fastsetvalue = true mode supports  textarea and input, but not work in div.

**Comment by asolntsev** [comment]
@nili0513 i don't understand how you expect it to work. By definition, div doesn't have "value" attribute. Web application user does not change div's value.

**Comment by nili0513** [comment]
@asolntsev 
Before fastsetvalue = true mode, I used the setValue () method to assign values to the input box of the div attribute normally, but after using fastsetvalue = true, the setValue () method cannot assign values to the input box of the div attribute. Only textarea and input input fields can be assigned normally.

![image](https://user-images.githubusercontent.com/47963946/106112914-2bec7100-6191-11eb-896d-4cd3ad6ea603.png)

**Comment by asolntsev** [comment]
@nili0513 Still, `<div>` doesn't have "value". You are probably talking about `div` with attribute `contenteditable="true"`. It's not "value", it's a "content". 

Yes, `fastSetValue=true` doesn't currently support adding texts to such `contenteditable="true"` elements. 
Could you register a [feature request](https://github.com/selenide/selenide/issues/new) for that?

Meanwhile, you can use method `sendKeys()` or `fastSetValue=false` to type text into such elements.

**Comment by nili0513** [comment]
@asolntsev 
ah~~ ,
Thank you for your guide. Since fastsetvalue = true, the sendkeys () method has passed the test.
