### ISSUE TITLE
'An unknown error has occurred' when running tests with the remote Firefox browser using Selenoid.

### ISSUE THREAD

**Issue by avanish-vaghela** [selenide/selenide#1394]
## The problem
'An unknown error has occurred' when running tests with the remote Firefox browser using Selenoid. 

## Details
The test themselves are passing but the following message is displayed in the console. The main issue is that the exception crashes the CI pipeline.

```
Thread-3] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Close webdriver: 26 -> RemoteWebDriver: firefox on LINUX (049d41e5-b654-4b11-a1c6-175c0f859504)...
[Webdrivers killer thread] INFO com.codeborne.selenide.impl.UnusedWebdriversCleanupThread - Thread 14 is dead. Let's close webdriver RemoteWebDriver: firefox on LINUX (049d41e5-b654-4b11-a1c6-175c0f859504)
Exception in thread "Webdrivers killer thread" org.openqa.selenium.WebDriverException: An unknown error has occurred
```

## Tell us about your environment
* **Selenide Version**: 5.18.1
* **Selenoid Version**: 1.10.1
* **Selenoid Configurations Manager Version**: 1.7.2
* **Firefox Version**:  84.0
* **Browser Driver Version**:   3.141.59
* **Selenium Version**:  3.141.59
* **OS Version**:  Linux

## Code To Reproduce Issue [ Good To Have ]

Remote Browser Configuration: 

```
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("enableVNC", true);
capabilities.setCapability("enableVideo", true);
capabilities.setCapability("enableLog", true);
capabilities.setVersion("84.0");
Configuration.browserCapabilities = capabilities;
Configuration.remote = "http://localhost:4444/wd/hub";
Configuration.startMaximized = true;
Configuration.browser = "firefox";
Configuration.reportsFolder = "build/test-reports/google/firefox";
```

Many thanks!

**Comment by asolntsev** [comment]
@avanish-vaghela I cannot reproduce your problem. Firefox runs in Selenoid on my machine. :)

You need find in your logs what was the reason of "An unknown error has occurred".
