### ISSUE TITLE
Nullity annotations are missing for WebDriverRunner

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1395]
## The problem
e.g. `WebDriverRunner.getSelenideProxy();` can return `null`, but IDEA can't show warning about it.

## Tell us about your environment
* **Selenide Version**: 5.18.0

**Comment by asolntsev** [comment]
implemented in https://github.com/selenide/selenide/commit/9b4723d090442c902db53f8e6bdde30410ff92f9
