### ISSUE TITLE
Add a possibility to find SelenideElements inside SelenideElements

### ISSUE THREAD

**Issue by ristoporila** [selenide/selenide#1399]
## Details
For example there are two variables declared in a parent class that the child classes use:
*SelenideElement table1=$("#table1"),
SelenideElement table2=$("#table2"),
SelenideElement button=$("#button");*

If I would want to click the buttons inside the tables, then I would have to use this:
*table1.$("#button").click();
table2.$("#button").click();*

To avoid duplicate code, then I can use a String variable for the locator, but I don't really like this way. What if I have another child class, where there is only one button and I don't have to search for it in a table, then I would like to use just the variable declared in the parent:
*button.click();*

For me the logical way to find the buttons inside the tables, would be like this: 
*table1.find(button).click();
table2.find(button).click();*

**Comment by asolntsev** [comment]
It was always possible using `By`:

```
By button = By.id("button");
table1.$(button).click();
table2.$(button).click();
```

**Comment by ristoporila** [comment]
It's not really what I meant. I like to declare all SelenideElements beforehand with `$` and css selector to keep it clean and consistent. I don't use `By`.

At the moment I am using similar logic you proposed, but with a String.
```
String locatorButton = "#button";
table1.$(locatorButton).click();
table2.$(locatorButton).click();
```

**Comment by asolntsev** [comment]
@ristoporila I am not sure that declaring all possible variable in the beginning of class/method is clean and consistent.
I would even say it's a bad practice.

Generally, in programming, a good practice is to make each variable's scope as narrow as possible. It means: declare every variable only in the place where it's actually needed. 

In other words, you actually want to declare two different web elements with a single `SelenideElement` instance. Seems strange. This is the locator which is the same for both elements. The right type for locator is `By`, not `SelenideElement`.

**Comment by ristoporila** [comment]
I agree that a variable's scope should be as narrow as possible, so I am controlling it with appropriate access modifier. For me the methods in page objects have better readability if I have SelenideElements declared beforehand.

I can see your point about it being a bit strange using a single SelenideElement instance with two different elements though.  You are right. The elements are different, they just share a locator.

Thanks for your replies.
