### ISSUE TITLE
The path separator of the screenshot() method is returning unix character '/' when using windows

### ISSUE THREAD

**Issue by LuisOsv** [selenide/selenide#1401]
## The problem
When using the method screenshot(), then it's returning a path separator of unix when using windows environment

## Details
For instance using `screenshot("Example Google");`
latest version of selenide returns:  `file:/C:/Users/luis.serna/Documents/SelenideNewVersionDemo/build/reports/tests/Example%20Google.png`

older version of selenide returns:
`C:\Users\luis.serna\Documents\SelenideNewVersionDemo\build\reports\tests\Example Google.png`

## Tell us about your environment
* **Selenide Version**:  5.18.0 
* **Chrome\Firefox\IE Version**:  Chrome
* **Browser Driver Version**:  chromedriver 88.0.4324.96 
* **Selenium Version**:  selenium-java-3.141.59
* **OS Version**:  Windows 10 pro

## Code To Reproduce Issue [ Good To Have ]

```
open("https://www.google.com/");
String googlePath = screenshot("Example Google");
```

**Comment by asolntsev** [comment]
Thank you.
Now I see: "file:/C:/Users/luis.serna/Documents/SelenideNewVersionDemo/build/reports/tests/Example%20Google.png" is an URL of screenshot. 

This is o totally valid URL, why do you see a problem here?

**Comment by asolntsev** [comment]
feel free to reopen in case of new information
