### ISSUE TITLE
Add index Condition

### ISSUE THREAD

**Issue by arturmkr** [selenide/selenide#1411]
For example, there is a following html code (table with data):
```
<div class="tableData">
    <div class="header">
        <span>Name</span>
        <span>Age</span>
        <span>Profession</span>
        <span>City</span>
    </div>
    <div class="content">
        <div>
            <span>Mike</span>
            <span>22</span>
            <span>QA</span>
            <span>Minsk</span>
        </div>
        <div>
            <span>Jane</span>
            <span>33</span>
            <span>Developer</span>
            <span>Tallinn</span>
        </div>
    </div>
</div>
```

Task is to write a method, that would return column data.
So, for column City following data should be returned - Minsk, Tallinn.

To do that:
```
  public ElementsCollection getDataForColumn(String columnTitle){
    ElementsCollection tableHeaders = $$("div.tableData > div.header");
    SelenideElement header = tableHeaders.findBy(text(columnTitle));
    int headerIndex = tableHeaders.indexOf(header);
    return $$(String.format("div.tableData > div.content > div > span:nth-child(%s)", ++headerIndex));
  }
```

I propose to add Condition index, so code would look like this:
```
  public ElementsCollection getDataForColumn(String columnTitle){
    ElementsCollection tableHeaders = $$("div.tableData > div.header");
    SelenideElement header = tableHeaders.findBy(text(columnTitle));
    int headerIndex = tableHeaders.indexOf(header);
    return $$("div.tableData > div.content > div > span").filter(Condition.index(headerIndex));
  }
```

**Comment by asolntsev** [comment]
@arturmkr It seems the second code is not really simpler than the first. In other words, introducing `index` condition doesn't really make things easier: you still need to write the hard flaky selector "div.tableData > div.content > div > span". 

In fact, it will make the tests _slower_ because selenide will load all `<span>`s from the browser and filter them on client side. 

P.S. Why are you using `++headerIndex` - the variable `headerIndex` is not used anymore?

**Comment by arturmkr** [comment]
> Why are you using ++headerIndex - the variable headerIndex is not used anymore?
Because in Java array starts with 0 index, but in JS array starts with 1.

**Comment by asolntsev** [comment]
Ah so. Then I would write `headerIndex+1` because you need to increase the value of the variable.

**Comment by asolntsev** [comment]
Feel free to reopen if got new information.
