### ISSUE TITLE
Microsoft Edge User Agent Test Failed

### ISSUE THREAD

**Issue by mystygage** [selenide/selenide#1423]
## The problem
I ran the test case for edge (`gradle edge`) and UserAgentTest failed:
```
UserAgentTest > currentUserAgentTest() FAILED
    java.lang.AssertionError at UserAgentTest.java:16
```

## Details
The official user agent for Chromium based Edge ist `Edg` as described here: https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string
The test case expects that `BaseIntegrationTest.browser` -> `edge` is part of the user agent.

I would like to create a PR for this, but I'm not shure how to handle browser specific test cases like this?

## Tell us about your environment
* **Selenide Version**: 5.19.0
* **Edge Version**: 88.0.705.81 
* **OS Version**: macOS 11.2.2

**Comment by asolntsev** [comment]
@mystygage Thank you for reporting the problem. 
Yes, please create a PR. 

> how to handle browser specific test cases like this?

The point of this test is just check that `getUserAgent()` works (somehow). And not to to test functionality of the browser itself. I think this test should be as simple and generic as possible. For example, it could check that user agent contains "Windows NT". Or even `isNotBlank()` is enough.

**Comment by mystygage** [comment]
Ok, I did a small workaround to support the matching naming pattern as good as it gets (https://github.com/mystygage/selenide/commit/223a80270624dd27526a8e627d030422d65facc8), but now there are some other tests failing:
```
FileUploadToGridTest.userCanUploadMultipleFiles()
FileUploadToGridTest.userCanUploadMultipleFiles_withoutForm()
SeleniumGridTest.canUseSeleniumGrid()
SeleniumGridTest.shouldUseLocalFileDetector()
```

I think these should also be fixed before I create the PR...

**Comment by asolntsev** [comment]
@mystygage Thank you for reporting it. 
I have fixed those tests in PR https://github.com/selenide/selenide/pull/1425. Let's see if github actions can run Selenide tests in Edge...
