### ISSUE TITLE
Rephrase ATTENTION line in javadoc

### ISSUE THREAD

**Issue by NewbieProger** [selenide/selenide#1430]
https://github.com/selenide/selenide/blob/fa420bd51e113f4629b97864c11a1c0ad2397cc8/src/main/java/com/codeborne/selenide/SelenideElement.java#L596

Изменить формулировку о том, что методы не производят поиск.
Предлагаю "Данный метод не производит поиск элемента, пока над ним не будут совершаться действия. 
Например, $("foo") не будет искать элемент на странице"
Например, $("foo").click()  будет искать элемент на странице и попробует его нажать"

**Comment by asolntsev** [comment]
Basically it's the right idea to improve the doc. 
But this clause is duplicated in many places. 
Probably just replace it by "lazy loading" and a link to page like https://github.com/selenide/selenide/wiki/lazy-loading ?

**Comment by NewbieProger** [comment]
Yeap, it's even better.
