### ISSUE TITLE
Tests not running in Microsoft Edge 90.0 in selenoid container

### ISSUE THREAD

**Issue by ArturFazlyev** [selenide/selenide#1440]
Tests not running in Microsoft Edge 90.0 in selenoid container.
Env:
Browser Microsoft Edge 90.0
Selenoid
Selenide 5.20.1

The connection is made as follows:
            switch (browser) {
            case BrowserType.CHROME:
                Configuration.browser = browser;
                Configuration.remote = LoadProperties.getProperties (). GetProperty ("selenium.server");
                Configuration.browserVersion = "89.0";
                break;
            case BrowserType.FIREFOX:
                Configuration.browser = browser;
                Configuration.remote = LoadProperties.getProperties (). GetProperty ("selenium.server");
                Configuration.browserVersion = "86.0";
                break;
            case BrowserType.EDGE:
                Configuration.browser = browser;
                Configuration.remote = LoadProperties.getProperties (). GetProperty ("selenium.server");
                Configuration.browserVersion = "90.0";
                break;
        }

As a result, we get an error:
 java.lang.IllegalArgumentException: Class not found: MicrosoftEdge
10:49:14
  Caused by: java.lang.ClassNotFoundException: MicrosoftEdge

Everything works fine on Selenide 5.6.1.

**Comment by BorisOsipov** [comment]
Configuration.browser must be `edge` not `MicrosoftEdge`

**Comment by dacloutier-logmein** [comment]
Doesn't this differ from Aerokube's specs:

https://aerokube.com/images/latest/#_microsoft_edge

which requires to use `MicrosoftEdge`

I am running into issues where locally, I would be able to use `Edge`, but on Selenoid, it would not find the proper image:

`org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 404. Message: unsupported browser: edge`

**Comment by lorsatti** [comment]
@BorisOsipov [here](https://github.com/aerokube/selenoid/issues/1015#issuecomment-721923884) you can read exactly the other way round... 😄  
How should it work?

**Comment by BorisOsipov** [comment]
>How should it work?

It works out of the box...
```
    @Test
    public void test() {
        Configuration.remote = "http://localhost:4444/wd/hub";
        Configuration.browser = "edge";
        open("https://www.google.com/");
        Selenide.sleep(500);
    }
```
test run log:
```
Nov 03, 2021 6:06:31 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[main] INFO com.codeborne.selenide.webdriver.BrowserResizer - Set browser size to 1366x768
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - BrowserName=msedge Version=95.0.1020.9 Platform=LINUX
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenide v. 6.0.3
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenium WebDriver v. 4.0.0 build revision: 3a21814679
[main] INFO com.codeborne.selenide.drivercommands.CreateDriverCommand - Create webdriver in current thread 1: RemoteWebDriver -> RemoteWebDriver: msedge on LINUX (1c9f4701016f89d39da4018d792825eb)
[Thread-4] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Close webdriver: 26 -> RemoteWebDriver: msedge on LINUX (1c9f4701016f89d39da4018d792825eb)...
[Thread-4] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Closed webdriver 26 in 5 ms

Process finished with exit code 0
```
Selenoid config
```
bo@bo-MS-7B86:~/.aerokube/selenoid$ cat browsers.json 
{
    "MicrosoftEdge": {
        "default": "95.0",
        "versions": {
            "95.0": {
                "image": "browsers/edge:95.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "chrome": {
        "default": "95.0",
        "versions": {
            "95.0": {
                "image": "selenoid/chrome:95.0",
                "port": "4444",
                "path": "/"
            }
        }
    },
    "firefox": {
        "default": "93.0",
        "versions": {
            "93.0": {
                "image": "selenoid/firefox:93.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}
```

**Comment by BorisOsipov** [comment]
Also works on 5.25.0
```
[main] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
Nov 03, 2021 6:12:20 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[main] INFO com.codeborne.selenide.webdriver.BrowserResizer - Set browser size to 1366x768
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - BrowserName=msedge Version=95.0.1020.9 Platform=LINUX
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenide v. 5.25.0
[main] INFO com.codeborne.selenide.webdriver.WebDriverFactory - Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
[main] INFO com.codeborne.selenide.drivercommands.CreateDriverCommand - Create webdriver in current thread 1: RemoteWebDriver -> RemoteWebDriver: msedge on LINUX (91c4e8045643084df83699a01174bdd2)
[Thread-1] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Close webdriver: 23 -> RemoteWebDriver: msedge on LINUX (91c4e8045643084df83699a01174bdd2)...
[Thread-1] INFO com.codeborne.selenide.drivercommands.CloseDriverCommand - Closed webdriver 23 in 55 ms

Process finished with exit code 0
```

**Comment by asolntsev** [comment]
I confirmed, just executed my tests on "edge" browser in Selenoid.
