### ISSUE TITLE
Add conditions that don't depend on web element

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1442]
There are few cases when conditions don't depend on web element. 
E.g. conditions for asserting clipboard\localstorage\etc

Seems it should be like `Selenide.clipboard().shouldHave(value("foobar")`

**Comment by bereg2k** [comment]
Should it be some kinda common interface that others like `Clipboard` or `LocalStorage` should extend?

**Comment by BorisOsipov** [comment]
@bereg2k seems yes

**Comment by dbudim** [comment]
@asolntsev @BorisOsipov 
What if we'll make check by predicate?)

Create interface `Conditional<T>` with method `void should(Predicate<T> predicate, String message);`

And all who wants support conditional wait need implement it with own type.
e.g. - ` LocalStorage implements Conditional<LocalStorage>` and overrides method with this type
`public void should(Predicate<LocalStorage> predicate, String message) ` where we can use some check utils method which will check predicate until timeout.

In test it will looks like
` Selenide.localStorage().should(storage -> storage.getItem("cat").equals("Tom"), "cat attribute in local storage doesn't match");`

**Comment by dbudim** [comment]
And one more question )
Do we need make own await implementation or can use some lib like Awaitility?)

**Comment by asolntsev** [comment]
> Create interface `Conditional<T>` with method `void should(Predicate<T> predicate, String message);`

1. Yes, I like the idea with `localStorage().should`. Though, I would like to have some most used predicates/conditions in Selenide out of the box. Say, 
  * `localStorage().shouldHave(item("cat", "Tom"))`,  
  * `localStorage().shouldBe(empty)` etc.
2. How could look like this API for the browser?  Something like
  * `BLAH().shouldHave(url("/bank/login/"))`
  * `BLAH().shouldHave(openedWindows(5))` etc.


> Do we need make own await implementation or can use some lib like Awaitility?)

We can use Awaitility if needed. I just didn't see a need for it until now.

**Comment by dbudim** [comment]
> @dbudim
> 
> > Create interface `Conditional<T>` with method `void should(Predicate<T> predicate, String message);`
> 
> 1. Yes, I like the idea with `localStorage().should`. Though, I would like to have some most used predicates/conditions in Selenide out of the box. Say,
> 
> * `localStorage().shouldHave(item("cat", "Tom"))`,
> * `localStorage().shouldBe(empty)` etc.


I though about flexibility for user to define any predicate as need) 
We can save flexibility and add built-in predicates via creating conditions for appropriate functionality.
E.g. for local storage - create `LocalStorageConditions` with static methods that returns built in predicate

`public static Predicate<LocalStorage> itemHasValue(String item, String value) {`
        ` return localStorage -> localStorage.getItem(item).equals(value);`
`  }`

And in test will be 
`Selenide.localStorage().should(LocalStorageConditions.itemHasValue("cat","Tom"), "item value doesn't match");`

or with static import
`Selenide.localStorage().should(itemHasValue("cat","Tom"), "item value doesn't match");`





> 
> 1. How could look like this API for the browser?  Something like
> 
> * `BLAH().shouldHave(url("/bank/login/"))`
> * `BLAH().shouldHave(openedWindows(5))` etc.


Actions with browser will be the same because it's just retry operation with ignoring exceptions until timeout)


> 
> > Do we need make own await implementation or can use some lib like Awaitility?)
> 
> We can use Awaitility if needed. I just didn't see a need for it until now.

**Comment by dbudim** [comment]
@asolntsev @BorisOsipov  I've made WIP: [PR 1478](https://github.com/selenide/selenide/pull/1478) just to show implementation)
For now didn't add docks and not prettified PR)
Please look and if all is ok, i'll add docs and make some pretty for PR)

**Comment by asolntsev** [comment]
will be released as Selenide 5.23.0 soon
