### ISSUE TITLE
PR #1370 Removed ability to use and/or static conditions in code that is depended on by a separate project

### ISSUE THREAD

**Issue by ben-nc2** [selenide/selenide#1443]
## The problem
PR #1370 means that the static and and or conditions expected multiple parameters rather than one which breaks our code when using compiled and packaged dependencies

## Details
We are currently blocked from upgrading from Selenide 5.17.x to a later version due to the effect that PR #1370 has had on our codebase. We have two repositories, one that we write UI tests against UI components and then a second that is testing an app that uses these UI components.

We have our own conditions that work in the UI component repo but when these are compiled and depended on by the second repo we get a `java.lang.NoSuchMethodError` error.

Pre-compiled they work like this
`            Condition condition = Condition.and("Visible", Condition.visible, not(cssClass("slds-assistive-text")));
            ((IHasLabel) cmp).label().shouldBe(condition);`
and that still works

However when calling this method from the second repo codebase we see the following compiled code:

`            Condition condition = Condition.and("Visible", Condition.visible, Condition.not(Condition.cssClass("slds-assistive-text")), new Condition[0]);
            ((IHasLabel)cmp).label().shouldBe(new Condition[]{condition});`

which then fails with the error

`java.lang.NoSuchMethodError: 'com.codeborne.selenide.Condition com.codeborne.selenide.Condition.and(java.lang.String, com.codeborne.selenide.Condition[])'`

We can work around this by updating all our references to Condition.and and Condition.or to use new And() and new Or() as this then takes a list and is handled but we would prefer to avoid this if possible.

## Tell us about your environment
Selenide version 5.18.x onwards
Latest Chrome and ChromeDriver on windows and linux

**Comment by asolntsev** [comment]
@ben-nc2 hi. And what is your suggestion?

As long as I see, you just need to upgrade both libraries to the latest Selenide version. Why not? I don't see any problems here. Why are you thinking of workarounds instead of this simple solution?

**Comment by ben-nc2** [comment]
Both our libraries are using the same selenide version but when the static and method is called in compiled jar dependency code it throws the error because the compiled version seems to only pass single varargs rather than the two conditions to the varargs. If that doesn't explain it properly I will try and create an example for you but at the moment it's wrapped too heavily in our code.

**Comment by asolntsev** [comment]
@ben-nc2 Yes, it's not clear for me. Sorry. :( 
I guess you still have some older version of Selenide or your jars in classpath...

**Comment by ben-nc2** [comment]
I believe it's because I need to have compiled and build the dependent library against 5.18+ before using it to run against my calling project with 5.18+. Will close, apologies
