### ISSUE TITLE
Add item search up from the current item

### ISSUE THREAD

**Issue by devmaster-st** [selenide/selenide#1446]
## The problem
Using the closest () method, I cannot search for ancestors that have specific parameter values.

## Details
For example, this entry is currently invalid: $.closest("data-test", "message-manager").getAttribute("id")
I want to find an ancestor that has data-test = 'message-manager' and get the id value from it.
And it would also be nice to rename the closest() method to ancestor() according to the xPath terminology (https://www.w3schools.com/xml/xpath_axes.asp).

## Tell us about your environment
* **Selenide Version**: 5.19.0
* **Chrome\Firefox\IE Version**: Chrome 89
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: macOS 10.15.7

## Code To Reproduce Issue [ Good To Have ]
$.closest("data-test", "message-manager")

**Comment by BorisOsipov** [comment]
Duplicate https://github.com/selenide/selenide/issues/1429
