### ISSUE TITLE
Possibility of applying $.hover() with offset

### ISSUE THREAD

**Issue by devmaster-st** [selenide/selenide#1447]
## The problem
Now the $.hover() method can hover the mouse cursor only at the center of the element, but in some cases it is required to hover over a place other than the center.

## Details
It would be convenient to apply an offset for the $.hover(), just as it is done for click now: $.hover(offset(offsetX, offsetY));

## Tell us about your environment
* **Selenide Version**: 5.19.0
* **Chrome\Firefox\IE Version**: Chrome 89
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: macOS

## Code To Reproduce Issue [ Good To Have ]
$.hover(offset(offsetX, offsetY));

**Comment by asolntsev** [comment]
fixed by #1461, will be released in Selenide 5.21.0
