### ISSUE TITLE
Suggestion add a tip, that it founds in DOM, not on screenview

### ISSUE THREAD

**Issue by NewbieProger** [selenide/selenide#1452]
https://github.com/selenide/selenide/blob/5230caa32807189f3b838bf7f8de0daa08adbcda/src/main/java/com/codeborne/selenide/Condition.java#L62

Suggest add this specifications to javaDoc and to others like this

**Comment by asolntsev** [comment]
@NewbieProger Could you specify an exact text to add? 

I see the javadoc already mentions that element may be hidden:
> Check if element exist. It can be visible or hidden.
