### ISSUE TITLE
Hiding nested locators in Allure report

### ISSUE THREAD

**Issue by AlexChernookov** [selenide/selenide#1459]
Hello,
I'm using Selenide+TestNg+Allure with PageObject pattern, I have a method for parsing and storing elements in ElementsCollection

```
@Step("Click checkBoxs with empty value ")
public void some_method(){
ElementsCollection ec = $$x("//myXpath");
for (SelenideElement e : ec){
 String value = e.$x("div").getAttribute("value")
if(value.isEmpty()){
e.click;
}

@Test
public void myTest(){
some_method();
}
```
After executing test there is following structure in Allure report:

> Click checkBoxs with empty value 
 . $$(By.xpath("//myXpath"))[0].$(By.xpath("div")) get value
 . $$(By.xpath("//myXpath"))[1].$(By.xpath("div")) get value
 . $$(By.xpath("//myXpath"))[2].$(By.xpath("div")) get value
 . $$(By.xpath("//myXpath"))[3].$(By.xpath("div")) click
.....................................
 . $$(By.xpath("//myXpath"))[100500].$(By.xpath("div")) get value

As I understand Allure is determining each $ or $$ as a step.
Is it possible to hide such detailed steps from the report ? When showing something like this to managers they wanted to see human-readable report :). 

I will be really appreciate for any suggestions or recommendations

**Comment by asolntsev** [comment]
@AlexChernookov Yes, `AllureSelenide` does add any action with Selenide to the report. 

How could it understand what steps do you want to see in report? How is it possible? The machine cannot read your thoughts. 

One possible solution is to avoid using `AllureSelenide` and mark the needed steps with Allure annotation `@Step`. 
Other possible solution is to **stop generating reports for managers**. The report is **for you**! The report is just a tool to allow you understand why the test failed. Nothing else. Let managers read excels.
