### ISSUE TITLE
How can I open a new tab in Chrome?

### ISSUE THREAD

**Issue by CloudWzhZzz** [selenide/selenide#1468]
I use   5.19.0

public void TestDemo2(){
        Configuration.browser = "chrome";
        open("https://www.abc.com");
        sleep(1000);
        switchTo().window(1);
        }

But IDE :
No window found with index: 1
Caused by: TimeoutException: Expected condition failed: waiting for window to be available by index: 1 (tried for 4 second(s) with 200 milliseconds interval)

**Comment by anilreddy** [comment]
@CloudWzhZzz This is a bug reporting area. Next time ask in stackoverflow

```java
String selectLinkOpeninNewTab = Keys.chord(Keys.CONTROL,Keys.RETURN);
$(By.linkText("urlLink")).sendKeys(selectLinkOpeninNewTab);
```

**Comment by CloudWzhZzz** [comment]
Thank you！
After reading the official api documentation of selenide, I didn't understand the usage of "switchTo". I thought it was possible to open a new tab page, so I mistakenly thought it was a bug, so I came here to ask questions.

**Comment by asolntsev** [comment]
@CloudWzhZzz method `switchTo` is used to switch between _existing_ tabs/windows/frames. It cannot open a new window.

Most probably you don't really need to open a new window. Can you specify why you think you need it?

**Comment by CloudWzhZzz** [comment]
> @CloudWzhZzz method `switchTo` is used to switch between _existing_ tabs/windows/frames. It cannot open a new window.
> 
> Most probably you don't really need to open a new window. Can you specify why you think you need it?

I need to open two tabs, log in on tab 1, then switch to tab 2 and refresh the page, so that tab 2 can use the cookie of tab 1 to log in automatically.
You may ask why you don’t log in directly on the  tab2, because the page opened on the  tab2 needs to be verified by the machine verification code if you want to log in, but the machine cannot pass the verification code verification, so you can only use the methods I mentioned above. Sign in to bypass the verification code verification process.

**Comment by asolntsev** [comment]
Sorry, i still have some questions :)

1. How do you bypass the verification code check in tab1?
2. If you can login in tab1 somehow, why cannot you use the same mechanism for logging in tab2?
3. When you have logged in in tab1, why can't you just continue the test in tab1 without opening any new tabs?

**Comment by CloudWzhZzz** [comment]
1.The process of bypassing the machine verification code is to use the internal login service. This is not universal, so the detailed process is not described.You can understand it as opening the back door on the login machine and directly obtaining the cookie of the account.
2.As mentioned in 1, tab1 is only used to obtain the cookie of the account, and has no other use, so after tab1 obtains the cookie, open tab2 and enter the website, you can use the cookie obtained by tab1 under the same browser to log in directly.
3.emmmm,this is indeed a way, I didn't expect it at the time, thank you for your reminder.(>_<|||)
