### ISSUE TITLE
Frequent error NullPointerException during passing from one page to another in construction SelenideElement.shouldBe(disappear))

### ISSUE THREAD

**Issue by stru4OK** [selenide/selenide#1474]
## The problem
Good afternoon!
I used following stack: Selenoid + Selenide + Jenkins. Encounter current error with nullpointerexception while trying to check if SelenideElement is not presented more longer on the page after click on button that lead to another page. What should I do to workaround this problem? Wait until page is load and after that check availability of Selenide Elements on it?
Thank you!

Full error stack:

```java
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:329)
	at com.codeborne.selenide.conditions.Hidden.apply(Hidden.java:20)
	at com.codeborne.selenide.impl.WebElementSource.checkCondition(WebElementSource.java:100)
	at com.codeborne.selenide.commands.Should.execute(Should.java:30)
	at com.codeborne.selenide.commands.Should.execute(Should.java:14)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:155)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:133)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:85)
	at com.sun.proxy.$Proxy21.shouldBe(Unknown Source)
	at Customers.TSystems.Modules.IDaaS.Pages.CreateNewADUser.createNewADUser(CreateNewADUser.java:255)
	at Customers.TSystems.Modules.IDaaS.Tests.CreateADUser.createSuccessMultipleADUsers(CreateADUser.java:114)
```

## Tell us about your environment
* **Selenide Version**: 5.20.1
* **Chrome\Firefox\IE Version**: Selenoid containter with Firefox 87.0
* **Browser Driver Version**: - // -
* **Selenium Version**:  - // -
* **OS Version**: Linux 3.10.0-1127.13.1.el7.x86_64

## Code To Reproduce Issue [ Good To Have ]
Creation of remote driver:

```java
URL url = null;

try {
   url = new URL(Props.getProps().hubAddress);
} catch (MalformedURLException e) {
   e.printStackTrace();
}

RemoteWebDriver driver = new RemoteWebDriver(url, getBrowserOptions());
```

`getBrowserOptions()` - here I set browser profile variables, set capability etc.

Variable declaration in class:
```java
private SelenideElement TEXT_STEP_HEADER = $x("//span[contains(text(),'Configure New AD User')]//span[contains(text(),'(Active)')]");
private SelenideElement BUTTON_NEXT = $x("//span[contains(text(),'Next')]/parent::button");
```

and in method further use it after when go to another page:

```java
//go to another page
BUTTON_NEXT.shouldBe(appear).click(); 
//check that header disappeared
TEXT_STEP_HEADER.shouldBe(disappear, Duration.ofSeconds(15)); 
```

**Comment by anilreddy** [comment]
@stru4OK this info is not clear can you provide more details like how you are passing driver etc,.

**Comment by BorisOsipov** [comment]
@stru4OK in fact it is NPE in selenium internal code and not related to selenide. is it stable? can you share reproducable example?

**Comment by stru4OK** [comment]
> @stru4OK this info is not clear can you provide more details like how you are passing driver etc,.

Good afternoon! Yes, of course I could share snippet of code, but I'm not sure that creation of remote driver has impact on getting NullPointExc. It looks like (according video of test) during passing from one page to another one I get this error, like DOM was lost or something like that. But I presumed that Selenide should wait if StaleException (or something like that) is fired. Or here in current situation we have something another? 

Creation of remote driver:
URL url = null;

try {
   url = new URL(Props.getProps().hubAddress);
} catch (MalformedURLException e) {
   e.printStackTrace();
}

RemoteWebDriver driver = new RemoteWebDriver(url, getBrowserOptions());

getBrowserOptions() - here I set browser profile variables, set capability etc.

**Comment by stru4OK** [comment]
> @stru4OK in fact it is NPE in selenium internal code and not related to selenide. is it stable? can you share reproducable example?

Good afternoon!
If the reason of current NPE is Selenium core, should I use try/catch/finally, I mean wrap every call '<SelenideElement>.shouldBe(<condition>)' in order to handle NPE and repeat this step again? But maybe it's more simpler and comfortable to add this mechanism in the core of Selenide?
For example, as far as I know some of errors StaleException Selenide now is handling, so maybe it (handling of NPE) should include in package of Selenide as well.

**Comment by anilreddy** [comment]
@stru4OK have you set driver to below code: If not it will throw NPE
```java
WebDriverRunner.setWebDriver(driver);
```

**Comment by stru4OK** [comment]
> @stru4OK have you set driver to below code: If not it will throw NPE
> 
> ```java
> WebDriverRunner.setWebDriver(driver);
> ```

Good afternoon!
In Selenide, I set driver like this:

Configuration.browser = RemoteBrowser.class.getName();

where RemoteBrowser is class that implements WebDriverProvider with overridden method:

@Override
    public RemoteWebDriver createDriver(DesiredCapabilities capabilities) {
        URL url = null;
        try {
            url = new URL(Props.getProps().hubAddress);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        RemoteWebDriver driver = new RemoteWebDriver(url, getBrowserOptions());
        this.sessionName = driver.getSessionId().toString();

        return driver;
    }

But I'm not sure that the problem is here, because everything works well unless SelenideElement.shouldBe(disappear) which failed hardly ever (1-3%).

**Comment by asolntsev** [comment]
@stru4OK It's a [bug 9266](https://github.com/SeleniumHQ/selenium/issues/9266) in Selenium WebDriver which is already fix in [PR 9299](https://github.com/SeleniumHQ/selenium/pull/9299). Unfortunately, it will only be released in Selenium 4.0 (and the release date is absolutely unknown). :(

We could create a workaround in Selenide, thought. The only drawback it might hide some other NPE inside of Selenium code. A hard choice...

**Comment by stru4OK** [comment]
Hello, @asolntsev!
Copy that! Thank you for answer!

**Comment by stru4OK** [comment]
Good afternoon!
Today have caught the same NPE: I've called SelenideElement.isDisplayed() and got:

```
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.isDisplayed(RemoteWebElement.java:329)
	at com.codeborne.selenide.commands.IsDisplayed.execute(IsDisplayed.java:22)
	at com.codeborne.selenide.commands.IsDisplayed.execute(IsDisplayed.java:15)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:155)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:133)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:85)
	at com.sun.proxy.$Proxy27.isDisplayed(Unknown Source)
```

**Comment by stru4OK** [comment]
@asolntsev, thank you for workaround! Have a great week!
