### ISSUE TITLE
You can't get a screenshot without  Configuration.screenshots = true;

### ISSUE THREAD

**Issue by stasek** [selenide/selenide#1477]
## The problem
Set Configuration.screenshots = false;. Use Selenide.screenshot("file_name"); in your code.
Selenide does not make screenshots

broken since version 5.16.0

## Tell us about your environment
* **Selenide Version**: 5.21.0
* **Chrome\Firefox\IE Version**: latest
* **Browser Driver Version**: latest
* **Selenium Version**: 3.141.59
* **OS Version**: masOSx 11.3.1

## Code To Reproduce Issue [ Good To Have ]
```
import com.codeborne.selenide.Configuration;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.*;

public class Example {

    @Test
    void getScreen(){
        Configuration.screenshots = true;
        open("https://google.com");
        screenshot("I_can");
        closeWebDriver();
    }

    @Test
    void cannotGetScreen(){
        Configuration.screenshots = false;
        open("https://google.com");
        screenshot("I_cannot");
        closeWebDriver();
    }

}
```

**Comment by BorisOsipov** [comment]
Seems broken in result of https://github.com/selenide/selenide/pull/1317
