### ISSUE TITLE
 Add work with Alert during file upload

### ISSUE THREAD

**Issue by MariyaStrucheva** [selenide/selenide#1479]
## The problem
In tests I need to download file with next case:

1. Click button for download
2. Get text from opened Alert for check
3. Submit Alert
4. Get downloaded file

## Details
Must have: auto submit/cancel alert for download
Nice to have: get text from Alert for checking

## Tell us about your environment
* **Selenide Version**: 5.21.0
* **Chrome\Firefox\IE Version**: Chrome 90v
* **OS Version**: Mac Os

**Comment by asolntsev** [comment]
@MariyaStrucheva See https://github.com/selenide/selenide/pull/1481

**Comment by MariyaStrucheva** [comment]
@asolntsev looks good! Will it be released in the next version?

**Comment by asolntsev** [comment]
yes, we can release Selenide 5.22.0 as soon as code review is completed.
