### ISSUE TITLE
Custom screenshot function

### ISSUE THREAD

**Issue by PavelOnz** [selenide/selenide#1486]
## The problem
Hello,
This is only a question: is there any way to override screenshot function in Selenide, so when screenshot event is triggered, its done using my function?
Thanks a lot!

BR,
Pavel

**Comment by asolntsev** [comment]
@PavelOnz Could you please describe the problem you are trying to solve?
Do you want to change a screenshot name or location? And why?

**Comment by PavelOnz** [comment]
Hi and thanks for quick reply. My screenshotting function does also element highlighting (setting the style through JS) and some few small things. 
I created some extra AssertJ assertions (against SelenideElement), which calls the function on failure, but it would be nice to have this possibility also when it comes to built in Selenide conditions for example.

**Comment by asolntsev** [comment]
@PavelOnz Sorry, but I would say it seems a bit useless :)
Why should one highlight the element if you know what the element it is? What problem are you trying to solve with the highlighting? I recommend to be pragmatic and avoid doing things "just for beauty". 

Anyway, you can create a file `src/main/resources/META-INF/defaultservices/com.codeborne.selenide.impl.Photographer` with content `com.yourcompany.YourPhotographer`. Then create a class `YourPhotographer` implementing interface `com.codeborne.selenide.impl.WebdriverPhotographer`.
