### ISSUE TITLE
About Supported Browsers

### ISSUE THREAD

**Issue by MitsubishiUFJInformationTechnologyLtd** [selenide/selenide#1491]
Hello,

This is just a comment.

GitHub wiki and FAQ at Selenide website say Selenide supports HtmlUnit.
However it doesn't at least in the latest version.
So I think it's a little bit confusing and better to mention at which version we can use HtmlUnit.

Selenide FAQ : https://selenide.org/faq.html
Supported browser : https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/Browsers.java

**Comment by asolntsev** [comment]
Hi @MitsubishiUFJInformationTechnologyLtd !
Actually HtmlUnit is also supported, you just need to 
1. add a dependency `implementation 'org.seleniumhq.selenium:htmlunit-driver:2.50.0'`
2. Use full class name as a "browser": `System.setProperty("selenide.browser", "org.openqa.selenium.htmlunit.HtmlUnitDriver");`

Anyway, thank you for noticing that. I will update the FAQ.
