### ISSUE TITLE
Make Java 11 a minimum requirement

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1496]
Currently Selenide requires Java 8 or higher (works on Java 11..17 for sure).

What do you think about increasing the minimum required Java version to 11?

Please vote 
* 👍 if you agree to Java 11, and
* 👎 if you still have to use Java 8.

**Comment by jreznot** [comment]
Could you please clarify how Selenide could benefit from JDK 11 baseline?

**Comment by bereg2k** [comment]
@jreznot [Local Variable Type Inference](https://docs.oracle.com/en/java/javase/13/language/local-variable-type-inference.html) first comes to mind. More readability, less verbosity, less code.

**Comment by jreznot** [comment]
> @jreznot [Local Variable Type Inference](https://docs.oracle.com/en/java/javase/13/language/local-variable-type-inference.html) first comes to mind. More readability, less verbosity, less code.

It is already available for projects with Selenide. Why is it needed for library itself?

**Comment by asolntsev** [comment]
@jreznot Well, it's not really critical in Selenide itself. It's rather a wish to be up-to-date and strive our users to update dependencies (incl. Java).

**Comment by asolntsev** [comment]
Closing the issue at the moment. 
It seems there is still a number of people still using Java 8. Let's postpone this decision (probably to a next major version of Selenide).
