### ISSUE TITLE
Improve switchTo().innerFrame() API

### ISSUE THREAD

**Issue by cbxp** [selenide/selenide#1500]
## The problem
* `innerFrame(vararg)` actually compiles without any args: `innerFrame()` - the expectation being that it could switch to the first (or only) available frame, on the page, but in reality it does nothing, not even an exception
*  `innerFrame()` accept frame id or names a parameter, which is inconsistent with `$()`, which accepts selectors. It would be nice to make two versions: 1. With instances of FrameByIdOrName 2. With string selectors. Maybe also rename the method to `frame()` and deprecate the old one because of behaviour change.
* Maybe switchTo() could also be a singleton constant, so that parentheses would not be needed?

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 5.22.2

**Comment by asolntsev** [comment]
implemented in PR #1509
