### ISSUE TITLE
RemoteWebDriver set firefox   not work

### ISSUE THREAD

**Issue by zhupengfarmer** [selenide/selenide#1501]
## The problem
When I upgraded from v5.15.1 to v5.22.2, I found that my test cases before relying on firefox all failed.After the test, I found that I set Configuration.browse = firefox, and it turned into chrome when I started RemoteWebDriver.

## Details

```java
Configuration.browser = getBrowser(browser);
 logger.info("浏览器配置-浏览器类型: " + Configuration.browser);

    private static String getBrowser(String browser) {
        String BROWSER = browserType;

        if (browser == null) {
            if (EnvInitUtil.env.equals("自动化测试巡检")) {
                BROWSER = "firefox";
            } else if (EnvInitUtil.env.equals("test")) {
                BROWSER = "chrome";
            }
        } else {
            BROWSER = browser;
        }

        return BROWSER;
    }
```

and   runtime

```bash
[2021-07-06 17:16:07.313] [TestNG-test=Customer Test1-1] INFO  c.m.uat.Util.InitUtil.DriverInitUtil.getChromeDriver [138] -  浏览器配置-浏览器类型: firefox

[2021-07-06 17:16:07.521] [TestNG-test=Customer Test1-3] INFO  c.c.s.i.WebDriverThreadLocalContainer.getAndCheckWebDriver [138] -  No webdriver is bound to current thread: 25 - let's create a new webdriver

Jul 06, 2021 5:16:09 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

[2021-07-06 17:16:09.584] [TestNG-test=Customer Test1-3] INFO  c.c.s.webdriver.WebDriverFactory.logBrowserVersion [138] -  BrowserName=chrome Version=91.0.4472.77 Platform=LINUX
[2021-07-06 17:16:09.585] [TestNG-test=Customer Test1-3] INFO  c.c.s.webdriver.WebDriverFactory.createWebDriver [79] -  Selenide v. 5.22.2
```

**Comment by zhupengfarmer** [comment]
/*
        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("name", zaleniumTestName);
        capabilities.setCapability(ChromeOptions.CAPABILITY, option);
        capabilities.setCapability("idleTimeout", 150);

        //baseUrl 配置
        Configuration.baseUrl = baseUrl;
        logger.info("浏览器配置-baseUrl: " + Configuration.baseUrl);

        //option 配置
        Configuration.browserCapabilities = capabilities;
*/

The problem appeared in Configuration.browserCapabilities. When v5.15.1, I set Configuration.browserCapabilities = chromoption, and then set Configuration.browser = firefox, and the startup browser is firefox. When the version comes to v5.22.2, the startup browser is chrome

**Comment by asolntsev** [comment]
@zhupengfarmer Can you provide a full working example?
I am trying to run your code, and it opens a Firefox browser.

**Comment by zhupengfarmer** [comment]
```java
       ChromeOptions option = new ChromeOptions();
        //去掉chrome 正受到自动测试软件的控制
        option.addArguments("disable-infobars");
        option.addArguments("user-agent=" + USER_AGENT);
        option.addArguments("--disable-blink-features=AutomationControlled");
        option.addArguments("--lang=zh-CN");


        //设置开发者模式启动
        //option.setExperimentalOption("excludeSwitches", Collections.singletonList("enable-automation"));
        option.setExperimentalOption("useAutomationExtension", false);
        option.setExperimentalOption("prefs", prefs);


        DesiredCapabilities capabilities = new DesiredCapabilities();

        capabilities.setCapability("name", zaleniumTestName);
        capabilities.setCapability(ChromeOptions.CAPABILITY, option);
        capabilities.setCapability("idleTimeout", 150);



        Configuration.browser = "firefox"
        Configuration.browserCapabilities = capabilities;

```

**Comment by asolntsev** [comment]
@zhupengfarmer Sorry, it's a not a fully compilable code. Variables `zaleniumTestName` and `prefs` are not defined.
And it's still not clear how you run a `RemoteWebDriver`.

Anyway, when I am trying to run this code, I see **Firefox** browser opened.
