### ISSUE TITLE
product requirement

### ISSUE THREAD

**Issue by long5192004** [selenide/selenide#1503]
In the autotest ui project, usually ,I need the fame support the datase init operation.

for example. Data Init at first,and when the autotest run over. we need destroy the data.

Could you support the frame for the database .just like MYSQL，oracle.

**Comment by rosolko** [comment]
No, we couldn't. Selenide is not about test data and database access layer.

**Comment by asolntsev** [comment]
@long5192004 In theory, we could implement a database support, but I don't see any reasons why we should do it. There are plenty of similar frameworks on the web. Why don't you use them? :)
