### ISSUE TITLE
Implement `ObjectCondition<WebDriver>` for the "number of windows" condition

### ISSUE THREAD

**Issue by bereg2k** [selenide/selenide#1508]
Implement ObjectCondition<WebDriver> for the number of opened windows.

## Details
One of the rather useful expected conditions in Selenium's native library `ExpectedConditions` is `numberOfWindowsToBe(int)`. It's possible to call it using Selenide like this:

`Selenide.Wait().withTimeout(ofSeconds(60)).until(numberOfWindowsToBe(2))`

It works well but in light of [the recent feature](https://github.com/selenide/selenide/pull/1478), it's better to use it via new approach. It adds reporting, built-in waits, etc. 

Possible usage:

```java
webdriver().shouldHave(numberOfWindows(2));
webdriver().shouldHave(numberOfWindows(2), ofSeconds(60));
```

Possible implementation:
- `NumberOfWindows` class that implements `ObjectCondition<WebDriver>`
- add `numberOfWindows` method to `WebDriverConditions`

**Comment by bereg2k** [comment]
I'd like to provide this feature if it's considered useful.

**Comment by asolntsev** [comment]
Sure, we can do it. 

I am not sure it's so much useful because typically it's enough to just switch to the new window:
```java
$("button").click();  // click opens a new tab
switchTo(window(1)); // wait for the new tab and switches to it.
```

But probably there might be cases...

**Comment by bereg2k** [comment]
It's a pretty ordinary thing on my current project. It's useful in E2E scenarios with integrations. 

1. User presses a button on a page.
2. User sees a spinner/loading dialog. 
3. The browser automatically opens the 2nd tab to continue the scenario there (normally, it's some remote service). That's for positive cases. 

This becomes useful because we can't tell how much time does the system need to send a user to the 2nd tab:
```java
$("button").click(); // click opens a new tab
Selenide.Wait().withTimeout(ofSeconds(60)).until(numberOfWindowsToBe(2)); 
switchTo(window(1)); // it's only reasonable to switch when the the 2nd tab is actually opened 
```
After all, `numberOfWindowsToBe` condition is in Selenium library for a reason.

Considering that Selenide is actively used for integration/e2e testing, this seems useful for such cases.

**Comment by bereg2k** [comment]
@asolntsev I've looked into `com.codeborne.selenide.SelenideTargetLocator`...

Is it possible to have the same functionality with this:

`switchTo(window(1), ofSeconds(60));`

If so, then this feature request loses most of its value :)

**Comment by asolntsev** [comment]
> If so, then this feature request loses most of its value :)

Yes, it seems so. :)
Though, probably there might be cases when someone needs to check number of tabs without switching to it.

**Comment by bereg2k** [comment]
Ok, I'll implement it then, probably it's not entirely useless.

**Comment by asolntsev** [comment]
implemented in https://github.com/selenide/selenide/pull/1511
