### ISSUE TITLE
Usage of selenium java api internals preventing from upgrade to coming selenium-4.0.0-beta-4

### ISSUE THREAD

**Issue by tyge68** [selenide/selenide#1512]
## The problem
I was trying to update to up coming selenium java api https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.0.0-beta-4
Which failed due to some classes depending on "internal" packages which no longer exist in 4.0.0-beta-4
i.e import org.openqa.selenium.internal.WrapsElement;

## Details
Try to update the selenium java api dependency to the up coming release 4.0.0-beta-4

## Tell us about your environment
* **Selenide Version**: -
* **Chrome\Firefox\IE Version**: -
* **Browser Driver Version**: -
* **Selenium Version**: 4.0.0-beta-4
* **OS Version**: -

## Code To Reproduce Issue [ Good To Have ]
No code, but simply update the dependency and try to rebuild the project.
SelenideElement will fail due to import org.openqa.selenium.internal.WrapsElement

**Comment by rosolko** [comment]
@tyge68 You can track selenium upgrade status in a pull request https://github.com/selenide/selenide/pull/1407

**Comment by tyge68** [comment]
@rosolko  thanks, in that case I will close this one
