### ISSUE TITLE
 java.lang.ClassNotFoundException: com.codeborne.selenide.Selenide

### ISSUE THREAD

**Issue by mpregos** [selenide/selenide#1513]
## The problem
I get this error, trying to run a simple 'Hello world' with selenide + testNG + groovy + gradle + openjdk11

## Details
I create a new project with intellij, that is gradle and as Additional Library i select only Groovy option
I create a simple test. The problem is when i run the command : gradle clean test

## Tell us about your environment
* **Selenide Version**: 5.23.0
* **Chrome: 92  
* **Browser Driver Version**: -
* **Selenium Version**: -
* **OS Version**: mac big sure

## Code To Reproduce Issue [ Good To Have ]
my gradle.build
`plugins {
    id 'groovy'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.codehaus.groovy:groovy-all:3.0.8'

    testCompileOnly ('com.codeborne:selenide:5.23.0',
            'org.testng:testng:7.4.0')
}

test {
    useTestNG()
}

tasks.withType(Test) {
    testLogging {
        exceptionFormat "full"
        events "started", "skipped", "passed", "failed"
        showStandardStreams true
    }
}`

My Test class
`package qa.pollfish.tests

import com.codeborne.selenide.Configuration
import com.codeborne.selenide.SelectorMode
import org.openqa.selenium.By
import org.testng.annotations.BeforeSuite
import org.testng.annotations.Test

import static com.codeborne.selenide.Selenide.*
import static com.codeborne.selenide.Condition.*

class SelenideHelloWorld {

    @BeforeSuite
    void create(){
        Configuration.selectorMode = SelectorMode.Sizzle
    }

    @Test
    void test1(){
        open('https://www.google.com')
    }
}
`

Fun fact is that with no problem occurs if i run the test via intellij

**Comment by BorisOsipov** [comment]
Hi @mpregos 

```
testCompileOnly ('com.codeborne:selenide:5.23.0',
        'org.testng:testng:7.4.0')
```
=>
```
testImplementation ('com.codeborne:selenide:5.23.0',
        'org.testng:testng:7.4.0')
```

**Comment by mpregos** [comment]
Cool.Awesome!!!
Keep up the good work guys!!! Selenide rocks. I start a migration to selenide !!!!
