### ISSUE TITLE
One element is left when destroying all created todo elements

### ISSUE THREAD

**Issue by ramyrezzz** [selenide/selenide#1516]
## The problem
Accessing the ToDo MVC app on: https://todomvc.com/examples/angularjs/#/
After adding 3 toDos, and trying to destroy all, one element seems to be left out.

## Details
If necessary, describe the problem you have been experiencing in more detail.

`
      <dependency>
          <groupId>com.codeborne</groupId>
          <artifactId>selenide</artifactId>
          <version>5.23.0</version>
          <scope>test</scope>
      </dependency>
`
## Tell us about your environment
* **Selenide Version**:  5.23.0
* **Chrome Version**: Version 92.0.4515.131 (Official Build) (64-bit)
* **Browser Driver Version**:  --
* **Selenium Version**:  --
* **OS Version**: Win10 Enterprise

## Code To Reproduce Issue [ Good To Have ]
    @Test
    public void WhenDestroying_toDo_tasks_one_is_left(){
        open("https://todomvc.com/examples/angularjs/#/");
        $(".new-todo").setValue("a").pressEnter();
        $(".new-todo").setValue("b").pressEnter();
        $(".new-todo").setValue("c").pressEnter();

        for (SelenideElement task : $$("ul.todo-list>li")) {
            task.hover().find(".destroy").click();
        }

        $$("ul.todo-list>li").shouldBe(empty);
    }

## Exception:
`
Element not found {$$(3 elements)[2]}
Expected: exist
Caused by: StaleElementReferenceException: stale element reference: element is not attached to the page document
`

**Comment by asolntsev** [comment]
@ramyrezzz It's a classical example of flaky test. 
You should not use loops in tests. 
At the moment when you start looping over `$$("ul.todo-list>li")`, the last element might not be rendered yet. 

Instead of looping over UI elements, I recommend to use loop 2..0 which **doesn't depend on UI elements**:

```java
    for (int i = 2; i >= 0; i--) {
      $("ul.todo-list>li", i).hover().find(".destroy").click();
    }
```

or even more simple:

```java
    $("ul.todo-list>li", 2).hover().find(".destroy").click();
    $("ul.todo-list>li", 1).hover().find(".destroy").click();
    $("ul.todo-list>li", 0).hover().find(".destroy").click();
```

**Comment by ramyrezzz** [comment]
@asolntsev Thanks, will look into it.
