### ISSUE TITLE
Can't filter a file that contacins non-ASCII chars in its name when downloading it

### ISSUE THREAD

**Issue by plagov** [selenide/selenide#1518]
## The problem
When I download a file that contains a non-ASCII char in its name, then Selenide can't filter files before downloading it.

## Details
For example. The file name is `Sørensen.pdf`. I'm downloading it as follows: `$().download(using(PROXY).withFilter(withExtension("pdf")))`. This fails with FileNotFoundException.
If there are no chars like `ø`, then the same code filters out and downloads a file w/o a problem.

I tried also this filtering - `withNameMatching("S.*")`. Still doesn't work.

## Tell us about your environment
* **Selenide Version**: 5.23.2

**Comment by asolntsev** [comment]
@plagov I tried to download a file with `ø` character in name - it works. See https://github.com/selenide/selenide/pull/1519. 
**Can you specify how can we reproduce the problem?**

**Comment by plagov** [comment]
@asolntsev I investigated it deeper in our application. Here's why Selenide can't filter the file with `ø`. 
If the file name has only ASCII chars, then the downloaded file name looks as follows:
`./Download PDF/83d532e1-9807-44aa-a8c4-0a90f8d311b5/Hello.pdf`

If the file name contains non-ASCII, then Selenide downloads it too, but it appears as:
`./Download PDF/de3d07cf-5128-49e0-a5a0-fa539b843fd3/_`

So, the filename becomes just `_`. The file content is right, it is that target PDF I need to download, just with a strange name instead. It's weird, I can't understand why it happens. Not sure it's because of Selenide. Probably it's an issue in our application, but I'm not sure because when a user downloads this file manually on UI, then all appears good and as expected.

Do you have any thoughts if Selenide somehow may affect this filename change? If not, then it's an issue on our side and you can close the issue. Sorry for a false alarm, if so :)

**Comment by asolntsev** [comment]
@plagov Wait, but why the file name matters? How exactly are you downloading the file?
I hope you are not trying to find the file by name in the downloads folder?

The proper way to download the file:

```
File myFile = $().download(using(PROXY).withFilter(withExtension("pdf")));
```

Then it doesn't matter if the downloaded file name is `ø.pdf` or `_.pdf`.

**Comment by plagov** [comment]
@asolntsev yes, I try to download the file like this:
```java
$().download(using(PROXY).withFilter(withExtension("pdf")))
```
And the file doesn't have an extension. I.e., when I wrote that the filename is just `_`, then it's literally just this, without anything else, just the underscore character. And it is that target PDF file I want to download. When I open it with a PDF viewer - it's that file that I need. Just with a weird name.

So, I don't think it's a Selenide issue.

**Comment by BorisOsipov** [comment]
@plagov could you debug a bit for use. Turn breakpoint here https://github.com/selenide/selenide/blob/b8b91aea105a754e611111fab144ed3f5d436568/src/main/java/com/codeborne/selenide/impl/HttpHelper.java#L51 and step by step see what is happened

**Comment by plagov** [comment]
@BorisOsipov thanks for the suggestion!
I see in the debugger, that the `content-disposition` header comes with the `filename` property that holds the value encoded in base64:
```
content-disposition: attachment; filename="U8O4cmVuc2VuLnBkZg=="
```
Thus, Selenide can't parse it.

Should the Selenide support the decoding of the `filename` value if it's base64 encoded?

**Comment by asolntsev** [comment]
If I read correctly [this document](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Content-Disposition), filename should not be encoded with base64. 

But if some popular browsers do understand base64-encoded filename, then Selenide could also understand. We try to emulate real browsers as much as possible.

**Comment by asolntsev** [comment]
@plagov I tried with latest Firefox and Chrome: they both download file with name `U8O4cmVuc2VuLnBkZg==`. 
They don't decoded the base64-encoded filename. 

It seems to be a bug in your AUT.

**Comment by plagov** [comment]
@asolntsev yes, I think it's indeed an issue on my side.
Thanks a lot for the time spent on this! We can close this ticket.
