### ISSUE TITLE
Could not download artifact 'org.bouncycastle:bcprov-jdk15on:1.51:bcprov-jdk15on.jar'

### ISSUE THREAD

**Issue by achung2018** [selenide/selenide#1521]
## The problem
Unable to upgrade selenide version 5.4.1 to 5.23.0 due to dependency on bouncycastle 1.51

## Details
Looks like there's a new dependecy download required for Selenide version 5.23.0, that is 'org.bouncycastle:bcprov-jdk15on:1.51:bcprov-jdk15on.jar'

I tried to upgrade selenide version 5.4.1 to 5.23.0 in my UI automation project which used Java 8, gradle 4.6. When it tried to run it, it tried to download 'org.bouncycastle:bcprov-jdk15on:1.51:bcprov-jdk15on.jar' and failed with error that it could not download this artifact. If I reverted back to Selenide 5.4.1 and it worked fine.

## Tell us about your environment
* **Selenide Version**:  5.23.0
* **Chrome\Firefox\IE Version**:  Firefox 91.0
* **Browser Driver Version**: 0.29.1
* **Selenium Version**: 
* **OS Version**:  Windows 7 Enterprise SP1 x64

**Comment by asolntsev** [comment]
@achung2018 No, Selenide doesn't have dependencies like `org.bouncycastle.*`.

Please run `./gradlew dependencies` and read the full dependency tree. You will see where `org.bouncycastle.*` comes from.

For more information on debugging dependencies, see https://selenide.org/2020/11/17/why-proxy-does-not-work-in-selenoid/
