### ISSUE TITLE
Hover not working after repeated open() or refresh()

### ISSUE THREAD

**Issue by flange-ipb** [selenide/selenide#1530]
## The problem
After calling open(url) a second time or refreshing the page hovering is not working.

## Tell us about your environment
* **Selenide Version**: 5.23.2
* **Chrome\Firefox\IE Version**: Firefox=78.13.0esr, I didn't test with Chrome/IE
* **Browser Driver Version**: geckodriver=0.26.0
* **Selenium Version**: 3.141.59
* **OS Version**: Debian 10 amd64

## Code To Reproduce Issue [ Good To Have ]
```Java
import org.junit.Test; // JUnit 4.13.2
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;

public class HoverTest {
	@Test
	public void test() {
		open("https://selenide.org/");
		$(byText("Quick start")).hover(); // .shouldBe(hovered) does not exist ;)
		sleep(1000);
		$(byText("Docs")).hover();
		sleep(1000);
		$(byText("Quick start")).hover();
		sleep(1000);

		//open("https://github.com"); // Browsing somewhere else will not solve the issue.

		open("https://selenide.org/");
		$(byText("Quick start")).hover();
		sleep(2000); // You will see that there was no hovering done.
		
		refresh(); // Also not working.
		$(byText("Quick start")).hover();
		sleep(2000);
	}
}
```

**Comment by asolntsev** [comment]
@flange-ipb How do you see that hover doesn't work?
I have executed your code, and it seems to me the hover does work (even after refresh). 

Probably the problem is that you don't wait after calling `open` and `refresh`, so you are calling `hover` method on an element which was found before opening/refreshing?

**Comment by flange-ipb** [comment]
Hi Andrei,
nope, it didn't resolve by introducing an explicit `sleep` immediately after the second `open` or after the `refresh`. I'm setting up Selenoid right now to test with different browser/versions. Let's see ...

**Comment by flange-ipb** [comment]
Alright, I can reproduce the bug with the selenoid/firefox:78.0 image. Fortunately, it is not present in the latest firefox:91.0 and chrome:92.0. Thus, problem solved. Kudos for developing such a fantastic piece of software!

**Comment by asolntsev** [comment]
Thank you for the responsible attitude. If only all the users behaved this way... :)
