### ISSUE TITLE
Duplicate method in the Condition class

### ISSUE THREAD

**Issue by evpl** [selenide/selenide#1541]
Class `Condition` contains two methods without javadoc that just return value of the `absentElementMatchesCondition` field:

```java
public boolean applyNull() {
    return absentElementMatchesCondition;
}
```

```java
public boolean missingElementSatisfiesCondition() {
    return absentElementMatchesCondition;
}
```

Could you explain their purpose? It seems that one method (`applyNull`) is enough.

**Comment by asolntsev** [comment]
@evpl Goot catch!
1. `applyNull` is an old method with a bad name. I think we can remove it. 
2. `missingElementSatisfiesCondition` is a newer method with a better name. We should use it everywhere.

**Comment by evpl** [comment]
@asolntsev ok, I’ll fix it. But I’m sure that`missingElementSatisfiesCondition` method name is too long. Can we use the name like `missingElementIsTrue` or `missingElementIsOk` with javadoc?

**Comment by asolntsev** [comment]
Yes, it's long. :(
But I couldn't come up with a shorter name that would be correct. 

I think it's not a problem because this method has very few usages.

**Comment by evpl** [comment]
@asolntsev pls review #1544

And what are you think about `applyNull` method in the `CollectionCondition` class? Should we rename it too?

**Comment by asolntsev** [comment]
@evpl yes, we should also rename it. In case of collections, "null" is even more frustrating name.

**Comment by evpl** [comment]
@asolntsev ok, I added it in the same PR
