### ISSUE TITLE
Add `SelenideElement.ancestor()` method

### ISSUE THREAD

**Issue by bereg2k** [selenide/selenide#1556]
Add `SelenideElement.ancestor()` method as a synonym for the existing `SelenideElement.closest()`. Same behavior.

The reason: this naming is closer to the actual XPath syntax (`ancestor::*`), and `closest()` is not that obvious for newbie adopters of Selenide.

**Comment by asolntsev** [comment]
@bereg2k Yes, it seems we could add such a synonym for `closest`. 
A long time ago, I used name `closest` because such a method existed in JQuery library. :)
