### ISSUE TITLE
Chrome hangs in Docker in Selenide 5.14.0 - 5.23.1

### ISSUE THREAD

**Issue by Jaaap** [selenide/selenide#1559]
## The problem
Since Selenide 5.14.0 we regularly have hanging **Docker** containers because of hanging Chrome processes.

## Details
Lower versions than 5.14.0 work ok, higher versions (5.15.0 and 5.23.1 tested) experience random hangs.
We **suspect** it is the Chrome process that hangs but it is hard to tell because of Docker.
We tried experimenting with `chromeOptions.setExperimentalOption("excludeSwitches", Arrays.asList("disable-dev-shm-usage"))` but that did not fix it.

## Tell us about your environment
* **Selenide Version**: 5.14.0 - 5.23.1
* **Chrome Version**: Chrome 92.0.4515.159
* **Browser Driver Version**: ???
* **Selenium Version**: 3.141.59
* **OS Version**: CentOS 8.3.20

## Code To Reproduce Issue
This is a big set of Java unittests.

**Comment by Jaaap** [comment]
contents of selenium-compose.yml:

```
version: "2.3"

services:
  selenium-chrome:
    # Note: this version must be compatible with selenium.version in pom.xml
    # 3.141.59-20210830 contains chrome 92.0.4515.159
    image: internal-server/selenium/standalone-chrome:3.141.59-20210830
    ports:
      - "4444"
    environment:
      START_XVFB: "false"
    healthcheck:
      test: ["CMD", "/xxx/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 5s
      timeout: 30s
      retries: 5
    shm_size: 2g
    privileged: false
    network_mode: bridge
    labels:
      company.bamboo.planName: ${bamboo_planName:-AppName}
```

**Comment by asolntsev** [comment]
@Jaaap Selenide adds option `--disable-dev-shm-usage` by default. Did you try to remove this option? Does it help?

**Comment by Jaaap** [comment]
Yes we tried to disable that with
```
chromeOptions.setExperimentalOption("excludeSwitches", Arrays.asList("disable-dev-shm-usage"))
```
but that did not fix it, although it did show up in selenium-chrome.log:
```
selenium-chrome_1  | 14:32:05.297 INFO [ActiveSessionFactory.apply] - Capabilities are: {
selenium-chrome_1  |   "acceptInsecureCerts": true,
selenium-chrome_1  |   "acceptSslCerts": true,
selenium-chrome_1  |   "browserName": "chrome",
selenium-chrome_1  |   "goog:chromeOptions": {
selenium-chrome_1  |     "args": [
selenium-chrome_1  |       "--headless",
selenium-chrome_1  |       "--disable-gpu",
selenium-chrome_1  |       "--proxy-bypass-list=\u003c-loopback>",
selenium-chrome_1  |       "--disable-dev-shm-usage",
selenium-chrome_1  |       "--no-sandbox",
selenium-chrome_1  |       "--disable-background-networking",
selenium-chrome_1  |       "--enable-features=NetworkService,NetworkServiceInProcess",
selenium-chrome_1  |       "--disable-background-timer-throttling",
selenium-chrome_1  |       "--disable-backgrounding-occluded-windows",
selenium-chrome_1  |       "--disable-breakpad",
selenium-chrome_1  |       "--disable-client-side-phishing-detection",
selenium-chrome_1  |       "--disable-component-extensions-with-background-pages",
selenium-chrome_1  |       "--disable-default-apps",
selenium-chrome_1  |       "--disable-features=TranslateUI",
selenium-chrome_1  |       "--disable-hang-monitor",
selenium-chrome_1  |       "--disable-ipc-flooding-protection",
selenium-chrome_1  |       "--disable-popup-blocking",
selenium-chrome_1  |       "--disable-prompt-on-repost",
selenium-chrome_1  |       "--disable-renderer-backgrounding",
selenium-chrome_1  |       "--disable-sync",
selenium-chrome_1  |       "--force-color-profile=srgb",
selenium-chrome_1  |       "--metrics-recording-only",
selenium-chrome_1  |       "--no-first-run",
selenium-chrome_1  |       "--password-store=basic",
selenium-chrome_1  |       "--use-mock-keychain",
selenium-chrome_1  |       "--hide-scrollbars",
selenium-chrome_1  |       "--mute-audio"
selenium-chrome_1  |     ],
selenium-chrome_1  |     "extensions": [
selenium-chrome_1  |     ],
selenium-chrome_1  |     "excludeSwitches": [
selenium-chrome_1  |       "enable-automation",
selenium-chrome_1  |       "load-extension",
selenium-chrome_1  |       "disable-dev-shm-usage"
selenium-chrome_1  |     ],
selenium-chrome_1  |     "prefs": {
selenium-chrome_1  |       "credentials_enable_service": false,
selenium-chrome_1  |       "plugins.always_open_pdf_externally": true,
selenium-chrome_1  |       "profile.default_content_setting_values.automatic_downloads": 1
selenium-chrome_1  |     }
selenium-chrome_1  |   },
selenium-chrome_1  |   "handlesAlerts": true,
selenium-chrome_1  |   "javascriptEnabled": true,
selenium-chrome_1  |   "pageLoadStrategy": "normal",
selenium-chrome_1  |   "takesScreenshot": true
selenium-chrome_1  | }

```

**Comment by asolntsev** [comment]
@Jaaap No-no, Selenide already adds line `chromeOptions.setExperimentalOption("excludeSwitches", Arrays.asList("disable-dev-shm-usage"))`. Did you try to open webdriver **without this line**?

**Comment by Jaaap** [comment]
Hmmm... confusing.
I tried to add it to `excludeSwitches` so the disable line would be removed (double negative ;)

**Comment by svschouw-bb** [comment]
> @Jaaap No-no, Selenide already adds line `chromeOptions.setExperimentalOption("excludeSwitches", Arrays.asList("disable-dev-shm-usage"))`. Did you try to open webdriver **without this line**?

Don't you mean Selenide already adds `chromeOptions.addArguments("--disable-dev-shm-usage");` ?

We tried using "excludeSwitches" to negate this, but this didn't seem to do anything.

**Comment by asolntsev** [comment]
Yes, Selenide already adds
`chromeOptions.addArguments("--disable-dev-shm-usage");`

You can look into the source:
https://github.com/selenide/selenide/blob/4d86e7e839d8d11d2d11a8479f2f90f03622e272/src/main/java/com/codeborne/selenide/webdriver/ChromeDriverFactory.java#L90

чт, 30 сент. 2021 г., 13:11 svschouw-bb ***@***.***>:

**Comment by asolntsev** [comment]
@svschouw-bb Please try to add these lines BEFORE opening a browser:

```java
Configuration.browser=com.your.company.YourChromeFactory.class;

class YourChromeFactory extends com.codeborne.selenide.webdriver.ChromeDriverFactory {
  protected List<String> createChromeArguments(Config config, Browser browser) {
    List<String> arguments = super.createChromeArguments(config, browser);
    arguments.remove("--disable-dev-shm-usage");
    return arguments;
  }  
}
```

**Comment by asolntsev** [comment]
@Jaaap @svschouw-bb Did you have a chance to try the hack mentioned above? ^^^

**Comment by Jaaap** [comment]
Yes it is running repeated unittests as we speak.
No hangs yet so it's looking promising.

**Comment by asolntsev** [comment]
@Jaaap Thank you for the experiment! 
Are you sure the is issue is still actual in latest Chrome and Chromedriver?

**Comment by Jaaap** [comment]
We've observed the problem in a docker container with
Chrome: 92.0.4515.159
ChromeDriver: 92.0.4515.107
Does that answer your question?

**Comment by asolntsev** [comment]
@Jaaap Could you try with the latest Chrome 94?

**Comment by Jaaap** [comment]
We could, but it requires a lot of time (and server resources) to run.
I'd be afraid you're gonna ask this for every major new Chrome version ;-)
Do we have any reason to believe it is fixed on the Chrome side?

**Comment by asolntsev** [comment]
No :)

But wasn't Docker needed exactly to make it easy using any Chrome version? If you say it "takes a lot of time" - something went wrong, I would say. :(

Never mind, it's just my grunt. ;)

We need to decide how to solve this issue. Is it ok for you to have `YourChromeFactory` in your tests? Can we close the issue then?

**Comment by Jaaap** [comment]
Yes Docker make some parts easier, and makes other parts much, much harder ;-)
We are happy with the `YourChromeFactory`, it still hasn't hung on our server.
Thanks for your help.
