### ISSUE TITLE
Make is easy to configure Selenide Proxy before it's started

### ISSUE THREAD

**Issue by IlyaHarlamov** [selenide/selenide#1561]
## The problem
Hi, I am facing one issue with Selenide proxy, I am trying to disable MITM.
Proxy is not configurable, as it is created and started on time to open a browser using `open()`. MITM may be only disabled before Proxy is started.

## Details
I have `Configuration.proxyEnabled = true;`
Here's my code after opening a browser with open():
```java
proxy = WebDriverRunner.getSelenideProxy().getProxy();
proxy.setMitmDisabled(true);
```
It returns a IllegalStateException with message "Cannot disable MITM after the proxy has been started".

## Expected
* Would be nice to have Proxy easily configurable

## Environment
* **Selenide Version**: 5.24.2

**Comment by asolntsev** [comment]
@IlyaHarlamov Do you use `WebDriverFactory` or `WebDriverProvider` in your project?

**Comment by IlyaHarlamov** [comment]
> @IlyaHarlamov Do you use `WebDriverFactory` or `WebDriverProvider` in your project?

As discussed in private, none of these

**Comment by asolntsev** [comment]
Let's discuss what would be the best API to configure the proxy.
I can suggest few options.

### 1. New configuration property
```
Configuration.proxyCustomizerClass = "com.my.FooProxyCustomizer";
```

### 2. New static configuration
Similar to `Configuration`:
```java
  ProxyConfiguration.mitmEnabled = false;
  ProxyConfiguration.host = “localhost”;
  ProxyConfiguration.port = 9999;
```

### 3. WebDriverFactory
Add method like `createProxy` to method `WebDriverFactory` and/or `WebDriverProvider`. 
Default implementation will just return `new BrowserUpProxyServer()`.

* Pros: it's powerful, no static configs
* Cons: not everybody uses `WebDriverFactory` or `WebDriverProvider`. Many users just call `open(url)`.

### 4. Lambda
When opening a new webdriver, pass a lambda to customize the proxy:
```
open(“https://google.com”, (proxy) -> {
  proxy.setMitmEnabled(false);
  proxy.setTrustAllServers(true);
});
```

* Pros: it's powerful, no static configs
* Cons: it's not clear if we should shutdown the previous proxy in `open` method (was it started with the same or different lambda?)


@BorisOsipov @rosolko @dbudim @dstekanov

**Comment by BorisOsipov** [comment]
@asolntsev 

5. Plugin via service loader.

I prefer 1 or 5

**Comment by BorisOsipov** [comment]
maybe...

**Comment by IlyaHarlamov** [comment]
@asolntsev, it is not only about MITM, there might be more configurations which are not possible to change right now, I know at least one more, the trust servers

**Comment by asolntsev** [comment]
@IlyaHarlamov Selenide already does `proxy.setTrustAllServers(true);` by default.
