### ISSUE TITLE
How to use selenide page objects with different drivers in same test?

### ISSUE THREAD

**Issue by ddeputatov-ta** [selenide/selenide#1562]
I have to test integration between 2 different apps, is there an easy way to do this? 

    @Test
    public void search() {
        SelenideDriver googleDriver = new SelenideDriver(new SelenideConfig());
        SelenideDriver bingDriver = new SelenideDriver(new SelenideConfig());

        var googlePage = googleDriver.open("https://google.com", Google.class);
        var bingPage = bingDriver.open("https://bing.com", Bing.class);

        googlePage.form.shouldBe(visible); // No webdriver is bound to current thread
        bingPage.form.shouldBe(visible);
    }

    public static class Google {
        public SelenideElement form = $("form[action='/search']");
    }
    public static class Bing {
        public SelenideElement form = $("input#sb_form_q");
    }

**Comment by s4ik4t** [comment]
Kindly use the [Gitter chat](https://gitter.im/codeborne/selenide) for questions/help.

**Comment by asolntsev** [comment]
@ddeputatov-ta You are almost doing it right :)
You create two drivers, but inside of `Google` and `Bing` you are still using static method `$` which doesn't use any of your drivers.

There are many ways how to use two drivers. For example, with annotations `@FindBy`:

```java
public static class Google {
    @FindBy(css = "form[action='/search']")
    public SelenideElement form;
}
public static class Bing {
    @FindBy(css = "input#sb_form_q")
    public SelenideElement form;
}
```
