### ISSUE TITLE
Screenplay support

### ISSUE THREAD

**Issue by jbadeau** [selenide/selenide#1563]
Hello,

I am looking for the correct way to integrate Selenide with the [Screenplay](https://serenity-js.org/handbook/design/screenplay-pattern.htm) pattern.

The issue I am facing is that an actor must be explicitly give the ability to **browseTheWeb** and should never be able to just open a browser with the static Selenide methods.

What is the correct way to manually create and manage Selenide instances.

My code will be based on the following https://github.com/mkutz/shakespeare/tree/main/modules/selenium/src/main/java/org/shakespeareframework/selenium

But with selenide instead selenium

**Comment by asolntsev** [comment]
@jbadeau To use Selenide without static methods, you need to create instance of `SelenideDriver`. It has the same non-static methods as class `Selenide` has (`open`, `$`, `$$` etc). See https://selenide.org/2018/10/10/selenide-5.0.0/

P.S. Sorry, your link opens "Page not found (Error 404)", but those articles of "Screenplay pattern" that I managed to find rather make me skeptical. The idea seems to me overrated. I believe you don't need any special framework to just write readable code.

**Comment by jbadeau** [comment]
We don't just use screenplay for browser testing. We use it for all types of testing. Web, API, DB, Spark, etc so we won't change just for web. Thanx, for the response. I was pretty sure SelenideDriver was the way but never hurts to check 😁

**Comment by asolntsev** [comment]
Sorry for my impoliteness, but it seems even more strange for me. The name "screen" like hints that the pattern is about _screen_, or the things the end-user can see on his monitor. It's not about DB, Api and Spark. 

But well, maybe I am just stupid, nevermind. :)

**Comment by jbadeau** [comment]
A better name for the pattern would prob be Playwrite but hey, it is what it is :p

The Screenplay Pattern uses the system metaphor of a stage performance where each test scenario is like a little screenplay describing how the actors should go about performing their activities while interacting with the system under test.

The "screen" in "screenplay" has nothing to do with the computer screen. On the contrary, the Screenplay Pattern is a general method of modelling acceptance tests interacting with any external interface of your system. In fact, the Serenity/JS implementation of the Screenplay Pattern can help you break free from UI-only-based testing!

**Comment by jbadeau** [comment]
Anyway, thanx for the cool lib.
