### ISSUE TITLE
Set the language option Edge webdriver

### ISSUE THREAD

**Issue by adrien1212** [selenide/selenide#1574]
## The problem
I want to change the language option of the Edge browser.

## Details
On chrome driver you can change the browser language thanks to the following code
### With Selenium (work fine)
```
System.setProperty("webdriver.edge.driver","path_to\\chromedriver.exe");

ChromeOptions options = new ChromeOptions();
options.addArguments("--lang=en");
ChromeDriver driver = new ChromeDriver(options);
driver.get("http://google.com");
```
### With Selenide (work fine)
```java
System.setProperty("selenide.browser", "chrome");

ChromeOptions options = new ChromeOptions();
options.addArguments("--lang=en");
Configuration.browserCapabilities.setCapability(ChromeOptions.CAPABILITY, options);
Selenide.open("http://google.com");
```
But it's impossible to reproduce on Edge, see the section _Code To Reproduce Issue, With Selenide (doesn't work)_

## Tell us about your environment
* **Selenide Version**:  5.23.3
* **MSEdge**: 93.0.961.52
* **MSEdge Browser Driver Version**: 93.0.961.52
* **Selenium Version**: 3.341.59
* **OS Version**: Windows10 20H2

### With Selenium (work fine)
```
System.setProperty("webdriver.edge.driver","path_to\\msedgedriver.exe");
		
EdgeOptions options = new EdgeOptions();
options.addArguments("--lang=en");
EdgeDriver driver = new EdgeDriver(options);
driver.get("http://google.com");
```
### With Selenide (doesn't work : The web brower stay in French language)
```
System.setProperty("selenide.browser", "edge");

EdgeOptions options = new EdgeOptions();
options.addArguments("--lang=en");
Configuration.browserCapabilities.setCapability(EdgeOptions.CAPABILITY, options);
Selenide.open("http://google.com");
```

Thank you

**Comment by asolntsev** [comment]
@adrien1212 Are you sure you use the proper version of selenium-*java (I mean, version `3.341.59`)?

On my machine your code doesn't even compile:
```java
    EdgeOptions options = new EdgeOptions();
    options.addArguments("--lang=en");  // method addArguments not found
    Configuration.browserCapabilities.setCapability(EdgeOptions.CAPABILITY, options);  // constant CAPABILITY not found
```

**Comment by adrien1212** [comment]
There are two versions of `EdgeOptions`.
The first one is developed by Selenium : org.openqa.selenium.edge.EdgeOptions

But microsoft has developed this own version : 
- https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/?tabs=java#using-selenium-3
- msedge-selenium-tools-java
And this `com.microsoft.edge.seleniumtools.EdgeOptions `offer the method `addArguments() `
