### ISSUE TITLE
Cannot use Safari with Selenium Proxy

### ISSUE THREAD

**Issue by fkrivsky** [selenide/selenide#1575]
## The problem
We are using Selenium proxy with our setup. It is working fine with Chrome/Edge/Firefox/Opera, however not with Safari. 
When we run the same code on Mac with browser Safari it fails with `org.openqa.selenium.SessionNotCreatedException: Capability 'proxy' could not be honored.`

Seems similar to #1236.

## Details
More details on the error:
```
org.openqa.selenium.SessionNotCreatedException: Capability 'proxy' could not be honored.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '<HOSTNAME_REDACTED>', ip: '****', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.7', java.version: '11.0.9'
Driver info: driver.version: SelenideDriver
selenide.url: https://www.google.com
selenide.baseUrl: http://localhost:8080
```

## Tell us about your environment
* **Selenide Version**:  5.24.3
* **Chrome\Firefox\IE Version**:  Safari 14
* **Browser Driver Version**: Default with Selenide 5.24.3
* **Selenium Version**: 3.141.59
* **OS Version**: macOS 10.15.7

## Code To Reproduce Issue [ Good To Have ]

```
package selenide;

import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;

@lombok.extern.log4j.Log4j2
public class ProxyTest {

	@org.testng.annotations.Test
	public void proxyTest() throws InterruptedException {
		Configuration.browser = "safari";
		Configuration.proxyHost = "localhost";
		Configuration.proxyPort = 10006;

		String proxyStr = Configuration.proxyHost + ":" + Configuration.proxyPort;
		log.info(proxyStr);

		org.openqa.selenium.Proxy proxy = new org.openqa.selenium.Proxy();
		proxy.setProxyType(org.openqa.selenium.Proxy.ProxyType.MANUAL);
		proxy.setHttpProxy(proxyStr);
		proxy.setSslProxy(proxyStr);

		WebDriverRunner.setProxy(proxy);

		com.codeborne.selenide.Selenide.open("https://www.google.com");
		Thread.sleep(10000);
	}
}
```

**Comment by asolntsev** [comment]
@fkrivsky As far as I know, it's a limitation of Safari driver: it cannot use proxy.
Anyway, it's not a bug in Selenide.
