### ISSUE TITLE
Upload file in other than [@type=file] element

### ISSUE THREAD

**Issue by xakrurychle** [selenide/selenide#1582]
## The problem

Hi, I am trying to upload a file into element which is different from standard  input type file element.
actual element a class="browse" ref="fileBrowse" href="#">select file...</a

May I ask for a piece of advice on how to overcome this trouble and upload the file successfully?

thank you

______
I was trying to use

1)

File file = $("#pathToTheElement").scrollIntoView(true).uploadFile(new File("path from the system folder"));

2)

File file = $("#pathToTheElement").scrollIntoView(true).uploadFromClasspath("file.txt"); 

where file.txt is in src/test/resources/folder/folder2/file.txt

I have also tried ("src/test/resources/folder/folder2/file.txt") aka the full path within the project structure.

ad1)  I'd get element is not of input type - guess that's correct
ad2)  I'd get file not found in classpath

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**:  5.2.2
* **Chrome\Firefox\IE Version**: 93.0.4577.82
* **Browser Driver Version**:  93.0.4577.63
* **Selenium Version**: 
* **OS Version**: mac 10.15.7

## Code To Reproduce Issue [ Good To Have ]
//Class located in src/main. The method is then called using a constructor in src/test.

@Step("testNo#1")
public Xyz xyz() {

    //File file = $("#pathToTheElement").scrollIntoView(true).uploadFile(new File("address to file"));
    //File file = $("#pathToTheElement").scrollIntoView(true).uploadFromClasspath("file.txt");

return this;
}

**Comment by asolntsev** [comment]
@xaknem Is far as I know, browser (or webdriver?) can only upload files using `<input type="file">`. 
If your `#pathToTheElement` is not `input`, you cannot upload the file. 
Try to look into HTML dom tree and find the needed `input`. 

P.S. When you find the input, use method `File file = $("#pathToInput").scrollIntoView(true).uploadFromClasspath("/folder/folder2/file.txt");`. [RTFT](https://github.com/selenide/selenide/blob/master/src/test/java/integration/FileUploadTest.java).
