### ISSUE TITLE
5.25.0-selenium-4.0.0-rc-1 creates WebDriver with bad Capabilites

### ISSUE THREAD

**Issue by y-lazakovich** [selenide/selenide#1591]
## The problem
`5.25.0-selenium-4.0.0-rc-1` is able to create any webdriver with bad `DesiredCapabilites`
- Able create `chromeDriver` with capabilities for Chrome+Firefox
- Able create `firefoxDriver` with capabilities for Chrome+Firefox

it doesn't reproduces with 5.25.0 it returns issue about conflict `Firefox` vs `Chrome` 
## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 5.25.0-selenium-4.0.0-rc-1
* **Chrome\Firefox Version**: 91\92
* **Browser Driver Version**: 91\92
* **Selenium Version**: v. 4.0.0-rc-1
* **OS Version**: Linux

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

> 

        ChromeOptions chromeOptions = new ChromeOptions();
        Map<String, Object> prefs = new HashMap<>();
        prefs.put("plugins.always_open_pdf_externally", false);
        prefs.put("credentials_enable_service", false);
        prefs.put("profile.password_manager_enabled", false);
        chromeOptions.setExperimentalOption("prefs", prefs);
        chromeOptions.addArguments("--window-size=1920,1080");
        capabilities.setCapability(CAPABILITY, chromeOptions);
        
        FirefoxProfile firefoxProfile = new FirefoxProfile();
        firefoxProfile.setPreference("browser.download.folderList", 2);
        firefoxProfile.setPreference("intl.accept_languages", "en,en-US");
        firefoxProfile.setPreference("browser.download.useDownloadDir", true);
        firefoxProfile.setPreference("browser.download.viewableInternally.enabledTypes", "");
        firefoxProfile.setPreference("browser.helperApps.neverAsk.saveToDisk", "application/pdf;text/plain;application/text;text/xml;application/xml");
        firefoxProfile.setPreference("pdfjs.disabled", true);  // disable the built-in PDF viewer
        FirefoxOptions firefoxOptions = new FirefoxOptions();
        firefoxOptions.setProfile(firefoxProfile);
        capabilities.setCapability(FIREFOX_OPTIONS, firefoxOptions);
        
        timeout = MILLISECONDS.convert(10, SECONDS);
        browser = "chrome";
        downloadsFolder = "build/downloads";
        browserCapabilities = capabilities;
        driverManagerEnabled = true;
        headless = true;

**Comment by BorisOsipov** [comment]
it is because in SE4 branch we don't use `MergeableCapabilities` https://github.com/selenide/selenide/blob/b8b91aea105a754e611111fab144ed3f5d436568/src/main/java/com/codeborne/selenide/webdriver/MergeableCapabilities.java#L19

**Comment by asolntsev** [comment]
@y-lazakovich The problem was fixed in Selenide 6.1.1
Now we throw "Conflicting browser name: 'chrome' vs. 'firefox'" again. 

See https://github.com/selenide/selenide/pull/1642/commits/8bdadd398ddf0dae3bddb49169b5031b746d77b1

**Comment by y-lazakovich** [comment]
@asolntsev Thanks a lot!
Hope in the future will be able to be a part of your open-source contributing development team

**Comment by asolntsev** [comment]
@y-lazakovich Sure you can! Here is a entertaining introduction: https://habr.com/ru/company/jugru/blog/537166/
