### ISSUE TITLE
Executing instances of Should commands with given Condition

### ISSUE THREAD

**Issue by mszajowskiwr** [selenide/selenide#1606]
## The problem

I'm looking for a solution that will allow me to register different should-commands, with different conditions to be executed in later stage. The simplest way to keep them, would be to hold them as Runnables, e.g.:
```java
List<Runnable> registeredCalls = List.of(
    () -> element.should(exist), 
    () -> anotherElement.shouldNotBe(visible),
    ...);
```

However, I would prefer to keep things more granular and utilise the `Condition` API, something like:
```java
registerElement(element).toExecute(new Should()).withConditions(exists);
registerElement(anotherElement).toExecute(new ShouldNotBe()).withConditions(visible);
```

Is there a neat way to do execute the should-command having the access only to `SelenideElement` instance, the should-`Command` instance and the `Condition` it must fulfil? 

## Details

What I have at my disposal, is the instance of `SelenideElement`, the instance of `Command<SelenideElement>` and the `Condition`. After looking into the architecture, I see that the `Condition`s, for `Should` sake, are generated from `Command::execute` args via `com.codeborne.selenide.commands.Util.argsToConditions` - what I basically need is a way, to have the opposite function - something that will allow me to use `Condition` to be fed into the `Command::execute` method (it takes `Object[]` as args and then it converts it to `Condition` - i need to opposite).

OR, I was thinking about extending `Should` and overriding the `execute()` for it, thus it would allow me to skip the `Condition...`->`Object[]`->`Condition...` conversion, but I'm struggling to understand the link between `SelenideElement proxy` and `WebElementSource locator` parameters of `Command::execute`. Also, the `prefix` in `Should` is private, thus I'd need to repeat the same logic in my child classes...

Is there something I'm missing in this picture?

**Comment by asolntsev** [comment]
@mszajowskiwr Hi. I don't understand what are you trying to achieve. At a first glance, it seems to be over-complicated.

Instead of 
```
registerElement(element).toExecute(new Should()).withConditions(exists);
registerElement(anotherElement).toExecute(new ShouldNotBe()).withConditions(visible);
```

Can't you just write
```
element(should(exist);
anotherElement.shouldNotBe(visible);
```

?

**Comment by mszajowskiwr** [comment]
I'm trying to prepare a list of callbacks to be executed later. The `anotherElement.shouldNotBe(visible)` will immediately perform the assertion, and I want to prepare this list earlier - by then I don't even have the webdriver available yet.

**Comment by asolntsev** [comment]
@mszajowskiwr No, there is no way to get `WebElementSource` from `SelenideElement`.
`SelenideElement` is a higher-level abstraction, it should not know about implementation details. And `WebElementSource` is an implementation details that can change from release to release. 

To be honest, I still don't understand why you call it "readable and easy to use". Can something be more easy than the standard Java API?
