### ISSUE TITLE
How to set attribute value?

### ISSUE THREAD

**Issue by PawelWas1985** [selenide/selenide#1608]
hello All. Can anyone from you help me with my question: 
i have WebElement: `<div class="noUi-origin noUi-stacking" style="left: 100%;"></div>` 
it is possible to change value of attribute: style ? i'd like to change it to "left: 0%;" i will be very grateful for help.

**Comment by asolntsev** [comment]
Webdriver API doesn't allow that.
But you can execute JavaScript code to change any attributes, text and values on the page. 

Something like `Selenide.executeJavascript("document.getElementById("blah").style = 'foo'");`.
