### ISSUE TITLE
Maven doesn't see of my TestNG tests after upgrading to Selenide 6.0.1

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1623]
## The problem
Given a project with Maven, TestNG and Selenide. 
After upgrading to Selenide 6.0.1, Maven surefire plugin doesn't find any tests anymore. 

## Tell us about your environment
* **Selenide Version**: 6.0.1

**Comment by nadiyazynyuk** [comment]
Which TestNG version can be used with Selenide 6.0.3?
7.0.0 works ok, later versions lead to "No tests were found"

**Comment by asolntsev** [comment]
@nadiyazynyuk any version of TestNG should be supported. Selenide itself is built with `org.testng:testng:7.4.0`. 

NB! Are you using dependency `com.codeborne:selenide-testng:6.0.3`, not `com.codeborne:selenide:6.0.3`?

**Comment by nadiyazynyuk** [comment]
Hi, the issue is solved, alongside upgrading TestNG version the io.qameta.allure:allure-testng version should be also upraded.
