### ISSUE TITLE
Bad browser language in version 6+

### ISSUE THREAD

**Issue by dironel** [selenide/selenide#1626]
## The problem
i'm setting broser language to us-En in chrome Options
 ChromeOptions chromeOptions = new ChromeOptions();
Configuration.browserCapabilities=chromeOptions;
WebDriverRunner.getAndCheckWebDriver();

this worked in selenide version 5.25.0
after upgrade to selenide version 6+ (tried 6.0.1,6.0.2,6.03) it's not working anyome.

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@dironel Can you try with Selenide 6.1.1?

P.S. Why are you using `getAndCheckWebDriver()` instead of good old `open(url)`?
