### ISSUE TITLE
Chaining selectors for id and class does not work as expected

### ISSUE THREAD

**Issue by JoakimBruce** [selenide/selenide#1627]
## The problem
Chaining a selector for an id (e.g. `$("#id")`) and CSS classes (e.g. `$(".parent-class .child-class")`) yields a different result than simply combining them (e.g. `$("#id .parent-class .child-class")`) in some cases. Chaining the selectors in a corresponding manner in the browser development console yields the same result, which seems more correct.

## Details
We first encountered this problem when chaining an element selected with an xpath expression with a selector for several consecutive CSS classes, but we encountered the same problem when selecting with an id first. We have primarily tested it in Chorme using Selenide 5.0.1, but we encountered the same problem in Firefox. I have since reproduced a simplified version in Selenide 6.0.3 (see code below).

In the code below, statements 1-6 pass as expected, while the last one fails. Statement 4-7 should (as far as I can see) check the same element (the ChildNode) but statement 7 finds the ParentNode instead, with the following error:
```
Element should not have text "ParentNode" {#parent/.tree-node .content}
Element: '<div class="content">ParentNode</div>'
Actual value: text="ParentNode"
```

## Tell us about your environment
* **Selenide Version**: 6.0.3
* **Chrome\Firefox\IE Version**: Chrome 95.0.4638.54
* **Browser Driver Version**: ChromeDriver 2.38
* **Selenium Version**: 4.0.0
* **OS Version**: Windows 10 Pro 20H2 19042.1288

## Code To Reproduce Issue [ Good To Have ]
```
<div id="parent" class="tree-node">
  <div class="content">
    ParentNode
  </div>
  <div id="child" class="tree-node">
    <div class="content">
      ChildNode
    </div>
  </div>
</div>
```

```
@Test
public void testSelector() {
	$("#parent.tree-node").shouldHave(text("ParentNode"));
	$("#parent .tree-node").shouldHave(text("ChildNode"));
	$("#parent").$(".tree-node").shouldHave(text("ChildNode"));
	$("#parent .tree-node .content").shouldHave(text("ChildNode"));
	$("#parent").$(".tree-node").$(".content").shouldHave(text("ChildNode"));
	$("#parent .tree-node").$(".content").shouldHave(text("ChildNode"));
	$("#parent").$(".tree-node .content").shouldNotHave(text("ParentNode"));
}
```

**Comment by asolntsev** [comment]
@JoakimBruce I must admit, it was also surprise for me. 

The line 
```javascript
document.querySelector('#parent').querySelector('.tree-node .content')
```

first finds all `'.tree-node .content'` elements in the while DOM, and then returns those of them which are descedants of `'#parent'`. It find it disappointing and incorrect, but I don't see any easy solution at the moment. :(
