### ISSUE TITLE
impossible to start browser maximized via capabilities setting.

### ISSUE THREAD

**Issue by Bersikan** [selenide/selenide#1630]
## The problem
impossible to set capabilities with "Configuration.browserCapabilities = SomeCapabilities" (pls see code example)
In current example browser starts in NOT maximized mode.

## Environment
* **Selenide Version**: 6.0.3
* **Chrome Version**: 95.0.4638.54
* **OS Version**: Win 10

## Code To Reproduce Issue

    @Test
    public void search() {
        DesiredCapabilities cap = new DesiredCapabilities();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("start-maximized");
        cap.setCapability(ChromeOptions.CAPABILITY, options);
        Configuration.browserSize = null;
        Configuration.browserCapabilities = cap;
        Selenide.open("https://www.goole.com/");
        Selenide.sleep(500);
    }

**Comment by Bersikan** [comment]
As capabilities already @Deprecated in selenium4 i think new "Configuration.browserOptions" should be created to be able work with ChromeOptions(); etc.

**Comment by asolntsev** [comment]
@Bersikan Can you try with Selenide 6.1.1?

NB! You will need to simplify your code to make it work properly:

```java
@Test
public void search() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("start-maximized");
    Configuration.browserCapabilities = options;
    Configuration.browserSize = null;
    Selenide.open("https://www.goole.com/");
    Selenide.sleep(500);
}
```

(shortly said, you don't need to wrap `ChromeOptions` into `DesiredCapabilities` anymore).
