### ISSUE TITLE
Selenide 6.0.3 spawns 2x times more sessions than required in parallel exectution via Junit5

### ISSUE THREAD

**Issue by artemryazantsev** [selenide/selenide#1639]
## The problem
After updating from Selenide 5.24.3 to 6.0.3 I faced strange behavior of parallel execution in my tests. That's what I found:

Selenide spawns 2 times more sessions than I set as a thread count for parallel execution in Junit5.
F.e. for 2 parallel threads, Selenide spawns 4 browser sessions etc.
It doesn't matter if it is a remote webdriver (I use Selenoid) or the local one.

It works absolutely fine with Selenide 5.24.3

## Details
There is an example of code how I reproduced the issue below

## Tell us about your environment
* **Selenide Version**: Selenide 6.0.3
* **Chrome\Firefox\IE Version**: Chrome/Firefox (doesn't matter)
* **Browser Driver Version**: Latest (autodownloaded)
* **Selenium Version**: 4.0
* **OS Version**: Linux

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.
command to run the tests (you can set any count of parallel threads):
`gradle clean test -Dthreads=2 `

**Test class**
```
public class ExampleTests {

    @BeforeEach
    void setup(){
        Configuration.browser="chrome";
    }

    @RepeatedTest(25)
    void selenide6TestExample(){
        open("https://github.com");
        Selenide.sleep(30000);
    }
}
```

**build.gradle**
```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
    testImplementation("com.codeborne:selenide:6.0.3")
}

test {
    useJUnitPlatform()
}

tasks.withType(Test) {
    systemProperties = System.properties
    def threadCount = System.properties.containsKey('threads') ? System.getProperty('threads') : 1
    systemProperties += [
            'junit.jupiter.execution.parallel.enabled'                 : true,
            'junit.jupiter.execution.parallel.mode.default'            : 'concurrent',
            'junit.jupiter.execution.parallel.mode.classes.default'    : 'concurrent',
            'junit.jupiter.execution.parallel.config.strategy'         : 'fixed',
            'junit.jupiter.execution.parallel.config.fixed.parallelism': threadCount,
            'junit.jupiter.extensions.autodetection.enabled'           : true,
    ]
    afterSuite { desc, result ->
        if (!desc.parent) { // will match the outermost suite
            def output = "Result: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} successes," +
                    " ${result.failedTestCount} failures, ${result.skippedTestCount} skipped)"
            println("\n╔══${'═' * output.length()}══╗\n║  $output  ║\n╚══${'═' * output.length()}══╝")
        }
    }

}
```

**Comment by BorisOsipov** [comment]
It is not selenide issue. By unknown reason if test calls any selenium API gradle spawn x2 tests count.
It can be easily reproduced with pure selenium with your gradle config by:
 ```
     @RepeatedTest(25)
    void selenide7TestExample() {
        System.out.println("Hello from test " + Thread.currentThread().getId());
        WebDriverManager.chromedriver().getDownloadedDriverPath();
        ChromeDriver driver = new ChromeDriver();
        driver.get("https://github.com");
        Selenide.sleep(10_000);
        driver.quit();
    }
```

**Comment by cocorossello** [comment]
Know issue in selenium 4.0. See https://github.com/SeleniumHQ/selenium/issues/9957

**Comment by BorisOsipov** [comment]
@cocorossello thank you for sharing the link.

seems explanation and workarounds could be found here https://github.com/SeleniumHQ/selenium/issues/9359

**Comment by asolntsev** [comment]
@arazantsau @cocorossello Hopefully this bug was fixed when JUnit 5.9.0 was released. Did you try to upgrade JUnit5?

**Comment by cocorossello** [comment]
Yes, it does work. You need a custom ParallelExecutionConfiguration with

```
    @Override
    public Predicate<? super ForkJoinPool> getSaturatePredicate() {
        return forkJoinPool -> true;
    }
```

**Comment by bogvol** [comment]
@cocorossello can you please share the whole solution that you mean? I had the same problem and was not able to solve by just overriding `getSaturatePredicate()` method.

**Comment by cocorossello** [comment]
That's weird, because it's all that is needed. Are you sure that junit is using this ParallelExecutionConfiguration?

In my case all I'm using is:

- Gradle junit configuration:
```
    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        systemProperties = [
                'junit.jupiter.execution.parallel.enabled'                 : 'true',
                'junit.jupiter.execution.parallel.config.strategy'         : 'custom',
                'junit.jupiter.execution.parallel.config.custom.class'     : 'com.example.ParallelConfigurationStrategy'
        ]
        ...
```

And The ParallelConfigurationStrategy class:

```

public class ParallelConfigurationStrategy implements ParallelExecutionConfiguration, ParallelExecutionConfigurationStrategy {
    private static final int PARALLEL_TESTS = 96;

    @Override
    public int getParallelism() {
        return PARALLEL_TESTS;
    }

    @Override
    public int getMinimumRunnable() {
        return getParallelism();
    }

    @Override
    public int getMaxPoolSize() {
        return PARALLEL_TESTS;
    }

    @Override
    public int getCorePoolSize() {
        return PARALLEL_TESTS;
    }

    @Override
    public int getKeepAliveSeconds() {
        return 30;
    }

    @Override
    public Predicate<? super ForkJoinPool> getSaturatePredicate() {
        return forkJoinPool -> true;
    }

    @Override
    public ParallelExecutionConfiguration createConfiguration(final ConfigurationParameters configurationParameters) {
        return this;
    }

}

```

**Comment by bogvol** [comment]
@cocorossello , thank you very much for the info.
In my opinion the main role here plays the method:
```
@Override
public int getMaxPoolSize() {
        return PARALLEL_TESTS;
}
```
because in `DefaultParallelExecutionConfigurationStrategy` class `getMaxPoolSize()` is `256 + parallelism`, after I changed it to your version, now it works as expected.

**Comment by viacheslav-kazarenko** [comment]
@cocorossello, @bogvol, please tell, whether this solution works with Java8? After reading other threads (in selenium and junit repos) about this issue, i'm confused if this this issue can be solved at all with Java8.

**Comment by asolntsev** [comment]
@viacheslav-kazarenko If I correctly understand, that problem with parallel tests was only actual for Java 8.
So I assume the fix is only applicable for Java 8m too.

Also, if I am not mistaken, that issue was fixed later in some of JUnit released.

**Comment by viacheslav-kazarenko** [comment]
@asolntsev, if I corretlly understand this issue discussion (https://github.com/SeleniumHQ/selenium/issues/10113), problem with parallel tests is related to different versions of Java, not only Java 8. Moreover, there are doubts about possibility of solving it for Java 8. That's why I wonder, whether solution above can help for Java 8...

**Comment by bogvol** [comment]
@viacheslav-kazarenko the solution works fine for my configuration:
1. Java 11
2. selenide 6.8.1
3. JUnit 5.9.2
