### ISSUE TITLE
Selenide should not throw exceptions if selenide.remote is set, but empty

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#1656]
`-Dselenide.remote=` throws an exception "invalid remote parameter" now.

Typical case for CI automation is to set different parameters for Selenium Grid/Selenoid execution and no parameter for local execution.

But `-Dselenide.remote=$grid_address` doesn't work for local execution even if $grid_address is empty.

`-Dselenide.remote=` should work the same way, when it is not set at all.

**Comment by asolntsev** [comment]
fixed in https://github.com/selenide/selenide/pull/1663
