### ISSUE TITLE
NEED help how to use SelenideProxyServer without instantiating explicitly any driver, with Selenium Grid ?

### ISSUE THREAD

**Issue by Tonicku** [selenide/selenide#1662]
## The problem
CustomWebdriverWithSelenideProxyTest is using SelenideProxyServer and instantiating explicitly the driver chrome or firefox.
how to have the same behavior of that test without  instantiating drivers.
but just using static Configuration.browser ?

**Comment by asolntsev** [comment]
@Tonicku What exactly do you want to achieve? 

Using proxy in Selenide is much easier than in `CustomWebdriverWithSelenideProxyTest`. 

```java
Configuration.proxyEnabled = true;
Configuration.remote = "your-grid-url";

open("some://url");

```

**Comment by asolntsev** [comment]
Feel free to reopen if new information arrives.

**Comment by Tonicku** [comment]
@asolntsev Thank for your support. 
what i wanted is to intercept traffic as depending on my tests, the id of the created object is in the xhr response.
after a upgrade settings on our selenium grid, i was able to use the DevTools in this way

No Activation of your settings
` WebDriver augmentedDriver = new Augmenter().augment(WebDriverRunner.getWebDriver());
        DevTools devTools = ((HasDevTools) augmentedDriver).getDevTools();
        devTools.createSession();
        devTools.send(Network.enable(Optional.of(100000000), Optional.empty(), Optional.empty()));
        final String[] responseBody = new String[1];
        devTools.addListener(Network.responseReceived(), responseReceived -> {
             .... code depending on what we are looking for ...
        });
        return responseBody;
    }`

I tried you approach, here is my working progress

        WebDriverRunner.getSelenideProxy()
                       .addResponseFilter("WorkRequest", (response, contents, messageInfo) -> {
                           if (messageInfo
                                   .getUrl()
                                   .contains("...")) {

                               log.debug("ResponseReceived: " + contents.getTextContents());

                           }
                       });

I don't have a result as i have to play with the host file or if there a way to inject them into SelenideProxy ?

**Comment by Tonicku** [comment]
when i activate the proxy ; Configuration.proxy = true., the Web application url is giving a response 400.
i guess it's because it's missing setting in the Selenide Proxy to have response 200.
i guess i need to set up the allow list into the proxy:
`WebDriverRunner.getSelenideProxy().getProxy().addAllowlistPattern();`

**Comment by asolntsev** [comment]
@Tonicku I don't think you need to call `addAllowlistPattern()`. In all my projects, proxy works without `addAllowlistPattern`. 

You rather need to investigate why your application responses with 400 code. Can you read the application logs?
