### ISSUE TITLE
Jinit 5 parallel tests execution doesn't work correctly with selenide 6.1.1

### ISSUE THREAD

**Issue by AleksandrHoroshko** [selenide/selenide#1665]
## The problem
Jinit5 parallel tests execution doesn't work correctly with selenide 6.1.1, there are extra threads run.

## Details
I have tried to start tests in parallel using Junit5 and it works correctly with selenide 5.25.0, when I set the following properties: junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.default=same_thread
junit.jupiter.execution.parallel.mode.classes.default=concurrent
junit.jupiter.execution.parallel.config.strategy=fixed
junit.jupiter.execution.parallel.config.fixed.parallelism=6

But now with selenide 6.1.1, my tests try to run much more threads than set up in my Junit5 configuration file junit-platform.properties file

## Tell us about your environment
* **6.1.1**: 
* **Ubuntu 20.04**:

**Comment by BorisOsipov** [comment]
Duplicate https://github.com/selenide/selenide/issues/1639
