### ISSUE TITLE
Is there any way how to donwload file with remote webdriver ?

### ISSUE THREAD

**Issue by dironel** [selenide/selenide#1686]
Hello i need to do this:
i have multiple nodes on selenium grid and i need download file on remote node (with remote webdriver) , but i don't know how.
I don't care if downloaded file ends on node local disk.
Is there any way how to do it using selenide $.download ?

**Comment by asolntsev** [comment]
Hi! 

Unfortunately, FOLDER mode doesn't work with Selenium Grid.
The reason is that Grid is a different machine, and test machine cannot always access files on that Grid machine. 

Please try `FileDownloadMode.HTTPGET` or `FileDownloadMode.PROXY`.

**Comment by asolntsev** [comment]
@dironel FYI I registered a feature request https://github.com/selenide/selenide/issues/1687
Probably some day somebody can implement it. :)
