### ISSUE TITLE
JavaDoc update is needed to reflect latest changes for WebDriverProvider interface

### ISSUE THREAD

**Issue by s4ik4t** [selenide/selenide#1690]
This is a documentation issue.

It seems that recently in v6.1.0 the `WebDriverProvider` interface was updated (`createDriver` method). However, the changes are not reflected in the JavaDoc.

https://selenide.org/javadoc/current/com/codeborne/selenide/WebDriverProvider.html

*Old method signature:* `createDriver(org.openqa.selenium.remote.DesiredCapabilities desiredCapabilities)`
*New method signature:* `createDriver(org.openqa.selenium.Capabilities capabilities)`

**Comment by asolntsev** [comment]
@s4ik4t thank you for pointing it out! Updated the javadoc.
