### ISSUE TITLE
Feature request: optional automatic scrolling

### ISSUE THREAD

**Issue by flange-ipb** [selenide/selenide#1692]
## The problem
This is kind of related to #1287. In order to click a `SelenideElement` I have to scroll to it first in case this element is obscured by another element. In my specific case, this behaviour depends on the browser screen resolution (something I may not be able to control), because the obscuring element is the page footer, which has a constant height. In principle, I would have to add `scrollTo()` before all my `click()` calls now.

## Feature request
* Add a config property to `Configuration` to enable automatic scrolling (default: false).
* Execute `scrollTo()` in the `SelenideElement.click()` method if this config property is enabled.
* I guess other methods may also fail if the element is obscured, for instance `hover()`.

## Tell us about your environment
* **Selenide Version**: 6.1.2
* **Selenoid Version**: 1.8.1

**Comment by asolntsev** [comment]
@flange-ipb do you know about setting `Configuration.clickViaJS = true`? I guess it solves your problem.

**Comment by flange-ipb** [comment]
Hi @asolntsev,
yes I've seen that and enabled it now. This makes my tests flaky, because it's a JSF application that heavily relies on AJAX. The warning in `clickViaJS`'s Javadoc is correct.
On the other hand, using `click(ClickOptions.usingJavaScript())` works for my specific problem, but again, I would have to add it to all my `click()` calls.

**Comment by BorisOsipov** [comment]
>have to add it to all my click() calls.

you can do it with pure selenium

```
public class ScrollWebdriverListener
        extends org.openqa.selenium.support.events.AbstractWebDriverEventListener {

    public void beforeClickOn(WebElement element, WebDriver driver) {
      Point location = element.getLocation();
      Selenide.executeJavaScript("window.scrollTo(" + location.getX() + ", " + location.getY() + ')');
    }
}
...
WebDriverRunner.addListener(new ScrollWebdriverListener());
```

**Comment by flange-ipb** [comment]
Thanks for the code snippet, @BorisOsipov. (N.B.: That's the same implementation like in the `ScrollTo` class.)
It works like a charm after adding a little offset to the y-coordinate, because the application also serves a sticky navbar on top. This solves my problem!
The class `AbstractWebDriverEventListener` and the method `WebDriverRunner.addListener(WebDriverEventListener listener)` are deprecated. It is also possible to implement `WebDriverListener` and override its `beforeClick(WebElement element)` method.
