### ISSUE TITLE
Find all returns results from multiple elements

### ISSUE THREAD

**Issue by DerekJLeggett** [selenide/selenide#1717]
## The problem
By.id: expMonth
$(by).findAll(By.tagName("option")).texts();
returns elements having tag name option from select having id expMonth as well as from expYear.
[January, February, March, April, May, June, July, August, September, October, November, December, 2016, 2020, 2019, 2018, 2017]
## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 6.1.1
* **Chrome\Firefox\IE Version**: Chrome: 97.0.4692.99
* **Browser Driver Version**: Using chromedriver 97.0.4692.71 (resolved driver for Chrome 97)
* **Selenium Version**: 3.141.59
* **OS Version**: Windows 10 Version: 20H2

## Code To Reproduce Issue [ Good To Have ]
Having 2 select elements, attempt to get the options from the 1st element, and the options from both elements are returned.
![image](https://user-images.githubusercontent.com/17225017/151882426-c9b18f29-9dc4-455f-a665-18624df13bca.png)
bug.

**Comment by DerekJLeggett** [comment]
Found working alternative: $$(by).texts();

**Comment by asolntsev** [comment]
@DerekJLeggett If you need to check the texts, don't call methods like `texts`. Instead, use methods like "should*":

```java
$("#expMonth option").shouldHave(texts("January", "February", ..., "December"));
$("#expYear option").shouldHave(texts("2016", "2020", "2017"));
```
