### ISSUE TITLE
Feature Request: add a timeOut for method confirm(), dismiss()

### ISSUE THREAD

**Issue by RomanRSN** [selenide/selenide#1721]
## The problem
The alert can appear in more than 4 seconds, and would be great to extend this calling the method

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 6.2.0

thanks for the greate product

**Comment by kachurinaa** [comment]
SelenideTargetLocator implements that feature

**Comment by asolntsev** [comment]
implemented in https://github.com/selenide/selenide/pull/1846.
will be released as Selenide 6.6.0
