### ISSUE TITLE
Download csv file 150mb then read files but java.lang.OutOfMemoryError: Java heap space is raised

### ISSUE THREAD

**Issue by Tonicku** [selenide/selenide#1728]
## The problem
I download a 150M csv file then i read it and load into List
when i read it and load via java application, i have no Java heap space issue
when i download that file with Selenide then read/load, Java Heap space appears

## Details
If necessary, describe the problem you have been experiencing in more detail.
https://selenide.org/2019/12/10/advent-calendar-download-files/
i am not using, as no url attribute
Configuration.proxyEnabled = true;
Configuration.fileDownload = PROXY;

Message from log
--------------------

java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid19340.hprof ...
Heap dump file created [1623186586 bytes in 8.899 secs]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Webdrivers killer thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "LittleProxy-0-ClientToProxyAcceptor-0"
JDWP exit error JVMTI_ERROR_INVALID_CLASS(21): on getting class status [./open/src/jdk.jdwp.agent/share/native/libjdwp/util.c:1284]
FATAL ERROR in native method: JDWP on getting class status, jvmtiError=JVMTI_ERROR_INVALID_CLASS(21)

## Tell us about your environment
* **Selenide Version**: 6.2.1
* **Chrome\Firefox\IE Version**: local 98.0.4758.81 (Official Build) (64-bit)
* **Browser Driver Version**: ChromeDriver 98.0.4758.80
* **Selenium Version**: 
* **OS Version**: Window 10

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@Tonicku not sure if we can help. You probably just need to give tests more memory.

Anyway, could you share that memory dump java_pid19340.hprof?

**Comment by Tonicku** [comment]
@asolntsev yeaaa i was doing it ... so i guess too many columns to load as List<String>
even zipped the hprof is quite huge :/ will try analyze it

**Comment by asolntsev** [comment]
@Tonicku Could you get a file? 

Feel free to reopen the issue if new information arrives.
