### ISSUE TITLE
Wiki: Please update custom conditions

### ISSUE THREAD

**Issue by flange-ipb** [selenide/selenide#1746]
Hi folks,

the [Wiki page on custom conditions](https://github.com/selenide/selenide/wiki/Custom-conditions) is not up-to-date with the API changes in the Condition class introduced with 6.0.1. Can you please update these useful examples?

Best regards,
Frank

**Comment by asolntsev** [comment]
@flange-ipb Thank you, I have updated the wiki page https://github.com/selenide/selenide/wiki/Custom-conditions

**Comment by flange-ipb** [comment]
Thanks @asolntsev
One objection for the method signature, it should be `public CheckResult check(Driver driver, WebElement element)`.

I played with the child condition before and ended up with more or less the same implementation (note: `condition.name` is private and has to be substituted with `condition.getName()`). What buggs me is that the fail message is not very helpful.
Example:
```
open("https://github.com/selenide/selenide/wiki/Custom-conditions");
$(".markdown-body > h1").shouldHave(child("a", attribute("aria-hidden", "true"))); // pass
$(".markdown-body > h1").shouldHave(child("a", attribute("aria-hidden", "false"))); // fails
```
The fail message is
```
Element should have child a has attribute {.markdown-body > h1}
Element: '<h1>List of custom conditions, created by Selenide community</h1>'
```
It would be better to have some additional information on the expected attribute.

**Comment by asolntsev** [comment]
@flange-ipb What Selenide version are you using?
I have tried `child` condition with latest Selenide 6.3.3, and it shows the expected attribute as well:

```
Element should have child a has attribute aria-hidden=false {.markdown-body > h1}
```

Anyway,  I have rewritten `child` implementation so that it doesn't use static method `$` and adds `Actual value` to the error message:
```
Element should have child a with attribute aria-hidden=false {.markdown-body > h1}
Element: '<h1>List of custom conditions, created by Selenide community</h1>'
Actual value: aria-hidden="true"
```

**Comment by flange-ipb** [comment]
@asolntsev Very good, thanks for your great support!
