### ISSUE TITLE
Invalid automatic module name

### ISSUE THREAD

**Issue by blutorange** [selenide/selenide#1748]
## The problem

The `Automatic-Module-Name` in the `MANIFEST.MF` is not a legal module name.

The problem is that illegal module names don't work in the `requires` directive of a `module-info.java`.

https://github.com/sormuras/modules/tree/main/doc/suspicious

## Details

From https://github.com/sormuras/modules/blob/main/doc/suspicious/illegal-automatic-module-names.txt#L79-L82

```text
com.codeborne:selenide-core:6.3.3 -> com.codeborne.selenide-core
com.codeborne:selenide-junit4:6.3.3 -> com.codeborne.selenide-junit4
com.codeborne:selenide-proxy:6.3.3 -> com.codeborne.selenide-proxy
com.codeborne:selenide-testng:6.3.3 -> com.codeborne.selenide-testng
```

Seems to be defined here https://github.com/selenide/selenide/blob/master/gradle/publish-module.gradle

Could be solved e.g. by replacing the hyphen with a period:

```text
com.codeborne:selenide-core:6.3.3 -> com.codeborne.selenide.core
com.codeborne:selenide-junit4:6.3.3 -> com.codeborne.selenide.junit4
com.codeborne:selenide-proxy:6.3.3 -> com.codeborne.selenide.proxy
com.codeborne:selenide-testng:6.3.3 -> com.codeborne.selenide.testng
```

**Comment by asolntsev** [comment]
Fixed by https://github.com/selenide/selenide/commit/e0551e0028c942def530bcaca5563b129dc4bf33
Released as Selenide 6.3.4
