### ISSUE TITLE
Browser heap memory is increasing very fast while running a test

### ISSUE THREAD

**Issue by CodingBasti** [selenide/selenide#1777]
## The problem
Browser heap memory is increasing very fast while running a test.

## Details
My web application creates and destroys often DOM elements. 
If I look into the browsers js heap while running a selenide test,
I see thousands of strings with same content "**(function() { // Copyright (c) 2012 The Chromium Authors. All rights reserved. // Use of this** (...)"
It looks like it is a file of the chrome driver, is 66384 bytes large and in the heap about 15.000 times!
If a start my app without selenide test, it seems fine.

## Tell us about your environment
* **Selenide Version**: 6.4.0
* **Chrome\Firefox\IE Version**: 100.0.4896.127
* **OS Version**: Mac OS 12.3.1

**Comment by CodingBasti** [comment]
<img width="1699" alt="Bildschirmfoto 2022-04-14 um 08 13 43" src="https://user-images.githubusercontent.com/22628369/164162098-26df717e-a6c2-4782-81cf-78ba49c295a0.png">

**Comment by asolntsev** [comment]
Wow, it's an interesting finding. :)
But probably it's a problem of Selenium (or even chromedriver?), not Selenide.

Could you please share the whole string which is partially visible on your screenshot?

**Comment by BorisOsipov** [comment]
It is https://source.chromium.org/chromium/chromium/src/+/main:chrome/test/chromedriver/js/call_function.js

docs -https://chromium.googlesource.com/chromium/src/+/refs/heads/main/chrome/test/chromedriver/docs/run_javascript.md#how-chromedriver-runs-javascript-code-use-method-2

**Comment by CodingBasti** [comment]
@asolntsev Here the **string**, not sure if it's cut of by chrome developer:
`function() { // Copyright (c) 2012 The Chromium Authors. All rights reserved. // Use of this source code is governed by a BSD-style license that can be // found in the LICENSE file. /** * Enum for WebDriver status codes. * @enum {number} */ var StatusCode = { STALE_ELEMENT_REFERENCE: 10, JAVA_SCRIPT_ERROR: 17, NO_SUCH_SHADOW_ROOT: 65, DETACHED_SHADOW_ROOT: 66 }; /** * Enum for node types. * @enum {number} */ var NodeType = { ELEMENT: 1, DOCUMENT: 9, }; /** * Dictionary key to use for holding an element ID. * @const * @type {string} */ var ELEMENT_KEY = 'ELEMENT'; /** * Dictionary key to use for holding a shadow element ID. * @const * @type {string} */ var SHADOW_ROOT_KEY = 'shadow-6066-11e4-a52e-4f735466cecf'; /** * True if using W3C Element references. * @const * @type {boolean} */ var w3cEnabled = false; /** * True if shadow dom is enabled. * @const * @type {boolean} */ var SHADOW_DOM_ENABLED = typeof ShadowRoot === 'function'; /** * Generates a unique ID to ident"`

**Comment by asolntsev** [comment]
@CodingBasti Strange, I am running a test against a web page that is constantly adding/removing web elements, but the memory consumption is not growing... 

Can you share your web page?

Anyway, I don't see how we can fix it in Selenide. It's a code of Selenium, Chrome or Chromedriver.

**Comment by CodingBasti** [comment]
@asolntsev Thanks for your test run!
I just found this older related post: https://stackoverflow.com/questions/54987256/protractor-endurance-test-memory-leak

**Comment by asolntsev** [comment]
@CodingBasti thank you for sharing the link!
I didn't understand: did somebody find a solution for this problem?

**Comment by CodingBasti** [comment]
Unfortunately, I have not found a solution yet. I am still researching...

**Comment by CodingBasti** [comment]
Just want to give an update here: We found a memory leak on our side in the web application. It was an event/listener that was added (but not removed after element was destroyed) for each new HTML-Element. 
I suppose that the selenium driver add this code for each listener, so this was the reason why it was in memory so often.

**Comment by asolntsev** [comment]
@CodingBasti Nice. Thank you for sharing the information.
