### ISSUE TITLE
[Question] : how to disable Credit-Card save pop-up

### ISSUE THREAD

**Issue by dacloutier-logmein** [selenide/selenide#1789]
## The problem
Is there a way to tell selenide to disable CreditCard save pop-up? I've looked up stackoverflow for answers, but nothing that I tried helped. It might just be something I have overlooked.

## Tell us about your environment
* **Selenide Version**: 6.4.0
* **Chrome\Firefox\IE Version**:  Latest versions (100 at the time of this issue)

## Steps To Reproduce Issue
- Access any page with a credit card form, fill the information, you should get the "creditcard save" pop-up.

**Comment by asolntsev** [comment]
@dacloutier-logmein I don't know the answer. Apparently, you should add some chrome option before starting the webdriver. Something similar to `enable-automation`, `plugins.always_open_pdf_externally`, `--disable-default-apps` etc.
