### ISSUE TITLE
Exception is raised when using german Umlaute

### ISSUE THREAD

**Issue by redhell** [selenide/selenide#1796]
## The problem
I'm testing an Vaadin Application and need to fill a text box with german umlaute (e.g. ä, ö, ü) and getting an exception in the frontend. But after I dismiss the exception popup the field is correctly filled. 

If I fill the field manual no exception is raised.

## Details
Im searching the input field with this: $($("vaadin-text-field).getShadowRoot().findElement(By.cssSelector("input"))).val("köln");
The same happens if I send it over sendKeys to the ui. 

## Tell us about your environment
* **Selenide Version**:  6.4
* **Chrome\Firefox\IE Version**:  Edge 100
* **Browser Driver Version**: 100.0.1185.50 win64
* **Selenium Version**: selenium webdriver 4.1.3
* **OS Version**:  win10

**Comment by asolntsev** [comment]
@redhell Sorry, your code doesn't compile on my machine. Could you please fix the code sample?

I tried to transform your code to this:
```
$("#shadow-host").getShadowRoot().findElement(By.cssSelector("#inputInShadow")).sendKeys("köln");
```

and it works on my machine.

**Comment by admizh** [comment]
@redhell it is likely that you are using characters in an encoding unknown to the web driver (typically for chrome). My advice is to try using a character set with the correct encodings. I use Utility method like this:

```
    @NotNull
    private static String getUmlautNames(int size) {
        String template = "àáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð";
        StringBuilder newName = new StringBuilder();
        while (newName.length() < size) {
            //commons lang 3
            final int i = RandomUtils.nextInt(0, template.length());
            newName.append(template.charAt(i));
        }
        return newName.toString();
    }
```

**Comment by asolntsev** [comment]
@redhell Did you have a chance to try solution suggested by @admizh ?
Feel free to share more info here.

Anyway, I guess this problem (if any) should be fixed in webdriver. Hardly we can fix it on Selenide side.

**Comment by redhell** [comment]
Hi,

yes I tried this. But the encoding isn't the problem.

In the log files we received an exception that the keypress event is empty.

**Comment by asolntsev** [comment]
Seems the problem was fixed by https://github.com/selenide/selenide/issues/1497
