### ISSUE TITLE
Selenide 6.4.0 can't override existing screenshots

### ISSUE THREAD

**Issue by Panwo** [selenide/selenide#1803]
Hello. 

We use Junit 5, our base class tests are annotated with "@ExtendWith({ScreenShooterExtension.class})". After upgrade to selenide 6.4.0 there are a lot of errors in the log :
![Capture](https://user-images.githubusercontent.com/16680623/168595612-fbda8688-4508-433a-af1e-6ff3ca92f22c.PNG)

**Comment by asolntsev** [comment]
@Panwo Yes, we consider it a feature, not a bug. :) 
We recommend to remove all reports/screenshots/other artifacts from previous test run before the next test run.
