### ISSUE TITLE
Pressing the Tab key should be removed from the method $.clear().

### ISSUE THREAD

**Issue by arsen-papoyan** [selenide/selenide#1808]
* **Selenide Version**:  6.5.0
* **Chrome\Firefox\IE Version**:  Chrome 101.0.4951.64
* **OS Version**: macOS Monterey 12.3.1 
* **Selenium Version**:  4.1.4

## Steps to reproduce:
Perform $.clear() operetion.

## Actual result
Method $.clear() does press "Home -> Shift+End -> Backspace -> Tab"

## Expected result
Method $.clear() shoud press "Home -> Shift+End -> Backspace"

**Comment by asolntsev** [comment]
I found that method `$.clear()` always un-focused the element. The only difference is that
* In Selenide 6.4.0, `$.clear()` moved focus to `<body>`.
* In Selenide 6.5.0, `$.clear()` moves focus to the next field

Why it's important for you where the focus moves?

**Comment by arsen-papoyan** [comment]
Scenario:
I should perform clear and type valid data in the Email field, next assert that the Email field stays valid (that is, not highlighted as red).
Since in Selenide 6.5.0, when `$.clear()` moves focus to the next field (that is, the Password field gets focus), next in case of `$.sendKey()` in the Email field, the Password field becomes invalid (that is, highlighted as red), and as I have the same assertion method for all form fields, then the positive test case fails.
![image](https://user-images.githubusercontent.com/74778982/169878406-d026d24d-ee60-4898-8bf8-72e4342df5f9.png)

**Comment by asolntsev** [comment]
@arsen-papoyan Wait, what it means? 

> as I have the same assertion method for all form fields

Does it mean that you have method like `assertAllFieldsValid` which verifies ALL fields instead if validating only email? 
At least this method is slow, and is slowing down your tests. And it also tests unrelated functionality (password validation instead of email validation). I recommend to verify separately validation of email and password fields.

P.S. It doesn't mean that we shouldn't fix method `$.clear()`, just wanted to be useful. :)

**Comment by arsen-papoyan** [comment]
> as I have the same assertion method for all form fields

this means: 
In the case of validating the current field, I use a selector (like a red highlight or clear button) that is the same for all fields, so I just assert that this selector should not be displayed.
In your suggestion, I should grab the selector for each field, and If there are eg. ten fields in the form, I should create a selector for each field to validate. I guess that is not the best practice.
What do you think?

**Comment by asolntsev** [comment]
@arsen-papoyan I would rather say it's a good practice to verify only the related things. 
To avoid duplication, you can create some reusable generic method like `verifyNoErrors($("[name=email]"))` or something similar.

**Comment by asolntsev** [comment]
@arsen-papoyan Fixed in Selenide 6.5.1 (just released).
