### ISSUE TITLE
Method $().setValue(value) in 6.5.0 throw UnsupportedCommandException in Appium tests

### ISSUE THREAD

**Issue by smirnov-mv** [selenide/selenide#1810]
## The problem
Method $().setValue(value) not working as expected (set value in field) after update Seelnide to 6.5.0.
In 6.4.0 method works.
## Details
```
Element should be editable {By.id: phone}
Element: '<EditText class="android.widget.EditText" resource-id="***********:id/txtPhone" checked="false" enabled="true" focused="true" package="***********" name="+7 (" className="android.widget.EditText" bounds="[40,280][728,411]" displayed="true">+7 (</EditText>'
Caused by: UnsupportedCommandException: 'readonly' attribute is unknown for the element. Only the following attributes are supported: [checkable, checked, {class,className}, clickable, {content-desc,contentDescription}, enabled, focusable, focused, {long-clickable,longClickable}, package, password, {resource-id,resourceId}, scrollable, selection-start, selection-end, selected, {text,name}, bounds, displayed, contentSize]
Comparison Failure: 
Expected :editable
Actual   :null
```
## Tell us about your environment
* **Selenide Version**: 6.5.0
* **Selenium Version**: 4.1.4
* **OS Version**: Appium, android native app (Driver info: io.appium.java_client.android.AndroidDriver)

## Code To Reproduce Issue [ Good To Have ]
    $(input).setValue(value);

**Comment by asolntsev** [comment]
@smirnov-mv Do you use [selenide-appium](https://github.com/selenide/selenide-appium) plugin? 

You the latest version of it 2.0.2 (just released). It should fix method `$.setValue()` in appium.

**Comment by smirnov-mv** [comment]
@asolntsev , yes, I have used appium plugin 2.0.1. Updated to 2.0.2 — now method `setValue()` for mobile fixed. Thanks.
