### ISSUE TITLE
Make clipboard work even in headless mode

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1816]
## The problem
Clipboard in Selenide work only in headful mode. 
We can make it work in headless mode as well by using JavaScript instead of `java.awt.Toolkit`. 

To set clipboard content:
```javascript
window.clipboardData.setData('key', 'value')
```

To get clipboard content:
```javascript
window.clipboardData.getData('key')
```

NB! Method `getData()` asks for permission. Need to find the webdriver option to suppress this dialog.

**Comment by kachurinaa** [comment]
I think it will help, it will accept all permissions
DesiredCapabilities caps = new DesiredCapabilities();
    caps.setCapability("browser", "Chrome");
    caps.setCapability("browser_version", "75.0");
    caps.setCapability("os", "Windows");
    caps.setCapability("os_version", "10");

    // INIT CHROME OPTIONS
    ChromeOptions options = new ChromeOptions();
    Map<String, Object> prefs = new HashMap<String, Object>();
    Map<String, Object> profile = new HashMap<String, Object>();
    Map<String, Object> contentSettings = new HashMap<String, Object>();

    // SET CHROME OPTIONS
    // 0 - Default, 1 - Allow, 2 - Block
    contentSettings.put("notifications", 1);
    profile.put("managed_default_content_settings", contentSettings);
    prefs.put("profile", profile);
    options.setExperimentalOption("prefs", prefs);

    // SET CAPABILITY
    caps.setCapability(ChromeOptions.CAPABILITY, options);

**Comment by asolntsev** [comment]
@kachurinaa I haven't found any working solution for Firefox. :(

**Comment by kachurinaa** [comment]
> @kachurinaa I haven't found any working solution for Firefox. :( Probably it's possible with CDP?
Try to experiment with that

```

#---------------------------------------------------------------------------
# Prefs starting with "permissions."
#---------------------------------------------------------------------------

# 1-Accept, 2-Deny, Any other value: Accept
- name: permissions.default.image
  type: RelaxedAtomicUint32
  value: 1
  mirror: always

- name: permissions.delegation.enabled
  type: bool
  value: true
  mirror: always

- name: permissions.isolateBy.userContext
  type: RelaxedAtomicBool
  value: false
  mirror: always

- name: permissions.isolateBy.privateBrowsing
  type: RelaxedAtomicBool
  value: true
  mirror: always
```

or this

```
- name: dom.webnotifications.allowinsecure
  type: RelaxedAtomicBool
  value: false
  mirror: always

- name: dom.webnotifications.allowcrossoriginiframe
  type: RelaxedAtomicBool
  value: false
  mirror: always

- name: dom.webnotifications.enabled
  type: RelaxedAtomicBool
  value: true
  mirror: always

- name: dom.webnotifications.requireuserinteraction
  type: RelaxedAtomicBool
  value: true
  mirror: always

- name: dom.webnotifications.requireinteraction.enabled
  type: RelaxedAtomicBool
  value: @IS_NIGHTLY_BUILD@
  mirror: always

- name: dom.webnotifications.silent.enabled
  type: RelaxedAtomicBool
#if defined(MOZ_WIDGET_ANDROID)
  value: @IS_NIGHTLY_BUILD@
#else
  value: false
#endif
  mirror: always
```

like this
```
FirefoxProfile ffprofile = new FirefoxProfile();
ffprofile.setPreference("dom.webnotifications.enabled", false);
WebDriver driver = new FirefoxDriver(ffprofile);
```

**Comment by asolntsev** [comment]
@kachurinaa The permission is not the only problem. Firefox also says that `navigator.clipboard` or `navigator.clipboard.readText` is not defined.

**Comment by kachurinaa** [comment]
@asolntsev
Type "about:config" url in ff and switch/add attrs like that
clipboard=true
Its new privacy policy

**Comment by asolntsev** [comment]
Found another potential solution: https://www.appsloveworld.com/bestanswer/selenium/138/how-to-fetch-copied-content-from-a-clipboard-selenium-headless-mode

**Comment by LivJes** [comment]
Any updates on this feature? The potential solution leads to a deleted page.

**Comment by asolntsev** [comment]
@LivJes No updates yet. I was playing with different options, but had no success.
Feel free to share a code sample if you know how to solve this problem

**Comment by catalan-ua** [comment]
Starting from 7.4.0 I'm getting the following error when using the code: **clipboard().setText(value);**
Could this error related to this fix or it this something different?
```
org.openqa.selenium.JavascriptException: javascript error: Failed to execute 'writeText' on 'Clipboard': Document is not focused.
  (Session info: chrome=127.0.6533.89)
Build info: version: '4.23.0', revision: '4df0a231af'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [b79ecb00b2ab4befc947fd7fdee4bde5, executeScript {script=await navigator.clipboard.writeText(arguments[0]), args=[{"m":[{"a":[{"x":141.37,"y":115.21,"i":"a0"}]}]}]}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 127.0.6533.89, chrome: {chromedriverVersion: 127.0.6533.88 (a2d0cb026721..., userDataDir: C:\Users\userName\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:57453}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57453/devtoo..., se:cdpVersion: 127.0.6533.89, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: b79ecb00b2ab4befc947fd7fdee4bde5
```

**Comment by asolntsev** [comment]
@LivJes Please try to upgrade to Selenide 7.4.0 - the clipboard was updated there. Should work in headless mode as well.
