### ISSUE TITLE
Add methods to copy and paste content

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1817]
## The problem
It's not trivial for users to find out how to Copy and Paste text in Selenide/Selenium. 
Selenide could suggest such a functionality. 

Internally, it would send keys "Ctrl+C"/"Cmd+C" and "Ctrl+V"/"Cmd+V" (depending on `navigator.platform`). 

## Tell us about your environment
* **Selenide Version**: 6.5.0

**Comment by evpl** [comment]
@asolntsev 

Hi! Please rate the idea:
1) Add `copy()` method to `SelenideElement` by using `SelenideElement.getText()` and `Clipboard.setText(String)`
2) Add `paste()` method to `SelenideElement` by using `Clipboard.getText()` and `SelenideElement.sendKeys(String)`

Is this implementation suitable?

**Comment by asolntsev** [comment]
@evpl I think `$.paste()` idea is good. It's very common to paste text from clipboard into some field.
But `$.copy()` ... is it a common scenario? Users usually don't copy text of a web element. They usually select some text by click or double-click, and then copy the selected text.

**Comment by evpl** [comment]
@asolntsev 

Ok, I'll do it!
