### ISSUE TITLE
How to test "remember me" functionality via Selenide

### ISSUE THREAD

**Issue by nikitakovaliov92** [selenide/selenide#1825]
Hello. I faced the problem of testing the "Remember me" functionality through Selenide. I was expecting that when using the profile details, the next time I open it, the home page would be displayed, but instead, the login page opened again. Is there a way to test this functionality with Selenide? 
**Note:** I do not claim that my code is really correct

_My environment_
**Selenide Version**: 6.4.0
**Selenium version**: 4.1.4
**Browser**: Chrome Version 102.0.5005.63
**OS Version**: Windows 11

_Code To Reproduce Issue_
```
Selenide.open(loginPage);
loginPage.inputEmailAndPassword();
loginPage.clickRememberMe();
loginPage.clickLoginButton();
Selenide.closeWindow();
ChromeOptions options = new ChromeOptions();
options.addArguments("user-data-dir=C:\\Users\\nikit\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\");
Selenide.open(homePage);
```

**Comment by asolntsev** [comment]
The question is about Selenium WebDriver, not Selenide. 

Anyway, here are few notes:
1. You create instance `ChromeOptions`, but you don't pass it to Selenide. Selenide just doesn't know about the existence of your `options` variable. 
2. Why do you think folder `C:\\Users\\nikit\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\` is the proper profile location? It's not. Every time when webdriver opens a browser, it generates a unique new profile in some temporary folder.
