### ISSUE TITLE
Java 1.6+ has jdk.httpserver, please remove dependency on Netty

### ISSUE THREAD

**Issue by tenor-dev** [selenide/selenide#1828]
Selenide brings a whole bunch of Netty dependencies to the project, even if proxy is not used/needed.

It would be much better to use the Java built-in jdk.httpserver to avoid bringing many complex dependencies to projects that use other http servers than Netty.

**Comment by asolntsev** [comment]
@tenor-dev We cannot avoid using Netty because Selenium 4.+ uses Netty. Not only for server, but also Netty http client.
