### ISSUE TITLE
Warning about legacy capabilities

### ISSUE THREAD

**Issue by svschouw-bb** [selenide/selenide#1862]
## The problem
When running selenide we get the warnings:

    Jun 17, 2022 7:37:30 PM org.openqa.selenium.remote.RemoteWebDriver startSession
    WARNING: Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [acceptSslCerts, handlesAlerts, javascriptEnabled, takesScreenshot]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/
    Jun 17, 2022 7:37:32 PM org.openqa.selenium.remote.ProtocolHandshake createSession
    WARNING: Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [acceptSslCerts, handlesAlerts, javascriptEnabled, takesScreenshot]; Please update to W3C Syntax: https://www.selenium.dev/blog/2022/legacy-protocol-support/

## Details
Not super important, but we have some test protections in place that no unexpected warnings are logged. These warnings trigger those protections. We can add them to the list of "expected exceptions" as a temporary workaround.

## Tell us about your environment
* **Selenide Version**: 6.6.3
* **Chrome\Firefox\IE Version**: Starting ChromeDriver 102.0.5005.61
* **Browser Driver Version**: Starting ChromeDriver 102.0.5005.61
* **Selenium Version**: 4.2.2

## Code To Reproduce Issue [ Good To Have ]
```java
public class SimpleSelenideTest {
	@Test
	void simpleTest() {
		Selenide.open("https://www.google.com/");
		System.out.println(Selenide.title());
	}
}
```

**Comment by asolntsev** [comment]
@svschouw-bb This is Selenium issue, not Selenide. See https://github.com/SeleniumHQ/selenium/issues/10711.
Until it's fixed in Selenium/chromedriver/geckodriver/etc. you can configure your logging to ignore warnings from `org.openqa.selenium.W3CCapabilityKeysValidator` (set its loggerLevel to `ERROR`).

**Comment by svschouw-bb** [comment]
Thank you for responding so fast.

I feel like the problem comes from `com.codeborne.selenide.webdriver.AbstractDriverFactory.createCommonCapabilities(T, Config, Browser, Proxy)` which uses all kinds of deprecated capabilities. Although I'm not sure what the alternatives should be.

The loggers that log these are `org.openqa.selenium.remote.RemoteWebDriver` and `org.openqa.selenium.remote.ProtocolHandshake` logging on level WARNING.

**Comment by asolntsev** [comment]
@svschouw-bb @AlexChernookov Well, it seems the problem was not only in Selenium, but in Selenide too. 
Hope PR https://github.com/selenide/selenide/pull/1870 will fix it. Going to release it as Selenide 6.6.6
