### ISSUE TITLE
Deprecated capabilities since Selenide 6.5.0

### ISSUE THREAD

**Issue by AlexChernookov** [selenide/selenide#1866]
## The problem
A warning is displayed in console from the time I've updated to Selenide 6.5.0
[Support for Legacy Capabilities is deprecated; You are sending the following invalid capabilities: [acceptSslCerts, handlesAlerts, javascriptEnabled, takesScreenshots]];  Please update to W3C Syntax.

**Comment by asolntsev** [comment]
@AlexChernookov Seems like duplicate of https://github.com/selenide/selenide/issues/1862
