### ISSUE TITLE
Not able to switch in between webdrivers? 

### ISSUE THREAD

**Issue by SkB1409** [selenide/selenide#1883]
Hi,
I am facing issue during the multiple webdriver switch.
Scenario:
Need to take two driver instances to open two separate chrome browsers.
In one browser need to login as USER1
In second browser need to login as USER2.
Issue::
I am able to open 2 driver instances and login as USER1 in one browser But not able to switch to second browser, open the url using() and login as USER2

Below is my code::

        baseUrl = ("https://foo.com");
        WebDriverManager.chromedriver().setup();
        WebDriver browser1 = new ChromeDriver(new ChromeOptions());
        WebDriver browser2 = new ChromeDriver(new ChromeOptions());
        
        using(browser1, () -> {
            BaseTest.shouldLogin(UserType.USER_01);
           
        });

        using(browser2, () -> {
            BaseTest.shouldLogin(UserType.USER_02);
            $("#h2").click();
            $("#user").shouldHave(text("User 02"));
        });

        using(browser1, () -> {
            $("#h1").click();
            $("#user").shouldHave(text("User 01"));

        });

        browser1.close();
        browser2.close();

**Comment by BorisOsipov** [comment]
@SkB1409 could not reproduce the issue.

The following example works fine for me
```
        Configuration.baseUrl = ("https://github.com");
        WebDriverManager.chromedriver().setup();
        WebDriver browser1 = new ChromeDriver(new ChromeOptions());
        WebDriver browser2 = new ChromeDriver(new ChromeOptions());

        using(browser1, () -> {
            open("/");
            $("h1").shouldHave(text("Where the world builds software"));
        });

        using(browser2, () -> {
            open("https://gitter.im/");
            $("h1").shouldHave(text("Where communities thrive"));
        });

        browser1.close();
        browser2.close();
 ```

could you provide [minimal reproducable example](http://sscce.org/)?

**Comment by SkB1409** [comment]
Thanks for the quick response BorisOsipiv
I will verify my tests by giving url's for both browsers like you did and get back

**Comment by SkB1409** [comment]
Working fine now, Thanks for the support @BorisOsipov
