### ISSUE TITLE
Backwards-incompatible API change for Kotlin users since 6.5.x

### ISSUE THREAD

**Issue by tenor-dev** [selenide/selenide#1885]
## The problem
Before `6.5.x` it was possible to set value of Selenide element as property in Kotlin:
`element("hello").value = "Hello"`

However, Selenide has changed the `setValue` method signature to `CharSequence`, which does not correspond to the type of getter `String getValue()`, making it impossible to use `setValue` as a property.

This is not a backwards-compatible change and made using Selenide in Kotlin less convenient.

**Comment by asolntsev** [comment]
I restored parameter type of `setValue` back to `String`. 

Though, I personally think it's a misuse of setValue method. It was never meant to be a property.

1. Test (and user) can perform some _interactions_ with web elements (not change properties of web elements), and
2. Test can _verify_ properties of elements (using methods *shouldHave*...)
