### ISSUE TITLE
Condition.visible doesn't work as expected

### ISSUE THREAD

**Issue by jinlxz** [selenide/selenide#1898]
## The problem
I created a simple test page to check how `Condition.visible` works, the element `p.positioned` in below code is positioned above the element `#p_hidden` by CSS styling in the page test.html, I use absolute position and z-index to position the element on the top of other elements, why did the unit test pass? it should fail, what's magic here?

if an element is covered by another element which has opacity 50%, is the first element visible here? 

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**:  6.0.3
* **Chrome\Firefox\IE Version**:  Version 103.0.5060.114 (Official Build) (64-bit)
* **Browser Driver Version**:  
* **Selenium Version**:   3.141.59
* **OS Version**:  windows10

## Code To Reproduce Issue [ Good To Have ]
```java
public class TestVisible(){
    @Test
    public void testIsDisplayed(){
        Selenide.open("http://127.0.0.1:8088/test.html");
        SelenideElement p=$("#p_hidden").shouldBe(Condition.visible);
        boolean displayed=getDriver().findElement(By.cssSelector("#p_hidden")).isDisplayed();
        System.out.println("element is displayed, "+ displayed);
    }
}
//test.html
<html>
<head><title>test</title>
<link rel="stylesheet" type="text/css" href="test.css">
</head>
<body>
<h1>Absolute positioning</h1>

<p id="p_hidden">I am a basic block level element. My adjacent block level elements sit on new lines below me.</p>

<p class="positioned">By default we span 100% of the width of our parent element, and we are as tall as our child content. Our total width and height is our content + padding + border width/height.</p>

<p>We are separated by our margins. Because of margin collapsing, we are separated by the width of one of our margins, not both.</p>

<p>inline elements <span>like this one</span> and <span>this one</span> sit on the same line as one another, and adjacent text nodes, if there is space on the same line. Overflowing inline elements <span>wrap onto a new line if possible — like this one containing text</span>, or just go on to a new line if not, much like this image will do: <img src="long.jpg"></p>
</body>
</html>

// test.css
* {
  box-sizing: border-box;
}

body {
  width: 500px;
  margin: 0 auto;
}

p {
  background: aqua;
  border: 3px solid blue;
  padding: 10px;
  margin: 10px;
}

span {
  background: red;
  border: 1px solid black;
}

.positioned {
  position: absolute;
  background: yellow;
  height: 100px;
  top: 30px;
  left: 30px;
z-index: 1000;
}
```

**Comment by BorisOsipov** [comment]
Hi @jinlxz 

>I created a simple test page to check how Condition.visible works

Selenide is Selenium Webdriver based tool. `Condition.visible` works exactly like `element.isDisplayed()` method.

>if an element is covered by another element which has opacity 50%, is the first element visible here?

Webdriver [W3C spec doesn't define](https://www.w3.org/TR/webdriver/#element-displayedness) visibility check steps in details and provides only [reference implementation as recomendation](https://github.com/SeleniumHQ/selenium/blob/trunk/javascript/atoms/dom.js#L460).

If you have any issues or concerns about `isDisplayed()` behaviour it seems better to file an issue in [selenium repo](https://github.com/SeleniumHQ/selenium) or [webdriver spec repo](https://github.com/w3c/webdriver)

**Comment by jinlxz** [comment]
Thank you, @BorisOsipov

**Comment by asolntsev** [comment]
@jinlxz Thank you for a good example, indeed. We can use it for different corner cases in our tests.

It's not even a webdriver problem, it's the browser (at least chrome) who considers this element as visible. 

I tried 3 commands in Developer Console:
> $('#p_hidden').hidden   -> false   // means: not hidden

> getComputedStyle($('#p_hidden')).display   -> 'block'   // means: not hidden

> $('#p_hidden').style.visibility  -> ''   // not sure what it means. According to the spec, ppossible values are "visible|hidden|collapse|initial|inherit"

**Comment by jinlxz** [comment]
@asolntsev that's wierd, in which cases the method `element.isDisplayed()` returns true？

**Comment by asolntsev** [comment]
@jinlxz I don't know exactly.  It should be defined in browser or webdriver specification, I guess.
