### ISSUE TITLE
Window in new tab has different dimension then default

### ISSUE THREAD

**Issue by Hetjavier** [selenide/selenide#1899]
When a new tab is opened the default settings from the window size are no longer applied

## Tell us about your environment
* **Selenide Version 6.6.6
* **Chrome\Firefox\IE Version Chrome 103
* **Browser Driver Version**: 
* **Selenium Version** 4.3.0
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]

Mainly opening a new tab and switching to it gives a smaller browser size

**Comment by asolntsev** [comment]
@Hetjavier   But how exactly do you open the new tab? What method or code do you use?

**Comment by BorisOsipov** [comment]
It is known issue for Chrome in headless mode - new tab has a smaller browser window size

**Comment by asolntsev** [comment]
@Hetjavier I prepared a pull request which makes `Selenide.switchTo().newWindow(WINDOW)` open a new window of size `Configuration.browserSize` (and even at position `Configuration.browserPosition`). But I am still in doubt is it really so much important feature?

**Comment by Hetjavier** [comment]
It's not that important but it is nowhere documented that it is working. As I saw Boris left a comment that this could have influence in own web drivers that get passed, so it can be discarded if it could cause more problems I assume.

**Comment by asolntsev** [comment]
Decided to abandon this feature, see https://github.com/selenide/selenide/pull/1908
