### ISSUE TITLE
Add ability to collect http(s) requests to HAR file without proxy (browserMob)

### ISSUE THREAD

**Issue by admizh** [selenide/selenide#190]
Selenium provide feature to collect PERFORMANCE logs:

``` Java
 DesiredCapabilities capabilities = createCommonCapabilities();
 capabilities.setCapability(CapabilityType.LOGGING_PREFS, getLogPreference());

private LoggingPreferences getLogPreference(){
        LoggingPreferences logPrefs = new LoggingPreferences();
        logPrefs.enable(LogType.BROWSER, Level.ALL);
        logPrefs.enable(LogType.PERFORMANCE, Level.INFO);
        return logPrefs;
    }

And we have ability get all requests from Json Array (Selenium Wired Protocol)

List<LogEntry> perfLogEntries = getWebDriver().manage().logs().get(LogType.PERFORMANCE).getAll();
       JSONArray devToolsLog = new JSONArray();
       for (LogEntry entry : perfLogEntries) {
           JSONObject message = new JSONObject(entry.getMessage());
           JSONObject devToolsMessage = message.getJSONObject("message");
           devToolsLog.put(devToolsMessage);
           entry.getTimestamp();
           Map<String, Object> objectMap = entry.toMap();
           for (String object : objectMap.keySet()) {
               new HarEntry(....)
           }
       }

I am able to get all the requests history. Necessary define the library to convert information to the HAR archive

It would be nice to implement it for selenide
1. get requests histoy from https (browserMob currently does not provide this capability)

```

**Comment by asolntsev** [comment]
@admizh thank you for the suggestion. I will analyze it from Monday.

**Comment by alexandermomot** [comment]
You are genius, admizh :)
No, really! So impressive and simple solution.

**Comment by asolntsev** [comment]
Hi @admizh ! I finally look into your suggestion. Sorry for such a long delay. I could run your code, but now I have few questions:
1. Why do you find it useful? I cannot imagine how to use these logs.
2. Why do you want to convert this information to HAR archive? Why isn't just JSON useful?
3. It only works in Chrome. Firefox returns empty logs. PhantomJS and HtmlUnit throw "UnsupportedCommandException". 

Do you want to just get requests history?
Than I have an idea. Probably we could create own proxy-server (like BrowserMobProxy, but much simpler) that could log all requests. I believe it should be quite simple, and it will work in all browsers. What do you think?

**Comment by leslyarun** [comment]
@asolntsev
Good idea. Simple proxy server which will create HAR file and ability to use corporate proxies

**Comment by asolntsev** [comment]
@leslyarun Let me ask once more, why do you need HAR files? Why isn't just JSON useful?

**Comment by leslyarun** [comment]
Har files can be used in tools like YSlow to get a performance score. @asolntsev

**Comment by rosolko** [comment]
@asolntsev 

Looks like chrome team won't implement this feature. Propose to close this issue for now.

> Status: WontFix (was: Unconfirmed)
> Summary: Add ability to get HAR files for Analysing Web 
> Requests (was: Aad ability to get HAR files for Analysing Web Requests)

**Comment by asolntsev** [comment]
@rosolko No, we still can do a universal solution for all browser. 
1. Catch all requests and responses using Selenide built-in BrowserMobProxy
2. Return a resulting HAR file in the end.

**Comment by admizh** [comment]
Yummy! https://github.com/SeleniumHQ/selenium/pull/7212

**Comment by NScheeren** [comment]
@admizh could you provide a sample on how to use this new functionality for creating a har file?

**Comment by asolntsev** [comment]
@admizh @mrcerbycsy @leslyarun @djtm  @rosolko @NScheeren Hi all! 

This feature was implemented a long time ago. Here is a blog post explaining how to get HAR file:
https://selenide.org/2019/12/18/advent-calendar-network-logs-with-proxy/

**Comment by GayuRenga** [comment]
@admizh  Have you got any solution to get HAR file without using proxy?

**Comment by asolntsev** [comment]
@GayuRenga @admizh FYI I am also thinking on integrating CDP into Selenide. It would allow to easily intercept all network requests without proxy.
