### ISSUE TITLE
Add alias in page initialization by @*FindBy 

### ISSUE THREAD

**Issue by wasder** [selenide/selenide#1903]
## The problem
It would be convenient to be able to set element's alias in page object using special annotation. 

## Details
Something like this:
```java
    @Alias("Phone input")
    @AndroidFindBy(id = "phoneInputText")
    @iOSXCUITFindBy(accessibility = "phoneInputField")
    public SelenideElement phoneInput;
```

**Comment by asolntsev** [comment]
Probably we should name this annotation `@As` because selenide already has method `as` for the same purpose.
