### ISSUE TITLE
org.jsoup:jsoup support removed from this version

### ISSUE THREAD

**Issue by gargpriya01** [selenide/selenide#1905]
<!-Issue- Cannot resolve symbol jsoup.
  
## The problem
Unable to use org.jsoup:jsoup dependency in the latest selenide releases starting from v6.3.3 to 6.6.6

## Details
I am unable to use jsoup dependency from selenium versions 6.3.2

## Tell us about your environment
* **Selenide Version**: Version in range 6.3.3-6.6.6
* **Chrome\Firefox\IE Version**: 103.0.5060.114
* **Browser Driver Version**: 
* **Selenium Version**: version as per selenide
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
import static org.jsoup.helper.HttpConnection.MULTIPART_FORM_DATA;
public UploadFile addMultiPart(File file) {
            reqSpec.setContentType(MULTIPART_FORM_DATA).addMultiPart(CONTROL_NAME_FILE, file, IMAGE_PNG_VALUE);
            return this;
        }

![image](https://user-images.githubusercontent.com/80456413/182337622-eedf85e2-738e-488c-9500-5c65be2e0228.png)

#helprequired #jsoup #java #dependency #fixrequired #versionbug

**Comment by asolntsev** [comment]
@gargpriya01 But it should? Selenide never intended to expose JSoup dependency. 
If you need to use JSoup in your tests, just add dependency `org.jsoup:jsoup:1.15.2` to your project.

P.S. I think JSoup was occasionally exposed in WebDriverManager 5.0.3, and it was fixed in its later versions:

```
[INFO] |  +- com.codeborne:selenide:jar:6.3.2:test
[INFO] |  |  \- com.codeborne:selenide-core:jar:6.3.2:test
[INFO] |  |     +- io.github.bonigarcia:webdrivermanager:jar:5.0.3:test
[INFO] |  |     |  +- com.google.code.gson:gson:jar:2.8.8:test
[INFO] |  |     |  \- org.jsoup:jsoup:jar:1.14.2:test
```

**Comment by gargpriya01** [comment]
Thanks , adding the dependency separately in the required module solved the issue
