### ISSUE TITLE
setValue("") doesn't trigger input events, value in page layout is not empty

### ISSUE THREAD

**Issue by beregeyko** [selenide/selenide#1906]
Selenide version: 6.6.6
Browser: Chrome 102.0.5005.61 
Browser driver: ChromeDriver 103.0.5060.134 
OS: MacOS BigSur 11.6
Framework: react-hook-form

Exists empty input field
1. Set any value using .setValue("abc");
2. Set empty value using .setValue("");

Actual result:
Input is empty, but value in page layout is not empty. As result validation for empty field is not working as expected

![image](https://user-images.githubusercontent.com/31613659/182390073-ef426eb3-f3b7-4597-95f7-10341e2b9f4d.png)

**Comment by asolntsev** [comment]
Yes, it's a well-known problem in webdriver: `WebElement.clean()` doesn't always work in React, Vue etc. applications. 

We created a special plugin for solving this problem: `selenide-clear-with-shortcut`, have you tried it? 
See https://selenide.org/2022/06/08/selenide-6.6.0/

**Comment by beregeyko** [comment]
@asolntsev 
It works as expected with `selenide-clear-with-shortcut`. Thanks a lot. 
Also I faced with the following issue: in case if input has type _number_
`<input class="input_input__p" min="1" name="id" placeholder="Type" type="number" value="">`

input.setValue("123") 
add 0 (zero) in input field inside setValueForTextInput of SetValue.class on `this.clear.clear(driver, element);` action . Is it known issue?

**Comment by asolntsev** [comment]
@beregeyko No, I am not aware of this issue. I tried to reproduce it right now - and I could not. Worked for me.
