### ISSUE TITLE
Add method to getall CSS properties of web element

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#1915]
## The problem
To debug some failing/flaky tests,
I want to log all CSS properties of an element. 

## Tell us about your environment
* **Selenide Version**: 6.7.1

## Code To get the CSS properties:
```javascript
        var cs = getComputedStyle(webElement);
        var len = cs.length;
        var result = {};
        for (var i=0;i<len;i++) {
          var style = cs[i];
          result[style] = cs.getPropertyValue(style);
        }
        return result;
```

**Comment by BorisOsipov** [comment]
> To debug some failing/flaky tests,
> I want to log all CSS properties of an element.

@asolntsev how shall it help to investigate failing/flaky tests? We don't enrich assertion error message with that data.

**Comment by asolntsev** [comment]
@BorisOsipov Well, I am not sure :) 
I had an issue with my work project where Selenium considers an element as invisible, though it was visible. I wanted to log all CSS properties of the element and realized there is no method for this in Selenium/Selenide. That's why I added this method.

But in the end, logging these CSS properties did not help: I still don't understand why `WebElement.isDisplayed()` returns false... :(

**Comment by asolntsev** [comment]
Decided to delete PR: this feature is hardly useful for anybody.
Converted branch to tag feature/#1915-get-css.
