### ISSUE TITLE
Duration.ofSeconds call not working as expected 

### ISSUE THREAD

**Issue by chipsenter** [selenide/selenide#1926]
## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to Selenide).
Tell us what you were trying to do and what happened instead. 

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by chipsenter** [comment]
HI , I believe this wait call is not working as expected ?
Tried the Duration.ofSeconds in multiple tests but none is working as expected, to solve the problem I have to use the not ideal Thread.sleep :(

Would be great to have a solution for this.

Selenide Version: 6.6.4
Chrome Version: 104.0.5112.79
Browser Driver Version: 104.0.5112.79
Selenium Version: 4.1.1
OS Version: macOs Monterey


$$(By.className("ag-checkbox-input")).get(0).should(visible, Duration.ofSeconds(45));
$$(By.className("ag-checkbox-input")).get(0).shouldBe(visible, Duration.ofSeconds(45));

public void checkFirstCheckboxInTableAndValidate() throws InterruptedException { $$(By.className("ag-checkbox-input")).get(0).shouldBe(appear, Duration.ofSeconds(45)); // HelperMethods.wait(20000); int checkboxes = $$(By.className("ag-checkbox-input")).size(); for (int i = 12; i < checkboxes; i++){ $$(By.className("ag-checkbox-input")).get(i).click(); HelperMethods.wait(1000); if($(By.id("my-tasks-actions-mark-complete-btn")).isDisplayed()){ System.out.println("Mark as completed button is visible and enabled"); $(By.id("my-tasks-actions-mark-complete-btn")).shouldBe(visible).shouldBe(enabled); break; } } }

Error is Below.

Element should be be visible {By.className: ag-checkbox-input[0]} Element: '<input aria-label="Press Space to toggle all rows selection (unchecked)" class="ag-input-field-input ag-checkbox-input" id="ag-32-input" ref="eInput" tabindex="-1" type="checkbox" value="on" displayed:false></input>' Actual value: hidden Screenshot: file:/Users/xxx/IdeaProjects/uplm-selenide-automation/build/reports/tests/1660753737302.0.png Page source: file:/Users/xxx/IdeaProjects/uplm-selenide-automation/build/reports/tests/1660753737302.0.html Timeout: 45 s.

If I comment out the thread sleep Test passes fine. ?

Thanks for help.
@asolntsev

**Comment by asolntsev** [comment]
Same question as in https://github.com/selenide/selenide/issues/906
