### ISSUE TITLE
Add caching API into standard API

### ISSUE THREAD

**Issue by groov1kk** [selenide/selenide#1927]
Hello

In [this](https://github.com/selenide/selenide/pull/1894) PR we've started discussing about possibility of implementing caching of elements using the standart API. How do you think, is it worth it?

If so, I could implement this feature.

In my PR I wrote, that  I didn't see it as a global feature. I also have concernes to implement this feature as overloading of standart `$` and `$$` methods, because if additional parameters would be required for these methods, there are a lot of overloaded methods will be present. For example:
```java
$(locator)
$(locator, xxx)
$(localtor, yyy)
$(locator, xxx, yyy)
```
etc.

For me, it is better to implement this feature as a separate methods, such as cache(seleniumSelector), cacheAll(cssSelector), cachex(xpathSelector), etc. For example:
```java
Selenide.cache("class").$("another.class").cacheAll("a")
```

**Comment by BorisOsipov** [comment]
Hello @groov1kk 

>I also have concernes to implement this feature as overloading of standart $ and $$ methods....

Thanks for the feedback. I share your opinion. Overloading is not a great idea.

>possibility of implementing caching of elements using the standart API

To be honest I am not happy about caching feature as standard API. I don't know whether anybody needs to do that. We didn't get any feature requests many years

**Comment by asolntsev** [comment]
@groov1kk @BorisOsipov Sounds like a new `selenide-cache-plugin`? :)

**Comment by BorisOsipov** [comment]
@asolntsev Maybe... Maybe :)
