### ISSUE TITLE
setCapability doesn't work

### ISSUE THREAD

**Issue by vlad8x8** [selenide/selenide#1939]
## The problem
setCapability() doesn't work

## Tell us about your environment
* **Selenide Version**: 6.7.3
* **Chrome Version**: 104.0.5112.102
* **OS Version**: win 10

## Code To Reproduce Issue
`Configuration.browserCapabilities.setCapability(ChromeOptions.CAPABILITY, new ChromeOptions().addArguments("--incognito"))`

## Workaround
``` 
Configuration.browser = Incognito.class.getName();

public static class Incognito extends ChromeDriverFactory {
   public ChromeOptions createCapabilities(Config config, Browser browser, Proxy proxy, File f) {
        return new ChromeOptions().addArguments("--incognito").merge(createCommonCapabilities(config, browser, proxy));
   }
}
```

**Comment by vlad8x8** [comment]
could be related to https://github.com/selenide/selenide/issues/676

**Comment by asolntsev** [comment]
You just need to simplify your code:
```java
Configuration.browserCapabilities = new ChromeOptions().addArguments("--incognito");
```

It was described in release notes:
https://selenide.org/2021/11/24/selenide-6.1.1/#wrapping-browser-capabilities

**Comment by vlad8x8** [comment]
Thanks a lot, Andrei!
