### ISSUE TITLE
Upload file doesn't work when run tests on  remote selenoid server

### ISSUE THREAD

**Issue by AlexChernookov** [selenide/selenide#1940]
## The problem
I have several tests that using upload file, locally they are passed. But when I run these tests on GitLab (using selenoid/vnc-chrome container) they are failed with  UnsupportedCommandException: unknown command: unknown command: session

![image](https://user-images.githubusercontent.com/5630479/188020194-965f132f-bce7-4dad-bebe-3b0ac8d56c2f.png)

Is there any way how to fix this problem?  Google says that this problem was fixed but it's strange 

## Tell us about your environment
* **Selenide Version **: 6.7.3
* **Chrome Version **: 104.0

**Comment by asolntsev** [comment]
It was a known incompatibility between Selenoid and Selenium4. See https://github.com/SeleniumHQ/selenium/issues/9350 and https://github.com/aerokube/selenoid/issues/1079. 
I heard it could be fixed by upgrading Selenoid itself. 
Anyway, it's not a Selenide issue.
