### ISSUE TITLE
Implement deep Shadow DOM selectors

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#1946]
Allow to replace long selector
`$(shadowCss("#inputInInnerShadow", "#shadow-host", "#inner-shadow-host")).click();`
via short selector that pierces Shadow DOM roots without knowing the path through nested shadow roots -  
`$(shadowDeepCss("#inputInInnerShadow")).click()`

**Comment by asolntsev** [comment]
implemented in https://github.com/selenide/selenide/pull/1947, will be released in Selenide 6.8.0
