### ISSUE TITLE
Split package error when using Selenide with Java 17 modules

### ISSUE THREAD

**Issue by dnicholas2001** [selenide/selenide#1962]
## The problem
Using Selenide in a multi module Java 17 project does not compile using maven because of the split package between selenide and selenide.core. For example, the package `com.codeborne.selenide.impl` exists in *both* modules.

## Details
If we depend only on selenide, it helps, but, we do not have access to SelenideConfig. Once we replace selenide maven dependency with selenide-core, we get access to SelenideConfig, but we cannot compile because of the split package issue between both modules.

## Tell us about your environment
* **Selenide Version**:  6.7.0
* **Selenium Version**:  4.4.0
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]
This is the error message in IntelliJ or maven, when attempting to build / compile

java: module com.codeborne.selenide reads package com.codeborne.selenide.logevents from both com.codeborne.selenide.core and com.codeborne.selenide

To reproduce, create a multi module Java project; in 1 module depend on selenide.core, in a second one, depend on selenide, in a third module, write a test that has a dependency on the first 2 modules.

**Comment by asolntsev** [comment]
@dnicholas2001 Yes, we haven't yet started working on modules support. I don't see a big need for this support: nobody complained until today. :) 
But if you submit a pull request, we will accept with a great pleasure. :) 

Could you please describe 
1. why you need modules in test project? Afaik Java9 modules were useful for building small JREs for production (by cutting out all unneeded modules). But why should anyone use it in test automation? 
2. Why do you need to use both `selenide.core` and `selenide` modules? Can't you use just `selenide` which includes all needed dependencies?

**Comment by dnicholas2001** [comment]
@asolntsev Many thanks for confirming on the topic of Java modules support.

**Comment by asolntsev** [comment]
Closing the issue at the moment. We can get back to it when it's really needed.
