### ISSUE TITLE
Restart browser in clean state after each test

### ISSUE THREAD

**Issue by peterwkc85** [selenide/selenide#1981]
Dear Forumer, 
I want to restart the browser after each test but the close() in @AfterEach and open() in @BeforeEach cause invalid session id. What will be the solution. Please help. 

## The problem
Dear Forumer, 
I want to restart the browser after each test but the close() in @AfterEach and open() in @BeforeEach cause invalid session id. What will be the solution. Please help. 

## Tell us about your environment
* **Selenide Version**: 
* **Chrome\Firefox\IE Version**:  Chrome
* **Browser Driver Version**:  
* **Selenium Version**: 4
* **OS Version**: Window 10 

## Code To Reproduce Issue [ Good To Have ]

```java
@BeforeEach
public void beforeEach() {
  open();
}

@AfterEach
public void afterEach() {
  close();
}
```

**Comment by asolntsev** [comment]
@peterwkc85 
1. What Selenide version are you using?
2. What is method `close()`? Class `Selenide` doesn't have method `close()`. It has only `closeWebDriver()` and `closeWindow()`. Which one are you using?
3. What is "invalid session id" error? Can you attach full error message with stack trace?

P.S. Anyway, there is `com.codeborne.selenide.junit5.BrowserStrategyExtension` for re-opening browser before every test. But usually I don't recommend this approach because it makes tests much slower. Instead, I recommend to open an empty page and clear cookies&localStorage&sessionStorage before every test.

**Comment by peterwkc85** [comment]
I tried to clear cookies but it doesn't logout the session. 
 WebDriverRunner.getWebDriver().manage().deleteAllCookies();
 WebDriverRunner.getWebDriver().navigate().refresh();

Can you provide a better solution?

**Comment by asolntsev** [comment]
@peterwkc85 Hi, did you see my questions in the previous comment?

To clear session storage: `Selenide.getSessionStorage().clear();`.
See https://selenide.org/2021/02/11/selenide-5.18.1/

**Comment by peterwkc85** [comment]
Answers to the Questions
1. Selenide version 6
2. I dont't know
3. I don't know

1. Regarding the clearSessionStorage, there is no such method available. 
2. There is email cachel in the input when i open the next test which is need to clear the text box, What should i do?

**Comment by asolntsev** [comment]
@peterwkc85 Sorry, but how can anybody help you if you say "it causes invalid session id", but cannot explain what means "invalid session id"? You complain about method `close()` that does not exist, and cannot explain what method is this.

I would like to help, but don't have enough information. :(

**Comment by peterwkc85** [comment]
You can ignore the previous questions about invalid session id and close() method. 
Please help on the clear() method now as it is cannot clear the input text box.

**Comment by asolntsev** [comment]
@peterwkc85 I feel like you don't respect other's time and effort. :(

About $.clear() - try `selenide-clear-with-shortcut`, see https://selenide.org/2022/06/08/selenide-6.6.0/.
