### ISSUE TITLE
setValue() ignores space

### ISSUE THREAD

**Issue by Borman010884** [selenide/selenide#1982]
$(element).setValue() ignores space

Selenide 6.9.0, Версия 105.0.5195.125, (arm64), Selenium 4.5.0, mac os monterey
![image](https://user-images.githubusercontent.com/14129632/194825460-3c040a29-0dea-4246-a846-6ecac6964a76.png)

**Comment by asolntsev** [comment]
@Borman010884 How can I reproduce the problem?
I tried this code, and it works:

```java
  @Test
  void spaceWorks() {
    open("https://duckduckgo.com");
    $(By.name("q")).setValue("Hello world");
    $(By.name("q")).shouldHave(value("Hello world"));
  }
```

**Comment by asolntsev** [comment]
@Borman010884 I think it's rather a feature (or bug) of your application.
