### ISSUE TITLE
ThreadGuard for parallel testing

### ISSUE THREAD

**Issue by redhell** [selenide/selenide#1993]
Hi,

does Selenide use the ThreadGuard feature of Selenium? (https://www.selenium.dev/documentation/webdriver/support_features/thread_guard/)

If not does it make sense to implement it for WebDriver and/or remoteWebDriver?

**Comment by asolntsev** [comment]
@redhell No, we don't use `ThreadGuard` in Selenide. Thank you for sharing, I didn't even know about this feature. :)

But we probably don't need `ThreadGuard` much. Selenide holds browsers in ThreadLocal variable, so users are guaranteed to get different browsers in different tests (until they override default Selenide behaviour with methods `setWebDriver()` etc.).
