### ISSUE TITLE
Selenide Chrome Firefox Edge Web Driver Manager

### ISSUE THREAD

**Issue by peterwkc85** [selenide/selenide#1994]
## The problem
As the default `open()` method called chromeDriver, is there any method to customize this to support firefox and edge browser?

## Details
Want to do cross browser testing using chromeDriver and FirefoxDriver supply from commandline value. 

## Tell us about your environment
* **Selenide Version**:  6.6
* **Chrome\Firefox\IE Version**:  Chrome 106
* **Browser Driver Version**:  
* **Selenium Version**:  4
* **OS Version**:  Win 10

## Code To Reproduce Issue [ Good To Have ]
None, Looking for recommendation

**Comment by soydivision** [comment]
AFAIK we use `-Dselenide.browser=edge` to set a browser using system prop.

**Comment by peterwkc85** [comment]
How to read the properties from commandline and set the corresponding driver?

**Comment by soydivision** [comment]
> How to read the properties from commandline and set the corresponding driver?

I usually use Maven so in my case `mvn -Dselenide.browser=firefox clean test`. Also you can change the browser in your code ```
//(before open() method)
Configuration.browser = "firefox";
```
which is less flexible. You can refer to [quick guide](https://github.com/soydivision/Selenide-quick-FAQ), although it needs a few updates, generally you should be fine.

**Comment by peterwkc85** [comment]
I tried with this Configuration.browser = System.getProperty("browser"); from -Dbrowser=firefox test but it throws exception like below: 

SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:157)

**Comment by soydivision** [comment]
> I tried with this Configuration.browser = System.getProperty("browser"); from -Dbrowser=firefox test but it throws exception like below:
> 
> SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:565) at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:242) at org.openqa.selenium.remote.RemoteWebDriver.(RemoteWebDriver.java:157)
> 
> PS: I can start Chrome session using the method above but not firefox and edge browser.

Are you using any sort of builder e.g. maven, ant, gradle? What you've written above makes no sense. You don't need to to pass a browser value from command line, all you have to do is just set it using `-Dselenide.browser=firefox`. Or inside the code before the open() method you can use this line of code `Configuration.browser = "edge";`. Again. Selenide is not Selenium. Just replace `-Dbrowser=firefox` to `-Dselenide.browser=firefox` in your CLI command.

**Comment by asolntsev** [comment]
The answer is given in wiki: https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver

As mentioned above, you need to set system property `selenide.browser` to `firefox`. OR you can just add this line in the beginning of your tests: `Configuration.browser = "firefox";`.

I see you did it; now you are getting `SessionNotCreatedException`. 
And this is not a Selenide problem. You need to read all your logs and find out the reason why Firefox driver failed to start. There are many possible reasons, e.g. Firefox browser is not installed on that machine.
