### ISSUE TITLE
java: cannot access com.browserup.bup.filters.RequestFilter   class file for com.browserup.bup.filters.RequestFilter not found

### ISSUE THREAD

**Issue by artur-severinov** [selenide/selenide#1998]
## The problem
Got an error while building project
Error:(24, 44) java: cannot access com.browserup.bup.filters.RequestFilter
  class file for com.browserup.bup.filters.RequestFilter not found

## Details

I'm working with VPN by SBER

## Tell us about your environment
* **Selenide Version**: 6.9.0
* **Chrome\Firefox\IE Version**: Chrome
* **Browser Driver Version**: 104
* **Selenium Version**: 
* **OS Version**: MacOS

## Code To Reproduce Issue [ Good To Have ]
    public void openPage(String url) {
        open(url);
        getSelenideProxy().responseMocker().mockText("cik-mock",
                urlStartsWith(GET, "https://gf-enigma-ift.delta.sbrf.ru/rmkib.tariffs/api/v1/tariffs/divisionStructure"),
                () -> "{\"success\":true,\"body\":{\"code\":\"CIB\",\"value\":\"ДКК\",\"type\":\"CA\",\"usersDivision\":true}}");
    }

**Comment by asolntsev** [comment]
@artur-severinov  Are you using `com.codeborne:selenide:6.9.0` or `com.codeborne:selenide-proxy:6.9.0`?

**Comment by artur-severinov** [comment]
Do You mean this?
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>6.9.0</version>
        </dependency>

**Comment by artur-severinov** [comment]
i found in my nexus this dependency

<dependency>
  <groupId>com.codeborne</groupId>
  <artifactId>selenide-proxy</artifactId>
  <version>6.2.1</version>
</dependency>

Will it help me with my problem? Or i need 6.9.0 version only?

**Comment by asolntsev** [comment]
@artur-severinov yes, you need dependency `com.codeborne:selenide-proxy` of any version.  I recommend the latest 6.9.0, but 6.2.1 is also acceptable.
