### ISSUE TITLE
click() method should be chainable, just like other SelenideElement methods

### ISSUE THREAD

**Issue by tenor-dev** [selenide/selenide#2007]
It would be convenient to chain click with other actions on the element:

`$("element").click().pressEnter()`

**Comment by BorisOsipov** [comment]
@tenor-dev it is not possible.

`SelenideElement extends WebElement` and click comes with `void click()` signature - we can't change return type.

**Comment by asolntsev** [comment]
@BorisOsipov By the way, we still can change signature of `void click(ClickOptions clickOption)`

**Comment by BorisOsipov** [comment]
@asolntsev sure 🙃. But I am not sure that someone wants to write smth like that: 

`$("element").click(ClickOptions.usingDefaultMethod()).pressEnter()`

**Comment by asolntsev** [comment]
@BorisOsipov Yes, I don't think so. :) 
But anyway, it's easy to make `$.click(options)` chainable - why not.

**Comment by amuthansakthivel** [comment]
@BorisOsipov @asolntsev - This will impact the Appium Code. 

We are extending AppiumClick to Click - 

https://github.com/selenide/selenide-appium/actions/runs/3370004485/jobs/5649131876
