### ISSUE TITLE
Selenium's method connectionTimeout(Duration) is called but doesn't exist

### ISSUE THREAD

**Issue by chklump** [selenide/selenide#2013]
## The problem
Just using the `open("/url")`-method crashes with
```
java.lang.NoSuchMethodError: 'org.openqa.selenium.remote.http.ClientConfig org.openqa.selenium.remote.http.ClientConfig.connectionTimeout(java.time.Duration)'
```

## Details
With commit e11f2b40499ba0a64f4acc541ee038af771094c5 the connectionTimout became configurable. For this, the Selenium-method `ClientConfig.connectionTimeout(java.time.Duration)` is called (see [SelenideNettyClientFactory.java](https://github.com/selenide/selenide/commit/e11f2b40499ba0a64f4acc541ee038af771094c5#diff-f1bb2b8f1313a09d9715e1d98668229453f3b2fa9eda20be8a904c6e078da47b) line 23).

However, the this method does no longer exist in Selenium. It was removed from Selenium with commit [1990a43a745669e87acb39331a0742979ecc728a](https://github.com/SeleniumHQ/selenium/commit/1990a43a745669e87acb39331a0742979ecc728a).

Downgrading to Selenide version 6.8.1 solves the problem for me.

## Tell us about your environment
* **Selenide Version**: 6.9.0
* **Chrome\Firefox\IE Version**: Firefox 106.0.5
* **Browser Driver Version**: 0.32.0
* **Selenium Version**: 4.5.0
* **OS Version**: Windows 10 21H2

## Code To Reproduce Issue [ Good To Have ]
`open("/url")`

**Comment by asolntsev** [comment]
@chklump Apparently, you are using too old version of Selenium. 
This method was later restored in commit https://github.com/SeleniumHQ/selenium/commit/9b012df78dbbfd84d8fef06308f40fbf6a29455b

**Comment by chklump** [comment]
Ah, you're right. I've been using `spring-boot-starter-parent` as a maven parent-pom and this pinned the selenium-version to 4.1.4. I wasn't aware of that.

Thanks for clarifying and sorry for bothering.
