### ISSUE TITLE
BasicAuthCredentials and Basic authorization stopped working

### ISSUE THREAD

**Issue by tronstone** [selenide/selenide#2015]
## The problem
I'm trying to use the basic authorization for the site instead of the deprecated one. Not authorized.

## Details
The next one works correctly: `BasicAuthCredentials(String login, String password)`.
The following construction does not work: `BasicAuthCredentials(String domain, String login, String password)`.

Trying to pass:

```java
Selenide.open(**pageURL**, **authenticationType**, **credentials**)) - where
**pageURL** is https://cfm-dev.taspre-phx.apps.boeing.com/
**authenticationType** is AuthenticationType.BASIC
**credentials** is new BasicAuthCredentials(
                "cfm-dev.taspre-phx.apps.boeing.com",
                "username",
                "password"
)
```

## Tell us about your environment
* **Selenide Version**: 6.9.0

**Comment by asolntsev** [comment]
@tronstone Do you use Selenide proxy? 
Are you sure the domain that requires authentication is the same that is in url? 
What browser do you use?

At least this example works with Selenide 6.9.0:
```java
  @Test
  void watchThis() {
      Configuration.proxyEnabled = true;
      open("https://the-internet.herokuapp.com/basic_auth", BASIC,
      new BasicAuthCredentials("the-internet.herokuapp.com", "admin", "admin"));
      $("#content").shouldHave(partialText("Congratulations! You must have the proper credentials."));
  }
```

**Comment by tronstone** [comment]
@asolntsev I don't use a proxy. All I need is to go to the site with basic authorization. Previously, I used the next constructor for this:
```new BasicAuthCredentials("username", "password")``` - but now it is deprecated.
And now the next method:
```open(String relativeOrAbsoluteUrl, AuthenticationType authenticationType, Credentials credentials)``` - should use a new constructor with a domain name for **Credentials**, although it is not needed.

**Comment by asolntsev** [comment]
@tronstone Now I understand. Yes, domain part is rather important when you use proxy (otherwise proxy would send authorization header to all domain, not only to the needed one). 

I confirm we have a bug that can be reproduced with this code:

```java
  @Test
  void oldWay() {
    // Test passes.
    // Opens url "https://admin:admin@the-internet.herokuapp.com/basic_auth"
    open("https://the-internet.herokuapp.com/basic_auth", BASIC,
      new BasicAuthCredentials("admin", "admin"));
    $("#content").shouldHave(partialText("Congratulations! You must have the proper credentials."));
  }

  @Test
  void newWay() {
    // Test doesn't pass.
    // Opens url "https://the-internet.herokuapp.com%5Cadmin:admin@the-internet.herokuapp.com/basic_auth"
    open("https://the-internet.herokuapp.com/basic_auth", BASIC,
      new BasicAuthCredentials("the-internet.herokuapp.com", "admin", "admin"));
    $("#content").shouldHave(partialText("Congratulations! You must have the proper credentials."));
  }
```

**Comment by tronstone** [comment]
@asolntsev Maybe just return a deprecated constructor? Let it be overloaded. Those who need a domain for proxying will use the new constructor. Since adding an empty line looks like a crutch.

**Comment by asolntsev** [comment]
@tronstone Yes, it seems a totally valid idea for "non-proxy" users. The domain is not really needed when adding BasicAuth credentials to url.

But in case of "proxy" users, the domain is essential for security. If users continue using the old constructor, they don't even know that they need to add domain to avoid sending credentials to 3rd party services. 

But yes, probably I will just un-deprecate the old constructor and add security warning to its javadoc.

**Comment by tronstone** [comment]
@asolntsev Thanks a lot)
