### ISSUE TITLE
Define ScreenShoot folder for TestNG

### ISSUE THREAD

**Issue by vlad-velichko** [selenide/selenide#2034]
## The problem
JUnit has a feature to define folder for screenshots. TestNG doesn't have it.
https://ru.selenide.org/documentation/screenshots.html

**Comment by asolntsev** [comment]
@vlad-velichko It's not really needed.
First of all, you generally should not need to change this folder at all.
Second, even if you really need, you can just change `Configuration.reportsFolder = folderWithScreenshots;`. 
JUnit listeners also do it.
