### ISSUE TITLE
No screenshots in custom SelenideDriver using non-Selenide asserts

### ISSUE THREAD

**Issue by vlad-velichko** [selenide/selenide#2040]
Code to reproduce:
```
@Listeners({ScreenShooter.class})
public class Main {
    @Test
    public void main() {
        SelenideDriver driver = new SelenideDriver(new SelenideConfig());
        driver.open("https://google.com");
        assertTrue(false);
    }
}
```
looks like it's not making screenshots because `com.codeborne.selenide.Screenshots` is using default static driver only `driver()`

**Comment by BorisOsipov** [comment]
Good catch. 
For me `Screenshots` as static thing should known nothing about screenshots from non-static SelenideDriver. But now it is coupled with `ScreenShotLaboratory` that's why we have such strange things.

**Comment by asolntsev** [comment]
@vlad-velichko Yes, but I don't see how it could be possible. `ScreenShooter` listener cannot get access to your  local variable `driver`.

**Comment by vlad-velichko** [comment]
@asolntsev can ScreenShooter get a list of all started drivers and make screenshots from all? It would be very nice to get a kinda environment screenshot

**Comment by asolntsev** [comment]
I don't understand why it's needed. The wish to have access to "current" driver(s) is contradictory to the wish to create your own `SelenideDriver` instance. The initial assumption was that `SelenideDriver ` is needed for people who want to explicitly manage the driver and avoid any kind of "magic" (ThreadLocals, static methods etc.)

@vlad-velichko **Why do you need to create `SelenideDriver` instance manually?**

**Comment by vlad-velichko** [comment]
I test softphone. I need 2-4 independent browser windows at the same time. Test looks like
```
    Given user A is logged in
    And user B is logged in
    When user A calls user B
    Then user B is getting incoming call
    ...
```

**Comment by vlad-velichko** [comment]
If this bug is not possible to fix, then would be nice to have at least a comment about limitations in ScreenShooter

**Comment by asolntsev** [comment]
@vlad-velichko Maybe it's easier to use 2-4 browsers using method `using`. :) 

See
https://selenide.org/2019/10/16/selenide-5.4.0/#add-method-using

**Comment by asolntsev** [comment]
> If this bug is not possible to fix, then would be nice to have at least a comment about limitations in ScreenShooter

Thank you for the suggestion. I added comment to ScreenShooter: https://github.com/selenide/selenide/commit/23c6936c69adcfdfc36532b3da18205816b663f8
