### ISSUE TITLE
Feature request: Provide a fluent method to validate current URL with an expected one before doing any operations on that page. 

### ISSUE THREAD

**Issue by PramodKumarYadav** [selenide/selenide#2048]
## Feature request
A generic approach to do fluent method chaining is to call the next Page class from the current class. To give an example, 
In login page after user has given username, password and clicked on login button, we would add a method as below to demonstrate that the Home page should have happened and any other operation that we want to do can be now done from the home page instance.  

```
public HomePage redirectToHomePage(){
    return new HomePage();
}
```

One problem with the above method is, it assumes that the HomePage() would be ready and available to do next steps. What if the password was wrong or another error stopped the login process to complete and thus never navigates to the page to Home page. 

I would like to assert that "after click" the url() indeed changed to the desired home-page-url before doing any more actions on the methods of HomePage class itself.  

One way, I can do this is:
```
public HomePage redirectToHomePage(){
    assertEquals(config.get("HOME_PAGE_URL"), url());
    return new HomePage();
}
```

OR

```
public HomePage redirectToHomePage(){
    assertTrue(url().contains(config.get("HOME_PAGE_URL"));
    return new HomePage();
}
```

Problem with first approach is, its not fluent and with all other fluent assertions in Selenide this sticks out badly and breaks the readability. Only good thing is if there are any mismatches, it would clearly show what the expected URL was and what the actual URL is.

Problem with second assertion is also the same that it is not a fluent assertion as other selenide assertions (although reads a little better than the first one. The bigger problem is in case of mismatches, it would only show comparison failure as below, which is not too useful. 

```
org.opentest4j.AssertionFailedError: 
Expected :false
Actual   :true
```

## Proposed Solution
Since we already have Junit5 dependency in Selenide, could it be an option to create a method named 

`urlShouldBe(String expectedUrl);`
which compares the actual url() value with this expectedUrl and in case of failure give a descriptive error. 

In terms of usage, this would read as below.

```
public HomePage redirectToHomePage(){
    urlShouldBe(config.get("HOME_PAGE_URL"));
    return new HomePage();
}
```

## Tell us about your environment
Environment is NA - since this is a new feature request. 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.
Not a bug but a feature request. 

Note: If you find it okay, I can create a pull request to create this method? If there is another way in which the same can be done, I will be happy to hear.

**Comment by BorisOsipov** [comment]
@PramodKumarYadav we already have such asserts:

```
import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.webdriver;
import static com.codeborne.selenide.WebDriverConditions.url;

    @Test
void foo() {
    open("https://github.com/");
    webdriver().shouldHave(url("https://gitlab.com/"));
}
```
with a good error message:
```
webdriver should have url https://gitlab.com/
Actual value: https://github.com/
Screenshot: file:/C:/Users/bo/IdeaProjects/demo/build/reports/tests/1670145807143.0.png
Page source: file:/C:/Users/bo/IdeaProjects/demo/build/reports/tests/1670145807143.0.html
Timeout: 4 s.
```
can you try?

**Comment by PramodKumarYadav** [comment]
Thanks for the information @BorisOsipov. This is exactly what I need 😊. This request can be closed. Cheers!
