### ISSUE TITLE
Add a delay for auto-closing of alerts

### ISSUE THREAD

**Issue by tenor-dev** [selenide/selenide#2054]
## The problem
Selenide auto-closes alerts and similar dialogs if they prevent making a screenshot when a test fails.
The dialogs often contain the reason why the test fails, but Selenide makes it impossible to see it.

## Proposed solution
The solution would be to extract the alert/dialog text it, print it to log, explaining that it is being closed automatically and then add a slight delay before closing it, so that people running the tests in front of them have a chance to see it.

**Comment by BorisOsipov** [comment]
Hi @tenor-dev 

>Selenide auto-closes alerts and similar dialogs if they prevent making a screenshot when a test fails.

No, selenide doesn't autoclose alerts. They are autoclosed by browser driver because we set `unhandledPromptBehavior` to `accept`. Alerts\promts are autoclosed  _before any_ interaction with browser not only before screenshots.

**Comment by tenor-dev** [comment]
@BorisOsipov is it possible to disable this in Selenide?

**Comment by BorisOsipov** [comment]
>Maybe ACCEPT_AND_NOTIFY should be the default? Assuming this will log what was inside

NOTIFY means "throw Exception" - not sure that all users should suffer from unexpected alerts and handle them mannualy all the time.
Also alert text for such exception is optional and e.g. Firefox doesnt provide it in error message.

If you want work with alerts please use existing API:
`Selenide.switchTo().alert().getText()`

**Comment by tenor-dev** [comment]
@BorisOsipov so are you saying that there is no way of at least logging text of auto-closed alerts by default?

This hides important errors, that can be difficult to debug because you don't know that this has happened on your CI server.

**Comment by asolntsev** [comment]
@tenor-dev It's an easy solution for your project: just set `Configuration.browserCapabilities.setCapability(UNHANDLED_PROMPT_BEHAVIOUR, ACCEPT_AND_NOTIFY);`. Let the exception flow.

@BorisOsipov Probably it's still a good idea to enable `ACCEPT_AND_NOTIFY` by default? Yes, it breaks backward compatibility, but it's better to solve technical problems and JS errors (which probably cause alerts) than ignoring them silently.

**Comment by asolntsev** [comment]
> Also alert text for such exception is optional and e.g. Firefox doesnt provide it in error message.

@BorisOsipov 
I just checked: both Chrome and Firefox throws an exception with alert text:
```java
UnhandledAlertException: unexpected alert open: {Alert text : Are you sure, Greg?} // chrome
UnhandledAlertException: Accepted user prompt dialog: Are you sure, Greg?: // firefox
UnhandledAlertException: unexpected alert open: {Alert text : Are you sure, Greg?}  // edge
UnhandledAlertException: : Are you sure, Greg? // safari
```

**Comment by BorisOsipov** [comment]
@asolntsev 
>I just checked: both Chrome and Firefox throws an exception with alert text:

that's nice.
