### ISSUE TITLE
$.select* should not fire change event if the value is not changed

### ISSUE THREAD

**Issue by cocorossello** [selenide/selenide#2062]
## The problem
Since selenide 6.10.0, change event is always fired when $.select* is invoked. It should not fire if the value is unchanged

## Tell us about your environment
* **Selenide Version**:  6.10.0
* **Chrome\Firefox\IE Version**: Chrome 108

## Code To Reproduce Issue [ Good To Have ]
I'm submitting a PR with tests in place

**Comment by cocorossello** [comment]
#2063

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/2063
