### ISSUE TITLE
Reported screenshot PNG file with too restrictive permissions

### ISSUE THREAD

**Issue by ivy-rew** [selenide/selenide#2081]
## Unreadable PNG files in reports
I have a failing selenide test, it writes HTML and PNG files for this as expected.
While the HTML file can be inspected, the PNG file is unreadable due to missing file permissions.
It seem like by default the PNG file has only user permissions granted. 
To me this makes no sense, why should we have other permissions than on the HTML files?
```
la -la
total 760
drwxr-xr-x 2 root root   4096 Dec 19 10:50 .
drwxr-xr-x 3 root root   4096 Dec 19 10:24 ..
-rw-r--r-- 1 root root 185070 Dec 19 10:24 1671441847908.0.html
-rw------- 1 root root 300295 Dec 19 10:24 1671441847908.0.png
-rw-r--r-- 1 root root   6929 Dec 19 10:38 1671442715640.0.html
-rw------- 1 root root  81180 Dec 19 10:38 1671442715640.0.png
-rw-r--r-- 1 root root   6929 Dec 19 10:47 1671443241881.0.html
-rw------- 1 root root  82825 Dec 19 10:47 1671443241881.0.png
-rw-r--r-- 1 root root   6929 Dec 19 10:50 1671443405071.0.html
-rw------- 1 root root  82496 Dec 19 10:50 1671443405071.0.png
```

This circumstance brings our build-pipeline to fail, as the PNG file can't be archived by our (Jenkins) job.

## environment
* **Selenide Version**:  6.10.3
* **Chrome\Firefox\IE Version**:  Firefox 108.0.1
* **OS Version**: Ubuntu 22.04

**Comment by ivy-rew** [comment]
Thanks for your investigation @BorisOsipov .

I agree that streamlining the user that runs maven with the jenkins job would help to circumvent that issue.
Here I can't do that easily, due to the given docker environment I'm executing in. 

Still it is a fact, that the created HTML file in the configured selenide-reports directory has other posix permissions than the PNG. And I don't get the idea behind not giving access to that PNG for group/global by default.

So if we run this test:
```
@Test
  void foo() {
    Selenide.open("https://www.google.com/");
    $(By.name("notMyForm")).sendKeys("me@axonivy.com");
  }
```

The output is:
![html-vs-png](https://user-images.githubusercontent.com/15085693/208465863-179ec211-76b3-4ec2-9f66-e0c8ae2e7b39.png)

Isn't that a bug?

**Comment by asolntsev** [comment]
@ivy-rew Wow, it was unexpected for me. :)
Yes, ".html" and ".png" files have different permissions. But 
1. does it really causes any problems?
2. we can fix it, but what is the right permission: `-rw-r--r--` or `-rw-------`?

**Comment by ivy-rew** [comment]
Hi @asolntsev 

1. yes, it causes real world issues here. The fact that only the user that created the file can read it causes, makes these files unreadable for other users running on the same system. So I can't design a test that by intention runs Maven with a different user and read/collect the test-results with another one.
2. To me, the naturally correct permissions for the png files should be `-rw-r--r--` . The other 'user-only' -rw- permissions only make sense in rare circumstances. E.g. my `~/.ssh` directory may contains highly sensible files that must be protected like that. But here we are talking about test-reports, which are by nature designed to be viewed by everyone. In my case, I'm eveng going to archive them in my pipeline, so making them visible to everyone who can touch access our jenkins web frontend.

**Comment by BorisOsipov** [comment]
@ivy-rew Thank you for detailed explanation.
The root cause of the issue is that Selenium creates screenshot as temporary file (`/tmp/foobar123123123.png`) and it is legit to create is with `-rw-------` permission – it is security based behavior (actually it comes from java std lib).
We only move tmp file to our report dir. Probably we should get rid of taking screenshots as file and write it directly to report folder.

**Comment by asolntsev** [comment]
@ivy-rew Please review PR https://github.com/selenide/selenide/pull/2084
