### ISSUE TITLE
Unable to download files greather than 64Mb through PROXY

### ISSUE THREAD

**Issue by ilya-corp** [selenide/selenide#2082]
## The problem
I have enabled internal proxy in my project by setting up global property `Configuration.proxyEnabled = true`.
During attempt of downloading files using method `FOLDER` or `PROXY` I receiving errors in the console log and can't download file.
The problem related to the limit in the built-in proxy server https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/proxy/BrowserUpProxyServerUnlimited.java line 17

My expectation is following:
Option 1. Change limit by default to 4Gbytes, provide ability to change this limit by Configuration.proxyRequestMaxLength
Option 2. Hardcode the most max size for this parameter
Option 3. Provide ability to change parameter by user by setup Configuration.proxyRequestMaxLength and leave 64Mb as default value

## Details
It's necessary to change limit
Download code snippet example:
```java
Configuration.proxyEnabled = true;
File downloadedFile = homePage.accessMethodsPageBlock.downloadThinClientX64ForWindowsButton.download(
 DownloadOptions.using(FOLDER)
    .withIncrementTimeout(Duration.ofMillis(6000))
    .withFilter(FileFilters.withExtension("zip"))
);
```

The console log example:
```
LittleProxy-0-ProxyToServerWorker-3] ERROR org.littleshoot.proxy.impl.ProxyToServerConnection - (AWAITING_INITIAL) [id: 0xaf349334, L:/10.168.70.228:50721 ! R:[downloads.scssdsd.ru/141.101.185.103:443](http://downloads.scssdsd.ru/141.101.185.103:443)]: Caught an exception on ProxyToServerConnection
io.netty.handler.codec.http.TooLongHttpContentException: Response entity too large: DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
```

## Tell us about your environment
* **Selenide Version**: 6.10.3
* **Chrome\Firefox\IE Version**: Chrome 108, FireFox latest
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: Windows 10

## Code To Reproduce Issue

```java
Configuration.proxyEnabled = true;
File downloadedFile = homePage.accessMethodsPageBlock.downloadThinClientX64ForWindowsButton.download(
 DownloadOptions.using(FOLDER)
    .withIncrementTimeout(Duration.ofMillis(6000))
    .withFilter(FileFilters.withExtension("zip"))
);
```

**Comment by asolntsev** [comment]
@ilya-corp We can increase max payload size from 64Mb to `Integer.MAX_VALUE` (which is 2GB). Not more. BrowserUpProxy doesn't allow more than 2GB.

BUT

I guess you will get OutOfMemory error in this case. Proxy will need to store the whole 4GB file in memory. Are you sure you really want it?

**Comment by asolntsev** [comment]
@ilya-corp I tried to increase this setting in proxy, but it still cannot download 4GB file (I tried both BrowserUpProxy and [MockServer](https://www.mock-server.com/mock_server/getting_started.html)). In case of a bit smaller files (1GB), they can download the file, but very slowly (much slower than without the proxy). 

So currently I don't know a good solution for downloading 4GB files through proxy. _If anyone knows about it, please share your knowledge._

**Comment by ilya-corp** [comment]
Typically file size of our project is 115-1500 Mbytes. 
Also I think, that proxy should not be global, we need to launch independent proxy for every webdriver. For example, I need to download small 5Mb file by proxy in 1 test of 500, and I need to download large 5Gb files without proxy (using FOLDER method) in 10 tests of 500. Another 30 tests should be executed from proxy to analyze outgoing requests and all another tests may be executed without proxy.

So, the code like following will be good:
Selenide.enableProxy();
open("https://mysite.ru)

**Comment by asolntsev** [comment]
@ilya-corp Let me ask. If `FOLDER` method works for you, why do you want to download that one file with `PROXY`?

**Comment by ilya-corp** [comment]
Andrey, it's very simple.
In the personal cabinet of out project we can download files (apps, reports, orders etc.) using FOLDER method - it's enough permissions to have Bearer tokens in the Local storage. 
However, we also providing ability to download large bases (backups of financial data of bloody 1C) to our users. But those large files stored in the different place (not in the personal cabinet) and requires Basic authorization. Users must to enter credentials (credentials may be different to personal cabinet) before downloading. 
I know that it's possible to use combinations of creds in the URL and I have working scenario for this. But it looks like some bycicle. I want to use PROXY to configure automatic headers for specific domains.

For example, domain of cabinet is https://mycompany.com
Domain for databases server is https://largefiles.mycompany.com
In the headers I want to use Authorization with Base64 combination of login:password. 

Hope it have sense.
Another argument. I can NOT use proxy in the project if I need to execute some test with downloading of large files (>4Mb).  It's because proxy setting is global now. It's because using proxy brings tests with requests larger 4Mb.

So, my suggestion is to use independent proxies for every driver and made configurable tp limit of proxy size (globally is also acceptable).

If you need any details, we can discuss it in the Telegram.

**Comment by asolntsev** [comment]
@ilya-corp I have few suggestions:
1. Let's set the default limit in Selenide as large as possible: `Integer.MAX_VALUE` (I don't want to introduce any new setting here. I guess nobody really needs it.)
2. But I see that downloading of large files through proxy works badly. I tried to debug it, but failed to find how to improve it.
3. That's why I don't recommend you to download files via proxy. 
4. I didn't understand from your explanation why your test cannot download files exactly as end-users do it. End-users don't set headers, right? They just login and use (de-facto) `FOLDER` mode. Why can't you do the same?
5. Anyway, I think you can download your files with `FOLDER` method like this:

```java
  open("https://largefiles.mycompany.com/favicon.ico");
  localStorage().setItem("whatever auth token you need", "whatever secret you need");
  open("https://largefiles.mycompany.com/");
  File largeFile = $("xx").download(FOLDER);
```

**Comment by ilya-corp** [comment]
@asolntsev 
1. Sure, please do that. Thansks in advance.
2. It's bad, but not critical.
3. Ok, got it
4. I have 2 types of downloads. a) Click something and get file. The FOLDER method is ideal for that and it works. b) Click something, ENTER LOGIN AND PASSWORD INTO SYSTEM BROWSER SPECIFIC WINDOW (Basic Auth) and download file.
I can not enter login-password into this system window, I must avoid appearing of it. I can avoid it I will open url with specific header Authorization, but by default browser don't send it (and don't know creds).

And the cherry on the pie. If I will use proxy in some test (it have no matter for the purpose), I will have provlem with downloading files ot TYPE A (via FOLDER method). It's because all request will be processed and failed by proxy. I have no ability to enable proxy for test 1 and disable proxy for tests, which using downloading by FOLDER.

Enabling and disabling proxy now is global setting. In multithreadig changing of Configuration.proxyEnabled may affect different tests and bring to unstable results. It's because I am requesting independent proxy for every driver.

**Comment by ilya-corp** [comment]
Example of Basic auth window
https://i.stack.imgur.com/2GvZv.png
