### ISSUE TITLE
Feature idea : add open method, which always re-opens the page

### ISSUE THREAD

**Issue by Panwo** [selenide/selenide#2086]
It would be great to have an open page method, which always re-opens an URL even if it is already opened. 
Currently, a workaround is to open and refresh which is not quite convenient. I suppose the use case is quite common, - changes made to the page are saved after calling open() method without a refresh, which is a bit confusing IMHO. 

Use case for suggested open method :

```java
@BeforeEach
open(URL)

@Test
modify page, assert

@Test
modify page, assert

....
```

Thanks

**Comment by asolntsev** [comment]
@Panwo Probably I didn't understand your question, but method `open(URL)` does exactly what you want: it opens given URL even if it was already opened.

**Comment by Panwo** [comment]
@asolntsev 
As I understand, when the same url is used in BeforeEachMethod, - page state remains unchanged before each new test execution, I expect that result of open method would be the same as clicking within a browser URL window and typing enter (same URL, but the page is refreshed)

![изображение](https://user-images.githubusercontent.com/16680623/209129315-d11b853c-1997-43c0-b245-d3e0e8737549.png)

It is also confirmed by test results when additional refresh is not used, all further open methods' execution time is much lower than the execution time of the first open method.

 First open :
![изображение](https://user-images.githubusercontent.com/16680623/209130877-2917e8ad-07fa-4c4a-8120-0108ec4a3839.png)

All next opens:
![изображение](https://user-images.githubusercontent.com/16680623/209130966-b685c79f-a3ef-4d0c-9468-ffe586134008.png)

**Comment by asolntsev** [comment]
> page state remains unchanged

No, it's not true. Every new `open(url)` does load the page again.

> execution time is much lower than the execution time of the first open method

yes, this is normal because the first `open` call needs to start the browser (and sometimes load webdriver binary). It takes time. The following `open` calls already use the opened browser, but still load given url.
