### ISSUE TITLE
@As annotation command didn't seem to work with SelenideElement

### ISSUE THREAD

**Issue by PramodKumarYadav** [selenide/selenide#2087]
## The problem
Taking inspiration from [this article](https://selenide.org/2022/09/24/selenide-6.8.0/#as-annotation ), I tried to use @As annotation alias to get meaningful names in the report but that didn't work. 

Note: When I use it as $.as() that works. 
Example (this works):  `private static final SelenideElement USER_NAME_INPUT = $("input[id='edit-name']").as("USER_NAME_INPUT");` it works. So its only the annotation that didnt work. 

## Details
Below is the report that shows that aliases work when I use the `as` command with element but not when I use @At annotation. 

```
[INFO]	2022-12-22 17:11:40,723	[SimpleReport]: Report for assertThatUserCanNotAddPatientIfMissingMandatoryFields()
+----------------------------------------------------------------------------------+------------------------------------------------------------------------+------------+------------+
| Element                                                                          | Subject                                                                | Status     | ms.        |
+----------------------------------------------------------------------------------+------------------------------------------------------------------------+------------+------------+
| webdriver                                                                        | create()                                                               | PASS       | 4056       |
| open                                                                             | https://dev8.ebloodbanking.com                                         | PASS       | 7294       |
| USER_NAME_INPUT                                                                  | should be(editable)                                                    | PASS       | 70         |
| USER_NAME_INPUT                                                                  | set value(dummyUserName)                                         | PASS       | 60         |
| input[id='edit-pass']                                                            | should be(editable)                                                    | PASS       | 46         |
| input[id='edit-pass']                                                            | set value(*******)                                                   | PASS       | 51         |
| SUBMIT_BUTTON                                                                    | should be(visible)                                                     | PASS       | 23         |
```

## Tell us about your environment
* **Selenide Version**:   <selenide.version>6.10.1</selenide.version>
* **Chrome\Firefox\IE Version**:  Chrome 
* **Browser Driver Version**:  Version 108.0.5359.125 (Official Build) (64-bit)
* **Selenium Version**: default from selenide
* **OS Version**: Windows 10

Running tests with Junit5. 
## Code To Reproduce Issue [ Good To Have ]

```
private static final SelenideElement USER_NAME_INPUT = $("input[id='edit-name']").as("USER_NAME_INPUT");

    @As("PASSWORD_INPUT")
    private static final SelenideElement PASSWORD_INPUT = $("input[id='edit-pass']");
```

**Comment by asolntsev** [comment]
@PramodKumarYadav Works as expected. 
As mentioned in this article, annotation `@As` is needed for cases when you have a page object with `@FindBy` annotations. 
In your example, there is no page object, no `@FindBy` annotations. 
In order to make annotations work, you need to initialize page object using method `Selenide.page` or `Selenide.open(url, class)`.

**Comment by PramodKumarYadav** [comment]
Thanks for the answer @asolntsev. This explains. 

P.S: Out of curiosity, would it be possible to also let the annotations work for Selenide elements? Code would look much more cleaner with those.

**Comment by asolntsev** [comment]
Why `@As` looks more cleaner than `.as`? I don't see any difference.

> would it be possible to also let the annotations work for Selenide elements?
I answer in my previous comment: annotation will work if you initialize page object using method `Selenide.page` or `Selenide.open(url, class)`.

**Comment by PramodKumarYadav** [comment]
>Why @As looks more cleaner than .as? I don't see any difference.

Cant really defend this since this seems more of a matter of a taste. The only thing I could say is with annotation all names are always aligned on top of elements (as below). 
```
@As("SUBMIT_BUTTON")
private static final SelenideElement SUBMIT_BUTTON = $("button[id='edit-submit']");

@As("SEND_PASSWORD_RESET_INSTRUCTIONS_LINK")
 private static final SelenideElement SEND_PASSWORD_RESET_INSTRUCTIONS_LINK = $("a[class='request-password-link']");
```

With .as(), depending on how big the selector is the name can get lost towards the right end (as in below example) and would need a bit of scrolling. . 

```
private static final SelenideElement SUBMIT_BUTTON = $("button[id='edit-submit']").as("SUBMIT_BUTTON");

private static final SelenideElement SEND_PASSWORD_RESET_INSTRUCTIONS_LINK = $("a[class='request-password-link']").as("SEND_PASSWORD_RESET_INSTRUCTIONS_LINK");
```

**Comment by PramodKumarYadav** [comment]
First of all, thanks for your prompt responses @asolntsev . I appreciate it :). 

For below:
>I answer in my previous comment: annotation will work if you initialize page object using method Selenide.page or Selenide.open(url, class).

I tried initialing the page using the Selenide.open(url, class) as below, but still in reports, I do not see the alias. Maybe I am doing something wrong that you can see from here?

```
class LoginPageTest extends TestBase {
    LoginPage loginPage;

    @BeforeEach
    public void setup() {
        loginPage = open(CONFIG.getString("LOGIN_URL"), LoginPage.class);
    }

    @Test
    void assertThatUserCanLoginWithValidUser() {
        loginPage
                .loginWith(CONFIG.getString("USERNAME"), CONFIG.getString("PASSWORD"))
                .shouldRedirectToHomePage();
    }
}
```

Login page contains these two elements as below. 
```
private static final SelenideElement USER_NAME_INPUT = $("input[id='edit-name']").as("USER_NAME_INPUT");

    @As("PASSWORD_INPUT")
    private static final SelenideElement PASSWORD_INPUT = $("input[id='edit-pass']");
```

Report only shows the alias for the one that was named using .as() and the one with @As annotation still shows the selector. 
```
[INFO]	2022-12-22 20:17:16,303	[SimpleReport]: Report for [engine:junit-jupiter]/[class:com.jagriti.plasma.tests.LoginPageTest]/[method:assertThatUserCanLoginWithValidUser()]
+-----------------------+------------------------------------------------------------------------+------------+------------+
| Element               | Subject                                                                | Status     | ms.        |
+-----------------------+------------------------------------------------------------------------+------------+------------+
| webdriver             | create()                                                               | PASS       | 4040       |
| open                  | https://dev8.ebloodbanking.com                                         | PASS       | 7232       |
| USER_NAME_INPUT       | should be(editable)                                                    | PASS       | 67         |
| USER_NAME_INPUT       | set value(*****)                                         | PASS       | 56         |
| input[id='edit-pass'] | should be(editable)                                                    | PASS       | 47         |
| input[id='edit-pass'] | set value(*****)                                                   | PASS       | 48         |
| SUBMIT_BUTTON         | should be(visible)                                                     | PASS       | 25         |
| SUBMIT_BUTTON         | click()                                                                | PASS       | 5337       |
```

**Comment by asolntsev** [comment]
@PramodKumarYadav Ah yes, then the field should not be static.
Why you want to create a page object instance, but make its fields static? `static` is evil.

See https://www.youtube.com/watch?v=dFQSOlOOoXE&list=PLfazdZ9SzB9eDJIugtfH7KeVLLAP1pDLh&ab_channel=DEVCLUB.EE

**Comment by PramodKumarYadav** [comment]
>static is evil 

I agree :). It was my bad to keep the field static. Keeping them static for a by locator would still not be an issue (since that would not change per element) but keeping it static for a SelenideElement is indeed bad since an element can have different state/properties depending on the test. 

>Ah yes, then the field should not be static.
Why you want to create a page object instance, but make its fields static?

I changed the elements to non-static (and also non final) and yet I see the same result .

```
private SelenideElement USER_NAME_INPUT = $("input[id='edit-name']").as("USER_NAME_INPUT");

@As("PASSWORD_INPUT")
private SelenideElement PASSWORD_INPUT = $("input[id='edit-pass']");
```

```
| USER_NAME_INPUT       | should be(editable)                                                    | PASS       | 69         |
| USER_NAME_INPUT       | set value(*******************)                                         | PASS       | 124        |
| input[id='edit-pass'] | should be(editable)                                                    | PASS       | 49         |
| input[id='edit-pass'] | set value(*********)                                                   | PASS       | 121        |
```

**Comment by asolntsev** [comment]
@PramodKumarYadav As I mentioned before, `@As` annotation was initially intended to work only with fields annotated with `@FindBy`.

But why not, now I also added PR for using `@As` annotation with usual `$` fields: https://github.com/selenide/selenide/pull/2088

**Comment by PramodKumarYadav** [comment]
@asolntsev : You rock!  🙌 😊. Thanks for the feature addition!
