### ISSUE TITLE
Change the Chrome headless mode to the new one.

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#2104]
## The problem

[Selenium 4.8 is going to deprecate the headless API](https://github.com/SeleniumHQ/selenium/pull/11099#issue-1402374967) for Chromium options. This decision was made because the Chromium team has implemented a new Chrome headless mode that allows for overcoming the limitations of the old headless mode.

Because we have a built-in Configuration.headless option, we have to decide whether to set the old headless option or change to the new mode.

The first step seems to be to temporarily change the headless mode in our codebase and check the compatibility between the old and new modes. WIP in https://github.com/selenide/selenide/pull/2105

## Details

For details see:
https://github.com/SeleniumHQ/selenium/commit/2db6080beb30aa17fbe456959ddf21b1f7aaa0dc

**Comment by asolntsev** [comment]
Done in https://github.com/selenide/selenide/pull/2105
