### ISSUE TITLE
Add ClickOptions argument for the doubleClick method

### ISSUE THREAD

**Issue by nikitakovaliov92** [selenide/selenide#2133]
Is there a reason why ClickOptions argument doesn't present in the doubleClick method?

**Comment by asolntsev** [comment]
Because nobody asked for it. :)
In fact, I never used `$.doubleClick()` in my work projects. 

What options do you need for `doubleClick`?

**Comment by nikitakovaliov92** [comment]
I agree that doubleClick is used too rarely, but in my case this is a good way to use it. I have a date window in which I want to select the current month minus 2, for this I need to double click on the previous button. I would expect that if there is a clickoptions with a timeout argument, each click will occur with a given pause

![img](https://user-images.githubusercontent.com/59257413/213649503-50ecade9-605a-4903-8c5d-fa52985d9fb6.png)

**Comment by nikitakovaliov92** [comment]
This is not urgent, because there is a workaround with click method :)

**Comment by aakachurin** [comment]
I will do this

**Comment by BorisOsipov** [comment]
@nikitakovaliov92 

>but in my case this is a good way to use it. I have a date window in which I want to select the current month minus 2

use:
```
$(".foo").click()
$(".foo").click()
```
We don't need new methods or API to cover trivial programming cases.

Feel free to reopen this issue if you have other examples.

**Comment by aakachurin** [comment]
> @nikitakovaliov92
> 
> > but in my case this is a good way to use it. I have a date window in which I want to select the current month minus 2 for this I need to double click on the previous button.
> 
> use:
> 
> ```
> $(".foo").click()
> $(".foo").click()
> ```
> 
> We don't need new methods or API to cover trivial programming cases.
> 
> Feel free to reopen this issue if you have other examples.

so why didn't we remove this method from the interface?

**Comment by BorisOsipov** [comment]
@aakachurin We can't remove the method because of backward compatibility.

**Comment by aakachurin** [comment]
I'll just keep it here so you will be able to merge it if you will change your mind

**Comment by asolntsev** [comment]
@nikitakovaliov92 May I ask what is your workaround? Is it like this?
> $(".foo").click()
> $(".foo").click()

@aakachurin I wonder if your implementation is different from just calling `$.click()` twice? 
If yes, then probably we might need this function.

**Comment by nikitakovaliov92** [comment]
> @nikitakovaliov92 May I ask what is your workaround? Is it like this?
yep, I just use click twice

**Comment by aakachurin** [comment]
> @nikitakovaliov92 May I ask what is your workaround? Is it like this?
> > $(".foo").click()
> > $(".foo").click()
> 
> @aakachurin I wonder if your implementation is different from just calling `$.click()` twice? 
> If yes, then probably we might need this function. 

yep, as there is different event in js
as i remember an unit test will fail if you use double call
but i think in most cases it is equal to double call
