### ISSUE TITLE
SoftAsserts not working with Cucumber/Junit4 runner

### ISSUE THREAD

**Issue by kamil1014** [selenide/selenide#2141]
## The problem
I have a problem when i try to use SoftAsserts with my Cucumber project with Junit4 runner, i get error about no registered listener.

## Details
Error is thrown because listener is not being registered when using rule annotation:

> java.lang.IllegalStateException: You must configure you classes using JUnit4/JUnit5/TestNG mechanism as documented in https://github.com/selenide/selenide/wiki/SoftAssertions

## Tell us about your environment
* **Selenide Version**: 6.40 selenide-junit4
* **Chrome\Firefox\IE Version**:  103
* **Browser Driver Version**:  103
* **Selenium Version**: -
* **OS Version**:  any

## Code To Reproduce Issue [ Good To Have ]

`

    public class SetupTests {
    @Rule
    public SoftAsserts softAsserts = new SoftAsserts();
    
    public SetupTests() throws IOException {
        this.tester = Tester.getInstance();
        Configuration.timeout = 30 * 1000;
        Configuration.assertionMode = AssertionMode.SOFT;
    }

    @Before(order=1)
    public void before(Scenario scenario) throws IOException, ClassNotFoundException, URISyntaxException {
        Main.getInstance().act().openSite();
        $("element").shouldBe(Condition.visible);`

**Comment by asolntsev** [comment]
@kamil1014 Afaik JUnit's `@Rule` annotation is not supported by Cucumber. We cannot fix it on Selenide side.

I can only recommend you to upgrade to JUnit 5 and stop using cucumber. :)

See https://github.com/selenide/selenide/issues/559#issuecomment-375679454 for example.
