### ISSUE TITLE
Cannot create DevTools session twice

### ISSUE THREAD

**Issue by MakKeywa** [selenide/selenide#2142]
## The problem
TimeoutException is thrown when trying to create session second time after first one was opened and closed.

## Tell us about your environment
* **Selenide Version**: since 6.10.2 until newest 6.11.2
* **Chrome Version**: 109.0.5414.120 (64-bit)
* **Browser Driver Version**: 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414)

## Code To Reproduce Issue [Java]
pom.xml:
`
    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide-testng</artifactId>
            <version>6.10.2</version>
        </dependency>
    </dependencies>`
    
Main.java:
`
import com.codeborne.selenide.Selenide;
import com.codeborne.selenide.WebDriverRunner;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.devtools.DevTools;
import org.openqa.selenium.devtools.v108.network.Network;

import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class Main {

    public static void main(String[] args) {
        Selenide.open();
        DevTools devTools = ((ChromeDriver) WebDriverRunner.getWebDriver()).getDevTools();
        devTools.createSession();
        devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));

        devTools.clearListeners();
        devTools.close();

        devTools = ((ChromeDriver) WebDriverRunner.getWebDriver()).getDevTools();
        devTools.createSession(); // StackTrace starts here!
        devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));

        devTools.clearListeners();
        devTools.close();
    }

}
`

result:
`
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Starting ChromeDriver 109.0.5414.74 (e7c5703604daa9cc128ccf5a5d3e993513758913-refs/branch-heads/5414@{#1172}) on port 39664
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Feb 01, 2023 10:47:41 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 109, so returning the closest version found: 108
Exception in thread "main" org.openqa.selenium.TimeoutException: java.util.concurrent.TimeoutException
Build info: version: '4.7.1', revision: 'c6795baf1a3'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: driver.version: unknown
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:162)
	at org.openqa.selenium.devtools.DevTools.findTarget(DevTools.java:146)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:115)
	at org.openqa.selenium.devtools.DevTools.createSession(DevTools.java:103)
	at Main.main(Main.java:25)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.openqa.selenium.devtools.Connection.sendAndWait(Connection.java:151)
	... 4 more

Process finished with exit code 1
`

**Comment by BorisOsipov** [comment]
It seems regression in selenium v 4.7.1. Could be reproduced without selenide:
```
    @Test
    public void foo() {
        WebDriverManager.chromedriver().setup();
        ChromeDriver chromeDriver = null;
        try {
            chromeDriver = new ChromeDriver();
            DevTools devTools = chromeDriver.getDevTools();
            devTools.createSession();
            devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));

            devTools.clearListeners();
            devTools.close();

            devTools = chromeDriver.getDevTools();
            devTools.createSession(); // StackTrace starts here!
            devTools.send(Network.enable(Optional.empty(), Optional.empty(), Optional.empty()));

            devTools.clearListeners();
            devTools.close();
        } finally {
            Objects.requireNonNull(chromeDriver).quit();
        }

    }
```

Please, file a bug in [selenium repo](https://github.com/SeleniumHQ/selenium/issues/new?assignees=&labels=I-defect%2Cneeds-triaging&template=bug-report.yml&title=%5B%F0%9F%90%9B+Bug%5D%3A+)

**Comment by MakKeywa** [comment]
Thanks!

**Comment by asolntsev** [comment]
just for record, the issue was reported in selenium repo 
and
marked as "works as expected": https://github.com/SeleniumHQ/selenium/issues/11606#issuecomment-1415014112
