### ISSUE TITLE
Find broken images in a web site

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2144]
## The problem
How to find the broken images in a page

## Details
How to find the broken images in a page

## Tell us about your environment
* **Selenide Version**: 6.8.1
* **Chrome\Firefox\IE Version**: 110.0
* **Browser Driver Version**: 
* **Selenium Version**: 4.4.0
* **OS Version**: Win 10

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by Soumendu-Khilar** [comment]
Refer this issue if it helps: https://github.com/selenide/selenide/issues/131

**Comment by asolntsev** [comment]
@nicholaswkc34 Selenide has a check for images:
```java
$("#valid-image img").shouldBe(image);
```

See https://selenide.org/2020/03/18/selenide-5.10.0/#we-added-condition-imgshouldbeimage

**Comment by nicholaswkc34** [comment]
What is "img" in the $ bracket?
