### ISSUE TITLE
use CDP screencast API to record mp4 videos - extremely useful for headless mode 

### ISSUE THREAD

**Issue by nir-tal-talkspace** [selenide/selenide#2145]
## The problem

Currently, there is no real option without complex scripts to record in headless mode
CDP provides screencast API selenium already implemented but does not use it (and no guides on using it)
frameworks like cypress puppeteer and playwright use it already. 

**start screen cast**
`devTools.send(Page.startScreencast(Optional.of(Page.StartScreencastFormat.JPEG), Optional.of(100), Optional.of(1920), Optional.of(1080), Optional.of(1)));`

**stop screencast**
`devTools.send(Page.stopScreencast())`

and an event listener which receives the raw data (which are the frames)

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast
https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-stopScreencast

we need to compose from all the frames an mp4 video on the finish.

@asolntsev suggested opening this issue.

![Screenshot 2023-02-02 at 10 10 34](https://user-images.githubusercontent.com/71274151/216267821-f4c98527-23c7-49eb-a0bd-49778522d34e.png)

we need this feature!
thanks!!!

**Comment by asolntsev** [comment]
@nir-tal-talkspace Nice idea. Would be great to have such a feature.
Now somebody should implement it and submit a pull request. any help is welcome.

**Comment by asolntsev** [comment]
Hopefully is implemented in https://github.com/selenide/selenide/pull/2768
