### ISSUE TITLE
Detect metadata like page title wheather is missing in the web page

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2147]
## The problem
Need to check the metadata about web page like page title, etc.. How to achive this?

## Details
Need to check the metadata about web page like page title, etc.. How to achive this?

## Tell us about your environment
* **Selenide Version**: 6.8.1
* **Chrome\Firefox\IE Version**: 110.0
* **Browser Driver Version**: Latest
* **Selenium Version**: 4
* **OS Version**:  Win 10

**Comment by asolntsev** [comment]
@nicholaswkc34 
1. For checking page title, Selenide has API from [version 5.25.0](https://selenide.org/2021/09/28/selenide-5.25.0/#we-added-check-webdrivershouldhavetitle)
```java
webdriver().shouldHave(title("Login page"));
webdriver().shouldHave(title("Login page"), Duration.ofSeconds(10));
```
2. What other info you need to check?
