### ISSUE TITLE
IllegalStateException при загрузке файла методом download(DownloadOptions.using(FOLDER))

### ISSUE THREAD

**Issue by cray2001** [selenide/selenide#2150]
## The problem
При загрузке файла (элемент без href) выбрасывается исключение IllegalStateException 

## Details
Логи селенида и скрин папки загрузки в приложении
![FOLDER](https://user-images.githubusercontent.com/92686004/217544634-6dd83030-0c44-40bc-944f-cae7cc4f8bfa.PNG)
[FOLDER_download.txt](https://github.com/selenide/selenide/files/10685998/FOLDER_download.txt)

## Tell us about your environment
* **Selenide Version**: 6.11.2
* **Chrome\Firefox\IE Version**: Chrome
* **Browser Driver Version**: 98
* **Selenium Version**: 
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]

```java
File file =exportCitiesButton.shouldBe(Condition.visible).download(DownloadOptions.using(FOLDER));
```

**Comment by asolntsev** [comment]
@cray2001 Please add `withExtension`, so Selenide knows which file to wait:

```java
File file = exportCitiesButton.download(using(FOLDER).withFilter(withExtension("xlsx")));
```
