### ISSUE TITLE
Testing Google Analytics using Selenide like Playwright

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2151]
## The problem
I had watch a youtube channel https://www.youtube.com/watch?v=V2dgEhY-U0Y where Playwright can test the google analytics functionality. I wonder how to achieve this in Selenide using MiTMProxy or others built in features. 

## Tell us about your environment
* **Selenide Version**: 6.8.1
* **Chrome\Firefox\IE Version**: 110.00 
* **Browser Driver Version**: -
* **Selenium Version**: 4
* **OS Version**:  Win 10

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@nicholaswkc34 If I understand correctly, I want to verify http requests/responses between browsers and outer world. 
In Selenide,
1. using [browser logs](https://selenide.org/2019/12/16/advent-calendar-browser-logs/)
2. using [Javascript code](https://selenide.org/2019/12/17/advent-calendar-browser-logs-with-js/)
3. using [Selenide's own built-in proxy](https://selenide.org/2019/12/18/advent-calendar-network-logs-with-proxy/)

These posts were written in year 2019; later Selenium added another way: using CDP.
With CDP, you can verify all requests/responses by
* `devTools.addListener(Network.requestWillBeSent()...`
* `devTools.addListener(Network.responseReceived()...`
See [PR 1691](https://github.com/selenide/selenide/pull/1691/files) for examples.
I guess Playwright also uses CDP.
