### ISSUE TITLE
Add web-driver support "print to pdf" configuration without any OS dialogs

### ISSUE THREAD

**Issue by natraj04** [selenide/selenide#2152]
## Details
In our project i came across a scenario where, after clicking on the pay button I get a print preview window(attached the screenShot for reference) to print the invoice. I need to save the invoice as PDF to a specific folder. 

## Tell us about your environment
* **Selenide Version**:  selenide-appium:2.4.0
* **Chrome\Firefox\IE Version**: 109.0.5414.119
* **OS Version**: macOS 12.5.1 (21G83)

## Thanks to @asolntsev support, I was able to handle the issue by setting some chrome preferences. 
                   // update chrome options to set download directory
                    ChromeOptions options = new ChromeOptions();
                    HashMap<String, Object> prefs = new HashMap<>();

                    prefs.put("download.prompt_for_download", false);
                    prefs.put("download.default_directory", downloadPath);
                    prefs.put("savefile.default_directory", downloadPath);
                    prefs.put("download.directory_upgrade", true);
                    prefs.put("download.extensions_to_open", "pdf");

                    // using --kiosk-printing to enable "silent printing"
                    options.addArguments("--kiosk-printing");

                    // disable 'chrome is being controlled by automated test software' bar
                    options.setExperimentalOption("prefs", prefs);

                    // set driver with updated chrome options
                    WebDriverRunner.setWebDriver(new ChromeDriver(options));

Im raising this ticket so that selenide can help in handling it issue, in an easier way.

**Comment by natraj04** [comment]
This feature should also support multiple browser (firefox, safari and chrome)

**Comment by asolntsev** [comment]
@natraj04 You code didn't work for me. But I managed to add few more settings to make it work, see https://github.com/selenide/selenide/compare/feature/2152-print-page-to-pdf?expand=1

Anyway, it has some disadvantages:
1. doesn't work in headless mode
2. doesn't work in Firefox, Safari and other non-Chromium browsers.

So I suggest to cancel this ticket and implement https://github.com/selenide/selenide/issues/1391 instead.

**Comment by natraj-rewaa** [comment]
Hi @asolntsev,

https://github.com/selenide/selenide/issues/1391 solution dosent work for my scenario, but thanks for adding the others in settings.

**Comment by asolntsev** [comment]
@natraj-rewaa Can you comment why it didn't work?

**Comment by natraj04** [comment]
@asolntsev For some context, below is how test scenario flows

Steps
1. Click on pay button
<img width="1160" alt="1" src="https://user-images.githubusercontent.com/49331044/223955151-4242130b-2250-4bae-a503-94a7a7d6f1bc.png">
2. A print preview will display with invoice details in it
<img width="907" alt="2" src="https://user-images.githubusercontent.com/49331044/223955294-2331ff0b-be41-447d-8ec1-bc2bf226b472.png">
3. click on save, a pdf will be downloaded and viewed like this
<img width="688" alt="3" src="https://user-images.githubusercontent.com/49331044/223955410-49a31a04-3ddc-4d76-83ea-491397c2a2bb.png">

Now this below code works in auto downloading the invoice, and im using it to validate and continue my script
```java
                    // update chrome options to set download directory
                    ChromeOptions options = new ChromeOptions();
                    HashMap<String, Object> prefs = new HashMap<>();
                    prefs.put("download.prompt_for_download", false);
                    prefs.put("download.default_directory", downloadPath);
                    prefs.put("savefile.default_directory", downloadPath);
                    prefs.put("download.directory_upgrade", true);
                    prefs.put("download.extensions_to_open", "pdf");
                    prefs.put("safebrowsing.enabled", true);

                    // disable save password pop up on browser
                    prefs.put("credentials_enable_service", false);
                    prefs.put("profile.password_manager_enabled", false);

                    // using --kiosk-printing to enable "silent printing"
                    options.addArguments("--kiosk");
                    options.addArguments("--kiosk-printing");
                    options.addArguments("--safebrowsing-disable-download-protection");
                    options.addArguments("--safebrowsing-disable-extension-blacklist");

                    //work-around for selenide after Chrome update with 111.0.5563.64 version
                    options.addArguments("--remote-allow-origins=*");

                    // setting prefs to chrome options
                    options.setExperimentalOption("prefs", prefs);

                    // set driver with updated chrome options
                    Configuration.browserCapabilities = options;
```
                    

I tried the suggested solution 'https://github.com/selenide/selenide/issues/1391'

added it before and after the pay button below is the pdf im getting
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/49331044/223956055-4d284597-85c2-47cf-b6e0-387826b91f65.png">

As you can see i dont see any details related to invoice.

Expected pdf will look something like this:
<img width="688" alt="3" src="https://user-images.githubusercontent.com/49331044/223956321-a67dae7f-15ca-47ba-b054-ff96db002a45.png">

**Comment by asolntsev** [comment]
@natraj04 Thank you for the details. Few questions:

> click on save, a pdf will be downloaded and viewed like this

Wait, but how exactly are you clicking on "save" button? Afaik Selenium webdriver doesn't have access to this "printing" dialog, and cannot click this "save" button.

> I tried the suggested solution 'https://github.com/selenide/selenide/issues/1391'

How exactly did you try it? Can you show the code?
In issue 1391, it was suggested to call method `driver.print(new PrintOptions());` - did you call that? 
If yes, this method should return PDF. You don't need to see this PDF on the screen.

**Comment by mlipok** [comment]
Printing in Chrome in non headles should be fixed now, take a look here:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=3517

**Comment by natraj04** [comment]
Closing the request! Thank you all for the help!

Its working for us with the below code,
`                  

                    ChromeOptions options = new ChromeOptions();
                    HashMap<String, Object> prefs = new HashMap<>();

                    prefs.put("download.prompt_for_download", false);
                    prefs.put("download.default_directory", downloadPath);
                    prefs.put("savefile.default_directory", downloadPath);
                    prefs.put("download.directory_upgrade", true);
                    prefs.put("download.extensions_to_open", "pdf");
                    prefs.put("safebrowsing.enabled", true);

                    // disable save password pop up on browser
                    prefs.put("credentials_enable_service", false);
                    prefs.put("profile.password_manager_enabled", false);

                    // using --kiosk-printing to enable "silent printing"
                    options.addArguments("--kiosk");
                    options.addArguments("--kiosk-printing");
                    options.addArguments("--safebrowsing-disable-download-protection");
                    options.addArguments("--safebrowsing-disable-extension-blacklist");

                    // unknown error: DevToolsActivePort file doesn't exist
                    options.addArguments("--disable-dev-shm-usage");
                    options.addArguments("--no-sandbox");

                    // setting prefs to chrome options
                    options.setExperimentalOption("prefs", prefs);

                    // set driver with updated chrome options
                    Configuration.browserCapabilities = options;`

<img width="567" alt="image" src="https://github.com/selenide/selenide/assets/49331044/93f68997-f80a-4060-9d8b-d952eede6a2a">

**Comment by cobaltautomationdev** [comment]
options.add_argument("--kiosk-printing")
options.add_argument("--headless=new")   ,
   # click print_button
    print_button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "[data-testid='docViewActionButton'][title='Print']")))
    print_button.click()

 if a pdf generated by click a print button on the website, it will not save the pdf automatically in headless mode, am I right?
