### ISSUE TITLE
alert prompt dialog input username and password

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2159]
## The problem
I have a website that prompt username and password signin before landing on the website. May I know how to input username and password to it and click ok button. 

## Details
I have a website that prompt username and password signin before landing on the website. May I know how to input username and password to it and click ok button. 

## Tell us about your environment
* **Selenide Version**: 6.8.1
* **Chrome\Firefox\IE Version**: 110.0
* **Browser Driver Version**: -
* **Selenium Version**: 4
* **OS Version**: Win 10

## Code To Reproduce Issue [ Good To Have ]
I did have alert.accept() and alert.dismiss().

**Comment by asolntsev** [comment]
@nicholaswkc34 What type of dialog you mean? There may be many possible options. 
If you mean Basic Auth, then Selenide has special methods:

```java
  open("http://localhost:8080/basic-auth/hello", "", "scott", "tiger");
```
