### ISSUE TITLE
Cannot resolve method setFileDetector when using Selenide with SauceLabs

### ISSUE THREAD

**Issue by amitkshatriya01** [selenide/selenide#2160]
## The problem
I am trying to use Selenide with sauceLabs for multithreaded parallel execution, everything seems to be working fine except for when scripts has to upload file to sauceLabs to then use in application. 

## Details
SauceLabs provides documentation as below to upload file and use it however when I do 

```java
WebDriverRunner.getWebDriver().setFileDetector(new LocalFileDetector());
```

I get error that cannot resolve method `setFileDetector`.
SauceLabs documentation for uploading file: https://support.saucelabs.com/hc/en-us/articles/115003685593-Uploading-Files-to-a-Sauce-Labs-Virtual-Machine-during-a-Test

I have tried the following and it works fine in local but since the same file path and file isn't available in sauceLabs VM its fails.
```java
Selenide.$(fileUpload).uploadFile(new File("./test.jpg"));
```

## Tell us about your environment
* **Selenide Version**: 6.11.1
* **Chrome\Firefox\IE Version**: 109
* **Browser Driver Version**: 109
* **Selenium Version**: 4.7.2
* **OS Version**: Windows 11

## Code To Reproduce Issue

```java
WebDriverRunner.getWebDriver().setFileDetector(new LocalFileDetector());
```

**Comment by asolntsev** [comment]
@amitkshatriya01 You don't really need to call `setFileDetector` because Selenide already does it:

```java
webDriver.setFileDetector(new LocalFileDetector());
```

See https://github.com/selenide/selenide/blob/724eef1378d797e5c849a90dab29223f0c23e978/src/main/java/com/codeborne/selenide/webdriver/RemoteDriverFactory.java#L25
