### ISSUE TITLE
Exception in thread "Dead threads watchdog"

### ISSUE THREAD

**Issue by TatsianaZ** [selenide/selenide#2162]
My code:

![image](https://user-images.githubusercontent.com/30373875/219945736-61bd3662-02e6-4a96-9d47-27425e1ecf04.png)

I have the following exception:

![image](https://user-images.githubusercontent.com/30373875/219945780-ea7df03a-e98c-497a-9b0f-709bff917b5e.png)

**Comment by asolntsev** [comment]
@TatsianaZ What Selenide version are you using?
At least I cannot reproduce the issue with Selenide 6.11.1. Look, this code works without any errors:
https://github.com/selenide/selenide/blob/issue2162/statics/src/test/java/integration/DevToolsTest.java
