### ISSUE TITLE
IllegalArgumentException Unknown HTTPClient factory selenide-netty-client-factory error in case of Selenide Test execution from Jar file

### ISSUE THREAD

**Issue by lnorbert11** [selenide/selenide#2166]
## The problem

Hello Dear Selenide Community!

I exported my Selenide tests to a jar file with Intelli-J. Unfortunately after starting the file from cmd(java -jar SelenideJarProject.jar) I get the error message below. 
Interestingly, if I comment out the Selenide commands, use Selenium instead and rebuild the jar. The test doesn't break down and opens the desired webpage. 

I tried different Selenide maven dependencies. (current version in the sample project is 6.11.2)

I uploaded a sample project to github. It contains only a class with some commands and the created jar file which you can reproduce the error with.  
If I run the test from Intelli-J I don't get any error even with Selenide. 

Could you please analyze the problem? 

Thank you and Best Regards,
Norbert

## Tell us about your environment
Browser version: Chrome 109.0.5414.75
Chromedriver version: 109.0.5414.74
Selenide maven dependency:  6.11.2
Java version: OpenJDK 17.0.5
OS version: Windows 10 Enterprise build: 19044.2486

## Code To Reproduce Issue [ Good To Have ]
https://github.com/lnorbert11/SelenideJarProject.git

`    public static void main(String[] args) {
        System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
        Configuration.browser = "chrome";
        open("https://selenide.org/");

        //Selenium
        //WebDriver driver = new ChromeDriver();
        //driver.get("https://selenide.org/");
    }`

Screenshot about the error: 
![SelenideError](https://user-images.githubusercontent.com/117342193/220080801-163a4d4f-5134-484a-8da0-820e97140382.PNG)

**Comment by asolntsev** [comment]
@lnorbert11 Have you tried to search your problem in github issues? 
Look: https://github.com/selenide/selenide/issues?q=is%3Aissue+Unknown+HTTPClient+factory+selenide-netty-client-factory

> This is not Selenide bug. Obviously, you are building the jar incorrectly: it doesn't contain all the needed classes.
MY simplest advice: don't use the single jar. I don't see any reasons why you should need it.

**Comment by Sarang25** [comment]
@lnorbert11  Did you get any success ? Same kind of executions flow are used in my company and after updating selenide version to 6.15.0 from 5.18.1 is giving  same error

**Comment by lnorbert11** [comment]
Hello @Sarang25!
I dont't have a final solution, but I've found a workaround. 
If you init your webdriver with selenium and pass it to WebDriverRunner then it should work as a runnable jar as well.

Here is a snippet:
System.setProperty("webdriver.chrome.driver", "chromedriver.exe");
Configuration.browser = "chrome";
WebDriver driver = new ChromeDriver();
WebDriverRunner.setWebDriver(driver);

You don't need to use selenium commands like driver.findElement ... you can use selenide instead, so you don't need to change any other part of you code, just the driver initialisation. 

I hope it'll help!

Best Regards,
Norbert

**Comment by asolntsev** [comment]
@Sarang25 @lnorbert11 The only proper solution is to build your JAR properly. This jar should include all needed files in `META-INF/services` from all your dependencies. First of all, from selenide*.jars

**Comment by Sarang25** [comment]
@asolntsev Thanks. I got a solution yesterday for this. I have to explicitly add dependency on pom.xml for latest selenium and WebdriverManager, secondly have to add this peace of code System.setProperty("webdriver.http.factory", "jdk-http-client"); on before starting the browser.

**Comment by asolntsev** [comment]
@Sarang25 No. Did you read my last comment https://github.com/selenide/selenide/issues/2166#issuecomment-1570995241? 

I believe you don't need to do both these action. 
1. If you just set `System.setProperty("webdriver.http.factory", "jdk-http-client");` - then you don't need to add selenium and WebdriverManager.
2. If you fix your JAR file as I described, you will not need any of these hacks at all.
