### ISSUE TITLE
very slow to verify elements with ElementsCollection in a list

### ISSUE THREAD

**Issue by jinlxz** [selenide/selenide#2170]
## The problem
very slow to verify elements with ElementsCollection in a list

## Details
I have a test to verify the content of an item in a list, the test looks like the following
```java
package org.example;

import com.codeborne.selenide.*;
import com.codeborne.selenide.ex.ElementNotFound;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;

import java.time.Duration;

import static com.codeborne.selenide.CollectionCondition.sizeGreaterThan;
import static com.codeborne.selenide.Condition.*;
import static com.codeborne.selenide.Selenide.$$;
import static com.codeborne.selenide.Selenide.element;
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;

public class MainTest {

    @Test
    public void verifySubscriptionItemsForOrder() throws Exception {
        Configuration.pageLoadTimeout = 50000;
        Selenide.open("http://127.0.0.1:8080/my_account4/My%20Account.html");
        getWebDriver().manage().window().maximize();
        LoggerUtils.logMethodTime("find all subscriptions related to the order");
        //find the subscription items for an order in subscription list, basically it retrieve all subscription items and filter by order id.
        ElementsCollection subscriptions = this.findSubscriptionItemsByOrderId("O-0000017865");
        LoggerUtils.logMethodTime("find the subscription related to the product");
        //find the subscription for the product SIMATIEDL, it uses the method `ElementCollection.filter()` to find the target subscription.
        SelenideElement target = this.findSubscriptionItem(subscriptions, "SIMATIEDL", 1);
        LoggerUtils.logMethodTime("verify product name.");
        target.find(By.cssSelector("span.cc_col_subscription_prod_name a")).shouldHave(exactOwnText("Industrial Edge Management License"));
        LoggerUtils.logMethodTime("verify subscription id");
        target.find(By.cssSelector("span.cc_goto_subscription_details")).shouldHave(matchText("^SB-.*"));
        LoggerUtils.logMethodTime("verify subscription recurring price.");
        target.find(By.cssSelector("span.cc_col_subscription_recurring_price")).shouldHave(ownText("USD $"));
        LoggerUtils.logMethodTime("finished to verify subscription recurring price.");
    }

    private ElementsCollection divSubscriptionItems = $$("div.subs-expands");

    public ElementsCollection findSubscriptionItemsByOrderId(String orderNumber) {
        ElementsCollection subscriptions = divSubscriptionItems.filter(childExactText(
                By.xpath(".//div[contains(@class,'subscription-data')]//div[contains(@class,'sub-heading')]"), orderNumber
        )).shouldBe(sizeGreaterThan(0));
        return subscriptions;
    }

    public SelenideElement findSubscriptionItem(ElementsCollection subscriptionItems, String sku, int inCartQuantity) {
        SelenideElement target = subscriptionItems.filter(childAttributeValue(By.cssSelector("span.cc_col_subscription_prod_name a"), "data-id", sku))
                .find(childExactText(By.cssSelector("div.subscription-data div.cc_col_subscription_status"), String.valueOf(inCartQuantity)))
                .shouldBe(exist);
        LoggerUtils.logMethodTime("the target subscription item is found in the list.");
        target.scrollIntoView(true).shouldBe(visible);
        return target;
    }

    public static Condition childExactText(By childBy, String text_) {
        return new Condition("childExactText") {
            @Override
            public CheckResult check(Driver driver, WebElement node) {
                String childText = null;
                Duration timeout = driver.getWebDriver().manage().timeouts().getImplicitWaitTimeout();
                try {

                    driver.getWebDriver().manage().timeouts().implicitlyWait(Duration.ZERO);
                    childText = element(node).find(childBy).getOwnText().trim();
//                    childText=node.findElement(childBy).getText().trim();
                } catch (ElementNotFound e) {
                } finally {
                    driver.getWebDriver().manage().timeouts().implicitlyWait(timeout);
                }
                if (childText == null)
                    return new CheckResult(false, "the exception NoSuchElementException is occurred.");
                return new CheckResult(childText.equals(text_), childText);
            }
        };
    }

    public static Condition childAttributeValue(By childBy, String key, String value) {
        return new Condition("childAttributeValue") {
            @Override
            public CheckResult check(Driver driver, WebElement node) {
                String childText = null;
                Duration timeout = driver.getWebDriver().manage().timeouts().getImplicitWaitTimeout();
                try {
                    driver.getWebDriver().manage().timeouts().implicitlyWait(Duration.ZERO);
//                    childText=element(node).find(childBy).getAttribute(key).trim();
                    childText = node.findElement(childBy).getAttribute(key).trim();
                } catch (ElementNotFound e) {
                } finally {
                    driver.getWebDriver().manage().timeouts().implicitlyWait(timeout);
                }
                if (childText == null)
                    return new CheckResult(false, "the exception NoSuchElementException is occurred.");
                return new CheckResult(childText.equals(value), childText);
            }
        };
    }
}
```
the output says the performance is not good
```
10:40:56.111 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#verifySubscriptionItemsForOrder:30 => find all subscriptions related to the order
10:41:19.957 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#verifySubscriptionItemsForOrder:32 => find the subscription related to the product
10:41:36.673 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#findSubscriptionItem:56 => the target subscription item is found in the list.
10:42:09.007 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#verifySubscriptionItemsForOrder:34 => verify product name.
10:42:26.156 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#verifySubscriptionItemsForOrder:36 => verify subscription id
10:42:44.047 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#verifySubscriptionItemsForOrder:38 => verify subscription recurring price.
10:43:00.742 [main] INFO  org.example.LoggerUtils - [time] org.example.MainTest#verifySubscriptionItemsForOrder:40 => finished to verify subscription recurring price.
```
I found it took about 20s and more to verify the content of the `target` element, I suppose the `target` element is located and cached by the method `this.findSubscriptionItem()`, it should not take so much time, It should be very fast, it seems the `target` element is re-evaluated every time when verifying the content, I am not sure if it is a performance issue of selenide library? could you help me on this, how can I optimize the code to improve performance?

## Tell us about your environment
* **Selenide Version**:  6.0.3
* **OS Version**:  windows 11

## Code To Reproduce Issue [ Good To Have ]
https://github.com/jinlxz/stackoverflow_questions
1. go the test resource folder src/test/resources, start a HTTP server with port 8080 and serving the files under test resource folder, so that we can test against it, I used python command `python -m http.server --bind 0.0.0.0 8080 `
2.  please run the unit test `org.example.MainTest#verifySubscriptionItemsForOrder` to reproduce the issue

**Comment by asolntsev** [comment]
@jinlxz Why you think `target` is cached? No, by default Selenide doesn't cache anything. 

First of all, I recommend you to avoid all this complex combination of loops. filters, xpaths and css selectors, and just **write a single xpath** to find the element you need. finding element by a single xpath is always much faster than any loops/filters. 

Secondly, what implicit timeout you use? If you use Selenide, please don't set implicit timeout to any number except `0`.

**Comment by jinlxz** [comment]
@asolntsev the `target` element is retrieved in the method `findSubscriptionItem`, which calls `target.shouldBe(visible)`, this call should evaluate and find the element, return it, I thought it will not try to locate the target element again when it executes `target.find(subEle). shouldBe(...)` in following statements, if it is not the case, can we cache the target element to improve performance?

about your suggestion, in some other cases I need to verify multiple items in the list, these items are generated in prior steps dynamicly, so it's difficult to get the exact and stable xpath or css locator for them, so I used filter here

I don't set implicit timeout in the test, it uses default value.

**Comment by asolntsev** [comment]
> in some other cases I need to verify multiple items in the list, these items are generated in prior steps dynamicly

Sorry, I don't understand this argument. 
I suggest you to generate `By` or xpath (or a part of xpath) on previous steps instead of `SelenideElement`. Sure, it's doable.

**Comment by asolntsev** [comment]
@jinlxz Yes, it's possible to cache the `target` element. And few more optimizations: see PR https://github.com/jinlxz/stackoverflow_questions/pull/1

But the search of `target` is still slow because you execute webdriver method `getOwnText()` in a loop for 600+ elements. Every webdriver call takes time. It's always a good idea to avoid repetitive webdriver calls in a loop. It's always better to find a single query (xpath, css or JavaScript code) to find the needed element by a single webdriver call.

After my optimizations these are the slowest steps in your test:

```
|open          |http://127.0.0.1:8080/my_account4/My%20Account.html         |PASS      |3411      |
|MainTest      |find all subscriptions related to the order                 |PASS      |15603     |
```

**Comment by jinlxz** [comment]
@asolntsev  Thanks for your help, the method `ElementsCollection.snapshot()` really improves the performance a lot, I will also try to optimize the xpath to reduce the total number to items for iteration, Thank you again.

**Comment by jinlxz** [comment]
@asolntsev  also it will be very helpful if we can implement a method `cached()` on SelenideElement.

**Comment by asolntsev** [comment]
@jinlxz Thank you for the good example. 
I registered few feature ideas that came from this discussion:
* https://github.com/selenide/selenide/issues/2171
* https://github.com/selenide/selenide/issues/2172
