### ISSUE TITLE
Unable to establish websocket connection

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2193]
## The problem
I had coded automation testing in selenide but strange time comes up.

The browser window not able to establish websocket connection to http://localhost:2757/devtools/browser/uuid

> [ERROR] Tests run: 97, Failures: 1, Errors: 0, Skipped: 96, Time
> elapsed: 3.945 s <<< FAILURE! - in
> com.rev.testManager.GenericTestManager [ERROR]
> com.rev.testManager.GenericTestManager.openPage  Time elapsed: 3.727 s
> <<< FAILURE!
> org.openqa.selenium.remote.http.ConnectionFailedException: Unable to
> establish websocket connection to
> http://localhost:2757/devtools/browser/d5f72b05-f030-41ee-88b2-5823e7d0f35c
> Build info: version: '4.4.0', revision: 'e5c75ed026a' System info:
> host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch:
> 'amd64', os.version: '5.14.0-283.el9.x86_64', java.version: '18.0.2'
> Driver info: driver.version: SelenideDriver selenide.url:
> https://www.buletintv3.my/ selenide.baseUrl:
> https://www.buletintv3.my/    at
> org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
>   at
> org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
>   at
> org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:106)
>   at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
>   at
> org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:116)
>   at java.base/java.util.Optional.map(Optional.java:260)  at
> org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
>   at
> org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:81)
>   at
> com.codeborne.selenide.webdriver.ChromeDriverFactory.create(ChromeDriverFactory.java:42)
>   at
> com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriverInstance(WebDriverFactory.java:109)
>   at
> com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:69)
>   at
> com.codeborne.selenide.drivercommands.CreateDriverCommand.lambda$createDriver$0(CreateDriverCommand.java:76)
>   at
> com.codeborne.selenide.logevents.SelenideLogger.get(SelenideLogger.java:166)
>   at
> com.codeborne.selenide.drivercommands.CreateDriverCommand.createDriver(CreateDriverCommand.java:52)
>   at
> com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:180)
>   at
> com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:149)
>   at
> com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:130)
>   at
> com.codeborne.selenide.impl.StaticDriver.getAndCheckWebDriver(StaticDriver.java:65)
>   at
> com.codeborne.selenide.SelenideDriver.getAndCheckWebDriver(SelenideDriver.java:220)
>   at
> com.codeborne.selenide.drivercommands.Navigator.lambda$navigateTo$0(Navigator.java:72)
>   at
> com.codeborne.selenide.logevents.SelenideLogger.run(SelenideLogger.java:153)
>   at
> com.codeborne.selenide.drivercommands.Navigator.navigateTo(Navigator.java:70)
>   at
> com.codeborne.selenide.drivercommands.Navigator.open(Navigator.java:32)
>   at
> com.codeborne.selenide.SelenideDriver.open(SelenideDriver.java:101)
>   at com.codeborne.selenide.Selenide.open(Selenide.java:52)   at
> com.rev.testManager.GenericTestManager.openPage(GenericTestManager.java:27)
>   at
> java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
>   at java.base/java.lang.reflect.Method.invoke(Method.java:577)   at
> org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
>   at
> org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
>   at
> org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
>   at
> org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
>   at
> org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:816)
>   at
> org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:590)
>   at
> org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
>   at
> org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
>   at
> org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
>   at
> org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
>   at
> org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
>   at
> org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
>   at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)   at
> org.testng.TestRunner.privateRun(TestRunner.java:806)     at
> org.testng.TestRunner.run(TestRunner.java:601)    at
> org.testng.SuiteRunner.runTest(SuiteRunner.java:433)  at
> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)  at
> org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)   at
> org.testng.SuiteRunner.run(SuiteRunner.java:330)  at
> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)  at
> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)   at
> org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)     at
> org.testng.TestNG.runSuitesLocally(TestNG.java:1176)  at
> org.testng.TestNG.runSuites(TestNG.java:1099)     at
> org.testng.TestNG.run(TestNG.java:1067)   at
> org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
>   at
> org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:111)
>   at
> org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
>   at
> org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
>   at
> org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
>   at
> org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
>   at
> org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
>   at
> org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

The code is working in MacOS  13.1 but not Centos 9 Stream edition.  I just invalidates the cache and thing become like this. 

## Tell us about your environment
* **Selenide Version**:  6.8.1
* **Chrome\Firefox\IE Version**:  111
* **Browser Driver Version**: 
* **Selenium Version**:  4
* **OS Version**:  Centos 9 Stream

## Code To Reproduce Issue [ Good To Have ]
@BeforeMethod
public void openPage() {
    open("https://buletintv3.my");
}

**Comment by nicholaswkc34** [comment]
They say need to add google options. How to do it in Selenide? 

https://stackoverflow.com/questions/75680149/unable-to-establish-websocket-connection

https://groups.google.com/g/chromedriver-users/c/xL5-13_qGaA?pli=1

**Comment by asolntsev** [comment]
@nicholaswkc34 These options are already added in Selenide 6.12.2, you just need to upgrade.

**Comment by nicholaswkc34** [comment]
Let me try to upgrade and see.

**Comment by nicholaswkc34** [comment]
It solved the problem, please close the issue.

**Comment by Redbeeard** [comment]
@FaridAzimov007 See chrome bug report:
This bug causes the browser window to not resize properly.
https://bugs.chromium.org/p/chromium/issues/detail?id=1416398

**Comment by FaridAzimov007** [comment]
> @FaridAzimov007 See chrome bug report: This bug causes the browser window to not resize properly. https://bugs.chromium.org/p/chromium/issues/detail?id=1416398

There is no answer for my issue=( I can]t find something here -  https://bugs.chromium.org/p/chromium/issues/detail?id=1416398

**Comment by FaridAzimov007** [comment]
So, what can we do now? Just wait?

**Comment by asolntsev** [comment]
AFAIK it's not true that "resizing doesn't work". It works, but it just cannot set bigger size than actual screen size. In some sense,  it's even reasonable.

**Comment by FaridAzimov007** [comment]
> @FaridAzimov007 Yes, I understand that you hadn't problem with resizing before 6.12.0. It happened because we switched from "old headless mode" (that supported any sizes) to "new headless mode" (that currently doesn't support sizes larger than screen size).
> 
> We cannot fix it somehow because Chrome developers decided to stop supporting the "old headless mode".

I see, is there any way I can solve this problem?
The thing is, with a resolution other than 1920X1080 I can't interact with the element on the page.

**Comment by asolntsev** [comment]
@FaridAzimov007 I don't know any better answer than this:
1. When you run locally, you need to have monitor of size `1920X1080` or larger.
2. When you run tests on CI server (any non-graphical environment like Jenkins on Linux), you can run `xvfb` server with a parameter a'la "screen size". Thus you ask xvfb to open large enough virtual screen. 

NB! If your web application doesn't work properly on screens smaller than `1920X1080`, you should probably register a bug. Normal users also cannot you your application, right? Then your tests have found a problem. This is why we are writing tests, right?

**Comment by FaridAzimov007** [comment]
> 1. When you run locally, you need to have monitor of size `1920X1080` or larger.
> 2. When you run tests on CI server (any non-graphical environment like Jenkins on Linux), you can run `xvfb` server with a parameter a'la "screen size". Thus you ask xvfb to open large enough virtual screen.
> 
> NB! If your web application doesn't work properly on screens smaller than `1920X1080`, you should probably register a bug. Normal users also cannot you your application, right? Then your tests have found a problem. This is why we are writing tests, right?

Thanks for the advice on the solution.
you are absolutely right.
But at the moment, businesses are not interested in making the app adaptable, to my great regret.
can we expect an update from selenide in the near future with a solution to the problem?

**Comment by asolntsev** [comment]
@FaridAzimov007 Once again: **I don't know how to fix this problem**. I think **we cannot fix** this problem. 
Developers of Chrome browser decided to switch to new "headless" mode that doesn't support the old behaviour.

**Comment by FaridAzimov007** [comment]
> @FaridAzimov007 Once again: **I don't know how to fix this problem**. I think **we cannot fix** this problem. Developers of Chrome browser decided to switch to new "headless" mode that doesn't support the old behaviour.

Got it.
Thank you Andrei!

**Comment by YuryKaminski1** [comment]
@asolntsev , thanks for your comment. It works after updating **Selenide** to the latest version (6.13.0 for me)
