### ISSUE TITLE
Selenide does not work with the Google Chrome v111

### ISSUE THREAD

**Issue by NerfPutin420** [selenide/selenide#2195]
When my Chrome get the new version, my Selenide testes failed because of a 403 Error Code. My colleague testes worked with the Chrome v110 but when he got the new v111, his testes also failed.
The solution was for us to change the selenide.browser to Firefox. Can you check on what's the problem with the new Chrome version?

**Comment by Sarkasronie** [comment]
Did you update to Selenide 6.12.2 where this error got fixed?

**Comment by NerfPutin420** [comment]
Oh I haven't seen your latest update, now the testes start fine, Thanks for you fast reply.

**Comment by TarasYanUA** [comment]
Thanks for a piece of advice to update IDEA. I had the same problem with chrome v111.

**Comment by Yawanaika** [comment]
Start parameter add "--remote-allow-origins=*"，like:
  `options.addArguments("--remote-allow-origins=*");`

**Comment by cemerick1** [comment]
This is still an issue even with 6.12.2. My tests are slower and fail consistently on chrome and edge but run fine on firefox.

**Comment by TarasYanUA** [comment]
> This is still an issue even with 6.12.2. My tests are slower and fail consistently on chrome and edge but run fine on firefox.

I don't have any of these bugs. You definitely need to write a letter to tech. support.

**Comment by asolntsev** [comment]
@cemerick1 I would like to help you, but I need to know how to reproduce this problem. Can you share some sample project, for example?

**Comment by cemerick1** [comment]
@asolntsev I appreciate it. We figured out the chrome issue by using WebDriverManager.chromedriver().clearResolutionCache() edge seems to be a local issue on our end. God Bless and thanks again for the help!
