### ISSUE TITLE
Email Sending Facility/Library

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2197]
## The problem
Dear all forumers, I had coded automation testing in Selenide version 6.12.1 and everything works perfectly except the email sending with attachment. Few years back, I usign Gmail less secure apps to sent email but now it is unavailable right now. Then, my company had **sendgrid paid service** but the send email with attachment sometimes works and sometimes didn't works. Besides this, I had also tried the latest Gmail API but some classes are unresolvable in Intellij IDE. So, I ran out of idea and need suggestion from you regarding the send email with attachment service. 

ADMIN, please don't close/delete this thread. I really need help. 

## Tell us about your environment
* **Selenide Version**: 6.12.1
* **Chrome\Firefox\IE Version**: 111 
* **Browser Driver Version**: 
* **Selenium Version**: 4.8.1
* **OS Version**: Centos 9 Stream

Please suggest some mail service which can send attachment.

**Comment by BorisOsipov** [comment]
It is not a forum. It is selenide library issue tracker.

**Comment by asolntsev** [comment]
@nicholaswkc34 Sorry, we understand you need help, but your question is not related to Selenide.
