### ISSUE TITLE
SelenideElement.clear() throws ElementNowFound after clearing

### ISSUE THREAD

**Issue by ClintEstwood** [selenide/selenide#2207]
## The problem
Smart search input element has logic:
Given When input has some value
And When user clear field
And Then user press Tab or click on any other page element
Then Smart search input dissapear.

So using SelenideElement.clear() on this field throws ElementNotFound exception.
As I understood Selenide not only clear the field, but also presses Tab and then verify that element is presented.

The issue solved by SelenideElement.toWebElement().clear()

## Tell us about your environment
* **Selenide Version**: 6.11.0
* **Chrome\Firefox\IE Version**: Firefox 102.8.0
* **Selenium Version**: 4.7.2
* **OS Version**: Windows 10 Pro 21H2

## Code To Reproduce Issue [ Good To Have ]

```
SelenideElement element = $("smart-search-input").should(appear).should(enabled).scrollTo();
element.setValue("Oh my");
element.clear(); //input element has been cleared and then disappeared. After that ElementNowFoundException happens
```

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/2221
