### ISSUE TITLE
Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Unable to establish websocket connection to http://localhost:00000/devtools/browser/8ccf95f5-bce1-4bbc-9a37-2a5a9586c08f

### ISSUE THREAD

**Issue by mbarua1** [selenide/selenide#2214]
## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to Selenide).
Tell us what you were trying to do and what happened instead. 

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**: 
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by mbarua1** [comment]
Selenium Version 3.2 and 3.6.12
I tried with both Selenium/serenity version and using CHrome driver 111 but still having same error. Could you please help me? I do have two seperate repo. So i need to fix for both version of serenity
Browser Driver version: Chrome 111.0.5563.64
Selenium 3.2 and 3.6.12

**Comment by mbarua1** [comment]
@asolntsev

**Comment by mbarua1** [comment]
net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate class org.openqa.selenium.chrome.ChromeDriver
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: 
Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (Unable to establish websocket connection to [http://localhost:00000/devtools/browser/8ccf95f5-bce1-4bbc-9a37-2a5a9586c08f](http://localhost:0/devtools/browser/8ccf95f5-bce1-4bbc-9a37-2a5a9586c08f)
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'XXXXXXXXXX  os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.2', java.version: '18'
Driver info: driver.version: ProvideNewDriver). See below for more details.
Caused by: org.openqa.selenium.remote.http.ConnectionFailedException: 
Unable to establish websocket connection to http://localhost/:XXXXXXXX/devtools/browser/8ccf95f5-bce1-4bbc-9a37-2a5a9586c08f
Build info: version: '4.1.2', revision: '9a5a329c5a'
System info: host: 'XXXXXXXXXXX', ip: 'XXXXXXXXXXXX', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '12.6.2', java.version: '18'
Driver info: driver.version: ProvideNewDriver

**Comment by mbarua1** [comment]
@here

**Comment by asolntsev** [comment]
@mbarua1 Why you registered this issue in Selenide project, though you are not using Selenide?

Anyway, you should upgrade to the latest Selenium version (4.8.1). The version you are using (3.2) is very-very old.
