### ISSUE TITLE
Feature request:  Condition.innerText() / Condition.innerHtml() 

### ISSUE THREAD

**Issue by dacloutier-logmein** [selenide/selenide#2220]
## The problem
Our company uses https://pusher.github.io/chameleon/ as a front end component library. The problem with it, is that it wraps a lot of elements that are unfortunately not handled by Selenide. 

For some elements, it becomes really problematic, example a `checkbox` becomes a `chameleon-checkbox`.
I do not expect, you to support that (it would be an endless task to support every framework). 

For some elements though, there are some possible workaround:

a `p` is often replaced by a `chameleon-typography` element. Unfortunately the `condition.text` always Yields `""` and consequently fails.

Asserting on `innerText()` works on the other hand.

## Details
What I would like is to support the `innerText()` and `innerHtml()` methods on the `Conditions.xxx` class.

**Comment by asolntsev** [comment]
@dacloutier-logmein Yes, we can add condition `$.shouldHave(innerText("foo"))` - similar to `ownText` we already have.
But do we really need `$.shouldHave(innerHtml("foo"))`? We don't usually verify html in tests. It would make our tests very fragile. 

P.S. By the way, doesn't `ownText` already solve your problem?

**Comment by asolntsev** [comment]
@dacloutier-logmein Could you please write few examples, say, for site https://pusher.github.io/chameleon/components/forms/?

I am trying to understand what problems you have with these components. 
For example, usual Selenide methods work with that checkbox without problems:
```java
  @Test
  void canSetCheckbox() {
    open("https://pusher.github.io/chameleon/components/forms/");
    $("#hello").shouldBe(checked);
    $("#hello").click();
    $("#hello").shouldNotBe(checked);
  }
```

**Comment by dacloutier-logmein** [comment]
Found a page where we can see sample component:
https://chameleon-design-system.netlify.app/?path=/docs/components-form-elements-checkbox--default

**Comment by dacloutier-logmein** [comment]
```java

 class chameleonWebTest
{

  private final static SelenideElement iFrame = $("#storybook-preview-iframe");
  private final static SelenideElement checkbox = $("chameleon-checkbox");
  private final static SelenideElement exampleSection = $("#story--components-form-elements-checkbox--default");

  @Test
  void checkbox()
  {
    open("https://chameleon-design-system.netlify.app/?path=/docs/components-form-elements-checkbox--default");
    switchTo().frame(iFrame);
    exampleSection.should(exist);
    checkbox.shouldBe(checked);
    checkbox.click();
    checkbox.shouldNotBe(checked);
  }
}

```

**Comment by dacloutier-logmein** [comment]
this yields:

```
Element should be checked {chameleon-checkbox}
Element: '<chameleon-checkbox checked label></chameleon-checkbox>'
Actual value: unchecked
Screenshot: file:~/Documents/IdeaProjects/chamelon-web-tester/chameleon-web-tester/build/reports/tests/1679399827689.0.png
Page source: file:~/Documents/IdeaProjects/chamelon-web-tester/chameleon-web-tester/build/reports/tests/1679399827689.0.html
Timeout: 4 s.
Element should be checked {chameleon-checkbox}
Element: '<chameleon-checkbox checked label></chameleon-checkbox>'
Actual value: unchecked
```

**Comment by asolntsev** [comment]
@dacloutier-logmein Thank you for the example!
Wait, but this checkbox is not clickable... How your test can uncheck it?

Anyway, I see this component uses _Shadow DOM_. Selenide has methods for working with shadow dom:

```java
private SelenideElement checkboxValue = $(shadowCss("input[type=checkbox]", "chameleon-checkbox"));
private final SelenideElement checkbox = $("chameleon-checkbox");

checkboxValue.shouldBe(checked);
checkbox.click();
checkboxValue.shouldNotBe(checked); // It's OK: it fails because checkbox is not really clickable

```

**Comment by dacloutier-logmein** [comment]
Working with the shadow dom, worked !
Thanks!

Think we can close.
