### ISSUE TITLE
Tests are failing which were working fine for months

### ISSUE THREAD

**Issue by NerfPutin420** [selenide/selenide#2222]
In our company, we are using Selenide v.6.12.2 and our tests were working fine for months, but this morning most of our tests failed. I've checked our tests and I can not understand the reason of the fails. Selenide couldn't find basic HTML elements in the tests and couldn't do simple actions like clicking and things like that.

I've also realised that, the Selenide is now using the CDP v.110 (because it can't find the v.111), but when the tests were fine it was using v.108.

Can you help me to solve this problem?

**Comment by asolntsev** [comment]
How can someone help you without seeing error messages, stacktraces etc.?

At least my tests are running today.

**Comment by NerfPutin420** [comment]
I have the basic error messages but this is a part of an error message:

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [xxx]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Starting ChromeDriver 111.0.5563.64 (c710e93d5b63b7095afe8c2c17df34408078439d-refs/branch-heads/5563@{#995}) on port xxxxx
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Mar 21, 2023 10:51:45 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 111, so returning the closest version found: 110
[1679392345.301][SEVERE]: Timed out receiving message from renderer: 30.000
[1679392345.311][SEVERE]: Timed out receiving message from renderer: 30.000

Element should be visible {a[title='example']}
....
After that, I have the basic error message which is provided after when an element is not found. The problem is that I am 100% sure that I've declared the correct element. because it was working for a long time, and we didn't change the source code of that file

**Comment by asolntsev** [comment]
Well, don't you want to start fix this `SLF4J: No SLF4J providers were found` issue?

P.S. I don't think "CDP version 111 vs 110" is a problem - it's just a warning which is (almost) always shown.

**Comment by NerfPutin420** [comment]
This SLF4J was always shown to us, even a test fails or not. Yesterday we found out we got some loading issues, because the page loadings were getting slower, so maybe that is the problem. Most of our test fails were because Selenide couldn't find elements on the page, but on the screenshots it was clearly there, so it was a bit confusing. 
So all in all, we think when we will correct this loading issues, all the fails will be gone. Sorry if I took your time and thanks for your help.

**Comment by asolntsev** [comment]
@NerfPutin420 Yes, these lines clearly say that there was a problem with loading:
> [1679392345.301][SEVERE]: Timed out receiving message from renderer: 30.000
> [1679392345.311][SEVERE]: Timed out receiving message from renderer: 30.000

But still, I highly recommend to solve the issue with SLF4J. It's really easy.
Do you understand that Slf4j is _logging_ library? Then you will see some useful logs that can help you solving various problems.
