### ISSUE TITLE
Timeout exception: while clicking on "Accept all cookies button" / How to maximize window (org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 29.778)

### ISSUE THREAD

**Issue by Reshmajadhavb** [selenide/selenide#2228]
## The problem
Hi, I am new to Selenide. Working on AngularJS application. Before login page website has accept cookies pop up , I think that problem is when window is not maximized accept cookie button is not completely visible. Hence its getting timed out. 

I checked that window maximize option is not available in Selenide.
If I want to scroll down and then click, how do I do that?

Please check the image. This is how it looks when page is loaded

## Tell us about your environment
Selenide Version - 6.12.2
Chrome:- 111
Selenium Version: 4.8
OS Version**: Windows 10 Enterprise (64 bit)

## Code To Reproduce Issue 

```java
package org.example;
import com.codeborne.selenide.Configuration;
import org.openqa.selenium.By;
import org.testng.annotations.Test;
import java.util.*;
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.Condition.*;

public class  loginAndSearchTest{
    //Configuration.browserSize = "1920x1080";
    
    @Test
    public void demoTest() throws InterruptedException {

-         open("intenal company url");
          $(By.cssSelector("#onetrust-reject-all-handler")).click();
        
    }
```

![image](https://user-images.githubusercontent.com/108232094/227525972-3ba9188b-8638-41c5-9199-b0000f019cae.png)

**Comment by Reshmajadhavb** [comment]
Hi , This issue is resolved by wait condition "should appear".


can someone please tell, how do I locate ngelelemts in selelnide like in below image there is no other attribute than ngContent.
![image](https://user-images.githubusercontent.com/108232094/227539156-6332e87a-2297-4a76-ac75-66152916ac04.png)

**Comment by asolntsev** [comment]
@Reshmajadhavb Hi. 
For example, you can find this element by text: 
```java
  import static com.codeborne.selenide.Selectors.byText;

  $(byText("Login")).click();
```

**Comment by asolntsev** [comment]
@Reshmajadhavb This test works for me. I am not getting timeouts.

Usually this error means that the browser could not load the site in time. The network was too slow in your office?

NB! Please fix the SLF4J warning. You see lots of red text, why don't you fix it?
NB! Next time please share source code **as text**, not images. Use services like pastebin or github gist for this.
