### ISSUE TITLE
Methods `$.selectOption*` throw a tricky error when applied for non-selects

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2231]
## The problem
Selenide has a bunch of methods for working with `<select>` element, like 
```java
$("select#gender").selectOptionContainingText("Female")
``` 

But it throws a totally **unreadable error message** when applied for non-`select` elements. 

## Tell us about your environment
* **Selenide Version**: 6.12.4

## Code To Reproduce Issue

```java
@Test
public void test() {
  Selenide.open("https://mui.com/material-ui/react-select/#multiple-select");
  Selenide.$("#demo-multiple-name").shouldBe(Condition.enabled).click();
  Selenide.$("ul[aria-labelledby='demo-multiple-name-label']").selectOptionContainingText("Kelly Snyder"); // fails
}
```

Stacktrace: https://pastebin.com/65fV5FU0

**Comment by nikitakovaliov92** [comment]
Please also mention somewhere in the javadoc that a select tag is required to use selectOption methods :)
