### ISSUE TITLE
Add support for webkit (safari) browser type

### ISSUE THREAD

**Issue by kupist-priv** [selenide/selenide#2238]
## The problem
Some of the implementations of selenium grid are expecting browserName as webkit and not safari.

ClassNotFoundException is raised when Configuration.browser = "webkit" is set.

## Details
Introduce similar implementation for Configuration.browser = "webkit" as implemented for Configuration.browser = "safari" to handle Safari Browser in diff grid implementations.

**Comment by asolntsev** [comment]
@kupist-priv Can you provide more details? What grid implementation do you mean? 

P.S. Anyway, you can override any capability by setting system property: 
```bash
-Dcapabilities.browserName=webkit -Dselenide.browser=safari
```

Or right in code (before opening a browser):
```java
System.setProperty("capabilities.browserName", "webkit");
```

**Comment by kupist-priv** [comment]
Thank u for the response. 

I am using SeleniumBox. 

Let me try with system properties. I tried with browser caps and it was causing conflict and exception.

**Comment by kupist-priv** [comment]
It is working. Ticket could be closed if no further steps.
