### ISSUE TITLE
Menu Bar Options not interactable

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2246]
## The problem
I doing the automation testing for https://www.freemalaysiatoday.com/. The menu bar has drop down options and it can navigate as usual but when i open the Chrome Dev tools to inspect, the menu bar options doesn't displayed, Why it is like this? 

## Details
I doing the automation testing for https://www.freemalaysiatoday.com/. The menu bar has drop down options and it can navigate as usual but when i open the Chrome Dev tools to inspect, the menu bar options doesn't displayed, Why it is like this? 

I even cannot test the Text Home, 
$x("//*[@id=\"__next\"]/div/div[4]/div/ul/li[1]/a").shouldHave(test("HOME")); The error is 

> Element should be interactable {By.xpath: //*[@id="__next"]/div/div[4]/div/ul/li[1]/a}
> Element: '<a aria-current="page" class="Style__StyledAnchor-sc-kwuyeg-0 SOKaF nav-link px-0 mx-0 mx-lg-2 mx-xl-1.125-rem pt-0.6-rem pb-0.4-rem lh-19-px fw-600 text-black me-0 me-lg-2 me-xl-1.125-rem text-uppercase active" href="/" displayed:false></a>'
> Actual value: hidden, opacity=1

## Tell us about your environment
* **Selenide Version**: 6.13.0
* **Chrome\Firefox\IE Version**: 111.0 
* **Browser Driver Version**: 5.13.2
* **Selenium Version**: 4.8.3
* **OS Version**: Win 11

**Comment by nicholaswkc34** [comment]
When i do hover() to element menu bar options, it show element not interactable.

**Comment by asolntsev** [comment]
1. When you open Chrome Dev tools, you make the size of your browser screen smaller.
2. Your app https://www.freemalaysiatoday.com/ has responsive design. The behaviour of the menu is different on big and small windows. On small windows, it doesn't use dropdown in menu.

P.S. This question is not related to Selenide.

**Comment by nicholaswkc34** [comment]
How about the latest questions?
