### ISSUE TITLE
Element Not Interactable

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2249]
## The problem
I doing automation testing for website https://www.freemalaysiatoday.com/ but the menu bar options is not clickable, What wrong with it? How to solve it using selenide? Cannot hover also. 

## Details
I doing automation testing for website https://www.freemalaysiatoday.com/ but the menu bar options is not clickable, What wrong with it? How to solve it using selenide?

$x("//*[@id=\"__next\"]/div/div[4]/div/ul/li[1]/a").click();

```
[ERROR]   GenericTestManager.testHome:51 Element should be interactable {By.xpath: //*[@id="__next"]/div/div[4]/div/ul/li[1]/a}
Element: '<a aria-current="page" class="Style__StyledAnchor-sc-kwuyeg-0 SOKaF nav-link px-0 mx-0 mx-lg-2 mx-xl-1.125-rem pt-0.6-rem pb-0.4-rem lh-19-px fw-600 text-black me-0 me-lg-2 me-xl-1.125-rem text-uppercase active" href="/" displayed:false></a>'
Actual value: hidden, opacity=1
```

## Tell us about your environment
* **Selenide Version**: 6.13.0
* **Chrome\Firefox\IE Version**: 111.0
* **Browser Driver Version**: 5.3.2
* **Selenium Version**: 4.8.3
* **OS Version**: Win 11

## Code To Reproduce Issue [ Good To Have ]
`$x("//*[@id=\"__next\"]/div/div[4]/div/ul/li[1]/a").click();`

**Comment by asolntsev** [comment]
@nicholaswkc34 What can I say? Hover doesn't work because the element is hidden.
Can you see this line?
> Actual value: hidden, opacity=1

It clearly says that the element is **hidden**.

**Comment by nicholaswkc34** [comment]
Yes, How to make it visible?

**Comment by asolntsev** [comment]
@nicholaswkc34 What are you asking me? I don't know. It's your application, it's your test. Sorry, but this question is not related to Selenide.
