### ISSUE TITLE
Put screenshots to ${test_class_name}/${test_method_name}.png

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#225]
[Pekka Kokkonen]
Only if there was an easier way to configure (override) how the screenshots are saved... ;) We'd like to save the screenshots and page sources so that they would be easier to include into Jenkins-generated test results (using e.g. jUnit report attachments plugin). This would require possibility to save the files in directory using a template such as .../${test_class_name}/${test_method_name}.png

**Comment by dmak** [comment]
I would be also interested in extra ways to configure path to screenshots. In my case I would prefer something like `${date}/${test_method_name}.png` (prefixed by `${selenide.reports}`).

**Comment by igor-dmitriev** [comment]
It would be a nice feature

**Comment by asolntsev** [comment]
@igor-dmitriev Feel free to submit a pull request! :)

**Comment by asolntsev** [comment]
UPD I don't see any reasons to implement this feature request. 
Selenide automatically adds a path to screenshot to the error message. It's absolutely enough to find the file. I even suggest that the name of screenshot could be absolutely random. 

Why should somebody search this file by name?

**Comment by dmak** [comment]
Yes and no: depends on where the image is saved. In particular, when a build job for Maven project is executed within Jenkins it is expected that all produced artifacts are within `./target` folder relative to project root. In this case there is a chance for post-build Jenkins job action to capture these screenshots. If they are saved to a temporary location (say, `/tmp`), then by the time they could be captured, they are removed.
Unfortunately I cannot check the location at the moment...

**Comment by asolntsev** [comment]
@dmak Yes, Selenide by default stores screenshots to `build/reports` (default for Gradle), and I assume that it's reasonable to set this value to `target/blah` for Maven. That's it. Let jenkins do the rest. I don't see any reasons to make it complex, use `/tmp` folder and "capture" the manually.

**Comment by dmak** [comment]
Looks OK for me.

**Comment by asolntsev** [comment]
With a rise of parametrized tests, and especially JUnit5 (which potentially can generate test names dynamically), and Kotlin tests (which can have absolutely any human-readable names in ticks), 
I find it almost impossible to give screenshots names of test methods. These can be pretty much any names.
