### ISSUE TITLE
Add Selenide browser.

### ISSUE THREAD

**Issue by gabrielnascimento2048** [selenide/selenide#2254]
## The problem
Idea to try to create selenide browser, be test more reliable and consistent, because sometimes we spend too much time on browser issue, then with this approach we can define the driver them just select with on we can use, based on OS drivers configured. 

## Details
can try to implement Electron runtime, cypress use this approach. With Electron we can manage the execution 

## Tell us about your environment
* **Selenide Version**: doesn't matter
* **Chrome\Firefox\IE Version**: doesn't matter
* **Browser Driver Version**: doesn't matter
* **Selenium Version**: doesn't matter
* **OS Version**: doesn't matter

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@gabrielnascimento2048 Sorry, but from this description, it's not absolutely clear what are you suggesting. :(

Anyway, what means "we spend too much time on browser issue"? What browser issue do you mean?

**Comment by gabrielnascimento2048** [comment]
Browser issue means to launch the webDrive instance. e.g. to run a sample example I need to launch the test waiting couple of secs 5secs  to open the browser, then execute the login on the app then start my test, all those steps, its almost 30 secs. Then I'm thinking about how we can implement some embedded browsers on Selenide, it should be more a brainstorm to consolidate the idea and try define some possible workflows.

**Comment by rosolko** [comment]
Browser initialization is more related to selenium

**Comment by asolntsev** [comment]
@gabrielnascimento2048 theoretically, we could create some feature like this. But currently I don't understand how exactly it should work.

**Comment by asolntsev** [comment]
Closing until we get to know what the feature is desired here...
