### ISSUE TITLE
Page objects for 2 browser instances

### ISSUE THREAD

**Issue by Sundeltop** [selenide/selenide#2256]
## The problem
I am trying to create page objects for 2 browser instances in a single test as in example: https://github.com/selenide/selenide/blob/main/src/test/java/integration/SelenideDriverITest.java

## Details
What I am doing, is creating `new SelenideDriver(new SelenideConfig())` to create new browser instance. Then calling `.open(URL, PageObject.class` to get page object. As far as I understand, now I should be able to interact with specific browser instance through page object method's. But currently I faced with error: No webdriver is bound to current thread: 19. You need to call open(url) first.

## Tell us about your environment
* **Selenide Version**:  6.13.0
* **Chrome\Firefox\IE Version**: 111.0.5563.149
* **Browser Driver Version**:  N/A
* **Selenium Version**: N/A
* **OS Version**: N/A

## Code To Reproduce Issue [ Good To Have ]
```
LoginPage session1 = new SelenideDriver(new SelenideConfig())
                .open("URL", LoginPage.class);
LoginPage session2 = new SelenideDriver(new SelenideConfig())
                .open("URL", LoginPage.class);
session1.login();
session2.login();
```

**Comment by asolntsev** [comment]
@Sundeltop Obviously, we cannot say anything if we don't see the code of `LoginPage`. 

P.S. And let me remind that in most cases you don't really need to create instance of `SelenideDriver` by your own.

**Comment by Sundeltop** [comment]
@asolntsev Thank you for your reply. Yes, this is just for learning purposes to interact with 2 browsers in the same tests. For the production test I would always mock required behaviour of second browser.

So, here is my LoginPage class:

```
public class LoginPage {

	public LoginPage login(String login, String password) {
		$("#login")
                	.setValue(login)
                	.shouldHave(value(login));
		$("#password")
                	.setValue(password)
                	.shouldHave(value(password));
		$("#confirm button")
                	.shouldBe(enabled)
                	.click();

      	return this;
	}
}
```

**Comment by asolntsev** [comment]
@Sundeltop Look, your `LoginPage` uses **static method** `Selenide.$`. This static method doesn't know about your `SelenideDriver`. It doesn't know in which driver your page object is defined. It just tries to get a "usual" webdriver (thread-local) and throws an exception. 

`LoginPage` should be reworked to work with given driver, not static driver:

```java
public class LoginPage {

    @FindBy(id = "login")
    private SelenideElement loginInput

    @FindBy(id = "password")
    private SelenideElement passwordInput;

    @FindBy(css = "#confirm button")
    private SelenideElement confirmButton;

    public LoginPage login(String login, String password) {
        loginInput
            .setValue(login)
            .shouldHave(value(login));

        passwordInput
            .setValue(password)
            .shouldHave(value(password));

        confirmButton.click();

        return this;
    }
}
```
