### ISSUE TITLE
Cannot set browser position to negative values

### ISSUE THREAD

**Issue by rniemczyk10** [selenide/selenide#2258]
## The problem
Cannot change browser position using negative values.
`DIMENSION_REGEX` pattern in BrowserResizer.java does not allow to use negative values for browser position.
https://github.com/selenide/selenide/blob/main/src/main/java/com/codeborne/selenide/webdriver/BrowserResizer.java

## Details
I am trying to move browser window to display to the left of main screen but `adjustBrowserPosition(Config config, WebDriver driver)` method throws exception `Browser position -1900x-450 is incorrect` .

BrowserPosition method should have separate pattern e.g. `"-?\\d+x-?\\d+"` 

## Tell us about your environment
* **Selenide Version**: doesn't matter
* **Chrome\Firefox\IE Version**: doesn't matter
* **Browser Driver Version**: doesn't matter
* **Selenium Version**: doesn't matter
* **OS Version**: doesn't matter

## Code To Reproduce Issue [ Good To Have ]
Set system property:
-Dselenide.browserPosition=-1900x-450

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/2259
