### ISSUE TITLE
Capability to add new method findElementIfExistElseIgnore 

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide#2261]
## The problem
Add capability to find and interact with element if it presents or ignore. I know this is not a best practice and always we should know how the application should behave. Selenide is meant to solve people problems. Recently we added functionality to handle random popups which against is not something ideal but we did it to make users' life easy. 

Currently, we have to build wrappers like this,

```java
try {
  $(webelement).click();
}
catch(NoSuchElementException e){
  //do nothing
}
```

> What about a method `$ifExists(weblement).click();`?

## Details

Modern-day applications are built behind feature flags(launch darkl and there are few developments happening all the time and hence there may be cases elements might be present and sometimes it won't be based on the feature flag. All we want to do is click if it is present else simply ignore it and move to the next step.

**Comment by asolntsev** [comment]
@amuthansakthivel I was also thinking about such a method.
BUT
Do you realize that such method will last 4 seconds (or whatever timeout you have)?
It makes tests so much slower.

Much better approach would be to read features flags by test code, and use ifs like this in tests:

```java
if (feature X is enabled) {
  $(webelement).click();
}
```

**Comment by amuthansakthivel** [comment]
You are correct @asolntsev. We are setting the states by using launch darkly API but the problem is we get rate limit errors and then we have solve that. So, I ended up spending time on things which are not useful for me.

Even I cannot create a custom method for this, because it will fail during the findElement phase. 

Yes, the tests will be slower but we are leveraging parallel execution. So I am okay to spend few extra seconds for robustness of my tests.

**Comment by asolntsev** [comment]
Sorry, I don't understand you. I don't know what is "darkly api", what means "rate limit" in this context. But I think you should rather solve the problem with rate limit instead of building hacks in the tests.

**Comment by asolntsev** [comment]
Sorry, I don't understand you. I don't know what is "darkly api", what means "rate limit" in this context. But I think you should rather solve the problem with rate limit instead of building hacks in the tests.

**Comment by amuthansakthivel** [comment]
https://launchdarkly.com/ - It is feature used by developers to put functionalities behind a flag. The application can behave differently based on the flag set. 
LaunchDarkly API does not allow more than 5 API calls in less than 10 seconds. In our application, we have to set at least 20 flags before running a test. 

It is so much of hard work. If we have functionality in selenide like findElementIfExistsElseIgnore it will solve most of our pain point.

Again this is just one use case. I am sure many people would have requested for such a feature. Please give me a hint on where should I start looking to develop a feature. I can create a PR to implement this feature

**Comment by asolntsev** [comment]
@amuthansakthivel Thank you for the clarification.

Do I correctly understand that it's a pricing question? The limitation "5 API calls in less than 10 seconds" is only in some free or cheap package.

Then I still highly recommend to clarify this problem without creating hacks in tests.
Buy an advanced package. Make as many calls as needed. In the end, it will be cheaper than hand-made hacks and unstable tests.

Anyway, my initial suggestion was not to SET 20 flags before every test, but to READ current flags in the beginning of tests. Read only once and cache. Then every test can use these flags:
```java
if (feature X is enabled) {
  $(webelement).click();
}
```

**Comment by amuthansakthivel** [comment]
It is a premium plan that we have @asolntsev. Even though we set states using api's there are cases where someone from product team or qa would just toggle the flag for testing purposes. 

I understand this is not a good practice but I am left with no other choice.

**Comment by asolntsev** [comment]
> but I am left with no other choice.

Wait, are you sure you understand my last sentence in https://github.com/selenide/selenide/issues/2261#issuecomment-1522421115? 
I don't see any problems here. You can **read feature flags once** and use in all tests.

**Comment by amuthansakthivel** [comment]
@asolntsev - Manual testers or product owners might change the flag for their test purpose. It is very hard to rely on that. Lets say, I want to just implement it in my project, is there any way to do it. Custom method wont work as the findElement call will fail

**Comment by asolntsev** [comment]
@amuthansakthivel I highly recommend to organize the testing process so that other people would not disturb when the automated tests are running. For example, using a dedicated testing environment for automated tests is a good strategy.

Anyway, you can easily create your custom method for waiting whatever you want.

What means `Custom method wont work as the findElement call will fail`. Do you use method `findElement` in your tests? Why? It should not be needed if you use Selenide.

**Comment by amuthansakthivel** [comment]
@asolntsev - I tried to create a custom commad like, but it fails before it reaches here

```java 
public class clickIfExists implements Command<SelenideElement> {
 @Nullable
  @Override
  public SelenideElement execute(
    SelenideElement proxy, WebElementSource locator, @Nullable Object[] objects) {
      try{
        $(proxy).click();
     }
      catch(Exception e){
     }
 }
}
```

**Comment by asolntsev** [comment]
@amuthansakthivel Please show how are you using this command? And a full stacktrace would be helpful.

**Comment by amuthansakthivel** [comment]
Trying to get the stack trace @asolntsev . Please allow me some time

**Comment by amuthansakthivel** [comment]
Hi @asolntsev 

Here is the code I use and the stacktrace,

private FacilitiesPage clickSave() {
    SAVE_BUTTON.execute(new ClickIfExists());
    return this;
  }

Stacktrace can be found [here](https://gist.github.com/amuthansakthivel/b3484fa86a583fec379c92e615267894)

**Comment by asolntsev** [comment]
Thanks, now I see the problem.
It's the same problem that was described in this old good post:
https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/

And I think you could replace `$(element).shouldBe(visible).click()` by `element.click()`.

**Comment by amuthansakthivel** [comment]
@asolntsev Thanks for the hint. I forget that the Selenide throws Error.

Replacing $(element).shouldBe(visible).click() by element.click() won't help either. Because we internally check whether the element is interactable before clicking. So, this functionality is not possible

Element not found {by text: Save123}
Expected: interactable
Screenshot: file:/Users/amuthansakthivel/ClipboardHealth/sunshine/build/reports/tests/1682572844322.0.png
Page source: file:/Users/amuthansakthivel/ClipboardHealth/sunshine/build/reports/tests/1682572844322.0.html
Timeout: 30 s.
Caused by: NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":".//*/text()[normalize-space(translate(string(.), '

	at com.codeborne.selenide.impl.WebElementSource.createElementNotFoundError(WebElementSource.java:87)
	at com.codeborne.selenide.impl.ElementFinder.createElementNotFoundError(ElementFinder.java:142)
	at com.codeborne.selenide.impl.WebElementSource.checkConditionAndReturnElement(WebElementSource.java:131)
	at com.codeborne.selenide.impl.WebElementSource.findAndAssertElementIsInteractable(WebElementSource.java:149)

**Comment by asolntsev** [comment]
But method `element.click()` also checks that the element is visible! You don't really need more.

**Comment by amuthansakthivel** [comment]
@asolntsev - Even after replacing the code is not working. If the element is not available it should ignore but it is currently throwing exception

**Comment by asolntsev** [comment]
Again, show the code and stack trace.

**Comment by amuthansakthivel** [comment]
@asolntsev - Here is the code that I tried

```java
public class ClickIfExists implements Command<SelenideElement> {

  @Nullable
  @Override
  public SelenideElement execute(SelenideElement selenideElement, WebElementSource webElementSource, @Nullable Object[] objects)
    throws IOException {
    try {
      selenideElement.click();
    } catch (Exception e) {

    }
    return selenideElement;
  }
}
```
```java
private FacilitiesPage clickSave() {
    SAVE_BUTTON.execute(new ClickIfExists());
    return this;
}
```
Stacktrace can be found [here](https://gist.github.com/amuthansakthivel/fb88919757490946d4737e20d28a9868)

**Comment by asolntsev** [comment]
I see. Did you read the post from my previous comment? It explains the problem with try/catch in your code.

**Comment by amuthansakthivel** [comment]
@asolntsev - It worked but I think this violates so many good coding practices. Thanks for all your help. I will close this issue now.

**Comment by asolntsev** [comment]
> but I think this violates so many good coding practices

@amuthansakthivel  Yes, it does violate. As well as any IFs and try/catches in tests.
