### ISSUE TITLE
@Find for SelenideElement

### ISSUE THREAD

**Issue by RobertoPegoraro** [selenide/selenide#2265]
Is there any annotation for find an element?

I'd like to declare something like that:

```java
@Find(xPath = "//input[@type='submit']")
private SelenideElement BTN_SUBMIT;
```

**Comment by asolntsev** [comment]
Hi @RobertoPegoraro !
Have you tried to search in Selenide repository?

<img width="410" alt="image" src="https://user-images.githubusercontent.com/279773/234656223-4954ac6c-e27c-4102-9c02-a6fe91095b2f.png">

https://github.com/search?q=repo%3Aselenide%2Fselenide%20%40Find&type=code
