### ISSUE TITLE
UnsupportedCommandException while taking browser console logs

### ISSUE THREAD

**Issue by luminorena** [selenide/selenide#2266]
## The problem
I wanted to take browser console logs but got an exception 
`org.openqa.selenium.UnsupportedCommandException: HTTP method not allowed`

## Details
It is reproduced on Firefox browser. While using Chrome, everything works well. 
However, I haven't checked it on other browsers. 

## Environment
* **Selenide Version 6.12.3**
* **Browser Firefox 112.0.2 (64-bit)**
* **Windows 10**

## Code To Reproduce Issue

```
public static void browserConsoleLogs() {
            attachAsText(
                    "Browser console logs",
                    String.join("\n", Selenide.getWebDriverLogs(BROWSER))
            );
    }
```

**Comment by asolntsev** [comment]
@luminorena Yes, Firefox doesn't support this command. 
We cannot do anything to fix it. 

BUT
we could read browser logs using BiDi protocol. Firefox already supports reading logs through BiDi.
