### ISSUE TITLE
Condition with `LocalDate`

### ISSUE THREAD

**Issue by y-lazakovich** [selenide/selenide#2268]
## The problem
It would be nice if Selenide could verify some date field with required pattern format which used in LocalDate class.

Given a field of type `date`:
```java
SelenideElement birthday = $("input#birthday");
LocalDate expected = LocalDate.parse("1981-06-08");
```

We could add few conditions like this:

1. `birthday.shouldHave(date(expected));`
2. `birthday.shouldHave(date(expected, ofPattern("dd.MM.yyyy")));`
3. `birthday.shouldHave(dateBetween(expected.minusDays(2), expected.plusDays(3)));` 

See https://t.me/selenide_ru/49201

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/2281
