### ISSUE TITLE
getAttribute returns null

### ISSUE THREAD

**Issue by RobertoPegoraro** [selenide/selenide#2274]
I'm trying to retrieve the viewBox attribute from my element

```
<svg aria-label="CheckIcon" class="Icon_primary-base__FQZxF" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"></svg>
```

but when I use 

```
element.$("div > svg").getAttribute("viewBox")
```
Selenide returns `null`

For the other attributes like `role`, `class`, `aria-label` it works good only for `viewBox` it returns null

Using javascript in the console I can capture the viewBox attribute:

![image](https://user-images.githubusercontent.com/10342271/236283350-3543c905-3ef2-40da-9ce5-ef714cda7b3c.png)

**Comment by asolntsev** [comment]
@RobertoPegoraro I confirm that I also observe the same issue. 
But we cannot fix it in Selenide. It's webdriver (or even browser) who returns `null` for attribute `viewBox`. Looks like a bug in the browser.

**Comment by RobertoPegoraro** [comment]
Solved using `getDomAttribute()` just in case someone else need this answer in the future.

**Comment by asolntsev** [comment]
@RobertoPegoraro It seems strange to me: according to javadoc, method `WebElement.getDomAttribute()` is usable for "boolean" attributes, and will return either "true" or null: "checked, defer, disabled, hidden, multiple, nowrap,readonly, required, selected, ...".

Anyway, thank you for sharing the information.

**Comment by RobertoPegoraro** [comment]
Here is the explanation: https://github.com/SeleniumHQ/selenium/issues/11996#issuecomment-1536501357
