### ISSUE TITLE
Clicking on disabled elements (buttons) should fail the same way as clicking on covered ones

### ISSUE THREAD

**Issue by angryziber** [selenide/selenide#2288]
## The problem
Flaky test because of Selenide clicking disabled element and not failing.

## Details
In our project, from time to time running post requests disable all submit buttons and then clicking those by Selenide just has no effect, making the test fail later on, which is harder to diagnose.

We propose failing the test if trying to click a disabled button (after the usual timeout of course).
There are no legitimate use cases of actually clicking disabled buttons, because it has no effect by design.
If somebody wants to check if the button is disabled or not, they can just use `shouldBe(disabled)`

## Tell us about your environment
selenide:6.13.1

**Comment by asolntsev** [comment]
@jazzboy65 No, the point is that `$.click()` should check that the element is **enabled**.
Currently `$.click()` only checks that the element is visible.
