### ISSUE TITLE
Capability to use custom locator strategy in @AndroidFindBy @iOSXCUITFindBy

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide#2298]
## The problem
We have added new locators to the selenide-appium in this [PR](https://github.com/selenide/selenide-appium/pull/81)
However, it cannot be used with @AndroidFindBy @iOSXCUITFindBy annotations. Since most apps have the same android and ios flow, most people still use the annotations. It would be great to use something like below

```
@AndroidFindBy(byAttribute("abcd","1234")
@iOSXCUITFindBy(withName("abcd","1234")
private WebElement element;

$(element).shouldBe(visible).click();
```

## Details
Currently if people were using the annotations @AndroidFindBy @iOSXCUITFindBy, they cannot use the AppiumSelectors class
So they end up creating something like

```
private By android_locator = byAttribute("abccd","1234");
private By ios_locator = byName("abccd","1234");

click(android_locator, ios_locator);

public void click(By android_locator, By ios_locator){
 By by = getElementBasedOnMobilePlatform(androidLocator, iosLocator); 
$(by).shouldBe(visible).click()
}
```

## Tell us about your environment
* **Selenide Version**: 
* **Selenide-Appium Version**: 
* **IOS\Android\WEB version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@amuthansakthivel Isn't this feature already solved by com.codeborne.selenide.appium.selector.CombinedBy ?
