### ISSUE TITLE
Selenide trying to find element multiple time for logging purpose

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide#2301]
## The problem
AppiumElementDescriber is trying to get text, tagname multiple times

```java
@AndroidFindBy(
    xpath = "//android.widget.Button[@text=\"Notification Preferences chevron forward\"]")
  @iOSXCUITFindBy(
    xpath = "//XCUIElementTypeButton[contains(@name,'Notification Preferences chevron forward')]")
  private WebElement notificationPreferencesButton;

$(notificationPreferencesButton).shouldBe(visible).click();
```

## Details

Appium Logs

https://gist.github.com/amuthansakthivel/8990c341ea403379f4ccbc16a8f65d1d#file-appium-logs-txt

## Tell us about your environment
* **Selenide Version**: 
* **Selenide-Appium Version**: 2.4.0-SNAPSHOT
* **IOS\Android\WEB version**:

**Comment by asolntsev** [comment]
@amuthansakthivel @BorisOsipov I am trying to understand, do we still have this problem? Please comment if yes.

**Comment by amuthansakthivel** [comment]
@asolntsev - This is not happening anymore. 

https://gist.github.com/amuthansakthivel/2eaf9343eaf20415e2f0222fbb1f700b
