### ISSUE TITLE
Selenide-appium: [unknow locator] is shown in profiler when CombinedBy is used

### ISSUE THREAD

**Issue by DmitryKalbeka** [selenide/selenide#2311]
## The problem
Profiler shows [unknow locator] instead of using locator when the locator is defined via CombinedBy.
Definition of the locator looks like 
`CombinedBy
.android(AppiumBy.accessibilityId(accessibilityId))
.ios(AppiumBy.name(accessibilityId))
`

## Environment
* **Selenide Version**: 6.14.1
* **Selenide-Appium Version**: 2.8.1

![image](https://github.com/selenide/selenide/assets/48528215/bcdad502-56a2-4152-8028-6f1bb17e2074)

**Comment by asolntsev** [comment]
Cool, huge thanks for the early testing of unreleased features! Thumbs up!
I will fix it asap.
