### ISSUE TITLE
Random advertiseement pop up when execute the test

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2313]
## The problem
I have a site https://master.nst.com.my/sports. There is advertisement pop up display randomly for certain menu options. There is no rules regard this. How to detect when there is pop up display then i just close the pop up. 

https://drive.google.com/file/d/1FZMdu1Er_ny9issuzXC8MLdHU9q0-1tY/view?usp=sharing
https://drive.google.com/file/d/1uqPDzPdKX4qrl_nSKeOsOz2kzj93bAjB/view?usp=sharing

## Details
I have a site https://master.nst.com.my/sports. There is advertisement pop up display randomly for certain menu options. There is no rules regard this. How to detect when there is pop up display then i just close the pop up. 

## Tell us about your environment
* **Selenide Version**: 6.14.0
* **Chrome\Firefox\IE Version**: 112 
* **Browser Driver Version**: 
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**: 
* **Selenium Version**: 4.8.3
* **OS Version**: CentOS 9

**Comment by nicholaswkc34** [comment]
Interesting point here.

**Comment by asolntsev** [comment]
@nicholaswkc34 I just leave it here :) 
https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/
