### ISSUE TITLE
Run no-sandbox and headless mode

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2325]
## The problem
How to run chrome in ubuntu server in no sandbox and headless mode since it is report this error when run in teamcity CI/CD tool: 

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally. (unknown error: DevToolsActivePort file doesn't exist)

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 6.12.2
* **Chrome\Firefox\IE Version**: 111
* **Browser Driver Version**:
* **Selenide-Appium Version**: -
* **IOS\Android\WEB version**: -
* **Selenium Version**: 4.8.1
* **OS Version**: Ubuntu Jammy

**Comment by asolntsev** [comment]
See https://selenide.org/2023/05/08/selenide-6.14.0/#remove-flag--no-sandbox

**Comment by nicholaswkc34** [comment]
Can this be achieve in 6.12.1 version?

**Comment by asolntsev** [comment]
@nicholaswkc34 What exactly do you want to achieve in 6.12.1?
Before version 6.14.0, Selenide added flag `--no-sandbox` by default. And always worked in headless mode.

**Comment by nicholaswkc34** [comment]
I tried to launch a browser in Ubutu server and get this error

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: unknown error: Chrome failed to start: exited abnormally. (unknown error: DevToolsActivePort file doesn't exist)

**Comment by asolntsev** [comment]
@nicholaswkc34 Did you find some solution? Did you tried to upgrade to latest Selenide/Selenium/Chrome versions?

Anyway, I am pretty sure this problem is not related to Selenide.

**Comment by xaldoxxx** [comment]
posible solucion

https://github.com/xaldoxxx/BlockDeNotas/blob/main/selenium002.ipynb
