### ISSUE TITLE
Fix Selenide book https://selenide.gitbooks.io/

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2327]
## The problem
It seems that site https://selenide.gitbooks.io/ is not working anymore.

Need to restore it.

## Details

I personally don't remember who and how wrote this book. And how to fix the site.
Need to investigate it.

**Any help is welcome!**

**Comment by oscarvarto** [comment]
@asolntsev Where is the repository for the documentation?

**Comment by asolntsev** [comment]
@oscarvarto If only I knew :) 

Is it possible that domain "gitbooks.io" was just renamed to "gitbook.io"?
At least I found that this URL is working now: https://selenide.gitbook.io/

**Comment by amitkshatriya01** [comment]
What help is needed on documentation? I have been using Selenide for some time now and would like to contribute starting with documentation if there's a need.

**Comment by asolntsev** [comment]
I don't know. All the documentation is here: https://selenide.org/documentation.html

Everything that is missing there is welcome.

**Comment by asolntsev** [comment]
Closing the issue: I hope https://selenide.gitbook.io/ is the right book.
