### ISSUE TITLE
$$ and $$x are missing for Appium selectors

### ISSUE THREAD

**Issue by kamil1014** [selenide/selenide#2333]
## The problem
There are missing $$ and $$x operators for finding Appium collections of elements.
There are only $ and $x operators in SelenideAppium class.

## Details
If there is other way to get collection of appium elements using Selenide please let me know.

## Tell us about your environment
* **Selenide-Appium Version**: 6.15.0
* **OS Version**:  Windows 10

## Code To Reproduce Issue

```java
$$(byText("text"))
```

**Comment by amuthansakthivel** [comment]
For now, you can still use Selenide.$$(by)

I will create a PR to fix it

**Comment by amuthansakthivel** [comment]
@asolntsev we may also want to include 

public SelenideAppiumElement $(WebElement element){
//logic to return SelenideAppiumElement;
}

Also when using pagefactory, we should provide an option to use SelenideAppiumElement reference

  @AndroidFindBy(xpath = "//android.view.ViewGroup[@content-desc=\"store item\"]")
  @iOSXCUITFindBy(xpath = "//*[@name='store item text']")
  private SelenideAppiumElement products;

**Comment by Bpete1979** [comment]
Thanks, came a cross the same issue.

**Comment by asolntsev** [comment]
> we should provide an option to use SelenideAppiumElement reference

It already works. You can declare PO fields (annotated by `@AndroidFindBy` / `@iOSXCUITFindBy`) as `SelenideAppiumElement`.

**Comment by asolntsev** [comment]
> There are missing $$ and $$x operators for finding Appium collections of elements.

May I ask WHY do you need collection of `SelenideAppiumElement`s? 
What are you going to do with such a collection? 

The point of collection is to check texts/attributes of multiple elements with a single call. And it's totally possible with the current `ElementsCollection`. What feature are you actually missing?
