### ISSUE TITLE
Selenium could not start a browser session

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2337]
## The problem
I had setup teamcity on ubuntu server with desktop installed. When i executed the test, I get the following error:

Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
  Host info: host: 'qa-automation-jenkins'

What is the possible reason for this?

@BeforeMethod public void openPage() {

Configuration.timeout = 60000;
Configuration.pageLoadStrategy = "none";
Configuration.baseUrl = "https";
Configuration.browserCapabilities = new ChromeOptions().addArguments("--no-sandbox");
Configuration.browserCapabilities = new ChromeOptions().addArguments("--disable-dev-shm-usage");
Configuration.browserCapabilities = new ChromeOptions().addArguments("--headless");

open("http");
}

## Tell us about your environment
* **Selenide Version**: 6.15.0
* **Chrome\Firefox\IE Version**: 114
* **Browser Driver Version**: -
* **Selenide-Appium Version**:-
* **IOS\Android\WEB version**:-
* **Selenium Version**: 4.8.1
* **OS Version**: Ubuntu Jammy

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@nicholaswkc34 What do you expect from us? There is a lot of possible reasons why this exception might happen. Based on this information, we cannot answer anything. You need to dig more.

**Comment by nicholaswkc34** [comment]
Haiz, I had run out of idea, why the browser cannot start on Linux where it wll start on Windows OS.

**Comment by asolntsev** [comment]
@nicholaswkc34 I am sorry. I wish you a good luck. But anyway, this problem is not about Selenide, it's rather about Selenium/Chrome/chromedriver.
