### ISSUE TITLE
ScreenShooterExtension doesn't work if webdriver is closed in AfterEach

### ISSUE THREAD

**Issue by liaombro** [selenide/selenide#2352]
## The problem
ScreenshooterExtension doesn't take screenshots, if webdriver is closed after the test in AfterEach method.

## Details
I'm using Junit5. I need to take a screenshot when non-Selenide asserts fail (AssertionFailedError). According to Selenide docs, I should use ScreenShooterExtension (https://selenide.org/javadoc/current/com/codeborne/selenide/junit5/ScreenShooterExtension.html).

Now, ScreenShooterExtension implements AfterEachCallback, which is called AFTER AfterEach method. If the browser is closed in AfterEach method, there is nothing to take screenshot from.

![image](https://github.com/selenide/selenide/assets/85120539/d7f47233-d707-4f80-9d0d-83453e60d344)
https://junit.org/junit5/docs/current/user-guide/#extensions-execution-order-overview
![image](https://github.com/selenide/selenide/assets/85120539/d3d4206a-3454-412d-97bf-f41c0aeca7ab)

## Tell us about your environment
* **Selenide Version**:  6.15.0
* **Chrome\Firefox\IE Version**: 114.0.5735.134
* **Browser Driver Version**: 114.0.5735.90
* **Selenide-Appium Version**: 
* **IOS\Android\WEB version**:
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
```
public class ExampleTest {

    @RegisterExtension
    ScreenShooterExtension screenshooter = new ScreenShooterExtension(true).to("build/some/folder");

    @Test
    void testSomething() {
        open("https://google.com");
    }

    @AfterEach
    void tearDown() {
        Selenide.closeWebDriver();
    }
}

```

**Comment by asolntsev** [comment]
@liaombro And?...
Yes, that's true: if you close the webdriver, nobody can take a screenshot anymore. So what is your suggestion?

**Comment by liaombro** [comment]
My suggestion is to take screenshots in AfterTestExecutionCallback, which gets executed before AfterEach methods.

**Comment by asolntsev** [comment]
@liaombro Thank you for the hint, implemented in https://github.com/selenide/selenide/pull/2356
