### ISSUE TITLE
Browser Alert Username and Password Input

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2360]
## The problem
I have a staging website where it need to input username and password before it's loading. How to do it? 

## Details
I have a staging website where it need to input username and password before it's loading. How to do

## Tell us about your environment
* **Selenide Version**: 6.14.0
* **Chrome\Firefox\IE Version**: 112
* **Browser Driver Version**: -
* **Selenide-Appium Version**: -
* **IOS\Android\WEB version**: -
* **Selenium Version**:  4.9.1
* **OS Version**:  Win 10

**Comment by asolntsev** [comment]
You can use method `Selenide.open` with username/password parameters.
RTFT: https://github.com/selenide/selenide/blob/main/statics/src/test/java/integration/BasicAuthTest.java#L13

**Comment by nicholaswkc34** [comment]
Thanks.
