### ISSUE TITLE
Mark Test as Failed if Broken Link

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2361]
## The problem
How to mark test as failed in selenide? 

## Details
How to mark test as failed in selenide? il.

## Tell us about your environment
* **Selenide Version**: 6.15.0
* **Chrome\Firefox\IE Version**: 113 
* **Browser Driver Version**: 113
* **Selenide-Appium Version**: -
* **IOS\Android\WEB version**: -
* **Selenium Version**:  4.9.1
* **OS Version**: Win 10

**Comment by asolntsev** [comment]
@nicholaswkc34 Usually people just use assert to mark test as failed.

Apparently, you planned to write IF like this:
```java
if (stuffWasProperlyLoaded) {
  // TODO mark test as failed
}
```

If so, you can express the same intention with one small assert:
```java
assertTrue(stuffWasProperlyLoaded);
```

**Comment by nicholaswkc34** [comment]
Thanks.
