### ISSUE TITLE
Run cucumber+Selenide in parallel

### ISSUE THREAD

**Issue by leticiafernandez** [selenide/selenide#2365]
## The problem
In our project, tests run in Selenide + Cucumber (Gradle project), now We have a usual execution but We need parallel execution to optimize our time execution. But, I don't find any information about that. Is it possible to do parallel execution?

## Tell us about your environment
* **Selenide Version**: 6.15.0
* **Cucumber Version**: 5.6.0

**Comment by asolntsev** [comment]
@leticiafernandez Selenide allows running tests in parallel. No problems. 
But I don't know about Cucumber.
