### ISSUE TITLE
Driver logs notification with .webdriverLogsEnabled(false)

### ISSUE THREAD

**Issue by vlad-velichko** [selenide/selenide#2366]
## The problem
I know you don't like when we are creating new SelenideDriver, but
when I create `new SelenideDriver(new SelenideConfig().webdriverLogsEnabled(false))`, I see this message in console:
`INFO: Driver logs no longer sent to console by default; https://www.selenium.dev/documentation/webdriver/drivers/service/#setting-log-output`
but expecting to suppress webdriver logs by `webdriverLogsEnabled(false)`

message added to selenium here: https://github.com/SeleniumHQ/selenium/commit/d92b0ae3d77f0b422964b6b24d090c73872a9cac

## Code To Reproduce Issue [ Good To Have ]
```
    public static void main(String[] args) {
        new SelenideDriver(new SelenideConfig()
                .webdriverLogsEnabled(false))
                .open("http://google.com");
    }
```

**Comment by BorisOsipov** [comment]
>but expecting to suppress webdriver logs with webdriverLogsEnabled(false)

The `webdriverLogsEnabled' option controls the collection of browser **driver** logs(chromedriver, geckodriver, etc). 

Logs you complain about to `INFO: Driver logs no longer sent to console by default;` are regular java application logs and should be handled by your logger config.
