### ISSUE TITLE
open() is not navigating to the new url on the same driver instance once a spec/suite is complete.

### ISSUE THREAD

**Issue by cemerick1** [selenide/selenide#2387]
## The problem
The open() method does not appear to be navigating to the new url once a suite has been completed which is causing intermittent fails when tests are run in parallel.

## Details
Once a spec/suite is completed selenide will utilize an already opened driver as designed. However, it appears that the open() method  does not successfully navigate to the correct url once the next suite/spec begins to fire off thus resulting in an assertion  failure because the test is not on the correct page even after extended wait times are applied.  Our temporary solution is to use closeWebDriver() after each spec/suite so that open() properly navigates.

## Tell us about your environment
* **Selenide Version**: 6.16.1
* **Chrome: Version**: 115.0.5790.99 (Official Build) (64-bit)
* **Windows 10 Pro Version**: 10.0.19045 Build 19045 
* **Test Runner**: Gauge 1.5.2 /Gauge Java 0.10.1

**Comment by asolntsev** [comment]
@cemerick1 Sorry, I didn't understand how exactly can I reproduce the problem. Could you, for example, create a small github project that I could run to reproduce it?

From your description, it sounds strange. Method `open()` opens a browser, and holds it in ThreadLocal variable. This browser will be closed only when this thread stops. 
1. If you run another test in the same thread, it will reuse the same browser instance. It will not be closed yet.
2. If you run another test in another thread, it will open another browser instance.

So, there should not be any problems in both cases.

**Comment by cemerick1** [comment]
I will try as best I can. For quick reference we are running in 4 parallel instances.

**Comment by cemerick1** [comment]
I have a hunch that it is occurring when running open() while the page was already in the middle of some action such as clicking a link.  I am struggling to find a public facing web site that I can reproduce this with since our own contains sensitive information. I'll continue to keep poking, but I figured I'd pass this information along.

**Comment by cemerick1** [comment]
I believe this may be a internal issue with our application since I can't reproduce outside of our company.  @asolntsev not sure if you wanna keep in the back of your mind for the future, but I put a workaround in our test repo to deal with our applications shortcomings. God Bless and thanks for your help!

**Comment by asolntsev** [comment]
@cemerick1 Thank you for sharing information. Let's close it now. We can always reopen the ticket if needed.
