### ISSUE TITLE
Name change request

### ISSUE THREAD

**Issue by DominikKrypel** [selenide/selenide#2390]
https://github.com/selenide/selenide/blob/167bf820524054a15f84902e546d4934d5933a8a/src/main/java/com/codeborne/selenide/SelenideElement.java#L141

due to the fact that Steven Seagal is faithful to Russia, is it possible to change to someone else? Please change it to, for example, Volodymyr Zelensky :)

**Comment by asolntsev** [comment]
Yes. Sure.
And I should rework some other test data in src/test/resources...
