### ISSUE TITLE
Setup Android/Iphone Project

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2391]
## The problem
Dear all, I have a selenide web project running fine on teamcity service. Now, I need to enhance the project with mobile testing features. Should I create another project for Android testing purposes or merge with web project but using different classes. 

## Details
Please share how to start on selenide-appium code. 

## Tell us about your environment
* **Selenide Version**: 6.15.0
* **Chrome\Firefox\IE Version**: 114
* **Browser Driver Version**: 113
* **Selenide-Appium Version**: 6.15.0
* **IOS\Android\WEB version**: Android 13
* **Selenium Version**: 4.8.1
* **OS Version**:  Win 10

**Comment by amuthansakthivel** [comment]
You can have it in the same project @nicholaswkc34 

The sample combined framework can be found [here](https://github.com/amuthansakthivel/OrangeHrmSelenideFramework)

Sample framework where you automate only mobile apps can be found [here](https://github.com/amuthansakthivel/SelenideAppiumFramework)

**Comment by nicholaswkc34** [comment]
Thanks @amuthansakthivel

**Comment by nicholaswkc34** [comment]
Closed issue
