### ISSUE TITLE
feature request: highlight element capability

### ISSUE THREAD

**Issue by dacloutier-logmein** [selenide/selenide#2395]
## The problem
when I code / debug tests or more often need to "demo" what occurs, I will often resort to highlighting elements I am about to interact with. Visual cues will often covey more than words, wether we like it or not.

## Details
I've been using a similar piece of code for a while now (it's been stripped down to remove error management) to do precisely that. The problem is that down the run, this add a little bit of noise compared to something that *could* possibly be natively handled by selenide (I am pretty confident that I am not the only one that would like this). Let's say that  the config could handle a "highlightElement" property or something along those lines.

the ask is, could we get some functionality a that would do this ?

```java
public void highlightSelenideElement(@NonNull final SelenideElement selenideElement)
  {
        final String oldStyle = selenideElement.getAttribute("style");
        Selenide.executeJavaScript(
            "arguments[0].setAttribute('style', 'background: yellow; border: 2px solid red;" +
                "color:black;return true;');", selenideElement.getWrappedElement());
        Selenide.sleep(200); // wait just long enough for the highlight to show up
        Selenide.executeJavaScript(
            String.format("arguments[0].setAttribute('style', '%s');", oldStyle),
            selenideElement.getWrappedElement());
 }
```

UPD It's a duplicate of https://github.com/selenide/selenide/issues/1277

**Comment by y-lazakovich** [comment]
On my previous project I tried to use this solution:
https://github.com/selenide-examples/gmail/blob/main/test/org/selenide/examples/gmail/Highlighter.java

It worked and at the same time broke application
It was angular and there were a lot conflict after implemented Highlighter examples

**Comment by dacloutier-logmein** [comment]
> I added method `$.highlight()` in PR #2481

Nice Thanks a lot !

Next step will be, as you hinted, the possibility to have like a global "highlight" flag, that would highlight any element that is being interacted with.
