### ISSUE TITLE
Google Vignette (Random Advertisement) Interrupt Test Flow

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2404]
## The problem
Dear All, I had several automated test web sites which have Google Vignette. The google vignette have dynamic iframe id. I cannot close it using automation code due to different google vignette button and different iframe id. 

Questions: 
How to deal with this kind of situation?
Any others solution?

I tried with adblock extension but still not able to block it. 

## Tell us about your environment
* **Selenide Version**: 6.15.0
* **Chrome\Firefox\IE Version**: 114
* **Browser Driver Version**: 114
* **Selenide-Appium Version**: 6.15.0
* **IOS\Android\WEB version**: -
* **Selenium Version**: 4.9.1
* **OS Version**: Win 10

## Code To Reproduce Issue [ Good To Have ]
public void closeAdPanel() {
        SelenideElement adPanel = $x("//*[@id=\"ad_position_box\"]");

        switchTo().frame($x("//*[@id=\"aswift_1\"]"));
        if (adPanel.is(Condition.visible)) {
            // Different type of advertisement closing btn
            if ($x("//*[@id=\"dismiss-button\"]/div/span").is(Condition.visible)) {
                switchTo().frame($x("//*[@id=\"aswift_1\"]"));
                $x("//*[@id=\"dismiss-button\"]/div/span").click();
                switchTo().defaultContent();
            } else if ($x("//*[@id=\"dismiss-button\"]/div/svg/path[1]").is(Condition.visible)) {
                switchTo().frame($x("//*[@id=\"aswift_1\"]"));
                $x("//*[@id=\"dismiss-button\"]/div/svg/path[1]").click();
                switchTo().defaultContent();
            } else if ($x("//*[@id=\"dismiss-button\"]/div/svg").is(Condition.visible)) {
                switchTo().frame($x("//*[@id=\"aswift_1\"]"));
                $x("//*[@id=\"dismiss-button\"]/div/svg").click();
                switchTo().defaultContent();
            }

        } else if ($x("//*[@id=\"dismiss-button\"]/div/span").is(Condition.visible)) {
            switchTo().frame($x("//*[@id=\"aswift_1\"]"));
            $x("//*[@id=\"dismiss-button\"]/div/span").click();
            switchTo().defaultContent();
        }
    }

**Comment by nicholaswkc34** [comment]
Please help me. Thanks a lot.

**Comment by nicholaswkc34** [comment]
The example of the site are www.nst.com.my and www.bharian.com.my

**Comment by asolntsev** [comment]
@nicholaswkc34 Sorry, but I don't understand how can we help you. 

NB! I highly recommend to disable all kinds of advertisements in test environment.

**Comment by nicholaswkc34** [comment]
Disable advertisement feature is last sortation. Any better approach?? Like block the ad using some extension.

**Comment by asolntsev** [comment]
@nicholaswkc34 Why do you think it's the last? I believe the opposite: it's the best approach. Disable ads in test environment. You want to test your business functionality, but ads not your functionality. It's just a noise. 

Anyway, this question is not related to Selenide.
