### ISSUE TITLE
Swipe and Scroll don't work on the latest selenide appium 

### ISSUE THREAD

**Issue by AlllxT** [selenide/selenide#2410]
Hello,

swipe actions by : 
  `$(element).swipe(AppiumSwipeOptions.left());`
  `$(element).swipe(AppiumSwipeOptions.right());`
  `$(element).swipe(AppiumSwipeOptions.left(3));`
  `$(element).swipe(AppiumSwipeOptions.right(3));`

doesnt work at all

        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide-appium</artifactId>
            <version>6.17.0</version>
        </dependency>

**Comment by asolntsev** [comment]
@naveensrinivasan Are you aware?

**Comment by AlllxT** [comment]
> @naveensrinivasan Are you aware?

also scroll doesn't work too

**Comment by AlllxT** [comment]
any updates?)

**Comment by asolntsev** [comment]
@amuthan-sakthivel @amuthansakthivel Are you aware?

**Comment by amuthansakthivel** [comment]
@asolntsev - I will check this today.

There is almost nill chance for the scroll not to work. 

@AlllxT - Could you please share the appium log. Also if possible, please share any open-source app where I could test swipe right and left

**Comment by amuthansakthivel** [comment]
@AlllxT - I have tested the scroll and it is working fine. But I don't have any app to test swipe but it should work

https://github.com/amuthansakthivel/TheOneFramework - Clone this repo and run

`mvn clean test -Dselenide.browser=com.tmb.provider.mobile.local.ApiDemosAndroidAppProvider -Dgroups=api-demos-mobile`

**Comment by AlllxT** [comment]
> @asolntsev - I will check this today.
> 
> There is almost nill chance for the scroll not to work.
> 
> @AlllxT - Could you please share the appium log. Also if possible, please share any open-source app where I could test swipe right and left
> 
> @AlllxT - Can you also confirm whether the scroll is working in selenide 6.16 and not in 6.17

my issue is related to mobile native app. let me post in somewhere and also I need to prepare the logs for you

**Comment by AlllxT** [comment]
> @asolntsev - I will check this today.
> 
> There is almost nill chance for the scroll not to work.
> 
> @AlllxT - Could you please share the appium log. Also if possible, please share any open-source app where I could test swipe right and left
> 
> @AlllxT - Can you also confirm whether the scroll is working in selenide 6.16 and not in 6.17

Android 9( API 28)
Steps to repoduce:
1. download the test app - https://github.com/AlllxT/testNativeAndtroidApp/tree/main/testApp/src/main/resources
2. Open it.
3. Select "Touch Actions" on main screen
4. Do swipe

<img width="605" alt="image" src="https://github.com/selenide/selenide/assets/27723645/86f6ce29-b491-4e39-943b-6ba64a825232">

<img width="502" alt="image" src="https://github.com/selenide/selenide/assets/27723645/329e878c-4416-4563-b360-c3eb3c20c56a">


Appium logs:
```

[HTTP] --> POST /session/b90bf268-1172-4099-a987-e36c0bb71a34/element
[HTTP] {"using":"id","value":"io.selendroid.testapp:id/LinearLayout1"}
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Calling AppiumDriver.findElement() with args: ["id","io.selendroid.testapp:id/LinearLayout1","b90bf268-1172-4099-a987-e36c0bb71a34"]
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Valid locator strategies for this request: xpath, id, class name, accessibility id, css selector, -android uiautomator
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Waiting up to 0 ms for condition
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Matched '/element' to command name 'findElement'
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Proxying [POST /element] to [POST http://127.0.0.1:8200/session/ff2c1096-2bfe-4e52-b3a1-89aecd3f3926/element] with body: {"strategy":"id","selector":"io.selendroid.testapp:id/LinearLayout1","context":"","multiple":false}
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Got response with status 200: {"sessionId":"ff2c1096-2bfe-4e52-b3a1-89aecd3f3926","value":{"ELEMENT":"00000000-0000-01ed-ffff-ffff00000021","element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01ed-ffff-ffff00000021"}}
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Responding to client with driver.findElement() result: {"element-6066-11e4-a52e-4f735466cecf":"00000000-0000-01ed-ffff-ffff00000021","ELEMENT":"00000000-0000-01ed-ffff-ffff00000021"}
[HTTP] <-- POST /session/b90bf268-1172-4099-a987-e36c0bb71a34/element 200 26 ms - 137
[HTTP] 
[HTTP] --> GET /session/b90bf268-1172-4099-a987-e36c0bb71a34/element/00000000-0000-01ed-ffff-ffff00000021/displayed
[HTTP] {}
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Calling AppiumDriver.elementDisplayed() with args: ["00000000-0000-01ed-ffff-ffff00000021","b90bf268-1172-4099-a987-e36c0bb71a34"]
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Matched '/element/00000000-0000-01ed-ffff-ffff00000021/attribute/displayed' to command name 'getAttribute'
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Proxying [GET /element/00000000-0000-01ed-ffff-ffff00000021/attribute/displayed] to [GET http://127.0.0.1:8200/session/ff2c1096-2bfe-4e52-b3a1-89aecd3f3926/element/00000000-0000-01ed-ffff-ffff00000021/attribute/displayed] with no body
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Got response with status 200: {"sessionId":"ff2c1096-2bfe-4e52-b3a1-89aecd3f3926","value":"true"}
[debug] [AndroidUiautomator2Driver@ffde (b90bf268)] Responding to client with driver.elementDisplayed() result: true
[HTTP] <-- GET /session/b90bf268-1172-4099-a987-e36c0bb71a34/element/00000000-0000-01ed-ffff-ffff00000021/displayed 200 10 ms - 14
[HTTP] 

```

**Comment by AlllxT** [comment]
> @asolntsev - I will check this today.
> 
> There is almost nill chance for the scroll not to work.
> 
> @AlllxT - Could you please share the appium log. Also if possible, please share any open-source app where I could test swipe right and left
> 
> @AlllxT - Can you also confirm whether the scroll is working in selenide 6.16 and not in 6.17

will check Scroll this evening or tomorrow... I have no much time now :( sorry

**Comment by amuthansakthivel** [comment]
@AlllxT - I have downloaded that app and checked it. The screen you mentioned does not have valid element to scroll to or perform swipe.

Current implementation scrolls to an element which is actually present. In the app you shared, the screen itself is not scrollable.

For more details, please check this [comment](https://github.com/selenide/selenide/issues/2410#issuecomment-1676229813)

@asolntsev - I would suggest to go ahead and close this issue ticket
