### ISSUE TITLE
No Release 6.17.0 on GitHub

### ISSUE THREAD

**Issue by djbrown** [selenide/selenide#2418]
Hello, I just saw on https://selenide.org/quick-start.html and https://central.sonatype.com/artifact/com.codeborne/selenide/ that the newest version is 6.17.0.
But on GitHub there are only releases 6.16.1 and before.
Where is 6.17.0 on GitHub?

UPDATE: I just saw that there actually is a tag 6.17.0, but no Release.
Maybe you just have to add some description as to what changed

**Comment by nikitakovaliov92** [comment]
for some reason, this exists only here

https://github.com/selenide/selenide/blob/main/CHANGELOG.md

**Comment by asolntsev** [comment]
@djbrown @nikitakovaliov92 Ooops, forgot to create the release on github. :) 

Thank you, release created: https://github.com/selenide/selenide/releases/tag/v6.17.0
