### ISSUE TITLE
Tests won't run after upgrade to Chrome 116

### ISSUE THREAD

**Issue by ccea-dev-team** [selenide/selenide#2423]
## The problem
Hi, My Chrome browser version was updated to 116 earlier today and now my Selenide tests won't run.

## Details
Console errors : 

[main] INFO com.codeborne.selenide.impl.WebDriverThreadLocalContainer - No webdriver is bound to current thread: 1 - let's create a new webdriver
[main] INFO com.codeborne.selenide.webdriver.SelenideNettyClientFactory - Changed readTimeout from PT3M to PT1M30S
FAILED CONFIGURATION: @BeforeClass setUp
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start.
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_345'
Driver info: driver.version: SelenideDriver
	at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:203)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:119)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
	... 54 more

## Tell us about your environment
* **Selenide Version**:  6.17.0
* **Chrome Version**. 116
* **Selenium Version**:  4.11
* **OS Version**:  win 10

**Comment by ccea-dev-team** [comment]
Think some other people getting this issue - possible bug in Selenium - https://github.com/SeleniumHQ/selenium/issues/12570

**Comment by ccea-dev-team** [comment]
Is there something I have to add to firewall/network rules after using selenium-manager instead of webdrivermanager?

**Comment by BorisOsipov** [comment]
@ccea-dev-team Can't reproduce. Works just fine.

>Is there something I have to add to firewall/network rules for using selenium-manager instead of webdrivermanager?

Perhaps. It seems better to address such questions to selenim repo, where selenium-manager is developed.

**Comment by ATIsname** [comment]
I have the same issue, but on mac OS. At the same time on windows 10 - it works correctely.
selenide version: 6.17.0
