### ISSUE TITLE
Unable to download a file without href with FileDownloadMode as Folder

### ISSUE THREAD

**Issue by Soumendu-Khilar** [selenide/selenide#2426]
## The problem
Scenario:
Login to the UI. Click on a button. CSV is downloaded.
I am trying to download a file which does not have a `href` attribute. I am using the below code to do it.

```java
// Providing the custom folder path:
Configuration.downloadsFolder=System.getproperty("user.dir")+"/UsageReports";
// File download code:
$(btnCsvDwnld).download(DownloadOptions.using(FileDownloadMode.FOLDER)
                        .withTimeout(Duration.ofMinutes(5)));
```

In this case the file download is started and completed in the UI but there is no folder created as UsageReports and eventually the download fails after 5 minutes of timeout.

Now, I change the downloadsFolder to an already existing folder name:
```java
Configuration.downloadsFolder="Users/<username>/Downloads";
```

For this I get the error message as :
```java
java.io.FileNotFoundException: Failed to download file in 300000 ms: files in /Users/<username>/Downloads haven't been modified for 398990 ms.
```

The File Download code works fine with the below combination:
```java
Configuration.downloadsFolder="Users/<username>/Downloads";
$(btnCsvDwnld).download(DownloadOptions.using(FileDownloadMode.FOLDER));
```

But this code sometimes fails with a timeout error since the default timeout is 4000ms and the file download take more time than this.

## Tell us about your environment
* **Selenide Version**: 6.10.1
* **Chrome Version**: 116
* **Browser Driver Version**: 115
* **Selenium Version**: 4.11.0

**Comment by asolntsev** [comment]
@Soumendu-Khilar Let me ask: do you use the value returned by method `$.download()`? 
Like this:
```java
File usageReport = $(btnCsvDwnld).download(DownloadOptions....withTimeout(...));
assertThat(usageReport.getName()).matches("my_usage_report.*\\.csv");
```

This is the proper way of downloading files.
In this case, 
1. you don't need to set `Configuration.downloadsFolder`
2. you don't taker if folder `UsageReports` was created or not.
3. you don't need to search the downloaded file in any folders.

Just check the returned `File` instance. 

See https://youtu.be/GwHG550moGc

**Comment by Soumendu-Khilar** [comment]
My project path is /Users/<username>/Projects/<ProjectName>. By default the file should be downloaded to build/downloads under <ProjectName> if there is no Configuration.downloadsFolder set is my assumption but that does not happen.
If I do not set the downloads folder path the file gets downloaded to my user Downloads folder (Users/<username>/Downloads) instead of the default build/downloads. And the test case keeps on waiting for the file to be present in build/downloads folder which was never created under the <ProjectName> directory and eventually failing once timeout is reach with the below error message.
**java.io.FileNotFoundException: Failed to download file in 30000 ms.**

here is the file path of the downloaded file
/Users/<Username>/Downloads/filename

Am I doing anything wrong here??

I am using ChromeOptions to set the Chrome capabilities. Is that interfering in any way?

**Comment by asolntsev** [comment]
Hi.
The question is, how do you initialize webdriver? Do you create it by yourself?

**Comment by Soumendu-Khilar** [comment]
Yes, I create the webdriver myself and then use Selenide's opn(url) method to open the webpage.
Here is my driver initialization code.

ChromeOptions options = new ChromeOptions();
                options.addArguments("--remote-allow-origins=*");
                options.addArguments("enable-automation");
                options.addArguments("--no-sandbox");
                options.addArguments("--disable-infobars");
                options.addArguments("--disable-dev-shm-usage");
                options.addArguments("--disable-browser-side-navigation");
                options.addArguments("--disable-gpu");
                options.addArguments("--disable-extensions");
                options.addArguments("--ignore-ssl-errors=yes");
                options.addArguments("--ignore-certificate-errors");
                preferences = new Hashtable<String, Object>();
                preferences.put("profile.default_content_settings.popups", 0);
                preferences.put("download.default_directory", System.getProperty("user.dir")+"/build/downloads");
                options.setExperimentalOption("prefs", preferences);

                driver = new ChromeDriver(options);
                setWebDriver(driver);

**Comment by asolntsev** [comment]
@Soumendu-Khilar That's what I thought. You don't really need to create the webdriver by yourself. Selenide already does it. 

Just call `open` - and it works:
```java
open(url);
File f = $(...).download();
```

Don't add options that are already added by Selenide out-of-the-box.

P.S. If you really need to add some option which is not added by Selenide, use a shorter code:

```java
  ChromeOptions options = new ChromeOptions();
  options.addArguments("--disable-browser-side-navigation");
  Configuration.browserCapabilities = options;

  open(url);
  File f = $(...).download();
```
