### ISSUE TITLE
Chrome Driver 116 unable to download Using Webdriver manger <version>4.2.2</version> Selenide version 5.15.1

### ISSUE THREAD

**Issue by koteswaraotekkem** [selenide/selenide#2429]
## The problem
Briefly describe the issue you are experiencing (or the feature you want to see added to Selenide).
Tell us what you were trying to do and what happened instead. 

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 
* **Chrome\Firefox\IE Version**: 
* **Browser Driver Version**:
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@koteswaraotekkem Yes, Selenide version 5.x is very old version. And ChromeDriver 116 is very fresh version.
It's quite expected that old Selenide doesn't support new browsers. 

The only way to fix it is to UPDATE SELENIDE.
Just use the latest version. It always works with new browsers.
