### ISSUE TITLE
Extent Test consolidate multiple run testing result

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2441]
## The problem
Dear All, I had coded selenide automation testing and I need consolidate multiple run testing result separate by day 1 day 2 day 3. 

## Details
I know its not related to Selenide but i really need help. 

## Tell us about your environment
* **Selenide Version**: 6.15.0
 **Chrome\Firefox\IE Version**: 114
* **Browser Driver Version**: Browser 117
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version**: 4.18.0
* **OS Version**: Win 10

**Comment by asolntsev** [comment]
Sorry, but this is really not related to Selenide. I personally never used extent report, and I have no idea how to consolidate multiple runs.
