### ISSUE TITLE
Selenide-Appium

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2447]
## The problem
I about to test mobile application. I thought of using selenide-appium. Is there any examples in maven. 

How to run it on CI/CD using teamcity?

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment
* **Selenide Version**: 6.15.0
* **Chrome\Firefox\IE Version**: 116 
* **Browser Driver Version**: 113
* **Selenide-Appium Version**: -
* **IOS\Android\WEB version**: Android
* **Selenium Version**:  4.1
* **OS Version**: Windows 10

**Comment by amuthansakthivel** [comment]
you can find reference project below using maven but CI is configured with github actions. You can customise it for teamcity.

https://github.com/amuthansakthivel/TheOneFramework/blob/main/.github/workflows/run-mobile-tests.yml
https://github.com/amuthansakthivel/TheOneFramework/blob/main/.github/workflows/run-mobile-tests-in-lambda-test.yml

https://github.com/amuthansakthivel/TheOneFramework

**Comment by asolntsev** [comment]
Hi @nicholaswkc34 !
Project `selenide-appium` contains its own integration tests. It's absolutely not important if you use Maven or Gradle for building your project.

1. https://github.com/selenide/selenide/tree/main/modules/appium/src/test/java/it/mobile
2. https://github.com/selenide-examples/selenide-appium
