### ISSUE TITLE
Method `$.type()` enters only the last characters in Android

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2459]
## The problem
Method `$("foo").type(TypeOptions.text("1234").clearFirst(false))` doesn't just enter text "1234". Instead, it:
1. enters "1"
2. removes "1",
3. enters "2"
4. removes "2"
5. enters "3"
6. etc.

In the end, the field contains only text "4" (but should contain "1234").

## Tell us about your environment
* **Selenide Version**: 6.17.2
* **OS Version**: Android

## Code To Reproduce Issue

```java
options.setAppPackage("com.google.android.dialer");
options.setAppActivity("com.google.android.dialer.extensions.GoogleDialtactsActivity");

SelenideAppium.$(By.id("com.google.android.dialer:id/search_box_start_search")).click();
SelenideAppium.$(By.id("com.google.android.dialer:id/search_view")).type(TypeOptions.text("1234").clearFirst(false));
```

**Comment by asolntsev** [comment]
As far as I see, it's rather a bug in Appium. 
When an input field already contains value "1", and I call method `$.sendKeys("2")`, it REPLACES "1" by "2". 
(But webdriver spec says `sendKeys` should APPEND character).

In Appium log I see that Appium translates `sendKeys` method to `AppiumDriver.setValue()` call:

```
[HTTP] --> POST /wd/hub/session/3d6f10a8-af06-4435-b5c3-8aec9ec0f233/element/00000000-0000-05e4-ffff-ffff00000033/value
[HTTP] {"id":"00000000-0000-05e4-ffff-ffff00000033","text":"2","value":["2"]}
[debug] [AndroidUiautomator2Driver@3a42 (3d6f10a8)] Calling AppiumDriver.setValue() with args: [["2"],"00000000-0000-05e4-ffff-ffff00000033","3d6f10a8-af06-4435-b5c3-8aec9ec0f233"]
[debug] [AndroidUiautomator2Driver@3a42 (3d6f10a8)] Matched '/element/00000000-0000-05e4-ffff-ffff00000033/value' to command name 'setValue'
[debug] [AndroidUiautomator2Driver@3a42 (3d6f10a8)] Added 'value' property ["2"] to 'setValue' request body
[debug] [AndroidUiautomator2Driver@3a42 (3d6f10a8)] Proxying [POST /element/00000000-0000-05e4-ffff-ffff00000033/value] to [POST http://127.0.0.1:8200/session/ad513b2f-b644-4f7c-9628-41468f54247e/element/00000000-0000-05e4-ffff-ffff00000033/value] with body: {"elementId":"00000000-0000-05e4-ffff-ffff00000033","text":"2","replace":false,"value":["2"]}
[debug] [AndroidUiautomator2Driver@3a42 (3d6f10a8)] Got response with status 200: {"sessionId":"ad513b2f-b644-4f7c-9628-41468f54247e","value":null}
[debug] [AndroidUiautomator2Driver@3a42 (3d6f10a8)] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/3d6f10a8-af06-4435-b5c3-8aec9ec0f233/element/00000000-0000-05e4-ffff-ffff00000033/value 200 997 ms - 14
[HTTP] 
```

**Comment by dillibabuj** [comment]
@asolntsev @amuthansakthivel here are my findings : 
sendKeys of Actions class seems to be webdriver spec compliant. Below code does seems to type out "1234" in android and ios.

`Actions actions = new Actions(driver);`
`actions.sendKeys("12").perform();`
`actions.sendKeys("34").perform();`

There seems to have been [options for whether to replace the text](https://github.com/appium/appium/pull/3402) or not in older versions of appium, not sure if they are still available or it's replaced/implemented differently in the latest versions. Someone from appium team can answer ? 

And also I came across few capabilities/settings, that might actually needs to be looked at if they fulfill / assist in the functionality our 'type' command is trying to implement : [sendKeyStrategy](https://github.com/appium/java-client/issues/217) & [keyInjectionDelay](https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/Setting.java#L36) . You or any other Appium expert can comment on these I believe.

**Comment by amuthansakthivel** [comment]
@dillibabuj - Thanks for a clear explanation. 

@asolntsev - Should I use action class for type instead of sendkeys?

**Comment by asolntsev** [comment]
@amuthansakthivel I don't know. Yes, probably (if it really works better).

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/2544
