### ISSUE TITLE
[Question] How can selenide duplicate current tab in browser?

### ISSUE THREAD

**Issue by vladyslav-ko** [selenide/selenide#2462]

**Comment by rosolko** [comment]
Looks like no. There is only solution with a new tab using url from current one

**Comment by vladyslav-ko** [comment]
I found solution with only Selenide using.
String currentURL = .....getCurrentUrl();
Selenide.switchTo().newWindow([WindowType.TAB](http://windowtype.tab/));
Selenide.switchTo().window(1);
[Selenide.open](http://selenide.open/)(currentURL);

**Comment by asolntsev** [comment]
@vladyslav-ko Almost. You can remove line `Selenide.switchTo().window(1);` because the previous line `switchTo(newWindow)` already does it.
