### ISSUE TITLE
issue - Selenide 6.18.0 Collections - Errors in comparison

### ISSUE THREAD

**Issue by antonpimnev** [selenide/selenide#2469]
## The problem
When the elements themselves are displayed in the test results: the Actual result is displayed incorrectly, and the actually existing and displayed elements are not found. 

## Details
№1
```java
List size mismatch (expected: 13, actual: 14)
Actual (14): [00. Dadata.ru, 01. ИНН / КПП / ОГРН, 02. Название, 03. Название полное, 04. Юридический адрес, 05. Фактический адрес, 06. Руководитель, 07. Состояние, действующая, 08. ОКВЭД, 09. Тип подразделения, 10. ОПФ, 11. Тип организации, 12. Выдача ОГРН]
Expected (13): [00. Dadata.ru, 01. ИНН / КПП / ОГРН, 02. Название, 03. Название полное, 04. Юридический адрес, 05. Фактический адрес, 06. Руководитель, 07. Состояние, действующая, 08. ОКВЭД, 09. Тип подразделения, 10. ОПФ, 11. Тип организации, 12. Выдача ОГРН]
Collection: #element/.gp[2]/b
```

№2
if add to Expected element "" then:
```java
Text #7 not found: "07. Состояние, действующая"
Actual (14): [00. Dadata.ru, 01. ИНН / КПП / ОГРН, 02. Название, 03. Название полное, 04. Юридический адрес, 05. Фактический адрес, 06. Руководитель, 07. Состояние, действующая, 08. ОКВЭД, 09. Тип подразделения, 10. ОПФ, 11. Тип организации, 12. Выдача ОГРН]
Expected (14): [00. Dadata.ru, 01. ИНН / КПП / ОГРН, 02. Название, 03. Название полное, 04. Юридический адрес, 05. Фактический адрес, 06. Руководитель, 07. Состояние, действующая, 08. ОКВЭД, 09. Тип подразделения, 10. ОПФ, 11. Тип организации, 12. Выдача ОГРН, ]
Collection: #element/.gp[2]/b
```

## Environment
* **Selenide Version**: 6.18.0
* **Selenium Version**: 4.11.0 (force cause errors with 4.12.0)
* **Chrome Version**: 115.0
* **Browser Driver Version**: Selenium WebDriver v. 4.11.0 build revision: 040bc5406b
* **OS Version**: Winwows 10 64-bit

## Code To Reproduce Issue
```java
$("#element").$$(".gp").get(2).$$("b")
                    .shouldHave(textsInAnyOrder("00. Dadata.ru",
                            "01. ИНН / КПП / ОГРН",
                            "02. Название",
                            "03. Название полное",
                            "04. Юридический адрес",
                            "05. Фактический адрес",
                            "06. Руководитель",
                            "07. Состояние, действующая",
                            "08. ОКВЭД",
                            "09. Тип подразделения",
                            "10. ОПФ",
                            "11. Тип организации",
                            "12. Выдача ОГРН",
                            ""));
        });
```

**Comment by asolntsev** [comment]
@antonpimnev How can I reproduce the problem? What site are you using?

For me, text checks work nicely. For example:

```java
    open("https://selenide.org/users.html");
    $$("#user-tags .tag").first(3)
      .shouldHave(texts("usa", "ukraine", "europe"));
```

**Comment by antonpimnev** [comment]
> @antonpimnev How can I reproduce the problem? What site are you using?
> 
> For me, text checks work nicely. For example:
> 
> ```java
>     open("https://selenide.org/users.html");
>     $$("#user-tags .tag").first(3)
>       .shouldHave(texts("usa", "ukraine", "europe"));
> ```

It is internal CRM-system unfortunately.

My theory about incorrect trim() somewhere inside Selenide Collections codebase.
And more complex elements inside Actual Collection like "07. Состояние, действующая" with punctuation marks inside, such as commas.

**Comment by asolntsev** [comment]
@antonpimnev  ok, but how can I fix the problem if I cannot reproduce the problem?

**Comment by antonpimnev** [comment]
@asolntsev may be pending status atm.
before someone else catch problem like this

**Comment by Au6ojlut** [comment]
I could be wrong, but...

the problem could be related to recent speed-up changes for "texts" condition, where JavaScript is used instead of `WebElement`'s `getText`. If I'm not mistaken, `getText` returns `visible` text (not only in terms of CSS visibility), so special characters were filtered out. However, JavaScript code doesn't do this.

Also, the errors messages do not escape special characters in string, so they are left invisible...

like
`This is a string with a zero-width​space`

`This is a string with a zero-width\u200Bspace`
 
:thinking:

**Comment by asolntsev** [comment]
@Au6ojlut 
> the problem could be related to recent speed-up changes for "texts" condition, where JavaScript is used instead of `WebElement`'s `getText`. If I'm not mistaken, `getText` returns `visible` text (not only in terms of CSS visibility), so special characters were filtered out. However, JavaScript code doesn't do this.

Good point! Yes, it's the problem.
JS implementation of `getTexts()` just used `innerText`, while webdriver `getText()` uses more complex [logic](https://w3c.github.io/webdriver/#get-element-text) incl. stripping invisible spaces. Grrr... 

Should be fixed by https://github.com/selenide/selenide/pull/2482
