### ISSUE TITLE
Unnecessary hubUrl condition in SelenoidClient

### ISSUE THREAD

**Issue by Plodick** [selenide/selenide#2475]
## The problem
When downloading a file or using the clipboard, the following exception occurs:
`java.lang.IllegalArgumentException: Expect hub url to end with /wd/hub, but received: <hub_url>`

## Details
This occurs due to a check in the client that the selenoid hub url must end with a /hub/url. This condition is not always met on the selenoid side.

## Tell us about your environment
* **Selenide Version**: 6.18.0

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/2476
