### ISSUE TITLE
Cannot find Selenide class - Compilation failure

### ISSUE THREAD

**Issue by amuthansakthivel** [selenide/selenide#2478]
## The problem
Cannot run selenide test in the Selenide version 6.18.0. 

If I downgrade to 6.17.0, it works. I suspect this is something with my setup. Not sure what

## Details
Clone https://github.com/amuthansakthivel/TheOneFramework

run `mvn clean test -Dgroups=web` 

Getting compilation failure that the class Selenide inside com.codeborne.selenide is not found

https://gist.github.com/amuthansakthivel/07fe0746a366bf26b1476dc68c9e7831

## Tell us about your environment
* **Selenide Version**:
* **Chrome\Firefox\IE Version**: chrome 116.0
* **Browser Driver Version**:
* **Selenide-Appium Version**: 6.18.0
* **IOS\Android\WEB version**:
* **Selenium Version**: 
* **OS Version**:  MacOS M1 - Ventura: 13.4.1

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by exmike** [comment]
Hello @amuthansakthivel I tried to reproduce your problem, ran tests, but I got errors after compilation and the problem could not be reproduced.
https://gist.github.com/exmike/ac8c1d6ef3b801ca32b0f644b1b4f6e2

**Comment by amuthansakthivel** [comment]
> Hello @amuthansakthivel I tried to reproduce your problem, ran tests, but I got errors after compilation and the problem could not be reproduced. https://gist.github.com/exmike/ac8c1d6ef3b801ca32b0f644b1b4f6e2

Thanks @exmike for trying this. The problem you quoted is different and may be because of selenium-chrome compatible issue. But it compiled successfully. This is weird. If there is a problem with my java version or installation, the compilation for other programs should fail or for selenide 6.17 should fail.

**Comment by asolntsev** [comment]
@amuthansakthivel I also cannot reproduce the problem. The compilation of works nicely with both Selenide 6.17.0 and 6.18.0.
