### ISSUE TITLE
elements collection returns element by non existing index

### ISSUE THREAD

**Issue by Elvintest** [selenide/selenide#2480]
Hello. For instance i have an elements collection which has size 1(it might happen by inaccuracy of qa) 
Selenide.$$(".className").size() = 1
why if i try to get the second element of this collection i get the first one? I guess i should get indexOutBonds exception or something like this but instead of expected behaviour i get the single element of my collection
Selenide.$$(".className").get(1) returns .className[1]
Selenide.$$(".className").get(10) returns .className[10]

## Tell us about your environment
* **Selenide Version 6.17.2**: 
* **Chrome  116.0.5845.188**: 
* **Browser Driver Version 115**:
* **Selenium WebDriver v. 4.11.0**: 
* **OS Version Win 11**:

**Comment by asolntsev** [comment]
@Elvintest it's because Selenide uses lazy loading principle for most operations. You will get the expected exception when you try to use these elements.

E.g. 
$$.get(0).click(); // works
$$.get(1).click(); // throws exception

**Comment by asolntsev** [comment]
Yes.

You are using methods `get` and `size`, but have you read javadoc for these methods?

```java
  /**
   * Gets the n-th element of collection (lazy evaluation)
   * @see <a href="https://github.com/selenide/selenide/wiki/lazy-loading">Lazy loading</a>
   */
  public SelenideElement get(int index) {...}
```

**Comment by Elvintest** [comment]
Unfortunately i missed it, thanks a lof for clarification:)
