### ISSUE TITLE
InvalidStateException is not an Exception but an Error, and can be thrown in normal situations

### ISSUE THREAD

**Issue by JonathanBerkeley** [selenide/selenide#2485]
## The problem
InvalidStateException isn't inherited from Exception, it's inherited from Error.

## Details
InvalidStateException should either be renamed to InvalidStateError, or have the inheritance hierarchy changed. This is causing a surprising Error to be generated in regular UI testing code. It would be desirable that an Error not be thrown in a regular, recoverable scenario.
https://selenide.org/javadoc/current/com/codeborne/selenide/ex/InvalidStateException.html

## Tell us about your environment
* **Selenide Version**: 6.11.0
* **Chrome\Firefox\IE Version**: 117.0.5938.92
* **Browser Driver Version**:  117.0.5938.92
* **Selenium Version**: 4.7.2
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]

```
try {
    // Something was in the way, throws ElementClickInterceptedException wrapped in InvalidStateException
    burgerMenu.click(); 
}
catch (ElementClickInterceptedException exception) {
    // Won't be caught
}
catch (Exception exception) {
    // Also won't be caught
}
menuItem.click();
```

Line: `burgerMenu.click()` generates InvalidStateException (inherits Error), can't be caught by Exception type ElementClickInterceptedException, catch block not entered.

See: https://stackoverflow.com/questions/77202494/why-cant-i-catch-elementclickinterceptedexception-exception-in-selenide-but-ca for further explanation on this code and circumstance.

**Comment by ccea-dev-team** [comment]
Not sure you should be doing something like that in the code example.  The main point of Selenide is that waits are done for you automatically using conditions.  Why not just have menuItem.shouldBe(visible).click(); ?

**Comment by JonathanBerkeley** [comment]
> Not sure you should be doing something like that in the code example. The main point of Selenide is that waits are done for you automatically using conditions. Why not just have menuItem.shouldBe(visible).click(); ?
> 
> Maybe there is a question about how to wait due to another element causing click intercepted exception- maybe something like menuItem.shouldBe(interactable).click(); or menuItem.shouldBe(enable).click(); or you should find the id of the element that is causing the intercepted and wait until is is not visible or exists i.e. otherElement.shouldNotBe(visible); Perhaps someone can explain this better? @asolntsev

I understand how it works, the reply is missing the crux of the issue. You can't catch ElementClickInterceptedException because it's wrapped in InvalidStateException which is misleadingly suffixed with Exception despite being an Error. Is being an Error not unintentional? This is a very recoverable scenario.

The code's just an example, the issue can be boiled down to:
```
try {
    component.click(); // Something was in the way, throws ElementClickInterceptedException wrapped in InvalidStateException
}
catch (ElementClickInterceptedException exception) {
    // Won't be caught
}
```

**Comment by ccea-dev-team** [comment]
The way you have it in your example looks like the old way of trying to do waits using Selenium and you're getting caught up in the semantics of what is an error and what is an exception.  Whereas my point is that using Selenide you shouldn't really be encountering these situations.

Maybe it's the way you have organised your tests, but I would have thought if a test can't click a button after a timeout I would allow the exception to be thrown causing the test to fail.  I'm not sure why you would want a process of catching the exception then trying again like the old Selenium way (why not just increase the timeout in the condition?) or doing something else (sounds like creating different paths for the same test or a possibly flakely test) - catching the exception seems irrelevant, at some point you are going to have to say if the test passed or not and whether its an exception subclass or error subclass isn't important.

**Comment by JonathanBerkeley** [comment]
> The way you have it in your example looks like the old way of trying to do waits using Selenium and you're getting caught up in the semantics of what is an error and what is an exception. Whereas my point is that using Selenide you shouldn't really be encountering these situations.
> 
> Maybe it's the way you have organised your tests, but I would have thought if a test can't click a button after a timeout I would allow the exception to be thrown causing the test to fail. I'm not sure why you would want a process of catching the exception then trying again like the old Selenium way (why not just increase the timeout in the condition?) or doing something else (sounds like creating different paths for the same test or a possibly flakely test) - catching the exception seems irrelevant, at some point you are going to have to say if the test passed or not and whether its an exception subclass or error subclass isn't important.

In the real code, burgerMenu.click() spawns a UI element that **may** block the next click to menuItem.click(). I can't do menuItem.shouldBe(visible).click() because it's perfectly valid for it to not be visible. I can do if (menuItem.is(visible), but timing then matters. Regardless, I can program around it, but this exception exhibits very surprising behaviour.

I was trying to just catch the attempt to click it, and deal with it in that case. Even using the catch for logging/screenshots, I'd expect to be able to catch the ElementClickInterceptedException, being an Error while just being a normal recoverable UI scenario is definitely not correct.

**Comment by BorisOsipov** [comment]
>InvalidStateException should either be renamed to InvalidStateError, or have the inheritance hierarchy changed

I don't think we do any of these options because of backwards compatibility and internal inheritance hierarchy design.

Please also read the blog post where Andrei explains our position on try\catch exceptions in testing.
https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/

**Comment by JonathanBerkeley** [comment]
> > InvalidStateException should either be renamed to InvalidStateError, or have the inheritance hierarchy changed
> 
> I don't think we do any of these options because of backwards compatibility and internal inheritance hierarchy design.
> 
> Please also read the blog post where Andrei explains our position on try\catch exceptions in testing. https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/

It's unfortunate to be named Exception when it's not an Exception. The backwards compatibility is because people may be catching on it already?

The example given in the blog is unrelated, this isn't timing related exception handling.

**Comment by ccea-dev-team** [comment]
> in the real code, burgerMenu.click() spawns a UI element that **may** block the next click to menuItem.click(). I can't do menuItem.shouldBe(visible).click() because it's perfectly valid for it to not be visible. I can do if (menuItem.is(visible)), but timing then matters. Regardless, I can program around it, but this exception exhibits very surprising behaviour.

I assume that this spawned element is not random and you have some control over if it appears or not?  If so create your test around that process rather than trying to deal with different conditions in a single test - maybe have 2 or 3 tests where some spawn this element and others don't and this would elimate the need for try/catch which was what the https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/ link is trying to say.

**Comment by JonathanBerkeley** [comment]
> > in the real code, burgerMenu.click() spawns a UI element that **may** block the next click to menuItem.click(). I can't do menuItem.shouldBe(visible).click() because it's perfectly valid for it to not be visible. I can do if (menuItem.is(visible)), but timing then matters. Regardless, I can program around it, but this exception exhibits very surprising behaviour.
> 
> I assume that this spawned element is not random and you have some control over if it blocks another element or not? If so create your test around that process rather than trying to deal with different conditions in a single test - maybe have 2 or 3 tests where some spawn this element and others don't and this would elimate the need for try/catch which was what the https://selenide.org/2019/12/02/advent-calendar-how-to-abuse-selenide/ link is trying to say.

It's not random, but if it will block the following element or not is nearly random, it depends on screen size/aspect ratio. I can't portably control for whether or not it will block the following element.

**Comment by ccea-dev-team** [comment]
> it depends on screen size/aspect ratio

If you are running tests on a build tool such as Jenkins then you really should have a standardised test envirorment or tests will fail randomly regardless of how you write them.

The link just uses the timing as an example - the point it is making is you should have control over what happens in the test, you should know that clicking x button will cause x to happen.  If things are random then seek to control that rather than complicate your tests with different pathways and try/catches.  This will also make your tests less flaky and easier to maintain.

**Comment by JonathanBerkeley** [comment]
> > it depends on screen size/aspect ratio
> 
> If you are running tests on a build tool such as Jenkins then you really should have a standardised test envirorment or tests will fail randomly regardless of how you write them.
> 
> The link just uses the timing as an example - the point it is making is you should have control over what happens in the test, you should know that clicking x button will cause x to happen. If things are random then seek to control that rather than complicate your tests with different pathways and try/catches. This will also make your tests less flaky and easier to maintain.

I'm not sure what exact affects the positioning of the UI element, it's not something I want to rely on, even if I can, it could easily break the test, it would be poor design to rely on that positioning. This conversation has completely derailed from the beginning, the template question asks to add code to reproduce as a good to have, that's why it was added. It was not intended for the issue to be about the code.

Though the actual issue has somewhat of an answer, the naming being "Exception" despite not being an Exception and in-fact being an Error is a wontfix technical debt because it may break backwards compatibility to fix it now.

**Comment by ccea-dev-team** [comment]
> This conversation has completely derailed from the beginning, the template question asks to add code to reproduce as a good to have, that's why it was added. It was not intended for the issue to be about the code.

The issue stems from you not understanding how to write a good test in Selenide and try to force it to do things to deal with bad practices on your side.  I won't respond anymore to your ill tempered replies and lack of reading links already sent to you to explain.  Go ahead and put as many try/catches as you like in your test, hell go ahead and catch a subclass of error, and good luck with that!

**Comment by JonathanBerkeley** [comment]
> > This conversation has completely derailed from the beginning, the template question asks to add code to reproduce as a good to have, that's why it was added. It was not intended for the issue to be about the code.
> 
> The issue stems from you not understanding how to write a good test in Selenide and try to force it to do things to deal with bad practices on your side. I won't respond anymore to your ill tempered replies and lack of reading links already sent to you to explain. Go ahead and put as many try/catches as you like in your test, hell go ahead and catch a subclass of error, and good luck with that!

There's no ill temper at all, the replies you are posting are unrelated to the issue, the suffix "Exception" is not correct for a class which is not an Exception. It's unproductive to hand-wave away library design issues as user-error when that's not at all the case. Can we please keep this professional and civil?

**Comment by mikfar** [comment]
facing the same issue

**Comment by asolntsev** [comment]
Hi @JonathanBerkeley !
I have a simpe answer for you. :) 

1. Yes, `InvalidStateException` extends `Error`, thus it should be called `InvalidStateError`, not `InvalidStateException`. 
  1.1. The good news is that we can rename it in a next major release. 
2. You can easily catch `InvalidStateException`, even if it extends `Error`. So I don't really understand what's your problem (besides the confusion). Just write `catch (InvalidStateException e)` if you want to catch it. ;)
3. I don't agree that `It would be desirable that an Error not be thrown in a regular, recoverable scenario`. It's common for tests to throw `Error` subclasses. Any assert basically throws `AssertionError`. 
  3.1 When you call `assertEquals(2, 3)`, it throws `AssertionError` (or its subclass).
  3.2. When you click an element that is not clickable, it throws `AssertionError` (more exactly, its subclass `InvalidStateException`).

In some sense, I understand your point that case 3.2 is more "recoverable" than case 3.1. Yes, you can catch this `InvalidStateException`, do some other manipulation with UI elements and click again. 

I personally don't like such tests, and I believe our professionalism consists in finding a better way to click without try/catching. Probably a good way to click that element is using JS code.  **Did you try `$.click(usingJavaScript())`**?

P.S. Are you aware that when we rename `InvalidStateException` to `InvalidStateError`, and you catch it, your test will spend extra 4 seconds and takes an extra screenshot? Do you really think it's a good waste of resources?

**Comment by JonathanBerkeley** [comment]
Hello @asolntsev, thanks for the detailed reply!

1. Great! As @BorisOsipov mentioned, there are a couple other examples like this, such as some of the subclasses of this: https://selenide.org/javadoc/current/com/codeborne/selenide/ex/UIAssertionError.html
2. Yes, that's true. Catching an Error is usually very wrong, so that's why I've had the initial reaction to avoid this, but in this circumstance, it can make sense. It may set off some code quality checkers such as SonarQube to do this, but of course this can be up to the developer to disable it for that line if it's needed.
3. That's true as well. I understand the point about AssertionError. An assertion failing would usually not be recoverable, but the situation is a bit more complex with these Selenide subclasses, some of which could be recoverable, but still, they are assertions of sorts. I can appreciate the reasoning they are here, and I agree the developer can choose to catch on the subclass if it is really required.

I will look to improve the original code, I had not thought to click in the way you suggested, so I will experiment with that, thanks for the tip.

For the P.S, I don't intend to take a screenshot no, I was pointing out other potential usecases for a try-catch but the screenshot one is a bad example as it would be taken anyway!
