### ISSUE TITLE
Could not start new session (Chrome driver)

### ISSUE THREAD

**Issue by leticiafernandez** [selenide/selenide#2488]
## The problem
When I try to execute my test several times...first time work well but second time appear this error message and timeout 

```
java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first.
Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
```

## Details
Only work again when pass 2 or 3 min. without execution

## Tell us about your environment
* **Selenide Version**: 6.18.0
* **Chrome Version**: 117.0.5938.134

## Code To Reproduce Issue [ Good To Have ]
1.- Execute test
2.- Execution finish
3.- Run again test

**Comment by asolntsev** [comment]
@leticiafernandez  Sorry, not enough information. I can re-run tests many times, everything works well.
