### ISSUE TITLE
Method $.isNotEmpty() is not available for collection 

### ISSUE THREAD

**Issue by julyaaaaa** [selenide/selenide#2535]
Please, restore $.isNotEmpty() for collection, because they are used at tests

**Comment by asolntsev** [comment]
@julyaaaaa Class `ElementsCollection` already has method `isEmpty()`. Isn't it enough?

P.S. I insist that using such methods in tests is a bad practice.

**Comment by julyaaaaa** [comment]
Some cases, it is need to check that some collections are not empty and method isNotEmpy() was a convenient solution for such cases.
