### ISSUE TITLE
Selenide 7.0.0+ doesn't seem to pull down dependencies in Gradle.

### ISSUE THREAD

**Issue by cemerick1** [selenide/selenide#2537]
## The problem
When I add `implementation 'com.codeborne:selenide:7.0.0'` and build the build.gradle file non of the selenide package doesn't seem to get pulled down.

## Tell us about your environment
* **Selenide Version**: 7.0.0 
* **OS Version**: Windows 10

## Code To Reproduce Issue [ Good To Have ]
![image](https://github.com/selenide/selenide/assets/43388329/946c38f6-556e-4d28-9851-482d232b9163)
![image](https://github.com/selenide/selenide/assets/43388329/f88ce4dc-dbb1-4ee7-97a6-08771b59a1e3)

**Comment by asolntsev** [comment]
I am absolutely sure Selenide 7.0.0 (and 7.0.1) jars are downloadable from maven central repo:
https://search.maven.org/remotecontent?filepath=com/codeborne/selenide/7.0.1/selenide-7.0.1.pom


You need to reload gradle project in IDEA, clean cache or whatever people usually do.

**Comment by cemerick1** [comment]
Good deal thanks Andrei! Appears I needed to remove these parameters in the gradle.build file.  Just for future FYI.

![image](https://github.com/selenide/selenide/assets/43388329/a91cdb72-6348-4757-b0f1-84b676d8a98f)
