### ISSUE TITLE
Switch Tab Not working

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2542]
## The problem
I had a website called https://watch-mediaprima-uat.switch.tv/ need login kachon.wong@revmedia.my and abcd1234. When i cliked the Terms and Conditions link, it open another tab but my automation cannot detect the second tab. I had switch to second tab. What wrong with it?

## Details
the Terms and Conditions link, it open another tab but my automation cannot detect the second tab. What wrong with it?

## Tell us about your environment
* **Selenide Version**:  6.15.0
* **Chrome\Firefox\IE Version**: 118
* **Browser Driver Version**: -
* **Selenide-Appium Version**: -
* **IOS\Android\WEB version**:-
* **Selenium Version**: 4.19.0
* **OS Version**: Win 10

## Code To Reproduce Issue

```java
@Test
public void testT&C() {
     login();
     $x("link").click();
     switchTo().window(1);
     $x("//h1[contains(text(), 'Terms of Use')]").shouldHave(text("Terms of Use"));
}
```

**Comment by asolntsev** [comment]
Hi.
You didn't provide the full code. You didn't show your `login` method.

Anyway, method `swithTo().window` works. Just the index is 0-based.

1. In the beginning, you need to call `switchTo().window(1)` - it will switch to the _second_ window (that contains username and password fields)
2. after entering credentials, you need to call `switchTo().window(0)` - it will switch to the _first_ window (the main content).
