### ISSUE TITLE
Implement downloading files via CDP or BiDi

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#2550]
Chome CDP has `setDownloadBehavior` method:
https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior in `Browser` domain.

Here is the sample test  subscribing to those events and printing the progress and completion 
in `Browser.downloadWillBegin listener`.

url: https://scholar.harvard.edu/files/torman_personal/files/samplepptx.pptx
filename: samplepptx.pptx

in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: inProgress
in Browser.downloadProgress listener. state: completed
in Browser.downloadProgress listener. state: completed
Inspecting downloaded filename: f5a83cbd-97fb-451e-8651-618f63c1ec59
Verified downloaded file: f5a83cbd-97fb-451e-8651-618f63c1ec59 in /tmp

**Comment by sbritprovectus** [comment]
@asolntsev I've made a PR for this issue. Could you please check. Thanks in advance

**Comment by britka** [comment]
@asolntsev I've made the PR for this issue. Could you check please. Thanks in advance

**Comment by asolntsev** [comment]
Great! Will look in a few days. Thanks.
