### ISSUE TITLE
Type / methods for entities related to Selenide Proxy can't be resolved without adding proxy dependency to a project

### ISSUE THREAD

**Issue by mr-alexov** [selenide/selenide#2562]
## The problem

Adding solely Selenide dependency (or com.codeborne:selenide-proxy)  to a project does not allow to work with some proxy and related methods, namely request.headers().add("User-Agent", "hacker");

The Selenide team claims that the code should work without adding explicit dependency, or adding solely selenide-proxy. 

## Details

With the code example
https://github.com/mr-alexov/selenide_proxy_add_header_example/blob/main/src/test/java/MirrorTests.java

Steps: 

1. Remove (or don't add) the dependency "com.github.valfirst.browserup-proxy:browserup-proxy-core:2.2.15" (from/to) the project build gradle (default state now is that it is missing)
2. Update dependencies. 
3. The code with the line
request.headers().add("X_REMOTE_USER", "JessyJames"); 
-- can't be compiled (the compiler can't resolve 'headers()'

If one adds explicit above-mentioned dependency, the code can be compiled. 

## Tell us about your environment
* Selenide 7.02: 
* IntelliJ Idea 2923,2,5
* Java 17, JDK Corretto 
* Windows 10:

**Comment by asolntsev** [comment]
Will be fixed in Selenide 7.0.3
