### ISSUE TITLE
Question for how can I make a little sign with Selenide

### ISSUE THREAD

**Issue by TricksterCode210** [selenide/selenide#2565]
## The problem
I have to make a test, where I have to sign a canvas element in the page. I don't know how can I draw a simple line or anything with Selenide. Can you help me with this question please?

## Details
Basically that would be enough for the further progress in the test:
![image](https://github.com/selenide/selenide/assets/84982671/afb43fd7-58ef-404f-b906-b3cf29ebb94b)

## Tell us about your environment
* **Selenide Version**: 6.17.2
* **Chrome\Firefox\IE Version**: Chrome 119
* **Browser Driver Version**:
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version**: 4.8.1
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
If I can't make this, that would be great feature, where we have a function which can draw a line on the canvas.
For example: draw(int startX, int startY, int endX, int endY). The starting coordinates would be the top left corner of the SelenideElement (in this example the canvas's corner)

**Comment by rosolko** [comment]
At least we have a function to get actions access - `driver.actions()`.
Also you don't need to call perform every time for each step, you can chain actiond and call `perform` method on final step:
```java 
driver.actions()
  .moveToElement(element)
  .clickAndHold(element)
  .moveByOffset(150, 50)
  .moveByOffset(100, 50)
  .release()
  .perform();
```

**Comment by TricksterCode210** [comment]
I'm gonna do my research to understand driver.action() even more. But my problem was a little bit unique for me, so I needed some help with it. Thanks for your answer!
