### ISSUE TITLE
UnsupportedCommandException on Empty Check with SelenideAppiumElement in Java

### ISSUE THREAD

**Issue by Deceptio** [selenide/selenide#2579]
**Environment:**
- Java Version: 14
- Selenide Version: 7.0.2
- Appium Version: 2.2.1

**Issue Description:**
An `UnsupportedCommandException` is thrown when attempting to apply the `shouldNotBe(Condition.empty)` method on a `SelenideAppiumElement` object. The element is expected to contain text, but the test fails, apparently because the `text` attribute is not being read correctly.

**Steps to Reproduce:**
1. Find an element using `findElementByXpath`.
2. Check if the element is not empty using `shouldNotBe(Condition.empty)`.

**Expected Behavior:**
The `shouldNotBe(Condition.empty)` method should be able to verify whether the text field contains text without throwing an exception.

**Current Behavior:**
An `UnsupportedCommandException` is thrown, stating that the `value` attribute is unknown.

**Additional Information:**
Using totalAssetAmountTextAA.getText() on the same element retrieves the correct text without any errors.

**Code Snippet:**
```java
SelenideAppiumElement totalAssetAmountTextAA = AutomationTools.findElementByXpath("//android.widget.TextView[@text='"+textWidgetAssetsTitle+"']/following-sibling::android.widget.TextView[1]");
totalAssetAmountTextAA.shouldNotBe(Condition.empty);
```
**Exception**
```java
Caused by: Element should not be empty: attribute value="" and exact text "" {By.xpath: //android.widget.TextView[@text='Total Amount']/following-sibling::android.widget.TextView[1]}
Element: '<TextView resource-id="null" checked="false" content-desc="USD 11000" enabled="true" focused="false" package="com.allshop.ert.it" name="USD 11000" className="android.widget.TextView" bounds="[118,1076][522,1143]" displayed="true">USD 11000</TextView>'
Timeout: 5 s.
Caused by: UnsupportedCommandException: 'value' attribute is unknown for the element. Only the following attributes are supported: [checkable, checked, {class,className}, clickable, {content-desc,contentDescription}, enabled, focusable, focused, {long-clickable,longClickable}, package, password, {resource-id,resourceId}, scrollable, selection-start, selection-end, selected, {text,name}, hint, extras, bounds, displayed, contentSize]
	at com.codeborne.selenide.impl.WebElementSource.handleError(WebElementSource.java:149)
```

**Comment by Deceptio** [comment]
Ah ok, that was a mistake on my part. I didn't realise that text AND value had to be empty. I was confused by the fact that getText() worked. So I thought this check should also work. The fact that value is not accessible is therefore a restriction of Android.
Maybe you could build 2 methods for an empty check for value and text?

**Comment by asolntsev** [comment]
> Maybe you could build 2 methods for an empty check for value and text?

Selenide already has such checks:
1. `$.shouldHave(exactText(""))`
2. `$.shouldHave(exactValue(""))`

**Comment by Deceptio** [comment]
Ok, then there's nothing more to say...
