### ISSUE TITLE
Can't find waitUntil among present methods

### ISSUE THREAD

**Issue by andreisuslov** [selenide/selenide#2587]
## The problem
The waitUntil(condition, timeout) is mentioned in the docs but is not available in the library. 
The [repo](https://github.com/selenide/selenide/blob/23d855e12a3ce08de2697418dfb95aef09f5fc47/src/main/java/com/codeborne/selenide/ElementsCollection.java#L159) has it as protected whereas I believe it needs to be public. I don't see a reason why it wouldn't be a public method, anyway. It would be quite handy for my current test automation scenario.

**Comment by asolntsev** [comment]
Yes, method `waitUntil` was marked as deprecated a long time ago (3 years?), and was removed in major release Selenide 6.0.0 (2 years ago). See https://selenide.org/2020/12/26/selenide-5.17.0/#added-should-methods-with-custom-timeout: 
> Now you can replace $.waitUntil(hasText("bob"), 18_000) by $.shouldHave(text("bob"), Duration.ofSeconds(18)).

BUT
> is mentioned in the docs
@andreisuslov What docs do you mean? Do we need to update that doc?
