### ISSUE TITLE
SoftAsserts incorrect behaviour with parametrized parallel tests using JUnit5

### ISSUE THREAD

**Issue by akalupkin** [selenide/selenide#2595]
## The problem
SoftAsserts works incorrectly with parametrized tests while running in parallel using JUnit5

## Details
- Enable SoftAsserts via junit extension and selenide config soft mode 
- Create test class consisted of one parametrized tests
- Make sure that test method will fail using both parameters by only one reason (not multiple failures)
- Run tests in parallel mode using JUnit5

**Expected result:** 
Each of the test run of the test method will be marked as failed with separated failure stacktraces in each thread

**Actual result:** 
One of the test run will be marked as passed and the other will be failed. The failed one will have in it's stacktrace failures from the run which was marked as passed

![Скриншот 21-12-2023 163458](https://github.com/selenide/selenide/assets/54039404/48691d67-ba81-452b-b599-ab7064773d34)
[log.txt](https://github.com/selenide/selenide/files/13742437/log.txt)

If you remove soft mode from config or switch to non-parallel execution the result will be as expected

## Tell us about your environment
* **Selenide Version**: 7.0.4
* **Chrome\Firefox\IE Version**: Chrome 120
* **Browser Driver Version**: 118
* **Selenide-Appium Version**: -
* **IOS\Android\WEB version**: -
* **Selenium Version**:  -
* **OS Version**: Windows 10 Pro
* **Java Version**: 17
* **JUnit Jupiter Version**: 5.10.0
* **JUnit Platform Version**: 1.10.0

## Code To Reproduce Issue [ Good To Have ]
```
@Slf4j
@ExtendWith({SoftAssertsExtension.class})
public class Test1 {
    private final SelenideElement searchButton = $("input[tabindex='0']");

    private static void setupSelenide() {
        Configuration.browser = "chrome";
        Configuration.assertionMode = AssertionMode.SOFT;
    }

    @BeforeAll
    public static void init() {
        setupSelenide();
    }

    @BeforeEach
    public void setup() {
        Selenide.open("https://www.google.com/");
    }

    @AfterEach
    @SneakyThrows
    public void tearDown() {
        try {
            WebDriverRunner.clearBrowserCache();
        } catch (Throwable e) {
            log.warn("Clear browser cache failed");
        }
        try {
            Selenide.clearBrowserLocalStorage();
        } catch (Throwable e) {
            log.warn("Clear browser local storage failed");
        }
        try {
            Selenide.closeWebDriver();
        } catch (Throwable e) {
            log.warn("Close web driver failed");
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"134", "1234"})
    void softAssertParallelTest(String input) {
        searchButton.shouldHave(text(input));
    }

```

**Comment by asolntsev** [comment]
@akalupkin Good catch! Yes, we have a bug (which was introduced by commit https://github.com/selenide/selenide/commit/5b0fa6db9fe2e3cc41263d0689866915f1 :)

Working on it.
