### ISSUE TITLE
Get index from element collection with findBy

### ISSUE THREAD

**Issue by ilan-QA** [selenide/selenide#2606]
Need to add a function that gets the element index from the collection with find by.

**Comment by JonathanBerkeley** [comment]
What use case has motivated this?

Can you not do the following, for example?:
```java
ElementsCollection widgets = $$(byText("Widget"));
int visibleWidgetIndex = widgets.indexOf(widgets.findBy(visible));
```

**Comment by BorisOsipov** [comment]
@JonathanBerkeley in v7 ElementsCollection no longer implements `List`, so there are no `indexOf()` implementation.

**Comment by ilan-QA** [comment]
what I'm using now:
`page.specialEventDeleteButtonsList()
                .get(page.specialEventsList().texts().indexOf(page.specialEventsList().find(text(formatDate)).getText())).click();`

I can use indexOf only when using list so I need to get the text out of all the elements and then search the text and get the index.
I want to use indexOf without the need to use list cause I already got elements collection and there is no point of extracting all the texts from all the elements.

how I want to use it:
`page.specialEventDeleteButtonsList()
                .get(page.specialEventsList().indexOf(page.specialEventsList().find(text(formatDate)))).click();`

"find" is returning element so why cant is just get the index of that element

**Comment by asolntsev** [comment]
@ilan-QA Most probably it's a bad idea anyway because such a search may be slow (depending on the collection size).

Can't you find element using `parent()` or `closest()` method?
Something like

```java
var eventDate = page.specialEventsList().find(text(formatDate)));
var eventRow = eventDate.closest("tr.event");
var deleteEvent = eventRow.find(".btn.delete");
deleteEvent.click();
```
