### ISSUE TITLE
add documentation for Profiler to Wiki/WebPage

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#261]
Profiler-feature is working for JUnit since 2.16 but is not documented yet

**Comment by asolntsev** [comment]
@vinogradoff Are we going to add that documentation?

**Comment by asolntsev** [comment]
@vinogradoff reminder

**Comment by asolntsev** [comment]
Added "reports" section to Selenide documentation:
* https://selenide.org/documentation/reports.html
* https://ru.selenide.org/documentation/reports.html
