### ISSUE TITLE
 Selenide-Appium: Encountered internal error running command: NotImplementedError: Not implemented yet for pageLoad.

### ISSUE THREAD

**Issue by algernon28** [selenide/selenide#2612]
## The problem
The app gets started in my cucumber hook by `SelenideAppium.launchApp();`

However, it crashes as soon as it starts the session, apparently because `pageLoadTimeout` is not implemented (note that I do not set that parameter explicitly, I believe Selenide sets it by default).

## Tell us about your environment
* **Selenide-Appium Version**: 7.0.4
* **IOS\Android\WEB version**: any
* **OS Version**: Windows 10
* **Java Version**: 17
* **Cucumber Version**: 7.15.0

## Code To Reproduce Issue
I implemented AndroidDriverProvider like this 

```java
public class AndroidDriverProvider extends BaseDriverProvider {

    public AndroidDriverProvider() {
        super();
    }

    @SneakyThrows
    @Nonnull
    @Override
    public WebDriver createDriver(@Nonnull Capabilities capabilities) {
        UiAutomator2Options options = new UiAutomator2Options().merge(capabilities);
        appendSauceOptions(options);
        AndroidDriver driver = new AndroidDriver(url, options);
        log.debug("Driver: {}", driver);
        return driver;
    }
}
```

[appium.log](https://github.com/selenide/selenide/files/14002401/appium.log)

[local-emu-android.json](https://github.com/selenide/selenide/files/14002410/local-emu-android.json)

[classes.zip](https://github.com/selenide/selenide/files/14002409/classes.zip)

**Comment by asolntsev** [comment]
@algernon28 Hi.
I don't think your app crashes because of `pageLoad`. I think it crashes for some reason.

About pageLoad: it doesn't really cause any problems. It just write a single INGO log:
> INFO WebDriverFactory - Failed to set page load timeout to 30000 ms: org.openqa.selenium.UnsupportedCommandException: ....

After this line, some other problem happens. 

P.S. To stop seeing this log, it's enough to remove `.merge(capabilities)` part from your code.

**Comment by algernon28** [comment]
I tried, but it seems it keeps being overwritten to 0 whatever I try. For Appium it seems it's hardcoded.
The app crashes constantly at that point, I couldn't see any other significant error.
And it doesn't happen if I instantiate AndroidDriver by myself, in a framework without selenide.

**Comment by asolntsev** [comment]
@algernon28 Then can you please show the error message with full stack trace?

**Comment by algernon28** [comment]
I believe I attached the whole appium log?
The session just crashes right after that command.
Then the app closes as consequence.
My java stacktrace only showed errors due to unknown appium session, because it closed.
The appium log is attached in the post.
The pageload is hardcoded to zero for SelenideAppium it seems.

**Comment by asolntsev** [comment]
@algernon28 No, I am asking for Java error message with full stack trace.
Can you also share the logs from android emulator?

From appium log I see that the session disappears after the `pageLoad` error, which kinda proves your theory:

```
2024-01-21 18:34:03:755 [AndroidUiautomator2Driver@ded4 (8694fd43)] Calling AppiumDriver.timeouts() with args: [null,null,null,0,null,"8694fd43-cb2b-447d-88d7-e420e8812e37"]
2024-01-21 18:34:03:760 [AndroidUiautomator2Driver@ded4 (8694fd43)] W3C timeout argument: {"pageLoad":0}}
2024-01-21 18:34:03:798 [AndroidUiautomator2Driver@ded4 (8694fd43)] Encountered internal error running command: NotImplementedError: Not implemented yet for pageLoad.
```

and AFTER them next lines:
```
2024-01-21 18:34:04:064 [AndroidUiautomator2Driver@ded4 (8694fd43)] Calling AppiumDriver.findElement() with args: ["xpath","//android.webkit.WebView[@text='Edenred Connect']","8694fd43-cb2b-447d-88d7-e420e8812e37"]
```


P.S. Yes, you are right: "pageLoad = 0" is hardcoded in SelenideAppium, and this is a bug. Will fix it in Selenide 7.1.0. But I still don't think it causes the app crash.

**Comment by algernon28** [comment]
It's the appium session that crashes.
I don't have the android logs at hand, I will gather them next time I have a chance to run it again if you think they are useful.

**Comment by asolntsev** [comment]
page load timeout fixed by https://github.com/selenide/selenide/pull/2628
