### ISSUE TITLE
@FindBy ElementsCollection has not been initialized with Selenide 7 and Kotlin

### ISSUE THREAD

**Issue by itd-ba** [selenide/selenide#2648]
## The problem
After updating to Selenide 7 I got the problem that all ElementsCollection added to a class as member with @FindBy won't be initialized.

Example Code:
```
  @FindBy(css = ".textElement")
  lateinit var textElements: ElementsCollection

  val text: String
    get() {
      return backgroundElements.asFixedIterable().stream().map { el ->  el.text }.toList().joinToString()
    }
```

If I call the getter of text I got a kotlin.UninitializedPropertyAccessException ("lateinit property textElementshas not been initialized").
It works if I change ElementsCollection to MutableList<WebElement>, but it doesn't work if I change it to MutableList<SelenideElement>.
This worked with version 6. 

## Tell us about your environment
* **Selenide Version**: 7.1.0
* **Chrome Version**: 103
* **Selenium Version**: 4.17.0
* **Kotlin Version**: 1.9.22

**Comment by BorisOsipov** [comment]
@itd-ba Could you provide reproducable example?


This works fine:
```
package com.example.demokotlin

import com.codeborne.selenide.ElementsCollection
import com.codeborne.selenide.Selenide.open
import com.codeborne.selenide.Selenide.page
import org.junit.jupiter.api.Test
import org.openqa.selenium.support.FindBy

class MainPageTest {
    @Test
    fun foo() {
        open("https://www.jetbrains.com/")
        val page = page(MainPage::class.java)
        assert(page.text == "For developers, For teams, For learning, Kotlin")
    }

    class MainPage {
        @FindBy(css = ".product-card__title")
        lateinit var textElements: ElementsCollection

        val text: String
            get() {
                return textElements.asFixedIterable().stream().map { el -> el.text }.toList().joinToString()
            }
    }
}
```

**Comment by itd-ba** [comment]
@BorisOsipov I can reproduce the behavior with your code if I remove the wrapping page function.
```
package com.example.demokotlin

import com.codeborne.selenide.ElementsCollection
import com.codeborne.selenide.Selenide.open
import org.junit.jupiter.api.Test
import org.openqa.selenium.support.FindBy

class MainPageTest {
    @Test
    fun foo() {
        open("https://www.jetbrains.com/")
        val page = MainPage()
        assert(page.text == "For developers, For teams, For learning, Kotlin")
    }

    class MainPage {
        @FindBy(css = ".product-card__title")
        lateinit var textElements: ElementsCollection

        val text: String
            get() {
                return textElements.asFixedIterable().stream().map { el -> el.text }.toList().joinToString()
            }
    }
}
```

Is it necessary to wrap the pages with the page function in Selenide 7?
It worked for me without calling the page function with Selenide 6.

**Comment by asolntsev** [comment]
@itd-ba yes, sure, you need to use method `page`. Otherwise, who will initialize fields annotated with `@FindBy`?

I don't believe it could with Selenide 6 as well.
How is it technically possible? When you just call `val page = MainPage()`, all fields of `MainPage` remain uninitialized.

**Comment by itd-ba** [comment]
Oh there seems to be some kind of field decorator who is initializing these fields in a base class. So I have to fix the initialization there. Sorry for bothering you. It's a huge test code base I'm not familiar with.
