### ISSUE TITLE
@As annotation not working for CombinedBy

### ISSUE THREAD

**Issue by itkhanz** [selenide/selenide#2654]
## The problem
Selenide provides `@As` annotation for PageFactory which is used as a placeholder for element description in the text report.

For example, here in the PageFactory this annotation works as expected:

```
@As("subtitle")
@AndroidFindBy(xpath = "//android.widget.TextView[@text=\"Demo app for the appium-boilerplate\"]")
@iOSXCUITFindBy(accessibility = "xxxxx")
private WebElement subtitle;
```

But if you use the annotation with `CombinedBy` or `By`, then the text in `@As` does not show up in the text report in terminal:

```
@As("support")
private final CombinedBy support = CombinedBy
        .android(AppiumSelectors.withText("Support"))
        .ios(AppiumSelectors.withText("Support"));

@As("support")
private static final By supportBy = AppiumSelectors.withText("Support");
```

## Details
Here is how it looks in terminal:

![Screenshot 2024-02-16 at 17 29 56](https://github.com/selenide/selenide/assets/62521743/40602dda-9b36-4adb-b55b-31bc1d161595)

Is this behavior intentional? Please share if this annotation has any other purpose than providing human-readable alias for page object fields in reports in which case this alias should be displayed as Element descriptor in text/html reports.

## Tell us about your environment
* **Selenide-Appium Version**: 7.1.0
* **Selenide-testng Version**: 7.1.0
* **Java Version**: 17
* **OS Version**:  MacOS Sonoma 14.2.1
* Application under Test: https://github.com/webdriverio/native-demo-app/releases/tag/v1.0.8

## Code To Reproduce Issue [ Good To Have ]
Just add the `@Listeners({ TextReport.class })` to TestNG class, and add the `slf4j-simple` and `selenide-testng` to get this report in terminal.

### TestClass

```
@Listeners({ TextReport.class })
public class BaseTest {

    @BeforeMethod
    public void setup() {
        SelenideAppium.launchApp();
        HomePage homePage = ScreenObject.screen(HomePage.class);
        homePage.checkTextVisibility();
    }

}

```
### HomePage.class

```
public class HomePage extends BasePage{

    @As("subtitle")
    @AndroidFindBy(xpath = "//android.widget.TextView[@text=\"Demo app for the appium-boilerplate\"]")
    @iOSXCUITFindBy(accessibility = "xxxxx")
    private WebElement subtitle;

    @As("support")
    private final CombinedBy support = CombinedBy
            .android(AppiumSelectors.withText("Support"))
            .ios(AppiumSelectors.withText("Support"));

    @As("support")
    private static final By supportBy = AppiumSelectors.withText("Support");

    public void checkTextVisibility() {
        $(subtitle).shouldBe(visible);
        $(support).shouldBe(visible);
        $(supportBy).shouldBe(visible);
    }
    
}
```

**Comment by asolntsev** [comment]
@itkhanz Hi. Anntoation `@As` was intended to use with those Page Object fields that are initialized by page factory. In other words, which are annotated with `@FindBy`, `@AndroidFindBy` etc.

In your code, you just create the field `support` by yourself, not using annotations. 

What you can do:
1. use method `as` for `SelenideElement`:
```java
$(support).as("support").shouldBe(visible);
```

2. declare PO fields of type `SelenideAppiumElement` instead of `CombinedBy`:
```java
public class HomePage extends BasePage{
    private final SelenideAppiumElement support = $(CombinedBy
            .android(AppiumSelectors.withText("Support"))
            .ios(AppiumSelectors.withText("Support"))).as("combined");
}
```

What we can do in Selenide:
we could add method `as` to class `CombinedBy`. Then you could declare PO fields like this:
```java
    private final CombinedBy support = CombinedBy
            .android(AppiumSelectors.withText("Support"))
            .ios(AppiumSelectors.withText("Support"))
            .as("combined");
```

**Comment by asolntsev** [comment]
Added javadoc to `@As` annotation: https://github.com/selenide/selenide/commit/17cb5f3ffbd3fff44a5dccc6b2f431087dedda35

**Comment by itkhanz** [comment]
> @itkhanz Hi. Anntoation `@As` was intended to use with those Page Object fields that are initialized by page factory. In other words, which are annotated with `@FindBy`, `@AndroidFindBy` etc.
> 
> In your code, you just create the field `support` by yourself, not using annotations.
> 
> What you can do:
> 
> 1. use method `as` for `SelenideElement`:
> 
> ```java
> $(support).as("support").shouldBe(visible);
> ```
> 
> 2. declare PO fields of type `SelenideAppiumElement` instead of `CombinedBy`:
> 
> ```java
> public class HomePage extends BasePage{
>     private final SelenideAppiumElement support = $(CombinedBy
>             .android(AppiumSelectors.withText("Support"))
>             .ios(AppiumSelectors.withText("Support"))).as("combined");
> }
> ```
> 
> What we can do in Selenide: we could add method `as` to class `CombinedBy`. Then you could declare PO fields like this:
> 
> ```java
>     private final CombinedBy support = CombinedBy
>             .android(AppiumSelectors.withText("Support"))
>             .ios(AppiumSelectors.withText("Support"))
>             .as("combined");
> ```

Thank you @asolntsev for the quick help. The second option i.e. _**declare PO fields of type SelenideAppiumElement instead of CombinedBy**_ seems to work for my use-case.
