### ISSUE TITLE
Method shouldNotBe(exist) throws NoSuchElementException for a non-existent SelenideApiumElement

### ISSUE THREAD

**Issue by 232629** [selenide/selenide#2665]
## The problem
Calling a method `$.shouldNot(exist)` on a non-existent `SelenideAppiumElement` throws an error.

## Tell us about your environment
* **Selenide-Appium Version**: 7.2.0
* **OS Version**: Win 10
* **Appium Version**: 2.5.1
* **uiautomator2 Version**: 2.45.1
## Code To Reproduce Issue

```java
public void test() {
    SelenideAppium.$(Selenide.$(By.xpath("Nope"))).shouldNotBe(exist);
}
```

```java
Element not found {By.xpath: Nope}
Expected: exist
Screenshot: file:/D:/test/Mobile/app5/app5AndroidUI/target/screenshots/1709209344135.0.png
Page source: file:/D:/test/Mobile/app5/app5AndroidUI/target/screenshots/1709209344135.0.xml
Timeout: 30 s.
Caused by: NoSuchElementException: An element could not be located on the page using the given search parameters.
```

[ FullStackTrace.txt](https://github.com/selenide/selenide/files/14449199/error.txt)

**Comment by BorisOsipov** [comment]
Reproducible without appium via Selenide test harness with the following test:
```
final class Foo extends IntegrationTest {
  @Test
  void bar() {
	openFile("page_with_selects_without_jquery.html");
    MissingPage missingPage = PageFactory.initElements(WebDriverRunner.getWebDriver(), MissingPage.class);
    Selenide.$(missingPage.element).shouldNotBe(exist);
  }

  public static class MissingPage {
    @FindBy(xpath = "//select[@name='wrong-select-name']")
    public WebElement element;
  }
}
```

The culprit is [here](https://github.com/selenide/selenide/blob/main/src/main/java/com/codeborne/selenide/impl/SelenideElementProxy.java#L82), where `webElementSource.description()` underhood calls `ElementDescriber` to describe a non-existent element and fails.
