### ISSUE TITLE
setLocation with "io.appium.java_client.Location" throws "Error: longitude must be provided" 

### ISSUE THREAD

**Issue by umerhamdan10** [selenide/selenide#2673]
## The problem
In Java client 9.1.0, this (https://github.com/appium/java-client/commit/4623e1138ca19c388ac2f636a30a4320c00b7fb5) issue is solved but will be released in the next version. 

After updating selenide-appium:7.2.0 and even 7.1.0, we are facing to run the test while setting the location before starting the test.
 
 My question is, how do I handle this issue because in 9.1.0  the setlocation (import org.openqa.selenium.html5.Location;
) is depriciated.

## Details
If necessary, describe the problem you have been experiencing in more detail.

## Tell us about your environment

* **Selenide-Appium Version**: 7.2.0 or 7.1.0
* **IOS\Android\WEB version**:
* **Selenium Version**: 
* **OS Version**: 

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by rosolko** [comment]
As the documentation says use `io.appium.java_client.Location` instead of `org.openqa.selenium.html5.Location`

**Comment by asolntsev** [comment]
@umerhamdan10 It seems your question is related to Appium, not Selenide.
