### ISSUE TITLE
Setting Configuration.clickViaJs is not taken into account when clicking

### ISSUE THREAD

**Issue by vasilyevit** [selenide/selenide#2679]
## The problem
In Selenide 7.1.0 setting Configuration.clickViaJs is not taken into account when clicking. The problem appeared in PR https://github.com/selenide/selenide/pull/2636/files#diff-65f4944525328422c0b02a3a1352894d53400e8146ab6d7a9f8768c6b55f930fL49 

## Tell us about your environment
* **Selenide Version**: 7.1.0, 7.2.0

## Code To Reproduce Issue [ Good To Have ]
HTML page example https://pastebin.com/p9fRPqyy

```
@Test
    void checkClickViaJs(){
        Configuration.clickViaJs = true;
        open(...);
        $x("//button").click();
    }
```

**Comment by asolntsev** [comment]
will be fixed by https://github.com/selenide/selenide/pull/2678
