### ISSUE TITLE
File downloads not working in Chrome v122 and Selenide 7.2.0

### ISSUE THREAD

**Issue by ccea-dev-team** [selenide/selenide#2689]
## The problem

Might be some issue with ChromeDriver for V122 as it stopped insecure downloads blocking things like .xls and pdf.  I've added a chrome option in the disable that, --disable-features=InsecureDownloadWarnings, but the file still does not seem to download.

## Tell us about your environment
* **Selenide Version**:  7.2.0
* **Chrome Version**: 122.0.6261.129 (Official Build) (64-bit
* **Selenium Version**: 4.18.1
* **OS Version**: Win 10

## Code To Reproduce Issue

Chrome options at set up - 

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--start-maximized");
    options.addArguments("--remote-allow-origins=*");
    options.addArguments("--disable-notifications");
    options.addArguments("--disable-features=InsecureDownloadWarnings");
    options.addArguments("--password-store=basic");		    
    Map<String, Object> prefs = new HashMap<String, Object>();
    prefs.put("credentials_enable_service", false);
    prefs.put("password_manager_enabled", false); 
    options.setExperimentalOption("prefs", prefs);
    Configuration.browserCapabilities = options;
    Configuration.browserSize = null;
    Configuration.fileDownload = FileDownloadMode.FOLDER;

Code to download file - 

    File file =  $("#hrFileExportsform\\:hrExportDwnBtn").download();

Messages in logs - 

![1](https://github.com/selenide/selenide/assets/99395943/b2e9cb57-16c9-4135-b07d-a92d8a18834b)

Gets file not found after 15 secs.  The download folder was created in the path ok but the file was not saved into it.  However the file was downloaded to the users download folder.

**Comment by BorisOsipov** [comment]
We couldn't set prefs using Configuration.browserCapabilities because those completely override Selenide's defaults, including the way downloads directory is set.

**Comment by BorisOsipov** [comment]
You can set it via `System.setProperty("chromeoptions.prefs","credentials_enable_service=false,password_manager_enabled=false");`

**Comment by ccea-dev-team** [comment]
Yup that worked and file downloaded ok.  Thanks
