### ISSUE TITLE
Run Automation code on different environment(Staging, Production)

### ISSUE THREAD

**Issue by nicholaswkc34** [selenide/selenide#2695]
## The problem
My automation code need to run on different environment which are staging and production. In this, there are different in URL. How to achieve this?

## Details
My automation code need to run on different environment which are staging and production. In this, there are different in URL. How to achieve this?

## Tell us about your environment
* **Selenide Version**: 7.2.1
* **Chrome\Firefox\IE Version**: 118
* **Browser Driver Version**:
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version**: 4.12.0
* **OS Version**: Window 10

## Code To Reproduce Issue [ Good To Have ]
Nope.

**Comment by asolntsev** [comment]
@nicholaswkc34 Selenide has parameter `Configuration.baseUrl` to solve your problem.
You can set its value in some of "before all" or "before each" methods:

```java
Configuration.baseUrl = "https://my.production.com";
// or
Configuration.baseUrl = "https://my.staging.com";
```

**Comment by nicholaswkc34** [comment]
That one is baseURL configuration but I'm looking for profile managemnet.

**Comment by asolntsev** [comment]
@nicholaswkc34 I am afraid I don't what means "profile management" in this context...

**Comment by rosolko** [comment]
@asolntsev As far as I understood the question is related to driver initialization with different options. This case it's related to custom driver creation - https://github.com/selenide/selenide/wiki/How-Selenide-creates-WebDriver
@nicholaswkc34 Using this approach you can create environment specific driver configuration and initialize an appropriate

**Comment by asolntsev** [comment]
@nicholaswkc34 may I ask how browser profile can depend on environment (prod/stage)? I don't understand. 

It seems reasonable to me to run tests with the same profile to avoid tests working differently in different environments.

**Comment by asolntsev** [comment]
@nicholaswkc34 may I ask how browser profile can depend on environment (prod/stage)? I don't understand. 

It seems reasonable to me to run tests with the same profile to avoid tests working differently in different environments.

**Comment by nicholaswkc34** [comment]
I think you all misunderstand the questions. I want my automation code run on different environemnt like staging and production which will have different URL and not browser profile.

**Comment by asolntsev** [comment]
> I think you all misunderstand the questions. I want my automation code run on different environemnt like staging and production which will have different URL and not browser profile. I know Maven support it but I forgot the exact command. 

Then my first answer solves your problem: https://github.com/selenide/selenide/issues/2695#issuecomment-2017241706

**Comment by cemerick1** [comment]
You can also store them in environment properties files.

**Comment by nicholaswkc34** [comment]
I wonder how to run specfiic URL from maven.

**Comment by asolntsev** [comment]
Then your question is about Maven, not Selenide. Right?
You just need to pass some system variables from Maven to your tests. 

```xml
<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <systemPropertyVariables>
                <selenide.baseUrl>https://my.test.env.com</selenide.baseUrl>
                <selenide.browser>firefox</selenide.browser>
                <selenide.headless>true</selenide.headless>
              </systemPropertyVariables>
            </configuration>
          </plugin>
```
