### ISSUE TITLE
Sometimes WebDriverRunner.closeWebDriver() creates extra browser entity processes when --no-sandbox capability is set

### ISSUE THREAD

**Issue by extryd** [selenide/selenide#2731]
## The problem
After running tests I have a lot of active browser entity processes which uses CPU up to 100%. Based on my testing I have noticed that these extra processes get created at `WebDriverRunner.closeWebDriver()` step AND when `--no-sandbox` capability is set.

## Details
It is reproduced in Chrome and Edge browsers. Switching off `--no-sandbox` capability fixes the problem. For me the issue is reproduced in ~30% of tests.
Additional note: During the writing the code sample I wasn't able to reproduce this issue with google.com and apple.com sites. Looks like the issue is depend of site itself 🤷‍♂️

## Tell us about your environment
* **Selenide Version**: 7.3.1
* **Chrome\Edge**: 124.0.6367.92 \ 124.0.2478.67
* **Selenium Version**:  4.20.0
* **OS Version**: W11 23H2 22631.3447

## Code To Reproduce Issue [ Good To Have ]
invocationCount = 10 is added since as it was mentioned above the issue isn't 100% cases reproduceable

```
public class TestClass {
    @BeforeSuite(alwaysRun = true)
    public static void setUp() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--no-sandbox");
        Configuration.browserCapabilities = options;
    }

    @AfterMethod(alwaysRun = true)
    public void closeWebDriver() {
        WebDriverRunner.closeWebDriver();
    }

    @Test(invocationCount = 10)
    public void test() {
        Selenide.open("https://www.youtube.com/");
    }
}
```

Here are examples of Task Manager after running code above
![chrome](https://github.com/selenide/selenide/assets/69474601/4610fa11-15ed-4dd2-afd1-46fe25c3709e)
![edge](https://github.com/selenide/selenide/assets/69474601/c52acc41-8300-4ce3-92a9-35c24c1f8142)

**Comment by nikitakovaliov92** [comment]
This is chrome issue: https://issues.chromium.org/issues/336164423

but I wonder why it works in playwright with `--no-sandbox` option

**Comment by extryd** [comment]
My bad, I haven't checked closed issues in selenium :)

**Comment by nikitakovaliov92** [comment]
> but I wonder why it works in playwright with `--no-sandbox` option

`--disable-renderer-backgrounding` is the reason why it works in playwright

**Comment by asolntsev** [comment]
@nikitakovaliov92 Strange: I can reproduce the problem on a Windows laptop. And option `--disable-renderer-backgrounding` doesn't help. The problem still persists.
