### ISSUE TITLE
Selenide Proxy downloads file with wrong name

### ISSUE THREAD

**Issue by Valentino-sys** [selenide/selenide#2733]
## The problem
I'm download file with Selenide Proxy cause element does not have a href, but file downloading with wrong name and without extention

## Details
The file downloads to the buld/downloads folder, but with wrong name. Instead of Regression Jobseeker_CV.pdf -> just '-'.

## Tell us about your environment
* **Selenide Version:**: 7.3.1
* **Chrome\Firefox\IE Version**:  latest
* **Browser Driver Version: latest**: latest
* **OS Version**: Windows

## Code To Reproduce Issue [ Good To Have ]
    @Given("setup proxy settings to download files from browser")
    public void setProxy() {
        Configuration.proxyEnabled = true;
        Configuration.fileDownload = PROXY;
    }
    @Then("I download a resume from preview modal and check that resume is downloaded with name {string}")
    public void assertCvDownload(String cvName) {
        assertActualFieldIsEqualToExpected(applicationManagementPage.downloadCVAndGetName(), cvName);
    }

    public String downloadCVAndGetName() {
        File cv = downloadCVButton.download();

        return cv.getName();
    }

I get file name and comparing with expected. And get assert Error:
expected: "Regression JobSeeker_CV.pdf"
 but was: "_"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)

Downloaded file:
![image](https://github.com/selenide/selenide/assets/72161585/c5f37b6a-7503-4655-9bd0-2ea46a881f47)
FYI : I i rename this file with correct name and extension manually it's has a valid content inside

Which interesting that this file was downloaded to another folder wtih correct name, but File object refers specifically to file with '-'
![image](https://github.com/selenide/selenide/assets/72161585/95480f33-3a47-42ab-a1d7-e70d9a548dab)

**Comment by asolntsev** [comment]
@Valentino-sys Sometimes browser downloads several files, including its own internal stuff. 
Then proxy cannot decide which one of these files you wanted to download.

But you can give proxy a hint. Replace `downloadCVButton.download()` by `downloadCVButton.download(withExtension("pdf")` or even `downloadCVButton.download(withName("Regression JobSeeker_CV.pdf")`.
