### ISSUE TITLE
shadowDeepCss failed to locate the element

### ISSUE THREAD

**Issue by ToniHuynh** [selenide/selenide#2747]
## The problem
Hi guys,

I'm quite new to Selenide and automation.

I tried to use shadowDeepCss to locate a button that is behind a shadow-root (closed) but it keeps failing. My code as below:
 
using Selenide shadowDeepCss to find and click an element inside a Shadow-Root

```
            String cssSelector = "#element-rDtQoq";
            $(shadowDeepCss(cssSelector)).click();

```

However, it works fine with the jQuery as below:
          
```
  String clickScript = "document.querySelector(\"[campaignid^='25']\").shadow.querySelector(\"#element-rDtQoq\").click();";
            executeJavaScript(clickScript);
```

## Details
Here is the shorten HTML code:

```
<yld-tag-host-campaign campaignid="251791">
#shadow-root (closed)
<form tabindex="-1" novalidate="" style="margin: 0; overflow: hidden; width: 500px; height: 500px;">
<button id="element-rDtQoq" y-id="element-rDtQoq" y-type="custom-close-button" style="left:481.5px;overflow:visible;position:absolute;top:-17px;height:37px;width:37px;z-index:7;border:none;background:none;cursor:pointer" type="button" role="button" aria-label="close" tabindex="1"><span style="border-radius:50% 50% 50% 50%;box-sizing:border-box;background:#000;border:2px solid #fff;outline:none;filter:drop-shadow( -3px 3px 5px #000 );display:block;width:65%;height:65%;margin:17.5%"><svg viewBox="0 0 11 11" style="position:absolute;top:50%;left:50%;transform:translate3d(-50%, -50%, 0);width:10px;height:10px"><line x1="1" y1="1" x2="10" y2="10" stroke="#fff" stroke-width="2" stroke-linecap="butt"></line><line x1="10" y1="1" x2="1" y2="10" stroke="#fff" stroke-width="2" stroke-linecap="butt"></line></svg></span></button>
</form>
</yld-tag-host-campaign>
```

## Tell us about your environment
* **Selenide Version**:  7.3.1
* **Chrome\Firefox\IE Version**:  114
* **Browser Driver Version**:
* **Selenide-Appium Version**:
* **IOS\Android\WEB version**:
* **Selenium Version**: 4.20.0
* **OS Version**: Windows 11

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by BorisOsipov** [comment]
Hi @ToniHuynh 

`shadow-root (closed)` prevents external access. please read the docs
https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM#element.shadowroot_and_the_mode_option


>"document.querySelector(\"[campaignid^='25']\").shadow.querySelector(\"#element-rDtQoq\"

It is not jQuery and is not valid js. Even if I fix it like `shadow=>shadowRoot` it will return `null` for closed shadow-dom as designed.

>However, it works fine with the jQuery as below:

Please provide a reproducible example - some URL to the site where we can reproduce the problem. Just some html does not seem to be enough.

**Comment by asolntsev** [comment]
Feel free to reopen the issue if we get a reproducible example.
