### ISSUE TITLE
shouldHave(Condition.value("")) matches any value instead of empty only

### ISSUE THREAD

**Issue by AleksandrHoroshko** [selenide/selenide#2760]
$(#someElement).shouldHave(Condition.value(""))
Even if found element has value="asdfasd" test is still passed
But when I change it to .shouldHave(Condition.attribute("value", "")) it works like expected, test passed only if element has empty value

**Comment by BorisOsipov** [comment]
See [javadoc ](https://github.com/selenide/selenide/blob/main/src/main/java/com/codeborne/selenide/Condition.java#L211) `Condition.value` checks `contains given "value" attribute as substring`. An empty string occurs in every string.

`Condition.attribute("value", "")` matches the full text.

If you want to make all checks strict by default, use `com.codeborne.selenide.Configuration#textCheck=FULL_TEXT`.

**Comment by AleksandrHoroshko** [comment]
But why value and partialValue is the same? It looks like value should work as full match and partialValue should work as partial match, but now they both work by partial match

<img width="867" alt="Screenshot at Jun 06 14-40-32" src="https://github.com/selenide/selenide/assets/51399666/86d0b5b7-5174-4fa2-bb8a-5b8dd4af92e7">

**Comment by BorisOsipov** [comment]
Because `partialValue` has been added with the `Configuration#textCheck` option to allow partial checking with `FULL_TEXT` mode.
We cannot change the default `value()` to a full match due to backward compatibility.
