### ISSUE TITLE
Need a method to scroll an element by a specified amount

### ISSUE THREAD

**Issue by donnieHub** [selenide/selenide#2769]
## The problem
Quite often there is a need to scroll down a particular element on a page (for example left menu on youtube page). This can be useful when content inside the element appears dynamically, i.e. only when you scroll down to it. 
Less often there is a need to scroll an element to the right.

## Details
This behavior can be easily achieved by using the javascript method `scrollBy()`. For example, if you want to scroll an element with id “box” down by 50 pixels, you can do:
```
const element = document.getElementById("box");
element.scrollBy(0, 50);
```
I have already implemented this method locally for selenide. I just need to get confirmation that this method is really necessary. It will look like this:
```
SelenideElement element = $("#box");
element.scrollOnElement(1000); // scroll element down by 1000 pixels
element.scrollOnElement(-1000); // scroll element up by 1000 pixels
element.scrollOnElement(0, 1000); // scroll element to the right by 1000 pixels
```

## Tell us about your environment
* **Selenide Version 7.3.1**: 
* **Chrome Version 126.0.6478.114**:

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/2809
