### ISSUE TITLE
Selenide, Jenkins // After running jobs on locally deployed Jenkins, the screenshot in allure looks very strange (grey content)

### ISSUE THREAD

**Issue by StasiukMarian** [selenide/selenide#2775]
**Brief info:**
I deployed Jenkins locally and configured the necessary plugins.
I take a screenshot during execution and in allure I see that screenshot is empty (black screen) in the report

**Environment:**
Allure Jenkins Plugin - Version 2.31.1
Selenide version - 7.3.2
Chrome version - 126.0.6478.127

What Operating System are you using (both controller, and any agents involved in the problem)?
Controller: Windows 11
Agents: Windows 11

**Reproduction steps**
I configured code to take a screenshot which was working previously:
```java
@Listeners({TextReport.class})
public class BaseTest {
    @BeforeClass
    public void configuration() {
            SelenideLogger.addListener("AllureSelenide", new AllureSelenide()
                .screenshots(true)
                .savePageSource(false));
    } 
    }
```

**also attached pom.xml file:**
[pom.txt](https://github.com/user-attachments/files/16086779/pom.txt)

I created locally freestyle job with a:
Source code management - Git,
Build Steps - Invoke top-level Maven targets - Goals: clean install
Post-build Actions - Allure report
**Expected Results**
After bulid done should be created allure report with a screenshot if test failed:

Local execution from IntelliJIdea:
![image](https://github.com/selenide/selenide/assets/91457119/a303141f-852e-4605-b18f-90777f21e981)
**Actual Results**
After bulid done created allure report with a screenshot if test failed:

Execution from Jenkins - Screenshot is empty (black screen if download):
![image](https://github.com/selenide/selenide/assets/91457119/ba1df576-ab4f-4dce-ba32-3df740e2b51e)

Screenshot:
![image](https://github.com/selenide/selenide/assets/91457119/9629de63-e58f-48ca-9803-663d1e20d37f)

**Notes:**
With the same code everything works month ago.

After installing a new version Jenkins with Allure Jenkins Plugin - Version 2.31.1 this issue happens.

**Also attaching github project:**
https://github.com/StasiukMarian/sep-2023-aqa.git

**Comment by BorisOsipov** [comment]
>With the same code everything works month ago.

So if nothing changes in the code, it is obviously your environment issue not related to Selenide/Selenium. Dunno why you decided to report it to selenide repo.
