### ISSUE TITLE
onBanner method from 6.13.0 release is missing

### ISSUE THREAD

**Issue by kamil1014** [selenide/selenide#2781]
## The problem
Hello, according to release notes:
https://selenide.org/2023/04/01/selenide-6.13.0/
there should be method Selenide.onBanner to handle banners.

## Details
There is no such a method in newest selenide version.

## Tell us about your environment
* **Selenide Version7.3.2: 

## Code To Reproduce Issue [ Good To Have ]
Get new version of selenide and check for method Selenide.onBanner

**Comment by asolntsev** [comment]
@kamil1014 Pay attention to the date of that post. :)
It was April, 1st. :) 

P.S. Anyway, later we released a similar method: https://selenide.org/2024/02/07/selenide-7.1.0/#if-with-timeout
