### ISSUE TITLE
List collection of type SelenideElement.class: RemoteWebElement cannot be cast to SelenideElement

### ISSUE THREAD

**Issue by ylazakovich** [selenide/selenide#2786]
## The problem

```java
  private static class MyContainer implements Container {
    @FindBy(css = "#hero>option")
    List<SelenideElement> options;
```

When I make any browser action with field `options` - `click()`, `getText()` and etc.
Then returns issue about casting `RemoteWebElement` to `SelenideElement`:
```java
class org.openqa.selenium.remote.RemoteWebElement cannot be cast to class com.codeborne.selenide.SelenideElement (org.openqa.selenium.remote.RemoteWebElement and com.codeborne.selenide.SelenideElement are in unnamed module of loader 'app')
```

## Details
This case reproduced when field 
1) init over `@FindBy`
2) has type `List<SelenideElement>`

## Tell us about your environment
* **Selenide Version**: 7.3.3
* **Selenium Version**: 4.22.0

## Code To Reproduce Issue [ Good To Have ]

[integration.pageobjects.ElementsContainerWithManuallyInitializedFieldsTest](https://github.com/selenide/selenide/blob/4ee0099289e91f4a87c95a934c6656faa832d509/statics/src/test/java/integration/pageobjects/ElementsContainerWithManuallyInitializedFieldsTest.java#L19)

```java
  @Test
  void canInitializeElementsContainerFieldsWithoutFindByAnnotation() {
    MyPage page = page();
    page.container.options.get(0).getText();
  }

 private static class MyPage {
    @FindBy(css = "#apostrophes-and-quotes")
    MyContainer container;
  }

  private static class MyContainer implements Container {
    SelenideElement headerLink = $("h2>a");
    @FindBy(css = "#hero>option")
    List<SelenideElement> options;
  }
```

**Comment by asolntsev** [comment]
Can you please specify why do you need `List<SelenideElement>`?
What benefits it gives over `ElementsCollection`?

I am asking because it's much easier to forbid `List<SelenideElement>` than implement it.

**Comment by ylazakovich** [comment]
No any benefits
It was discovered completely by accident

I'm agree with your solution 
to forbid `List<SelenideElement>` than implement it.

**Comment by asolntsev** [comment]
In the end, I added support for `List<SelenideElement>` in https://github.com/selenide/selenide/pull/2787
Maybe it's not really needed, and we still can forbid `List<SelenideElement>` in future, but this time... it was easier to allow. :)
