### ISSUE TITLE
Remote downloading in FOLDER mode

### ISSUE THREAD

**Issue by viraart** [selenide/selenide#2789]
## The problem
I've tried to use file download ability using FOLDER mode (selenide-grid 7.3.2).
With this code locally all works fine:
```java
Configuration.downloadsFolder =  "C:\\Users\\User1\\Downloads";
Configuration.fileDownload = FileDownloadMode.FOLDER;
File downloadedPDF = $x("//footer//bdi[text() = 'Export to PDF']/ancestor::button").download();
```

But when I try to run the same test remotely(-Dwebdriver.type=remote) it fails with:
"You must enable downloads in order to work with downloadable files."

## Details
After I specified "se:downloadsEnabled=true" manually next error appeared:
"WebDriverException: Please enable management of downloads via the command line arg [--enable-managed-downloads] and restart the node
Timeout: 60 s"

After setting "--enable-managed-downloads" up manually tests start attempt to use local file system instead of remote one.

Could you please confirm that FOLDER mode doesn't supports webdriver remote? 
Or should I configure smth additionally?

## Tell us about your environment
* **Selenide Version**: 7.3.2

**Comment by asolntsev** [comment]
Method `$.download()` **works with Selenium Grid** starting from version 7.2.0: https://selenide.org/2024/02/27/selenide-7.2.0/#download-files-to-folder-in-selenium-grid

What exactly means "tests start attempt to use local file system instead of remote one"?

**Comment by IlyaMaliauka** [comment]
Greetings @asolntsev, 
Here's some more context (we share the same project with a reporter): 
We actually use Selenoid + Selenide 7.3. 
We used to download our files via standard Http request just like it's proposed by selenoid docs. 
And the post https://selenide.org/2024/02/27/selenide-7.2.0/#download-files-to-folder-in-selenium-grid was the actual reason why we tried to use both FOLDER and CDP download method. However neither of them work regardless of Configuration.downloadsFolder param was set manually or the default value was used. 


> Here's an error that occurs when we use  Configuration.fileDownload = FileDownloadMode.CDP;
> 10:12:17.686 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.commands.Clear: com.codeborne.selenide.commands.Clear
> 10:12:17.741 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.DownloadFileToFolder: com.codeborne.selenide.impl.DownloadFileToFolder
> 10:12:17.746 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.DownloadFileWithCdp: com.codeborne.selenide.impl.DownloadFileWithCdp
> 10:12:17.767 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.commands.Commands: com.codeborne.selenide.appium.commands.SelenideAppiumCommands
> 10:12:17.898 [main] DEBUG com.codeborne.selenide.commands.DownloadFile -- Download file: method: CDP, timeout: 60000 ms
> 10:12:18.389 [main] DEBUG com.codeborne.selenide.impl.DownloadFileWithCdp -- clear devtools listeners
> 10:12:18.423 [main] DEBUG com.codeborne.selenide.impl.DownloadFileWithCdp -- add devtools listener for 'downloadWillBegin'
> 10:12:18.427 [main] DEBUG com.codeborne.selenide.impl.DownloadFileWithCdp -- add devtools listener for 'downloadProgress'
> 2024-07-23 10:12:18 [main] INFO  BrowserTest: openBrowser Clicked webElement  css selector: #table-files > tbody > tr:nth-child(2) > td.text-right.file-link > a]
> 10:13:18.701 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.ex.ErrorFormatter: com.codeborne.selenide.ex.SelenideErrorFormatter
> 
> Failed to download file in 60000 ms., found files: [C:\Users\MyUser\IdeaProjects\MyProject\build\downloads\1718313772809_32656_1]
> Timeout: 60 s.


> And here's the one when we use  Configuration.fileDownload = FileDownloadMode.FOLDER;
> 10:16:43.584 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.impl.ElementDescriber: com.codeborne.selenide.appium.AppiumElementDescriber
> 10:16:43.625 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.commands.Clear: com.codeborne.selenide.commands.Clear
> 10:16:43.682 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.DownloadFileToFolder: com.codeborne.selenide.impl.DownloadFileToFolder
> 10:16:43.685 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.DownloadFileWithCdp: com.codeborne.selenide.impl.DownloadFileWithCdp
> 10:16:43.710 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.commands.Commands: com.codeborne.selenide.appium.commands.SelenideAppiumCommands
> 10:16:43.831 [main] DEBUG com.codeborne.selenide.commands.DownloadFile -- Download file: method: FOLDER, timeout: 60000 ms
> 2024-07-23 10:16:43 [main] INFO  BrowserTest: openBrowser Clicked webElement  css selector: #table-files > tbody > tr:nth-child(2) > td.text-right.file-link > a]
> 10:43.522 [main] DEBUG com.codeborne.selenide.impl.DownloadFileToFolder -- Matching files not found: [], all new files: [], all files: [1718313772809_32656_1]
> ......
> 10:17:43.929 [main] DEBUG com.codeborne.selenide.impl.DownloadFileToFolder -- Matching files still not found -> stop waiting for new files after 60012 ms. (timeout: 60000 ms.)
> 10:17:43.933 [main] DEBUG com.codeborne.selenide.impl.DownloadFileToFolder -- No [crdownload, tmp] files found, conclude download is completed (filter: none)
> 10:17:43.941 [main] INFO com.codeborne.selenide.impl.DownloadFileToFolder -- Downloaded files in C:\Users\MyUser\IdeaProjects\MyProject\build\downloads: []
> 10:17:43.942 [main] DEBUG com.codeborne.selenide.impl.DownloadFileToFolder -- All downloaded files: [1718313772809_32656_1]
> 10:17:43.952 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.ex.ErrorFormatter: com.codeborne.selenide.ex.SelenideErrorFormatter
> 
> Failed to download file in 60000 ms.
> Timeout: 60 s.

As far as I can see from logs, in both cases compiler tried to find the file on the local machine, not the selenoid. 
Connection to the selenoid is established by using Configration.remote = http://my.cool.ip:4444/wd/hub

**Comment by asolntsev** [comment]
If you use Selenoid, then you need "

**Comment by asolntsev** [comment]
If you use Selenoid, then you need "selenide-selenoid" dependency instead of "selenide-grid". It can download files from Selenoid.

**Comment by IlyaMaliauka** [comment]
Thank you for the hint, it works well now :) 
Considered doing so in the first hand, but I read that project "selenide-selenoid" was merged into project "selenide". Right now I see that I need to add the dependency anyway.
