### ISSUE TITLE
com.codeborne.selenide.appium.AppiumElementDescriber is invoked even if default Chrome/Edge browsers are used.

### ISSUE THREAD

**Issue by IlyaMaliauka** [selenide/selenide#2790]
## The problem
We initialize browser with 
```java
Configuration.browser = isMobile() ? "SelenideAppiumDriverFactory.class.getName()" : "edge/chrome";
```

Since we added `selenide-appium` dependency to our project, I always see messages like this regardless of do use Mobile browser or not: 
```java
Using implementation of com.codeborne.selenide.impl.ElementDescriber: com.codeborne.selenide.appium.AppiumElementDescriber
```

Which caused no problems even though it looked strange. 
But recently our tests on Edge started failing with an error:
```java
ConnectionFailedException: JdkWebSocket initial request execution error
Timeout: 10 s.
Caused by: ConnectionFailedException: JdkWebSocket initial request execution error
```

Which obviously indicates some kind of a problem with CDP.
I removed `selenide-appium` dependency, added `selenium-remote` instead and it fixed the issue. 
But we do need appium in our project. 
Is this behaviour expected? 

## Tell us about your environment
* **Selenide Version**: latest 
* **Selenide-Appium Version**: latest

**Comment by BorisOsipov** [comment]
>Is this behaviour expected?

No, but without a stack trace and a reproducible example it is impossible to help. For me Edge works like a charm.

**Comment by IlyaMaliauka** [comment]
Here's our full configuration:
Configuration.screenshots = ENABLE_SCREENSHOTS_PROPERTY;
        Configuration.savePageSource = false;
        Configuration.timeout = SELENIDE_TIMEOUT_PROPERTY;
        Configuration.fileDownload = FileDownloadMode.FOLDER;
        Configuration.downloadsFolder = isSelenoid() ? "target/downloads" : "/build/downloads/";
        Configuration.reportsFolder = REPORTS_FOLDER_PROPERTY;
        Configuration.browserCapabilities = 
        capabilities.setCapability("browserName", "MicrosoftEdge");
        capabilities.setCapability("browserVersion", "123.0");
        capabilities.setCapability("selenoid:options", Map.of("enableVNC", true,
                "enableVideo", "true",
                "name", "$ourSessionNameHere",
                "sessionTimeout", SELENOID_SESSION_TIMEOUT));
        Configuration.reportsFolder = REPORTS_FOLDER_PROPERTY;


Then I just open the browser with selenide and the error is following;

> ConnectionFailedException: JdkWebSocket initial request execution error
> Timeout: 10 s.
> Caused by: ConnectionFailedException: JdkWebSocket initial request execution error
> 
> 	at com.codeborne.selenide.ex.UIAssertionError.wrapToUIAssertionError(UIAssertionError.java:131)
> 	at com.codeborne.selenide.ex.UIAssertionError.wrapThrowable(UIAssertionError.java:114)
> 	at com.codeborne.selenide.ex.UIAssertionError.wrap(UIAssertionError.java:108)
> 	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:96)
> 	at jdk.proxy2/jdk.proxy2.$Proxy45.setValue(Unknown Source)
> 	at autotests.framework.page.AzureAuthenticationPage.passAzureAuthWithCert(AzureAuthenticationPage.java:25)
> 	at util.BrowserTest.openBrowser(BrowserTest.java:24)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
> 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
> 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
> 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
> 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
> 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
> 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
> 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:848)
> 	at org.testng.TestRunner.run(TestRunner.java:621)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
> 	at org.testng.TestNG.runSuites(TestNG.java:1114)
> 	at org.testng.TestNG.run(TestNG.java:1082)
> 	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
> 	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
> Caused by: org.openqa.selenium.remote.http.ConnectionFailedException: JdkWebSocket initial request execution error
> Build info: version: '4.22.0', revision: 'c5f3146703*'
> System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
> Driver info: driver.version: unknown
> 	at org.openqa.selenium.remote.http.jdk.JdkHttpClient.openSocket(JdkHttpClient.java:246)
> 	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:89)
> 	at org.openqa.selenium.devtools.SeleniumCdpConnection.<init>(SeleniumCdpConnection.java:36)
> 	at org.openqa.selenium.devtools.SeleniumCdpConnection.lambda$create$3(SeleniumCdpConnection.java:103)
> 	at java.base/java.util.Optional.map(Optional.java:260)
> 	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:103)
> 	at org.openqa.selenium.devtools.SeleniumCdpConnection.create(SeleniumCdpConnection.java:49)
> 	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:50)
> 	at org.openqa.selenium.devtools.DevToolsProvider.getImplementation(DevToolsProvider.java:29)
> 	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:207)
> 	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:178)
> 	at com.codeborne.selenide.impl.WebdriverUnwrapper.unwrap(WebdriverUnwrapper.java:57)
> 	at com.codeborne.selenide.impl.WebdriverUnwrapper.unwrap(WebdriverUnwrapper.java:53)
> 	at com.codeborne.selenide.impl.WebdriverUnwrapper.cast(WebdriverUnwrapper.java:30)
> 	at com.codeborne.selenide.impl.WebdriverUnwrapper.cast(WebdriverUnwrapper.java:26)
> 	at com.codeborne.selenide.impl.WebdriverUnwrapper.instanceOf(WebdriverUnwrapper.java:18)
> 	at com.codeborne.selenide.appium.AppiumDriverUnwrapper.isMobile(AppiumDriverUnwrapper.java:13)
> 	at com.codeborne.selenide.appium.commands.AppiumSetValue.execute(AppiumSetValue.java:25)
> 	at com.codeborne.selenide.appium.commands.AppiumSetValue.execute(AppiumSetValue.java:16)
> 	at com.codeborne.selenide.commands.Commands.execute(Commands.java:162)
> 	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:134)
> 	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:86)
> 	... 28 more
> Caused by: java.net.http.WebSocketHandshakeException
> 	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:224)
> 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
> 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
> 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
> 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:844)
> 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
> Caused by: jdk.internal.net.http.websocket.CheckFailedException: Unexpected HTTP response status code 502
> 	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.checkFailed(OpeningHandshake.java:341)
> 	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.handleResponse(OpeningHandshake.java:250)
> 	at java.net.http/jdk.internal.net.http.websocket.OpeningHandshake.resultFrom(OpeningHandshake.java:220)
> 	... 10 more
>

**Comment by asolntsev** [comment]
@IlyaMaliauka Thank you for reporting. 
In PR https://github.com/selenide/selenide/pull/2791, AppiumElementDescriber will be fixed (will fall back to SelenideElementDescriber if a web browser is opened). 

BUT
I see from your stack trace that `AppiumElementDescriber` was not a problem. I see `WebSocketHandshakeException` - I assume it's rather a bug in Selenium's `Augmenter` class that tries to establish CDP connection with mobile app.

**Comment by matvey-podbelsky-quarks-tech** [comment]
@asolntsev, @IlyaMaliauka, I had the same problem with selenoid + android driver. Fixed by adding capabilities se:cdpEnabled", false

**Comment by IlyaMaliauka** [comment]
Thank you guys, will wait for the update.
 Unfortunately adding "se:cdpEnabled" cap. didn't help, seems like it's only for appium. But the things is that I don't use appium in this particular scenario.
@asolntsev actually the logs are very strange, 
I simlified the test to minimum, it's a simple login now. However there are messages about some downloads (with CDP, actually, even though we use Folder download method). 

Here's my whole test: 
```
Selenide.open(BASE_URL);
 $(USER_MAIL_FIELD).setValue(email);
        $(NEXT_BUTTON).click();

```
And some logs:
> 2024-07-24 11:18:13 [main] INFO  Navigation to https://sapedia-qa.one.int.sap/wiki/ completed
> 11:18:13.966 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.WebElementSelector: com.codeborne.selenide.impl.WebElementSelector
> 11:18:13.971 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.impl.ElementDescriber: com.codeborne.selenide.appium.AppiumElementDescriber
> 11:18:14.015 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.commands.Clear: com.codeborne.selenide.commands.Clear
> 11:18:14.069 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.impl.DownloadFileToFolder: org.selenide.selenoid.DownloadFileInSelenoid
> 11:18:14.073 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.impl.DownloadFileWithCdp: com.codeborne.selenide.impl.DownloadFileWithCdp
> 11:18:14.093 [main] INFO com.codeborne.selenide.impl.Plugins -- Using implementation of com.codeborne.selenide.commands.Commands: com.codeborne.selenide.appium.commands.SelenideAppiumCommands
> 11:18:24.196 [main] DEBUG com.codeborne.selenide.impl.Plugins -- Using default implementation of com.codeborne.selenide.ex.ErrorFormatter: com.codeborne.selenide.ex.SelenideErrorFormatter
