### ISSUE TITLE
Add class Widget with SelenideAppiumElement ilike in appium

### ISSUE THREAD

**Issue by DaniilMoiseevPenza** [selenide/selenide#2808]
## The problem
Widgets in appium is class for working with widgets.
Its very powerful for some issues, f.e. i have PageObject:

```java
public class AndroidSettingsPage{

    @AndroidFindBy(xpath = "//*[contains(@resource-id,\"recycler_view\")]/android.widget.LinearLayout")
    private List<SettingsWidget> settingsWidgets;
}
```

And WidgetClass:

```java
public class SettingsWidget extends Widget {

    @AndroidFindBy(id = "android:id/title")
    private WebElement title;

    @AndroidFindBy(id = "android:id/checkbox")
    private WebElement checkbox;

    public String getTitle() {
        return title.getText();
    }
}
```

When i inizializate AndroidSettingsPage i have list settings and with then very easy to work.
But they returned WebElement and it is hard to work with them with selenide.

Another problem that then i call page(AndroidSettingsPage.class) my list is null.

Can you please fix this?

https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/pagefactory/Widget.java

Code for this widget in appium repository

**Comment by asolntsev** [comment]
@DaniilMoiseevPenza Just replace `class SettingsWidget extends Widget` -> `class SettingsWidget implements Container`

**Comment by DaniilMoiseevPenza** [comment]
@asolntsev 
with List not working(

![image](https://github.com/user-attachments/assets/40d848bd-bb30-48e9-a81a-ba7691a45aa1)
![image](https://github.com/user-attachments/assets/c57aad81-1bcc-4cef-b77d-1fc031d72f46)


@Getter
public class SettingsWidget implements Container {

    @AndroidFindBy(id = "android:id/title")
    private SelenideAppiumElement title;

    @AndroidFindBy(id = "android:id/checkbox")
    private SelenideAppiumElement checkbox;

    public String getTitle() {
        return title.getText();
    }

    public void waitUntilVisibleCheckbox() {
        checkbox.shouldBe(visible);
    }

    public void setCheckbox() {
        checkbox.click();
    }

    public boolean isChecked() {
        return Boolean.parseBoolean(checkbox.getAttribute(CHECKED));
    }
}

@Lazy
@Component
@Name("Android настройки")
public class AndroidSettingsPage extends AlfaMobilePage {

    private static final String ENABLE_TEST_SERVERS_SETTING = "Включить тестовые сервера";
    private static final String FAST_AUTHORIZATION_SETTING = "Быстрая авторизация";
    private static final String ENABLE_SSL_PINNING = "Online SSL Pinning";
    private static final String ENABLE_ONBOARDING = "Показывать onboarding";

    @Required
    @AndroidFindBy(xpath = "//android.widget.TextView[@text='Диагностика']")
    private SelenideAppiumElement diagnosticsTitle;

    @Required
    @AndroidFindBy(xpath = "//*[contains(@resource-id,\"recycler_view\")]/android.widget.LinearLayout")
    private List<SettingsWidget> settingsWidgets;

    @AndroidFindBy(id = "ru.alfabank.mobile.android.feature:id/action_bar_root")
    private FastRegistrationWidget fastRegistrationWidget;
}

**Comment by BorisOsipov** [comment]
>with List not working(

Yes, because lists are only decorated with `FindBy\FindBys` annotations. But on Appium there are lots of custom `Android/IosFindBy\CrapBy` annotations.

https://github.com/selenide/selenide/blob/main/src/main/java/com/codeborne/selenide/impl/SelenidePageFactory.java#L336
