### ISSUE TITLE
Add Conditions containsInnerText and ContainsAttribute

### ISSUE THREAD

**Issue by DaniilMoiseevPenza** [selenide/selenide#2819]
Hello.

It will be great if we will have next conditions:

containsInnerText ilike containsText

containsAttribute ilike containsText

**Comment by asolntsev** [comment]
@DaniilMoiseevPenza Can you please specify? I cannot find condition "containsText" in Selenide... 
I see only these:
* `$("h1").shouldHave(partialText("ello Joh"))`
* `$("h1").shouldHave(text("Hello John"))`
* `$("h1").shouldHave(innerText("Hello"))`

About attributes: what is the case?
Currently attribute-related conditions check the whole attribute:
* `$("#mydiv").shouldHave(attribute("fileId"))`

**Comment by DaniilMoiseevPenza** [comment]
@asolntsev 
Yes, sorry)
We have element
<div class="aJCxG4 hQWkTE" </div>

partialAttribute:
$("h1").shouldHave(partialAttribute("class","aJCxG4"))

partialInnerText:
$("h1").shouldHave(partialInnerText("ello Joh"))

**Comment by asolntsev** [comment]
Why not just use
1. `$("h1").shouldHave(cssClass("aJCxG4"))`
2. `$("h1").shouldHave(partialText("ello Joh"))`
?

**Comment by DaniilMoiseevPenza** [comment]
cssClass assert for contains, not equal?
if attrubute not class,f.e. some customer attrubute or image ?

partialText search for innersTexts?

if yes< sorry for issue,thank you for help))
