### ISSUE TITLE
 .select...() methods stopped triggering the event in Selenide version 7.4.2 

### ISSUE THREAD

**Issue by avkalabin** [selenide/selenide#2832]
## The problem
After Selenide was updated to 7.4.2, all .select...() methods stopped triggering the event that changes step_num (should change to 1 or 2 when selecting), but visually the selection is done.

## Tell us about your environment
* **Selenide Version**: 7.4.2
* **MicrosoftEdge Version **: 123.0.2420.53
* **Selenoid Version**: 1.11.2
* **Selenium Version**: v. 4.23.0 build revision: 4df0a231af
* **OS Version**: Ubuntu 22.04.3

## Code To Reproduce Issue [ Good To Have ]
![3](https://github.com/user-attachments/assets/6c2ce3b5-fe5d-47c6-a9b6-95ba2caedda4)

**Comment by asolntsev** [comment]
@avkalabin How can we reproduce the problem? 
I just tried - "change" and "input" events are correctly triggered in my tests. 
I have no idea what event is triggering `step_num` change in your page.

**Comment by avkalabin** [comment]
I'm not sure. Is there anything I can do to help reproduce or somehow figure out the problem? I'll try to find out what event triggers the step_num change.

**Comment by asolntsev** [comment]
The best way is to write a failing test. So that we could runthis test and reproduce the problem.

**Comment by avkalabin** [comment]
Sorry, I don't quite understand. Of course I can write my test code here, but if the tested product is not accessible from the outside, how do you run the test?

**Comment by asolntsev** [comment]
I mean, write a test for some public site. 
Like https://todomvc.com/ or https://the-internet.herokuapp.com/.

Or provide html snippet that has the same problem.
