### ISSUE TITLE
When downloading the file from an element without href on Edge, Selenide detects new window and fails to close.

### ISSUE THREAD

**Issue by IlyaHarlamov** [selenide/selenide#2836]
## The problem
When downloading the file from an element without href on Edge, Selenide detects new window and fails to close.
The test proceeds after the timeout of 20 seconds, but it increases the execution time and in my case, prevents to validate an element that appears for few seconds after downloading the file.

## Details
Here is the code I am running:
```java
element.download(DownloadOptions.using(FileDownloadMode.FOLDER).withTimeout(Duration.ofSeconds(15)));
```
In the browser, it shows the download error, however the file itself is downloaded and is available in the downloads folder.
<img width="356" alt="image" src="https://github.com/user-attachments/assets/e96c65ee-4a2b-4fd6-9a1e-a1a3fb113593">

**Here is the log:**
It states that new window has been opened, however I do not see it physically.
```
2024-09-06 12:33:17 [main] INFO WindowsCloser - File has been opened in a new window, let's close 1 new windows
2024-09-06 12:33:17 [main] INFO WindowsCloser -   Let's close 503784C53CDD8CC713B7A6DCDDCE62FC
2024-09-06 12:33:37 [main] WARN WindowsCloser -   Failed to close 503784C53CDD8CC713B7A6DCDDCE62FC
org.openqa.selenium.WebDriverException: unknown error: failed to close window in 20 seconds
  (Session info: MicrosoftEdge=128.0.2739.63)
Build info: version: '4.24.0', revision: '748ffc9bc3'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [a216be72f94832e2814becf4caf40d43, close {}]
Capabilities {acceptInsecureCerts: true, browserName: MicrosoftEdge, browserVersion: 128.0.2739.63, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:57004}, msedge: {msedgedriverVersion: 128.0.2739.63 (6ff765a876b3..., userDataDir: <deleted>}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57004/devtoo..., se:cdpVersion: 128.0.2739.63, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
```

Also, if I add `.withAction(DownloadActions.clickAndConfirm())`, then I do not see the error in the browser, however, the error in the console about new window is still there.
<img width="356" alt="image" src="https://github.com/user-attachments/assets/18276e1c-1c7e-4303-a12f-ed58fdf25435">

**It work fine with Firefox.**

## Tell us about your environment
* **Selenide Version**: 7.4.3 (also reproducible in 6.17)
* **Edge Version**: 128.0.2739.63
* **Browser Driver Version**: 128.0.2739.63
* **OS Version**: Windows 11 23H2

**Comment by IlyaHarlamov** [comment]
In addition, is there a way to download a file, but don't wait for the download to finish and go on to validate elements on the page and only after few validations get the File object?
As far as I know, when the file downloads, Selenide creates a folder with random name for the downloaded file, but I couldn't find a reliable way to retrieve the path to the file, especially if tests are running in parallel.

**Comment by asolntsev** [comment]
> In addition, is there a way to download a file, but don't wait for the download to finish and go on to validate elements on the page and only after few validations get the File object? 

No, Selenide doesn't have such method. 
But WHY do you need it? Why don't you want the file, and then perform other checks?


> I couldn't find a reliable way to retrieve the path to the file, especially if tests are running in parallel.

You **don't need** to retrieve the path.
Method `download` returns the file. You don't need to find this file anymore. Just check this file. Like this:

```java
File report = $("#report").download();
assertThat(report.getName()).isEqualTo("report20240908.pdf");
```

**Comment by asolntsev** [comment]
@IlyaHarlamov I see this line in your logs:
> WebDriverException: unknown error: failed to close window in 20 seconds

Why 20 seconds?
I guess you set implicit timeout to 20 seconds.
Please don't do it. Selenide has its own waiting mechanism. No need for implicit timeout.

**Comment by IlyaHarlamov** [comment]
@asolntsev 
> No, Selenide doesn't have such method.
But WHY do you need it? Why don't you want the file, and then perform other checks?

When I download a file, an element appears on the page, and disappears after few seconds. So it is possible that it disappears before the file is downloaded, it makes impossible to validate it.

Although there is a workaround - a separate test can be created.
Or in the same test, after download(), I can trigger the download once again by just clicking on the element and validate the element. So this is not that critical.

> You don't need to retrieve the path.
Method download returns the file. You don't need to find this file anymore. Just check this file. Like this:

Yep, it is exactly what I am doing right now

Sorry, I didn't explain it correctly. I was thinking about my previous problem about element that appears and disappears. I was thinking to workaround it by performing the `click()` instead of the `download()`, then validate the element and then locate the file by path and perform the checks on the file.

> Why 20 seconds?
I guess you set implicit timeout to 20 seconds.
Please don't do it. Selenide has its own waiting mechanism. No need for implicit timeout.

Honestly saying, I have no idea where these 20 seconds are coming from, I am not setting the timeout anywhere other than as parameter in `download()`. I believe that selenide detects the new window after PDF download and tried to close it, I guess that Selenium retries to close the window for 20 seconds by default? Not sure. 


=============================
Finally, about the main issue,  I have now tried to download with `FileDownloadMode.CDP`, with Edge. It works, a bit slower, but works.
But I believe it should also work with `FileDownloadMode.FOLDER`

**Comment by asolntsev** [comment]
> it makes impossible to validate it.

Sorry, I didn't understand: to validate _what_?

**Comment by IlyaHarlamov** [comment]
@asolntsev 
The element which appears on the web page for few seconds when I download the file.

Let's say that when I download the file, one element appears and is visible for 5 seconds and I want to validate the text of the element.
If the download takes more than 5 seconds, the element already disappeared

**Comment by asolntsev** [comment]
@IlyaHarlamov Are you sure _you really need to test that element_?
Such a test might be unstable anyway. Sooner or later it may happen that it disappears before the test verifies it. 

P.S. If you insist, here is the way. You can verify anything right after the click in `withAction` method:

```java
    File downloadedFile = $("#report").download(
      using(FOLDER).withFilter(withExtension("pdf")).withAction((driver, link) -> {
          link.click();
          $("#the-disappearing-element").shouldHave(text("Catch me if you can"));
        }
      )
    );
```

**Comment by IlyaHarlamov** [comment]
@asolntsev Ahh I see, should have figured this out... thank you!
 I would be really happy not to, but yes, unfortunately I have to 😄

**Comment by IlyaHarlamov** [comment]
Thank you for the fix! 🙂
