### ISSUE TITLE
selectOptionByValue does not trigger onChange event

### ISSUE THREAD

**Issue by fabb** [selenide/selenide#2847]
## The problem
I use `selectOptionByValue` to change the value of a `<select>` in my react app.

## Details
My `<select>` is a managed react component, so I need the `onChange` handler to be fired to really change the value. When calling `selectOptionByValue`, the selected value in the browser changes, but the `onChange` handler is not fired, so my application does not recognize that the value has been changed.

The `onChange` handler used to fire correctly in a previous version a few months ago.

Setting `Configuration.fastSetValue = false` does _not_ fix the issue.

The `selectOption` method has the same issue.

My current workaround is to trigger the `change` event manually after calling `selectOptionByValue`:
```
Selenide.executeJavaScript("arguments[0].dispatchEvent(new Event('change', { bubbles: true }))", $(byTestId("my-select")));
```

## Tell us about your environment
* **Selenide Version**: 7.4.3
* **Chrome Version**: 128.0.6613.138
* **Selenium Version**: 4.24.0
* **OS Version**: macOS Sonoma 14.6.1

**Comment by asolntsev** [comment]
@fabb Thank you for reporting.

I think this problem was already described here: https://github.com/selenide/selenide/issues/2832
And fixed here: https://github.com/selenide/selenide/pull/2835

Will be released soon as Selenide 7.5.0
