### ISSUE TITLE
Selenide + BrowserUpProxy + PAC File + RemoteWebDriver problem

### ISSUE THREAD

**Issue by tronstone** [selenide/selenide#2864]
## The problem
I'm trying to use a proxy server built into Selenide to intercept traffic and analyze response codes. But there is a problem that this requires auto-configuration of the proxy using the PAC file. In numerous attempts, I have not been able to successfully get the data to appear in Har. That is, the proxy is up, but entries in Har are empty. I set the file using setProxyAutoconfigUrl(). It's also running on the Selenoid.

## Tell us about your environment
* **Selenide Version**: 6.19.1
* **Firefox**: 115.9
* **Browser Driver Version**: RemoteWebDriver, autodowloaded from Selenide WDM

## Code To Reproduce Issue
`

        Configuration.remote = "remote_url";
        Configuration.browser = "firefox:;
        Configuration.proxyEnabled = true;
        Configuration.browserCapabilities.setCapability(
                CapabilityType.PROXY,
                new Proxy().setProxyAutoconfigUrl(webDriverProperties.getProxyAutoconfigURL())
        );

       // Was also
       BrowserUpProxy proxy = new BrowserUpProxyServer();
        proxy.start();

        Proxy seleniumProxy = ClientUtil.createSeleniumProxy(proxy);
        seleniumProxy.setProxyAutoconfigUrl(webDriverProperties.getProxyAutoconfigURL());

        FirefoxOptions firefoxOptions = new FirefoxOptions();
        firefoxOptions.setCapability(CapabilityType.PROXY, seleniumProxy);

        WebDriverRunner.setProxy(seleniumProxy);

       // And this
       FirefoxProfile profile = new FirefoxProfile();
        profile.setPreference("network.proxy.type", 2);  // 2 = PAC URL
        profile.setPreference("network.proxy.autoconfig_url", webDriverProperties.getProxyAutoconfigURL());

        FirefoxOptions firefoxOptions = new FirefoxOptions();
        firefoxOptions.setCapability(
                CapabilityType.PROXY,
                new Proxy().setProxyAutoconfigUrl(webDriverProperties.getProxyAutoconfigURL())
        );

        Configuration.browserCapabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, firefoxOptions);

       // And this
       FirefoxOptions firefoxOptions = new FirefoxOptions();
        firefoxOptions.addArguments("--proxy-pac-url=" + webDriverProperties.getProxyAutoconfigURL());

        Configuration.browserCapabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, firefoxOptions);
`

**Comment by BorisOsipov** [comment]
[BrowserUpProxy doesn't understand PAC](https://github.com/lightbody/browsermob-proxy/issues/659).

You have to parse PAC yourself then implement [SelenideProxyServerFactory ](https://github.com/selenide/selenide/blob/e8a306261f99173b04942eaade23618d42e54651/src/main/java/com/codeborne/selenide/proxy/SelenideProxyServerFactory.java#L17) and set `selenideProxyServer.getProxy().setChainedProxy("pac parsed proxy address");` before proxy starts. Also don't forget to add your SelenideProxyServerFactory implementation in service loader.
After that Selenide proxy can understand that there is upstream proxy from PAC file.

Even then you have to make sure that there is a direct network connection between the host where the tests (and the selenide proxy) are running and the selenoid host in both directions for all ports. Also requires network connection from selenide proxy and chained proxy address.
