### ISSUE TITLE
Incorrect description or behaviour of `Selenide#screenshot(java.lang.String)` function

### ISSUE THREAD

**Issue by nektonick** [selenide/selenide#2896]
## The problem
Descriptions of [this function](https://github.com/selenide/selenide/blob/b4f57d1f9a4ff85b799b616c787bef49b7f761fc/statics/src/main/java/com/codeborne/selenide/Selenide.java#L275) says: 

> Take the screenshot of current page and save to file fileName.html and fileName.png.

However, I found, that fileName.html file will not be created after function call.

## Details
I check implementation details and found, that `Selenide#screenshot(java.lang.String)` calls `SelenideDriver#screenshot(java.lang.String)` which calls `takeScreenshot` with parameter `savePageSource=false`, so html file will not be saved (even if `Configuration#savePageSource` is true).

Is the problem with function description, function implementation, or both?

## Tell us about your environment
* **Selenide Version**: main branch or v7.5.1 tag

**Comment by asolntsev** [comment]
@nektonick Yes, seems that the javadoc and real behaviour don't match. :) 

The change was introduced in commit [48dae56e](https://github.com/selenide/selenide/commit/48dae56e). Before it, `takeScreenshot(driver, fileName, true, true)` was called. 
It's hard to say if it was intentional, but let's fix one of them. 

So, what option is better: `true, false` or `true, true`?

**Comment by nektonick** [comment]
@asolntsev Is it a good idea to get the value of the second parameter from Configuration? 
It seems to me that `Configuration#savePageSource` should be responsible for that behavior.

**Comment by asolntsev** [comment]
I am not sure.

`Configuration.savePageSource` and `Configuration.screenshots` are used when Selenide automatically takes a screenshot in case of test failure.

But when the user explicitly calls method `takeScreenshot()`, he obviously wants the screenshot, even if `Configuration.screenshots == false`. At least it was intention of commit [c6eba7cb](https://github.com/selenide/selenide/commit/c6eba7cb)

**Comment by nektonick** [comment]
Ok, then, I think, we should update the description of the current function without changing its behavior.
Also, I would be happy to have another function that creates both png and html (something like `Screenshot screenshot(`String fileName, boolean saveScreenshot, boolean savePageSource)` parameters), since I can't find any function that saves page html in Selenide.java.

What do you think about it?

**Comment by asolntsev** [comment]
@nektonick I've updated javadoc and changed the behaviour.
Now it depends on `Configuration.savePageSource`.

See https://github.com/selenide/selenide/pull/2901/files

I just thought it was the simplest solution for the moment..

**Comment by asolntsev** [comment]
@nektonick The fix has been released in Selenide 7.6.0
