### ISSUE TITLE
Java 22 + Selenide 7.6: Cannot compile simple project, getting `cannot access com.browserup.bup.filters.RequestFilter`

### ISSUE THREAD

**Issue by jstefek** [selenide/selenide#2910]
## The problem
Cannot compile simple maven project, using just one dependecy for Selenide 7.6.0 and instantiating SelenideDriver with `null` proxy. Got exception:
```
java: cannot access com.browserup.bup.filters.RequestFilter
  class file for com.browserup.bup.filters.RequestFilter not found
```

Works with Selenide 7.5.1.

## Tell us about your environment
* **Selenide Version**: 7.6.0, 7.6.1
* **Browser + Driver Version**:  Chrome 131 + selenium manager downloaded chromedriver
* **OS Version**: Windows 11, intel cpu | MacOs Sonoma M2 cpu
* **Java** 22 temurin

## Code To Reproduce Issue
Simple maven project with a single dependency:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>selenide-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>7.6.0</version>
        </dependency>
    </dependencies>
</project>
```

And one class:
```
package org.example;

import com.codeborne.selenide.SelenideConfig;
import com.codeborne.selenide.SelenideDriver;
import org.openqa.selenium.chrome.ChromeDriver;


public class Main {
    public static void main(String[] args) {
        new SelenideDriver(new SelenideConfig(), new ChromeDriver(), null);
    }
}
```

When trying to compile with `mvn clean compile`, I get:
```
java: cannot access com.browserup.bup.filters.RequestFilter
  class file for com.browserup.bup.filters.RequestFilter not found
```

dependency tree using `mvn dependency:tree`:
```
[INFO] org.example:selenide-test:jar:1.0-SNAPSHOT
[INFO] \- com.codeborne:selenide:jar:7.6.0:compile
[INFO]    +- org.seleniumhq.selenium:selenium-java:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-api:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.26.0:compile
[INFO]    |  |  +- com.google.auto.service:auto-service-annotations:jar:1.1.1:compile
[INFO]    |  |  +- org.seleniumhq.selenium:selenium-chromium-driver:jar:4.26.0:compile
[INFO]    |  |  +- org.seleniumhq.selenium:selenium-json:jar:4.26.0:compile
[INFO]    |  |  \- org.seleniumhq.selenium:selenium-manager:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-devtools-v128:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-devtools-v129:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-devtools-v130:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-devtools-v85:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:4.26.0:compile
[INFO]    |  |  \- org.seleniumhq.selenium:selenium-http:jar:4.26.0:compile
[INFO]    |  |     \- dev.failsafe:failsafe:jar:3.3.2:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:4.26.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-remote-driver:jar:4.26.0:compile
[INFO]    |  |  +- io.opentelemetry.semconv:opentelemetry-semconv:jar:1.25.0-alpha:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-api:jar:1.43.0:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-context:jar:1.43.0:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-exporter-logging:jar:1.43.0:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-sdk-common:jar:1.43.0:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:jar:1.43.0:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:jar:1.43.0:compile
[INFO]    |  |  |  \- io.opentelemetry:opentelemetry-api-incubator:jar:1.43.0-alpha:runtime
[INFO]    |  |  +- io.opentelemetry:opentelemetry-sdk-trace:jar:1.43.0:compile
[INFO]    |  |  +- io.opentelemetry:opentelemetry-sdk:jar:1.43.0:compile
[INFO]    |  |  |  +- io.opentelemetry:opentelemetry-sdk-metrics:jar:1.43.0:compile
[INFO]    |  |  |  \- io.opentelemetry:opentelemetry-sdk-logs:jar:1.43.0:compile
[INFO]    |  |  +- net.bytebuddy:byte-buddy:jar:1.15.7:compile
[INFO]    |  |  \- org.seleniumhq.selenium:selenium-os:jar:4.26.0:compile
[INFO]    |  |     \- org.apache.commons:commons-exec:jar:1.4.0:compile
[INFO]    |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:4.26.0:compile
[INFO]    |  \- org.seleniumhq.selenium:selenium-support:jar:4.26.0:compile
[INFO]    +- org.slf4j:slf4j-api:jar:2.0.16:compile
[INFO]    +- com.codeborne:selenide-core:jar:7.6.0:compile
[INFO]    |  +- org.opentest4j:opentest4j:jar:1.3.0:compile
[INFO]    |  \- org.apache.httpcomponents.client5:httpclient5:jar:5.4.1:runtime
[INFO]    |     +- org.apache.httpcomponents.core5:httpcore5:jar:5.3.1:runtime
[INFO]    |     \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.3.1:runtime
[INFO]    +- org.jspecify:jspecify:jar:1.0.0:compile
[INFO]    +- com.google.errorprone:error_prone_annotations:jar:2.36.0:compile
[INFO]    +- com.google.guava:guava:jar:33.3.1-jre:compile
[INFO]    |  +- com.google.guava:failureaccess:jar:1.0.2:compile
[INFO]    |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]    |  +- org.checkerframework:checker-qual:jar:3.43.0:compile
[INFO]    |  \- com.google.j2objc:j2objc-annotations:jar:3.0.0:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.17.0:runtime
[INFO]    \- commons-io:commons-io:jar:2.18.0:runtime
```

Notes:
* works, when I use Java 21
* works, when you just use `new SelenideDriver(new SelenideConfig());`.

**Comment by asolntsev** [comment]
@jstefek Sorry, but I cannot reproduce the problem.
The line `new SelenideDriver(new SelenideConfig(), new ChromeDriver(), null);` is executed on my machine without errors.

Please run `mvn dependency:tree`.
Or maybe you could create a sample project to reproduce the issue?

**Comment by jstefek** [comment]
updated the ticket

**Comment by jstefek** [comment]
also does not work in java 23

**Comment by asolntsev** [comment]
@jstefek Thanks, now I could reproduce the problem. Should be fixed by PR https://github.com/selenide/selenide/pull/2912

**Comment by ansonliao** [comment]
Hi @asolntsev , 
I meet this issue as well, my `selenide` version is `7.10.0`, please check the screenshot below, could you kindly help to advise?
Thanks.

<img width="889" height="186" alt="Image" src="https://github.com/user-attachments/assets/49822a39-f70c-42a7-8645-844b466af175" />

**Comment by asolntsev** [comment]
@ansonliao Are you sure you added dependency `com.codeborne:selenide-proxy:7.10.0` to your project (instead of `com.codeborne:selenide:7.10.0`)?

**Comment by ansonliao** [comment]
> [@ansonliao](https://github.com/ansonliao) Are you sure you added dependency `com.codeborne:selenide-proxy:7.10.0` to your project (instead of `com.codeborne:selenide:7.10.0`)?

Thanks for your reply @asolntsev , I don't touch `selenide` recently, so no knowledge for the recent `Selenide`, I just added the `selenide-proxy` dependency, it the error is gone.
Thanks for your great help.
Could you mind to provide some whole code sample on the mock/proxy?
I checked some documents, but it scattered, so far I can't make the mock/proxy run.
Thanks.

**Comment by asolntsev** [comment]
https://selenide.org/2022/10/07/selenide-6.9.0/#proxy-mock-response

https://selenide.org/2024/04/28/selenide-7.3.1/#mock-specific-content-type

**Comment by ansonliao** [comment]
Hi @asolntsev ， thanks for your reply.
I read these documents before I write the code, unfortunately I meet some errors as well, my network traffice interception code snippet as below,
```java
var mockResponse = """
		{
		    "items": [],
		    "page": 1,
		    "hasMore": false
		  }
	""";

Configuration.proxyEnabled = true;
getSelenideProxy().responseMocker().mockText("mock-no-datda", urlContains(GET, "/v5/api/products"), 200,
													 () -> mockResponse);
```

When executing, it will be error and the message is
```shell
config.proxyEnabled == true but proxy server is not created.
```

<img width="1295" height="216" alt="Image" src="https://github.com/user-attachments/assets/c23749de-9c03-4474-9bf3-dd955e7b4028" />

I checked some sample codes from here: https://github.com/selenide/selenide/tree/b891541636845122ad6c446a478d41b1d72e9a8f/modules/proxy/src/test/java/integration/proxy
but it doen't have a direct method that how to create a proxy server.

Could you kindly help to advise?

Thanks.

> https://selenide.org/2022/10/07/selenide-6.9.0/#proxy-mock-response
> 
> https://selenide.org/2024/04/28/selenide-7.3.1/#mock-specific-content-type

**Comment by asolntsev** [comment]
You just need to call `Configuration.proxyEnabled = true;` BEFORE you open the browser. @ansonliao

**Comment by ansonliao** [comment]
> You just need to call `Configuration.proxyEnabled = true;` BEFORE you open the browser. [@ansonliao](https://github.com/ansonliao)

Thanks for your reply, it works fine now.

**Comment by asolntsev** [comment]
@ansonliao Thank you for the update.

I've added a notice to the error message, now it will look like this:
> config.proxyEnabled == true but proxy server is not created. Be sure to enable proxy BEFORE you open the browser.
