### ISSUE TITLE
Please update documentation for reporting

### ISSUE THREAD

**Issue by AndriiYushkov** [selenide/selenide#2914]
## The problem
[Documentation about integration with allure report](https://selenide.org/documentation/reports.html#allure-report) not full, and need to be updated. Need to extend it for different combination of technologies. In case when used Cucumber 7 with allure and Junit 5 - everything working according to current documentation. At the same time when we change test-runner to TestNG - Allure Selenide stop working at all. 

## Details
After several days investigation we found that
SelenideLooger add listener called from @BeforeAll cucumber static method not initialize allure listener. 
Steps to reproduce:
1. Initialize [SimpleReport](https://github.com/selenide/selenide/blob/main/src/main/java/com/codeborne/selenide/logevents/SimpleReport.java) class in @BeforeAll and call start() method
2. Object of SimpleReport class stored as static variable of cucumber step definition class
3. At least 1 cucumber test for web should run
4. Call stop() method in @After cucumber method (not static).
Expected result:
Console log have generated text report.
Actual result:
Warning message displayed: Can not publish report because Selenide logger has not started.

To fix this issue need to move SimpleReport initialization call and start() method from @BeforeAll cucumber static method to @Before cucumber method (not static). SimpleReport object stored as not static field in step defenition cucumber class After that console log had generated test report.
Same approach for Allure Report.
Line of code: SelenideLogger.addListener("AllureSelenide", new AllureSelenide());
should be placed in @Before cucumber not static method.

If this is a bug please fix it, If its a feature - it should be documented.

## Tell us about your environment
* **Selenide Version**: 7.6.0
* **Chrome Version**: 131.0.6778.109 (Official Build) (64-bit)
* **TestNG Version**: 7.10.2
* **Allure Version**: 2.29.0
* **Cucumber Version**: 7.20.1
* **OS Version**: Windows 11

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
Hi @AndriiYushkov 

I've added a warning to the above mentioned [documentation](https://selenide.org/documentation/reports.html#allure-report). Also, I've added debug logs to `SelenideLogger`. 

But I don't think we have to describe all possible frameworks and corner cases in Selenide documentation. There is a lot of technologies, all they can have different unexpected nuances. I rather suggest enabling debug logs and applying other debugging techniques.

Maybe it helps:
* [How to debug autotests](https://www.youtube.com/watch?v=-TvVCxmb9ss&ab_channel=EpicHey%21Conference)
* [Как дебажить автотесты](https://www.youtube.com/watch?v=4Kh5yppP8zY&ab_channel=DEVCLUB.EU)
