### ISSUE TITLE
Proxy request filter not working for localhost

### ISSUE THREAD

**Issue by Daniel-F-Garcia** [selenide/selenide#2916]
## The problem

I added a request filter to log all requests.
It works for requests to external sources but not localhost.

## Details

in my test I setup the filter

```
Configuration.proxyEnabled = true;
open();

SelenideProxyServer proxy = getSelenideProxy();
proxy.addRequestFilter("request-logger", new RequestFilter() {
  @Override
  public HttpResponse filterRequest(HttpRequest request, HttpMessageContents contents, HttpMessageInfo messageInfo) {
    log.info("{} {}", request.method(), request.uri());
    return null;
  }
});
```

My tests run against http://localhost:9000
I open a page (html, css, js etc), click a button which triggers an ajax request (to an endpoint served by http://localhost:9000)
I would expect log entries for html page, associated css, js etc and ajax endpoint 

I tried both Firefox and Edge and get the same results. 
Both browsers make their own external calls, which I get logging for.

In my JavaScript, where I make the AJAX call I made the following changes:
* change URL to https external address (https://www.google.com/) - I get logging
* change URL to http external address (http://www.bom.gov.au/) - I get logging
* change URL to http://127.0.0.1:9000/path/to/endpoint - I don't get any logging

## Tell us about your environment
* **Selenide Version**: 7.6.1
* **Edge Version**: 129.0.2792.52
* **Firefox Version**: 128.3.1esr
* **Selenium Version**: 4.27.0
* **OS Version**: Windows 10.0.19045

**Comment by Daniel-F-Garcia** [comment]
workaround is to set baseURL to  `format("http://{0}:9000", InetAddress.getLocalHost().getHostAddress());` or explicitly open pages based on that baseURL.

**Comment by asolntsev** [comment]
Hi @Daniel-F-Garcia 

Sorry, but I cannot reproduce the problem. I coped your code _and added open("http://localhost:9000")_ after it, and it runs well. Request to "http://localhost:9000" gets intercepted and logged.

**Comment by asolntsev** [comment]
Feel free to reopen the issue if we get more information.
