### ISSUE TITLE
Switching to a window with a configurable timeout

### ISSUE THREAD

**Issue by kenston** [selenide/selenide#399]
In `com.codeborne.selenide.SelenideTargetLocator.window(int)`:

``` java
  public WebDriver window(int index) {
    try {
      return Wait().until(windowToBeAvailableAndSwitchToIt(index));
    }
    catch (TimeoutException e) {
      throw wrapThrowable(e, timeout);
    }
  }
```

The `Wait()` used relied on the `timeout` configuration. Is it possible for us to have a configurable timeout similar to `SelenideElement.waitUntil(Condition condition, long timeoutMilliseconds)`? 

I have some pop-up windows that may open after a period that is longer than the configured `timeout`. It would not be good to increase the `timeout` value just to cover these cases.

**Comment by asolntsev** [comment]
@kenston Generally, it's not a bad idea to increase the `timeout`. It doesn't affect tests execution time (unless you have a lot-lot-lot of failing tests). 

But yes, we could create additional methods like
* `switchTo().window(2, 8000);`    or
* `in(8000, ms).switchTo().window(2);`    or
* `in("8s").switchTo().window(2);`    or
* `switchTo(withTimeout(8000)).window(2);`

What you suggest?

**Comment by kenston** [comment]
@asolntsev `switchTo(withTimeout(8000)).window(2);` is simple and sufficient. `in(8000, ms).switchTo().window(2);` or `in("8s").switchTo().window(2);` look interesting if it's going to configure any default `Wait()` (covering even `Selenide.dismiss(...)` and other future cases). Will `in(8000, ms)` return `Selenide`?

**Comment by asolntsev** [comment]
@kenston I don't know yet what it should return. That's the question. I am afraid this feature will require a bigger refactoring. But no doubt, we still need to do it.

**Comment by symonk** [comment]
@asolntsev @kenston thoughts on:

```java
switchTo().window(index, timeout); 
switchTo().window(nameOrHandleOrTitle, timeout);
```

We can overload the TargetSelector window methods for index/title/handle etc ?

**Comment by asolntsev** [comment]
@symonk Agree. Just one more suggestion: let set `timeout` type to `java.time.Duration`, not `long`. 
Then users can use it like this:

```java
switchTo().window(2, Duration.ofSeconds(15)); 
switchTo().window("some title", Duration.ofMilliseconds(8888));
```

**Comment by symonk** [comment]
I will take this one, starting soon

**Comment by jlentink** [comment]
@symonk Any news on this?

**Comment by asolntsev** [comment]
@kenston @symonk @jlentink Done in Selenide 5.7.0, see https://github.com/selenide/selenide/pull/1054

**Comment by donesvad** [comment]
hey @asolntsev 
could you also add the same method with custom duration for the frame? 
something like `switchTo().frame("contentFrame", Duration.ofSeconds(15)); `

**Comment by donesvad** [comment]
https://github.com/selenide/selenide/pull/1722
here are some proposed changes with `switchTo().frame()` with custom duration
