### ISSUE TITLE
Showing evaluation result in LogEvent

### ISSUE THREAD

**Issue by kenston** [selenide/selenide#420]
The condition `$("#msg").isDisplayed();` will produce a `LogEvent` with `getElement()` = `#msg`, `getSubject()` = `is displayed()`, and `getStatus()` = `PASS`.

Is it possible for us to distinguish the result of the condition evaluation in `LogEvent`?

In the example above, a method like `getResult()` may return `true` if `#msg` is indeed displayed; otherwise, it returns `false`. The datatype for the method can be `String` so we can return other results (e.g., for `.val()`).

**Comment by asolntsev** [comment]
@kenston Hi! 
Sorry, but I don't understand what do you want to achieve. Do you want to create more details report?

**Comment by kenston** [comment]
Hi @asolntsev 

Yes, I want to create a more detailed log of the browser interactions made. The `subject` value of `is displayed()` is interpreted as "a call was made to check if element was displayed", but we don't know whether it evaluated to true or was displayed or not.

**Comment by asolntsev** [comment]
@kenston Hi. Sorry for the long delay. Now I am trying to cleanup the backlog. :)

1. Output of `$.isDisplayed()` is always short: "true" or "false". But how can we log result of some other methods (like `$.getText()`) that can be very, very long? 
2. I believe that the only method of `SelenideElement` that should be used in tests is "should*" methods: `$.shouldBe(visible)`. In good tests, we should not use methods like `$("#msg").isDisplayed()` or `$("#msg").getText()`. Method `$.isDisplayed()` can only be useful in `if`, but `if` in test is a bad practice, right?

**Comment by kenston** [comment]
@asolntsev, Ok, got it. The need is no longer there, but thanks for revisiting the ticket.
