### ISSUE TITLE
Problems with usage Sizzle on some pages

### ISSUE THREAD

**Issue by juliaviluhina** [selenide/selenide#434]
Error "Sizzle is not defined" appears on some pages 

For example
http://todomvc.com/examples/dojo/
http://todomvc4tasj.herokuapp.com/
http://todomvc.com/examples/troopjs_require/

If injecting Sizzle provides through "window.Sizzle = Sizzle;" (in https://github.com/codeborne/selenide/blob/master/src/main/resources/sizzle.js)
Sizzle will be loaded successfully on described pages  (I checked it)

As I understood, on this pages Sizzle injects through the
if ( typeof define === "function" && define.amd ) {
	define(function() { return Sizzle; });
But this approach doesn't work correctly on described pages

Also, I checked Sizzle usage on several another pages - Sizzle usage works correctly, described problems do not appear.

In my opinion, Sizzle usage in Selenide does not have high priority. However, this feature is declared and should work correctly )

**Comment by asolntsev** [comment]
@juliaviluhina I would say that it's rather a bug in Sizzle: it doesn't work on pages like http://todomvc.com/examples/dojo/ that use Dojo, not JQuery. 

But it seems that I found a workaround in Sizzle.js
Going to prepare a pull request.

**Comment by juliaviluhina** [comment]
Thank you @asolntsev 
I really appreciate your efforts and I think Selenide is great tool 👍
