### ISSUE TITLE
add customisable "before all actions" hooks

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#447]
Use case:
- simulate "protractor" when waitForAngualr() helper is called for all actions.
- slow down all actions for "demo" reasons

With this feature Selenide will become suitable for automation of Angular applications, and probably applications based on some other similar js frameworks.

Currently the workaround for Selenide to test Angular applications is the following: https://github.com/automician/snippets/tree/master/java/widgetsapproach/src/main/java/com/automician/core/angular

**Comment by vkondin** [comment]
_simulate "protractor" when waitForAngualr() helper is called for all actions._
Hi!
Why dont you want to use $("some selector").waitUntil() instead?

**Comment by rmarinsky** [comment]
@vkondin because you need to use allot of waitUntil and more over, you have to customize each of waitUntil. Any angular element have uniq data-attribute. And using special waiting before all actions it's simpler

**Comment by ddemin** [comment]
@yashaka , @rmarinsky , @asolntsev 
https://github.com/codeborne/selenide/pull/324
point №3

But that solution isn't elegant yet =)

**Comment by yashaka** [comment]
@ddemin 
what solution is not elegant? :)

Your #324 is imho not relevant to selenide at all. By - are classic selenium selectors. All "waiting logic" of Selenide is implemented in SelenideElement, so it was bad idea to put it into By. 

@vkondin 
Selenide way is "easy not bothering about waits", and what you have proposed - is explicit wait with which you should bother all the time. 

Of course there also should be some way to add "custom implicit" waits per element, like @ddemin proposed (if I understood him correctly), but that should be implemented in SelenideElement, not in By.

**Comment by ddemin** [comment]
I think hook can be called inside Commands#execute method. And it can be stored inside Configuration class.
What do you think ?

````
public <T> T execute(Object proxy, WebElementSource webElementSource, String methodName, Object[] args) 
      throws IOException {
    Command command = commands.get(methodName);
    if (command == null) {
      throw new IllegalArgumentException("Unknown Selenide method: " + methodName);
    }    
    Configuration.beforeAnyCommandHook.run();
    return (T) command.execute((SelenideElement) proxy, webElementSource, args);
  }

**Comment by yashaka** [comment]
From first look,  it seems reasonable...

we can also wait, what @asolntsev thinks:-)

**Comment by rmarinsky** [comment]
Just implement WebDriverEventListener interface from selenium, and put 'waiters' to before methods, such as:
`beforeFindBy`, `beforeClickOn`, `beforeChangeValueOf`
So, I think in selenide, it doesn't need to be developed

**Comment by rosolko** [comment]
Looks like this not an issue or reasonable improvement.
Fell free to reopen if have prepared PR with implementation.
