### ISSUE TITLE
Support for HOCON

### ISSUE THREAD

**Issue by fancywriter** [selenide/selenide#462]
Would be great to support configuration with HOCON https://github.com/typesafehub/config
Instead of (or in addition to) system properties https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/Configuration.java

**Comment by asolntsev** [comment]
@fancywriter Yes, probably it's a good idea.
Feel free to implement a pull request for this integration! :)

**Comment by fancywriter** [comment]
@asolntsev IDEA code analyser says to me that **openBrowserTimeoutMs** is not used - is it planned to be used in future?

**Comment by asolntsev** [comment]
@fancywriter Yes, `openBrowserTimeoutMs` is not used anymore. We should remove it. 
There is also a similar setting `closeBrowserTimeoutMs` which also could be removed (hm... actually it's used, but probably we should simplify that code and remove the setting).

**Comment by fancywriter** [comment]
@asolntsev please take a look at this draft https://github.com/fancywriter/selenide/commit/97241dddee791d2a5e736d11d11dc484e6a12863 and say if it's OK. It's not ready yet, I don't have enough free time today - will take as soon as possible to finish. :)

**reference.conf** is used to store default values of all properties. One issue is that design of this library doesn't allow empty/null/missing values - we need to always specify properties which are used - in fact it's good thing, helps avoid NPE errors. I found few values which can be null - will think better how to resolve them later.

Values can be overriden either with java system properties as before or also with **application.conf** in classpath

**Comment by rosolko** [comment]
Starting from 5.0.0 version you can implement `com.codeborne.selenide.Config` interface and pass custom config
