### ISSUE TITLE
Condition or("condition-name", condition1, condition2) output is misleading if it fails.

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#469]
if `$("#id").shouldBe(or("condition-name", hidden, text("disabled")))` fails,

it outputs only as if it had only first condition:

Element should be hidden {#id}
.....

But logically it should be
Element should be hidden {#id} or have text "disabled" {#id} ...

---------
It's the same for and() - but it is okay in this case, because for the first failing condition should stop the evaluating.

**Comment by asolntsev** [comment]
Fixed in Selenide 5.3.0 by https://github.com/selenide/selenide/pull/962
