### ISSUE TITLE
Add possibility to use SelenideProxyServer for users who create their own webdriver

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#542]
By default, Selenide creates its own webdriver and starts its own proxy server for downloading files (if `Configuration.fileDownload = PROXY`). 

But some users create their own instance of webdriver (using `WebDriverProvider` or `WebDriverRunner.setWebDriver()`). Those users cannot use `Configuration.fileDownload = PROXY` because Selenide doesn't start its proxy server in this case.

We need to allow those users to start `SelenideProxyServer` and use for their own webdriver creation.

**Comment by VitMS** [comment]
It will be great if such ability has been implemented. 
It's very actual for me.

**Comment by VitMS** [comment]
The test where I used the `Configuration.fileDownload = PROXY` setting fails now on the WeBDriver starting, but 1-2 weeks ago was passed.
Occured Exception:
_...
org.openqa.selenium.WebDriverException: Unable to convert: Capabilities [{proxy=Proxy(manual, http=PC:61354, ssl=PC:61354), acceptSslCerts=true, pageLoadStrategy=normal, chromeOptions=org.openqa.selenium.chrome.ChromeOptions@6501f5a7}]
..._

It is worth noting - in the case if `Configuration.fileDownload = GETHTTP` - the browser starts successfully.
Chrome driver version is 2.29.
Chrome browser version is _BrowserName=chrome Version=58.0.3029.110_
I created a simple test:
public class Temp {
    @Test
    public void testName() throws Exception {
        Configuration.browser = "chrome";
        Configuration.fileDownload = Configuration.FileDownloadMode.PROXY;
        System.setProperty( "webdriver.chrome.driver", "<path_to_driver>\\chromedriver.exe" );
        Selenide.open( "<AUT_URL>" );
    }
}
Its behaviour is the same.

Are there any ideas what is happening?

**Comment by asolntsev** [comment]
@VitMS Unfortunately I don't enough information to be able to help you. :(
Can you create a sample project that would reproduce your problem? Your code sample works fine for me.

**Comment by VitMS** [comment]
@asolntsev Hi,
I was busy on other projects. The mentioned expection (WebDriverException: Unable to convert) is not actual any more.
Can we try to implement this possibility? 
Now I have to save downloaded files, but can't because of I'm using a custom WebDriver.

**Comment by asolntsev** [comment]
@VitMS Yes, I plan to implement this feature. Hopefully in a next Selenide release.

**Comment by asolntsev** [comment]
Closing the issue. The feature was implemented almost a year ago.
Code samples are here:
1. [`WebdriverRunner.setWebDriver()` case](https://github.com/selenide/selenide/blob/master/statics/src/test/java/integration/CustomWebdriverWithSelenideProxyTest.java)
2. [`WebdriverProvider` case](https://github.com/selenide/selenide/blob/master/statics/src/test/java/integration/CustomWebdriverProviderWithSelenideProxyTest.java)
