### ISSUE TITLE
how can i closed window not quit Browser not closed webdriver

### ISSUE THREAD

**Issue by zhupengfarmer** [selenide/selenide#567]
selenium have driver.close  and driver.quit

selenide.close=diver.quit

if i have many  windows ,need webdriverrunner.getwebdriver.close.
even need Selenide.switchTo().window()  to  keep  do not quit webdriver.

can selenide.closeWindow(1);
selenide.closeOtherWindows;
like this  cooooool function

**Comment by asolntsev** [comment]
@zhupengfarmer Currently you can call `getWebdriver().close()` - which is not too long. Good enough for me. 

Well, in pure Selenium, you also need to first switch to the window and only then call `webdriver.close()`. Selenide doesn't make it any worse. 

P.S. Yes, it was a bad idea to use "selenide.close=diver.quit". But it was a long time ago, we were young and didn't read documentation. Now it's quite impossible to change it. :)

**Comment by zhupengfarmer** [comment]
it's cool
