### ISSUE TITLE
getWebDriverLogs(LogType.PERFORMANCE, Level.ALL) doesn't work 

### ISSUE THREAD

**Issue by Metaun** [selenide/selenide#586]
If we send LogType.PERFORMANCE in method we get  an error 
```
org.openqa.selenium.WebDriverException: unknown error: log type 'performance' not found
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 4.4.0-92-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
```
It works correct with other types and if I use the standard way for getting this log (without selenide) it works to. 

Selenide version: 4.5

**Comment by BorisOsipov** [comment]
Hi @Metaun 

I haven't tried getting performance log, but it looks interesting.

Btw have you set up chrome capabilities as it described in https://sites.google.com/a/chromium.org/chromedriver/logging/performance-log to enable such log colletion?

**Comment by rosolko** [comment]
@Metaun Ping, can you please answer question if you already try apply provided chrome capabilities?

**Comment by rosolko** [comment]
No response from author. Obsolete.
