### ISSUE TITLE
Selenide throws ElementNotFound exception on not related  WebDriverException e.g. element is not clickable

### ISSUE THREAD

**Issue by BorisOsipov** [selenide/selenide#607]
Guy from slack chat ran into issue. 
When he tried to click to the element he got ElementNotFound exception BUT element exists on the page

> com.codeborne.selenide.ex.ElementNotFound: 
> Element not found {By.linkText: Выбрать контрагента}
> Expected: exist
>         at ru.BlrwblTest.createBlrwbl(BlrwblTest.java:43)
> Caused by: org.openqa.selenium.WebDriverException: 
> unknown error: Element <a href="#" class="but" style="margin: 0 0 -5px;" onclick="return loadRefData('recipient')">...</a> is not clickable at point (1195, 32). Other element would receive the click: <div class="b-head-top unselectable">...</div>

It is not ok. Need fix this and research other possible cases

**Comment by robben1234** [comment]
I've updated Selenide recently from older version and today saw similar problem.

`Element not found {By.xpath: //input[@id='permission_admin_manage_colors']/..}
Expected: exist
        ...
Caused by: WebDriverException: unknown error: Element is not clickable at point (1055, 1820)
	...
Caused by: org.openqa.selenium.WebDriverException: unknown error: Element is not clickable at point (1055, 1820)
  (Session info: chrome=61.0.3163.100)`

For HTML:

`<div class="checker">
<span>
<input id="permission_admin_manage_colors" type="checkbox" class="uniform ng-pristine ng-valid">
</span>
</div>`

And for select:

`span.hover().click();`

In Chrome page didn't scrolled down to element, left stood on header and so element was not clickable. Tried without hover and waiting for element be visible - all had the same trace.

**Comment by BorisOsipov** [comment]
@robben1234 have you tried to update chromedriver to the latest version? Try it. It may help you.

**Comment by robben1234** [comment]
@BorisOsipov yeah, seems that it was the issue for me. Thanks for your help.

**Comment by simple-elf** [comment]
@BorisOsipov I faced the same issue. Unfortunately this bug goes to Selenium itself. Because there is `Caused by: org.openqa.selenium.WebDriverException:
unknown error:`

**Comment by BorisOsipov** [comment]
@simple-elf yep.
But problem that Selenide says "Element not found" in such a case - it's wrong.

**Comment by simple-elf** [comment]
```
    else if (lastError instanceof WebDriverException) {
      if (lastError.getMessage().contains("is not clickable at point"))
        throw new UIAssertionError(lastError.getMessage().replace("unknown error: ", "").split("\n")[0], lastError);
      else
        throw webElementSource.createElementNotFoundError(exist, lastError);
    }
```
There is an example, how we can throw different exception. But here we need new exception class - ElementNotClickable

**Comment by jpratt2** [comment]
If this is happening in Chrome with the error "element not clickable" I found this solution: 

```
    public void click(WebElement element) {
        js.executeScript("arguments[0].click();", element);
        //this alternate click method can fix the Chrome driver issue "Element is not clickable"
        //https://stackoverflow.com/questions/11908249/debugging-element-is-not-clickable-at-point-error
    }
```

**Comment by asolntsev** [comment]
@jpratt2 Thank you. Actually you can enable this mode with this setting: `Configuration.clickViaJs = true;`

**Comment by jpratt2** [comment]
Or how about extending .click with a try catch?
Something like
```
try {
      element.click();
    }catch(Exception ex){
      executeJavaScript("arguments[0].click();",element);//sometimes Chrome requires this for the "element not clickable" error
    }
```

**Comment by jpratt2** [comment]
Something to consider
```
try {
      element.click();
    }catch(Exception ex){
      executeJavaScript("arguments[0].click();",element);
    }
```

**Comment by rosolko** [comment]
@jpratt2 As write before - to click via JS just pass configuration parameter.
It calls method:
```
protected void click(WebElement element) {
    if (clickViaJs) {
      executeJavaScript("arguments[0].click()", element);
    }
    else {
      element.click();
    }
  }
``
Solution that you provide bad, because if exception will thrown for click method - you can't handle it, and represent for user. Same for catch block. What if something goes wrong inside JS executor.

**Comment by BorisOsipov** [comment]
>agreed; l think this ticket can be marked complete.

nope. it still should be fixed in selenide.

**Comment by BorisOsipov** [comment]
@simple-elf yes it is.
