### ISSUE TITLE
ElementsCollection#first(int) & last(int) methods to get specified number of collection elements

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#623]
Sometimes at some applications where we can't control/seed the database, we have to create new objects in a list and check them only in the head or in the tail of the list, not the full list. 

GIVEN
```java
$$(“.item”).shouldHave(texts(“a”, “b”, “c”, “d”, “e”, “f”));
```

THEN the following methods would be helpful:

```java
$$(“.item”).first(3).shouldHave(texts(“a”, “b”, “c”));
$$(“.item”).last(3).shouldHave(texts(“d”, “e”, “f”));
```

**Comment by asolntsev** [comment]
Implemented in https://github.com/codeborne/selenide/pull/624, will be released in Selenide 4.9

**Comment by yashaka** [comment]
The feature is not implemented correctly. It also lacks test coverage in context of "waiting behaviour" and "error messages". 

@asolntsev, please reopen.

**Comment by asolntsev** [comment]
@yashaka Can you remind what exactly was implemented incorrectly? 

P.S. I added missing tests in a separate PR: https://github.com/codeborne/selenide/pull/779

**Comment by asolntsev** [comment]
@yashaka Can you remind what exactly was implemented incorrectly?

**Comment by yashaka** [comment]
oh... was so far in the past... I can hardly recall the point... 

Also, seems like I was not detailed enough in my last message... Sorry for that:(
