### ISSUE TITLE
Pass custom DesiredCapabilities to Browser

### ISSUE THREAD

**Issue by danteg233** [selenide/selenide#630]
## The problem
Hi there, we got small problem with running our test remotely on Selenium Hub. Everything works fine, If we use default drivers, but we need to have an option to use our own `DesiredCapabilities`. At the moment, it's impossible. So, we did implementation of `WebDriverProvider` (named it `CustomWebDriverProvider`), and it's works fine locally, but on Selenium Hub it doesn't work, it throws error

> The best matching driver provider org.openqa.selenium.ie.InternetExplorerDriver can't create a new driver instance for Capabilities [{pageLoadStrategy=normal, browserName=com.vmware.vcac.qe.ui.selenide.CustomWebDriverProvider}]

Yeap, the same trouble as it was discussed [here](https://github.com/codeborne/selenide/issues/558)

Thanks to [Boris Osipov](https://github.com/BorisOsipov) for answer.

## Our point
Could you add feature that gives us ability to put our own `Options` and `DesiredCapabilities` for browser, without any `WebDriverProvider` implementations, or tell `WebDriver ` to read it from some file.

**Comment by BorisOsipov** [comment]
Hi @danteg233 

Have a look to this pull request https://github.com/codeborne/selenide/pull/556/
If I understand you correctly this is exactly what you want. You can pick up this PR and help us to add this feature :wink:

**Comment by ostap-oleksyn** [comment]
@danteg233 what capabilities are you trying to set? Selenide can set custom capabilities via system property "capabilities.capabilityName". It should work with RemoteWebDriver as well.

**Comment by danteg233** [comment]
@ostap-oleksyn could u point, where I can find where Selenide reads all those capabilities?

**Comment by ostap-oleksyn** [comment]
[This method](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/webdriver/AbstractDriverFactory.java#L72) transferCapabilitiesFromSystemProperties() reads capabilities from system properties and those capabilities are then [merged](https://github.com/codeborne/selenide/blob/master/src/main/java/com/codeborne/selenide/webdriver/AbstractDriverFactory.java#L68) to common capabilities.

**Comment by danteg233** [comment]
@ostap-oleksyn that's not what we want, If we use that method, then we should set a lot of parameters, we want to be able to read it from some json let say, what is more elegantly

**Comment by SergeyPirogov** [comment]
Hi, regarding json you are able to use Java Owner or deserialize your capabilities from json like:

```
DesiredCapabilities dc = gson.fromFile("blabla")
Config.capabilities = dc
```

Just as an idea

**Comment by Gnafu** [comment]
I had this exact need for a project I jumped in recently.
If you have to change only the desired capabilities, and your capability is listed in the com.codeborne.selenide.Configuration file, you can just set them as suggested by @SergeyPirogov 

Configuration.browserCapabilities

Have a look at the AbstractDriverFactory.java as well, because the "pageLoadStrategy" is used alone, so you can set it without using the Configuration.browserCapabilities

Configuration.pageLoadStrategy

**Comment by asolntsev** [comment]
@danteg233 Can we close the issue? 
`Configuration.browserCapabilities` have been existing for a while.
