### ISSUE TITLE
Add Condition with Predicate<WebElement> parameter as alternative to check element conditions

### ISSUE THREAD

**Issue by rumpfc** [selenide/selenide#662]
Since Java 8 supports Lambda notations, there should be a possibility to check custom conditions with `Predicate<WebElement>` instead of writing a new Condition class which overrides `Condition.accept(WebElement).`

Example: Check if input element (id=myinputfield) doesn't contain any text (method name can be different)
```
Selenide.$("#myinputfield")
   .should(Condition.customCondition(w -> w.getAttribute("value").isEmpty()));
```

If giving each Condition a name is mandatory, maybe calling it like this:
```
Selenide.$("#myinputfield")
   .should(Condition.customCondition("Input element is empty", w -> w.getAttribute("value").isEmpty()));
```

- [ ] Add static function which accepts a Predicate<Webelement> (and String name) as parameter(s)

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/1059
