### ISSUE TITLE
Add support for Safari driver

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#69]
Starting with Selenium 2.30.0, the SafariDriver comes bundled with the Selenium server. Writing a test for Safari is just as straightforward as using the FirefoxDriver:

https://code.google.com/p/selenium/wiki/SafariDriver

P.S. Selenide tests need to be reworked because Safari driver doesn't support local URLs like file:/home/projects/bla.html": https://code.google.com/p/selenium/issues/detail?id=3773

**Comment by Mitalig** [comment]
@asolntsev Do we have complete support for Safari as we are in 2016 now?

**Comment by asolntsev** [comment]
@Mitalig Yes, Selenide does support Safari webdriver.
What you mean by **complete** support? 

P.S. It's still the sad true: some Selenide tests still fail with Safari browser. But it's not a problem of Selenide, it's a problem of Safari webdriver. As long as I understand, Apple developers do not want to implement webdriver standard for their browser.
