### ISSUE TITLE
Add API for manipulating windows/tabs

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#72]
Add method for convenient creating new tabs, switching to tab and back.

**Comment by kenston** [comment]
Hi @asolntsev, is there a built-in method for opening a new tab?

**Comment by asolntsev** [comment]
@kenston No, nor Selenide neither Selenium has such an API.
But this idea seems strange to me. Why would you need to open a tab? 
User doesn't do it. Typically a tab is opened when user clicks some element. So, your test should also click that element.

**Comment by kenston** [comment]
@asolntsev There are cases where we want to interact with more than two tabs at a time. We may have to interact (test) the front-end of a site, but at the same time having to interact (set-up) something on the back-end of the site (e.g., in the middle of the front-end testing) which requires opening a new tab.

**Comment by asolntsev** [comment]
I recommend to avoid using 2 tabs. More generally, avoid using UI for any
technical needs. If you need to prepare some data, change settings etc.,
please do it via API or SQL or whatever else, but not via UI. UI is only
for emulating user actions.

**Comment by kenston** [comment]
@asolntsev Thanks for the general advice. There are still legitimate use cases where back-end (UI) testing is part of the overall testing to be carried out by testers (for back-end users) although not necessarily for front-end users. For example, I may be testing my own WordPress plugin with a setting page in the Admin backend.

**Comment by asolntsev** [comment]
@kenston Well, you may test your own WordPress plugin, but I still claim that you don't need 2 tabs for that. 

The idea is still the same:
1. You write a separate test for the settings page. 
You click elements on the settings page and verify that appropriate settings are changed in database.

2. You write a separate test for client side.
You change settings in database and verify that end-client sees changes in UI.
