### ISSUE TITLE
Add new feature getSelectionRange / hasSelectionRange

### ISSUE THREAD

**Issue by mseele** [selenide/selenide#766]
## The problem
There is no method to check the selection range of text for an input text field.

## The Details
Whould be cool to integrade a method `SelenideElement.getSelectionRange` and/or `Condition.selectionRange(String selection)` to selenide.

## Tell us about your environment
* **Selenide Version:** 4.12.2
* **Selenium Version:** 3.13.0
* **OS Version:** Windows 10

## Code To Reproduce Issue [ Good To Have ]

Right now we check it like this:

```
private String getSelectionRange(SelenideElement element) {
	return executeJavaScript("return arguments[0].value.substring(arguments[0].selectionStart, arguments[0].selectionEnd);", element); //$NON-NLS-1$
}
```

**Comment by symonk** [comment]
Hi @mseele can you provide a little more info? is this for the length of entered text ('value') or the maximum length value on a given field?  I will create a PR when you clarify, thanks.

**Comment by vinogradoff** [comment]
What is selectionRange exactly? Characters selected with a mouse (to copy to clipboard?) inside of any element?

**Comment by mseele** [comment]
It's the start and end positions of the current text selection in an <input> element.

Please see https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange for more details.

It is, for example, usefull if you have an input field that selects the whole input on focus (by code) and you want to test this.

**Comment by asolntsev** [comment]
@mseele 
1. If I understand correctly, your method `getSelectionRange` actually returns selected text (not start/end positions). Thus it should be named `getSelectedText()`. Am I right?
2. In Selenide style, we should add condition instead of just getter. Like this:

```java
$("textarea#bio").shouldHave(selectedText("London"));
$("textarea#bio").shouldHave(text("birth place: London"));
```

**Comment by symonk** [comment]
given the following image, it would be returning the value for 'selected' (basically what has been selected / highlighted?

![image](https://user-images.githubusercontent.com/17887843/43411396-f786a258-9421-11e8-9528-ad6d732027dd.png)

if so, do we think this is a worthwhile feature to implement?

**Comment by mseele** [comment]
@symonk you example is exactly what i meant.

**Comment by asolntsev** [comment]
@symonk yes, why not. But I remind that I still prefer adding condition instead of just getter:

```java
$("textarea#bio").shouldHave(selectedText("London"));
```

**Comment by asolntsev** [comment]
@symonk Hi! How is your PR going?

**Comment by symonk** [comment]
pretty slow sorry @asolntsev I am experimenting with the idea here https://github.com/symonk/selenide/commit/addca46b59af1d2967ed8eba78f29c08aa7977dd, however I am changing jobs right now so I have a lot of stuff to work out and no time just yet to continue.

**Comment by asolntsev** [comment]
@symonk no problems! I can do this PR by myself. I just wanted to be sure that we don't do the same job twice.

**Comment by symonk** [comment]
@asolntsev Hello, I am settled into work now so im going to work on this, ok?

**Comment by asolntsev** [comment]
@symonk Sure, go on :)

**Comment by symonk** [comment]
@asolntsev we can close this, fixed in PR
