### ISSUE TITLE
Speedup the Page object initialization

### ISSUE THREAD

**Issue by deventh** [selenide/selenide#776]
## The problem
Page object initialization takes some time searching by selectors (css, xpath) and increasing proportionally to the fields count. Let's speed it up by simply init in a few threads

## Details
`org.openqa.selenium.support.PageFactory#proxyFields`

``` java
private static void proxyFields(FieldDecorator decorator, Object page, Class<?> proxyIn) {
    Field[] fields = proxyIn.getDeclaredFields();
    for (Field field : fields) {
      Object value = decorator.decorate(page.getClass().getClassLoader(), field);
      if (value != null) {
        try {
          field.setAccessible(true);
          field.set(page, value);
        } catch (IllegalAccessException e) {
          throw new RuntimeException(e);
        }
      }
    }
  }
```
fields init can be parallelized. Or create the extension point of the framework to let end user init the fields in the bulk and use many threads using `FieldDecorator`.

## Tell us about your environment
* **Selenide Version:** 3.12.0
* **Chrome\Firefox\IE Version:** does not matter
* **Browser Driver Version:** does not matter
* **Selenium Version:** does not matter
* **OS Version:** does not matter

**Comment by rosolko** [comment]
@deventh Hi there.
Do you get some metrics related to this improvement?
Can you please provide profit in numbers?

**Comment by symonk** [comment]
interested to see the gains, typically page objects should be small, having a huge class with many many locators is bad design and probably quite rare.

**Comment by asolntsev** [comment]
@deventh If I am not mistaken, Selenide doesn't load web elements immediately, but uses lazy loading. So, probably this optimisation doesn't have any effect...

**Comment by deventh** [comment]
@asolntsev page object fields are inited with the proxies. Now without changing the current API the one way to speed it up is call getters on fields in many threads. 

Or provide the own implementation of how the fields are inited. Since the Selenide is the framework and for the `org.openqa.selenium.support.pagefactory.FieldDecorator` there is the default proxy-based implementation it would be nice to make it a bit more flexible for this purpose.

`org.openqa.selenium.support.pagefactory.FieldDecorator` could look like:
```java
public interface FieldDecorator {
  Object decorate(ClassLoader loader, Collection<Field> fields);
}
```
instead of 
```java
public interface FieldDecorator {
  Object decorate(ClassLoader loader, Field field);
}
```
This will allow to build the custom `FieldDecorator` with fields init in many threads. It could be other implementation than default one.

I will provide the PR with example later

**Comment by asolntsev** [comment]
@deventh wait, it seems to be a bit over-engineering. Do you want to actually disable Selenide built-in lazy loading mechanism, and load all fields immediately (in many threads) to gain speed? How many milliseconds will you gain? Did you really try it? 
* Do you know that every following call to any of page object fields will intercept with the browser anyway? So, there will be many calls anyway. You cannot avoid all of them. 
* And what about the fact that lazy loading is really useful? Some elements may not exist at the moment when the page object is being initialised. Your solution will break many tests.

**Comment by deventh** [comment]
@asolntsev 

> Do you want to actually disable Selenide built-in lazy loading mechanism, and load all fields immediately (in many threads) to gain speed?

Surely no. But since there is a framework and as the end user I can choose the implementation I need for my particular case. `FieldDecorator` as interface allows me replace with a different implementation if needed. But this interface could be changed a bit to accept the Collection of fields instead of one by one

> And what about the fact that lazy loading is really useful? 

Yes, it is useful

> Do you know that every following call to any of page object fields will intercept with the browser anyway? So, there will be many calls anyway. You cannot avoid all of them.

Yes. Also the model of keeping webdrivers (now are kept per each thread) could be changed to try load them in parallel. I will try to experiment

**Comment by asolntsev** [comment]
@deventh I am not sure I really understand what are you trying to achieve. How many milliseconds can this approach save? Do you have any numbers?

Anyway, we cannot change `FieldDecorator` because it's a **Selenium**, not Selenide class. 

But well, if your experiments succeed, fell free to send pull request (even some draft variant). I am ready to discuss it. :)

**Comment by asolntsev** [comment]
@deventh I am closing the issue due to inactivity. 
Feel free to reopen if you wish.
