### ISSUE TITLE
PageFactory pattern with Selenide

### ISSUE THREAD

**Issue by brobee** [selenide/selenide#793]
Hi,

I didn't find any information regarding this, but I tried the following and I got an error:

I have a POM with PF:

```
public class WhateverClass extends BasePage {

    @FindBy(name = "LOGIN")
    private SelenideElement element1;

    @FindBy(name = "PASSWORD")
    private SelenideElement element2;

    @FindBy(name = "SUBMIT")
    private SelenideElement submitElement;

    @FindBy(id = "IFRAME")
    private SelenideElement cwIframe;

    public ConsultWorkStartPage() {
        PageFactory.initElements(driver, this);
    }

```
Initialization is not successful

> java.lang.IllegalArgumentException: Can not set com.codeborne.selenide.SelenideElement Element to com.sun.proxy.$Proxy85
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
> 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
> 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
> 	at java.lang.reflect.Field.set(Field.java:764)
> 	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:117)
> 	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
> 	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:92)
> 	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:79)

When I tried simple pure Selenium WebElement, I got Nullpointer Exception.

I'd like to use PageFactory in order to use Loadable Component approach to make our life (switching between the windows etc.) easier. Any suggestion would be appreciated.

**Comment by vinogradoff** [comment]
Actually you don't need PageFactor and FindBy annotation when using Selenide. Just do

    private SelenideElement element1=$(byName("LOGIN"));

    private SelenideElement element2=$(byName("PASSWORD"));

    private SelenideElement submitElement=$(byName("SUBMIT"));

    private SelenideElement cwIframe=$("#IFRAME");

will do the job.

You needed PageFactory and FindBy, because you cannot do it in Selenium in the same manner.

**Comment by brobee** [comment]
Ok gotit, how can you initialize and return page objects following the loadable component pattern? Actually that is the reason, why I want to use PF. Thanks

**Comment by symonk** [comment]
@brobee this is the power of selenide :) driver-less, page factory-less page objects, just nice and clean

**Comment by symonk** [comment]
@asolntsev @vinogradoff requesting to close? documentation already covers this
