### ISSUE TITLE
Download function: missing basic authentication header

### ISSUE THREAD

**Issue by marcuskaufmann** [selenide/selenide#831]
## The problem
The request that is fired to download a file from a site doesn't contain authentication header that is used in the session. Session cookies were applied to the new request but the authentication header field is missing.

## Details
When I browse a site that requires basic authentication and start to download a file, the file download results in a FileNotFoundException and the call finishs with HTTP 401 - unauthorized.

See DownloadFileWithHttpRequest.executeHttpRequest
If I add the missing header in debug mode before the call is fired then it works

## Tell us about your environment
* **Selenide Version:** 4.12.3

**Comment by marcuskaufmann** [comment]
Is there any update on that issue?

**Comment by symonk** [comment]
interesting, will have a little look into this tomorrow.  Please post anymore relevant info you have @marcuskaufmann

**Comment by symonk** [comment]
any available websites that can replicate this scenario publically @marcuskaufmann ?

**Comment by marcuskaufmann** [comment]
@symonk Unfortunately the website in question is not available to the public. The session cookie itself should be plenty enough to authenticate the call but in this case it isn't.
If I had to guess the reason then it would be a wrong configuration or implementation on the server side which I can't change though.

Basically it's more like a missing option to workaround such situations than an issue in Selenide.
I will try to create a demo project with jetty to emulate that behavior

**Comment by asolntsev** [comment]
@marcuskaufmann I guess it's a server configuration issue. I think that browser typically doesn't send BasicAuth header with every request, but only with first request (and then uses session cookie for following requests). 

Anyway, we could add BasicAuth header to download request. It should be a simple change.
@symonk What do you think?

**Comment by symonk** [comment]
hmm seems like a unique web application, I would assume after auth server would respond with the cookie for the client for subsequent requests. Do we just stealthily supply this HTTP header with the requests from download()? or do we have another command like downloadWithX(); ? @asolntsev

**Comment by asolntsev** [comment]
@symonk Good question. I am not sure. Probably I vote for "just stealthily supply this HTTP header with the requests from download()".

**Comment by marcuskaufmann** [comment]
Sorry, I had recently a busy time. I didn't had time to work on the demo project, too. Thank you for picking up this edge case anyway. You guys make a great job!

**Comment by asolntsev** [comment]
@marcuskaufmann @symonk I guess we can close the issue?
Feel free to reopen if you still need this feature.
