### ISSUE TITLE
Remove black magic from adjustBrowserSize() method

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [selenide/selenide#838]
`adjustBrowserSize` method contains following code:

```java
else if (config.startMaximized()) {
      try {
        if (browser.isChrome()) {
          maximizeChromeBrowser(driver.manage().window());
        }
        else {
          driver.manage().window().maximize();
        }
      }
      catch (Exception cannotMaximize) {
        log.warning("Cannot maximize " + driver.getClass().getSimpleName() + ": " + cannotMaximize);
      }
    }
```

this code in its turn has the "black magic" method: 

```java
private void maximizeChromeBrowser(WebDriver.Window window) {
    // Chrome driver does not support maximizing. Let apply black magic!
    org.openqa.selenium.Dimension screenResolution = getScreenSize();

    window.setSize(screenResolution);
    window.setPosition(new org.openqa.selenium.Point(0, 0));
  }

  Dimension getScreenSize() {
    Toolkit toolkit = Toolkit.getDefaultToolkit();

    return new Dimension(
      (int) toolkit.getScreenSize().getWidth(),
      (int) toolkit.getScreenSize().getHeight());
  }
```

that seems to be not useful anymore. Chrome already is able to maximize the window.

Tried `getWebDriver().manage().window().maximize()` in debug and it worked like a charm in Chrome!

**Comment by symonk** [comment]
`getWebDriver().manage().window().maximize()` not sure this works in mac OSX, will confirm in work tomorrow but I have problems with it

**Comment by rosolko** [comment]
@asolntsev @BorisOsipov Also notice that `driver.manage().window().fullscreen()` works well on mac. So can it be `maximize` replacement for chrome?

**Comment by BorisOsipov** [comment]
```
    /**
     * Maximizes the current window if it is not already maximized
     */
    void maximize();

    /**
     * Fullscreen the current window if it is not already fullscreen
     */
    void fullscreen();
```

I am not sure that maximize() and fullscreen() are the same

**Comment by asolntsev** [comment]
@BorisOsipov @rosolko Exactly. "maximize" and "fullscreen" are different things. 

@AlexanderPoleschuk @symonk I confirm: "maixime" still doesn't work on Mac. :( 

So we still cannot remove the hack :( At least for Mac.

**Comment by asolntsev** [comment]
Can anyone confirm that "maximize" works with Chrome on Windows and Linux? 
We probably could use this hack only on MacOS?

**Comment by rosolko** [comment]
@asolntsev Works well on windows. Can't say anything for linux.

**Comment by AlexanderPoleschuk** [comment]
https://bugs.chromium.org/p/chromedriver/issues/detail?id=985 JFYI. the issue was logged in 2015...

**Comment by symonk** [comment]
I think the hack is ok until official support is created, tho that seems to be a low priority :/ we can leave this open but i think it might be a while :D

**Comment by symonk** [comment]
something like this works on mac OSX -> chromeOptions.add_argument("--kiosk"), but it enters a kind of stupid mode... I prefer to just read screensize and set it.

**Comment by asolntsev** [comment]
@AlexanderPoleschuk @symonk Just tried - still getting the same problem. :(

I am executing: 
```
driver.manage().window().maximize();
```

and getting:

```
unknown error: failed to change window state to maximized, current state is normal
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.14.1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
```

**Comment by AlexanderPoleschuk** [comment]
@asolntsev 
> Driver info: chromedriver=2.42.591059

The issue was fixed in 2.44 drvier.
Here are release notes:
https://sites.google.com/a/chromium.org/chromedriver/downloads

However, I'm not sure how we may provide backward-compatible solution for pre-2.44 versions, if we remove this workaround.
Thoughts?

**Comment by rosolko** [comment]
Can confirm, maximize works on a macos with `2.44` version of chromedriver

**Comment by asolntsev** [comment]
@AlexP no problems. Selenide contains file `versions.properties`, so we can assume that (most of) Selenide users use the right chromedriver version.

**Comment by symonk** [comment]
```Starting ChromeDriver 2.44.609545 with => Version 70.0.3538.110 (Official Build) (64-bit)```

successfully maximized

**Comment by symonk** [comment]
@asolntsev @rosolko any more thoughts on this?

**Comment by asolntsev** [comment]
@symonk thank you for the reminder! I will try it once more on my Mac and then remove the black magic.

**Comment by symonk** [comment]
sure thing, if you need help checking something just ping me

**Comment by asolntsev** [comment]
@symonk Allright, I checked out - Chrome maximization now works on MacOS. I created a PR: https://github.com/selenide/selenide/pull/901
