### ISSUE TITLE
Selenide 5 breaks remote driver initialization

### ISSUE THREAD

**Issue by AlexanderPoleschuk** [selenide/selenide#839]
Before 5.0.0 the code below worked like a charm:
```
@BeforeMethod(alwaysRun = true)
public static void setup() {
WebDriverRunner.setWebDriver(remote);
remote.manage().window().maximize();
remote.manage().deleteAllCookies(); //IE fix
open(Configuration.baseUrl);
````
On 5.0.0 it claims to use open() before driver is initialized. It seems to be weird.

In addition this code:
```
@AfterSuite
public static void saveEnvironment() {
        Configuration.headless = true;
        HasCapabilities remote = (HasCapabilities) getWebDriver();
        ENV.setProperty("Url:", Configuration.baseUrl);
....
```
is not working anymore w/o specifying open() command also. It was used to save parameters that are placed in allure.properties file and are used in allure report.

**Comment by rosolko** [comment]
Start from 5 version you have to call open to initialize you browser.
Work as designed.
Looks like you trying to access `remote` varable initialized in `AfterSuite` block but in `BeforeMethod` block - it's a wrong using.

**Comment by asolntsev** [comment]
@AlexanderPoleschuk Can you answer for this question:
> How is it possible that you use `remote` variable in `@BeforeMethod`, but get it only in `@AfterSuite`? Please show all your setup code. How do you initialize `remote` variable?

**Comment by AlexanderPoleschuk** [comment]
@asolntsev remote variable was one of the ways(or maybe the only) for real browser maximization.
I've described part of this in https://github.com/selenide/selenide/issues/838. So, instead of enlarging the window size to screen size we've used remote to manage this, cause remote really maximized the window. 
As now I'm not able to run test cases against Jenkins, I've removed remote initialization and use getWebDriver().manage().window().maximize(); directly.

as for using remote in @AfterSuite - it was used to store values into environment.properties file for Allure. So they a kinda two separate things.

**Comment by asolntsev** [comment]
@AlexanderPoleschuk Can you show **compilable code** that reproduces the problem? Otherwise we cannot investigate it. The code provided in the beginning of this issue is **not compilable**: method `setup()` uses variable `remote` which is **not defined** anywhere.

**Comment by AlexanderPoleschuk** [comment]
Here you go. As I've said - remote used to maximize the window to full width. The code below works with latest 4.* version, but doesn't work starting with 5.*. The code might seem strange, but it was used for quite a long time on a purpose to save environment values for a build run. And I don't complain about the way Selenide 5 works now, this is more informative issue thing.

```
package core.base;

import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.WebDriverRunner;
import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.openqa.selenium.HasCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.BeforeSuite;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Paths;
import java.util.Properties;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;

public class TestBase {

    private static final String BROWSER = StringUtils.defaultString(System.getProperty("browser"),
            "chrome");
    public static final Logger LOGGER = Logger.getLogger(TestBase.class);
    private static final Properties ENV = new Properties();

    @BeforeSuite
    public static void setVariables() {
        Configuration.timeout = 5000L;
        Configuration.baseUrl = "https://www.onliner.by/";
        Configuration.startMaximized = true;
        Configuration.fastSetValue = true;
        Configuration.savePageSource = false;
//        Configuration.headless = true;
        Configuration.browser = BROWSER;
    }

    @BeforeMethod(alwaysRun = true)
    public static void setup() {
        RemoteWebDriver remote = (RemoteWebDriver) getWebDriver();
        WebDriverRunner.setWebDriver(remote);
        remote.manage().window().maximize();
        remote.manage().deleteAllCookies(); //IE fix
        open("");
    }

    @AfterMethod(alwaysRun = true)
    public static void tearDown() {
       WebDriverRunner.closeWebDriver();
    }

    @AfterSuite
    public static void saveEnvironment() {
        HasCapabilities remote = (HasCapabilities) getWebDriver();
        ENV.setProperty("Url", Configuration.baseUrl);
        ENV.setProperty("Browser", remote.getCapabilities().getBrowserName() + " v." + remote.getCapabilities().getVersion());
        ENV.setProperty("Platform", remote.getCapabilities().getPlatform().name());
        ENV.setProperty("Platform version", remote.getCapabilities().getPlatform().getMajorVersion() + "." +
                remote.getCapabilities().getPlatform().getMinorVersion());
        File file = Paths.get(System.getProperty("user.dir"), "/target/allure-results").toAbsolutePath().toFile();
        if (!file.exists()) {
            LOGGER.info("Created dirs: " + file.mkdirs());
        }
        try (FileWriter out = new FileWriter("./target/allure-results/environment.properties")) {
            ENV.store(out, "Environment variables for report");
        } catch (IOException ex) {
            LOGGER.error("Unable to write info to: " + file.getName(), ex);
        }
    }
}
```

**Comment by asolntsev** [comment]
@AlexanderPoleschuk Thank you, now I can investigate your issue.

The problem is in method `setup()`. You just need to remove one line:

```
    public static void setup() {
        RemoteWebDriver remote = (RemoteWebDriver) getWebDriver();
        WebDriverRunner.setWebDriver(remote);   // REMOVE THIS LINE
        remote.manage().window().maximize();
        ...
    }
```

It will solve your problem. 

P.S. There is an open issue for similar problem: https://github.com/selenide/selenide/issues/867
