### ISSUE TITLE
unknown error: cannot parse capability: pageLoadStrategy

### ISSUE THREAD

**Issue by paveltrue** [selenide/selenide#843]
I'm launching my tests in a suite. And i get this error:
org.openqa.selenium.WebDriverException: unknown error: cannot parse capability: pageLoadStrategy
from unknown error: page load strategy unsupported
  (Driver info: chromedriver=2.42.591088 (7b2b2dca23cca0862f674758c9a3933e685c27d5),platform=Windows NT 6.2.9200 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 45 milliseconds
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'AVK', ip: '192.168.4.233', os.name: 'Windows 8', os.arch: 'amd64', os.version: '6.2', java.version: '1.8.0_162'
Driver info: driver.version: ChromeDriver

But when i launching my tests separately all is fine. 
where is my fault?

**Comment by BorisOsipov** [comment]
Chrome does not support PageLoadStrategy.EAGER check it in your code\env

**Comment by paveltrue** [comment]
omg. Stupid mistake. Thanks a lot
