### ISSUE TITLE
ClassCastException after updating of Selenide from 4.12.3 to 5.0.0

### ISSUE THREAD

**Issue by Victoria151291** [selenide/selenide#844]
## The problem
ClassCastException at getting text of element of list after updating of Selenide from 4.12.3 to 5.0.0

## Details
I have a following problem after updating Selenide from 4.12.3 to 5.0.0.
I have one method which collects the list of selenide elements and other method which gets the element from this list, its text and compares it with the string from the other list.

During the test it's failed with following exception:
java.lang.ClassCastException: java.base/java.lang.String cannot be cast to com.codeborne.selenide.SelenideElement

If you simply get the element's text like that:
`someFilters1.get(0).getText()`
everything is OK.

Test completes successfully with the previous Selenide's version 4.12.3.

## Tell us about your environment
* **Selenide Version:** 5.0.0
* **Chrome\Firefox\IE Version:** Chrome 69.0.3497.100
* **Browser Driver Version:** ChromeDriver 2.41
* **OS Version:** Windows 10

## Code To Reproduce Issue [ Good To Have ]

```
 public List <SelenideElement> getListOfFilters() {
     ElementsCollection someFilters1 = $$x("someLocator1");
     ElementsCollection someFilters2 = $$x("someLocator2");
     ElementsCollection someFilters3 = $$x("someLocator3");
     List <SelenideElement> commonListOfFilters = new ArrayList < > ();
     commonListOfFilters.addAll(someFilters1);
     commonListOfFilters.addAll(someFilters2);
     commonListOfFilters.addAll(someFilters3);
     return commonListOfFilters;
 }

 public void compareFilters() {
     FiltersOnPage filtersOnPage = new FiltersOnPage();
     range(0, listOfLabelsOfFilters.size()).forEach(
         i - > getVisibleTextAndAssertIt(filtersOnPage.getListOfFilters().get(i), listOfLabelsOfFilters.get(i)));
 }

 public Page getVisibleTextAndAssertIt(SelenideElement element, String matchText) {
     String elementText = element.getText();
     assertEquals(elementText, matchText);
     return this;
 }
```

**Comment by Victoria151291** [comment]
Tell me please when will this bug fixed? Thanks.

**Comment by BorisOsipov** [comment]
@Victoria151291 Sure!


minimum reproducable example
```
    open("https://the-internet.herokuapp.com/tables");
    ElementsCollection elements = $$("#table1 td");
    List<SelenideElement> selenideElements = new ArrayList<>();
    selenideElements.addAll(elements);// here collection elements will be casted to List<String>
	
```

**Comment by BorisOsipov** [comment]
@Victoria151291 fix was released in 5.0.1

**Comment by Victoria151291** [comment]
@BorisOsipov , yes, I've already seen it and updated the Selenide's version in my project. Thank you very much 👍

**Comment by TeooLuarsabishvili** [comment]
Hi, I have same problem for  selenide 7.0.0 and higher

**Comment by asolntsev** [comment]
> Hi, I have same problem for  selenide 7.0.0 and higher

I don't believe ;)

Please provide proof.
