### ISSUE TITLE
Add the possibility to move to a certain sibling and preceding element, after `parent()` method

### ISSUE THREAD

**Issue by plagov** [selenide/selenide#845]
## The problem
Add the possibility to move to a certain sibling and preceding element, after `parent()` method, relative to the one the `parent()` method was called.

## Details
Consider the following HTML:

```html
<tr>
  <td>
  <td>
</tr>
<tr>
  <td class="today">
  <td>
</tr>
<tr>
  <td>
  <td>
</tr>
```

So, if I would need to move to the `td` element in `tr` that is next to `tr td.today`, I would do: 
`$("td.today").parent().sibling(0).find("td", 1);`

Respectively, if moving to the `td` in preceding `tr` before `tr td.today`, then it would be:
`$("td.today").parent().preceding(0).find("td", 1);`

Argument of `sibling()` or `preceding()` method is the index of a sibling/preceding element relative to the current element where `parent()` method was called.

**Comment by asolntsev** [comment]
Implemented in https://github.com/selenide/selenide/pull/1064
