### ISSUE TITLE
Whether there is a way to force to tighten all dependences (including the web driver) at a stage of assembly of the maven project?

### ISSUE THREAD

**Issue by vitassecuriti** [selenide/selenide#846]
## The problem
At assembly of the maven project in a local repository the dependences of libraries specified in pom.xml and other necessary dependences are tightened. 

During the work in the closed network (without free access in the Internet) we use artifactory in the closed contour. In this artifactory neobzodimy dependences are replicated from artifactory in an open contour.

If I correctly understand, webdriver manager downloads the necessary driver at launch of tests. Thus, webdriver doesn't get to a local repository since from the closed network can't download the necessary driver.

Whether there is a way to force to tighten all dependences (including the web driver) at a stage of assembly of the maven project?

## Tell us about your environment
* **Selenide Version:** 5.0.0
* **Chrome\Firefox\IE Version:** 70.0
* **Browser Driver Version:** 
* **Selenium Version:**
* **OS Version:** Win 7 pro

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

## Details
pom.xml
```pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>test</groupId>
    <artifactId>1</artifactId>
    <version>1.0-SNAPSHOT</version>
    
    <!-- For allure reporting -->
    <properties>
        <aspectj.version>1.8.10</aspectj.version>
    </properties>
    <!-- For allure reporting -->
    
    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>5.0.0</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <!-- For allure reporting -->
	    <dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-junit4</artifactId>
			<version>2.7.0</version>
	    </dependency>
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-selenide</artifactId>
			<version>2.7.0</version>
		</dependency>

        <!-- For allure reporting -->
    </dependencies>
	<build>
	    <plugins>
		<plugin>
		    <groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-surefire-plugin</artifactId>
		    <version>2.20</version>
		    <configuration>
		        <testFailureIgnore>false</testFailureIgnore>
		        <argLine>
		            -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
		        </argLine>
		        <properties>
		            <property>
		                <name>listener</name>
		                <value>io.qameta.allure.junit4.AllureJunit4</value>
		            </property>
		        </properties>
		    </configuration>
		    <dependencies>
		        <dependency>
		            <groupId>org.aspectj</groupId>
		            <artifactId>aspectjweaver</artifactId>
		            <version>${aspectj.version}</version>
		        </dependency>
		    </dependencies>
		</plugin>
		</plugins>
	</build>
</project>
```

my simple test
```java
import com.codeborne.selenide.logevents.SelenideLogger;
import io.qameta.allure.junit4.DisplayName;
import io.qameta.allure.selenide.AllureSelenide;
import org.junit.Test;
import static com.codeborne.selenide.Condition.visible;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.WebDriverRunner.CHROME;
import static junit.framework.TestCase.assertTrue;

public class TestFile {

    @Test
    @DisplayName("Чтоб название теста было  readble")
    public void TestdriverTest(){
	SelenideLogger.addListener("AllureSelenide", new 
        AllureSelenide().screenshots(true).savePageSource(false));
        String webUrl = "http://mail.ru";
	com.codeborne.selenide.Configuration.baseUrl = webUrl;
        String gridHubUrl = "http://10.50.8.125:4444/wd/hub";//"http://localhost:4444/wd/hub";
        com.codeborne.selenide.Configuration.timeout = 10000;
        com.codeborne.selenide.Configuration.browser = CHROME;
        com.codeborne.selenide.Configuration.startMaximized = true;
        com.codeborne.selenide.Configuration.remote = gridHubUrl;

        open("http://mail.ru");
	$("a.logo__img").shouldBe(visible);
        assertTrue("Test",true);
    }
}
```

**Comment by symonk** [comment]
I don't think this is a selenide issue @vitassecuriti.

the WDM is configured separately. you have some options:

Option 1)
```java
## this can support a proxy inside the WebDriverManager config
#wdm.proxy=here
# wdm.proxyUser=
# wdm.proxyPass=
```

Option 2) Disable it in selenide and use standard binary lookup with system properties.

Option 3) Configure wdm to download the binaries internally and host them somewhere, e.g on Artifactory

**Comment by BorisOsipov** [comment]
>I left this issues with the purpose to understand whether there is an opportunity in general, if perhaps, then how to realize.

1) @symonk described opportunities. How to realize is up to you. We don't know your limitation and so on.
2) May make advise to try [selenoid](https://github.com/aerokube/selenoid). It can work in docker or standalone mode. For more details read his docs.
3) Also, if you use `Configuration.remote=url` Selenide won't handle drivers binary downloading.


>If to use system variables, then the sense available of the web driver in selenide vanishes.

Only for you. If you are in restricted network it is your problem not selenide.

>Can you give examples how to configure wdm for work with the necessary Artifactory from maven of the project with tests?

I guess You should make such questions in [wdm repo](https://github.com/bonigarcia/webdrivermanager/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by vitassecuriti** [comment]
>> Only for you. If you are in restricted network it is your problem not selenide.

**Comment by symonk** [comment]
Thanks, but just like any library selenide cannot cater to closed networks in terms of web driver manager (nor can Web Driver Manager itself).

If a proxy to the outside internet is out of the question perhaps just disabling this feature when working with selenide and managing your binaries internally is the best approach.  This is what I would recommend.

Thanks and  thanks for using Selenide.  @asolntsev @BorisOsipov  we should close this one.
