### ISSUE TITLE
Error in proxy settings before starting the browser

### ISSUE THREAD

**Issue by rtvbaa** [selenide/selenide#850]
## The problem
Error in proxy settings before starting the browser

## Details
To start the proxy, I use the following settings:
  BrowserMobProxy proxy = new BrowserMobProxyServer();
  proxy.setTrustAllServers(true);
  proxy.blacklistRequests("https?://www\\.google\\.com/.*", 400);
  proxy.start(80);

If I want to use Selenide proxy:
  Configuration.proxyEnabled = true;
  Configuration.proxyPort = 80;
  WebDriverRunner.getSelenideProxy().getProxy().blacklistRequests("https?://www\\.google\\.com/.*", 400);
  open("https://www.google.com");

Process finished with exit code -1
java.lang.NullPointerException

* **Selenide Version:5.0.0**
* **Chrome**

**Comment by rosolko** [comment]
@rtvbaa Proxy starts after driver starts, so in your case when you call `WebDriverRunner.getSelenideProxy()` your receise a `java.lang.NullPointerException` because there are no running proxy.
Just change order of your requests:
1. `open("google.com");`
2. `WebDriverRunner.getSelenideProxy().getProxy().blacklistRequests("https?://www\.google\.com/.*", 400);`
3. other logic

**Comment by rtvbaa** [comment]
open("google.com"); runs a proxy and opens the site. All requests after it are meaningless.

**Comment by rtvbaa** [comment]
I need to block all sites except the checked, but for an example it is better.

**Comment by asolntsev** [comment]
@rtvbaa Method `WebDriverRunner.getSelenideProxy()` returns null when called **before** method `open()`. It's because method `open()` actually starts proxy server and opens a browser window. 

You can open a blank browser window before setting blacklist:

```java
open();
WebDriverRunner.getSelenideProxy().getProxy().blacklistRequests("https?://www\.google\.com/.*", 400);
open("https://www.google.com");
```
