### ISSUE TITLE
Chrome does not start in headless mode when proxyEnabled is true

### ISSUE THREAD

**Issue by Mcseemkaz** [selenide/selenide#853]
## The problem
I try to implement tests to check that file can be downloaded. So I put some settings for this in @Before method:
Configuration.fileDownload = PROXY;
Configuration.proxyEnabled = true;

It works fine and file has already downloaded when running on Chrome.
But when I run a test on Chrome headless mode it`s failed because the browser isn`t able to open tested page (just blank screen on a screenshot).

I didn't' set up any additional parameters for the proxy. I supposed Selenide own proxy should be enough for this simple case. 

## Tell us about your environment
* **Selenide Version:*5.0.0*
* **Chrome\Firefox\IE Version:*Chrome v 71.0.3578.33*
* **OS Version:*Windows 10 64*

**Comment by rosolko** [comment]
@Mcseemkaz Chrome 71? For now the latest stable version is 70.0.3538.77

**Comment by Mcseemkaz** [comment]
Yep, I mixed up -  Chrome driver is 71, the browser version, of course, is 70. But the issue still is presented. @rosolko Could you provide some help, please?

**Comment by rosolko** [comment]
@Mcseemkaz chromedriver can't be 71 version. `2.43` is latest one!
http://chromedriver.chromium.org/downloads

**Comment by BorisOsipov** [comment]
@rosolko [71 exists.](https://chromedriver.storage.googleapis.com/index.html?path=71.0.3578.33/) It is a new version. 
For details about new versioning see https://groups.google.com/forum/#!topic/chromedriver-users/HvlKWqv34es

**Comment by BorisOsipov** [comment]
@Mcseemkaz 	We can't recomend and support 70-71 chromedrivers cause it is no official version by Chrome devs.
"This new release is still experimental, and is not yet a replacement for the official release of ChromeDriver, currently at version 2.42. Instead,"

**Comment by rosolko** [comment]
@BorisOsipov Got it, thanks!

**Comment by Mcseemkaz** [comment]
@rosolko  ![image](https://user-images.githubusercontent.com/35467812/48075188-4cfccc00-e1eb-11e8-9a9b-ba6fc495adf5.png)

Maybe, we will finish the conversation about Chrome version. Guys, I just would like to get help with my problem.

**Comment by rosolko** [comment]
Your problem can be cause by incompatible of new chromedriver and chrome

**Comment by rosolko** [comment]
@Mcseemkaz As @BorisOsipov previously offer to you - downgrade chromedriver to 2.42 version.

**Comment by rosolko** [comment]
@Mcseemkaz Reference documentation about solution: https://github.com/bonigarcia/webdrivermanager

**Comment by BorisOsipov** [comment]
@Mcseemkaz Please, let us know if downgrade to chromedriver to 2.4X helps.

**Comment by Silentpax** [comment]
Hi

I've encountered the same issue using docker and xvrb.

CHROME_VERSION: 68.0.3440.84
CHROMEDRIVER_VERSION: 2.42
Initial DockerFile that I'm building on maven:3.5.4-jdk-8

xvrb command: `xvfb-run --server-args="-screen 0 2560x1440x24" mvn -e -B exec:java -PRunner`

What's funny, on my local machine (Linux mint 18.3) this problem does not exist.

**Comment by BorisOsipov** [comment]
@Silentpax your issue is:
you use 
```
Configuration.fileDownload = PROXY;
Configuration.proxyEnabled = true;
```
and some docker image your app url isn't loading, am I rigth?

**Comment by rosolko** [comment]
As I remember headless chrome doesn't require xvfb session

**Comment by Silentpax** [comment]
@BorisOsipov exactly, just a blank page in screenshot

@rosolko will check it out

**Comment by BorisOsipov** [comment]
@Silentpax also simple project with test and your dockerfile will help us to reproduce issue.

**Comment by asolntsev** [comment]
@Mcseemkaz I cannot reproduce your problem. I have been using Chrome+headless+proxy in my test for several years, and they work all the time. I guess your problem could be caused by mismatching versions of chrome and chromedriver.

**Comment by asolntsev** [comment]
Closing the issue due to inactivity.

**Comment by MartinGitGud** [comment]
same issue with firefox 85.0.2, gecko driver 0.29.0, selenide driver 3.141.59

**Comment by asolntsev** [comment]
@MartinGitGud Thank you for sharing the knowledge!
Probably a good idea to set proxy host is using Selenium built-in helper class `NetworkUtils`:

```java
Configuration.proxyHost = new NetworkUtils().getNonLoopbackAddressOfThisMachine();
```

**Comment by MartinGitGud** [comment]
unfortunately, 
`Configuration.proxyHost = new NetworkUtils().getNonLoopbackAddressOfThisMachine();`

does return my machine name instead of "localhost" and is exactly the reason why the website is not shown inside the browser window.
