### ISSUE TITLE
Chrome process hangs after Selenide tests runs

### ISSUE THREAD

**Issue by xkubist** [selenide/selenide#857]
## The problem
Chrome close, but chrome process hangs after Selenide tests runs. I expect the chrome process to be closed.

## Tell us about your environment
* **Selenide Version: 4.9.1**
* **Chrome Version: 70.0.3538.77**
* **Browser Driver Version: 2.43**
* **Selenium Version: 3.8.1:**
* **OS Version: Windows 10**

## Code To Reproduce Issue
public void googleTest() {
        System.setProperty("webdriver.chrome.driver","C:\\Users\\kubistelm\\Downloads\\chromedriver_win32\\chromedriver.exe");
        System.setProperty("selenide.browser", "Chrome");
        open("https://google.com/ncr");
        $(By.name("q")).val("google").pressEnter();
}

**Comment by asolntsev** [comment]
Closing the issue due to inactivity.
