### ISSUE TITLE
NoClassDefFoundError: org/openqa/selenium/remote/DesiredCapabilities

### ISSUE THREAD

**Issue by jkromski** [selenide/selenide#860]
## The problem
I'm not sure if this is an issue but for some reason I was missing org.seleniumhq.selenium:selenium-remote-driver so I assume that it should be added to Selenide dependencies

## Details
Running a test via Intellij
Exception thrown:
```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/DesiredCapabilities

	at com.codeborne.selenide.webdriver.AbstractDriverFactory.createCommonCapabilities(AbstractDriverFactory.java:63)
	at com.codeborne.selenide.webdriver.FirefoxDriverFactory.createFirefoxOptions(FirefoxDriverFactory.java:51)
	at com.codeborne.selenide.webdriver.FirefoxDriverFactory.createFirefoxDriver(FirefoxDriverFactory.java:32)
	at com.codeborne.selenide.webdriver.FirefoxDriverFactory.create(FirefoxDriverFactory.java:28)
	at com.codeborne.selenide.webdriver.WebDriverFactory.lambda$createWebDriver$0(WebDriverFactory.java:61)
	at java.base/java.util.Optional.map(Optional.java:254)
	at com.codeborne.selenide.webdriver.WebDriverFactory.createWebDriver(WebDriverFactory.java:61)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.createDriver(WebDriverThreadLocalContainer.java:230)
	at com.codeborne.selenide.impl.WebDriverThreadLocalContainer.getAndCheckWebDriver(WebDriverThreadLocalContainer.java:116)
	at com.codeborne.selenide.WebDriverRunner.getAndCheckWebDriver(WebDriverRunner.java:134)
	at com.codeborne.selenide.impl.Navigator.navigateTo(Navigator.java:66)
	at com.codeborne.selenide.impl.Navigator.open(Navigator.java:38)
	at com.codeborne.selenide.Selenide.open(Selenide.java:80)
	at com.codeborne.selenide.Selenide.open(Selenide.java:56)
```
my failing dependencies:
```
+- com.codeborne:selenide:jar:4.14.0:test
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-api:jar:3.14.0:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-safari-driver:jar:3.14.0:test
[INFO] |  |  +- org.seleniumhq.selenium:selenium-support:jar:3.14.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.8.15:test
[INFO] |  |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  +- io.github.bonigarcia:webdrivermanager:jar:2.2.5:test
[INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.25:test
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.7:test
[INFO] |  |  +- org.rauschig:jarchivelib:jar:0.8.0:test
[INFO] |  |  |  \- org.apache.commons:commons-compress:jar:1.14:test
[INFO] |  |  \- org.jsoup:jsoup:jar:1.11.3:test
[INFO] |  +- net.lightbody.bmp:browsermob-core:jar:2.1.5:test
[INFO] |  |  +- net.lightbody.bmp:littleproxy:jar:1.1.0-beta-bmp-17:test
[INFO] |  |  +- dnsjava:dnsjava:jar:2.1.8:test
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.25:test
[INFO] |  |  +- com.jcraft:jzlib:jar:1.1.3:test
[INFO] |  |  +- io.netty:netty-all:jar:4.0.51.Final:test
[INFO] |  |  +- org.bouncycastle:bcprov-jdk15on:jar:1.58:test
[INFO] |  |  +- org.bouncycastle:bcpkix-jdk15on:jar:1.58:test
[INFO] |  |  \- net.lightbody.bmp:mitm:jar:2.1.5:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-api:jar:5.2.0:test
[INFO] |     +- org.apiguardian:apiguardian-api:jar:1.0.0:test
[INFO] |     +- org.opentest4j:opentest4j:jar:1.1.0:test
[INFO] |     \- org.junit.platform:junit-platform-commons:jar:1.2.0:test
```

## Environment
* **Java Version:** 10.0.2
* **Selenide Version:** 4.14.0
* **Chrome\Firefox\IE Version:** Not related
* **Browser Driver Version:** 3.14?
* **Selenium Version:** 3.14
* **OS Version:** Ubuntu 18.04

## Solution which I found is:
Add explicit dependency:
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-remote-driver</artifactId>
	<version>3.14.0</version>
</dependency>

Would this be a good way for solving it?

**Comment by BorisOsipov** [comment]
@jkromski can you show your pom.xml? I don't have an idea what is going on.

As you can see in https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.14.0

`org.seleniumhq.selenium-remote-driver` is dependency of `org.seleniumhq.selenium:selenium-java` and we depends only on `selenium-java`. So you don't have to add `elenium-remote-driver` to make it work.

**Comment by jkromski** [comment]
yes you are right 
possibly some issue on mvn caching side?

my pom dependencies
<dependencies>
		<dependency>
			<groupId>com.codeborne</groupId>
			<artifactId>selenide</artifactId>
			<version>4.14.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>3.14.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.10</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jmagick</groupId>
			<artifactId>jmagick</artifactId>
			<version>6.6.9</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.im4java</groupId>
			<artifactId>im4java</artifactId>
			<version>1.4.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.minio</groupId>
			<artifactId>minio</artifactId>
			<version>5.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.google.inject</groupId>
			<artifactId>guice</artifactId>
			<version>4.2.0</version>
		</dependency>
		<dependency>
			<groupId>ru.yandex.qatools.ashot</groupId>
			<artifactId>ashot</artifactId>
			<version>1.5.4</version>
		</dependency>
	</dependencies>

**Comment by BorisOsipov** [comment]
>possibly some issue on mvn caching side?

@jkromski no it's maven dependency resolution issue. `ashot` depends on 
`org.seleniumhq.selenium.selenium-remote-driver:2.53.0` So, maven use `2.53.0` for `selenium-remote-driver`

**Comment by BorisOsipov** [comment]
You can try to exclude such deps from `ashot` or explicitly set `selenium-remote-driver` in your pom.xml.

it's not selenide issue. I'am closing this.

**Comment by jkromski** [comment]
thanks, I see the version which you pointed out but much lower on the list.
Thanks
