### ISSUE TITLE
Add aliases for $ and $$ similar to $x and $$x but for all another selector types

### ISSUE THREAD

**Issue by nbdnnm** [selenide/selenide#864]
Hello,

I would like to propose the next improvement:
Introduce the same separate selector aliases for $ and $$ as for xpath ($x and $$x), e.g. 
Java selector | proposed selenide selector
--------------|-----------------------------
className | $className, $SclassName
cssSelector | $css, $Scss
id | $id, $$id
linkText | $linkText, $$linkText
name, $name, $$name
partialLinkText | $partialLinkText, $$partialLinkText
tagName | $tagName, $$tagName

**Comment by rosolko** [comment]
Not planed.
Selenide contains only aliases that can be copied and reused in a console.
