### ISSUE TITLE
Selenide 5.0.0. WebDriverRunner.setWebDriver(new ChromeDriver()) incorrect behaviour

### ISSUE THREAD

**Issue by alexmuzyka** [selenide/selenide#867]
Code:
...
WebDriver instance1 = WebDriverRunner.getWebDriver();
WebDriverRunner.setWebDriver(new ChromeDriver());
WebDriver instance2 = WebDriverRunner.getWebDriver();
...

On Selenide 4... it worked as we expected: we have two instances, and can easely switching between them.

On Selenide 5.0.0 after WebDriverRunner.setWebDriver(new ChromeDriver()) - WebDriverRunner is closing opened browser (instance1), and create a new one. 

Can you return back this functionality?

Thanks

PS: original comment (request) from Andrei Solntsev: https://selenide.org/2018/10/10/selenide-5.0.0/

**Comment by rosolko** [comment]
No, we can't.
Use a new approach for two instances:
```
SelenideDriver browser1 = new SelenideDriver();
SelenideDriver browser2 = new SelenideDriver();
```

**Comment by BorisOsipov** [comment]
@alexmuzyka We suggest to use new approach as described @rosolko 

But it seems to need ahve look at this issue deeper.

**Comment by asolntsev** [comment]
See PR https://github.com/selenide/selenide/pull/890
