### ISSUE TITLE
All downloaded files should be stored in unique locations

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#892]
## The problem
Currently Selenide downloads all files to `build/reports/tests` with their original names. 
It can cause a problem when several parallel tests download multiple files with the same name. 

We need to generate unique location for every downloaded file.

**Comment by symonk** [comment]
perhaps, to also include https://github.com/selenide/selenide/issues/225 ?

**Comment by symonk** [comment]
@asolntsev @rosolko looks like we have surpassed the milestones here, should we modify them again?  5.2.2 was released I think

**Comment by asolntsev** [comment]
@symonk thank you. Marking this issue as resolved (actually in December 2018) :)
