### ISSUE TITLE
Scraping multiple pages of Google, unexpected results

### ISSUE THREAD

**Issue by tanel3203** [selenide/selenide#899]
## The problem
Selenide scrapes the first page of google results as expected. For second the scraped results show a mix of first and second page. When using non-headless mode, the results on the second page are actually different from first page in full.

## Details

*The results of the code example for first page:*
http://www.cs.otago.ac.nz/cosc348/alignments/Lecture04_StringSearch.pdf
http://www.ajer.org/papers/v6(11)/ZA0611216222.pdf
http://care.diabetesjournals.org/content/diacare/suppl/2016/08/12/39.9.1643.DC1/DC152171SupplementaryData.pdf
http://stephanus.tlg.uci.edu/helppdf/text.search.pdf
http://dimacs.rutgers.edu/BMC/TeacherMaterials/SuffixTrees.pdf
https://link.springer.com/content/pdf/10.1007/3-540-51324-8_38.pdf
https://www.toddington.com/wp-content/uploads/Facebook-Search-Strings-2.pdf
https://www.eiseverywhere.com/file_uploads/8a9341f04ab274ca10d993444d2002c0_4.ODonoghueVince.pdf
https://www.loggly.com/wp-content/uploads/2017/08/Loggly-Search-Cheat-Sheet.pdf
https://www.bu.edu/tech/files/2016/06/BW-How-to-Use-Wildcards-in-Searches.pdf

*the results for second page:*
http://www.cs.otago.ac.nz/cosc348/alignments/Lecture04_StringSearch.pdf
http://www.ajer.org/papers/v6(11)/ZA0611216222.pdf
http://care.diabetesjournals.org/content/diacare/suppl/2016/08/12/39.9.1643.DC1/DC152171SupplementaryData.pdf
http://stephanus.tlg.uci.edu/helppdf/text.search.pdf
http://dimacs.rutgers.edu/BMC/TeacherMaterials/SuffixTrees.pdf
https://link.springer.com/content/pdf/10.1007/3-540-51324-8_38.pdf
https://www.toddington.com/wp-content/uploads/Facebook-Search-Strings-2.pdf
https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/fundamentals/configuration/15_sy/fundamentals-15-sy-book/cf-cli-search.pdf
https://ieeexplore.ieee.org/iel5/4/22616/01052819.pdf
http://www.cs.princeton.edu/courses/archive/fall11/cos226/lectures/53SubstringSearch.pdf

Notice how the first 7/10 results are the same. It varies how many of them are the same.

## Tell us about your environment
* **Selenide Version:** 4.14.1
* **Chrome\Firefox\IE Version:** Firefox 64.0
* **Browser Driver Version:** selenide default
* **Selenium Version:** selenide default
* **OS Version:**  macos mojave 10.14

## Code To Reproduce Issue [ Good To Have ]

a simple scala template to reproduce:
````

import com.codeborne.selenide.{CollectionCondition, Configuration, ElementsCollection, Selenide}
import com.codeborne.selenide.Selenide.{$, $$}
import org.openqa.selenium.By


object GoogleMultipage extends App {

  val includeNonEmpyLinks: String = "string-length(@href)>3"
  val excludeCacheLinks: String = "not(@class='fl')]"

  Configuration.headless=false

  Selenide.open("http://www.google.com")


  // set Google search bar to a search string and press enter
  $(By.name("q"))
      .setValue("""
                  |"search"+"string" -"negative" filetype:pdf
                """.stripMargin)
      .pressEnter()

  // get google result page 1 (10 results per page)
  val res1 = $$(By.xpath(s"//div[@class='srg']//div[@class='g']//div//div[@class='rc']//div[@class='r']//a[$includeNonEmpyLinks and $excludeCacheLinks"))
      .shouldBe(CollectionCondition.size(10))

  for (j <- 0 to 9) println(res1.get(j).attr("href"))


  // scroll down and go to page 2
  $(By.xpath(s"//a[@aria-label='Page 2']")).scrollTo().click(1,1)


  // get google result page 2 (10 results per page)
  val res2 = $$(By.xpath(s"//div[@class='srg']//div[@class='g']//div//div[@class='rc']//div[@class='r']//a[$includeNonEmpyLinks and $excludeCacheLinks"))
      .shouldBe(CollectionCondition.size(10))

  for (j <- 0 to 9) println(res2.get(j).attr("href"))

}
````

**Comment by vinogradoff** [comment]
The thing is that after click you are changing from page1 to page2, but
starting the evaluate 10 result immediately. So 7 are gathered from page 1,
3 from page 2 in your case. How to avoid it? Basic idea: try to figure out
the moment when you are definitely on page 2. for example:
$(pageno).shouldHave(exactText("2"))

Or $(firsthit_from_page1).should(disappear)

Only after that - $$()...

**Comment by vinogradoff** [comment]
Yes, it is solved, except that if you have a construct of 10 items with
some layout, which are replaced with 10 items of identical layout (but
different texts) it is impossible to tell arbitrary of 10 items you see are
old or new. So you need some anchor on inhalt that get changed - like page
number or concrete text of an item. In your example the anchor was - 10
results which is same every time

>

**Comment by tanel3203** [comment]
After the click to second page, added the following:
````
  $(By.xpath(s"//td[@class='cur']")).shouldBe(Condition.exactText("2"))
````
Google changes the page link to text and adds class cur.
After this continued with the $$(..

Did one round of manual testing with the same browser. This seems to have fixed it.

Thanks @vinogradoff ! Closing this.
