### ISSUE TITLE
Issue with remote Webdriver (browserstack) and guice PO injection. Driver is closed right after it is opened

### ISSUE THREAD

**Issue by nikita-prikazchikov** [selenide/selenide#902]
## The problem
Selenide from version 5.0.0 is not able to work with browserstack using PO injected with Guice.
It seems to me that the issue is similar to  #629  
## Details
I see following error right after open() method call in the next code statement
java.lang.IllegalStateException: Webdriver has been closed. You need to call open(url) to open a browser again.
I tried all 5.* version of selenide and it fails the same way. But the 4.14.2 works fine with the same code. So it seems to me that the issue was brought with 5th version refactoring. 

The idea for test structure is to separate test steps definition from actual implementation because we want to support multiple versions of site. So Guice was used to inject all implementations of steps and PO implementation later. 

Logs tell that the quit command was sent to webdriver
[75146e78feb935bfce0116f270043ac326edaad3-selenium-logs.txt](https://github.com/selenide/selenide/files/2807887/75146e78feb935bfce0116f270043ac326edaad3-selenium-logs.txt)
13:20:58.804 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Done: [fetching logs for: browser]
13:20:58.804 DEBUG [14] org.openqa.selenium.remote.server.DriverServlet - Finished: POST /session/b26c891f-8a35-4dd7-a8a8-ccb4a5657a5f/log
13:20:58.840 DEBUG [14] org.openqa.selenium.remote.server.DriverServlet - Handling: DELETE /session/b26c891f-8a35-4dd7-a8a8-ccb4a5657a5f
13:20:58.840 INFO [14] org.openqa.selenium.remote.server.DriverServlet - Executing: [delete session: b26c891f-8a35-4dd7-a8a8-ccb4a5657a5f])
13:20:58.847 DEBUG [78] org.openqa.selenium.remote.RemoteWebDriver - Executing: quit [59ad4c107b3084e4ec9c60c429c50f58, quit {}]

But the actual quit exist only in AfterMethod and is not called yet.

## Tell us about your environment
* **Selenide Version:** 5.0.0 - 5.1.0
* **Chrome\Firefox\IE Version:** Chrome stable (71.0) 
* **Browser Driver Version:** no exactly set (3.141.5 in dependencies)
* **Selenium Version:** 3.14.0
* **OS Version:** Win10, Win8.1, Win7

## Code To Reproduce Issue
Source code with example can be found: https://github.com/nikita-prikazchikov/testgradle
Run LoginTest from loginTest to reproduce the issue after fixing browserstack credentials in AbstractTest class.

Quick reference:
```java
@Test
    @TmsLink("PRD_TC_023_Account_Sign In")
    @Description("Verify that user is able to sign in to his user account with  valid user credentials")
    private void loginTest() {
        st.home.openHomePage();
        st.home.openLoginForm();
        st.login.login(td.getUser());
    }

@Override
    @Step("Open Home page")
    public void openHomePage(){
        homePage.open();
        window.close();
    }

public void close(){
        if(root.exists()){
            close.click();
        }
    }```

**Comment by asolntsev** [comment]
@nikita-prikazchikov The problem is that you initialize selenide elements **before** opening a browser:

```java
public class HomePageDesktop {

    public SelenideElement signInLink    = $(".desktop-only .account-header-menu-item__signin-register-link");
    public SelenideElement myAccountLink = $(".account-header-menu-item__loggedin-user-link");

    public void open() {
        Selenide.open("https://www.neimanmarcus.com/en-us/");
    }
}
```

This is exactly the problem described in [Selenide 5.0.0 release notes](https://ru.selenide.org/2018/10/10/selenide-5.0.0/)

We intentionally disallow it in Selenide 5.0.0 because we believe it's a weird design. 
I recommend you to remove those public fields of type `SelenideElement`, and create public methods instead. Something like this:

```java
public class HomePageDesktop {
    public void open() {
        Selenide.open("https://www.neimanmarcus.com/en-us/");
    }
    public void signIn() {
        $(".desktop-only .account-header-menu-item__signin-register-link").click();
    }
    public void openMyAccount() {
        $(".account-header-menu-item__loggedin-user-link").click();
    }
}
```

See https://asolntsev.github.io/ru/2016/07/09/true-page-object/ :)

P.S. You actually don't need Guice :)
Your test object creates Guice by itself, and uses Guice for initializing its own fields. Much simpler would be to just initialize its own fields without Guice.
