### ISSUE TITLE
`disable-infobars` gets lost in Selenide

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#903]
## The problem
Selenide opens browser with an annoying "this browser is being controlled by automated software" infobar at the top, thought I add `disable-infobars` option. This option still works when I use pure Selenium (see code below). 

## Code To Reproduce Issue

```java
public class ChromeOptionsTest {
  WebDriver driver;

  @Test
  void viaOptions() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("disable-infobars");
    driver = new ChromeDriver(options);
    driver.navigate().to("https://google.com");      // NB! No infobar
    sleep(3000);
  }

  @Test
  void viaCapabilities() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("disable-infobars");
    DesiredCapabilities caps = DesiredCapabilities.chrome();
    caps.setCapability(ChromeOptions.CAPABILITY, options);
    driver = new ChromeDriver(caps);
    driver.navigate().to("https://google.com");      // NB! No infobar
    sleep(3000);
  }

  @Test
  void viaSelenide() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("disable-infobars");
    DesiredCapabilities caps = DesiredCapabilities.chrome();
    caps.setCapability(ChromeOptions.CAPABILITY, options);

    Configuration.browser = "chrome";
    Configuration.browserCapabilities = caps;

    open("https://google.com");      // NB! Infobar is visible! Like `disable-infobars` didn't work.
    sleep(3000);
  }

  @AfterEach
  void tearDown() {
    if (driver != null) driver.quit();
  }
}
```

**Comment by BorisOsipov** [comment]
I think it is duplicate of https://github.com/selenide/selenide/issues/676

**Comment by symonk** [comment]
hmm is this specifically only 'disable-infobars' or we have a more serious issue with options in general?

**Comment by BorisOsipov** [comment]
They removed `disable-infobars ` https://chromium.googlesource.com/chromium/src/+/d869ab3350d8ebd95222b4a47adf87ce3d3214b1

**Comment by asolntsev** [comment]
@BorisOsipov Could you remind what should we do with this information? :)

**Comment by Galadhen** [comment]
I think it means, that Chrome v75 was last with this flag and now we should use another flag) 
Or you want support earlier versions?

**Comment by dstekanov** [comment]
@asolntsev seems we can close this issue because we do not have `disable-infobars` anymore, for this purpose, if I'm not wrong, we have https://github.com/selenide/selenide/blob/master/src/main/java/com/codeborne/selenide/webdriver/ChromeDriverFactory.java#L42

**Comment by asolntsev** [comment]
@dstekanov Thanks for the remainder. Yes, we can close this issue because it was a duplicate of #676 anyway, and `disable-infobars` was removed.

**Comment by ksiv** [comment]
@asolntsev Thanks, friend! your code in the topic start is the best show-case I'v found so far on the issue.
Only you need to correct the name to "Capabilities are  lost in Selenide". 
Change "disable-infobars" to "start-maximized" and you ll see this one is lost as well.
One may link it to #676 but this one is better because it shows the difference :-) 
it is also clean no try to "merge"  options and other complication
