### ISSUE TITLE
Add ability to retrieve By variable from SelenideElement

### ISSUE THREAD

**Issue by SeleniumTestAB** [selenide/selenide#905]
## The problem
Ability to retrieve By locator from SelenideElement
## Details
The variable stored as SelenideElement should have ability to give it's locator (maybe as getElementLocator or getLocator). This addition would help e.g. extracting options from elements with tag "select".

## Tell us about your environment
* **Selenide Version:**
* **Chrome\Firefox\IE Version:**
* **Browser Driver Version:**
* **Selenium Version:**
* **OS Version:**

**Comment by asolntsev** [comment]
@SeleniumTestAB It's not always possible. For example, if SelenideElement is created like this:

```java
WebElement oldSchool = getWebDriver().findElement(By.id("id"));
SelenideElement se = $(oldSchool);
```

Instead, method `SelenideElement.toString()` returns the selector. It should be enough to understand which element it was. 

P.S. You can extract options from select just by executing 
```java
ElementsCollection options = $("select#id").findAll("option");
```
