### ISSUE TITLE
Configuration.timeout setting is invalid in open () method

### ISSUE THREAD

**Issue by btkukinom** [selenide/selenide#906]
I am using the following.
```
selenide: 4.14.0
geckodriver: 0.23.0
firefox: 60.3.0 ESR
```
In @ Before of the test, we specify the following.
```
Configuration.timeout = 1200000;
```

However, the value of `Configuration.timeout = 1200000;` is invalid when a timeout occurs in the open () method.

```
org.openqa.selenium.TimeoutException: Timeout loading page after 300000 ms
Build info: version: '3.14.0', revision: 'aacccce 0', time: '2018-08-02 T 20: 19: 58.91 Z'
System info: host: 'XXXX', ip: 'XXXX', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.21.1.el7.x86 _ 64', java .version: '11 .0.2 '
Driver info: org.openqa.selenium.firefox.FirefoxDriver
selenide.url: http://127.0.0.1:8082/XXXX
Moz: headless: false, moz: processID: 19333, moz: profile: capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 60.3.0, javascriptEnabled: true, moz: accessibilityChecks: false, moz: geckodriverVersion: /tmp/rust_mozprofile.c7blpK ..., moz: useNonSpecCompliantPointerOrigin: false, moz: webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-693.21.1.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
selenide.baseUrl: http: // localhost: 8080
```

I think that `pageLoad: 300000` is the cause.
Is the timeout setting of the open () method different from that specified by `Configuration.timeout`?

**Comment by symonk** [comment]
we are probably not polling often for checking page is loaded with open and I really don't know if we should or want to be.  I will look at this tonight to see.

**Comment by asolntsev** [comment]
@btkukinom @symonk `Configuration.timeout` is used when finding elements and checking conditions. For page load timeout, there is a separate setting. You can set it via webdriver api: `getWebDriver().manage().timeouts().pageLoadTimeout(30, SECONDS);`

**Comment by ncelerier** [comment]
Just in case anyone would know: getWebDriver() is available after you add this import:
import static com.codeborne.selenide.WebDriverRunner.getWebDriver;

**Comment by asolntsev** [comment]
@chipsenter Did you read the javadoc of this method? The same place where you see it's deprecated. 

```java
    /**
     * @param time The timeout value.
     * @param unit The unit of time.
     * @return A Timeouts interface.
     * @see <a href="https://www.w3.org/TR/webdriver/#set-timeouts">W3C WebDriver</a>
     * @see <a href="https://www.w3.org/TR/webdriver/#dfn-timeouts-configuration">W3C WebDriver</a>
     * @deprecated Use {@link #pageLoadTimeout(Duration)}
     *
     * Sets the amount of time to wait for a page load to complete before throwing an error.
     * If the timeout is negative, not null, or greater than 2e16 - 1, an error code with
     * invalid argument will be returned.
     */
    @Deprecated
    Timeouts pageLoadTimeout(long time, TimeUnit unit);
```

**Comment by chipsenter** [comment]
No just read the code :) 
`getWebDriver().manage().timeouts().pageLoadTimeout(10, TimeUnit.MINUTES);`

**Comment by chipsenter** [comment]
would this work instead > 
`getWebDriver().manage().timeouts().scriptTimeout(Duration.ofMinutes(10));`

**Comment by asolntsev** [comment]
yes, it should work.

**Comment by asolntsev** [comment]
@chipsenter Why you think this wait is not working? 
I think it works. I see the clear text "Timeout: 45 s." in your error message. It means Selenide had been waiting for 45 seconds before throwing this error. And the element hadn't became visible in 45 seconds. Probably you just need a bigger timeout?

**Comment by chipsenter** [comment]
I see that too and that part is OK,  only thing I don't understand is why
it's not checking the element even though it's visible in dom?

What I understand from this call,  selenide should wait until the element
is rendered, if it takes 1 sec or 30sec it will wait and click.?

Wish I could show you when it runs.?

**Comment by asolntsev** [comment]
@chipsenter Yes, Selenide waits (for 45 seconds) until the elements becomes visible.
But the problem is that the element doesn't get visible. It's **invisible**. Look at the error message:

Element **should be be visible**
Element: '<input **displayed:false**></input>'
**Actual value: hidden**

For some reason, Selenium webdriver thinks this element is not visible.

**Comment by chipsenter** [comment]
Sorry I created duplicates for this, but why does it work when I remove the Duration call and use a hard sleep instead ??

**Comment by asolntsev** [comment]
@chipsenter How can I answer your question? 
If you provide some instructions how I could reproduce the issue, I would be able to investigate it. But I cannot just answer all types of questions like "why my code isn't working?" without seeing the code...

Could you at least show your code with "hard sleep"?

**Comment by chipsenter** [comment]
Thought I posted code above ?. 

this is the method that will check if there is any elements in the table. 
line 1-5 is the most important one, when we enter this method and use selenide DurationOfSeconds its basically just waiting for 45sec and wont jump to the line 3 to give me the total checkboxes seen.

scenario 2.  if I comment out line 2 (hard sleep) and comment line 1 test will execute fine and work. So to me the 'shouldBe visible param is not working in this case. 

    public void checkFirstCheckboxInTableAndValidate() throws InterruptedException {
1.        $$(By.className("ag-checkbox-input")).get(0).shouldBe(visible, Duration.ofSeconds(45));
2. //        HelperMethods.wait(20000);  // HARD SLEEP 
3.       int checkboxes = $$(By.className("ag-checkbox-input")).size();
4.       System.out.println("Selenide can see: " + checkboxes + " in the table");
5.        for (int i = 12; i < checkboxes; i++){
6.           $$(By.className("ag-checkbox-input")).get(i).click();
            HelperMethods.wait(1000);
            if($(By.id("my-tasks-actions-mark-complete-btn")).isDisplayed()){
                System.out.println("Mark as completed button is visible and enabled");
                $(By.id("my-tasks-actions-mark-complete-btn")).shouldBe(visible).shouldBe(enabled);
                break;
            }
        }
    }

any suggestions for change above ?

**Comment by asolntsev** [comment]
Ahhaa!
And what you see in the logs after "Selenide can see: " in scenario 2?

**Comment by chipsenter** [comment]
[image: Screen Shot 2022-08-17 at 11.20.13 AM.png]
It took 8 sec to load the table this run, but Selenide waited for 45sec and
failed.
