### ISSUE TITLE
Problem with run tests in different browser than chrome (Selenide+TestNG+...)

### ISSUE THREAD

**Issue by testowysel** [selenide/selenide#908]
Hi,
I'm new here. I have problem with running tests with different browser than Chrome. I'm using Selenide+TestNG + some other stuff (see my pom.xml below). In example I've tried to open IE using:

System.setProperty("webdriver.ie.driver", "src\\test\\Resources\\IEDriverServer.exe");
 System.setProperty("selenide.browser", "Internet Explorer");

but it doesn't work.  Chrome browser  is opened.

Same situation with code:
  WebDriverManager.iedriver().setup();

I put this code in my abstract class with tag:

 @BeforeMethod
    public void before() 
{

//2nd try to open IE
        WebDriverManager.iedriver().setup();

// 1st  tryto open IE, now commented
        // System.setProperty("webdriver.ie.driver", "src\\test\\Resources\\IEDriverServer.exe");
        //  System.setProperty("selenide.browser", "Internet Explorer");

    }

TestCases which I run extends this abstract class. I've also tried to put this code directly in the TC class. Also doesn't work. 

Still got (TC is run but all the time in Chrome browser):

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
lut 06, 2019 10:25:29 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
lut 06, 2019 10:25:31 AM com.codeborne.selenide.drivercommands.LazyDriver getAndCheckWebDriver
**INFO: No webdriver is bound to current thread: 1 - let's create a new webdriver**
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 39432
Only local connections are allowed.
lut 06, 2019 10:25:35 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
lut 06, 2019 10:25:36 AM com.codeborne.selenide.webdriver.WebDriverFactory logBrowserVersion
 create a new webdriver
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 39432
Only local connections are allowed.
lut 06, 2019 10:25:35 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
lut 06, 2019 10:25:36 AM com.codeborne.selenide.webdriver.WebDriverFactory logBrowserVersion
INFO: BrowserName=chrome Version=71.0.3578.98 Platform=XP
lut 06, 2019 10:25:36 AM com.codeborne.selenide.webdriver.WebDriverFactory createWebDriver
INFO: Selenide v. 5.1.0
lut 06, 2019 10:25:36 AM com.codeborne.selenide.webdriver.WebDriverFactory logSeleniumInfo
INFO: Selenium WebDriver v. 3.141.59 build time: 2018-11-14T08:17:03
lut 06, 2019 10:25:36 AM com.codeborne.selenide.drivercommands.CreateDriverCommand createDriver
...

my pom.xml:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.abb</groupId>
    <artifactId>gcm</artifactId>
    <version>1.0-SNAPSHOT</version>

    <profiles>

        <profile>
            <id>Regression</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>3.0.0-M3</version>
                            <configuration>
                                <suiteXmlFiles>
                                    <suiteXmlFile>testRun.xml</suiteXmlFile>
                                </suiteXmlFiles>
                            </configuration>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>

        
    </profiles>

    <properties>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>

    <dependencies>

        
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>5.1.0</version>
        </dependency>

        <dependency>
            <groupId>net.sourceforge.jexcelapi</groupId>
            <artifactId>jxl</artifactId>
            <version>2.6.12</version>
        </dependency>

        
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>4.2</version>
        </dependency>

        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.7</version>
        </dependency>
        

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>6.14.2</version>
            <scope>compile</scope>
        </dependency>

        
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>3.2.0</version>
        </dependency>

    </dependencies>

</project>

I would be grateful if You can advice me how to fix this. I would like to have possibility to use IE or Firefox too.

Regards 
Tomes

**Comment by evgeny-tumashchick** [comment]
Hi. To set needed browser type I use

import com.codeborne.selenide.Configuration
Configuration.browser = "firefox"

**In your case use "ie"**

Following documentation description for this Selenide property
 /**
   * Which browser to use.
   * Can be configured either programmatically or by system property "-Dselenide.browser=ie".
   * Supported values: "chrome", "firefox", "legacy_firefox", "ie", "htmlunit", "phantomjs", "opera", "safari", "edge", "jbrowser"
   * <br>
   * Default value: "chrome"
   */
  public static String browser = defaults.browser();

**Comment by osyanin** [comment]
And Selenide handles webdriver automatically.

**Comment by testowysel** [comment]
Cool, it works. Checked with IE (works very slowly but works) , Firefox and Edge Thanks for quick response.

Last question. How set maximized window.
Now I have:
  Configuration.startMaximized = true;


![window](https://user-images.githubusercontent.com/47357145/52336838-44907900-2a06-11e9-8915-a0b90c835513.png)


Regards 
Tomes

**Comment by symonk** [comment]
`WebDriverManager.iedriver().setup();` 

The above does nothing for the driver instantiation, this just directs webdriver manager to aquire the binary if necessary.  you simple want to set the `Configuration.browser = "ie";`

Also: be careful of using slashes, try to use `File.separator();` instead for cross platform execution, for maven try to put versions inside your <properties> and reference them using `${property.name}` instead too.

`Configuration.startMaximized` should help you full screen, what operating system are you running on?  as for slow IE this is a problem on the side of IE, the support is lackluster at best
