### ISSUE TITLE
Opening a blank page.

### ISSUE THREAD

**Issue by tamasmartin** [selenide/selenide#914]
## Question
I have just started using Selenide. I have a question: is it possible to open a blank page in Selenide with the open(String url) method?
Thanks.

**Comment by asolntsev** [comment]
Hi Tamas.
Welcome to the club! :)

I am not sure, probably, something like open("about:blank") could work.

But why do you need it? Typically nobody needs to test the empty page.

**Comment by tamasmartin** [comment]
Thank you for your answer, that does not work, I tried that first. I need it in the before method to avoid some errors. When the previous test case ends up on a page with a specific URL, the next step will not reload the page if the URL is the same. So I tried to load a blank page in the before step.
What I could do is creating an own WebDriver instance and pass it to Selenide. The simple open() way would have been more convenient.

**Comment by vinogradoff** [comment]
Selenide.reload(); ?

**Comment by asolntsev** [comment]
Yes, we also open an empty page before every test. It's a good idea. We
created our own empty page which also clears cookies, localStorage etc.

How creating your own webdriver instance can help?

**Comment by asolntsev** [comment]
fixed in Selenide 5.2.3
