### ISSUE TITLE
Driver session on BrowserStack is not closed on Selenide >5.0.1

### ISSUE THREAD

**Issue by monterson** [selenide/selenide#917]
## The problem
Hi, I have a problem with the BrowserStack & Selenide >5.0.1.
It looks like the session is not correctly closed.

## Details
Everytime when I start the tests (JUnit4) there is a timeout on browserstack. It happens on all browsers. Everything worked fine on Selenide 5.0.1. 

![image](https://user-images.githubusercontent.com/23195039/54020770-dec31880-418e-11e9-851a-9ca50c0225f4.png)
![image](https://user-images.githubusercontent.com/23195039/54020814-f7cbc980-418e-11e9-8ec9-49febae7988b.png)

## Tell us about your environment
* **Selenide Version:** 5.1.0, 5.2.0
* **Chrome\Firefox\IE Version:** Remote WebDriver, all browsers
* **Selenium Version:** 3.14.0
* **OS Version:** Win10

## Code To Reproduce Issue [ Good To Have ]
I initialize remote driver with the code:
` WebDriver driver = new RemoteWebDriver(new URL("http://" + username + ":" + accessKey + "@" + ConfigReader.config.get("server") + "/wd/hub"), capabilities);
        WebDriverRunner.setWebDriver(driver);
        WebDriverRunner.getWebDriver().manage().window().maximize();`

after tests I close driver 
`  @After
    public void tearDownBrowser() {
        WebDriverRunner.closeWebDriver();
    }`

**Comment by vinogradoff** [comment]
Please try with just


Configuration.remote="http://" + username + ":" + accessKey + "@" +
ConfigReader.config.get("server") + "/wd/hub”;


instead, settings capabilites over System.properties

https://selenide.org/2016/12/30/selenide-4.2/

**Comment by monterson** [comment]
Hi, thanks for quick answer. 
I changed it but unfortunately it did not help. I still get the timeouts on browserstack. Test is executed but session is not closed. I believe something implemented in Selenide 5.1.0 causes this problem or my code is somehow not compatible with this version.

**Comment by vinogradoff** [comment]
Now you dont create the driver yourself, right?

Then yes, actually Selenide must have closed it at the end. If you use
setWebDriver still - then it is more difficult to tell what went wrong)

**Comment by monterson** [comment]
Ah! 
You are right! Thank you @vinogradoff . I changed wrong initialization method. Now everything is fine. You can close this ticket.
