### ISSUE TITLE
Selenide 5.2.1 cannot download ChromeDriver 73.0.3683.68  on Windows 10 for Chrome v. 73.0.3683.75

### ISSUE THREAD

**Issue by violetastegaru** [selenide/selenide#920]
## The problem
While using the latest release for Selenide 5.2.1, we cannot run our tests on Windows 10 with Chrome 73.0.xxx since we get the following error:
Mar 14, 2019 12:48:10 PM com.codeborne.selenide.drivercommands.LazyDriver getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 1 - let's create a new webdriver
[03-14 12:48:10][main] INFO  io.github.bonigarcia.wdm.WebDriverManager - Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
[03-14 12:48:11][main] INFO  io.github.bonigarcia.wdm.WebDriverManager - Latest version of chromedriver is 74.0.3729.6
[03-14 12:48:11][main] INFO  io.github.bonigarcia.wdm.Downloader - Using binary driver previously downloaded
[03-14 12:48:11][main] INFO  io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\viodia\.m2\repository\webdriver\chromedriver\win32\74.0.3729.6\chromedriver.exe
Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 1266
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

Failed to instantiate [com.codeborne.selenide.SelenideDriver]: Factory method 'getBrowser' threw exception; nested exception is org.openqa.selenium.SessionNotCreatedException: session not created: **This version of ChromeDriver only supports Chrome version 74**
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Windows NT 10.0.16299 x86_64) (WARNING: The server did not provide any stacktrace information)

## Details
We need to block the browser version to 73 since this is the official release available for Chrome:
WebDriverManager.chromedriver().version("73.0");
Everyone needs to upgrade the browser version.

## Tell us about your environment
* **Selenide Version: 5.2.1
* **Chrome\Firefox\IE Version: 73.0.3683.75
* **Browser Driver Version:  ChromeDriver 73.0.3683.68  - needed
* **Selenium Version:3.141.59
* **OS Version: Windows 10

## Code To Reproduce Issue [ Good To Have ]
public WebDriver createDriver(WebdriverProperties driverProperties) throws Exception {
        baseUrl = "";
        browser = TestContext.getBrowser();
        //WebDriverManager.chromedriver().version("73.0");
        open("about:blank");
        return WebDriverRunner.getWebDriver();
    }

**Comment by asolntsev** [comment]
Have you tried to clear WDM preferences?

* For Windows: https://twitter.com/Anton94569401/status/1105776214940270594?s=19
* For Linux: https://twitter.com/jselenide/status/1105757355017490432?s=19

**Comment by violetastegaru** [comment]
Hi Andrei, 

Thank you very much for sharing the fix with us. 
I have cleaned up the WDM preferences and it works as expected without the workaround. 

Thank you,
Vio
