### ISSUE TITLE
getCurrentUrl

### ISSUE THREAD

**Issue by wengxiaofeng** [selenide/selenide#921]
can not get current url
selenium webdriver support it

public interface WebDriver extends SearchContext {
    String getCurrentUrl();

**Comment by evgeny-tumashchick** [comment]
Use
Selenide.open( your url here  )
Full description here:
com.codeborne.selenide.Selenide#open(java.lang.String)

**Comment by evgeny-tumashchick** [comment]
WebDriverRunner.url()

Full description here
com.codeborne.selenide.WebDriverRunner#url

**Comment by Kotaro254195** [comment]
I owe you
