### ISSUE TITLE
java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first.

### ISSUE THREAD

**Issue by zutshishweta** [selenide/selenide#922]
## The problem
I am trying to group my selenide tests using TestNG annotation and adding the groups in  testng.xml. But I am getting the following exception while running it:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mar 18, 2019 4:32:43 PM com.codeborne.selenide.drivercommands.LazyDriver getAndCheckWebDriver
INFO: No webdriver is bound to current thread: 1 - let's create a new webdriver
java.lang.IllegalStateException: No webdriver is bound to current thread: 1. You need to call open(url) first.
```

## Details
I am running the test on chrome, seems to have the correct project structure, I think. Not sure, why am I getting this exception.

## Tell us about your environment
* **Selenide Version:** 5.0.1
* **TestNG version:** 6.14.3
* **OS:** MAC

## Code To Reproduce Issue [ Good To Have ]
Here's my test/project structure:

### loginPage

```java
public class LoginPage extends BasePage {
  private final SelenideElement el1 = $(...);
  public static LoginPage open(){
    Selenide.open("url");
    return new LoginPage();
  }

  public void set(){
    el1.setValue("value");} ...
  }
```

### LoginTest

```java
public class LoginTest extends BaseTest {
  @BeforeMethod
  public void initTestData(){ ....}

  @Test(groups={"smoke"})
  public void testLogin() {
    var loginpage = LoginPage.open();
    .....
  }
}
```

### BaseTest

```java
public class BaseTest {
  @BeforeSuite ...
  @BeforeMethod ....
  @AfterMethod ...
}
```

**Comment by vinogradoff** [comment]
It is not an exception, it is a warning telling you that messages from
third party libraries won't be logged. You can ignore it for now

**Comment by Lewka** [comment]
Try to run your code in debug, add a breakpoint in Navigator class, in `navigateTo` method, in `catch` blocks, and u'll see actual reason of failing.

**Comment by g-one** [comment]
I'm getting the same error. TestNG xml works without groups but when we add groups then we are getting the following error:

`java.lang.IllegalStateException: No webdriver is bound to current thread: 13. You need to call open(url) first.
        at com.codeborne.selenide.drivercommands.LazyDriver.getWebDriver(LazyDriver.java:67)
        at com.codeborne.selenide.impl.ElementFinder.getSearchContext(ElementFinder.java:86)
        at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:74)
        at com.codeborne.selenide.commands.ToWebElement.execute(ToWebElement.java:11)
        at com.codeborne.selenide.commands.ToWebElement.execute(ToWebElement.java:8)
        at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
        at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:57)
        at com.sun.proxy.$Proxy16.toWebElement(Unknown Source)
`

**Comment by Lewka** [comment]
@g-one have you tried to run in debug mode?

**Comment by marisabell-PD** [comment]
@Lewka Any update ? Facing the same issue when run in parallel using testng xml

<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
    <suite name="Parallel Tests" parallel="tests" thread-count="1" verbose="10">
<test name="Chrome Tests">
    <parameter name="browserName" value="chrome"/>
    <parameter name="version" value="74.0"/>

    <packages>
        <package name="com.*"/
    </packages>
</test> 

<test name="Firefox Tests">
    <parameter name="browserName" value="firefox"/>
    <packages>
        <package name="com.*"/
    </packages>
</test> 
</suite>

public class DriverBase {
    private RemoteWebDriver driver;
    @BeforeClass(alwaysRun = true)
    @Epic("Regression tests")
    @Parameters(value = {"browserName", "version"})
    public void setUp(@Optional String browserName, @Optional String version) throws Exception {
        Configuration.browser = "com.core.SelenoidWebDriverProvider";
    }
    @AfterClass
    public void tearDown() {
        if (driver != null) {
            driver.quit();
            driver = null;
        }
    }



public class SelenoidWebDriverProvider implements WebDriverProvider {
    @Override
    public WebDriver createDriver(DesiredCapabilities capabilities) {
        capabilities.setBrowserName("chrome");
        capabilities.setVersion("");
        capabilities.setCapability("enableVNC", true);
        capabilities.setCapability("enableVideo", false);
        try {
            RemoteWebDriver driver = new RemoteWebDriver(
                    URI.create("http://localhost:4444/wd/hub").toURL(),
                    capabilities
            );
            driver.manage().window().maximize();
            return driver;
        } catch (MalformedURLException e) {
            throw new RuntimeException(e);
        }
    }
}



java.lang.IllegalStateException: No webdriver is bound to current thread: 16. You need to call open(url) first.

	at com.codeborne.selenide.drivercommands.LazyDriver.getWebDriver(LazyDriver.java:67)
	at com.codeborne.selenide.impl.ElementFinder.getSearchContext(ElementFinder.java:86)
	at com.codeborne.selenide.impl.ElementFinder.getWebElement(ElementFinder.java:74)
	at com.codeborne.selenide.commands.Hover.execute(Hover.java:12)
	at com.codeborne.selenide.commands.Hover.execute(Hover.java:9)
	at com.codeborne.selenide.commands.Commands.execute(Commands.java:144)
	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:99)
	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65)
	at com.sun.proxy.$Proxy29.hover(Unknown Source)

**Comment by Lewka** [comment]
@marisabell-PD could u run with my custom version? I just added more logs to Selenide. [link to download](https://gofile.io/?c=SAagxQ)

**Comment by asolntsev** [comment]
@Lewka Why do you include both "testng" and "junit-jupiter-engine" in your pom.xml?
It's typically nonsense to use both of them together.

**Comment by asolntsev** [comment]
@zutshishweta @g-one May I ask you to create a sample project that I could run to reproduce the problem? Otherwise it's just impossible for me to investigate your problem. I am pretty sure it's caused by initialisation order of your classes/tests/page objects. 

Then I will reopen the issue.

**Comment by Lewka** [comment]
@asolntsev what? I didn't post any code

**Comment by asolntsev** [comment]
@lewka see comment above: https://github.com/selenide/selenide/issues/922#issuecomment-499840187

There is a "link to download" with pom.xml

**Comment by Lewka** [comment]
@asolntsev no idea why, cause I've just added some logs to `Selenide` and builded it with `Gradle`

**Comment by Lewka** [comment]
@asolntsev If u open selenide-5.2.1 pom of your, u'll see `testng` as well

**Comment by asolntsev** [comment]
@Lewka Yes, it's ok. Selenide  Because Selenide needs both JUnit and TestNG _for compilation_.
And we also need to test both "Selenide+JUnit" and "Selenide+TestNG" combinations because Selenide is a testing framework.

But in normal projects, you either use JUnit or TestNG, not both of them. 

> If u open selenide-5.2.1 pom of your, u'll see testng as well

**Comment by Lewka** [comment]
@asolntsev 

> But in normal projects, you either use JUnit or TestNG, not both of them.
I know that, what I posted was just modified version of `Selenide`

**Comment by georgerobertkplivi** [comment]
I have been trying several days to run my tests developed with selenide in docker, but i cannot get any success and I could not fine anything on the internet to assist with running tests in docker using selenide. Please help.
`import org.junit.Before;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;

import static com.codeborne.selenide.Selenide.open;

public class BaseTest {

    final String baseURL = "https://www.amazon.in/";

    @Before
    public void setUp() throws MalformedURLException {

        ChromeOptions options = new ChromeOptions();
        URL remoteURL = new URL("http://localhost:4444/wd/hub");
        WebDriver driver = new RemoteWebDriver(remoteURL, options);
        driver.get(baseURL);

//        open(baseURL);
    }
}`

**Comment by asolntsev** [comment]
Let's continue discussion at https://github.com/selenide/selenide/discussions/2004
