### ISSUE TITLE
Migrate from jul to slf4j

### ISSUE THREAD

**Issue by gschukin** [selenide/selenide#923]
## The problem
Migrate to slf4j from java.util.logging as it is almost defacto api for logging
## Details
Currently selenide using jul for logging, but also have a dependency on webdrivermanager that use slf4j. It would be nice to unify and have one logging configuration entry point without the need to play with jul bridge and java.util.logging.config.file configuration.

## Tell us about your environment
* **Selenide Version:** 5.2.2
* **Chrome\Firefox\IE Version:** NA
* **Browser Driver Version:** NA
* **Selenium Version:** NA
* **OS Version:** NA

**Comment by asolntsev** [comment]
Sounds reasonable.
Though, WebDriverManager is optional, and there can be users who don't want to use SLF4J nor WDM. But it's rather theoretical risk.

**Comment by gschukin** [comment]
browsermob also use slf4j

I can make PR if you'd like to

**Comment by asolntsev** [comment]
See PR https://github.com/selenide/selenide/pull/926

**Comment by asolntsev** [comment]
Implemented in PR #926. Will be released in Selenide 5.5.0 soon.
