### ISSUE TITLE
Change applyNull method to not final method

### ISSUE THREAD

**Issue by Lewka** [selenide/selenide#930]
## The problem
Hi. Could you change method 
```
public final boolean applyNull()
```
In `Condtion` class to not final method? Cause we've faced situation, when element doesn't exist on the page, and I wanna check something else in my custom condition, and now all I can do, it's just pass an argument `true` to `Condition` constructor, and then i'll get a `null` instead of error. But it's not what we want.
We want to check another condition. smt like this 
```
public boolean applyNull() {
 return true;
}
```

**Comment by asolntsev** [comment]
@Lewka Yes, we could make method `applyNull()` non-final. 
But let me first ask why passing `true` to `Condition` constructor is not enough? It was the initial plan, and haven't understood why it doesn't work for you.

**Comment by Lewka** [comment]
@asolntsev я уже точно не смогу вспомнить, т.к. больше не нахожусь на том проекте. Проблема вроде была такая, что если нам приходит null элемент, то я хочу проверить отличное от метода apply условие, как это реализовано например в проверке размера коллекции элементов. 

```

А сейчас, там прописано такое поведение, что если элемент null, и мы передали true в условии, то он просто вернет null, без проверки условия.
```   
if (element == null) {
      if (!check.applyNull()) {
        throw createElementNotFoundError(check, lastError);
      }
}
```

**Comment by asolntsev** [comment]
@Lewka А какое условие в принципе возможно проверить, если элемент не был найден? Что тут ещё проверять?

**Comment by Lewka** [comment]
@asolntsev то что мы передаем в условие. У нас было условие, которое проверяет, если элемент есть на странице, на нем мы ищем child элемент, берем текст оттуда, и проверяем с тем что мы передали в условие. Если нету parent, т.е. он null, тогда проверить равно ли 0-лю то что мы передали в условие.

**Comment by asolntsev** [comment]
@Lewka Так это ж то же самое, что в случае 0 и не 0 использовать разные кондишены.

**Comment by Lewka** [comment]
@asolntsev откуда нам знать будет ли элемент на странице, при некоторых условиях его не будет. Нам нужно отталкиваться от того, представлен ли элемент на странице или нет. Если да проверяем одно, если нет, проверяем другое.

**Comment by asolntsev** [comment]
@Lewka Вообще это как-то странно: вы ведь должны заранее знать поведение приложения. Тест - это же спецификация приложения. Если parent должен существовать - проверяйте, что существует. Если не должен - проверяйте, что не существует. Тест не должен угадывать. Так ведь?

**Comment by Lewka** [comment]
@asolntsev все верно.это и есть поведение приложения такое, мы его и проверяем.там не только нужно проверить что он существует, но и еще что внутри него содержится. можно было бы это обернуть в несколько условий, но зачем? когда можно написать одно условие, которое выполняет то то нужно.

**Comment by asolntsev** [comment]
@Lewka Нет, всё равно не понимаю. 
Сделайте один Condition для тех случаев, когда parent должен существовать, и другой Condition для тех случаев, когда не должен. Всё просто.

**Comment by Lewka** [comment]
@asolntsev если только это разбить на 2 разных метода, и 2 разных condition. Даже если вы не согласны с нашим подходом, что помешает сделать метод не `final`?

**Comment by asolntsev** [comment]
@Lewka Да, и было бы правильно разбить на 2 разных Condition. 
Поймите меня правильно: чем больше вещей я делаю не-final, тем больше создаю возможностей для всевозможных ошибок, которые мне же потом придётся разруливать. Я по своему богатому опыту уже предвижу, чем может аукнуться ваш вариант. Я каждый день читаю кучу жалоб типа "у меня какая-то магия происходит, не знаю как повторить, но иногда тесты падают."

Ну ладно, дадим шанс. В этом конкретном случае изменение вроде не такое уж страшное. Посмотрим. :)

Done in https://github.com/selenide/selenide/commit/219670b6ed0080ab1fe3e74af416b11d0d143cd0
