### ISSUE TITLE
Eliminate dependencies clash (enforcer)

### ISSUE THREAD

**Issue by ravxz** [selenide/selenide#932]
## The problem
We use Selenide libraries in our maven project and apply Enforcer plugin to check for dependencies versions clashes. Selenide artifacts has such issues and we have to calculate dependency exclusions each time new Selenide release is issued.

## Details
Below is extract from our pom.xml for Selenide dependencies inclusion:

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.codeborne</groupId>
                <artifactId>selenide</artifactId>
                <version>4.14.0</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.fasterxml.jackson.core</groupId>
                        <artifactId>jackson-annotations</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-all</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.squareup.okio</groupId>
                        <artifactId>okio</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.commons</groupId>
                        <artifactId>commons-lang3</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>4.0.51.Final</version>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>25.0-jre</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okio</groupId>
                <artifactId>okio</artifactId>
                <version>1.14.1</version>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.7</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>2.8.9</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
    </dependencies>

**Comment by rosolko** [comment]
@ravxz Didn't catch the issue in general. What is your problem? Which solution do you waiting for at the final?

**Comment by ravxz** [comment]
@rosolko, the problem is that Selenide depends (transitively) on maven artifacts with the same groupId+artifactId but with different versions. Maven Enforcer plugin fails our build when it finds such dependency versions collisions. To sort this out we figure out exclusions to dependency section for Selenide for each its new release. That work could be done by Selenide project automatically.

**Comment by rosolko** [comment]
@ravxz Sound like it isn't a selenide problem. Any of artifacts can contain overridden by you dependency. Look like it's plugin problem.

**Comment by ravxz** [comment]
@rosolko , actually Selenide uses maven libraries which use different versions of other libraries. That could be issue in future. In maven project it's possible to exclude clashed versions of maven artifacts in dependency/exclusions tag.  For gradle there are similar plugins.
