### ISSUE TITLE
Starting with Selenium 3.141.59, org.openqa.selenium.internal breaks since the package name changed for WrapsElement

### ISSUE THREAD

**Issue by Drenjy** [selenide/selenide#933]
## The problem
Starting with Selenium 3.141.59, code breaks since the package name changed for WrapsElement and Locatable from org.openqa.selenium.internal to org.openqa.selenium. The interface org.openqa.selenium.internal.WrapsElement was left in the code base, and thus, existing imports are happy.

Consider moving imports org.openqa.selenium.internal.WrapsElement to avoid confusion.
![not imported depends](https://user-images.githubusercontent.com/1714340/56739255-eb1f2700-6776-11e9-9ae0-908cdb196ed1.jpg)

## Details
selenide-5.2.2

**Comment by asolntsev** [comment]
I don't understand if it actually causes problems, or is it just a warning? We run tests on Selenium 3.141.59 and Selenide 5.2.2, and everything works well. 

Yes, sure, we will remove usages of deprecated classes. We left them for some time to keep backward compatibility (for those who needs to use previous Selenium versions).

**Comment by VatslauX** [comment]
Compilation failed

**Comment by rosolko** [comment]
@Drenjy @VatslauX As said @asolntsev you build tool resolve dependency and it's looks like selenium dependency is outdated or invalid and it's not a selenide problem. Inspect your dependencies and exclude outdated selenium dependency for library that it's going from.
