### ISSUE TITLE
Cannot use the same driver for SeleniumWebDriver and Selenide in single Framework.

### ISSUE THREAD

**Issue by jimmyjavid** [selenide/selenide#936]
## In my existing framework I use driver.get("") of selenium WebDriver to open a browser and I am looking to integrate selenide in my existing framework.
       I use the following code :         
                System.setProperty("webdriver.gecko.driver", "/Applications/geckodriver");
		WebDriver driver = new FirefoxDriver();
		webdriverContainer.setWebDriver(driver);
		Selenide.open("https://www.google.com");

to set up a driver so that same driver is used to work with the webDriver element as well as to work with selenide element...But to my surprise I found two Browsers getting open one providing the driver for web driver and another for selenide.

So I wanted to know is there a way where I can use driver interchangeably for selenide and Selenium in one Framework.

**Comment by rosolko** [comment]
Provide more information in description, what and how do you trying to do and what expected behavior.

**Comment by jimmyjavid** [comment]
@rosolko  actually the problem that I am facing here is the driver returned by driver.get("") of selenium cannot work with selenide. And if I use open of selenide it only works with selenide commands.

and when I try to set webDriver of Selenide using 
webdriverContainer.setWebDriver(Seleniumdriver); 
before writing Selenide.open()...so that same driver could be used for both in one single browser.
 It does not allow doing so instead open two browsers ------one working with seleniumDriver and another working with Selenide driver.

**Comment by thasherwin** [comment]
Please use WebDriverRunner.setWebDriver(driver)

**Comment by rosolko** [comment]
It is logical that different tools operate with different objects.
`WebDriverRunner.setWebDriver(driver)` allows you to work with selenium webdriver using selenide.
And `WebDriverRunner.getWebDriver()` allows you to get selenium webdriver instance fro, selenide.
