### ISSUE TITLE
Misleading chromeoptions.args documentation

### ISSUE THREAD

**Issue by harshtuna** [selenide/selenide#938]
## The problem
Configuration javadoc suggests wrong chromeoptions.args format

## Details
https://selenide.org/javadoc/current/com/codeborne/selenide/Configuration.html

> chromeoptions.args - Sets the arguments for chrome options, parameters are comma separated If comma is a part of the value, use double quotes around the argument Non-official list of parameters can be found at https://peter.sh/experiments/chromium-command-line-switches/ Example: --no-sandbox,--disable-3d-apis,"--user-agent=Firefox 45, Mozilla"

Comma separated list does not work with chromedriver 74. Cromedriver for win32 supports **space** as separator, chromedriver for linux does not allow separators, each option should be a separate element in the args array

## Tell us about your environment
* **Selenide Version:** 5.2.3
* **Chrome\Firefox\IE Version:** Chrome 74.x
* **Browser Driver Version:** 74.0.3729.6
* **Selenium Version:** -
* **OS Version:** Windows 10, RHEL 7

## Code To Reproduce Issue [ Good To Have ]
`chromeoptions.args=--incognito,--disable-extensions`

**Comment by BorisOsipov** [comment]
cc @vinogradoff as I know you are a fan of this way of passing chrome options

**Comment by BorisOsipov** [comment]
>Cromedriver for win32 supports space as separator, chromedriver for linux does not allow separators, each option should be a separate element in the args array

@harshtuna I will be nice to see some link to chromedriver docs/code as proof. Can you share your findings?

**Comment by harshtuna** [comment]
chromedriver docs on this subject are missing.
Actually Selenide is properly parsing chromeoptions.args, false alarm, sorry
Odd win32 behavior is in chromedriver - they've got non-documented feature which injects dev tool extension even if **--disable-extensions** specified

**Comment by harshtuna** [comment]
chromeoptions.args format in Selenide Javadoc is **correct**

**Comment by harshtuna** [comment]
Chromedriver disable extension issue in SO https://stackoverflow.com/questions/56273279/how-to-disable-all-chrome-extensions-using-chromedriver
