### ISSUE TITLE
Selenide-thrown exception not catched

### ISSUE THREAD

**Issue by theolice** [selenide/selenide#939]
## The problem
When Selenide searches for an element and that element isn't found, the resulting exception isn't caught by a try/catch. Instead of entering a try/catch it crashes/stops the whole running instance.

## Details
I'm attempting to use Selenide to automate multiple consecutive actions. Some of those actions should be able to run even though a previous action/check failed. In example given below: not being able to find `foo` at Google page shouldn't stop the search of `bar` at DuckDuckGo.

## Tell us about your environment
* **Selenide Version:** 5.2.3
* **Chrome\Firefox\IE Version:** Both Chrome
* **Browser Driver Version:** 74.0.3729.6
* **Selenium Version:** 3.141.59
* **OS Version:** Windows 10

## Code To Reproduce Issue
```java
public static void main(String[] args) throws Exception {
    try {
        setUp(args);;
        openGoogle();
        openDDG();
    } catch (Exception e) {
    	System.out.println(e.toString());
    }
}

private static void setUp(String[] args) {
    Configuration.startMaximized = true;
    Configuration.timeout = 1000;
    Configuration.browser = Browsers.CHROME;
}

private static void openGoogle() {
    try {
        open("https://www.google.com/");
        $(By.xpath("//h3[contains(text(), 'foo')]")).should(exist).shouldBe(visible);
    } catch (Exception e) {
        screenshot("error");
        System.out.println(e.toString());
        throw e;
    }
}

private static void openDDG() {
    try {
        open("https://duckduckgo.com/");
        $(By.xpath("//h3[contains(text(), 'bar')]")).should(exist).shouldBe(visible);
    } catch (Exception e) {
        screenshot("error");
        System.out.println(e.toString());
        throw e;
    }
}
```

**Comment by BorisOsipov** [comment]
@theolice you have to catch UIAssertionError error. It inherits from
java.lang.Error -> java.lang.AssertionError -> com.codeborne.selenide.ex.UIAssertionError

so you can't catch it by `catch (Exception e) {`

**Comment by BorisOsipov** [comment]
e.g.
```
try {
        setUp(args);;
        openGoogle();
        openDDG();
    } catch (UIAssertionError e) {
    	System.out.println(e.toString());
    }
```

**Comment by theolice** [comment]
Thanks! This has indeed fixed my problem 😃

**Comment by asolntsev** [comment]
@theolice Just a reminder: as a rule, it's not needed to catch exceptions in tests. 
In the examples you provided above, it doesn't have any sense. If you remove "catch" block, nothing really changes. Selenide takes screenshot and reports a detailed error message out-of-the-box.
