### ISSUE TITLE
Method uploadFile() doesn't work for multiple files if parent tag `form` hasn't existed

### ISSUE THREAD

**Issue by dilook** [selenide/selenide#943]
## The problem
Method `uploadFile()` throw `NoSuchElementException`
[stacktrace.txt](https://github.com/selenide/selenide/files/3237628/stacktrace.txt)
 for multiple files uploading on page with input field, but without parent tag form

## Tell us about your environment
* **Selenide Version: 4.13.0**
* **Chrome Version: 74.0.3729.169**
* **Browser Driver Version: chromedriver 74.0.3729.6**
* **OS Version: Windows 7**

## Code To Reproduce Issue
```java
Selenide.open("file:///C:/multiple_upload.html")
File tempFile = Files.createTempFile(null, null).toFile();
$("#real-input").uploadFile(tempFile, tempFile)
```
html-page
```html
<!DOCTYPE HTML>
<html>
	<head>
	  <meta charset="utf-8">
	</head>
	<body>
		<div class="input-container">
		  <input type="file" id="real-input" multiple= "">
		</div>
	</body>
</html>
```

**Comment by asolntsev** [comment]
@dilook It seems reasonable to me. All inputs should be inside `<form>`.

**Comment by BorisOsipov** [comment]
Hello @dilook,

1) It will be nice if you make some full example (code and corresponding html) to reproduce issue. As I see from your stacktrace your issue that element just was not found in dom.
2) Underhood `$("#real-input").uploadFile(tempFile, tempFile)` doesn't do some magic - it uses usual selenium methods to upload, so it might be selenium issue then

**Comment by dilook** [comment]
@BorisOsipov 
1. It's synthetic example, this real [page.zip](https://github.com/selenide/selenide/files/3241301/page.zip)
2. Selenium method uploadFile() works good for multiple files. Parent form element searching realized in
[com.codeborne.selenide.commands.UploadFile](https://github.com/selenide/selenide/blob/1841ef27e05d7d289228d4296411143eb4a6f1e7/src/main/java/com/codeborne/selenide/commands/UploadFile.java#L35)
```java
 if (file.length > 1) {
      SelenideElement form = proxy.closest("form");
```
@asolntsev I don't know how correct to use `<input>` (with or without `<form>`), but this is how it's implemented in testapp, see [page.zip](https://github.com/selenide/selenide/files/3241301/page.zip)

p.s It's react js

**Comment by BorisOsipov** [comment]
Thanks for researching this! Will see

**Comment by asolntsev** [comment]
@dilook Can you share **a full example**? Your page.zip contains only one file (`page.html`) which refers to `reset.css`, `browser-check.js` etc. I cannot run this example. :(

The problem is that I can fix the issue, but I cannot check that my fix helps in your case.

**Comment by asolntsev** [comment]
Created a universal solution that should also fix this issue: https://github.com/selenide/selenide/pull/1188
