### ISSUE TITLE
Selenide should automatically take screenshot in case of AssertionError Junit(5)

### ISSUE THREAD

**Issue by Artem034** [selenide/selenide#945]
## The problem
Selenide (ScreenShotterExtention) don`t take screenshots in Junit5 with [Assertions class](https://junit.org/junit5/docs/5.4.0/api/org/junit/jupiter/api/Assertions.html) 

## Details
Similar fixed issue in junit4 functionality:
#79 #95  

## Code To Reproduce Issue [ Good To Have ]
`
@Test
    @DisplayName("Junit assert without screenshot")
    void googleTest()  {
        open("https://duckduckgo.com/");
        assertEquals("asd", "zxc");
    }

    @Test
    @DisplayName("Selenide assert and screenshot")
    void googleTest2() {
        open("https://www.google.com/");
        $("#q").shouldHave(Condition.text("fail test"));
    }
`

**Comment by Artem034** [comment]
Possible fix: https://github.com/Artem034/selenide/commit/bab82934ea30197235e26a24a3de78184caec4bf

**Comment by asolntsev** [comment]
I guess it was fixed in Selenide 5.2.4?
https://selenide.org/2019/06/20/selenide-5.2.4/
