### ISSUE TITLE
Create custom SelenideElement methods

### ISSUE THREAD

**Issue by firyx** [selenide/selenide#947]
Hello,

what is the best approach to create new/custom SelenideElement methods?

Thanks

**Comment by rosolko** [comment]
https://github.com/selenide/selenide/tree/master/statics/src/test/java/integration/customcommands

**Comment by shalak** [comment]
Hi @rosolko 

I'm wondering - how can I override some already existing command, but only for those elements that were obtained via `$_()`?

I have a custom dropdown list in my project that's not a native `select` and I would like to change the behavior of choosing the options. 

When I prepared `MySelenideComponent` with `selectOptionByValue(String... value)` and [I added the command](https://github.com/selenide/selenide/blob/0edfe07c1d71da8bd1b282730a201b3c772f5432/statics/src/test/java/integration/customcommands/MyFramework.java#L16), the new `selectOptionByValue` is called even on the regular `SelenideElement` objects, the ones that were obtained via `$()`.

**Comment by asolntsev** [comment]
@firyx Probably a simpler way is to use `$.execute`:

```java
  var turnCalendar = new Command<SelenideElement>() {...};
  var pickDate = new Command<SelenideElement>() {...};

  $("hiddenFileInput").execute(turnCalendar).execute(pickDate("03.09");
```

See https://selenide.org/2019/09/02/selenide-5.3.0/
