### ISSUE TITLE
Clear Browser Cookies issue in after method postcondition 

### ISSUE THREAD

**Issue by 1986stas** [selenide/selenide#951]
## The problem
Hello guys! Thank you for your hard work and selenide framework. It is a very helpful and useful. But I've got an issue/question which is related to 
Selenide.clearBrowserCookies();
Selenide.clearBrowserLocalStorage();
Previously when I was using those methods in 4.14.0 version of selenide, they cleared my cache and user was logged out, so that a user had to be logged in again before test and it was expected behavior. When I migrated to the latest version of selenide after running the first test those two methods in the @AfterMethod don't clear cache and a user is still logged in. Could you please clarify what exactly was changed or give me an advice? And what kind of info you do need to understand what is going on there?
Thanks in advance
## Tell us about your environment
* **Selenide Version: 5.2.3**
* **Chrome: 75**
* **Chromedriver: 75**
* **OS Version: Windows 8.1, Linux 16.04**

## Code To Reproduce Issue [ Good To Have ]
@BeforeMethod
    public void setUpPubDashPortlet() {
        publisherDashboardPage.login();
        publisherDashboardPage.scrollIntoPortletBody();
    }
 @AfterMethod
    public void tearDown() {
        Selenide.clearBrowserCookies();
        Selenide.clearBrowserLocalStorage();
    }

**Comment by 1986stas** [comment]
sorry, my bad)) everything works as expected))

**Comment by 1986stas** [comment]
sorry, my bad)) everything works as expected))

**Comment by BohdanKhomuk** [comment]
@1986stas How did you manage to solve this problem? Because @AfterMethod doesn't clear the cache and a user is still logged in
