### ISSUE TITLE
consider adding SelenideElement#type method as "fluent" version of sendKeys returning SelenideELement instead of void

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#953]
We used to use "$.setValue" a lot in common selenide examples, but I start to think, that from the testing perspective "by default" it is good to use some method that does not have "clear()" built in. 

This, for example, would "implicitly" find bugs, when field values do not have "empty" value by default, but should... By default such behavior is more natural, and less magical... 

We have such a method in Selenium - "sendKeys", but it is not "selenidish" enough, it returns void, so we can't write something like:

```
$(byName("q")).sendKeys("selenide").pressEnter();
```

So, what about adding the corresponding fluent version of the method, something like:

```
$(byName("q")).type("selenide").pressEnter();
```

Where `type` does not have `clear()` built in...

**Comment by SeleniumTestAB** [comment]
I am pretty sure that append() method does it

**Comment by yashaka** [comment]
you are right:) bind me)
