### ISSUE TITLE
Disable Screenshot generation temporarily in test

### ISSUE THREAD

**Issue by mseele** [selenide/selenide#957]
## The problem
I want to disable screenshot generation temporarily for the following statement (and enable it afterwards):
```
protected void waitForLoadingComplete(SelenideElement element) {
	try {
		element.waitUntil(appears, timeout(100, TimeUnit.MILLISECONDS))
		       .waitWhile(visible, timeout(5, TimeUnit.MINUTES));
	} catch (@SuppressWarnings("unused") ElementShould | ElementNotFound e) {
		// catch exception: if loading was too fast
	} catch (Throwable e) {
		e.printStackTrace();
	}
}
```

We wait here for loading bar - which will not be visible when loading is too fast.

I cannot disable "globally" via `Configuration.screenshots = false;` because we run our tests in parallel with JUnit5 (https://junit.org/junit5/docs/snapshot/user-guide/#writing-tests-parallel-execution).

I tried to disable via `WebDriverRunner.getSelenideDriver().config()` but there is no chance to edit the `config.screenshots()` value.

## Tell us about your environment
* **Selenide Version:** 5.2.5
* **Chrome\Firefox\IE Version:** Lastest
* **Browser Driver Version:** Latest
* **Selenium Version:** 3.141.59
* **OS Version:** Windows 10

## Code To Reproduce Issue [ Good To Have ]

```
protected void waitForLoadingComplete(SelenideElement element) {
	try {
		element.waitUntil(appears, timeout(100, TimeUnit.MILLISECONDS))
		       .waitWhile(visible, timeout(5, TimeUnit.MINUTES));
	} catch (@SuppressWarnings("unused") ElementShould | ElementNotFound e) {
		// catch exception: if loading was too fast
	} catch (Throwable e) {
		e.printStackTrace();
	}
}
```

**Comment by asolntsev** [comment]
@mseele Before we start implementing the feature, I want to warn you that it's not a good idea. :)

I see some disadvantages in your test:
1. If the element will never exist (loader is broken), your test will not detect it.
2. If selector of loader gets changed, your test will not detect it (and will be flaky). 

I recommend you to find another way to assure that the loading has been completed. Try to find some visual change that should happen as a result of loading. Probably 
* some header should appear, or 
* some disabled buttons should get enabled 
* etc. 

This is the only way to write a stable test.

**Comment by mseele** [comment]
Good point, but how then to test the loader?

**Comment by asolntsev** [comment]
@mseele I have a simple suggestion: don't test the loader! :)
Seriously, as we discussed before, it's just impossible to write a stable test for loader. I highly recommend to 
1. either testing loader logic with unit-tests (JavaScript code also can be covered by unit-tests)
2. or not testing loader at all. It's not a critical feature. If the loader gets broken, the business will still work.
