### ISSUE TITLE
Please add applicationName in Configuration

### ISSUE THREAD

**Issue by fbarbu15** [selenide/selenide#959]
I want to run parallel test with Grid on 2 docker chrome instances (image: selenium/node-chrome-debug), one that has 1920x1080 and one that has 1280x1024 screen size. From docker-compose file I can set different applicationNames for those instances. One has applicationName=chrome_1920 and one has applicationName=chrome_1280 and I can see in the grid this setting. 
The only thing I'm missing is to set from Selenide:
Configuration.applicationName = "chrome_1920";
and 
Configuration.applicationName = "chrome_1280";
I tried with:
Configuration.browserCapabilities.setCapability("applicationName", "chrome_1920");
But doesn't seem to work because of https://github.com/selenide/selenide/issues/676
Thanks

**Comment by rosolko** [comment]
@fbarbu15 We have `browserSize` configuration for browser size

**Comment by fbarbu15** [comment]
Yeah, I would use that also.
Configuration.browserSize = "1920x1080" and Configuration.browserSize = "1280x1024" but I have something like this:

	public SetupWebDriver(String browser, String seleniumHubUrl) throws MalformedURLException {
		this.browser = browser;
		if (this.browser.equalsIgnoreCase("chrome_1920")) {
			Configuration.browser = "chrome";
			Configuration.browserSize = "1920x1080";
			Configuration.applicationName = "chrome_1920";
		} else if (this.browser.equalsIgnoreCase("chrome_1280")) {
			Configuration.browser = "chrome";
			Configuration.browserSize = "1280x1024";
			Configuration.applicationName = "chrome_1280";
		}

		Configuration.remote = seleniumHubUrl;
		Configuration.screenshots = false;
		Configuration.savePageSource = false;

	}

And I have 2 docker container hubs that are running in grid with the following capabilities:
capabilities: Capabilities {applicationName: chrome_1920, browserName: chrome, maxInstances: 3, platform: LINUX, platformName: LINUX, seleniumProtocol: WebDriver, server:CONFIG_UUID: d66ca8e2-2479-4027-baa7-217...}
capabilities: Capabilities {applicationName: chrome_1280, browserName: chrome, maxInstances: 3, platform: LINUX, platformName: LINUX, seleniumProtocol: WebDriver, server:CONFIG_UUID: 3996b47d-2760-4343-8a08-82f...}
The first container has a screenSize/resolution (not browser size) of 1920x1080 and the second 1280x1024.

The reason I have this setup is to simulate different screen sizes and run tests in parallel for them.

Thanks

**Comment by rosolko** [comment]
@fbarbu15 Why don't you just run tests two times with different arguments?
You can pass them from build tool and not directly in a code

**Comment by fbarbu15** [comment]
@rosolko My desire was to run them in parallel, not two separate times. Found a work-around by using until #676 is fixed.
ChromeOptions chromeOptions = new ChromeOptions();
			chromeOptions.setCapability("applicationName", "chrome_1920");
			this.driver = new RemoteWebDriver(new URL(seleniumHubUrl), chromeOptions);
			this.driver.manage().window().setSize(new Dimension(1920, 1080));
			WebDriverRunner.setWebDriver(this.driver);

**Comment by rosolko** [comment]
@fbarbu15 This is a bad approach. Selenide allows to do that, but this is a bad approach. 
It's kind of trick or backdoor. And we don't implement a new property that extend this backdoor.
If you want to create two session use `SelenideDriver`.

**Comment by asolntsev** [comment]
@fbarbu15 Hi. Sorry for the delay. Sometimes I react slowly :)

Why don't we just fix #676 instead of adding new settings to `Configuration`?

About parallel running: I recommend to create 2 separate maven profiles (or gradle tasks). Then you can run them either in parallel or separately. Something like this:

```groovy
task chrome_1920(type: Test) {
  systemProperties['selenide.browser'] = 'chrome'
  systemProperties['selenide.browserSize'] = '1920x1080'
}

task chrome_1280(type: Test) {
  systemProperties['selenide.browser'] = 'chrome'
  systemProperties['selenide.browserSize'] = '1280x1024'
}
```

IMHO parallel run of tests is invented for other purpose: when you have a lot of tests, and want to run them simultaneously in the single configuration. Using my suggestion, you can run all your tests **inside `chrome_1920`** in parallel.

**Comment by fbarbu15** [comment]
Thanks @asolntsev for the answer. 
Unfortunately I cannot run test simultaneously on my project because they have a certain degree of dependency of each-other, test3 depends on test2 which depends on test1 and so on. 
The only parallelization that I hope to achieve is to run all of the test on multiple environments based on what customers are using most. In my case on chrome (two different screen sizes) and on firefox (one screen size). 

I managed to achieve this with the work-around I described in my last comment but was hoping to not need to use WebDriver.

Since then, I tried to simplify things and only run in parallel on chrome and firefox, without any screen size differences and it still doesn't work without using the workaround.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Grid Docker Test" verbose="3" parallel="tests"
	thread-count="10">
	<listeners>
		<listener class-name="listeners.Listeners"></listener>
	</listeners>
	<test name="Test Firefox">
		<parameter name="browser" value="firefox"></parameter>
		<classes>
			<class name="tests.GeneralTabTests">
			</class>
		</classes>
	</test>
	<test name="Test Chrome">
		<parameter name="browser" value="chrome"></parameter>
		<classes>
			<class name="tests.GeneralTabTests">
			</class>
		</classes>
	</test>
</suite> <!-- Suite -->
```


```
public class SetupWebDriver {

	private String browser;

	public SetupWebDriver(String browser, String seleniumHubUrl) throws MalformedURLException {
		this.browser = browser;
		if (this.browser.equalsIgnoreCase("firefox")) {
			Configuration.browser = "firefox";
		} else if (this.browser.equalsIgnoreCase("chrome")) {
			Configuration.browser = "chrome";
		} 
		
		Configuration.remote = seleniumHubUrl;
		Configuration.screenshots = false;
		Configuration.savePageSource = false;

	}

}
```

This setup runs tests twice on one containter (chrome or firefox taken at random it seems) but never both of them in parallel as I would expect.

If SetupWebDriver is changes like bellow it works as expected, tests are running in parralel (one time on chrome container and one time on firefox container):

```
public class SetupWebDriver {

	private WebDriver driver;
	private String browser;

	public SetupWebDriver(String browser, String seleniumHubUrl) throws MalformedURLException {
		this.browser = browser;
		if (this.browser.equalsIgnoreCase("firefox")) {
			FirefoxOptions firefoxOptions = new FirefoxOptions();
			this.driver = new RemoteWebDriver(new URL(seleniumHubUrl), firefoxOptions);
			WebDriverRunner.setWebDriver(this.driver);
		} else if (this.browser.equalsIgnoreCase("chrome")) {
			ChromeOptions chromeOptions = new ChromeOptions();
			this.driver = new RemoteWebDriver(new URL(seleniumHubUrl), chromeOptions);
			WebDriverRunner.setWebDriver(this.driver);
		} 

		Configuration.screenshots = false;
		Configuration.savePageSource = false;

	}

}
```

**Comment by asolntsev** [comment]
@fbarbu15 Yes, your first code cannot work because `Configuration.browser` is static variable. If you set it to `chrome` in one thread, it immediately applies to all other threads. 

Your second code works. Why you call it a workaround?

NB! I still recommend you to create 2 or 3 separate tasks/profiles (like `chrome_1920`, `chrome_1280`, `firefox`) and 2 or 3 separate jobs in jenkins (which call `mvn chrome_1920`, `mvn chrome_1280`, `mvn firefox` correspondingly). Then jenkins can run those jobs independently (simultaneously). It's much easier seatup.

**Comment by fbarbu15** [comment]
Oh I see. rosolko said in his last comment that this is a bad approach.
Will use it this way then and also try your suggestion with different maven profiles.
Thanks for the help!
