### ISSUE TITLE
Add check on Xpath's start to SelenideElement find methods 

### ISSUE THREAD

**Issue by rusakovStas** [selenide/selenide#963]
## The problem
When we use method find (ByXpath) or $/$$ on SelenideElement we expects that this method would be search element from this SelenideElement, but commonly it's not  true.  
For example: 

We have DOM: 
```
<A>
 <B>
   <C>
       <button>H!</button>
       <D> 
             <button>H!</button>
       </D>
    </C>
 </B>
 <B1> 
    <C>
             <button>H!</button>
    </C>
 </B1>
</A>

```
`$x("//B").findAll(By.xpath("//button"))  //should find "//B//button", but found just "//button"  `

To get "//B//button" we should specify Xpath like that 
`$x("//B").findAll(By.xpath(".//button")) `

To avoid that nonintuitive behavior i suggest to add check for Xpath's start to all find methods which working with Xpath to SelenideElement. That check will be throw exception with message like "You must start Xpath with '.' (dot symbol) when you want to find element from another." in case when search method on SelenideElement called with Xpath starts on no '.' (dot) symbols. 
Maybe, it make sense to add Configuration flag to turn off that behavior for backward compatibility and _people who wants strange_

**Comment by rusakovStas** [comment]
I think the example is not very successful... 
Should i specify all examples (on all methods) or it better to do in real tests?

**Comment by AlexKvasko** [comment]
You  should start your xpath from dot (.) if you want to find element in element
In Your example you should write $x("//B").findAll(By.xpath(".//button"))

**Comment by rusakovStas** [comment]
Agree. Thanks)

**Comment by asolntsev** [comment]
@rusakovStas I agree, we should add such a check. I don't think we need a `Configuration` flag because this behaviour is just never needed.

**Comment by SeleniumTestAB** [comment]
I suggest different approach, maybe the '.' should be injected at start of string if someone uses xpath? From what i see it needs to be added in find(), findAll() and maybe $ methods.

**Comment by asolntsev** [comment]
@SeleniumTestAB Probably it's a good idea. Hard to choose one: if Selenide should throw an exception or just add "." automatically. 

Probably exception is better because it forces people to learn XPath?

**Comment by AlexKvasko** [comment]
> Probably exception is better because it would force people to learn XPath?
Please do not do anything with this functionality. This is a part ofXPath functionality not Selenium or Selenide.

**Comment by rusakovStas** [comment]
@AlexKvasko 
Could you write an example of usage that functionality?

**Comment by AlexKvasko** [comment]
> @AlexKvasko
> Could you write an example of usage that functionality?

//a[contains(.,'link')]
.//*[@id='awesomeId']
Dot is not a part of selenium.

**Comment by rusakovStas** [comment]
I knew that) 
I mean usage of Xpath which starts on no dot symbol in case like:  
$("some element").$x("xpath which start on no dot symbol")

**Comment by asolntsev** [comment]
Implemented by PR https://github.com/selenide/selenide/pull/975 in Selenide 5.4.0
