### ISSUE TITLE
Add feature not re-searched SelenideElement

### ISSUE THREAD

**Issue by ddubtsov35** [selenide/selenide#964]
@asolntsev 

## Problem
Selenide not have feature set SelenideElement once, without re searched before every using. ElementsCollection may use .snapshot function for this. 

## Details
For example i have element in locators class:
SelenideElement getText() {
return $(By.id("text")).shouldBe(Condition.visible.because("Text should not visible")) 
}

In page class i wanna use it few time:
if(locatorsClass.getText().getValue().contains("aaa")){
locatorsClass.getText().click()
}

In this example element will be search thrice(In first time **.shouldBe**, in Second time **getValue()**, in third time **.click()**). 
May make method to SelenideElement class for example $(By.id(""))**.snapshot()** 
In this case for this example element will be search once.

**Comment by asolntsev** [comment]
@ddubtsov35 Selenide has such a method:
`WebElement snapshot = $("...").toWebElement();`

In this case, the element will not be re-searched.

But why you actually need it? I think it's a bad idea in most cases. In your sample, it's a bad idea to have "if ... then click" in test. Ideally, tests should not have any IFs.
