### ISSUE TITLE
Add option to change browser size during test execution

### ISSUE THREAD

**Issue by stevenmchaves** [selenide/selenide#965]
## The problem
Would like to change browser sizes within a test not just within a BeforeSuite. I am using Gauge.

**Comment by rosolko** [comment]
@stevenmchaves During test run you can access to selenium webdriver api.
Get a driver via: `WebDriver driver = WebDriverRunner.getWebDriver();`
Change size: `driver.manage().window().setSize(new Dimension(1024,768));`

**Comment by stevenmchaves** [comment]
Yea, i figured it out like 30 minutes i posted. Thanks.
