### ISSUE TITLE
inverted reason in error messages and general readability issues

### ISSUE THREAD

**Issue by yashaka** [selenide/selenide#967]
The following code:

```java
        open("http://todomvc.com/examples/emberjs");
        $("#new-todo").append("a").pressEnter();
        $$("#task-list>li").findBy(exactText("a")).doubleClick();
```

fails with:

```
Element not found {#task-list>li}
Expected: visible

Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
Timeout: 4 s.
Caused by: Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'
Screenshot: null
Timeout: 0 ms.
	at ...
```

To my understanding, it states the "reason" and "result" direction incorrectly. 
Our goal was to find `#task-list>li.findBy(exact text 'b')` but we failed, because the search stopped at `#task-list>li`. This means that the error should be either:

*option 1*
```
Element not found {#task-list>li}
Expected: visible

Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
Timeout: 4 s.
Causes: Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'
Screenshot: null
Timeout: 0 ms.
	at ...
```

or

*option 2*
```
Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'

Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
Timeout: 4 s.
Caused by: Element not found {#task-list>li}
Expected: visible
Screenshot: null
Timeout: 0 ms.
	at ...
```

Regardless of which option to choose, probably both should be cleared from redundant details:

*option 1*
```
Element not found {#task-list>li}
Expected: visible

Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
Timeout: 4 s.
Causes: Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'
	at ...
```

or

*option 2*
```
Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'

Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
Timeout: 4 s.
Caused by: Element not found {#task-list>li}
Expected: visible
	at ...
```

And probably I would restructure some info for the same purpose of clearness and readability (if this is possible technically according to current implementation):

*option 1*
```
Element not found {#task-list>li}
Expected: visible

Causes: Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'

Timeout: 4 s.
Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
	at ...
```

or

*option 2*
```
Element not found {#task-list>li.findBy(exact text 'b')}
Expected: exact text 'b'

Caused by: Element not found {#task-list>li}
Expected: visible

Timeout: 4 s.
Screenshot: file:/.../1566024696836.0.png
Page source: file:/.../1566024696836.0.html
	at ...
```

Ideas used in final examples:
* screenshot and page source are pretty verbose and less used... So I would put them at the end of the message
* Timeout is concise and better to see before bulky screenshot and page source... but yet less useful if comparing to locators and expected conditions... 

Now regarding option 1 vs option 2. 

* option 2
  * pros
    * when we look at the error message, the first thing we will see - is the "whole locator". Hence it will be easier to connect this info with the exact line in code because they will be more or less the same: `{#task-list>li.findBy(exact text 'b')}` = `$$("#task-list>li").findBy(exactText("a"))`
      * This will make it faster to understand the context... Like: 1 first, understand context (WHEN from BDD) 2 second - understand the cause (THEN from BDD)
* option 1
  * pros
    * for those who are pretty quick-witted it will be much faster at one sight to get the actual reason for the failure: we start in the message from the final cause: {#task-list>li} 

Other ideas:
* I would put in message the information about "what action we were trying to do with this locator" ... like "double-click" in our case...

**Comment by asolntsev** [comment]
fixed by https://github.com/selenide/selenide/pull/1189
