### ISSUE TITLE
fastSetValue mode (= via javascript) doesn't work in frames / iframes

### ISSUE THREAD

**Issue by vinogradoff** [selenide/selenide#974]
Schematic reproduction:
```
<body>
  <input id="a" type="text">
  <frame name="f">
    <body>
     <input id="b" type="text">
    </body>
  </frame> 
</body>

Configuration.fastSetValue=true;
$("#a").setValue("a"); // sets value
switchTo().frame("f");
$("#b").setValue("b"); // doesn't set value

```

**Comment by dstekanov** [comment]
Hi @vinogradoff,

I tried to reproduce the issue with iframe and frameset/frame but couldn't. 

I tried the following cases:

```
Configuration.fastSetValue = true;
switchTo().frame("frame");
$("#input").setValue("value");
```

and 

```
switchTo().frame("frame");
Configuration.fastSetValue = true;
$("#input").setValue("value");
```

Could you please re-check this issue on your side or provide a public page where you can reproduce it?

**Comment by ChrisZcu** [comment]
Hi, @vinogradoff, I want to reproduce it, but I use iframe with "src" tag, and there is no problem to set the valus, so could reproduce the issue or check your code?
Thankful if you could respons early!

**Comment by asolntsev** [comment]
feel free to reopen the issue when received new information.
