### ISSUE TITLE
Add support for Edge Dev (Chromium based)

### ISSUE THREAD

**Issue by mseele** [selenide/selenide#978]
## The problem
Add Support for Edge Dev (Chromium based) in com.codeborne.selenide.Browsers

WebDriverManager already supports it: https://github.com/bonigarcia/webdrivermanager/issues/337

## Tell us about your environment
* **Selenide Version:** 5.3.1
* **Selenium Version:** 3.141.59
* **OS Version:** Windows 10

**Comment by asolntsev** [comment]
@mseele Good point! Let's do it.

**Comment by asolntsev** [comment]
@mseele I discovered that Edge browser is actually supported in Selenide from year 2016.
See commit https://github.com/selenide/selenide/commit/036711f833f4722fbd4a98b3d967fec88ad61e7d

Line `WebDriverManager.edgedriver().setup();` is also executed inside Selenide. 

Please specify more details what exactly needs to be done, and we will re-open the issue.

**Comment by mseele** [comment]
I'm talking about edge driver (chromium): https://www.microsoft.com/en-us/edge

**Comment by asolntsev** [comment]
@mseele I just tried it, and Selenide works perfectly with chromium-based edge driver (I personally tried it on MacOS).

The only problem is that WebDriverManager cannot detect version of installed Edge browser on MacOS, so you need to set it manually:

```java
WebDriverManager.edgedriver().version("80.0.361.66").setup();
```

**Comment by mseele** [comment]
great to hear. thank you
