### ISSUE TITLE
Assertion mode problem

### ISSUE THREAD

**Issue by IIIPARAZITIII** [selenide/selenide#981]
## The problem
Assertion mode refused to work.

## Details
When I describe BaseTest as some kind of logic and behavior with the @BeforeAll and @AfterAll methods that must be done before the start of the test, the script crashes on the very first method ... click (); ... both in the method with the annotation @BeforeAll and @AfterAll (screenshot with an example below).
![BrokenBaseTest](https://user-images.githubusercontent.com/54977796/66029836-b7f07900-e508-11e9-9607-2e4f34139777.png)
But if you transfer these steps to the method with the @Test annotation in this class or to the methods of the classes that BaseTest will hear ... then everything starts to work and with all the methods described in the documentation (screenshot with an example below).
![WorkedBaseTest](https://user-images.githubusercontent.com/54977796/66029905-e1110980-e508-11e9-994e-1128694a46da.png)
The problem is solved, I hope I clearly described the essence. It is not clear only why in the first case Sekenide refuses to work and throws an exception.

## Tell us about your environment
* **Selenide Version:** 5.6.1
* **Chrome\Firefox\IE Version:** latest
* **Browser Driver Version:** latest
* **Selenium Version:** was chosen by Selenide
* **OS Version:** Windows 10

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.

**Comment by asolntsev** [comment]
@IIIPARAZITIII Could you please share a code as text, not a screenshot?
Or even better, could you create a small project on github which would reproduce the problem?

**Comment by IIIPARAZITIII** [comment]
Of course, I can. Take it [(https://github.com/IIIPARAZITIII/selenide-assertion-mode-problem)].
And as I understand this problem appears only with static methodы BeforAll and AfterAll.

**Comment by asolntsev** [comment]
@IIIPARAZITIII Thank you, now I could reproduce the problem.

It's an interesting issue. The problem is that you call `userSteps.logIn()` in `@BeforeAll` method, but Selenide's `SoftAssertsExtension` only supports soft checks between `@BeforeEach` and `@AfterEach` methods. 

@rosolko What do you think, should we fix `SoftAssertsExtension` to bind `SoftAssertListener` also in  `@BeforeAll` method?

**Comment by IIIPARAZITIII** [comment]
@asolntsev I'm glad to help, but I'm sure that this problem will be the same in the AfterAll method too. You can model it if you will use the methods from the variable userSteps in an @AfterAll method only.

**Comment by Litemn** [comment]
By the way junit 5 in concurrent mode `beforeAll` `before` and `test` might execute in different threads and storing `com.codeborne.selenide.logevents.SelenideLogger#listeners` in thread local may broke work of soft assertions. I don't look deep in selenide code - maybe there already present some solution.

**Comment by asolntsev** [comment]
@litemn good point. No, I think we don't have a solution yet.

**Comment by asolntsev** [comment]
BTW We have a duplicate issue: https://github.com/selenide/selenide/issues/1070
