### ISSUE TITLE
ArrayIndexOutOfBoundsException from LastCollectionElement

### ISSUE THREAD

**Issue by JoakimBruce** [selenide/selenide#991]
## The problem
When trying to find elements in the last element of an empty collection, an ArrayIndexOutOfBoundsException is thrown. It would be more helpful if a Selenide specific exception is thrown instead (e.g an ElementNotFound exception).

## Details
When running our automatic tests, we sometimes have flaky behavior where trying to find a collection of elements unexpectedly yields an empty collection (the cause of which is not really relevant here). In one instance, we tried to get the last element of such a collection, and find an ElementsCollection from said last element. We then got the following rather confusing stack trace:
>java.lang.ArrayIndexOutOfBoundsException: -1
>	at java.util.ArrayList.elementData(ArrayList.java:422) ~[na:1.8.0_201]
>	at java.util.ArrayList.get(ArrayList.java:435) ~[na:1.8.0_201]
>	at com.codeborne.selenide.impl.LastCollectionElement.lastElementOf(LastCollectionElement.java:38) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.impl.LastCollectionElement.getWebElement(LastCollectionElement.java:34) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.impl.SelenideElementProxy.dispatchAndRetry(SelenideElementProxy.java:102) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.impl.SelenideElementProxy.invoke(SelenideElementProxy.java:65) ~[selenide-5.0.0.jar:5.0.0]
>	at com.sun.proxy.$Proxy11.findElements(Unknown Source) ~[na:na]
>	at com.codeborne.selenide.impl.WebElementSelector.findElements(WebElementSelector.java:37) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.impl.BySelectorCollection.getElements(BySelectorCollection.java:30) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.ElementsCollection.waitUntil(ElementsCollection.java:135) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.ElementsCollection.should(ElementsCollection.java:108) ~[selenide-5.0.0.jar:5.0.0]
>	at com.codeborne.selenide.ElementsCollection.shouldHave(ElementsCollection.java:86) ~[selenide-5.0.0.jar:5.0.0]
>	[a shouldHave(size(n)) call on an elementsCollection.last().findAll(...)]
>	(...)

A workaround is to add a check of the first collection so that we fail if it is empty before getting the last element from it, but it is not apparent that that is the solution when this error is encountered. For contrast, when trying to find a SelenideElement in the last element of an empty collection, an ElementNotFound exception is thrown.

## Tell us about your environment
* **Selenide Version:** 5.0.0
* **Chrome\Firefox\IE Version:** N/A
* **Browser Driver Version:** N/A
* **Selenium Version:** 3.14.0 (Java)
* **OS Version:** N/A

## Code To Reproduce Issue [ Good To Have ]
```java
// Yields an ElementNotFound exception
$$(".no-such-class").last().$(".neither-is-this").should(exist);
// Yields an ArrayIndexOutOfBoundsException
$$(".no-such-class").last().$$(".neither-is-this").shouldHave();
```

**Comment by asolntsev** [comment]
Fixed in Selenide 5.6.2 by https://github.com/selenide/selenide/pull/1043
