### ISSUE TITLE
Add method to check content of ":before" and other pseudo elements

### ISSUE THREAD

**Issue by asolntsev** [selenide/selenide#994]
Here are some examples how to get content of pseudo elements by JavaScript call:

https://stackoverflow.com/questions/28244911/selenium-webdriver-get-text-from-css-property-content-on-a-before-pseudo-ele/28265738#28265738

**Comment by Denysss** [comment]
@asolntsev 
How do you see the public API?
As a new command:
```
$("#myWebElement").pseudoContant(":before");
$("#myWebElement").pseudoBefore();
$("#myWebElement").getPseudoValue(":before", "content");
```
As an extension of getAttribute:
```
$("#myWebElement").getAttribute(":after");
```
As for me, `getPseudoValue(String pseudoElementName, String propertyName)` is the most universal solution

**Comment by asolntsev** [comment]
@Denysss I don't know yet. But what I definitely prefer is to have "should" methods, not "get" methods. 

Something like 
* `$("#myWebElement").shouldHave(pseudoAttribute(":before", "blah"))` or
* `$("#myWebElement").shouldHave(attribute(":before", "blah"))`

**Comment by asolntsev** [comment]
implemented in https://github.com/selenide/selenide/pull/1045
