### ISSUE TITLE
Feature request: add Condition attributeContainsValue (java.lang.String attributeName, java.lang.String matchedExpectedAttributeValue)

### ISSUE THREAD

**Issue by sergeyrybakin** [selenide/selenide#996]
Feature request
## The problem
Condition attribute requires **exact** text of attribute value.
Sample: $("#mydiv").shouldHave(attribute("fileId", "12345"));

It would be great to have Condition to verify attribute by matched text:
Example:
attribute "field" can contains value: "Job12345", "12345 job", etc. Where "12345" - is matched text.
$("#mydiv").shouldHave(attributeContainsValue("fileId", "12345"));

## My environment
* **Selenide Version:5.3.1
* **Chrome\Firefox\IE Version: 77.0.3865.120\69.0.2
* **Browser Driver Version:
* **Selenium Version:3.141.59
* **OS Version:Ubuntu 18.04.3 LTS

## Code To Reproduce Issue [ Good To Have ]
Please remember that with sample code it's easier to reproduce the bug.
It's not good example, but:
http://the-internet.herokuapp.com/dynamic_content?with_content=static

$("content img").shouldHave(attributeContainsValue("src", "/img/avatars/Original-Facebook-Geek-Profile-Avatar-"));

**Comment by rosolko** [comment]
@sergeyrybakin Thanks for a report!

 In selenide we trying to hold only few _basic_ conditions. 
**But!** You can easily implement this condition by your own - just need to implement `Condition`.
Also you can find examples on our [wiki](https://github.com/selenide/selenide/wiki/Community-conditions) page.

Is this message helps you?
Write back please with answer and extend our wiki with you condition implementation.
Feel free to close this issue if no question left.

Thanks!

**Comment by asolntsev** [comment]
@rosolko What about overloaded condition `attribute` with regexp parameter?

Something like this:

```java
$("#mydiv").shouldHave(attribute(Pattern.compile(".*12345.*")));

// or

$("#mydiv").shouldHave(attributeMathching(".*12345.*"));
```
